var searchData=
[
  ['cabxpyax',['cabxpyAx',['../structquda_1_1cabxpy_ax.html',1,'quda']]],
  ['cabxpyaxnorm',['cabxpyaxnorm',['../structquda_1_1cabxpyaxnorm.html',1,'quda']]],
  ['caxpby',['caxpby',['../structquda_1_1caxpby.html',1,'quda']]],
  ['caxpbypczpw',['caxpbypczpw',['../structquda_1_1caxpbypczpw.html',1,'quda']]],
  ['caxpbypz',['caxpbypz',['../structquda_1_1caxpbypz.html',1,'quda']]],
  ['caxpbypzymbw',['caxpbypzYmbw',['../structquda_1_1caxpbypz_ymbw.html',1,'quda']]],
  ['caxpbypzymbwcdotproductuynormy',['caxpbypzYmbwcDotProductUYNormY',['../structquda_1_1caxpbypz_ymbwc_dot_product_u_y_norm_y.html',1,'quda']]],
  ['caxpy',['caxpy',['../structquda_1_1caxpy.html',1,'quda']]],
  ['caxpydotzy',['caxpydotzy',['../structquda_1_1caxpydotzy.html',1,'quda']]],
  ['caxpynorm2',['caxpyNorm2',['../structquda_1_1caxpy_norm2.html',1,'quda']]],
  ['caxpyxmaz',['caxpyxmaz',['../structquda_1_1caxpyxmaz.html',1,'quda']]],
  ['caxpyxmaznormx',['caxpyxmaznormx',['../structquda_1_1caxpyxmaznormx.html',1,'quda']]],
  ['cdot',['Cdot',['../structquda_1_1_cdot.html',1,'quda']]],
  ['cdotnorma',['CdotNormA',['../structquda_1_1_cdot_norm_a.html',1,'quda']]],
  ['cdotnormb',['CdotNormB',['../structquda_1_1_cdot_norm_b.html',1,'quda']]],
  ['cg',['CG',['../classquda_1_1_c_g.html',1,'quda']]],
  ['clovercuda',['CloverCuda',['../classquda_1_1_clover_cuda.html',1,'quda']]],
  ['cloverdslashcuda',['CloverDslashCuda',['../classquda_1_1_clover_dslash_cuda.html',1,'quda']]],
  ['cloverfield',['CloverField',['../classquda_1_1_clover_field.html',1,'quda']]],
  ['cloverfieldparam',['CloverFieldParam',['../structquda_1_1_clover_field_param.html',1,'quda']]],
  ['cloverparam',['CloverParam',['../structquda_1_1_clover_param.html',1,'quda']]],
  ['coeffsign',['CoeffSign',['../structquda_1_1fermion__force_1_1_coeff_sign.html',1,'quda::fermion_force']]],
  ['coeffsign_3c_200_2c_200_20_3e',['CoeffSign&lt; 0, 0 &gt;',['../structquda_1_1fermion__force_1_1_coeff_sign_3_010_00_010_01_4.html',1,'quda::fermion_force']]],
  ['coeffsign_3c_200_2c_201_20_3e',['CoeffSign&lt; 0, 1 &gt;',['../structquda_1_1fermion__force_1_1_coeff_sign_3_010_00_011_01_4.html',1,'quda::fermion_force']]],
  ['coeffsign_3c_201_2c_201_20_3e',['CoeffSign&lt; 1, 1 &gt;',['../structquda_1_1fermion__force_1_1_coeff_sign_3_011_00_011_01_4.html',1,'quda::fermion_force']]],
  ['colormatrix',['ColorMatrix',['../struct_color_matrix.html',1,'']]],
  ['colorspinorfield',['ColorSpinorField',['../classquda_1_1_color_spinor_field.html',1,'quda']]],
  ['colorspinorfieldorder',['ColorSpinorFieldOrder',['../class_color_spinor_field_order.html',1,'']]],
  ['colorspinorfieldorder',['ColorSpinorFieldOrder',['../classquda_1_1_color_spinor_field_order.html',1,'quda']]],
  ['colorspinorfieldorder_3c_20double_20_3e',['ColorSpinorFieldOrder&lt; double &gt;',['../classquda_1_1_color_spinor_field_order.html',1,'quda']]],
  ['colorspinorfieldorder_3c_20float_20_3e',['ColorSpinorFieldOrder&lt; float &gt;',['../classquda_1_1_color_spinor_field_order.html',1,'quda']]],
  ['colorspinorparam',['ColorSpinorParam',['../classquda_1_1_color_spinor_param.html',1,'quda']]],
  ['completeforce',['CompleteForce',['../classquda_1_1fermion__force_1_1_complete_force.html',1,'quda::fermion_force']]],
  ['complex',['complex',['../structcomplex.html',1,'']]],
  ['complextypeid',['ComplexTypeId',['../struct_complex_type_id.html',1,'']]],
  ['complextypeid_3c_20double_20_3e',['ComplexTypeId&lt; double &gt;',['../structquda_1_1_complex_type_id_3_01double_01_4.html',1,'quda']]],
  ['complextypeid_3c_20float_20_3e',['ComplexTypeId&lt; float &gt;',['../structquda_1_1_complex_type_id_3_01float_01_4.html',1,'quda']]],
  ['copycuda',['CopyCuda',['../classquda_1_1copy_1_1_copy_cuda.html',1,'quda::copy']]],
  ['cpucloverfield',['cpuCloverField',['../classquda_1_1cpu_clover_field.html',1,'quda']]],
  ['cpucolorspinorfield',['cpuColorSpinorField',['../classquda_1_1cpu_color_spinor_field.html',1,'quda']]],
  ['cpugaugefield',['cpuGaugeField',['../classquda_1_1cpu_gauge_field.html',1,'quda']]],
  ['cudacloverfield',['cudaCloverField',['../classquda_1_1cuda_clover_field.html',1,'quda']]],
  ['cudacolorspinorfield',['cudaColorSpinorField',['../classquda_1_1cuda_color_spinor_field.html',1,'quda']]],
  ['cudagaugefield',['cudaGaugeField',['../classquda_1_1cuda_gauge_field.html',1,'quda']]],
  ['cxpaypbz',['cxpaypbz',['../structquda_1_1cxpaypbz.html',1,'quda']]]
];
