var searchData=
[
  ['s',['S',['../structquda_1_1clover_1_1_s.html',1,'quda::clover::S&lt; real, length &gt;'],['../structquda_1_1colorspinor_1_1_s.html',1,'quda::colorspinor::S&lt; real, length &gt;'],['../structquda_1_1gauge_1_1_s.html',1,'quda::gauge::S&lt; real, length &gt;']]],
  ['scalar',['scalar',['../structquda_1_1scalar.html',1,'quda']]],
  ['scalar_3c_20char_20_3e',['scalar&lt; char &gt;',['../structquda_1_1scalar_3_01char_01_4.html',1,'quda']]],
  ['scalar_3c_20char2_20_3e',['scalar&lt; char2 &gt;',['../structquda_1_1scalar_3_01char2_01_4.html',1,'quda']]],
  ['scalar_3c_20char3_20_3e',['scalar&lt; char3 &gt;',['../structquda_1_1scalar_3_01char3_01_4.html',1,'quda']]],
  ['scalar_3c_20char4_20_3e',['scalar&lt; char4 &gt;',['../structquda_1_1scalar_3_01char4_01_4.html',1,'quda']]],
  ['scalar_3c_20double_20_3e',['scalar&lt; double &gt;',['../structquda_1_1scalar_3_01double_01_4.html',1,'quda']]],
  ['scalar_3c_20double2_20_3e',['scalar&lt; double2 &gt;',['../structquda_1_1scalar_3_01double2_01_4.html',1,'quda']]],
  ['scalar_3c_20double3_20_3e',['scalar&lt; double3 &gt;',['../structquda_1_1scalar_3_01double3_01_4.html',1,'quda']]],
  ['scalar_3c_20double4_20_3e',['scalar&lt; double4 &gt;',['../structquda_1_1scalar_3_01double4_01_4.html',1,'quda']]],
  ['scalar_3c_20float_20_3e',['scalar&lt; float &gt;',['../structquda_1_1scalar_3_01float_01_4.html',1,'quda']]],
  ['scalar_3c_20float2_20_3e',['scalar&lt; float2 &gt;',['../structquda_1_1scalar_3_01float2_01_4.html',1,'quda::scalar&lt; float2 &gt;'],['../structquda_1_1scalar.html',1,'quda::scalar&lt; Float2 &gt;']]],
  ['scalar_3c_20float3_20_3e',['scalar&lt; float3 &gt;',['../structquda_1_1scalar_3_01float3_01_4.html',1,'quda']]],
  ['scalar_3c_20float4_20_3e',['scalar&lt; float4 &gt;',['../structquda_1_1scalar_3_01float4_01_4.html',1,'quda']]],
  ['scalar_3c_20short_20_3e',['scalar&lt; short &gt;',['../structquda_1_1scalar_3_01short_01_4.html',1,'quda']]],
  ['scalar_3c_20short2_20_3e',['scalar&lt; short2 &gt;',['../structquda_1_1scalar_3_01short2_01_4.html',1,'quda']]],
  ['scalar_3c_20short3_20_3e',['scalar&lt; short3 &gt;',['../structquda_1_1scalar_3_01short3_01_4.html',1,'quda']]],
  ['scalar_3c_20short4_20_3e',['scalar&lt; short4 &gt;',['../structquda_1_1scalar_3_01short4_01_4.html',1,'quda']]],
  ['sd',['SD',['../classquda_1_1_s_d.html',1,'quda']]],
  ['shareddslashcuda',['SharedDslashCuda',['../class_shared_dslash_cuda.html',1,'']]],
  ['sharedmemory',['SharedMemory',['../structquda_1_1_shared_memory.html',1,'quda']]],
  ['shiftcolorspinorfield',['ShiftColorSpinorField',['../classquda_1_1_shift_color_spinor_field.html',1,'quda']]],
  ['shiftcolorspinorfieldarg',['ShiftColorSpinorFieldArg',['../structquda_1_1_shift_color_spinor_field_arg.html',1,'quda']]],
  ['shiftupdate',['ShiftUpdate',['../classquda_1_1_shift_update.html',1,'quda']]],
  ['sign',['Sign',['../struct_sign.html',1,'']]],
  ['sign_3c_201_20_3e',['Sign&lt; 1 &gt;',['../struct_sign_3_011_01_4.html',1,'']]],
  ['simplebicgstab',['SimpleBiCGstab',['../classquda_1_1_simple_bi_c_gstab.html',1,'quda']]],
  ['solver',['Solver',['../classquda_1_1_solver.html',1,'quda']]],
  ['solverparam',['SolverParam',['../structquda_1_1_solver_param.html',1,'quda']]],
  ['sortedevals',['SortedEvals',['../structquda_1_1_sorted_evals.html',1,'quda']]],
  ['spacecolorspinororder',['SpaceColorSpinorOrder',['../structquda_1_1colorspinor_1_1_space_color_spinor_order.html',1,'quda::colorspinor']]],
  ['spacespinorcolororder',['SpaceSpinorColorOrder',['../structquda_1_1colorspinor_1_1_space_spinor_color_order.html',1,'quda::colorspinor']]],
  ['spin_5fmapper',['spin_mapper',['../structquda_1_1spin__mapper.html',1,'quda']]],
  ['spin_5forder_5fmapper',['spin_order_mapper',['../structquda_1_1spin__order__mapper.html',1,'quda']]],
  ['spin_5forder_5fmapper_3c_201_2c_20quda_5ffloat4_5ffield_5forder_20_3e',['spin_order_mapper&lt; 1, QUDA_FLOAT4_FIELD_ORDER &gt;',['../structquda_1_1spin__order__mapper_3_011_00_01_q_u_d_a___f_l_o_a_t4___f_i_e_l_d___o_r_d_e_r_01_4.html',1,'quda']]],
  ['spin_5forder_5fmapper_3c_202_2c_20quda_5ffloat4_5ffield_5forder_20_3e',['spin_order_mapper&lt; 2, QUDA_FLOAT4_FIELD_ORDER &gt;',['../structquda_1_1spin__order__mapper_3_012_00_01_q_u_d_a___f_l_o_a_t4___f_i_e_l_d___o_r_d_e_r_01_4.html',1,'quda']]],
  ['spinor',['Spinor',['../class_spinor.html',1,'']]],
  ['spinornoise',['SpinorNoise',['../classquda_1_1_spinor_noise.html',1,'quda']]],
  ['spinortexture',['SpinorTexture',['../class_spinor_texture.html',1,'']]],
  ['square_5f',['square_',['../structquda_1_1clover_1_1square__.html',1,'quda::clover::square_&lt; ReduceType, Float &gt;'],['../structquda_1_1colorspinor_1_1square__.html',1,'quda::colorspinor::square_&lt; ReduceType, Float &gt;'],['../structquda_1_1gauge_1_1square__.html',1,'quda::gauge::square_&lt; ReduceType, Float &gt;']]],
  ['square_5f_3c_20reducetype_2c_20char_20_3e',['square_&lt; ReduceType, char &gt;',['../structquda_1_1colorspinor_1_1square___3_01_reduce_type_00_01char_01_4.html',1,'quda::colorspinor::square_&lt; ReduceType, char &gt;'],['../structquda_1_1gauge_1_1square___3_01_reduce_type_00_01char_01_4.html',1,'quda::gauge::square_&lt; ReduceType, char &gt;']]],
  ['square_5f_3c_20reducetype_2c_20int_20_3e',['square_&lt; ReduceType, int &gt;',['../structquda_1_1gauge_1_1square___3_01_reduce_type_00_01int_01_4.html',1,'quda::gauge']]],
  ['square_5f_3c_20reducetype_2c_20short_20_3e',['square_&lt; ReduceType, short &gt;',['../structquda_1_1colorspinor_1_1square___3_01_reduce_type_00_01short_01_4.html',1,'quda::colorspinor::square_&lt; ReduceType, short &gt;'],['../structquda_1_1gauge_1_1square___3_01_reduce_type_00_01short_01_4.html',1,'quda::gauge::square_&lt; ReduceType, short &gt;']]],
  ['staggered',['Staggered',['../classquda_1_1_staggered.html',1,'quda']]],
  ['staggeredapply',['StaggeredApply',['../structquda_1_1_staggered_apply.html',1,'quda']]],
  ['staggeredarg',['StaggeredArg',['../structquda_1_1_staggered_arg.html',1,'quda']]],
  ['staggereddslashtest',['StaggeredDslashTest',['../class_staggered_dslash_test.html',1,'']]],
  ['staggeredlaunch',['StaggeredLaunch',['../structquda_1_1_staggered_launch.html',1,'quda']]],
  ['staggeredreconstruct',['StaggeredReconstruct',['../structquda_1_1_staggered_reconstruct.html',1,'quda']]],
  ['su3_5fmatrix',['su3_matrix',['../structsu3__matrix.html',1,'']]],
  ['su3_5fvector',['su3_vector',['../structsu3__vector.html',1,'']]]
];
