var searchData=
[
  ['fanti_5fhermitmat',['fanti_hermitmat',['../structfanti__hermitmat.html',1,'']]],
  ['fcomplex',['fcomplex',['../structfcomplex.html',1,'']]],
  ['fhalf_5fwilson_5fvector',['fhalf_wilson_vector',['../structfhalf__wilson__vector.html',1,'']]],
  ['fieldorder',['FieldOrder',['../structquda_1_1clover_1_1_field_order.html',1,'quda::clover::FieldOrder&lt; Float, nColor, nSpin, order &gt;'],['../structquda_1_1gauge_1_1_field_order.html',1,'quda::gauge::FieldOrder&lt; Float, nColor, nSpinCoarse, order, native_ghost, storeFloat, use_tex &gt;']]],
  ['fieldorder_5fwrapper',['fieldorder_wrapper',['../structquda_1_1colorspinor_1_1fieldorder__wrapper.html',1,'quda::colorspinor::fieldorder_wrapper&lt; Float, storeFloat &gt;'],['../structquda_1_1gauge_1_1fieldorder__wrapper.html',1,'quda::gauge::fieldorder_wrapper&lt; Float, storeFloat &gt;']]],
  ['fieldordercb',['FieldOrderCB',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fieldordercb_3c_20float_2c_20coarsespin_2c_20coarsecolor_2c_201_2c_20csorder_2c_20float_2c_20ghostfloat_20_3e',['FieldOrderCB&lt; Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat &gt;',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fieldordercb_3c_20float_2c_20coarsespin_2c_20coarsecolor_2c_201_2c_20order_20_3e',['FieldOrderCB&lt; Float, coarseSpin, coarseColor, 1, order &gt;',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fieldordercb_3c_20float_2c_20finespin_2c_20finecolor_2c_201_2c_20order_20_3e',['FieldOrderCB&lt; Float, fineSpin, fineColor, 1, order &gt;',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fieldordercb_3c_20float_2c_20finespin_2c_20finecolor_2c_20coarsecolor_2c_20order_2c_20vfloat_20_3e',['FieldOrderCB&lt; Float, fineSpin, fineColor, coarseColor, order, vFloat &gt;',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fieldordercb_3c_20real_2c_20ns_2c_20nc_2c_201_2c_20order_20_3e',['FieldOrderCB&lt; real, Ns, Nc, 1, order &gt;',['../classquda_1_1colorspinor_1_1_field_order_c_b.html',1,'quda::colorspinor']]],
  ['fixedinvmaxvalue',['fixedInvMaxValue',['../structquda_1_1fixed_inv_max_value.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20char_20_3e',['fixedInvMaxValue&lt; char &gt;',['../structquda_1_1fixed_inv_max_value_3_01char_01_4.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20char2_20_3e',['fixedInvMaxValue&lt; char2 &gt;',['../structquda_1_1fixed_inv_max_value_3_01char2_01_4.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20char4_20_3e',['fixedInvMaxValue&lt; char4 &gt;',['../structquda_1_1fixed_inv_max_value_3_01char4_01_4.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20short_20_3e',['fixedInvMaxValue&lt; short &gt;',['../structquda_1_1fixed_inv_max_value_3_01short_01_4.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20short2_20_3e',['fixedInvMaxValue&lt; short2 &gt;',['../structquda_1_1fixed_inv_max_value_3_01short2_01_4.html',1,'quda']]],
  ['fixedinvmaxvalue_3c_20short4_20_3e',['fixedInvMaxValue&lt; short4 &gt;',['../structquda_1_1fixed_inv_max_value_3_01short4_01_4.html',1,'quda']]],
  ['fixedmaxvalue',['fixedMaxValue',['../structquda_1_1fixed_max_value.html',1,'quda']]],
  ['fixedmaxvalue_3c_20char_20_3e',['fixedMaxValue&lt; char &gt;',['../structquda_1_1fixed_max_value_3_01char_01_4.html',1,'quda']]],
  ['fixedmaxvalue_3c_20char2_20_3e',['fixedMaxValue&lt; char2 &gt;',['../structquda_1_1fixed_max_value_3_01char2_01_4.html',1,'quda']]],
  ['fixedmaxvalue_3c_20char4_20_3e',['fixedMaxValue&lt; char4 &gt;',['../structquda_1_1fixed_max_value_3_01char4_01_4.html',1,'quda']]],
  ['fixedmaxvalue_3c_20short_20_3e',['fixedMaxValue&lt; short &gt;',['../structquda_1_1fixed_max_value_3_01short_01_4.html',1,'quda']]],
  ['fixedmaxvalue_3c_20short2_20_3e',['fixedMaxValue&lt; short2 &gt;',['../structquda_1_1fixed_max_value_3_01short2_01_4.html',1,'quda']]],
  ['fixedmaxvalue_3c_20short4_20_3e',['fixedMaxValue&lt; short4 &gt;',['../structquda_1_1fixed_max_value_3_01short4_01_4.html',1,'quda']]],
  ['float4_5fprecision_5fmapper',['float4_precision_mapper',['../structquda_1_1float4__precision__mapper.html',1,'quda']]],
  ['float4_5fprecision_5fmapper_3c_20char_20_3e',['float4_precision_mapper&lt; char &gt;',['../structquda_1_1float4__precision__mapper_3_01char_01_4.html',1,'quda']]],
  ['float4_5fprecision_5fmapper_3c_20double_20_3e',['float4_precision_mapper&lt; double &gt;',['../structquda_1_1float4__precision__mapper_3_01double_01_4.html',1,'quda']]],
  ['float4_5fprecision_5fmapper_3c_20short_20_3e',['float4_precision_mapper&lt; short &gt;',['../structquda_1_1float4__precision__mapper_3_01short_01_4.html',1,'quda']]],
  ['floatnorder',['FloatNOrder',['../structquda_1_1clover_1_1_float_n_order.html',1,'quda::clover::FloatNOrder&lt; Float, length, N, add_rho, huge_alloc &gt;'],['../structquda_1_1gauge_1_1_float_n_order.html',1,'quda::gauge::FloatNOrder&lt; Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase &gt;'],['../structquda_1_1colorspinor_1_1_float_n_order.html',1,'quda::colorspinor::FloatNOrder&lt; Float, Ns, Nc, N, spin_project, huge_alloc &gt;']]],
  ['fmunuarg',['FmunuArg',['../structquda_1_1_fmunu_arg.html',1,'quda']]],
  ['fsu3_5fmatrix',['fsu3_matrix',['../structfsu3__matrix.html',1,'']]],
  ['fsu3_5fvector',['fsu3_vector',['../structfsu3__vector.html',1,'']]],
  ['fullclover',['FullClover',['../structquda_1_1_full_clover.html',1,'quda']]]
];
