QUDA: CMakeFiles/3.12.0/CompilerIdCUDA/tmp/CMakeCUDACompilerId.cudafe1.c File Reference
CMakeCUDACompilerId.cudafe1.c File Reference
Variables
const char * info_compiler = ((const char *)"INFO:compiler[NVIDIA]")
static const char info_version [50] = {((char)73),((char)78),((char)70),((char)79),((char)58),((char)99),((char)111),((char)109),((char)112),((char)105),((char)108),((char)101),((char)114),((char)95),((char)118),((char)101),((char)114),((char)115),((char)105),((char)111),((char)110),((char)91),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)49),((char)48),((char)46),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)46),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)56),((char)57),((char)93),((char)0)}
const char * info_platform = ((const char *)"INFO:platform[Darwin]")
const char * info_arch = ((const char *)"INFO:arch[]")
const char * info_language_dialect_default = ((const char *)"INFO:dialect_default[98]")
Variable Documentation
info_arch
const char* info_arch = ((const char *)"INFO:arch[]")
Definition at line 20 of file CMakeCUDACompilerId.cudafe1.c.
Referenced by main().
info_compiler
const char* info_compiler = ((const char *)"INFO:compiler[NVIDIA]")
Definition at line 15 of file CMakeCUDACompilerId.cudafe1.c.
Referenced by main().
info_language_dialect_default
const char* info_language_dialect_default = ((const char *)"INFO:dialect_default[98]")
Definition at line 25 of file CMakeCUDACompilerId.cudafe1.c.
Referenced by main().
info_platform
const char* info_platform = ((const char *)"INFO:platform[Darwin]")
Definition at line 19 of file CMakeCUDACompilerId.cudafe1.c.
Referenced by main().
info_version
const char info_version[50] = {((char)73),((char)78),((char)70),((char)79),((char)58),((char)99),((char)111),((char)109),((char)112),((char)105),((char)108),((char)101),((char)114),((char)95),((char)118),((char)101),((char)114),((char)115),((char)105),((char)111),((char)110),((char)91),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)49),((char)48),((char)46),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)46),((char)48),((char)48),((char)48),((char)48),((char)48),((char)48),((char)56),((char)57),((char)93),((char)0)} static
Definition at line 5 of file CMakeCUDACompilerId.cudafe1.c.