QUDA: tests/blas_reference.cpp File Reference
blas_reference.cpp File Reference
#include <blas_reference.h>
#include <stdio.h>
#include <comm_quda.h>
Functions
template<typename Float >
void aXpY (Float a, Float *x, Float *y, int len)
void axpy (double a, void *x, void *y, int len, QudaPrecision precision)
template<typename Float >
void aX (Float a, Float *x, int len)
void ax (double a, void *x, int len, QudaPrecision precision)
template<typename Float >
void mXpY (Float *x, Float *y, int len)
void mxpy (void *x, void *y, int len, QudaPrecision precision)
template<typename Float >
double norm2 (Float *v, int len)
double norm_2 (void *v, int len, QudaPrecision precision)
template<typename Float >
static void xpay (Float *x, Float a, Float *y, int len)
void xpay (void *x, double a, void *y, int length, QudaPrecision precision)
Function Documentation
aX()
template<typename Float > void aX (Float a, Float * x, int len) inline
Definition at line 18 of file blas_reference.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, and x.
Referenced by ax().
ax()
void ax (double a, void * x, int len, QudaPrecision precision)
Definition at line 22 of file blas_reference.cpp.
References a, aX(), len, QUDA_DOUBLE_PRECISION, and x.
aXpY()
template<typename Float > void aXpY (Float a, Float * x, Float * y, int len) inline
Definition at line 6 of file blas_reference.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, x, and y.
Referenced by axpy().
axpy()
void axpy (double a, void * x, void * y, int len, QudaPrecision precision)
Definition at line 11 of file blas_reference.cpp.
References a, aXpY(), len, QUDA_DOUBLE_PRECISION, x, and y.
mXpY()
template<typename Float > void mXpY (Float * x, Float * y, int len) inline
Definition at line 29 of file blas_reference.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, x, and y.
Referenced by mxpy().
mxpy()
void mxpy (void * x, void * y, int len, QudaPrecision precision)
Definition at line 33 of file blas_reference.cpp.
References len, mXpY(), QUDA_DOUBLE_PRECISION, x, and y.
norm2()
template<typename Float > double norm2 (Float * v, int len) inline
Definition at line 41 of file blas_reference.cpp.
References comm_allreduce(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, and sum().
Referenced by getRealBidiagMatrix(), and norm_2().
norm_2()
double norm_2 (void * v, int len, QudaPrecision precision)
Definition at line 48 of file blas_reference.cpp.
References len, norm2(), and QUDA_DOUBLE_PRECISION.
Referenced by invert_test(), and main().
xpay() [1/2]
template<typename Float > static void xpay (Float * x, Float a, Float * y, int len) inline static
Definition at line 55 of file blas_reference.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, x, and y.
Referenced by xpay().
xpay() [2/2]
void xpay (void * x, double a, void * y, int length, QudaPrecision precision)
Definition at line 59 of file blas_reference.cpp.
References a, length, QUDA_DOUBLE_PRECISION, x, xpay(), and y.