QUDA: tests/blas_reference.h File Reference
blas_reference.h File Reference
#include <enum_quda.h>
Functions
double norm_2 (void *vector, int len, QudaPrecision precision)
void mxpy (void *x, void *y, int len, QudaPrecision precision)
void ax (double a, void *x, int len, QudaPrecision precision)
void axpy (double a, void *x, void *y, int len, QudaPrecision precision)
void xpay (void *x, double a, void *y, int len, QudaPrecision precision)
Function Documentation
ax()
void ax (double a, void * x, int len, QudaPrecision precision)
Definition at line 22 of file blas_reference.cpp.
References a, aX(), len, QUDA_DOUBLE_PRECISION, and x.
axpy()
void axpy (double a, void * x, void * y, int len, QudaPrecision precision)
Definition at line 11 of file blas_reference.cpp.
References a, aXpY(), len, QUDA_DOUBLE_PRECISION, x, and y.
mxpy()
void mxpy (void * x, void * y, int len, QudaPrecision precision)
Definition at line 33 of file blas_reference.cpp.
References len, mXpY(), QUDA_DOUBLE_PRECISION, x, and y.
norm_2()
double norm_2 (void * vector, int len, QudaPrecision precision)
Definition at line 48 of file blas_reference.cpp.
References len, norm2(), and QUDA_DOUBLE_PRECISION.
Referenced by invert_test(), and main().
xpay()
void xpay (void * x, double a, void * y, int len, QudaPrecision precision)
Definition at line 59 of file blas_reference.cpp.
References a, length, QUDA_DOUBLE_PRECISION, x, xpay(), and y.