QUDA: quda::DiracClover Class Reference
quda::DiracClover Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracClover (const DiracParam &param)
DiracClover (const DiracClover &dirac)
virtual ~DiracClover ()
DiracClover & operator= (const DiracClover &dirac)
void Clover (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu=0., double mu_factor=0.) const
Create the coarse clover operator.
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Member Functions
void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
void initConstants ()
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes
cudaCloverField & clover
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Detailed Description
Definition at line 233 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracClover() [1/2]
quda::DiracClover::DiracClover (const DiracParam & param)
Definition at line 8 of file dirac_clover.cpp.
References warningQuda.
DiracClover() [2/2]
quda::DiracClover::DiracClover (const DiracClover & dirac)
Definition at line 16 of file dirac_clover.cpp.
References warningQuda.
~DiracClover()
quda::DiracClover::~DiracClover () virtual
Definition at line 24 of file dirac_clover.cpp.
Member Function Documentation
checkParitySpinor()
void quda::DiracClover::checkParitySpinor (const ColorSpinorField & out, const ColorSpinorField & in) const protected virtual
Reimplemented from quda::Dirac.
Definition at line 35 of file dirac_clover.cpp.
References quda::Dirac::checkParitySpinor(), clover, errorQuda, in, out, and quda::LatticeField::VolumeCB().
Referenced by Clover(), quda::DiracCloverPC::CloverInv(), quda::DiracCloverPC::Dslash(), DslashXpay(), and quda::DiracCloverPC::DslashXpay().
Clover()
void quda::DiracClover::Clover (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 66 of file dirac_clover.cpp.
References quda::ApplyClover(), checkParitySpinor(), clover, quda::Dirac::flops, in, out, and parity.
createCoarseOp()
void quda::DiracClover::createCoarseOp (GaugeField & Y, GaugeField & X, GaugeField & Xinv, GaugeField & Yhat, const Transfer & T, double kappa, double mu = 0., double mu_factor = 0.) const virtual
Create the coarse clover operator.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
Xinv[out] Coarse clover inverse field
Yhat coarse preconditioned link field
kappa Kappa parameter for the coarse operator
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 138 of file dirac_clover.cpp.
References a, clover, quda::CoarseOp(), quda::Dirac::gauge, quda::Dirac::kappa, mu, mu_factor, QUDA_CLOVER_DIRAC, QUDA_MATPC_INVALID, quda::ColorSpinorField::TwistFlavor(), quda::Transfer::Vectors(), and X.
DslashXpay()
void quda::DiracClover::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Applies the operator (A + k D)
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 46 of file dirac_clover.cpp.
References quda::asymCloverDslashCuda(), checkLocation, checkParitySpinor(), quda::Dirac::checkSpinorAlias(), clover, quda::Dirac::commDim, quda::Dirac::dagger, errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, out, parity, quda::Dirac::profile, QUDA_CUDA_FIELD_LOCATION, and x.
Referenced by M(), and quda::DiracCloverPC::M().
initConstants()
void quda::DiracClover::initConstants () protected
M()
void quda::DiracClover::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 73 of file dirac_clover.cpp.
References quda::Dirac::checkFullSpinor(), quda::ColorSpinorField::Create(), DslashXpay(), quda::ColorSpinorField::Even(), in, quda::Dirac::kappa, QudaGaugeParam_s::location, quda::ColorSpinorField::Odd(), out, param, QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_EVEN_PARITY, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT4_FIELD_ORDER, QUDA_ODD_PARITY, and QUDA_UKQCD_GAMMA_BASIS.
Referenced by MdagM().
MdagM()
void quda::DiracClover::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 107 of file dirac_clover.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), in, M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), out, and quda::Dirac::tmp1.
operator=()
DiracClover & quda::DiracClover::operator= (const DiracClover & dirac)
Definition at line 26 of file dirac_clover.cpp.
References clover, dirac, and quda::DiracWilson::operator=().
Referenced by quda::DiracCloverPC::operator=().
prepare()
void quda::DiracClover::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 120 of file dirac_clover.cpp.
References b, errorQuda, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, src, and x.
reconstruct()
void quda::DiracClover::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracCloverPC.
Definition at line 132 of file dirac_clover.cpp.
Member Data Documentation
clover
cudaCloverField& quda::DiracClover::clover protected
Definition at line 236 of file dirac_quda.h.
Referenced by checkParitySpinor(), Clover(), quda::DiracCloverPC::CloverInv(), createCoarseOp(), quda::DiracCloverPC::createCoarseOp(), quda::DiracCloverPC::DiracCloverPC(), quda::DiracCloverPC::Dslash(), DslashXpay(), quda::DiracCloverPC::DslashXpay(), and operator=().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_clover.cpp