QUDA: quda::Laplace< Float, nDim, nColor, Arg > Class Template Reference
quda::Laplace< Float, nDim, nColor, Arg > Class Template Reference
Public Member Functions
Laplace (Arg &arg, const ColorSpinorField &meta)
virtual ~Laplace ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y)
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
Protected Member Functions
long long flops () const
long long bytes () const
bool tuneGridDim () const
unsigned int minThreads () const
unsigned int maxBlockSize () const
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const ColorSpinorField & meta
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename Float, int nDim, int nColor, typename Arg>
class quda::Laplace< Float, nDim, nColor, Arg >
Definition at line 159 of file laplace.cu.
Constructor & Destructor Documentation
Laplace()
template<typename Float, int nDim, int nColor, typename Arg> quda::Laplace< Float, nDim, nColor, Arg >::Laplace (Arg & arg, const ColorSpinorField & meta) inline
Definition at line 179 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg, quda::Tunable::aux, quda::ColorSpinorField::AuxString(), quda::Laplace< Float, nDim, nColor, Arg >::meta, strcat(), and strcpy().
~Laplace()
template<typename Float, int nDim, int nColor, typename Arg> virtual quda::Laplace< Float, nDim, nColor, Arg >::~Laplace () inline virtual
Definition at line 194 of file laplace.cu.
Member Function Documentation
apply()
template<typename Float, int nDim, int nColor, typename Arg> void quda::Laplace< Float, nDim, nColor, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 196 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg, quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::LatticeField::Location(), quda::Laplace< Float, nDim, nColor, Arg >::meta, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, quda::stream, and quda::tuneLaunch().
bytes()
template<typename Float, int nDim, int nColor, typename Arg> long long quda::Laplace< Float, nDim, nColor, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 169 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg, quda::Laplace< Float, nDim, nColor, Arg >::meta, and quda::ColorSpinorField::VolumeCB().
flops()
template<typename Float, int nDim, int nColor, typename Arg> long long quda::Laplace< Float, nDim, nColor, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 165 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg, quda::Laplace< Float, nDim, nColor, Arg >::meta, nColor, and quda::ColorSpinorField::VolumeCB().
maxBlockSize()
template<typename Float, int nDim, int nColor, typename Arg> unsigned int quda::Laplace< Float, nDim, nColor, Arg >::maxBlockSize () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 176 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg, and deviceProp.
minThreads()
template<typename Float, int nDim, int nColor, typename Arg> unsigned int quda::Laplace< Float, nDim, nColor, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 175 of file laplace.cu.
References quda::Laplace< Float, nDim, nColor, Arg >::arg.
tuneGridDim()
template<typename Float, int nDim, int nColor, typename Arg> bool quda::Laplace< Float, nDim, nColor, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 174 of file laplace.cu.
tuneKey()
template<typename Float, int nDim, int nColor, typename Arg> TuneKey quda::Laplace< Float, nDim, nColor, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 205 of file laplace.cu.
References quda::Tunable::aux, quda::Laplace< Float, nDim, nColor, Arg >::meta, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int nDim, int nColor, typename Arg> Arg& quda::Laplace< Float, nDim, nColor, Arg >::arg protected
Definition at line 162 of file laplace.cu.
Referenced by quda::Laplace< Float, nDim, nColor, Arg >::apply(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::Laplace< Float, nDim, nColor, Arg >::Laplace(), quda::Laplace< Float, nDim, nColor, Arg >::maxBlockSize(), and quda::Laplace< Float, nDim, nColor, Arg >::minThreads().
meta
template<typename Float, int nDim, int nColor, typename Arg> const ColorSpinorField& quda::Laplace< Float, nDim, nColor, Arg >::meta protected
Definition at line 163 of file laplace.cu.
Referenced by quda::Laplace< Float, nDim, nColor, Arg >::apply(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::Laplace< Float, nDim, nColor, Arg >::Laplace(), and quda::Laplace< Float, nDim, nColor, Arg >::tuneKey().
The documentation for this class was generated from the following file:
lib/laplace.cu