QUDA: quda::ArpackArgs< Float > Class Template Reference
quda::ArpackArgs< Float > Class Template Reference
Public Member Functions
ArpackArgs (QudaMatvec< Float > &matvec, std::vector< ColorSpinorField *> &evecs, std::complex< Float > *evals, int nev, int ncv, char *which, Float tol)
virtual ~ArpackArgs ()
void apply ()
void save ()
Private Attributes
QudaMatvec< Float > & matvec
std::vector< ColorSpinorField * > & evecs
size_t clen
size_t cldn
std::complex< Float > * w_d_
std::complex< Float > * w_v_
int nev
int ncv
char * lanczos_which
Float tol
int info
Detailed Description
template<typename Float>
class quda::ArpackArgs< Float >
Definition at line 165 of file quda_arpack_interface.cpp.
Constructor & Destructor Documentation
ArpackArgs()
template<typename Float> quda::ArpackArgs< Float >::ArpackArgs (QudaMatvec< Float > & matvec, std::vector< ColorSpinorField *> & evecs, std::complex< Float > * evals, int nev, int ncv, char * which, Float tol) inline
Definition at line 188 of file quda_arpack_interface.cpp.
References quda::ArpackArgs< Float >::cldn, quda::ArpackArgs< Float >::clen, quda::ArpackArgs< Float >::evecs, quda::ArpackArgs< Float >::ncv, and quda::ArpackArgs< Float >::w_v_.
~ArpackArgs()
template<typename Float> virtual quda::ArpackArgs< Float >::~ArpackArgs () inline virtual
Definition at line 196 of file quda_arpack_interface.cpp.
References quda::ArpackArgs< Float >::w_v_.
Member Function Documentation
apply()
template<typename Float > void quda::ArpackArgs< Float >::apply ()
Definition at line 270 of file quda_arpack_interface.cpp.
References errorQuda, nev, printfQuda, and tol.
save()
template<typename Float > void quda::ArpackArgs< Float >::save ()
Definition at line 207 of file quda_arpack_interface.cpp.
References quda::ColorSpinorParam::create, quda::ColorSpinorField::Create(), csParam, e, errorQuda, quda::ColorSpinorParam::fieldOrder, quda::ColorSpinorParam::location, nev, quda::norm(), printfQuda, QUDA_CPU_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_REFERENCE_FIELD_CREATE, QUDA_SINGLE_PRECISION, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, SortEvals::SelectLarge(), SortEvals::SelectSmall(), quda::ColorSpinorParam::setPrecision(), SortEvals::small_values, and quda::ColorSpinorParam::v.
Member Data Documentation
cldn
template<typename Float> size_t quda::ArpackArgs< Float >::cldn private
Definition at line 174 of file quda_arpack_interface.cpp.
Referenced by quda::ArpackArgs< Float >::ArpackArgs().
clen
template<typename Float> size_t quda::ArpackArgs< Float >::clen private
Definition at line 173 of file quda_arpack_interface.cpp.
Referenced by quda::ArpackArgs< Float >::ArpackArgs().
evecs
template<typename Float> std::vector<ColorSpinorField*>& quda::ArpackArgs< Float >::evecs private
Definition at line 170 of file quda_arpack_interface.cpp.
Referenced by quda::ArpackArgs< Float >::ArpackArgs().
info
template<typename Float> int quda::ArpackArgs< Float >::info private
Definition at line 184 of file quda_arpack_interface.cpp.
lanczos_which
template<typename Float> char* quda::ArpackArgs< Float >::lanczos_which private
Definition at line 181 of file quda_arpack_interface.cpp.
matvec
template<typename Float> QudaMatvec<Float>& quda::ArpackArgs< Float >::matvec private
Definition at line 169 of file quda_arpack_interface.cpp.
ncv
template<typename Float> int quda::ArpackArgs< Float >::ncv private
Definition at line 180 of file quda_arpack_interface.cpp.
Referenced by quda::ArpackArgs< Float >::ArpackArgs().
nev
template<typename Float> int quda::ArpackArgs< Float >::nev private
spectrum info
Definition at line 179 of file quda_arpack_interface.cpp.
tol
template<typename Float> Float quda::ArpackArgs< Float >::tol private
general arpack library parameters
Definition at line 183 of file quda_arpack_interface.cpp.
w_d_
template<typename Float> std::complex<Float>* quda::ArpackArgs< Float >::w_d_ private
Definition at line 175 of file quda_arpack_interface.cpp.
w_v_
template<typename Float> std::complex<Float>* quda::ArpackArgs< Float >::w_v_ private
Definition at line 176 of file quda_arpack_interface.cpp.
Referenced by quda::ArpackArgs< Float >::ArpackArgs(), and quda::ArpackArgs< Float >::~ArpackArgs().
The documentation for this class was generated from the following file:
lib/quda_arpack_interface.cpp