QUDA: Spinor< RegType, StoreType, N, write, tex_id > Class Template Reference
Spinor< RegType, StoreType, N, write, tex_id > Class Template Reference
#include <texture.h>
Public Member Functions
Spinor ()
Spinor (const ColorSpinorField &x, int nFace=1)
Spinor (const Spinor &st)
Spinor & operator= (const Spinor &src)
void set (const cudaColorSpinorField &x)
~Spinor ()
__device__ void save (RegType x[], int i, const int parity=0)
void backup (char **spinor_h, char **norm_h, size_t bytes, size_t norm_bytes)
void restore (char **spinor_h, char **norm_h, size_t bytes, size_t norm_bytes)
void * V ()
float * Norm ()
Public Member Functions inherited from SpinorTexture< RegType, StoreType, N, tex_id >
SpinorTexture ()
SpinorTexture (const ColorSpinorField &x, int nFace=1)
SpinorTexture (const SpinorTexture &st)
SpinorTexture & operator= (const SpinorTexture &src)
void set (const cudaColorSpinorField &x, int nFace=1)
virtual ~SpinorTexture ()
__device__ void load (RegType x[], const int i, const int parity=0)
__device__ void loadGhost (RegType x[], const int i, const int dim)
QudaPrecision Precision () const
int Stride () const
int Bytes () const
Private Types
typedef bridge_mapper< RegType, StoreType >::type InterType
typedef SpinorTexture< RegType, StoreType, N, tex_id > ST
Additional Inherited Members
Protected Attributes inherited from SpinorTexture< RegType, StoreType, N, tex_id >
StoreType * spinor
StoreType * ghost_spinor
Texture< InterType, StoreType, tex_id > tex
Texture< InterType, StoreType, -1 > ghostTex
float * norm
int stride
unsigned int cb_offset
unsigned int cb_norm_offset
int ghost_stride [4]
Detailed Description
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1>
class Spinor< RegType, StoreType, N, write, tex_id >
Parameters
RegType Register type used in kernel
InterType Intermediate format - RegType precision with StoreType ordering
StoreType Type used to store field in memory
N Length of vector of RegType elements that this Spinor represents
tex_id Which texture reference are we using. A default of -1 disables textures on architectures that don't support texture objects.
Definition at line 528 of file texture.h.
Member Typedef Documentation
InterType
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> typedef bridge_mapper<RegType,StoreType>::type Spinor< RegType, StoreType, N, write, tex_id >::InterType private
Definition at line 530 of file texture.h.
ST
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> typedef SpinorTexture<RegType,StoreType,N,tex_id> Spinor< RegType, StoreType, N, write, tex_id >::ST private
Definition at line 531 of file texture.h.
Constructor & Destructor Documentation
Spinor() [1/3]
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> Spinor< RegType, StoreType, N, write, tex_id >::Spinor () inline
Definition at line 542 of file texture.h.
Spinor() [2/3]
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> Spinor< RegType, StoreType, N, write, tex_id >::Spinor (const ColorSpinorField & x, int nFace = 1) inline
Definition at line 549 of file texture.h.
Spinor() [3/3]
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> Spinor< RegType, StoreType, N, write, tex_id >::Spinor (const Spinor< RegType, StoreType, N, write, tex_id > & st) inline
Definition at line 555 of file texture.h.
~Spinor()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> Spinor< RegType, StoreType, N, write, tex_id >::~Spinor () inline
Definition at line 580 of file texture.h.
Member Function Documentation
backup()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> void Spinor< RegType, StoreType, N, write, tex_id >::backup (char ** spinor_h, char ** norm_h, size_t bytes, size_t norm_bytes) inline
Definition at line 601 of file texture.h.
References quda::blas::bytes, checkCudaError, SpinorTexture< RegType, StoreType, N, tex_id >::norm, and SPINOR.
Norm()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> float* Spinor< RegType, StoreType, N, write, tex_id >::Norm () inline
Definition at line 629 of file texture.h.
References SpinorTexture< RegType, StoreType, N, tex_id >::norm.
operator=()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> Spinor& Spinor< RegType, StoreType, N, write, tex_id >::operator= (const Spinor< RegType, StoreType, N, write, tex_id > & src) inline
Definition at line 561 of file texture.h.
References SpinorTexture< RegType, StoreType, N, tex_id >::ghost_spinor, SpinorTexture< RegType, StoreType, N, tex_id >::operator=(), SpinorTexture< RegType, StoreType, N, tex_id >::spinor, and src.
restore()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> void Spinor< RegType, StoreType, N, write, tex_id >::restore (char ** spinor_h, char ** norm_h, size_t bytes, size_t norm_bytes) inline
Definition at line 614 of file texture.h.
References quda::blas::bytes, checkCudaError, SpinorTexture< RegType, StoreType, N, tex_id >::norm, and SPINOR.
save()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> __device__ void Spinor< RegType, StoreType, N, write, tex_id >::save (RegType x[], int i, const int parity = 0) inline
Definition at line 583 of file texture.h.
References SpinorTexture< RegType, StoreType, N, tex_id >::cb_norm_offset, SpinorTexture< RegType, StoreType, N, tex_id >::cb_offset, copyFloatN(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, SpinorTexture< RegType, StoreType, N, tex_id >::norm, parity, SPINOR, SpinorTexture< RegType, StoreType, N, tex_id >::stride, value, x, and y.
set()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> void Spinor< RegType, StoreType, N, write, tex_id >::set (const cudaColorSpinorField & x) inline
Definition at line 572 of file texture.h.
References SpinorTexture< RegType, StoreType, N, tex_id >::ghost_spinor, SpinorTexture< RegType, StoreType, N, tex_id >::set(), SpinorTexture< RegType, StoreType, N, tex_id >::spinor, and x.
Referenced by quda::computeCloverSigmaOprod().
V()
template<typename RegType, typename StoreType, int N, int write, int tex_id = -1> void* Spinor< RegType, StoreType, N, write, tex_id >::V () inline
Definition at line 628 of file texture.h.
References SPINOR.
The documentation for this class was generated from the following file:
include/texture.h