QUDA: quda::DiracImprovedStaggeredPC Class Reference
quda::DiracImprovedStaggeredPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracImprovedStaggeredPC (const DiracParam &param)
DiracImprovedStaggeredPC (const DiracImprovedStaggeredPC &dirac)
virtual ~DiracImprovedStaggeredPC ()
DiracImprovedStaggeredPC & operator= (const DiracImprovedStaggeredPC &dirac)
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracImprovedStaggered
DiracImprovedStaggered (const DiracParam &param)
DiracImprovedStaggered (const DiracImprovedStaggered &dirac)
virtual ~DiracImprovedStaggered ()
DiracImprovedStaggered & operator= (const DiracImprovedStaggered &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracImprovedStaggered
cudaGaugeField & fatGauge
cudaGaugeField & longGauge
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 716 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracImprovedStaggeredPC() [1/2]
quda::DiracImprovedStaggeredPC::DiracImprovedStaggeredPC (const DiracParam & param)
Definition at line 124 of file dirac_improved_staggered.cpp.
DiracImprovedStaggeredPC() [2/2]
quda::DiracImprovedStaggeredPC::DiracImprovedStaggeredPC (const DiracImprovedStaggeredPC & dirac)
Definition at line 130 of file dirac_improved_staggered.cpp.
~DiracImprovedStaggeredPC()
quda::DiracImprovedStaggeredPC::~DiracImprovedStaggeredPC () virtual
Definition at line 136 of file dirac_improved_staggered.cpp.
Member Function Documentation
M()
void quda::DiracImprovedStaggeredPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracImprovedStaggered.
Definition at line 150 of file dirac_improved_staggered.cpp.
References errorQuda.
MdagM()
void quda::DiracImprovedStaggeredPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracImprovedStaggered.
Definition at line 155 of file dirac_improved_staggered.cpp.
References quda::Dirac::deleteTmp(), quda::DiracImprovedStaggered::Dslash(), quda::DiracImprovedStaggered::DslashXpay(), errorQuda, in, quda::Dirac::mass, quda::Dirac::matpcType, quda::Dirac::newTmp(), out, parity, QUDA_EVEN_PARITY, QUDA_INVALID_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
operator=()
DiracImprovedStaggeredPC & quda::DiracImprovedStaggeredPC::operator= (const DiracImprovedStaggeredPC & dirac)
Definition at line 141 of file dirac_improved_staggered.cpp.
References dirac, and quda::DiracImprovedStaggered::operator=().
prepare()
void quda::DiracImprovedStaggeredPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracImprovedStaggered.
Definition at line 176 of file dirac_improved_staggered.cpp.
References b, src, and x.
reconstruct()
void quda::DiracImprovedStaggeredPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracImprovedStaggered.
Definition at line 184 of file dirac_improved_staggered.cpp.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_improved_staggered.cpp