QUDA: GaugeAlgTest Class Reference
GaugeAlgTest Class Reference
Protected Member Functions
void SetReunitarizationConsts ()
bool checkDimsPartitioned ()
bool comparePlaquette (double3 a, double3 b)
bool CheckDeterminant (double2 detu)
void CallUnitarizeLinks (cudaGaugeField *cudaInGauge)
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
QudaGaugeParam param
Timer a0
Timer a1
double2 detu
double3 plaq
cudaGaugeField * cudaInGauge
int nsteps
int nhbsteps
int novrsteps
bool coldstart
double beta_value
RNG * randstates
Detailed Description
Definition at line 42 of file gauge_alg_test.cpp.
Member Function Documentation
CallUnitarizeLinks()
void GaugeAlgTest::CallUnitarizeLinks (cudaGaugeField * cudaInGauge) inline protected
Definition at line 81 of file gauge_alg_test.cpp.
References errorQuda, exit(), num_failures, num_failures_dev, and quda::unitarizeLinks().
CheckDeterminant()
bool GaugeAlgTest::CheckDeterminant (double2 detu) inline protected
Definition at line 73 of file gauge_alg_test.cpp.
References DABS, e, prec, and QUDA_DOUBLE_PRECISION.
checkDimsPartitioned()
bool GaugeAlgTest::checkDimsPartitioned () inline protected
Definition at line 57 of file gauge_alg_test.cpp.
References comm_dim_partitioned().
comparePlaquette()
bool GaugeAlgTest::comparePlaquette (double3 a, double3 b) inline protected
Definition at line 62 of file gauge_alg_test.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::a1, fused_exterior_ndeg_tm_dslash_cuda_gen::a2, b, DABS, prec, and QUDA_DOUBLE_PRECISION.
SetReunitarizationConsts()
void GaugeAlgTest::SetReunitarizationConsts () inline protected
Definition at line 44 of file gauge_alg_test.cpp.
References e, reunit_allow_svd, reunit_svd_only, quda::setUnitarizeLinksConstants(), svd_abs_error, svd_rel_error, and unitarize_eps.
SetUp()
virtual void GaugeAlgTest::SetUp () inline protected virtual
Definition at line 92 of file gauge_alg_test.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::a1, QudaGaugeParam_s::anisotropy, CallUnitarizeLinks(), comm_dim_partitioned(), QudaGaugeParam_s::cpu_prec, quda::GaugeFieldParam::create, QudaGaugeParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, errorQuda, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, quda::LatticeFieldParam::ghostExchange, gParam, quda::InitGaugeField(), link_recon, quda::GaugeFieldParam::link_type, quda::Monte(), newQudaGaugeParam(), num_failures_dev, quda::GaugeFieldParam::order, quda::LatticeFieldParam::pad, param, quda::plaquette(), prec, printfQuda, QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_GAUGE_ORDER, QUDA_FLOAT4_GAUGE_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_GAUGE_FIXED_NO, QUDA_GHOST_EXCHANGE_EXTENDED, QUDA_GHOST_EXCHANGE_NO, QUDA_MILC_GAUGE_ORDER, QUDA_NULL_FIELD_CREATE, QUDA_PERIODIC_T, QUDA_RECONSTRUCT_8, QUDA_RECONSTRUCT_NO, QUDA_VECTOR_GEOMETRY, QUDA_VERBOSE, QUDA_WILSON_LINKS, QUDA_ZERO_FIELD_CREATE, R, quda::GaugeFieldParam::reconstruct, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, setDims(), setVerbosity(), quda::GaugeFieldParam::t_boundary, QudaGaugeParam_s::t_boundary, tdim, QudaGaugeParam_s::type, QudaGaugeParam_s::X, xdim, y, ydim, and zdim.
TearDown()
virtual void GaugeAlgTest::TearDown () inline protected virtual
Definition at line 189 of file gauge_alg_test.cpp.
References quda::getLinkDeterminant(), quda::getLinkTrace(), num_failures_dev, quda::PGaugeExchangeFree(), and printfQuda.
Member Data Documentation
a0
Timer GaugeAlgTest::a0 protected
Definition at line 210 of file gauge_alg_test.cpp.
a1
Timer GaugeAlgTest::a1 protected
Definition at line 210 of file gauge_alg_test.cpp.
beta_value
double GaugeAlgTest::beta_value protected
Definition at line 218 of file gauge_alg_test.cpp.
coldstart
bool GaugeAlgTest::coldstart protected
Definition at line 217 of file gauge_alg_test.cpp.
cudaInGauge
cudaGaugeField* GaugeAlgTest::cudaInGauge protected
Definition at line 213 of file gauge_alg_test.cpp.
detu
double2 GaugeAlgTest::detu protected
Definition at line 211 of file gauge_alg_test.cpp.
nhbsteps
int GaugeAlgTest::nhbsteps protected
Definition at line 215 of file gauge_alg_test.cpp.
novrsteps
int GaugeAlgTest::novrsteps protected
Definition at line 216 of file gauge_alg_test.cpp.
nsteps
int GaugeAlgTest::nsteps protected
Definition at line 214 of file gauge_alg_test.cpp.
param
QudaGaugeParam GaugeAlgTest::param protected
Definition at line 208 of file gauge_alg_test.cpp.
plaq
double3 GaugeAlgTest::plaq protected
Definition at line 212 of file gauge_alg_test.cpp.
randstates
RNG* GaugeAlgTest::randstates protected
Definition at line 219 of file gauge_alg_test.cpp.
The documentation for this class was generated from the following file:
tests/gauge_alg_test.cpp