QUDA: quda::DiracStaggeredPC Class Reference
quda::DiracStaggeredPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracStaggeredPC (const DiracParam &param)
DiracStaggeredPC (const DiracStaggeredPC &dirac)
virtual ~DiracStaggeredPC ()
DiracStaggeredPC & operator= (const DiracStaggeredPC &dirac)
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracStaggered
DiracStaggered (const DiracParam &param)
DiracStaggered (const DiracStaggered &dirac)
virtual ~DiracStaggered ()
DiracStaggered & operator= (const DiracStaggered &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 666 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracStaggeredPC() [1/2]
quda::DiracStaggeredPC::DiracStaggeredPC (const DiracParam & param)
Definition at line 120 of file dirac_staggered.cpp.
DiracStaggeredPC() [2/2]
quda::DiracStaggeredPC::DiracStaggeredPC (const DiracStaggeredPC & dirac)
Definition at line 126 of file dirac_staggered.cpp.
~DiracStaggeredPC()
quda::DiracStaggeredPC::~DiracStaggeredPC () virtual
Definition at line 132 of file dirac_staggered.cpp.
Member Function Documentation
M()
void quda::DiracStaggeredPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracStaggered.
Definition at line 146 of file dirac_staggered.cpp.
References errorQuda.
MdagM()
void quda::DiracStaggeredPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracStaggered.
Definition at line 151 of file dirac_staggered.cpp.
References quda::Dirac::deleteTmp(), quda::DiracStaggered::Dslash(), quda::DiracStaggered::DslashXpay(), errorQuda, in, quda::Dirac::mass, quda::Dirac::matpcType, quda::Dirac::newTmp(), out, parity, QUDA_EVEN_PARITY, QUDA_INVALID_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
operator=()
DiracStaggeredPC & quda::DiracStaggeredPC::operator= (const DiracStaggeredPC & dirac)
Definition at line 137 of file dirac_staggered.cpp.
References dirac, and quda::DiracStaggered::operator=().
prepare()
void quda::DiracStaggeredPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracStaggered.
Definition at line 172 of file dirac_staggered.cpp.
References b, src, and x.
reconstruct()
void quda::DiracStaggeredPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracStaggered.
Definition at line 180 of file dirac_staggered.cpp.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_staggered.cpp