QUDA: quda::DiracTwistedMassPC Class Reference
quda::DiracTwistedMassPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracTwistedMassPC (const DiracTwistedMassPC &dirac)
DiracTwistedMassPC (const DiracParam &param, const int nDim)
virtual ~DiracTwistedMassPC ()
DiracTwistedMassPC & operator= (const DiracTwistedMassPC &dirac)
void TwistInv (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu, double mu_factor=0.) const
Create the coarse even-odd preconditioned twisted-mass operator.
Public Member Functions inherited from quda::DiracTwistedMass
DiracTwistedMass (const DiracTwistedMass &dirac)
DiracTwistedMass (const DiracParam &param, const int nDim)
virtual ~DiracTwistedMass ()
DiracTwistedMass & operator= (const DiracTwistedMass &dirac)
void Twist (ColorSpinorField &out, const ColorSpinorField &in) const
double Mu () const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracTwistedMass
void twistedApply (ColorSpinorField &out, const ColorSpinorField &in, const QudaTwistGamma5Type twistType) const
void TwistedDslash (ColorSpinorField &out, const ColorSpinorField &in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void TwistedDslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const ColorSpinorField &x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void NdegTwistedDslash (ColorSpinorField &out, const ColorSpinorField &in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void NdegTwistedDslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const ColorSpinorField &x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracTwistedMass
double mu
double epsilon
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 512 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracTwistedMassPC() [1/2]
quda::DiracTwistedMassPC::DiracTwistedMassPC (const DiracTwistedMassPC & dirac)
Definition at line 154 of file dirac_twisted_mass.cpp.
DiracTwistedMassPC() [2/2]
quda::DiracTwistedMassPC::DiracTwistedMassPC (const DiracParam & param, const int nDim)
Definition at line 156 of file dirac_twisted_mass.cpp.
~DiracTwistedMassPC()
quda::DiracTwistedMassPC::~DiracTwistedMassPC () virtual
Definition at line 158 of file dirac_twisted_mass.cpp.
Member Function Documentation
createCoarseOp()
void quda::DiracTwistedMassPC::createCoarseOp (GaugeField & Y, GaugeField & X, GaugeField & Xinv, GaugeField & Yhat, const Transfer & T, double kappa, double mu, double mu_factor = 0.) const virtual
Create the coarse even-odd preconditioned twisted-mass operator.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
Xinv[out] Coarse clover inverse field
Yhat coarse preconditioned link field
kappa Kappa parameter for the coarse operator
mu TM mu parameter for the coarse operator
mu_factor multiplicative factor for the mu parameter
Reimplemented from quda::DiracTwistedMass.
Definition at line 437 of file dirac_twisted_mass.cpp.
References a, c, quda::CoarseOp(), quda::Dirac::gauge, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedMass::mu, mu_factor, QUDA_TWISTED_MASSPC_DIRAC, and X.
Dslash()
void quda::DiracTwistedMassPC::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 179 of file dirac_twisted_mass.cpp.
References a, quda::ApplyTwistGamma(), b, c, quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::Dirac::deleteTmp(), quda::DiracTwistedMass::epsilon, errorQuda, in, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedMass::mu, quda::DiracTwistedMass::NdegTwistedDslash(), quda::Dirac::newTmp(), out, parity, QUDA_DEG_DSLASH_TWIST_INV, QUDA_DEG_TWIST_INV_DSLASH, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_NONDEG_DSLASH, QUDA_TWIST_GAMMA5_INVERSE, QUDA_TWIST_INVALID, QUDA_TWIST_NO, QUDA_TWIST_SINGLET, and quda::DiracTwistedMass::TwistedDslash().
Referenced by M().
DslashXpay()
void quda::DiracTwistedMassPC::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 220 of file dirac_twisted_mass.cpp.
References a, quda::ApplyTwistGamma(), b, c, quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::Dirac::deleteTmp(), quda::DiracTwistedMass::epsilon, errorQuda, in, quda::Dirac::kappa, quda::DiracTwistedMass::mu, quda::DiracTwistedMass::NdegTwistedDslashXpay(), quda::Dirac::newTmp(), out, parity, QUDA_DEG_DSLASH_TWIST_INV, QUDA_DEG_TWIST_INV_DSLASH, QUDA_NONDEG_DSLASH, QUDA_TWIST_GAMMA5_INVERSE, QUDA_TWIST_INVALID, QUDA_TWIST_NO, QUDA_TWIST_SINGLET, quda::DiracTwistedMass::TwistedDslashXpay(), and x.
Referenced by M().
M()
void quda::DiracTwistedMassPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracTwistedMass.
Definition at line 258 of file dirac_twisted_mass.cpp.
References a, b, c, quda::Dirac::deleteTmp(), Dslash(), DslashXpay(), quda::DiracTwistedMass::epsilon, in, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedMass::mu, quda::DiracTwistedMass::NdegTwistedDslashXpay(), quda::Dirac::newTmp(), out, parity, QUDA_DEG_DSLASH_TWIST_XPAY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_NONDEG_DSLASH, QUDA_TWIST_SINGLET, quda::Dirac::tmp1, and quda::DiracTwistedMass::TwistedDslashXpay().
Referenced by MdagM().
MdagM()
void quda::DiracTwistedMassPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracTwistedMass.
Definition at line 295 of file dirac_twisted_mass.cpp.
References quda::Dirac::deleteTmp(), in, M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), out, and quda::Dirac::tmp2.
operator=()
DiracTwistedMassPC & quda::DiracTwistedMassPC::operator= (const DiracTwistedMassPC & dirac)
Definition at line 163 of file dirac_twisted_mass.cpp.
References dirac, and quda::DiracTwistedMass::operator=().
prepare()
void quda::DiracTwistedMassPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracTwistedMass.
Definition at line 304 of file dirac_twisted_mass.cpp.
References b, quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedMass::NdegTwistedDslashXpay(), quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_NONDEG_DSLASH, QUDA_ODD_PARITY, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_SINGLET, src, quda::Dirac::tmp1, quda::DiracTwistedMass::twistedApply(), TwistInv(), and x.
reconstruct()
void quda::DiracTwistedMassPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracTwistedMass.
Definition at line 398 of file dirac_twisted_mass.cpp.
References b, quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedMass::NdegTwistedDslashXpay(), quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_NONDEG_DSLASH, QUDA_ODD_PARITY, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_SINGLET, quda::Dirac::tmp1, quda::DiracTwistedMass::twistedApply(), TwistInv(), and x.
TwistInv()
void quda::DiracTwistedMassPC::TwistInv (ColorSpinorField & out, const ColorSpinorField & in) const
Definition at line 172 of file dirac_twisted_mass.cpp.
References in, out, QUDA_TWIST_GAMMA5_INVERSE, and quda::DiracTwistedMass::twistedApply().
Referenced by prepare(), and reconstruct().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_twisted_mass.cpp