QUDA: quda::Deflation Class Reference
quda::Deflation Class Reference
#include <deflation.h>
Public Member Functions
Deflation (DeflationParam &param, TimeProfile &profile)
virtual ~Deflation ()
void verify ()
void increment (ColorSpinorField &V, int nev)
void reduce (double tol, int max_nev)
void operator() (ColorSpinorField &out, ColorSpinorField &in)
void loadVectors (ColorSpinorField *RV)
Load the eigen space vectors from file.
void saveVectors (ColorSpinorField *RV)
Save the eigen space vectors in file.
bool is_complete ()
Test whether the deflation space is complete and therefore cannot be further extended
int size ()
return deflation space size
double flops () const
Return the total flops done on this and all coarser levels.
Private Attributes
DeflationParam & param
TimeProfile profile
ColorSpinorField * r
ColorSpinorField * Av
ColorSpinorField * r_sloppy
ColorSpinorField * Av_sloppy
Detailed Description
Deflation methods :
Definition at line 78 of file deflation.h.
Constructor & Destructor Documentation
Deflation()
quda::Deflation::Deflation (DeflationParam & param, TimeProfile & profile)
Constructor for Deflation class
Parameters
param DeflationParam struct that defines all meta data
profile Timeprofile instance used to profile
Definition at line 30 of file deflation.cpp.
References Av, Av_sloppy, quda::ColorSpinorField::Component(), quda::ColorSpinorField::Create(), csParam, QudaEigParam_s::cuda_prec_ritz, quda::DeflationParam::eig_global, getVerbosity(), QudaEigParam_s::import_vectors, loadVectors(), quda::DeflationParam::location, param, quda::TimeProfile::Print(), printfQuda, profile, QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT4_FIELD_ORDER, QUDA_MEMORY_DEVICE, QUDA_SUMMARIZE, QUDA_UKQCD_GAMMA_BASIS, QUDA_ZERO_FIELD_CREATE, r, r_sloppy, QudaEigParam_s::run_verify, quda::DeflationParam::RV, quda::DeflationParam::tot_dim, and verify().
~Deflation()
quda::Deflation::~Deflation () virtual
Destructor for Deflation class. Frees any existing Deflation instance
Definition at line 76 of file deflation.cpp.
References Av, Av_sloppy, QudaEigParam_s::cuda_prec_ritz, quda::DeflationParam::eig_global, getVerbosity(), param, quda::TimeProfile::Print(), profile, QUDA_DOUBLE_PRECISION, QUDA_SUMMARIZE, r, and r_sloppy.
Member Function Documentation
flops()
double quda::Deflation::flops () const
Return the total flops done on this and all coarser levels.
Definition at line 89 of file deflation.cpp.
increment()
void quda::Deflation::increment (ColorSpinorField & V, int nev)
In the incremental eigcg: expands deflation space.
Parameters
V container of new eigenvectors
nev number of vectors to load
Definition at line 207 of file deflation.cpp.
References Av, Av_sloppy, quda::blas::ax(), quda::blas::caxpy(), quda::blas::cDotProduct(), quda::ColorSpinorField::Component(), quda::ColorSpinorField::Components(), quda::ColorSpinorField::CompositeDim(), quda::conj(), quda::blas::copy(), QudaEigParam_s::cuda_prec_ritz, quda::DeflationParam::cur_dim, e, quda::DeflationParam::eig_global, errorQuda, fused_exterior_ndeg_tm_dslash_cuda_gen::i, QudaInvertParam_s::inv_type, QudaEigParam_s::invert_param, quda::DeflationParam::ld, quda::DeflationParam::matDeflation, quda::DeflationParam::matProj, nev, quda::blas::norm2(), offset, param, printfQuda, QUDA_DOUBLE_PRECISION, QUDA_EIGCG_INVERTER, QUDA_INC_EIGCG_INVERTER, r, quda::DeflationParam::RV, quda::sqrt(), quda::DeflationParam::tot_dim, and warningQuda.
Referenced by quda::IncEigCG::operator()().
is_complete()
bool quda::Deflation::is_complete () inline
Test whether the deflation space is complete and therefore cannot be further extended
Definition at line 159 of file deflation.h.
References quda::DeflationParam::cur_dim, param, and quda::DeflationParam::tot_dim.
Referenced by quda::IncEigCG::operator()().
loadVectors()
void quda::Deflation::loadVectors (ColorSpinorField * RV)
Load the eigen space vectors from file.
Parameters
RV Loaded eigen-space vectors (pre-allocated)
Definition at line 384 of file deflation.cpp.
References quda::ColorSpinorField::Components(), quda::DeflationParam::eig_global, errorQuda, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::ColorSpinorField::IsComposite(), param, printfQuda, profile, quda::QUDA_PROFILE_INIT, quda::QUDA_PROFILE_IO, read_spinor_field(), strcmp(), V, vec_infile, and QudaEigParam_s::vec_infile.
Referenced by Deflation().
operator()()
void quda::Deflation::operator() (ColorSpinorField & out, ColorSpinorField & in)
This applies deflation operation on a given spinor vector(s)
Parameters
out The projected vector
in The input vector (or equivalently the right hand side vector)
Definition at line 152 of file deflation.cpp.
References b, quda::blas::caxpy(), quda::blas::cDotProduct(), quda::ColorSpinorField::Components(), quda::DeflationParam::cur_dim, quda::DeflationParam::eig_global, errorQuda, QudaEigParam_s::extlib_type, fused_exterior_ndeg_tm_dslash_cuda_gen::i, QudaInvertParam_s::inv_type, QudaEigParam_s::invert_param, quda::DeflationParam::invRitzVals, quda::DeflationParam::ld, magma_Xgesv(), quda::DeflationParam::matProj, quda::norm2(), param, quda::LatticeField::Precision(), printfQuda, QUDA_EIGCG_INVERTER, QUDA_EIGEN_EXTLIB, QUDA_INC_EIGCG_INVERTER, QUDA_MAGMA_EXTLIB, r_sloppy, quda::DeflationParam::RV, quda::sqrt(), quda::DeflationParam::use_inv_ritz, and x.
reduce()
void quda::Deflation::reduce (double tol, int max_nev)
In the incremental eigcg: reduce deflation space based on the following criteria:
Parameters
tol : keep all eigenvectors with residual norm less then tol
max_nev : keep the lowest max_nev eigenvectors (conservative)
Definition at line 285 of file deflation.cpp.
References Av_sloppy, quda::blas::caxpy(), quda::blas::cDotProductNormA(), quda::ColorSpinorField::Component(), quda::ColorSpinorField::Components(), quda::blas::copy(), quda::ColorSpinorField::Create(), csParam, quda::DeflationParam::cur_dim, e, quda::DeflationParam::eig_global, errorQuda, QudaEigParam_s::extlib_type, fabs(), getVerbosity(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, quda::DeflationParam::invRitzVals, quda::DeflationParam::ld, magma_Xheev(), quda::DeflationParam::matDeflation, quda::DeflationParam::matProj, memcpy(), quda::norm2(), param, quda::pinned_allocator, quda::pinned_deleter, printf(), printfQuda, QUDA_EIGEN_EXTLIB, QUDA_MAGMA_EXTLIB, QUDA_MEMORY_MAPPED, QUDA_VERBOSE, QUDA_ZERO_FIELD_CREATE, r, r_sloppy, quda::DeflationParam::RV, quda::sqrt(), tol, quda::DeflationParam::tot_dim, quda::DeflationParam::use_inv_ritz, quda::blas::xpay(), and quda::blas::zero().
Referenced by quda::IncEigCG::operator()().
saveVectors()
void quda::Deflation::saveVectors (ColorSpinorField * RV)
Save the eigen space vectors in file.
Parameters
RV Save eigen-space vectors from here
Definition at line 420 of file deflation.cpp.
References quda::ColorSpinorField::Components(), quda::DeflationParam::eig_global, errorQuda, host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::ColorSpinorField::IsComposite(), param, printfQuda, profile, quda::QUDA_PROFILE_INIT, quda::QUDA_PROFILE_IO, safe_malloc, strcmp(), V, vec_outfile, QudaEigParam_s::vec_outfile, and write_spinor_field().
size()
int quda::Deflation::size () inline
return deflation space size
Definition at line 164 of file deflation.h.
References quda::DeflationParam::cur_dim, and param.
Referenced by quda::IncEigCG::operator()().
verify()
void quda::Deflation::verify ()
This method verifies the correctness of the MG method. It checks:
eigen-vector accuracy
...
Verification that the computed approximate eigenvectors are (not) valid
Definition at line 100 of file deflation.cpp.
References Av_sloppy, quda::blas::caxpy(), quda::blas::cDotProductNormA(), quda::ColorSpinorField::Components(), quda::DeflationParam::cur_dim, quda::DeflationParam::eig_global, errorQuda, QudaEigParam_s::extlib_type, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::DeflationParam::ld, magma_Xheev(), quda::DeflationParam::matDeflation, quda::DeflationParam::matProj, memcpy(), quda::norm2(), param, quda::pinned_allocator, quda::pinned_deleter, printfQuda, QUDA_EIGEN_EXTLIB, QUDA_MAGMA_EXTLIB, r, r_sloppy, quda::DeflationParam::RV, quda::sqrt(), quda::blas::xpay(), and quda::zero().
Referenced by Deflation(), and quda::IncEigCG::operator()().
Member Data Documentation
Av
ColorSpinorField* quda::Deflation::Av private
High precision aux field
Definition at line 91 of file deflation.h.
Referenced by Deflation(), increment(), and ~Deflation().
Av_sloppy
ColorSpinorField* quda::Deflation::Av_sloppy private
Deflation matrix operation result
Definition at line 97 of file deflation.h.
Referenced by Deflation(), increment(), reduce(), verify(), and ~Deflation().
param
DeflationParam& quda::Deflation::param private
Local copy of the deflation metadata
Definition at line 82 of file deflation.h.
Referenced by Deflation(), increment(), is_complete(), loadVectors(), operator()(), reduce(), saveVectors(), size(), verify(), and ~Deflation().
profile
TimeProfile quda::Deflation::profile private
TimeProfile for this level
Definition at line 85 of file deflation.h.
Referenced by Deflation(), loadVectors(), saveVectors(), and ~Deflation().
r
ColorSpinorField* quda::Deflation::r private
High precision aux field
Definition at line 88 of file deflation.h.
Referenced by Deflation(), increment(), reduce(), verify(), and ~Deflation().
r_sloppy
ColorSpinorField* quda::Deflation::r_sloppy private
Ritz precision residual vector
Definition at line 94 of file deflation.h.
Referenced by Deflation(), operator()(), reduce(), verify(), and ~Deflation().
The documentation for this class was generated from the following files:
include/deflation.h
lib/deflation.cpp