QUDA: quda::DiracTwistedMass Class Reference
quda::DiracTwistedMass Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracTwistedMass (const DiracTwistedMass &dirac)
DiracTwistedMass (const DiracParam &param, const int nDim)
virtual ~DiracTwistedMass ()
DiracTwistedMass & operator= (const DiracTwistedMass &dirac)
void Twist (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
double Mu () const
void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu, double mu_factor=0.) const
Create the coarse twisted-mass operator.
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Member Functions
void twistedApply (ColorSpinorField &out, const ColorSpinorField &in, const QudaTwistGamma5Type twistType) const
void TwistedDslash (ColorSpinorField &out, const ColorSpinorField &in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void TwistedDslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const ColorSpinorField &x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void NdegTwistedDslash (ColorSpinorField &out, const ColorSpinorField &in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
void NdegTwistedDslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const ColorSpinorField &x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes
double mu
double epsilon
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Detailed Description
Definition at line 456 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracTwistedMass() [1/2]
quda::DiracTwistedMass::DiracTwistedMass (const DiracTwistedMass & dirac)
Definition at line 11 of file dirac_twisted_mass.cpp.
DiracTwistedMass() [2/2]
quda::DiracTwistedMass::DiracTwistedMass (const DiracParam & param, const int nDim)
Definition at line 8 of file dirac_twisted_mass.cpp.
~DiracTwistedMass()
quda::DiracTwistedMass::~DiracTwistedMass () virtual
Definition at line 14 of file dirac_twisted_mass.cpp.
Member Function Documentation
createCoarseOp()
void quda::DiracTwistedMass::createCoarseOp (GaugeField & Y, GaugeField & X, GaugeField & Xinv, GaugeField & Yhat, const Transfer & T, double kappa, double mu, double mu_factor = 0.) const virtual
Create the coarse twisted-mass operator.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
Xinv[out] Coarse clover inverse field
Yhat coarse preconditioned link field
kappa Kappa parameter for the coarse operator
mu TM mu parameter for the coarse operator
mu_factor multiplicative factor for the mu parameter
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedMassPC.
Definition at line 148 of file dirac_twisted_mass.cpp.
References a, c, quda::CoarseOp(), quda::Dirac::gauge, quda::Dirac::kappa, mu, mu_factor, QUDA_MATPC_INVALID, QUDA_TWISTED_MASS_DIRAC, and X.
M()
void quda::DiracTwistedMass::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedMassPC.
Definition at line 81 of file dirac_twisted_mass.cpp.
References a, b, quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), epsilon, errorQuda, quda::ColorSpinorField::Even(), in, quda::Dirac::kappa, mu, NdegTwistedDslashXpay(), quda::Dirac::newTmp(), out, QUDA_DEG_DSLASH_TWIST_XPAY, QUDA_EVEN_PARITY, QUDA_FULL_SITE_SUBSET, QUDA_NONDEG_DSLASH, QUDA_ODD_PARITY, QUDA_TWIST_INVALID, QUDA_TWIST_NO, QUDA_TWIST_SINGLET, quda::ColorSpinorField::SiteSubset(), tmp, quda::Dirac::tmp2, and TwistedDslashXpay().
Referenced by MdagM().
MdagM()
void quda::DiracTwistedMass::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedMassPC.
Definition at line 119 of file dirac_twisted_mass.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), in, M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), out, and quda::Dirac::tmp1.
Mu()
double quda::DiracTwistedMass::Mu () const inline virtual
Reimplemented from quda::Dirac.
Definition at line 494 of file dirac_quda.h.
References mu.
NdegTwistedDslash()
void quda::DiracTwistedMass::NdegTwistedDslash (ColorSpinorField & out, const ColorSpinorField & in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const protected
Definition at line 60 of file dirac_twisted_mass.cpp.
References a, b, c, quda::Dirac::commDim, d, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, in, quda::ndegTwistedMassDslashCuda(), out, parity, and quda::Dirac::profile.
Referenced by quda::DiracTwistedMassPC::Dslash().
NdegTwistedDslashXpay()
void quda::DiracTwistedMass::NdegTwistedDslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const ColorSpinorField & x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const protected
Definition at line 69 of file dirac_twisted_mass.cpp.
References a, b, c, quda::Dirac::commDim, d, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, in, quda::ndegTwistedMassDslashCuda(), out, parity, quda::Dirac::profile, and x.
Referenced by quda::DiracTwistedMassPC::DslashXpay(), M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedMassPC::prepare(), and quda::DiracTwistedMassPC::reconstruct().
operator=()
DiracTwistedMass & quda::DiracTwistedMass::operator= (const DiracTwistedMass & dirac)
Definition at line 16 of file dirac_twisted_mass.cpp.
References dirac, and quda::DiracWilson::operator=().
Referenced by quda::DiracTwistedMassPC::operator=().
prepare()
void quda::DiracTwistedMass::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedMassPC.
Definition at line 130 of file dirac_twisted_mass.cpp.
References b, errorQuda, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, src, and x.
reconstruct()
void quda::DiracTwistedMass::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedMassPC.
Definition at line 142 of file dirac_twisted_mass.cpp.
Twist()
void quda::DiracTwistedMass::Twist (ColorSpinorField & out, const ColorSpinorField & in) const
Definition at line 35 of file dirac_twisted_mass.cpp.
References in, out, QUDA_TWIST_GAMMA5_DIRECT, and twistedApply().
twistedApply()
void quda::DiracTwistedMass::twistedApply (ColorSpinorField & out, const ColorSpinorField & in, const QudaTwistGamma5Type twistType) const protected
Definition at line 25 of file dirac_twisted_mass.cpp.
References quda::ApplyTwistGamma(), quda::Dirac::checkParitySpinor(), quda::Dirac::dagger, epsilon, quda::Dirac::flops, in, quda::Dirac::kappa, mu, and out.
Referenced by quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedMassPC::reconstruct(), Twist(), and quda::DiracTwistedMassPC::TwistInv().
TwistedDslash()
void quda::DiracTwistedMass::TwistedDslash (ColorSpinorField & out, const ColorSpinorField & in, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const protected
Definition at line 40 of file dirac_twisted_mass.cpp.
References a, b, c, quda::Dirac::commDim, d, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, in, out, parity, quda::Dirac::profile, and quda::twistedMassDslashCuda().
Referenced by quda::DiracTwistedMassPC::Dslash().
TwistedDslashXpay()
void quda::DiracTwistedMass::TwistedDslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const ColorSpinorField & x, QudaParity parity, QudaTwistDslashType twistDslashType, double a, double b, double c, double d) const protected
Definition at line 49 of file dirac_twisted_mass.cpp.
References a, b, c, quda::Dirac::commDim, d, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, in, out, parity, quda::Dirac::profile, quda::twistedMassDslashCuda(), and x.
Referenced by quda::DiracTwistedMassPC::DslashXpay(), M(), and quda::DiracTwistedMassPC::M().
Member Data Documentation
epsilon
double quda::DiracTwistedMass::epsilon protected
Definition at line 460 of file dirac_quda.h.
Referenced by quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedMassPC::DslashXpay(), M(), quda::DiracTwistedMassPC::M(), and twistedApply().
mu
double quda::DiracTwistedMass::mu protected
Definition at line 459 of file dirac_quda.h.
Referenced by createCoarseOp(), quda::DiracTwistedMassPC::createCoarseOp(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedMassPC::DslashXpay(), M(), quda::DiracTwistedMassPC::M(), Mu(), and twistedApply().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_twisted_mass.cpp