QUDA: quda::Lanczos Class Reference
quda::Lanczos Class Reference
#include <lanczos_quda.h>
Public Member Functions
Lanczos (RitzMat &ritz_mat, QudaEigParam &eigParam, TimeProfile &profile)
virtual ~Lanczos ()
void operator() (double *alpha, double *beta, cudaColorSpinorField **Eig_Vec, cudaColorSpinorField &r, cudaColorSpinorField &Apsi, int k0, int m)
Public Member Functions inherited from quda::Eig_Solver
Eig_Solver (QudaEigParam &eigParam, TimeProfile &profile)
virtual ~Eig_Solver ()
bool convergence (const double &r2, const double &hq2, const double &r2_tol, const double &hq_tol)
void PrintStats (const char *, int k, const double &r2, const double &b2, const double &hq2)
void PrintSummary (const char *name, int k, const double &r2, const double &b2)
void GrandSchm_test (cudaColorSpinorField &psi, cudaColorSpinorField **Eig_Vec, int Nvec, double *delta)
Private Attributes
const RitzMat & ritz_mat
Additional Inherited Members
Static Public Member Functions inherited from quda::Eig_Solver
static Eig_Solver * create (QudaEigParam &param, RitzMat &ritz_mat, TimeProfile &profile)
Protected Attributes inherited from quda::Eig_Solver
QudaEigParam & eigParam
TimeProfile & profile
Detailed Description
Basic Lanczos algorithm
Definition at line 60 of file lanczos_quda.h.
Constructor & Destructor Documentation
Lanczos()
quda::Lanczos::Lanczos (RitzMat & ritz_mat, QudaEigParam & eigParam, TimeProfile & profile)
Definition at line 18 of file eig_lanczos_quda.cpp.
~Lanczos()
quda::Lanczos::~Lanczos () virtual
Definition at line 24 of file eig_lanczos_quda.cpp.
Member Function Documentation
operator()()
void quda::Lanczos::operator() (double * alpha, double * beta, cudaColorSpinorField ** Eig_Vec, cudaColorSpinorField & r, cudaColorSpinorField & Apsi, int k0, int m) virtual
Implements quda::Eig_Solver.
Definition at line 29 of file eig_lanczos_quda.cpp.
References quda::axpy(), quda::Eig_Solver::GrandSchm_test(), quda::norm2(), printfQuda, quda::Eig_Solver::profile, quda::QUDA_PROFILE_COMPUTE, quda::blas::reDotProduct(), ritz_mat, quda::sqrt(), and quda::zero().
Member Data Documentation
ritz_mat
const RitzMat& quda::Lanczos::ritz_mat private
Definition at line 63 of file lanczos_quda.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
include/lanczos_quda.h
lib/eig_lanczos_quda.cpp