QUDA: quda::DiracM Class Reference
quda::DiracM Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracM (const Dirac &d)
DiracM (const Dirac *d)
void operator() (ColorSpinorField &out, const ColorSpinorField &in) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const
int getStencilSteps () const
Public Member Functions inherited from quda::DiracMatrix
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
virtual ~DiracMatrix ()
unsigned long long flops () const
QudaMatPCType getMatPCType () const
std::string Type () const
bool isStaggered () const
const Dirac * Expose ()
Additional Inherited Members
Protected Attributes inherited from quda::DiracMatrix
const Dirac * dirac
Detailed Description
Definition at line 1014 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracM() [1/2]
quda::DiracM::DiracM (const Dirac & d) inline
Definition at line 1017 of file dirac_quda.h.
DiracM() [2/2]
quda::DiracM::DiracM (const Dirac * d) inline
Definition at line 1018 of file dirac_quda.h.
Member Function Documentation
getStencilSteps()
int quda::DiracM::getStencilSteps () const inline virtual
Implements quda::DiracMatrix.
Definition at line 1045 of file dirac_quda.h.
References quda::DiracMatrix::dirac, and quda::Dirac::getStencilSteps().
operator()() [1/3]
void quda::DiracM::operator() (ColorSpinorField & out, const ColorSpinorField & in) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1020 of file dirac_quda.h.
References quda::DiracMatrix::dirac, in, quda::Dirac::M(), and out.
operator()() [2/3]
void quda::DiracM::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1025 of file dirac_quda.h.
References quda::DiracMatrix::dirac, in, quda::Dirac::M(), out, tmp, and quda::Dirac::tmp1.
operator()() [3/3]
void quda::DiracM::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1033 of file dirac_quda.h.
References quda::DiracMatrix::dirac, in, quda::Dirac::M(), out, quda::Dirac::tmp1, and quda::Dirac::tmp2.
The documentation for this class was generated from the following file:
include/dirac_quda.h