QUDA: anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune Class Reference
anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune Class Reference
Public Member Functions
DslashPolicyTune (DslashCuda &dslash, cudaColorSpinorField *in, const int volume, const int *ghostFace, TimeProfile &profile)
virtual ~DslashPolicyTune ()
void apply (const cudaStream_t &stream)
int tuningIter () const
bool advanceAux (TuneParam &param) const
bool advanceTuneParam (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
long long flops () const
long long bytes () const
void preTune ()
void postTune ()
Private Member Functions
bool tuneGridDim () const
bool tuneAuxDim () const
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Attributes
DslashCuda & dslash
DslashParam & dslashParam
cudaColorSpinorField * in
const int volume
const int * ghostFace
TimeProfile & profile
Detailed Description
Definition at line 1895 of file dslash_policy.cuh.
Constructor & Destructor Documentation
DslashPolicyTune()
anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::DslashPolicyTune (DslashCuda & dslash, cudaColorSpinorField * in, const int volume, const int * ghostFace, TimeProfile & profile) inline
Definition at line 1910 of file dslash_policy.cuh.
References comm_enable_peer2peer(), comm_gdr_enabled(), comm_gpuid(), comm_peer2peer_enabled_global(), anonymous_namespace{dslash_policy.cuh}::config, device, disableProfileCount(), deg_tm_dslash_cuda_gen::dslash, dslash_comms, dslash_copy, dslash_exterior_compute, anonymous_namespace{dslash_policy.cuh}::dslash_init, dslash_interior_compute, dslash_pack_compute, anonymous_namespace{dslash_policy.cuh}::enable_policy(), enableProfileCount(), end, errorQuda, anonymous_namespace{dslash_policy.cuh}::first_active_p2p_policy, anonymous_namespace{dslash_policy.cuh}::first_active_policy, getenv(), quda::getKernelPackT(), getTuneCache(), getTuning(), getVerbosity(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, anonymous_namespace{dslash_policy.cuh}::p2p_policies(), anonymous_namespace{dslash_policy.cuh}::policies(), quda::policy, QUDA_SILENT, DslashParam::remote_write, quda::setKernelPackT(), setPolicyTuning(), strcmp(), streams, and warningQuda.
~DslashPolicyTune()
virtual anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::~DslashPolicyTune () inline virtual
Definition at line 2114 of file dslash_policy.cuh.
References setPolicyTuning().
Member Function Documentation
advanceAux()
bool anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::advanceAux (TuneParam & param) const inline
Definition at line 2162 of file dslash_policy.cuh.
References anonymous_namespace{dslash_policy.cuh}::first_active_p2p_policy, anonymous_namespace{dslash_policy.cuh}::first_active_policy, anonymous_namespace{dslash_policy.cuh}::p2p_policies(), param, and anonymous_namespace{dslash_policy.cuh}::policies().
advanceTuneParam()
bool anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::advanceTuneParam (TuneParam & param) const inline
Definition at line 2179 of file dslash_policy.cuh.
References param.
apply()
void anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::apply (const cudaStream_t & stream) inline
Definition at line 2116 of file dslash_policy.cuh.
References comm_enable_peer2peer(), comm_peer2peer_enabled_global(), anonymous_namespace{dslash_policy.cuh}::config, deg_tm_dslash_cuda_gen::dslash, errorQuda, quda::getKernelPackT(), getTuning(), in, p, anonymous_namespace{dslash_policy.cuh}::p2p_policies(), anonymous_namespace{dslash_policy.cuh}::policies(), QUDA_DEBUG_VERBOSE, DslashParam::remote_write, quda::setKernelPackT(), and quda::tuneLaunch().
bytes()
long long anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::bytes () const inline
Definition at line 2208 of file dslash_policy.cuh.
References KERNEL_POLICY, and DslashParam::kernel_type.
defaultTuneParam()
void anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::defaultTuneParam (TuneParam & param) const inline
Definition at line 2186 of file dslash_policy.cuh.
References anonymous_namespace{dslash_policy.cuh}::config, anonymous_namespace{dslash_policy.cuh}::first_active_p2p_policy, anonymous_namespace{dslash_policy.cuh}::first_active_policy, and param.
flops()
long long anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::flops () const inline
Definition at line 2200 of file dslash_policy.cuh.
References KERNEL_POLICY, and DslashParam::kernel_type.
initTuneParam()
void anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::initTuneParam (TuneParam & param) const inline
Definition at line 2181 of file dslash_policy.cuh.
References anonymous_namespace{dslash_policy.cuh}::config, anonymous_namespace{dslash_policy.cuh}::first_active_p2p_policy, anonymous_namespace{dslash_policy.cuh}::first_active_policy, and param.
postTune()
void anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::postTune () inline
Definition at line 2218 of file dslash_policy.cuh.
preTune()
void anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::preTune () inline
Definition at line 2216 of file dslash_policy.cuh.
sharedBytesPerBlock()
unsigned int anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::sharedBytesPerBlock (const TuneParam & param) const inline private
Definition at line 1907 of file dslash_policy.cuh.
sharedBytesPerThread()
unsigned int anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::sharedBytesPerThread () const inline private
Definition at line 1906 of file dslash_policy.cuh.
tuneAuxDim()
bool anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::tuneAuxDim () const inline private
Definition at line 1905 of file dslash_policy.cuh.
tuneGridDim()
bool anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::tuneGridDim () const inline private
Definition at line 1904 of file dslash_policy.cuh.
tuneKey()
TuneKey anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::tuneKey () const inline
Definition at line 2191 of file dslash_policy.cuh.
References comm_dim_topology_string(), KERNEL_POLICY, DslashParam::kernel_type, and strcat().
tuningIter()
int anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::tuningIter () const inline
Definition at line 2159 of file dslash_policy.cuh.
Member Data Documentation
dslash
DslashCuda& anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::dslash private
Definition at line 1897 of file dslash_policy.cuh.
dslashParam
DslashParam& anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::dslashParam private
Definition at line 1898 of file dslash_policy.cuh.
ghostFace
const int* anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::ghostFace private
Definition at line 1901 of file dslash_policy.cuh.
in
cudaColorSpinorField* anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::in private
Definition at line 1899 of file dslash_policy.cuh.
profile
TimeProfile& anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::profile private
Definition at line 1902 of file dslash_policy.cuh.
volume
const int anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::volume private
Definition at line 1900 of file dslash_policy.cuh.
The documentation for this class was generated from the following file:
lib/dslash_policy.cuh