QUDA: quda::KSForceComplete< Float, Oprod, Gauge, Mom > Class Template Reference
quda::KSForceComplete< Float, Oprod, Gauge, Mom > Class Template Reference
Public Member Functions
KSForceComplete (KSForceArg< Oprod, Gauge, Mom > &arg, const GaugeField &meta, QudaFieldLocation location)
virtual ~KSForceComplete ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneSharedBytes () const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
virtual bool tuneAuxDim () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize () const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
KSForceArg< Oprod, Gauge, Mom > arg
const GaugeField & meta
const QudaFieldLocation location
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename Float, typename Oprod, typename Gauge, typename Mom>
class quda::KSForceComplete< Float, Oprod, Gauge, Mom >
Definition at line 126 of file ks_force_quda.cu.
Constructor & Destructor Documentation
KSForceComplete()
template<typename Float, typename Oprod, typename Gauge, typename Mom> quda::KSForceComplete< Float, Oprod, Gauge, Mom >::KSForceComplete (KSForceArg< Oprod, Gauge, Mom > & arg, const GaugeField & meta, QudaFieldLocation location) inline
Definition at line 141 of file ks_force_quda.cu.
References quda::arg().
~KSForceComplete()
template<typename Float, typename Oprod, typename Gauge, typename Mom> virtual quda::KSForceComplete< Float, Oprod, Gauge, Mom >::~KSForceComplete () inline virtual
Definition at line 146 of file ks_force_quda.cu.
Member Function Documentation
apply()
template<typename Float, typename Oprod, typename Gauge, typename Mom> void quda::KSForceComplete< Float, Oprod, Gauge, Mom >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 148 of file ks_force_quda.cu.
References quda::arg(), blockDim, gridDim, and QUDA_CUDA_FIELD_LOCATION.
Referenced by quda::completeKSForce().
bytes()
template<typename Float, typename Oprod, typename Gauge, typename Mom> long long quda::KSForceComplete< Float, Oprod, Gauge, Mom >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 162 of file ks_force_quda.cu.
flops()
template<typename Float, typename Oprod, typename Gauge, typename Mom> long long quda::KSForceComplete< Float, Oprod, Gauge, Mom >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 161 of file ks_force_quda.cu.
References quda::arg().
Referenced by quda::completeKSForce().
minThreads()
template<typename Float, typename Oprod, typename Gauge, typename Mom> unsigned int quda::KSForceComplete< Float, Oprod, Gauge, Mom >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 138 of file ks_force_quda.cu.
References quda::arg().
sharedBytesPerBlock()
template<typename Float, typename Oprod, typename Gauge, typename Mom> unsigned int quda::KSForceComplete< Float, Oprod, Gauge, Mom >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 134 of file ks_force_quda.cu.
sharedBytesPerThread()
template<typename Float, typename Oprod, typename Gauge, typename Mom> unsigned int quda::KSForceComplete< Float, Oprod, Gauge, Mom >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 133 of file ks_force_quda.cu.
tuneGridDim()
template<typename Float, typename Oprod, typename Gauge, typename Mom> bool quda::KSForceComplete< Float, Oprod, Gauge, Mom >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 137 of file ks_force_quda.cu.
tuneKey()
template<typename Float, typename Oprod, typename Gauge, typename Mom> TuneKey quda::KSForceComplete< Float, Oprod, Gauge, Mom >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 159 of file ks_force_quda.cu.
References quda::LatticeField::VolString().
tuneSharedBytes()
template<typename Float, typename Oprod, typename Gauge, typename Mom> bool quda::KSForceComplete< Float, Oprod, Gauge, Mom >::tuneSharedBytes () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 136 of file ks_force_quda.cu.
Member Data Documentation
arg
template<typename Float, typename Oprod, typename Gauge, typename Mom> KSForceArg<Oprod, Gauge, Mom> quda::KSForceComplete< Float, Oprod, Gauge, Mom >::arg private
Definition at line 128 of file ks_force_quda.cu.
location
template<typename Float, typename Oprod, typename Gauge, typename Mom> const QudaFieldLocation quda::KSForceComplete< Float, Oprod, Gauge, Mom >::location private
Definition at line 130 of file ks_force_quda.cu.
meta
template<typename Float, typename Oprod, typename Gauge, typename Mom> const GaugeField& quda::KSForceComplete< Float, Oprod, Gauge, Mom >::meta private
Definition at line 129 of file ks_force_quda.cu.
The documentation for this class was generated from the following file:
lib/ks_force_quda.cu