QUDA: quda::WuppertalSmearing< Float, Ns, Nc, Arg > Class Template Reference
quda::WuppertalSmearing< Float, Ns, Nc, Arg > Class Template Reference
Public Member Functions
WuppertalSmearing (Arg &arg, const ColorSpinorField &meta)
virtual ~WuppertalSmearing ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y)
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
Protected Member Functions
long long flops () const
long long bytes () const
bool tuneGridDim () const
unsigned int minThreads () const
unsigned int maxBlockSize () const
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const ColorSpinorField & meta
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename Float, int Ns, int Nc, typename Arg>
class quda::WuppertalSmearing< Float, Ns, Nc, Arg >
Definition at line 150 of file color_spinor_wuppertal.cu.
Constructor & Destructor Documentation
WuppertalSmearing()
template<typename Float, int Ns, int Nc, typename Arg> quda::WuppertalSmearing< Float, Ns, Nc, Arg >::WuppertalSmearing (Arg & arg, const ColorSpinorField & meta) inline
Definition at line 169 of file color_spinor_wuppertal.cu.
References quda::Tunable::aux, quda::ColorSpinorField::AuxString(), comm_dim_partitioned_string(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta, strcat(), and strcpy().
~WuppertalSmearing()
template<typename Float, int Ns, int Nc, typename Arg> virtual quda::WuppertalSmearing< Float, Ns, Nc, Arg >::~WuppertalSmearing () inline virtual
Definition at line 174 of file color_spinor_wuppertal.cu.
Member Function Documentation
apply()
template<typename Float, int Ns, int Nc, typename Arg> void quda::WuppertalSmearing< Float, Ns, Nc, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 176 of file color_spinor_wuppertal.cu.
References quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg, quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::LatticeField::Location(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, quda::stream, and quda::tuneLaunch().
Referenced by quda::wuppertalStep().
bytes()
template<typename Float, int Ns, int Nc, typename Arg> long long quda::WuppertalSmearing< Float, Ns, Nc, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 160 of file color_spinor_wuppertal.cu.
References quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg, quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta, and quda::ColorSpinorField::VolumeCB().
flops()
template<typename Float, int Ns, int Nc, typename Arg> long long quda::WuppertalSmearing< Float, Ns, Nc, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 156 of file color_spinor_wuppertal.cu.
References quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg, quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta, and quda::ColorSpinorField::VolumeCB().
maxBlockSize()
template<typename Float, int Ns, int Nc, typename Arg> unsigned int quda::WuppertalSmearing< Float, Ns, Nc, Arg >::maxBlockSize () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 166 of file color_spinor_wuppertal.cu.
References quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg, and deviceProp.
minThreads()
template<typename Float, int Ns, int Nc, typename Arg> unsigned int quda::WuppertalSmearing< Float, Ns, Nc, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 165 of file color_spinor_wuppertal.cu.
References quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg.
tuneGridDim()
template<typename Float, int Ns, int Nc, typename Arg> bool quda::WuppertalSmearing< Float, Ns, Nc, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 164 of file color_spinor_wuppertal.cu.
tuneKey()
template<typename Float, int Ns, int Nc, typename Arg> TuneKey quda::WuppertalSmearing< Float, Ns, Nc, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 185 of file color_spinor_wuppertal.cu.
References quda::Tunable::aux, quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int Ns, int Nc, typename Arg> Arg& quda::WuppertalSmearing< Float, Ns, Nc, Arg >::arg protected
Definition at line 153 of file color_spinor_wuppertal.cu.
Referenced by quda::WuppertalSmearing< Float, Ns, Nc, Arg >::apply(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::bytes(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::flops(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::maxBlockSize(), and quda::WuppertalSmearing< Float, Ns, Nc, Arg >::minThreads().
meta
template<typename Float, int Ns, int Nc, typename Arg> const ColorSpinorField& quda::WuppertalSmearing< Float, Ns, Nc, Arg >::meta protected
Definition at line 154 of file color_spinor_wuppertal.cu.
Referenced by quda::WuppertalSmearing< Float, Ns, Nc, Arg >::apply(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::bytes(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::flops(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::tuneKey(), and quda::WuppertalSmearing< Float, Ns, Nc, Arg >::WuppertalSmearing().
The documentation for this class was generated from the following file:
lib/color_spinor_wuppertal.cu