QUDA: quda::DiracTwistedCloverPC Class Reference
quda::DiracTwistedCloverPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracTwistedCloverPC (const DiracTwistedCloverPC &dirac)
DiracTwistedCloverPC (const DiracParam &param, const int nDim)
virtual ~DiracTwistedCloverPC ()
DiracTwistedCloverPC & operator= (const DiracTwistedCloverPC &dirac)
void TwistCloverInv (ColorSpinorField &out, const ColorSpinorField &in, const int parity) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu, double mu_factor=0.) const
Create the coarse even-odd preconditioned twisted-clover operator. Unlike the Wilson operator, the coarsening of the preconditioned clover operator differs from that of the unpreconditioned clover operator, so we need to specialize it.
Public Member Functions inherited from quda::DiracTwistedClover
DiracTwistedClover (const DiracTwistedClover &dirac)
DiracTwistedClover (const DiracParam &param, const int nDim)
virtual ~DiracTwistedClover ()
DiracTwistedClover & operator= (const DiracTwistedClover &dirac)
void TwistClover (ColorSpinorField &out, const ColorSpinorField &in, const int parity) const
double Mu () const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracTwistedClover
void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
void twistedCloverApply (ColorSpinorField &out, const ColorSpinorField &in, const QudaTwistGamma5Type twistType, const int parity) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracTwistedClover
double mu
double epsilon
cudaCloverField & clover
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 596 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracTwistedCloverPC() [1/2]
quda::DiracTwistedCloverPC::DiracTwistedCloverPC (const DiracTwistedCloverPC & dirac)
Definition at line 126 of file dirac_twisted_clover.cpp.
DiracTwistedCloverPC() [2/2]
quda::DiracTwistedCloverPC::DiracTwistedCloverPC (const DiracParam & param, const int nDim)
Definition at line 128 of file dirac_twisted_clover.cpp.
~DiracTwistedCloverPC()
quda::DiracTwistedCloverPC::~DiracTwistedCloverPC () virtual
Definition at line 130 of file dirac_twisted_clover.cpp.
Member Function Documentation
createCoarseOp()
void quda::DiracTwistedCloverPC::createCoarseOp (GaugeField & Y, GaugeField & X, GaugeField & Xinv, GaugeField & Yhat, const Transfer & T, double kappa, double mu, double mu_factor = 0.) const virtual
Create the coarse even-odd preconditioned twisted-clover operator. Unlike the Wilson operator, the coarsening of the preconditioned clover operator differs from that of the unpreconditioned clover operator, so we need to specialize it.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
Xinv[out] Coarse clover inverse field
Yhat coarse preconditioned link field
kappa Kappa parameter for the coarse operator
mu TM mu parameter for the coarse operator
mu_factor multiplicative factor for the mu parameter
Reimplemented from quda::DiracTwistedClover.
Definition at line 358 of file dirac_twisted_clover.cpp.
References a, quda::DiracTwistedClover::clover, quda::CoarseOp(), quda::Dirac::gauge, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedClover::mu, mu_factor, QUDA_TWISTED_CLOVERPC_DIRAC, quda::ColorSpinorField::TwistFlavor(), quda::Transfer::Vectors(), and X.
Dslash()
void quda::DiracTwistedCloverPC::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 152 of file dirac_twisted_clover.cpp.
References a, b, dslash_cuda_gen::clover, commDim(), deg_tm_dslash_cuda_gen::dagger, errorQuda, quda::blas::flops, in, kappa, mu, out, parity, QUDA_DEG_CLOVER_TWIST_INV_DSLASH, QUDA_DEG_DSLASH_CLOVER_TWIST_INV, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_INVALID, QUDA_TWIST_NO, QUDA_TWIST_SINGLET, quda::twistedCloverDslashCuda(), quda::ColorSpinorField::TwistFlavor(), and quda::ColorSpinorField::Volume().
Referenced by M().
DslashXpay()
void quda::DiracTwistedCloverPC::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 189 of file dirac_twisted_clover.cpp.
References a, b, dslash_cuda_gen::clover, commDim(), deg_tm_dslash_cuda_gen::dagger, errorQuda, quda::blas::flops, in, kappa, mu, out, parity, QUDA_DEG_CLOVER_TWIST_INV_DSLASH, QUDA_DEG_DSLASH_CLOVER_TWIST_INV, QUDA_TWIST_INVALID, QUDA_TWIST_NO, QUDA_TWIST_SINGLET, quda::twistedCloverDslashCuda(), quda::ColorSpinorField::TwistFlavor(), quda::ColorSpinorField::Volume(), and x.
Referenced by M().
M()
void quda::DiracTwistedCloverPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracTwistedClover.
Definition at line 227 of file dirac_twisted_clover.cpp.
References a, quda::DiracTwistedClover::clover, quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::deleteTmp(), Dslash(), DslashXpay(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::Dirac::kappa, quda::Dirac::matpcType, quda::DiracTwistedClover::mu, quda::Dirac::newTmp(), out, parity, quda::Dirac::profile, QUDA_DEG_DSLASH_CLOVER_TWIST_XPAY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_SINGLET, quda::Dirac::tmp1, TwistCloverInv(), and quda::twistedCloverDslashCuda().
Referenced by MdagM().
MdagM()
void quda::DiracTwistedCloverPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracTwistedClover.
Definition at line 267 of file dirac_twisted_clover.cpp.
References quda::Dirac::deleteTmp(), in, M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), out, and quda::Dirac::tmp2.
operator=()
DiracTwistedCloverPC & quda::DiracTwistedCloverPC::operator= (const DiracTwistedCloverPC & dirac)
Definition at line 135 of file dirac_twisted_clover.cpp.
References dirac, and quda::DiracTwistedClover::operator=().
prepare()
void quda::DiracTwistedCloverPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracTwistedClover.
Definition at line 276 of file dirac_twisted_clover.cpp.
References b, quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, QUDA_TWIST_SINGLET, src, quda::Dirac::tmp1, TwistCloverInv(), and x.
reconstruct()
void quda::DiracTwistedCloverPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracTwistedClover.
Definition at line 329 of file dirac_twisted_clover.cpp.
References b, quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, QUDA_TWIST_SINGLET, quda::Dirac::tmp1, TwistCloverInv(), and x.
TwistCloverInv()
void quda::DiracTwistedCloverPC::TwistCloverInv (ColorSpinorField & out, const ColorSpinorField & in, const int parity) const
Definition at line 144 of file dirac_twisted_clover.cpp.
References in, out, parity, QUDA_TWIST_GAMMA5_INVERSE, and quda::DiracTwistedClover::twistedCloverApply().
Referenced by M(), prepare(), and reconstruct().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_twisted_clover.cpp