QUDA: quda::DiracMdagM Class Reference
quda::DiracMdagM Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracMdagM (const Dirac &d)
DiracMdagM (const Dirac *d)
void operator() (ColorSpinorField &out, const ColorSpinorField &in) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const
int getStencilSteps () const
Public Member Functions inherited from quda::DiracMatrix
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
virtual ~DiracMatrix ()
unsigned long long flops () const
QudaMatPCType getMatPCType () const
std::string Type () const
bool isStaggered () const
const Dirac * Expose ()
Public Attributes
double shift
Shift term added onto operator (M^dag M + shift)
Additional Inherited Members
Protected Attributes inherited from quda::DiracMatrix
const Dirac * dirac
Detailed Description
Definition at line 1051 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMdagM() [1/2]
quda::DiracMdagM::DiracMdagM (const Dirac & d) inline
Definition at line 1054 of file dirac_quda.h.
DiracMdagM() [2/2]
quda::DiracMdagM::DiracMdagM (const Dirac * d) inline
Definition at line 1055 of file dirac_quda.h.
Member Function Documentation
getStencilSteps()
int quda::DiracMdagM::getStencilSteps () const inline virtual
Implements quda::DiracMatrix.
Definition at line 1086 of file dirac_quda.h.
References quda::DiracMatrix::dirac, and quda::Dirac::getStencilSteps().
operator()() [1/3]
void quda::DiracMdagM::operator() (ColorSpinorField & out, const ColorSpinorField & in) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1060 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracMatrix::dirac, in, quda::Dirac::MdagM(), out, and shift.
operator()() [2/3]
void quda::DiracMdagM::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1066 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracMatrix::dirac, in, quda::Dirac::MdagM(), out, shift, tmp, and quda::Dirac::tmp1.
operator()() [3/3]
void quda::DiracMdagM::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1074 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracMatrix::dirac, in, quda::Dirac::MdagM(), out, shift, quda::Dirac::tmp1, and quda::Dirac::tmp2.
Member Data Documentation
shift
double quda::DiracMdagM::shift
Shift term added onto operator (M^dag M + shift)
Definition at line 1058 of file dirac_quda.h.
Referenced by invertMultiShiftQuda(), and operator()().
The documentation for this class was generated from the following file:
include/dirac_quda.h