QUDA: DslashCuda Class Reference
DslashCuda Class Reference
Public Member Functions
DslashCuda (cudaColorSpinorField *out, const cudaColorSpinorField *in, const cudaColorSpinorField *x, const GaugeField &gauge, const int parity, const int dagger, const int *commOverride)
virtual ~DslashCuda ()
virtual TuneKey tuneKey () const
const char * getAux (KernelType type) const
void setAux (KernelType type, const char *aux_)
void augmentAux (KernelType type, const char *extra)
virtual int Nface () const
int Dagger () const
virtual void preTune ()
virtual void postTune ()
virtual long long flops () const
virtual long long bytes () const
Public Attributes
DslashParam dslashParam
Protected Member Functions
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
bool tuneAuxDim () const
unsigned int minThreads () const
void fillAuxBase ()
Set the base strings used by the different dslash kernel types for autotuning.
void fillAux (KernelType kernel_type, const char *kernel_str)
Specialize the auxiliary strings for each kernel type.
void setParam ()
Set the dslashParam for the current multi-GPU parameters (set these at the last minute to ensure we always use the correct ones while policy autotuning).
Protected Attributes
cudaColorSpinorField * out
const cudaColorSpinorField * in
const cudaColorSpinorField * x
const GaugeField & gauge
const QudaReconstructType reconstruct
char * saveOut
char * saveOutNorm
const int dagger
char aux_base [TuneKey::aux_n]
char aux [8][TuneKey::aux_n]
Static Protected Attributes
static bool init = false
static char ghost_str [TuneKey::aux_n]
Detailed Description
Definition at line 365 of file dslash_quda.cuh.
Constructor & Destructor Documentation
DslashCuda()
DslashCuda::DslashCuda (cudaColorSpinorField * out, const cudaColorSpinorField * in, const cudaColorSpinorField * x, const GaugeField & gauge, const int parity, const int dagger, const int * commOverride) inline
Definition at line 460 of file dslash_quda.cuh.
References DslashParam::An2, DslashParam::anisotropy, DslashParam::anisotropy_f, bindGaugeTex(), DslashParam::coeff, DslashParam::coeff_f, comm_coord(), comm_dim(), comm_dim_partitioned(), DslashParam::commDim, DslashParam::dc, dim, dslashParam, errorQuda, EXTERIOR_KERNEL_ALL, EXTERIOR_KERNEL_T, EXTERIOR_KERNEL_X, EXTERIOR_KERNEL_Y, EXTERIOR_KERNEL_Z, f, fillAux(), fillAuxBase(), float, gauge, DslashParam::gauge_fixed, DslashParam::gauge_stride, ghost_str, DslashParam::ghostDim, DslashParam::ghostNormOffset, DslashParam::ghostOffset, fused_exterior_ndeg_tm_dslash_cuda_gen::i, DslashParam::in, in, init, DslashParam::inNorm, INTERIOR_KERNEL, KERNEL_POLICY, DslashParam::No2, DslashParam::out, out, DslashParam::outNorm, DslashParam::parity, parity, DslashParam::Pt0, DslashParam::PtNm1, QUDA_PERIODIC_T, quda::setPackComms(), DslashParam::sp_stride, strcat(), strcpy(), DslashParam::t_boundary, DslashParam::t_boundary_f, DslashParam::TB2, DslashParam::twist_a, DslashParam::twist_b, DslashParam::x, x, and DslashParam::xNorm.
~DslashCuda()
virtual DslashCuda::~DslashCuda () inline virtual
Definition at line 552 of file dslash_quda.cuh.
References gauge, and unbindGaugeTex().
Member Function Documentation
augmentAux()
void DslashCuda::augmentAux (KernelType type, const char * extra) inline
Definition at line 564 of file dslash_quda.cuh.
References aux, and strcat().
bytes()
virtual long long DslashCuda::bytes () const inline virtual
Definition at line 693 of file dslash_quda.cuh.
References DslashParam::commDim, d, dslashParam, EXTERIOR_KERNEL_ALL, EXTERIOR_KERNEL_T, EXTERIOR_KERNEL_X, EXTERIOR_KERNEL_Y, EXTERIOR_KERNEL_Z, float, in, INTERIOR_KERNEL, KERNEL_POLICY, DslashParam::kernel_type, reconstruct, and x.
Dagger()
int DslashCuda::Dagger () const inline
Definition at line 570 of file dslash_quda.cuh.
References dagger.
fillAux()
void DslashCuda::fillAux (KernelType kernel_type, const char * kernel_str) inline protected
Specialize the auxiliary strings for each kernel type.
Parameters
[in] kernel_type The kernel_type we are generating the string got
[in] kernel_str String corresponding to the kernel type
Definition at line 418 of file dslash_quda.cuh.
References aux, aux_base, ghost_str, INTERIOR_KERNEL, strcat(), and strcpy().
Referenced by DslashCuda().
fillAuxBase()
void DslashCuda::fillAuxBase () inline protected
Set the base strings used by the different dslash kernel types for autotuning.
Definition at line 390 of file dslash_quda.cuh.
References aux_base, DslashParam::commDim, dagger, dslashParam, QUDA_RECONSTRUCT_12, QUDA_RECONSTRUCT_13, QUDA_RECONSTRUCT_8, QUDA_RECONSTRUCT_9, QUDA_RECONSTRUCT_NO, reconstruct, strcat(), strcpy(), and x.
Referenced by DslashCuda().
flops()
virtual long long DslashCuda::flops () const inline virtual
Definition at line 651 of file dslash_quda.cuh.
References DslashParam::commDim, d, dslashParam, EXTERIOR_KERNEL_ALL, EXTERIOR_KERNEL_T, EXTERIOR_KERNEL_X, EXTERIOR_KERNEL_Y, EXTERIOR_KERNEL_Z, in, INTERIOR_KERNEL, KERNEL_POLICY, DslashParam::kernel_type, and x.
getAux()
const char* DslashCuda::getAux (KernelType type) const inline
Definition at line 556 of file dslash_quda.cuh.
References aux.
minThreads()
unsigned int DslashCuda::minThreads () const inline protected
Definition at line 381 of file dslash_quda.cuh.
References dslashParam, and DslashParam::threads.
Nface()
virtual int DslashCuda::Nface () const inline virtual
Definition at line 568 of file dslash_quda.cuh.
postTune()
virtual void DslashCuda::postTune () inline virtual
Definition at line 626 of file dslash_quda.cuh.
References out.
preTune()
virtual void DslashCuda::preTune () inline virtual
Definition at line 621 of file dslash_quda.cuh.
References out.
setAux()
void DslashCuda::setAux (KernelType type, const char * aux_) inline
Definition at line 560 of file dslash_quda.cuh.
References aux, and strcpy().
setParam()
void DslashCuda::setParam () inline protected
Set the dslashParam for the current multi-GPU parameters (set these at the last minute to ensure we always use the correct ones while policy autotuning).
Definition at line 429 of file dslash_quda.cuh.
References comm_peer2peer_enabled(), dim, dslashParam, float, quda::getKernelPackT(), DslashParam::ghost, DslashParam::ghostNorm, in, INTERIOR_KERNEL, DslashParam::kernel_type, DslashParam::tProjScale, and DslashParam::tProjScale_f.
sharedBytesPerBlock()
unsigned int DslashCuda::sharedBytesPerBlock (const TuneParam & param) const inline protected
Definition at line 377 of file dslash_quda.cuh.
tuneAuxDim()
bool DslashCuda::tuneAuxDim () const inline protected
Definition at line 379 of file dslash_quda.cuh.
tuneGridDim()
bool DslashCuda::tuneGridDim () const inline protected
Definition at line 378 of file dslash_quda.cuh.
tuneKey()
virtual TuneKey DslashCuda::tuneKey () const inline virtual
Definition at line 553 of file dslash_quda.cuh.
References aux, dslashParam, in, and DslashParam::kernel_type.
Member Data Documentation
aux
char DslashCuda::aux[8][TuneKey::aux_n] protected
Definition at line 383 of file dslash_quda.cuh.
Referenced by augmentAux(), fillAux(), getAux(), setAux(), and tuneKey().
aux_base
char DslashCuda::aux_base[TuneKey::aux_n] protected
Definition at line 382 of file dslash_quda.cuh.
Referenced by fillAux(), and fillAuxBase().
dagger
const int DslashCuda::dagger protected
Definition at line 374 of file dslash_quda.cuh.
Referenced by Dagger(), and fillAuxBase().
dslashParam
DslashParam DslashCuda::dslashParam
Definition at line 458 of file dslash_quda.cuh.
Referenced by bytes(), DslashCuda(), fillAuxBase(), flops(), minThreads(), setParam(), and tuneKey().
gauge
const GaugeField& DslashCuda::gauge protected
Definition at line 371 of file dslash_quda.cuh.
Referenced by DslashCuda(), and ~DslashCuda().
ghost_str
char DslashCuda::ghost_str static protected
Definition at line 384 of file dslash_quda.cuh.
Referenced by DslashCuda(), and fillAux().
in
const cudaColorSpinorField* DslashCuda::in protected
Definition at line 369 of file dslash_quda.cuh.
Referenced by bytes(), DslashCuda(), flops(), setParam(), and tuneKey().
init
bool DslashCuda::init = false static protected
Definition at line 375 of file dslash_quda.cuh.
Referenced by DslashCuda().
out
cudaColorSpinorField* DslashCuda::out protected
Definition at line 368 of file dslash_quda.cuh.
Referenced by DslashCuda(), postTune(), and preTune().
reconstruct
const QudaReconstructType DslashCuda::reconstruct protected
Definition at line 372 of file dslash_quda.cuh.
Referenced by bytes(), and fillAuxBase().
saveOut
char* DslashCuda::saveOut protected
Definition at line 373 of file dslash_quda.cuh.
saveOutNorm
char * DslashCuda::saveOutNorm protected
Definition at line 373 of file dslash_quda.cuh.
x
const cudaColorSpinorField* DslashCuda::x protected
Definition at line 370 of file dslash_quda.cuh.
Referenced by bytes(), DslashCuda(), fillAuxBase(), and flops().
The documentation for this class was generated from the following file:
lib/dslash_quda.cuh