QUDA: quda::GaussSpinor< FloatIn, Ns, Nc, InOrder > Class Template Reference
quda::GaussSpinor< FloatIn, Ns, Nc, InOrder > Class Template Reference
Public Member Functions
GaussSpinor (InOrder &in, const ColorSpinorField &meta, RNG &rngstate)
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
void preTune ()
void postTune ()
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize () const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
InOrder & in
const ColorSpinorField & meta
RNG & rngstate
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename FloatIn, int Ns, int Nc, typename InOrder>
class quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >
Definition at line 61 of file spinor_gauss.cu.
Constructor & Destructor Documentation
GaussSpinor()
template<typename FloatIn, int Ns, int Nc, typename InOrder> quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::GaussSpinor (InOrder & in, const ColorSpinorField & meta, RNG & rngstate) inline
Definition at line 75 of file spinor_gauss.cu.
Member Function Documentation
apply()
template<typename FloatIn, int Ns, int Nc, typename InOrder> void quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 78 of file spinor_gauss.cu.
References quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, in, quda::LatticeField::Location(), QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, quda::stream, quda::tuneLaunch(), and quda::ColorSpinorField::VolumeCB().
Referenced by quda::gaussSpinor().
bytes()
template<typename FloatIn, int Ns, int Nc, typename InOrder> long long quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 92 of file spinor_gauss.cu.
References in.
flops()
template<typename FloatIn, int Ns, int Nc, typename InOrder> long long quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 91 of file spinor_gauss.cu.
minThreads()
template<typename FloatIn, int Ns, int Nc, typename InOrder> unsigned int quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 72 of file spinor_gauss.cu.
References quda::ColorSpinorField::VolumeCB().
postTune()
template<typename FloatIn, int Ns, int Nc, typename InOrder> void quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 97 of file spinor_gauss.cu.
References quda::RNG::restore().
preTune()
template<typename FloatIn, int Ns, int Nc, typename InOrder> void quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 94 of file spinor_gauss.cu.
References quda::RNG::backup().
sharedBytesPerBlock()
template<typename FloatIn, int Ns, int Nc, typename InOrder> unsigned int quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 69 of file spinor_gauss.cu.
sharedBytesPerThread()
template<typename FloatIn, int Ns, int Nc, typename InOrder> unsigned int quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 67 of file spinor_gauss.cu.
tuneGridDim()
template<typename FloatIn, int Ns, int Nc, typename InOrder> bool quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 71 of file spinor_gauss.cu.
tuneKey()
template<typename FloatIn, int Ns, int Nc, typename InOrder> TuneKey quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 89 of file spinor_gauss.cu.
References quda::ColorSpinorField::AuxString(), and quda::LatticeField::VolString().
Member Data Documentation
in
template<typename FloatIn, int Ns, int Nc, typename InOrder> InOrder& quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::in private
Definition at line 62 of file spinor_gauss.cu.
meta
template<typename FloatIn, int Ns, int Nc, typename InOrder> const ColorSpinorField& quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::meta private
Definition at line 63 of file spinor_gauss.cu.
rngstate
template<typename FloatIn, int Ns, int Nc, typename InOrder> RNG& quda::GaussSpinor< FloatIn, Ns, Nc, InOrder >::rngstate private
Definition at line 64 of file spinor_gauss.cu.
The documentation for this class was generated from the following file:
lib/spinor_gauss.cu