QUDA: LoadStore< Real > Class Template Reference
LoadStore< Real > Class Template Reference
Public Member Functions
LoadStore (int vol)
void loadMatrixFromField (const Real *const field, int oddBit, int half_lattice_index, Matrix< 3, std::complex< Real > > *const mat) const
void loadMatrixFromField (const Real *const field, int oddBit, int dir, int half_lattice_index, Matrix< 3, std::complex< Real > > *const mat) const
void storeMatrixToField (const Matrix< 3, std::complex< Real > > &mat, int oddBit, int half_lattice_index, Real *const field) const
void addMatrixToField (const Matrix< 3, std::complex< Real > > &mat, int oddBit, int half_lattice_index, Real coeff, Real *const) const
void addMatrixToField (const Matrix< 3, std::complex< Real > > &mat, int oddBit, int dir, int half_lattice_index, Real coeff, Real *const) const
void storeMatrixToMomentumField (const Matrix< 3, std::complex< Real > > &mat, int oddBit, int dir, int half_lattice_index, Real coeff, Real *const) const
Real getData (const Real *const field, int idx, int dir, int oddBit, int offset, int hfv) const
void addData (Real *const field, int idx, int dir, int oddBit, int offset, Real, int hfv) const
int half_idx_conversion_ex2normal (int half_lattice_index, const int *dim, int oddBit) const
int half_idx_conversion_normal2ex (int half_lattice_index, const int *dim, int oddBit) const
Private Attributes
const int volume
const int half_volume
Detailed Description
template<class Real>
class LoadStore< Real >
Definition at line 311 of file hisq_force_reference2.cpp.
Constructor & Destructor Documentation
LoadStore()
template<class Real> LoadStore< Real >::LoadStore (int vol) inline
Definition at line 316 of file hisq_force_reference2.cpp.
Member Function Documentation
addData()
template<class Real > void LoadStore< Real >::addData (Real *const field, int idx, int dir, int oddBit, int offset, Real v, int hfv) const
Definition at line 405 of file hisq_force_reference2.cpp.
References gauge_order, idx, offset, and QUDA_MILC_GAUGE_ORDER.
addMatrixToField() [1/2]
template<class Real > void LoadStore< Real >::addMatrixToField (const Matrix< 3, std::complex< Real > > & mat, int oddBit, int half_lattice_index, Real coeff, Real * const field) const
Definition at line 487 of file hisq_force_reference2.cpp.
References dw_dslash_4D_cuda_gen::coeff(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, mat(), offset, Vh, and Vh_ex.
Referenced by computeAllLinkSite(), computeLongLinkSite(), computeMiddleLinkSite(), computeOneLinkSite(), and computeSideLinkSite().
addMatrixToField() [2/2]
template<class Real > void LoadStore< Real >::addMatrixToField (const Matrix< 3, std::complex< Real > > & mat, int oddBit, int dir, int half_lattice_index, Real coeff, Real * const field) const
Definition at line 513 of file hisq_force_reference2.cpp.
References dw_dslash_4D_cuda_gen::coeff(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, mat(), offset, Vh, and Vh_ex.
getData()
template<class Real > Real LoadStore< Real >::getData (const Real *const field, int idx, int dir, int oddBit, int offset, int hfv) const
Definition at line 396 of file hisq_force_reference2.cpp.
References gauge_order, idx, offset, and QUDA_MILC_GAUGE_ORDER.
half_idx_conversion_ex2normal()
template<class Real > int LoadStore< Real >::half_idx_conversion_ex2normal (int half_lattice_index, const int * dim, int oddBit) const
Definition at line 336 of file hisq_force_reference2.cpp.
References dim, E1, E1h, E2, E3, idx, sid, za, and zb.
half_idx_conversion_normal2ex()
template<class Real > int LoadStore< Real >::half_idx_conversion_normal2ex (int half_lattice_index, const int * dim, int oddBit) const
Definition at line 365 of file hisq_force_reference2.cpp.
References dim, E1, E2, E3, idx, sid, za, and zb.
Referenced by completeForceSite(), computeLongLinkSite(), and computeOneLinkSite().
loadMatrixFromField() [1/2]
template<class Real > void LoadStore< Real >::loadMatrixFromField (const Real *const field, int oddBit, int half_lattice_index, Matrix< 3, std::complex< Real > > *const mat) const
Definition at line 417 of file hisq_force_reference2.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, offset, Vh, and Vh_ex.
Referenced by completeForceSite(), computeAllLinkSite(), computeLongLinkSite(), computeMiddleLinkSite(), computeOneLinkSite(), and computeSideLinkSite().
loadMatrixFromField() [2/2]
template<class Real > void LoadStore< Real >::loadMatrixFromField (const Real *const field, int oddBit, int dir, int half_lattice_index, Matrix< 3, std::complex< Real > > *const mat) const
Definition at line 440 of file hisq_force_reference2.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, offset, Vh, and Vh_ex.
storeMatrixToField()
template<class Real > void LoadStore< Real >::storeMatrixToField (const Matrix< 3, std::complex< Real > > & mat, int oddBit, int half_lattice_index, Real *const field) const
Definition at line 465 of file hisq_force_reference2.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, mat(), offset, Vh, and Vh_ex.
Referenced by computeMiddleLinkSite().
storeMatrixToMomentumField()
template<class Real > void LoadStore< Real >::storeMatrixToMomentumField (const Matrix< 3, std::complex< Real > > & mat, int oddBit, int dir, int half_lattice_index, Real coeff, Real * const field) const
Definition at line 543 of file hisq_force_reference2.cpp.
References dw_dslash_4D_cuda_gen::coeff(), and mat().
Referenced by completeForceSite().
Member Data Documentation
half_volume
template<class Real> const int LoadStore< Real >::half_volume private
Definition at line 314 of file hisq_force_reference2.cpp.
volume
template<class Real> const int LoadStore< Real >::volume private
Definition at line 313 of file hisq_force_reference2.cpp.
The documentation for this class was generated from the following file:
tests/hisq_force_reference2.cpp