QUDA: quda::RitzMat Class Reference
quda::RitzMat Class Reference
#include <ritz_quda.h>
Public Member Functions
RitzMat (DiracMatrix &d, const QudaEigParam &param)
RitzMat (DiracMatrix *d, const QudaEigParam &param)
virtual ~RitzMat ()
void operator() (cudaColorSpinorField &out, const cudaColorSpinorField &in) const
Protected Member Functions
bool newTmp (cudaColorSpinorField **tmp, const cudaColorSpinorField &a) const
void deleteTmp (cudaColorSpinorField **a, const bool &reset) const
Protected Attributes
const DiracMatrix & dirac_mat
int N_Poly
double shift
double * cheby_param
cudaColorSpinorField * tmp1
cudaColorSpinorField * tmp2
Friends
class DiracMatrix
Detailed Description
Ritz matrix is targeted matrix object what we want to calculate its eigen values and eigen vectors. In lattice QCD application, this is normally Dirac operator
Definition at line 19 of file ritz_quda.h.
Constructor & Destructor Documentation
RitzMat() [1/2]
quda::RitzMat::RitzMat (DiracMatrix & d, const QudaEigParam & param) inline
Definition at line 36 of file ritz_quda.h.
RitzMat() [2/2]
quda::RitzMat::RitzMat (DiracMatrix * d, const QudaEigParam & param) inline
Definition at line 40 of file ritz_quda.h.
~RitzMat()
quda::RitzMat::~RitzMat () virtual
Definition at line 55 of file ritz_quda.cpp.
Member Function Documentation
deleteTmp()
void quda::RitzMat::deleteTmp (cudaColorSpinorField ** a, const bool & reset) const protected
Definition at line 64 of file ritz_quda.cpp.
References a.
Referenced by operator()().
newTmp()
bool quda::RitzMat::newTmp (cudaColorSpinorField ** tmp, const cudaColorSpinorField & a) const protected
Definition at line 56 of file ritz_quda.cpp.
References a, param, QUDA_ZERO_FIELD_CREATE, and tmp.
Referenced by operator()().
operator()()
void quda::RitzMat::operator() (cudaColorSpinorField & out, const cudaColorSpinorField & in) const
Definition at line 17 of file ritz_quda.cpp.
References axpby(), quda::axpy(), cheby_param, deleteTmp(), dirac_mat, fabs(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, N_Poly, newTmp(), out, quda::pow(), shift, tmp1, and tmp2.
Friends And Related Function Documentation
DiracMatrix
friend class DiracMatrix friend
Definition at line 21 of file ritz_quda.h.
Member Data Documentation
cheby_param
double* quda::RitzMat::cheby_param protected
Definition at line 27 of file ritz_quda.h.
Referenced by operator()().
dirac_mat
const DiracMatrix& quda::RitzMat::dirac_mat protected
Definition at line 24 of file ritz_quda.h.
Referenced by operator()().
N_Poly
int quda::RitzMat::N_Poly protected
Definition at line 25 of file ritz_quda.h.
Referenced by operator()().
shift
double quda::RitzMat::shift protected
Definition at line 26 of file ritz_quda.h.
Referenced by operator()().
tmp1
cudaColorSpinorField* quda::RitzMat::tmp1 mutable protected
Definition at line 29 of file ritz_quda.h.
Referenced by operator()().
tmp2
cudaColorSpinorField* quda::RitzMat::tmp2 mutable protected
Definition at line 30 of file ritz_quda.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
include/ritz_quda.h
lib/ritz_quda.cpp