QUDA: quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg > Class Template Reference
quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg > Class Template Reference
Public Member Functions
CopyColorSpinor (Arg &arg, const ColorSpinorField &out, const ColorSpinorField &in, QudaFieldLocation location)
virtual ~CopyColorSpinor ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool advanceSharedBytes (TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y)
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize () const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
Arg & arg
const ColorSpinorField & out
const ColorSpinorField & in
const QudaFieldLocation location
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Static Private Attributes
static constexpr int Ns = 4
Detailed Description
template<typename FloatOut, typename FloatIn, int Nc, typename Arg>
class quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >
Definition at line 191 of file copy_color_spinor.cuh.
Constructor & Destructor Documentation
CopyColorSpinor()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::CopyColorSpinor (Arg & arg, const ColorSpinorField & out, const ColorSpinorField & in, QudaFieldLocation location) inline
Definition at line 206 of file copy_color_spinor.cuh.
References quda::arg(), errorQuda, in, out, QUDA_CHIRAL_GAMMA_BASIS, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, and QUDA_UKQCD_GAMMA_BASIS.
~CopyColorSpinor()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > virtual quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::~CopyColorSpinor () inline virtual
Definition at line 224 of file copy_color_spinor.cuh.
Member Function Documentation
advanceSharedBytes()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > bool quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::advanceSharedBytes (TuneParam & param) const inline private virtual
The goal here is to throttle the number of thread blocks per SM by over-allocating shared memory (in order to improve L2 utilization, etc.). We thus request the smallest amount of dynamic shared memory that guarantees throttling to a given number of blocks, in order to allow some extra leeway.
Reimplemented from quda::Tunable.
Definition at line 201 of file copy_color_spinor.cuh.
apply()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > void quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 226 of file copy_color_spinor.cuh.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, in, out, QUDA_CHIRAL_GAMMA_BASIS, QUDA_CPU_FIELD_LOCATION, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_UKQCD_GAMMA_BASIS, quda::TuneParam::shared_bytes, quda::stream, and quda::tuneLaunch().
bytes()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > long long quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 262 of file copy_color_spinor.cuh.
References quda::arg().
flops()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > long long quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 261 of file copy_color_spinor.cuh.
minThreads()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > unsigned int quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 203 of file copy_color_spinor.cuh.
References in.
sharedBytesPerBlock()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > unsigned int quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 200 of file copy_color_spinor.cuh.
sharedBytesPerThread()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > unsigned int quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::sharedBytesPerThread () const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 199 of file copy_color_spinor.cuh.
tuneGridDim()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > bool quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 202 of file copy_color_spinor.cuh.
tuneKey()
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > TuneKey quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 260 of file copy_color_spinor.cuh.
References in.
Member Data Documentation
arg
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > Arg& quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::arg private
Definition at line 193 of file copy_color_spinor.cuh.
in
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > const ColorSpinorField& quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::in private
Definition at line 195 of file copy_color_spinor.cuh.
location
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > const QudaFieldLocation quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::location private
Definition at line 196 of file copy_color_spinor.cuh.
Ns
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > constexpr int quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::Ns = 4 static private
Definition at line 192 of file copy_color_spinor.cuh.
out
template<typename FloatOut , typename FloatIn , int Nc, typename Arg > const ColorSpinorField& quda::CopyColorSpinor< FloatOut, FloatIn, 4, Nc, Arg >::out private
Definition at line 194 of file copy_color_spinor.cuh.
The documentation for this class was generated from the following file:
lib/copy_color_spinor.cuh