QUDA: quda::DiracDomainWall4DPC Class Reference
quda::DiracDomainWall4DPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracDomainWall4DPC (const DiracParam &param)
DiracDomainWall4DPC (const DiracDomainWall4DPC &dirac)
virtual ~DiracDomainWall4DPC ()
DiracDomainWall4DPC & operator= (const DiracDomainWall4DPC &dirac)
void Dslash4 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5inv (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const double &kappa5) const
void Dslash4Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash5Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash5invXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const double &kappa5, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracDomainWallPC
DiracDomainWallPC (const DiracParam &param)
DiracDomainWallPC (const DiracDomainWallPC &dirac)
virtual ~DiracDomainWallPC ()
DiracDomainWallPC & operator= (const DiracDomainWallPC &dirac)
Public Member Functions inherited from quda::DiracDomainWall
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, GaugeField &Xinv, GaugeField &Yhat, const Transfer &T, double kappa, double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracDomainWall
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaTune tune
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 363 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracDomainWall4DPC() [1/2]
quda::DiracDomainWall4DPC::DiracDomainWall4DPC (const DiracParam & param)
Definition at line 8 of file dirac_domain_wall_4d.cpp.
DiracDomainWall4DPC() [2/2]
quda::DiracDomainWall4DPC::DiracDomainWall4DPC (const DiracDomainWall4DPC & dirac)
Definition at line 11 of file dirac_domain_wall_4d.cpp.
~DiracDomainWall4DPC()
quda::DiracDomainWall4DPC::~DiracDomainWall4DPC () virtual
Definition at line 14 of file dirac_domain_wall_4d.cpp.
Member Function Documentation
Dslash4()
void quda::DiracDomainWall4DPC::Dslash4 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 26 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::Dirac::mass, out, parity, and quda::Dirac::profile.
Referenced by dslashCUDA(), and M().
Dslash4Xpay()
void quda::DiracDomainWall4DPC::Dslash4Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 76 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::Dirac::mass, out, parity, quda::Dirac::profile, and x.
Referenced by M(), prepare(), and reconstruct().
Dslash5()
void quda::DiracDomainWall4DPC::Dslash5 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 40 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::DiracDomainWall::Ls, quda::Dirac::mass, out, parity, and quda::Dirac::profile.
Referenced by dslashCUDA().
Dslash5inv()
void quda::DiracDomainWall4DPC::Dslash5inv (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const double & kappa5) const
Definition at line 58 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::DiracDomainWall::Ls, quda::Dirac::mass, out, parity, and quda::Dirac::profile.
Referenced by dslashCUDA(), M(), prepare(), and reconstruct().
Dslash5invXpay()
void quda::DiracDomainWall4DPC::Dslash5invXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const double & kappa5, const ColorSpinorField & x, const double & k) const
Definition at line 112 of file dirac_domain_wall_4d.cpp.
References a, b, quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::DiracDomainWall::Ls, quda::Dirac::mass, out, parity, quda::Dirac::profile, and x.
Referenced by M().
Dslash5Xpay()
void quda::DiracDomainWall4DPC::Dslash5Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 93 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::domainWallDslashCuda(), errorQuda, quda::Dirac::flops, quda::Dirac::gauge, in, quda::DiracDomainWall::Ls, quda::Dirac::mass, out, parity, quda::Dirac::profile, and x.
Referenced by M().
M()
void quda::DiracDomainWall4DPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWallPC.
Definition at line 131 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::dagger, quda::Dirac::deleteTmp(), Dslash4(), Dslash4Xpay(), Dslash5inv(), Dslash5invXpay(), Dslash5Xpay(), errorQuda, in, quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::Dirac::newTmp(), out, parity, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, and quda::Dirac::tmp1.
Referenced by dslashCUDA(), and MdagM().
MdagM()
void quda::DiracDomainWall4DPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWallPC.
Definition at line 165 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::deleteTmp(), in, M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), out, and quda::Dirac::tmp2.
Referenced by dslashCUDA().
operator=()
DiracDomainWall4DPC & quda::DiracDomainWall4DPC::operator= (const DiracDomainWall4DPC & dirac)
Definition at line 16 of file dirac_domain_wall_4d.cpp.
References dirac, and quda::DiracDomainWallPC::operator=().
prepare()
void quda::DiracDomainWall4DPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWallPC.
Definition at line 173 of file dirac_domain_wall_4d.cpp.
References b, quda::Dirac::deleteTmp(), Dslash4Xpay(), Dslash5inv(), errorQuda, quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, src, quda::Dirac::tmp1, and x.
reconstruct()
void quda::DiracDomainWall4DPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWallPC.
Definition at line 220 of file dirac_domain_wall_4d.cpp.
References b, quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), Dslash4Xpay(), Dslash5inv(), errorQuda, quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, quda::Dirac::tmp1, and x.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_domain_wall_4d.cpp