QUDA: quda::QudaMatvec< Float > Class Template Reference
quda::QudaMatvec< Float > Class Template Reference
Public Member Functions
QudaMatvec (DiracMatrix &matEigen, QudaPrecision prec, ColorSpinorField &meta)
virtual ~QudaMatvec ()
void operator() (std::complex< Float > *out, std::complex< Float > *in)
Protected Attributes
DiracMatrix & matEigen
QudaPrecision matPrecision
ColorSpinorField * cuda_in
ColorSpinorField * cuda_out
Detailed Description
template<typename Float>
class quda::QudaMatvec< Float >
Definition at line 103 of file quda_arpack_interface.cpp.
Constructor & Destructor Documentation
QudaMatvec()
template<typename Float> quda::QudaMatvec< Float >::QudaMatvec (DiracMatrix & matEigen, QudaPrecision prec, ColorSpinorField & meta) inline
Definition at line 117 of file quda_arpack_interface.cpp.
References csParam, quda::QudaMatvec< Float >::cuda_in, quda::QudaMatvec< Float >::cuda_out, quda::QudaMatvec< Float >::matPrecision, quda::ColorSpinorField::Nspin(), QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT4_FIELD_ORDER, QUDA_UKQCD_GAMMA_BASIS, and QUDA_ZERO_FIELD_CREATE.
~QudaMatvec()
template<typename Float> virtual quda::QudaMatvec< Float >::~QudaMatvec () inline virtual
Definition at line 130 of file quda_arpack_interface.cpp.
References quda::QudaMatvec< Float >::cuda_in, and quda::QudaMatvec< Float >::cuda_out.
Member Function Documentation
operator()()
template<typename Float > void quda::QudaMatvec< Float >::operator() (std::complex< Float > * out, std::complex< Float > * in)
Definition at line 139 of file quda_arpack_interface.cpp.
References quda::ColorSpinorParam::create, quda::ColorSpinorField::Create(), csParam, quda::ColorSpinorParam::fieldOrder, in, quda::ColorSpinorParam::location, out, QUDA_CPU_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_REFERENCE_FIELD_CREATE, QUDA_SINGLE_PRECISION, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, quda::ColorSpinorParam::setPrecision(), and quda::ColorSpinorParam::v.
Member Data Documentation
cuda_in
template<typename Float> ColorSpinorField* quda::QudaMatvec< Float >::cuda_in protected
Definition at line 112 of file quda_arpack_interface.cpp.
Referenced by quda::QudaMatvec< Float >::QudaMatvec(), and quda::QudaMatvec< Float >::~QudaMatvec().
cuda_out
template<typename Float> ColorSpinorField* quda::QudaMatvec< Float >::cuda_out protected
Definition at line 113 of file quda_arpack_interface.cpp.
Referenced by quda::QudaMatvec< Float >::QudaMatvec(), and quda::QudaMatvec< Float >::~QudaMatvec().
matEigen
template<typename Float> DiracMatrix& quda::QudaMatvec< Float >::matEigen protected
Problem matrix
Definition at line 108 of file quda_arpack_interface.cpp.
matPrecision
template<typename Float> QudaPrecision quda::QudaMatvec< Float >::matPrecision protected
Matrix vector precision (may not coincide with arpack IRA routines precision)
Definition at line 110 of file quda_arpack_interface.cpp.
Referenced by quda::QudaMatvec< Float >::QudaMatvec().
The documentation for this class was generated from the following file:
lib/quda_arpack_interface.cpp