QUDA: quda::CGNR Class Reference
quda::CGNR Class Reference
#include <invert_quda.h>
Public Member Functions
CGNR (DiracMatrix &mat, DiracMatrix &matSloppy, SolverParam &param, TimeProfile &profile)
virtual ~CGNR ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::CG
CG (DiracMatrix &mat, DiracMatrix &matSloppy, SolverParam &param, TimeProfile &profile)
virtual ~CG ()
void solve (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
bool convergence (const double &r2, const double &hq2, const double &r2_tol, const double &hq_tol)
bool convergenceHQ (const double &r2, const double &hq2, const double &r2_tol, const double &hq_tol)
bool convergenceL2 (const double &r2, const double &hq2, const double &r2_tol, const double &hq_tol)
void PrintStats (const char *, int k, const double &r2, const double &b2, const double &hq2)
void PrintSummary (const char *name, int k, const double &r2, const double &b2)
virtual double flops () const
Private Attributes
DiracMdagM mdagm
DiracMdagM mdagmSloppy
ColorSpinorField * bp
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (const double &tol, const double &b2, QudaResidualType residual_type)
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
Detailed Description
Definition at line 435 of file invert_quda.h.
Constructor & Destructor Documentation
CGNR()
quda::CGNR::CGNR (DiracMatrix & mat, DiracMatrix & matSloppy, SolverParam & param, TimeProfile & profile)
Definition at line 67 of file inv_cg_quda.cpp.
~CGNR()
quda::CGNR::~CGNR () virtual
Definition at line 71 of file inv_cg_quda.cpp.
References bp, and init.
Member Function Documentation
operator()()
void quda::CGNR::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Reimplemented from quda::CG.
Definition at line 79 of file inv_cg_quda.cpp.
References b, bp, quda::SolverParam::compute_true_res, quda::ColorSpinorField::Create(), csParam, quda::DiracMatrix::Expose(), quda::blas::HeavyQuarkResidualNorm(), init, quda::SolverParam::iter, quda::Dirac::M(), quda::Dirac::Mdag(), mdagm, quda::blas::norm2(), quda::CG::operator()(), quda::Solver::param, quda::Solver::PrintSummary(), QUDA_ZERO_FIELD_CREATE, quda::sqrt(), quda::SolverParam::true_res, quda::SolverParam::true_res_hq, x, quda::blas::xmyNorm(), and z.
Member Data Documentation
bp
ColorSpinorField* quda::CGNR::bp private
Definition at line 440 of file invert_quda.h.
Referenced by operator()(), and ~CGNR().
init
bool quda::CGNR::init private
Definition at line 441 of file invert_quda.h.
Referenced by operator()(), and ~CGNR().
mdagm
DiracMdagM quda::CGNR::mdagm private
Definition at line 438 of file invert_quda.h.
Referenced by operator()().
mdagmSloppy
DiracMdagM quda::CGNR::mdagmSloppy private
Definition at line 439 of file invert_quda.h.
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_cg_quda.cpp