QUDA: quda::CalculateYhat< Float, n, Arg > Class Template Reference
quda::CalculateYhat< Float, n, Arg > Class Template Reference
Public Member Functions
CalculateYhat (Arg &arg, const LatticeField &meta)
virtual ~CalculateYhat ()
void apply (const cudaStream_t &stream)
bool advanceTuneParam (TuneParam &param) const
TuneKey tuneKey () const
Public Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z)
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y)
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
Protected Member Functions
long long flops () const
long long bytes () const
unsigned int minThreads () const
bool tuneGridDim () const
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize () const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const LatticeField & meta
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename Float, int n, typename Arg>
class quda::CalculateYhat< Float, n, Arg >
Definition at line 1417 of file coarse_op.cuh.
Constructor & Destructor Documentation
CalculateYhat()
template<typename Float, int n, typename Arg> quda::CalculateYhat< Float, n, Arg >::CalculateYhat (Arg & arg, const LatticeField & meta) inline
Definition at line 1431 of file coarse_op.cuh.
References quda::Tunable::aux, comm_dim_partitioned_string(), and strcpy().
~CalculateYhat()
template<typename Float, int n, typename Arg> virtual quda::CalculateYhat< Float, n, Arg >::~CalculateYhat () inline virtual
Definition at line 1435 of file coarse_op.cuh.
Member Function Documentation
advanceTuneParam()
template<typename Float, int n, typename Arg> bool quda::CalculateYhat< Float, n, Arg >::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 1446 of file coarse_op.cuh.
References quda::Tunable::advanceTuneParam(), quda::LatticeField::Location(), quda::CalculateYhat< Float, n, Arg >::meta, param, and QUDA_CUDA_FIELD_LOCATION.
apply()
template<typename Float, int n, typename Arg> void quda::CalculateYhat< Float, n, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 1437 of file coarse_op.cuh.
References quda::CalculateYhat< Float, n, Arg >::arg, quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::LatticeField::Location(), quda::CalculateYhat< Float, n, Arg >::meta, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::calculateY().
bytes()
template<typename Float, int n, typename Arg> long long quda::CalculateYhat< Float, n, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 1424 of file coarse_op.cuh.
References quda::CalculateYhat< Float, n, Arg >::arg.
flops()
template<typename Float, int n, typename Arg> long long quda::CalculateYhat< Float, n, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 1423 of file coarse_op.cuh.
References quda::CalculateYhat< Float, n, Arg >::arg, and n.
minThreads()
template<typename Float, int n, typename Arg> unsigned int quda::CalculateYhat< Float, n, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 1426 of file coarse_op.cuh.
References quda::CalculateYhat< Float, n, Arg >::arg.
tuneGridDim()
template<typename Float, int n, typename Arg> bool quda::CalculateYhat< Float, n, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 1428 of file coarse_op.cuh.
tuneKey()
template<typename Float, int n, typename Arg> TuneKey quda::CalculateYhat< Float, n, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 1451 of file coarse_op.cuh.
References quda::Tunable::aux, quda::TuneKey::aux_n, quda::LatticeField::Location(), quda::CalculateYhat< Float, n, Arg >::meta, QUDA_CUDA_FIELD_LOCATION, strcat(), strcpy(), and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int n, typename Arg> Arg& quda::CalculateYhat< Float, n, Arg >::arg protected
Definition at line 1420 of file coarse_op.cuh.
Referenced by quda::CalculateYhat< Float, n, Arg >::apply(), quda::CalculateYhat< Float, n, Arg >::bytes(), quda::CalculateYhat< Float, n, Arg >::flops(), and quda::CalculateYhat< Float, n, Arg >::minThreads().
meta
template<typename Float, int n, typename Arg> const LatticeField& quda::CalculateYhat< Float, n, Arg >::meta protected
Definition at line 1421 of file coarse_op.cuh.
Referenced by quda::CalculateYhat< Float, n, Arg >::advanceTuneParam(), quda::CalculateYhat< Float, n, Arg >::apply(), and quda::CalculateYhat< Float, n, Arg >::tuneKey().
The documentation for this class was generated from the following file:
lib/coarse_op.cuh