QUDA: quda::ExtractGhost< Float, length, nDim, Order > Class Template Reference
quda::ExtractGhost< Float, length, nDim, Order > Class Template Reference
Public Member Functions
ExtractGhost (ExtractGhostArg< Order, nDim > &arg, const GaugeField &meta, QudaFieldLocation location, bool extract)
virtual ~ExtractGhost ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize () const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int blockStep () const
virtual int blockMin () const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 9.0 (Technical Specifications per Compute Capability)
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
ExtractGhostArg< Order, nDim > arg
int size
const GaugeField & meta
QudaFieldLocation location
bool extract
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
Detailed Description
template<typename Float, int length, int nDim, typename Order>
class quda::ExtractGhost< Float, length, nDim, Order >
Definition at line 165 of file extract_gauge_ghost_helper.cuh.
Constructor & Destructor Documentation
ExtractGhost()
template<typename Float, int length, int nDim, typename Order> quda::ExtractGhost< Float, length, nDim, Order >::ExtractGhost (ExtractGhostArg< Order, nDim > & arg, const GaugeField & meta, QudaFieldLocation location, bool extract) inline
Definition at line 180 of file extract_gauge_ghost_helper.cuh.
References quda::ExtractGhost< Float, length, nDim, Order >::arg, d, quda::ExtractGhost< Float, length, nDim, Order >::size, and quda::Tunable::writeAuxString().
~ExtractGhost()
template<typename Float, int length, int nDim, typename Order> virtual quda::ExtractGhost< Float, length, nDim, Order >::~ExtractGhost () inline virtual
Definition at line 195 of file extract_gauge_ghost_helper.cuh.
Member Function Documentation
apply()
template<typename Float, int length, int nDim, typename Order> void quda::ExtractGhost< Float, length, nDim, Order >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 197 of file extract_gauge_ghost_helper.cuh.
References quda::ExtractGhost< Float, length, nDim, Order >::arg, quda::TuneParam::block, quda::ExtractGhost< Float, length, nDim, Order >::extract, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::ExtractGhost< Float, length, nDim, Order >::location, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, quda::stream, and quda::tuneLaunch().
bytes()
template<typename Float, int length, int nDim, typename Order> long long quda::ExtractGhost< Float, length, nDim, Order >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 216 of file extract_gauge_ghost_helper.cuh.
References quda::ExtractGhost< Float, length, nDim, Order >::arg, and d.
flops()
template<typename Float, int length, int nDim, typename Order> long long quda::ExtractGhost< Float, length, nDim, Order >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 215 of file extract_gauge_ghost_helper.cuh.
minThreads()
template<typename Float, int length, int nDim, typename Order> unsigned int quda::ExtractGhost< Float, length, nDim, Order >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 177 of file extract_gauge_ghost_helper.cuh.
References quda::ExtractGhost< Float, length, nDim, Order >::size.
sharedBytesPerBlock()
template<typename Float, int length, int nDim, typename Order> unsigned int quda::ExtractGhost< Float, length, nDim, Order >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 174 of file extract_gauge_ghost_helper.cuh.
sharedBytesPerThread()
template<typename Float, int length, int nDim, typename Order> unsigned int quda::ExtractGhost< Float, length, nDim, Order >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 173 of file extract_gauge_ghost_helper.cuh.
tuneGridDim()
template<typename Float, int length, int nDim, typename Order> bool quda::ExtractGhost< Float, length, nDim, Order >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 176 of file extract_gauge_ghost_helper.cuh.
tuneKey()
template<typename Float, int length, int nDim, typename Order> TuneKey quda::ExtractGhost< Float, length, nDim, Order >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 213 of file extract_gauge_ghost_helper.cuh.
References quda::Tunable::aux, quda::ExtractGhost< Float, length, nDim, Order >::meta, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int length, int nDim, typename Order> ExtractGhostArg<Order,nDim> quda::ExtractGhost< Float, length, nDim, Order >::arg private
Definition at line 166 of file extract_gauge_ghost_helper.cuh.
Referenced by quda::ExtractGhost< Float, length, nDim, Order >::apply(), quda::ExtractGhost< Float, length, nDim, Order >::bytes(), and quda::ExtractGhost< Float, length, nDim, Order >::ExtractGhost().
extract
template<typename Float, int length, int nDim, typename Order> bool quda::ExtractGhost< Float, length, nDim, Order >::extract private
Definition at line 170 of file extract_gauge_ghost_helper.cuh.
Referenced by quda::ExtractGhost< Float, length, nDim, Order >::apply().
location
template<typename Float, int length, int nDim, typename Order> QudaFieldLocation quda::ExtractGhost< Float, length, nDim, Order >::location private
Definition at line 169 of file extract_gauge_ghost_helper.cuh.
Referenced by quda::ExtractGhost< Float, length, nDim, Order >::apply().
meta
template<typename Float, int length, int nDim, typename Order> const GaugeField& quda::ExtractGhost< Float, length, nDim, Order >::meta private
Definition at line 168 of file extract_gauge_ghost_helper.cuh.
Referenced by quda::ExtractGhost< Float, length, nDim, Order >::tuneKey().
size
template<typename Float, int length, int nDim, typename Order> int quda::ExtractGhost< Float, length, nDim, Order >::size private
Definition at line 167 of file extract_gauge_ghost_helper.cuh.
Referenced by quda::ExtractGhost< Float, length, nDim, Order >::ExtractGhost(), and quda::ExtractGhost< Float, length, nDim, Order >::minThreads().
The documentation for this class was generated from the following file:
lib/extract_gauge_ghost_helper.cuh