QUDA: lib/comm_common.cpp File Reference
comm_common.cpp File Reference
#include <unistd.h>
#include <assert.h>
#include <quda_internal.h>
#include <comm_quda.h>
Classes
struct Topology_s
Functions
static int index (int ndim, const int *dims, const int *x)
static bool advance_coords (int ndim, const int *dims, int *x)
char * comm_hostname (void)
double comm_drand (void)
Topology * comm_create_topology (int ndim, const int *dims, QudaCommsMap rank_from_coords, void *map_data)
void comm_destroy_topology (Topology *topo)
void comm_peer2peer_init (const char *hostname_recv_buf)
bool comm_peer2peer_enabled (int dir, int dim)
int comm_peer2peer_enabled_global ()
void comm_enable_peer2peer (bool enable)
Enable / disable peer-to-peer communication: used for dslash policies that do not presently support peer-to-peer communication.
bool comm_intranode_enabled (int dir, int dim)
void comm_enable_intranode (bool enable)
Enable / disable intra-node (non-peer-to-peer) communication.
int comm_ndim (const Topology *topo)
const int * comm_dims (const Topology *topo)
const int * comm_coords (const Topology *topo)
const int * comm_coords_from_rank (const Topology *topo, int rank)
int comm_rank_from_coords (const Topology *topo, const int *coords)
static int mod (int a, int b)
int comm_rank_displaced (const Topology *topo, const int displacement[])
void comm_set_default_topology (Topology *topo)
Topology * comm_default_topology (void)
void comm_set_neighbor_ranks (Topology *topo)
int comm_neighbor_rank (int dir, int dim)
int comm_dim (int dim)
int comm_coord (int dim)
MsgHandle * comm_declare_send_relative_ (const char *func, const char *file, int line, void *buffer, int dim, int dir, size_t nbytes)
MsgHandle * comm_declare_receive_relative_ (const char *func, const char *file, int line, void *buffer, int dim, int dir, size_t nbytes)
MsgHandle * comm_declare_strided_send_relative_ (const char *func, const char *file, int line, void *buffer, int dim, int dir, size_t blksize, int nblocks, size_t stride)
MsgHandle * comm_declare_strided_receive_relative_ (const char *func, const char *file, int line, void *buffer, int dim, int dir, size_t blksize, int nblocks, size_t stride)
void comm_finalize (void)
void comm_dim_partitioned_set (int dim)
void comm_dim_partitioned_reset ()
int comm_dim_partitioned (int dim)
int comm_partitioned ()
Loop over comm_dim_partitioned(dim) for all comms dimensions.
bool comm_gdr_enabled ()
Query if GPU Direct RDMA communication is enabled (global setting)
bool comm_gdr_blacklist ()
Query if GPU Direct RDMA communication is blacklisted for this GPU.
void reduceMaxDouble (double &max)
void reduceDouble (double &sum)
void reduceDoubleArray (double *sum, const int len)
int commDim (int dir)
int commCoords (int dir)
int commDimPartitioned (int dir)
void commDimPartitionedSet (int dir)
void commDimPartitionedReset ()
Reset the comm dim partioned array to zero,.
bool commGlobalReduction ()
void commGlobalReductionSet (bool global_reduction)
bool commAsyncReduction ()
void commAsyncReductionSet (bool async_reduction)
Variables
static unsigned long int rand_seed = 137
static bool peer2peer_enabled [2][4]
static bool peer2peer_init = false
static bool intranode_enabled [2][4]
static int enable_peer_to_peer = 3
static bool enable_p2p = true
static bool enable_intranode = true
Topology * default_topo = NULL
static int neighbor_rank [2][4]
static bool neighbors_cached = false
static int manual_set_partition [QUDA_MAX_DIM] = {0}
static bool globalReduce = true
static bool asyncReduce = false
Function Documentation
advance_coords()
static bool advance_coords (int ndim, const int * dims, int * x) inline static
Definition at line 42 of file comm_common.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, ndim, and x.
Referenced by comm_create_topology().
comm_coord()
int comm_coord (int dim)
Return the coording of this process in the dimension dim
Parameters
dim Dimension which we are querying
Returns
Coordinate of this process
Definition at line 411 of file comm_common.cpp.
References comm_coords(), comm_default_topology(), and dim.
Referenced by commCoords(), DslashCuda::DslashCuda(), quda::launch_kernel_random(), and site_link_sanity_check_internal_12().
comm_coords()
const int* comm_coords (const Topology * topo)
Definition at line 314 of file comm_common.cpp.
References Topology_s::my_coords.
Referenced by comm_coord(), and comm_rank_displaced().
comm_coords_from_rank()
const int* comm_coords_from_rank (const Topology * topo, int rank)
Definition at line 320 of file comm_common.cpp.
References Topology_s::coords, and rank.
comm_create_topology()
Topology* comm_create_topology (int ndim, const int * dims, QudaCommsMap rank_from_coords, void * map_data)
Definition at line 94 of file comm_common.cpp.
References advance_coords(), comm_rank(), Topology_s::coords, Topology_s::dims, errorQuda, fused_exterior_ndeg_tm_dslash_cuda_gen::i, index(), int, Topology_s::my_coords, Topology_s::my_rank, Topology_s::ndim, ndim, nodes, QUDA_MAX_DIM, rand_seed, rank, Topology_s::ranks, safe_malloc, and x.
Referenced by comm_init().
comm_declare_receive_relative_()
MsgHandle* comm_declare_receive_relative_ (const char * func, const char * file, int line, void * buffer, int dim, int dir, size_t nbytes)
Receive from the "dir" direction in the "dim" dimension
Definition at line 460 of file comm_common.cpp.
References attributes, checkCudaError, comm_declare_receive_displaced(), dim, e, err, errorQuda, func, printfQuda, and QUDA_MAX_DIM.
comm_declare_send_relative_()
MsgHandle* comm_declare_send_relative_ (const char * func, const char * file, int line, void * buffer, int dim, int dir, size_t nbytes)
Send to the "dir" direction in the "dim" dimension
Definition at line 421 of file comm_common.cpp.
References attributes, checkCudaError, comm_declare_send_displaced(), quda::blas::copy(), device_free, device_malloc, dim, e, err, errorQuda, func, host_free, printfQuda, QUDA_MAX_DIM, safe_malloc, and tmp.
comm_declare_strided_receive_relative_()
MsgHandle* comm_declare_strided_receive_relative_ (const char * func, const char * file, int line, void * buffer, int dim, int dir, size_t blksize, int nblocks, size_t stride)
Strided receive from the "dir" direction in the "dim" dimension
Definition at line 538 of file comm_common.cpp.
References attributes, checkCudaError, comm_declare_strided_receive_displaced(), dim, e, err, errorQuda, func, fused_exterior_ndeg_tm_dslash_cuda_gen::i, printfQuda, and QUDA_MAX_DIM.
comm_declare_strided_send_relative_()
MsgHandle* comm_declare_strided_send_relative_ (const char * func, const char * file, int line, void * buffer, int dim, int dir, size_t blksize, int nblocks, size_t stride)
Strided send to the "dir" direction in the "dim" dimension
Definition at line 495 of file comm_common.cpp.
References attributes, checkCudaError, comm_declare_strided_send_displaced(), quda::blas::copy(), device_free, device_malloc, dim, e, err, errorQuda, func, host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, printfQuda, QUDA_MAX_DIM, safe_malloc, and tmp.
comm_default_topology()
Topology* comm_default_topology (void)
Definition at line 361 of file comm_common.cpp.
References default_topo, and errorQuda.
Referenced by comm_coord(), comm_declare_receive_displaced(), comm_declare_send_displaced(), comm_declare_strided_receive_displaced(), comm_declare_strided_send_displaced(), comm_dim(), and comm_finalize().
comm_destroy_topology()
void comm_destroy_topology (Topology * topo)
Definition at line 137 of file comm_common.cpp.
References Topology_s::coords, host_free, and Topology_s::ranks.
Referenced by comm_finalize().
comm_dim()
int comm_dim (int dim)
Return the number of processes in the dimension dim
Parameters
dim Dimension which we are querying
Returns
Length of process dimensions
Definition at line 404 of file comm_common.cpp.
References comm_default_topology(), comm_dims(), and dim.
Referenced by quda::calculateY(), comm_dim_partitioned(), comm_init(), comm_peer2peer_init(), commDim(), quda::LatticeField::createIPCComms(), quda::LatticeField::destroyIPCComms(), DslashCuda::DslashCuda(), quda::launch_kernel_random(), set_layout(), and site_link_sanity_check_internal_12().
comm_dim_partitioned()
int comm_dim_partitioned (int dim)
Definition at line 597 of file comm_common.cpp.
References comm_dim(), dim, and manual_set_partition.
Referenced by quda::GenericPackGhostLauncher< Float, Ns, Ms, Nc, Mc, Arg >::bytes(), quda::calculateY(), quda::CalculateYArg< Float, coarseGauge, fineGauge, fineSpinor, fineSpinorTmp, fineClover >::CalculateYArg(), GaugeAlgTest::checkDimsPartitioned(), comm_init(), comm_partitioned(), commDimPartitioned(), quda::cudaGaugeField::commsComplete(), computeHISQForceQuda(), quda::GaugeField::createGhostZone(), quda::ColorSpinorField::createGhostZone(), DslashCuda::DslashCuda(), quda::GaugeField::exchange(), quda::ColorSpinorField::exchange(), quda::cudaGaugeField::exchangeExtendedGhost(), quda::cpuGaugeField::exchangeExtendedGhost(), quda::cudaGaugeField::exchangeGhost(), quda::cudaColorSpinorField::exchangeGhost(), quda::ExtractGhostArg< Order, nDim >::ExtractGhostArg(), quda::gaugefixingFFT(), gaugeLink_mgpu(), quda::GenericPackGhostLauncher< Float, Ns, Ms, Nc, Mc, Arg >::GenericPackGhostLauncher(), hisq_force_init(), hisq_force_test(), quda::cudaGaugeField::injectGhost(), main(), neighborIndex_mg(), quda::PackGhostArg< Field >::PackGhostArg(), quda::PGaugeExchange(), quda::cudaGaugeField::recvStart(), quda::cudaGaugeField::sendStart(), GaugeAlgTest::SetUp(), and quda::XSD::XSD().
comm_dim_partitioned_reset()
void comm_dim_partitioned_reset ()
Definition at line 590 of file comm_common.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, manual_set_partition, and QUDA_MAX_DIM.
Referenced by commDimPartitionedReset().
comm_dim_partitioned_set()
void comm_dim_partitioned_set (int dim)
Definition at line 583 of file comm_common.cpp.
References dim, and manual_set_partition.
Referenced by commDimPartitionedSet().
comm_dims()
const int* comm_dims (const Topology * topo)
Definition at line 308 of file comm_common.cpp.
References Topology_s::dims.
Referenced by comm_dim(), and comm_rank_displaced().
comm_drand()
double comm_drand (void)
We provide our own random number generator to avoid re-seeding rand(), which might also be used by the calling application. This is a clone of rand48(), provided by stdlib.h on UNIX.
Returns
a random double in the interval [0,1)
Definition at line 82 of file comm_common.cpp.
References a, and rand_seed.
Referenced by insertNoise(), and quda::random().
comm_enable_intranode()
void comm_enable_intranode (bool enable)
Enable / disable intra-node (non-peer-to-peer) communication.
Parameters
[in] enable Boolean flag to enable / disable intra-node (non peer-to-peer) communication
Definition at line 298 of file comm_common.cpp.
References enable_intranode.
comm_enable_peer2peer()
void comm_enable_peer2peer (bool enable)
Enable / disable peer-to-peer communication: used for dslash policies that do not presently support peer-to-peer communication.
Parameters
[in] enable Boolean flag to enable / disable peer-to-peer communication
Definition at line 288 of file comm_common.cpp.
References enable_p2p.
Referenced by anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::apply(), and anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::DslashPolicyTune().
comm_finalize()
void comm_finalize (void)
Definition at line 573 of file comm_common.cpp.
References comm_default_topology(), comm_destroy_topology(), and comm_set_default_topology().
Referenced by endQuda().
comm_gdr_blacklist()
bool comm_gdr_blacklist ()
Query if GPU Direct RDMA communication is blacklisted for this GPU.
Definition at line 627 of file comm_common.cpp.
References comm_barrier(), comm_gpuid(), comm_rank(), errorQuda, getenv(), getVerbosity(), printf(), and QUDA_SILENT.
Referenced by comm_peer2peer_init(), and anonymous_namespace{dslash_policy.cuh}::DslashFactory::create().
comm_gdr_enabled()
bool comm_gdr_enabled ()
Query if GPU Direct RDMA communication is enabled (global setting)
Definition at line 611 of file comm_common.cpp.
References getenv(), and strcmp().
Referenced by comm_peer2peer_init(), quda::cudaGaugeField::commsComplete(), quda::cudaColorSpinorField::commsQuery(), quda::cudaColorSpinorField::commsWait(), quda::LatticeField::createComms(), quda::DslashCoarsePolicyTune::DslashCoarsePolicyTune(), anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::DslashPolicyTune(), quda::cudaGaugeField::exchangeExtendedGhost(), quda::cudaGaugeField::exchangeGhost(), quda::cudaColorSpinorField::exchangeGhost(), quda::cudaGaugeField::injectGhost(), quda::cudaGaugeField::recvStart(), quda::cudaColorSpinorField::recvStart(), quda::cudaGaugeField::sendStart(), and quda::cudaColorSpinorField::sendStart().
comm_hostname()
char* comm_hostname (void)
Definition at line 58 of file comm_common.cpp.
Referenced by comm_gather_hostname(), comm_init(), and comm_peer2peer_init().
comm_intranode_enabled()
bool comm_intranode_enabled (int dir, int dim)
Query if intra-node (non-peer-to-peer) communication is enabled in a given dimension and direction
Parameters
dir Direction (0 - backwards, 1 forwards)
dim Dimension (0-3)
Returns
Whether intra-node communication is enabled
Definition at line 294 of file comm_common.cpp.
References dim, enable_intranode, and intranode_enabled.
comm_ndim()
int comm_ndim (const Topology * topo)
Definition at line 302 of file comm_common.cpp.
References Topology_s::ndim.
Referenced by comm_declare_receive_displaced(), comm_declare_send_displaced(), comm_declare_strided_receive_displaced(), and comm_declare_strided_send_displaced().
comm_neighbor_rank()
int comm_neighbor_rank (int dir, int dim)
Definition at line 396 of file comm_common.cpp.
References comm_set_neighbor_ranks(), dim, neighbor_rank, and neighbors_cached.
Referenced by comm_peer2peer_init().
comm_partitioned()
int comm_partitioned ()
Loop over comm_dim_partitioned(dim) for all comms dimensions.
Returns
Whether any communications dimensions are partitioned
Definition at line 602 of file comm_common.cpp.
References comm_dim_partitioned(), and fused_exterior_ndeg_tm_dslash_cuda_gen::i.
Referenced by quda::DslashCoarseLaunch::operator()().
comm_peer2peer_enabled()
bool comm_peer2peer_enabled (int dir, int dim)
Query if peer-to-peer communication is enabled
Parameters
dir Direction (0 - backwards, 1 forwards)
dim Dimension (0-3)
Returns
Whether peer-to-peer is enabled
Definition at line 265 of file comm_common.cpp.
References dim, enable_p2p, and peer2peer_enabled.
Referenced by comm_peer2peer_enabled_global(), anonymous_namespace{dslash_policy.cuh}::commsComplete(), quda::cudaGaugeField::commsComplete(), quda::cudaColorSpinorField::commsQuery(), quda::cudaColorSpinorField::commsWait(), anonymous_namespace{dslash_policy.cuh}::completeDslash(), quda::LatticeField::createIPCComms(), quda::LatticeField::destroyIPCComms(), quda::cudaGaugeField::exchangeExtendedGhost(), quda::cudaGaugeField::exchangeGhost(), quda::cudaColorSpinorField::exchangeGhost(), quda::cudaColorSpinorField::gather(), anonymous_namespace{dslash_policy.cuh}::getStreamIndex(), quda::cudaGaugeField::injectGhost(), anonymous_namespace{dslash_policy.cuh}::issueGather(), anonymous_namespace{dslash_policy.cuh}::issuePack(), anonymous_namespace{dslash_policy.cuh}::DslashBasic::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashPthreads::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedExterior::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashGDR::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedGDR::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashGDRRecv::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedGDRRecv::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashZeroCopyPack::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedZeroCopyPack::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashZeroCopyPackGDRRecv::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedZeroCopyPackGDRRecv::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashZeroCopy::operator()(), anonymous_namespace{dslash_policy.cuh}::DslashFusedZeroCopy::operator()(), quda::cudaGaugeField::recvStart(), quda::cudaColorSpinorField::recvStart(), quda::cudaColorSpinorField::scatter(), quda::cudaGaugeField::sendStart(), quda::cudaColorSpinorField::sendStart(), and DslashCuda::setParam().
comm_peer2peer_enabled_global()
int comm_peer2peer_enabled_global ()
Query what peer-to-peer communication is enabled globally
Returns
2-bit number reporting 1 for copy engine, 2 for remote writes
Definition at line 269 of file comm_common.cpp.
References comm_allreduce_int(), comm_peer2peer_enabled(), dim, enable_p2p, enable_peer_to_peer, and quda::blas::init().
Referenced by anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::apply(), quda::DslashCoarsePolicyTune::DslashCoarsePolicyTune(), anonymous_namespace{dslash_policy.cuh}::DslashPolicyTune::DslashPolicyTune(), and quda::cudaColorSpinorField::exchangeGhost().
comm_peer2peer_init()
void comm_peer2peer_init (const char * hostname_recv_buf)
Enabled peer-to-peer communication.
Parameters
hostname_buf Array that holds all process hostnames
Definition at line 154 of file comm_common.cpp.
References abs(), atoi(), checkCudaErrorNoSync, comm_barrier(), comm_dim(), comm_gather_gpuid(), comm_gdr_blacklist(), comm_gdr_enabled(), comm_gpuid(), comm_hostname(), comm_neighbor_rank(), comm_rank(), comm_set_neighbor_ranks(), comm_size(), dim, enable_peer_to_peer, errorQuda, getenv(), getVerbosity(), gpuid, host_free, intranode_enabled, neighbor_rank, peer2peer_enabled, peer2peer_init, printf(), printfQuda, prop, QUDA_SILENT, safe_malloc, and strncmp().
Referenced by comm_init().
comm_rank_displaced()
int comm_rank_displaced (const Topology * topo, const int displacement[])
Definition at line 337 of file comm_common.cpp.
References comm_coords(), comm_dims(), comm_rank_from_coords(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, mod(), Topology_s::ndim, and QUDA_MAX_DIM.
Referenced by comm_declare_receive_displaced(), comm_declare_send_displaced(), comm_declare_strided_receive_displaced(), comm_declare_strided_send_displaced(), and comm_set_neighbor_ranks().
comm_rank_from_coords()
int comm_rank_from_coords (const Topology * topo, const int * coords)
Definition at line 326 of file comm_common.cpp.
References Topology_s::dims, index(), Topology_s::ndim, and Topology_s::ranks.
Referenced by comm_rank_displaced().
comm_set_default_topology()
void comm_set_default_topology (Topology * topo)
Definition at line 355 of file comm_common.cpp.
References default_topo.
Referenced by comm_finalize(), and comm_init().
comm_set_neighbor_ranks()
void comm_set_neighbor_ranks (Topology * topo)
Definition at line 374 of file comm_common.cpp.
References comm_rank_displaced(), d, default_topo, errorQuda, neighbor_rank, and neighbors_cached.
Referenced by comm_neighbor_rank(), and comm_peer2peer_init().
commAsyncReduction()
bool commAsyncReduction ()
Definition at line 684 of file comm_common.cpp.
References asyncReduce.
Referenced by quda::blas::caxpyXmazMR(), quda::ReduceArg< T >::ReduceArg(), and reduceLaunch().
commAsyncReductionSet()
void commAsyncReductionSet (bool async_reduction)
Definition at line 686 of file comm_common.cpp.
References asyncReduce.
Referenced by quda::MR::operator()().
commCoords()
int commCoords (int dir)
Definition at line 672 of file comm_common.cpp.
References comm_coord().
Referenced by applyGaugeFieldScaling(), createSiteLinkCPU(), and quda::GCR::operator()().
commDim()
int commDim (int dir)
Definition at line 670 of file comm_common.cpp.
References comm_dim().
Referenced by applyGaugeFieldScaling(), createSiteLinkCPU(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedCloverPC::DslashXpay(), quda::exchangeExtendedGhost(), quda::extractGhost(), and quda::extractGhostEx().
commDimPartitioned()
int commDimPartitioned (int dir)
Definition at line 674 of file comm_common.cpp.
References comm_dim_partitioned().
Referenced by quda::cudaColorSpinorField::commsQuery(), quda::cudaColorSpinorField::commsWait(), createCloverQuda(), quda::LatticeField::createComms(), quda::cudaColorSpinorField::createComms(), quda::LatticeField::destroyComms(), initQudaMemory(), loadGaugeQuda(), quda::cudaColorSpinorField::recvStart(), quda::cudaColorSpinorField::scatter(), quda::cudaColorSpinorField::scatterExtended(), quda::cudaColorSpinorField::sendStart(), quda::shiftColorSpinorField(), quda::ShiftColorSpinorFieldArg< Output, Input >::ShiftColorSpinorFieldArg(), and updateR().
commDimPartitionedReset()
void commDimPartitionedReset ()
Reset the comm dim partioned array to zero,.
This should only be needed for automated testing when different partitioning is applied within a single run.
Definition at line 678 of file comm_common.cpp.
References comm_dim_partitioned_reset().
Referenced by end().
commDimPartitionedSet()
void commDimPartitionedSet (int dir)
Definition at line 676 of file comm_common.cpp.
References comm_dim_partitioned_set().
Referenced by process_command_line_option(), StaggeredDslashTest::SetUp(), and DslashTest::SetUp().
commGlobalReduction()
bool commGlobalReduction ()
Definition at line 680 of file comm_common.cpp.
References globalReduce.
Referenced by quda::tuneLaunch().
commGlobalReductionSet()
void commGlobalReductionSet (bool global_reduction)
Definition at line 682 of file comm_common.cpp.
References globalReduce.
Referenced by quda::IncEigCG::eigCGsolve(), quda::PreconCG::operator()(), quda::MR::operator()(), and quda::SD::operator()().
index()
static int index (int ndim, const int * dims, const int * x) inline static
Utility function for indexing into Topology::ranks[]
Parameters
ndim Number of grid dimensions in the network topology
dims Array of grid dimensions
x Node coordinates
Returns
Linearized index cooresponding to the node coordinates
Definition at line 32 of file comm_common.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, ndim, and x.
Referenced by comm_create_topology(), and comm_rank_from_coords().
mod()
static int mod (int a, int b) inline static
Definition at line 332 of file comm_common.cpp.
References a, and b.
Referenced by comm_rank_displaced(), and quda::polarSu3().
reduceDouble()
void reduceDouble (double & sum)
Definition at line 665 of file comm_common.cpp.
References comm_allreduce(), globalReduce, and sum().
Referenced by quda::blas::normCpu(), quda::blas::reDotProductCpu(), and quda::SolverParam::updateInvertParam().
reduceDoubleArray()
void reduceDoubleArray (double * sum, const int len)
Definition at line 667 of file comm_common.cpp.
References comm_allreduce_array(), globalReduce, len, and sum().
Referenced by quda::blas::cDotProduct(), quda::blas::cDotProductCopy(), quda::blas::cDotProductCpu(), quda::blas::hDotProduct(), quda::blas::hDotProduct_Anorm(), quda::blas::HeavyQuarkResidualNormCpu(), quda::blas::reDotProduct(), reduceCuda(), and mixed::reduceCuda().
reduceMaxDouble()
void reduceMaxDouble (double & max)
Definition at line 663 of file comm_common.cpp.
References comm_allreduce_max().
Referenced by quda::maxGauge().
Variable Documentation
asyncReduce
bool asyncReduce = false static
Definition at line 661 of file comm_common.cpp.
Referenced by commAsyncReduction(), and commAsyncReductionSet().
default_topo
Topology* default_topo = NULL
Definition at line 353 of file comm_common.cpp.
Referenced by comm_default_topology(), comm_set_default_topology(), and comm_set_neighbor_ranks().
enable_intranode
bool enable_intranode = true static
Definition at line 292 of file comm_common.cpp.
Referenced by comm_enable_intranode(), and comm_intranode_enabled().
enable_p2p
bool enable_p2p = true static
Definition at line 263 of file comm_common.cpp.
Referenced by comm_enable_peer2peer(), comm_peer2peer_enabled(), and comm_peer2peer_enabled_global().
enable_peer_to_peer
int enable_peer_to_peer = 3 static
Definition at line 152 of file comm_common.cpp.
Referenced by comm_peer2peer_enabled_global(), and comm_peer2peer_init().
globalReduce
bool globalReduce = true static
Definition at line 660 of file comm_common.cpp.
Referenced by commGlobalReduction(), commGlobalReductionSet(), reduceDouble(), and reduceDoubleArray().
intranode_enabled
bool intranode_enabled[2][4] static
Initial value:
= { {false,false,false,false},
          {false,false,false,false} }
Definition at line 149 of file comm_common.cpp.
Referenced by comm_intranode_enabled(), and comm_peer2peer_init().
manual_set_partition
int manual_set_partition[QUDA_MAX_DIM] = {0} static
Definition at line 581 of file comm_common.cpp.
Referenced by comm_dim_partitioned(), comm_dim_partitioned_reset(), and comm_dim_partitioned_set().
neighbor_rank
int neighbor_rank[2][4] static
Initial value:
= { {-1,-1,-1,-1},
                                          {-1,-1,-1,-1} }
Definition at line 369 of file comm_common.cpp.
Referenced by comm_neighbor_rank(), comm_peer2peer_init(), and comm_set_neighbor_ranks().
neighbors_cached
bool neighbors_cached = false static
Definition at line 372 of file comm_common.cpp.
Referenced by comm_neighbor_rank(), and comm_set_neighbor_ranks().
peer2peer_enabled
bool peer2peer_enabled[2][4] static
Initial value:
= { {false,false,false,false},
                                        {false,false,false,false} }
Definition at line 145 of file comm_common.cpp.
Referenced by comm_peer2peer_enabled(), and comm_peer2peer_init().
peer2peer_init
bool peer2peer_init = false static
Definition at line 147 of file comm_common.cpp.
Referenced by comm_peer2peer_init().
rand_seed
unsigned long int rand_seed = 137 static
Definition at line 73 of file comm_common.cpp.
Referenced by comm_create_topology(), and comm_drand().