QUDA: include/dbldbl.h File Reference
dbldbl.h File Reference
#include <math.h>
Classes
struct doubledouble
struct doubledouble2
struct doubledouble3
Typedefs
typedef double2 dbldbl
Functions
__device__ __forceinline__ dbldbl make_dbldbl (double head, double tail)
__device__ __forceinline__ double get_dbldbl_head (dbldbl a)
__device__ __forceinline__ double get_dbldbl_tail (dbldbl a)
__device__ __forceinline__ dbldbl add_double_to_dbldbl (double a, double b)
__device__ __forceinline__ dbldbl mul_double_to_dbldbl (double a, double b)
__device__ __forceinline__ dbldbl neg_dbldbl (dbldbl a)
__device__ __forceinline__ dbldbl add_dbldbl (dbldbl a, dbldbl b)
__device__ __forceinline__ dbldbl sub_dbldbl (dbldbl a, dbldbl b)
__device__ __forceinline__ dbldbl mul_dbldbl (dbldbl a, dbldbl b)
__device__ __forceinline__ dbldbl div_dbldbl (dbldbl a, dbldbl b)
__device__ __forceinline__ dbldbl sqrt_dbldbl (dbldbl a)
__device__ __forceinline__ dbldbl rsqrt_dbldbl (dbldbl a)
__device__ bool operator> (const doubledouble &a, const double &b)
__device__ doubledouble operator+ (const doubledouble &a, const doubledouble &b)
__device__ doubledouble operator- (const doubledouble &a, const doubledouble &b)
__device__ doubledouble operator* (const doubledouble &a, const doubledouble &b)
__device__ doubledouble operator/ (const doubledouble &a, const doubledouble &b)
__device__ doubledouble add_double_to_doubledouble (const double &a, const double &b)
__device__ doubledouble mul_double_to_doubledouble (const double &a, const double &b)
__device__ doubledouble2 operator+ (const doubledouble2 &a, const doubledouble2 &b)
__device__ doubledouble3 operator+ (const doubledouble3 &a, const doubledouble3 &b)
Typedef Documentation
dbldbl
typedef double2 dbldbl
Definition at line 61 of file dbldbl.h.
Function Documentation
add_dbldbl()
__device__ __forceinline__ dbldbl add_dbldbl (dbldbl a, dbldbl b)
Definition at line 127 of file dbldbl.h.
References a, b, e, and z.
Referenced by operator+(), and doubledouble::operator+=().
add_double_to_dbldbl()
__device__ __forceinline__ dbldbl add_double_to_dbldbl (double a, double b)
Definition at line 89 of file dbldbl.h.
References a, b, and z.
Referenced by add_double_to_doubledouble().
add_double_to_doubledouble()
__device__ doubledouble add_double_to_doubledouble (const double & a, const double & b) inline
Definition at line 330 of file dbldbl.h.
References a, add_double_to_dbldbl(), and b.
div_dbldbl()
__device__ __forceinline__ dbldbl div_dbldbl (dbldbl a, dbldbl b)
Definition at line 199 of file dbldbl.h.
References a, b, e, t, and z.
Referenced by operator/().
get_dbldbl_head()
__device__ __forceinline__ double get_dbldbl_head (dbldbl a)
Definition at line 77 of file dbldbl.h.
References a.
get_dbldbl_tail()
__device__ __forceinline__ double get_dbldbl_tail (dbldbl a)
Definition at line 83 of file dbldbl.h.
References a.
make_dbldbl()
__device__ __forceinline__ dbldbl make_dbldbl (double head, double tail)
Definition at line 68 of file dbldbl.h.
References z.
mul_dbldbl()
__device__ __forceinline__ dbldbl mul_dbldbl (dbldbl a, dbldbl b)
Definition at line 177 of file dbldbl.h.
References a, b, e, t, and z.
Referenced by operator*().
mul_double_to_dbldbl()
__device__ __forceinline__ dbldbl mul_double_to_dbldbl (double a, double b)
Definition at line 103 of file dbldbl.h.
References a, b, and z.
Referenced by mul_double_to_doubledouble().
mul_double_to_doubledouble()
__device__ doubledouble mul_double_to_doubledouble (const double & a, const double & b) inline
Definition at line 334 of file dbldbl.h.
References a, b, and mul_double_to_dbldbl().
neg_dbldbl()
__device__ __forceinline__ dbldbl neg_dbldbl (dbldbl a)
Definition at line 112 of file dbldbl.h.
References a, and z.
operator*()
__device__ doubledouble operator* (const doubledouble & a, const doubledouble & b) inline
Definition at line 322 of file dbldbl.h.
References a, b, and mul_dbldbl().
operator+() [1/3]
__device__ doubledouble operator+ (const doubledouble & a, const doubledouble & b) inline
Definition at line 314 of file dbldbl.h.
References a, add_dbldbl(), and b.
operator+() [2/3]
__device__ doubledouble2 operator+ (const doubledouble2 & a, const doubledouble2 & b)
Definition at line 376 of file dbldbl.h.
References a, and b.
operator+() [3/3]
__device__ doubledouble3 operator+ (const doubledouble3 & a, const doubledouble3 & b)
Definition at line 379 of file dbldbl.h.
References a, and b.
operator-()
__device__ doubledouble operator- (const doubledouble & a, const doubledouble & b) inline
Definition at line 318 of file dbldbl.h.
References a, b, and sub_dbldbl().
operator/()
__device__ doubledouble operator/ (const doubledouble & a, const doubledouble & b) inline
Definition at line 326 of file dbldbl.h.
References a, b, and div_dbldbl().
operator>()
__device__ bool operator> (const doubledouble & a, const double & b) inline
Definition at line 310 of file dbldbl.h.
References a, and b.
rsqrt_dbldbl()
__device__ __forceinline__ dbldbl rsqrt_dbldbl (dbldbl a)
Definition at line 252 of file dbldbl.h.
References a, e, s, and z.
sqrt_dbldbl()
__device__ __forceinline__ dbldbl sqrt_dbldbl (dbldbl a)
Definition at line 225 of file dbldbl.h.
References a, e, s, t, y, and z.
sub_dbldbl()
__device__ __forceinline__ dbldbl sub_dbldbl (dbldbl a, dbldbl b)
Definition at line 153 of file dbldbl.h.
References a, b, e, and z.
Referenced by operator-().