QUDA: include/double_single.h File Reference
double_single.h File Reference
Classes
struct doublesingle
struct doublesingle2
struct doublesingle3
Functions
__host__ __device__ void dsadd (volatile float2 &c, const volatile float2 &a, const volatile float2 &b)
__host__ __device__ volatile doublesingle operator+= (volatile doublesingle &a, const volatile doublesingle &b)
__host__ __device__ double operator+= (double &a, doublesingle &b)
__host__ __device__ double2 operator+= (double2 &a, doublesingle2 &b)
__host__ __device__ double3 operator+= (double3 &a, doublesingle3 &b)
Function Documentation
dsadd()
__host__ __device__ void dsadd (volatile float2 & c, const volatile float2 & a, const volatile float2 & b) inline
Definition at line 3 of file double_single.h.
References a, b, c, and e.
Referenced by doublesingle::operator+=(), and operator+=().
operator+=() [1/4]
__host__ __device__ volatile doublesingle operator+= (volatile doublesingle & a, const volatile doublesingle & b) inline
Definition at line 31 of file double_single.h.
References a, b, and dsadd().
operator+=() [2/4]
__host__ __device__ double operator+= (double & a, doublesingle & b)
Definition at line 34 of file double_single.h.
References a, and b.
operator+=() [3/4]
__host__ __device__ double2 operator+= (double2 & a, doublesingle2 & b)
Definition at line 45 of file double_single.h.
References a, and b.
operator+=() [4/4]
__host__ __device__ double3 operator+= (double3 & a, doublesingle3 & b)
Definition at line 56 of file double_single.h.
References a, and b.