QUDA: tests/gauge_force_test.cpp File Reference
gauge_force_test.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <quda.h>
#include <test_util.h>
#include <gauge_field.h>
#include "misc.h"
#include "gauge_force_reference.h"
#include "gauge_force_quda.h"
#include <sys/time.h>
#include <dslash_quda.h>
Functions
void usage (char **argv)
static void gauge_force_test (void)
static void display_test_info ()
void usage_extra (char **argv)
int main (int argc, char **argv)
Variables
int device
static QudaGaugeParam qudaGaugeParam
QudaGaugeFieldOrder gauge_order = QUDA_QDP_GAUGE_ORDER
bool verify_results
int tdim
QudaPrecision prec
int xdim
int ydim
int zdim
int niter
QudaReconstructType link_recon
QudaPrecision link_prec = QUDA_SINGLE_PRECISION
int gridsize_from_cmdline []
int length []
float loop_coeff_f []
int path_dir_x [][5]
int path_dir_y [][5]
int path_dir_z [][5]
int path_dir_t [][5]
Function Documentation
display_test_info()
static void display_test_info () static
Definition at line 576 of file gauge_force_test.cpp.
References gauge_order, get_gauge_order_str(), get_prec_str(), get_recon_str(), link_prec, link_recon, niter, printfQuda, return(), tdim, xdim, ydim, and zdim.
Referenced by main().
gauge_force_test()
static void gauge_force_test (void) static
Definition at line 345 of file gauge_force_test.cpp.
References QudaGaugeParam_s::anisotropy, compare_floats(), computeGaugeForceQuda(), QudaGaugeParam_s::cpu_prec, createMomCPU(), createSiteLinkCPU(), QudaGaugeParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, device, e, E1h, E2, E3, endQuda(), errorQuda, exchange_cpu_sitelink_ex(), quda::blas::flops, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, gauge_force_reference(), gauge_order, QudaGaugeParam_s::gauge_order, gaugeSiteSize, getTuning(), gSize, host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, initQuda(), length, link_prec, link_recon, loop_coeff_f, memcpy(), memset(), QudaGaugeParam_s::mom_ga_pad, momSiteSize, newQudaGaugeParam(), niter, path_dir_t, path_dir_x, path_dir_y, path_dir_z, pinned_malloc, printfQuda, QUDA_GAUGE_FIXED_NO, QUDA_MILC_GAUGE_ORDER, QUDA_PERIODIC_T, QUDA_QDP_GAUGE_ORDER, QUDA_SINGLE_PRECISION, QUDA_SU3_LINKS, QUDA_TUNE_YES, QUDA_VERBOSE, qudaGaugeParam, R, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, safe_malloc, setDims(), setVerbosityQuda(), sid, src, strong_check_mom(), QudaGaugeParam_s::t_boundary, tdim, timeval::tv_sec, timeval::tv_usec, QudaGaugeParam_s::type, V, V_ex, verify_results, Vh, Vh_ex, QudaGaugeParam_s::X, xdim, ydim, Z, za, zb, and zdim.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 600 of file gauge_force_test.cpp.
References display_test_info(), exit(), finalizeComms(), fprintf(), gauge_force_test(), gauge_order, gridsize_from_cmdline, fused_exterior_ndeg_tm_dslash_cuda_gen::i, initComms(), link_prec, prec, process_command_line_option(), QUDA_MILC_GAUGE_ORDER, QUDA_QDP_GAUGE_ORDER, strcmp(), usage(), and verify_results.
usage()
void usage (char ** argv)
Definition at line 1693 of file test_util.cpp.
Referenced by main().
usage_extra()
void usage_extra (char ** argv)
Definition at line 592 of file gauge_force_test.cpp.
References printfQuda, and return().
Variable Documentation
device
int device
Definition at line 2238 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by gauge_force_test().
gauge_order
QudaGaugeFieldOrder gauge_order = QUDA_QDP_GAUGE_ORDER
Definition at line 17 of file gauge_force_test.cpp.
Referenced by computeLinkOrderedOuterProduct(), display_test_info(), gauge_force_test(), get_su3_matrix(), main(), and printQudaGaugeParam().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 50 of file test_util.cpp.
Referenced by main().
length
int length[]
Definition at line 34 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
link_prec
QudaPrecision link_prec = QUDA_SINGLE_PRECISION
Definition at line 29 of file gauge_force_test.cpp.
Referenced by display_test_info(), gauge_force_test(), and main().
link_recon
QudaReconstructType link_recon
Definition at line 1612 of file test_util.cpp.
Referenced by display_test_info(), and gauge_force_test().
loop_coeff_f
float loop_coeff_f[]
Definition at line 86 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
niter
int niter
Definition at line 1630 of file test_util.cpp.
Referenced by display_test_info(), and gauge_force_test().
path_dir_t
int path_dir_t[][5]
Definition at line 291 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
path_dir_x
int path_dir_x[][5]
Definition at line 137 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
path_dir_y
int path_dir_y[][5]
Definition at line 189 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
path_dir_z
int path_dir_z[][5]
Definition at line 240 of file gauge_force_test.cpp.
Referenced by gauge_force_test().
prec
QudaPrecision prec
Definition at line 1615 of file test_util.cpp.
Referenced by main().
qudaGaugeParam
QudaGaugeParam qudaGaugeParam static
Definition at line 16 of file gauge_force_test.cpp.
Referenced by computeGaugeForceQuda(), gauge_force_test(), llfat_test(), and unitarize_link_test().
tdim
int tdim
Definition at line 24 of file gauge_force_test.cpp.
Referenced by display_test_info(), and gauge_force_test().
verify_results
bool verify_results
Definition at line 1641 of file test_util.cpp.
Referenced by gauge_force_test(), and main().
xdim
int xdim
Definition at line 1620 of file test_util.cpp.
Referenced by display_test_info(), and gauge_force_test().
ydim
int ydim
Definition at line 1621 of file test_util.cpp.
Referenced by display_test_info(), and gauge_force_test().
zdim
int zdim
Definition at line 1622 of file test_util.cpp.
Referenced by display_test_info(), and gauge_force_test().