QUDA: tests/gauge_alg_test.cpp File Reference
gauge_alg_test.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <quda.h>
#include <quda_internal.h>
#include <gauge_field.h>
#include <comm_quda.h>
#include <test_util.h>
#include <gauge_tools.h>
#include <pgauge_monte.h>
#include <random_quda.h>
#include <unitarization_links.h>
#include <gtest.h>
Classes
class GaugeAlgTest
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
#define DABS(a) ((a)<(0.)?(-(a)):(a))
Functions
TEST_F (GaugeAlgTest, Generation)
TEST_F (GaugeAlgTest, Landau_Overrelaxation)
TEST_F (GaugeAlgTest, Coulomb_Overrelaxation)
TEST_F (GaugeAlgTest, Landau_FFT)
TEST_F (GaugeAlgTest, Coulomb_FFT)
int main (int argc, char **argv)
Variables
int device
int xdim
int ydim
int zdim
int tdim
int gridsize_from_cmdline []
QudaReconstructType link_recon
QudaPrecision prec
char latfile []
int num_failures =0
int * num_failures_dev
Macro Definition Documentation
DABS
#define DABS (a) ((a)<(0.)?(-(a)):(a))
Definition at line 36 of file gauge_alg_test.cpp.
Referenced by GaugeAlgTest::CheckDeterminant(), and GaugeAlgTest::comparePlaquette().
MAX
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 35 of file gauge_alg_test.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 272 of file gauge_alg_test.cpp.
References device, endQuda(), finalizeComms(), fprintf(), gridsize_from_cmdline, fused_exterior_ndeg_tm_dslash_cuda_gen::i, initComms(), initQuda(), process_command_line_option(), tdim, xdim, ydim, and zdim.
TEST_F() [1/5]
TEST_F (GaugeAlgTest , Generation)
Definition at line 224 of file gauge_alg_test.cpp.
References quda::getLinkDeterminant(), quda::plaquette(), and QUDA_CUDA_FIELD_LOCATION.
TEST_F() [2/5]
TEST_F (GaugeAlgTest , Landau_Overrelaxation)
Definition at line 236 of file gauge_alg_test.cpp.
References quda::gaugefixingOVR(), quda::plaquette(), printfQuda, and QUDA_CUDA_FIELD_LOCATION.
TEST_F() [3/5]
TEST_F (GaugeAlgTest , Coulomb_Overrelaxation)
Definition at line 243 of file gauge_alg_test.cpp.
References quda::gaugefixingOVR(), quda::plaquette(), printfQuda, and QUDA_CUDA_FIELD_LOCATION.
TEST_F() [4/5]
TEST_F (GaugeAlgTest , Landau_FFT)
Definition at line 250 of file gauge_alg_test.cpp.
References quda::gaugefixingFFT(), quda::plaquette(), printfQuda, and QUDA_CUDA_FIELD_LOCATION.
TEST_F() [5/5]
TEST_F (GaugeAlgTest , Coulomb_FFT)
Definition at line 258 of file gauge_alg_test.cpp.
References quda::gaugefixingFFT(), quda::plaquette(), printfQuda, and QUDA_CUDA_FIELD_LOCATION.
Variable Documentation
device
int device
Definition at line 2238 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by main().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 50 of file test_util.cpp.
Referenced by main().
latfile
char latfile[]
Definition at line 1627 of file test_util.cpp.
link_recon
QudaReconstructType link_recon
Definition at line 1612 of file test_util.cpp.
Referenced by GaugeAlgTest::SetUp().
num_failures
int num_failures =0
Definition at line 32 of file gauge_alg_test.cpp.
Referenced by GaugeAlgTest::CallUnitarizeLinks(), CallUnitarizeLinks(), main(), and unitarize_link_test().
num_failures_dev
int* num_failures_dev
Definition at line 33 of file gauge_alg_test.cpp.
Referenced by GaugeAlgTest::CallUnitarizeLinks(), CallUnitarizeLinks(), hisq_force_test(), GaugeAlgTest::SetUp(), GaugeAlgTest::TearDown(), and unitarize_link_test().
prec
QudaPrecision prec
Definition at line 1615 of file test_util.cpp.
Referenced by GaugeAlgTest::CheckDeterminant(), GaugeAlgTest::comparePlaquette(), and GaugeAlgTest::SetUp().
tdim
int tdim
Definition at line 1623 of file test_util.cpp.
Referenced by main(), and GaugeAlgTest::SetUp().
xdim
int xdim
Definition at line 1620 of file test_util.cpp.
Referenced by main(), and GaugeAlgTest::SetUp().
ydim
int ydim
Definition at line 1621 of file test_util.cpp.
Referenced by main(), and GaugeAlgTest::SetUp().
zdim
int zdim
Definition at line 1622 of file test_util.cpp.
Referenced by main(), and GaugeAlgTest::SetUp().