QUDA: tests/hisq_unitarize_force_test.cpp File Reference
hisq_unitarize_force_test.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <quda.h>
#include "test_util.h"
#include "gauge_field.h"
#include "misc.h"
#include "hisq_force_reference.h"
#include "ks_improved_force.h"
#include "hw_quda.h"
#include <sys/time.h>
#include <dslash_quda.h>
Functions
void usage (char **argv)
void setPrecision (QudaPrecision precision)
void createNoisyLinkCPU (void **field, QudaPrecision prec, int seed)
static void hisq_force_init ()
static void hisq_force_end ()
static void hisq_force_test ()
static void display_test_info ()
int main (int argc, char **argv)
Variables
cudaGaugeField * cudaFatLink = NULL
cpuGaugeField * cpuFatLink = NULL
cudaGaugeField * cudaOprod = NULL
cpuGaugeField * cpuOprod = NULL
cudaGaugeField * cudaResult = NULL
cpuGaugeField * cpuResult = NULL
cpuGaugeField * cpuReference = NULL
static QudaGaugeParam gaugeParam
bool verify_results
double accuracy = 1e-5
int ODD_BIT = 1
int device
int xdim
int ydim
int zdim
int tdim
int gridsize_from_cmdline []
QudaReconstructType link_recon
QudaPrecision prec
QudaPrecision link_prec = QUDA_SINGLE_PRECISION
QudaPrecision hw_prec = QUDA_SINGLE_PRECISION
QudaPrecision cpu_hw_prec = QUDA_SINGLE_PRECISION
QudaPrecision mom_prec = QUDA_SINGLE_PRECISION
Function Documentation
createNoisyLinkCPU()
void createNoisyLinkCPU (void ** field, QudaPrecision prec, int seed)
Definition at line 56 of file hisq_unitarize_force_test.cpp.
References createSiteLinkCPU(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, prec, ptr, QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, rand(), srand(), and V.
Referenced by hisq_force_init().
display_test_info()
static void display_test_info () static
Definition at line 195 of file hisq_unitarize_force_test.cpp.
References get_prec_str(), get_recon_str(), link_prec, link_recon, printfQuda, return(), tdim, xdim, ydim, and zdim.
Referenced by main().
hisq_force_end()
static void hisq_force_end () static
Definition at line 130 of file hisq_unitarize_force_test.cpp.
References cpuFatLink, cpuOprod, cpuReference, cpuResult, cudaFatLink, cudaOprod, cudaResult, and endQuda().
Referenced by hisq_force_test().
hisq_force_init()
static void hisq_force_init () static
Definition at line 80 of file hisq_unitarize_force_test.cpp.
References quda::GaugeFieldParam::anisotropy, comm_rank(), QudaGaugeParam_s::cpu_prec, cpuFatLink, cpuOprod, cpuReference, cpuResult, quda::GaugeFieldParam::create, createNoisyLinkCPU(), QudaGaugeParam_s::cuda_prec, cudaFatLink, cudaOprod, cudaResult, device, QudaGaugeParam_s::gauge_order, quda::cpuGaugeField::Gauge_p(), gaugeParam, quda::LatticeFieldParam::ghostExchange, gParam, initQuda(), link_prec, link_recon, quda::GaugeFieldParam::link_type, quda::cudaGaugeField::loadCPUField(), quda::GaugeFieldParam::order, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_GAUGE_ORDER, QUDA_GENERAL_LINKS, QUDA_GHOST_EXCHANGE_NO, QUDA_QDP_GAUGE_ORDER, QUDA_ZERO_FIELD_CREATE, QudaGaugeParam_s::reconstruct, setDims(), tdim, QudaGaugeParam_s::X, xdim, ydim, and zdim.
Referenced by hisq_force_test().
hisq_force_test()
static void hisq_force_test (void) static
Definition at line 147 of file hisq_unitarize_force_test.cpp.
References accuracy, comm_allreduce_int(), comm_size(), compare_floats(), QudaGaugeParam_s::cpu_prec, cpuFatLink, cpuOprod, cpuReference, cpuResult, cudaFatLink, cudaOprod, cudaResult, e, errorQuda, quda::cpuGaugeField::Gauge_p(), gaugeParam, gaugeSiteSize, hisq_force_end(), hisq_force_init(), num_failures_dev, printfQuda, quda::cudaGaugeField::saveCPUField(), quda::fermion_force::setUnitarizeForceConstants(), unitarize_eps, quda::fermion_force::unitarizeForce(), quda::fermion_force::unitarizeForceCPU(), verify_results, and quda::LatticeField::Volume().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 209 of file hisq_unitarize_force_test.cpp.
References display_test_info(), finalizeComms(), fprintf(), gridsize_from_cmdline, hisq_force_test(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, initComms(), prec, process_command_line_option(), setPrecision(), and usage().
setPrecision()
void setPrecision (QudaPrecision precision)
Definition at line 46 of file hisq_unitarize_force_test.cpp.
References link_prec.
Referenced by main().
usage()
void usage (char ** argv)
Definition at line 1693 of file test_util.cpp.
Referenced by main().
Variable Documentation
accuracy
double accuracy = 1e-5
Definition at line 33 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_test().
cpu_hw_prec
QudaPrecision cpu_hw_prec = QUDA_SINGLE_PRECISION
Definition at line 43 of file hisq_unitarize_force_test.cpp.
cpuFatLink
cpuGaugeField* cpuFatLink = NULL
Definition at line 18 of file hisq_unitarize_force_test.cpp.
Referenced by computeKSLinkQuda(), hisq_force_end(), hisq_force_init(), and hisq_force_test().
cpuOprod
cpuGaugeField* cpuOprod = NULL
Definition at line 21 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_end(), hisq_force_init(), and hisq_force_test().
cpuReference
cpuGaugeField* cpuReference = NULL
Definition at line 27 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_end(), hisq_force_init(), and hisq_force_test().
cpuResult
cpuGaugeField* cpuResult = NULL
Definition at line 24 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_end(), hisq_force_init(), and hisq_force_test().
cudaFatLink
cudaGaugeField* cudaFatLink = NULL
Definition at line 17 of file hisq_unitarize_force_test.cpp.
Referenced by computeKSLinkQuda(), hisq_force_end(), hisq_force_init(), and hisq_force_test().
cudaOprod
cudaGaugeField* cudaOprod = NULL
Definition at line 20 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_end(), hisq_force_init(), and hisq_force_test().
cudaResult
cudaGaugeField* cudaResult = NULL
Definition at line 23 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_end(), hisq_force_init(), and hisq_force_test().
device
int device
Definition at line 2238 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by hisq_force_init().
gaugeParam
QudaGaugeParam gaugeParam static
Definition at line 29 of file hisq_unitarize_force_test.cpp.
Referenced by hisq_force_init(), and hisq_force_test().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 50 of file test_util.cpp.
Referenced by main().
hw_prec
QudaPrecision hw_prec = QUDA_SINGLE_PRECISION
Definition at line 42 of file hisq_unitarize_force_test.cpp.
link_prec
QudaPrecision link_prec = QUDA_SINGLE_PRECISION
Definition at line 41 of file hisq_unitarize_force_test.cpp.
Referenced by display_test_info(), hisq_force_init(), and setPrecision().
link_recon
QudaReconstructType link_recon
Definition at line 1612 of file test_util.cpp.
Referenced by display_test_info(), and hisq_force_init().
mom_prec
QudaPrecision mom_prec = QUDA_SINGLE_PRECISION
Definition at line 44 of file hisq_unitarize_force_test.cpp.
ODD_BIT
int ODD_BIT = 1
Definition at line 34 of file hisq_unitarize_force_test.cpp.
prec
QudaPrecision prec
Definition at line 1615 of file test_util.cpp.
Referenced by createNoisyLinkCPU(), and main().
tdim
int tdim
Definition at line 1623 of file test_util.cpp.
Referenced by display_test_info(), and hisq_force_init().
verify_results
bool verify_results
Definition at line 1641 of file test_util.cpp.
Referenced by hisq_force_test().
xdim
int xdim
Definition at line 1620 of file test_util.cpp.
Referenced by display_test_info(), and hisq_force_init().
ydim
int ydim
Definition at line 1621 of file test_util.cpp.
Referenced by display_test_info(), and hisq_force_init().
zdim
int zdim
Definition at line 1622 of file test_util.cpp.
Referenced by display_test_info(), and hisq_force_init().