QUDA: tests/hisq_force_reference.h File Reference
hisq_force_reference.h File Reference
#include <enum_quda.h>
#include <gauge_field.h>
Functions
void halfwilson_hisq_force_reference (float eps, float weight1, void *act_path_coeff, void *temp_x, void *sitelink, void *mom)
void halfwilson_hisq_force_reference (double eps, double weight1, void *act_path_coeff, void *temp_x, void *sitelink, void *mom)
void color_matrix_hisq_force_reference (float eps, float weight, void *act_path_coeff, void *temp_xx, void *sitelink, void *mom)
void computeHisqOuterProduct (void *src, void *dst, QudaPrecision precision)
void computeLinkOrderedOuterProduct (void *src, void *dest, QudaPrecision precision, int gauge_order)
void computeLinkOrderedOuterProduct (void *src, void *dest, QudaPrecision precision, size_t separation, int gauge_order)
void hisqStaplesForceCPU (const double *path_coeff, const QudaGaugeParam &param, quda::cpuGaugeField &oprod, quda::cpuGaugeField &link, quda::cpuGaugeField *newOprod)
void hisqCompleteForceCPU (const QudaGaugeParam &param, quda::cpuGaugeField &oprod, quda::cpuGaugeField &link, quda::cpuGaugeField *mom)
void hisqLongLinkForceCPU (double coeff, const QudaGaugeParam &param, quda::cpuGaugeField &oprod, quda::cpuGaugeField &link, quda::cpuGaugeField *newOprod)
Function Documentation
color_matrix_hisq_force_reference()
void color_matrix_hisq_force_reference (float eps, float weight, void * act_path_coeff, void * temp_xx, void * sitelink, void * mom)
Definition at line 1162 of file hisq_force_reference.cpp.
References do_color_matrix_hisq_force_reference().
computeHisqOuterProduct()
void computeHisqOuterProduct (void * src, void * dst, QudaPrecision precision)
Definition at line 512 of file hisq_force_reference.cpp.
References forwardShiftedOuterProduct(), QUDA_SINGLE_PRECISION, and src.
computeLinkOrderedOuterProduct() [1/2]
void computeLinkOrderedOuterProduct (void * src, void * dest, QudaPrecision precision, int gauge_order)
Definition at line 475 of file hisq_force_reference.cpp.
References computeLinkOrderedOuterProduct(), gauge_order, QUDA_SINGLE_PRECISION, and src.
computeLinkOrderedOuterProduct() [2/2]
void computeLinkOrderedOuterProduct (void * src, void * dest, QudaPrecision precision, size_t separation, int gauge_order)
Definition at line 485 of file hisq_force_reference.cpp.
References computeLinkOrderedOuterProduct(), gauge_order, QUDA_SINGLE_PRECISION, and src.
halfwilson_hisq_force_reference() [1/2]
void halfwilson_hisq_force_reference (float eps, float weight1, void * act_path_coeff, void * temp_x, void * sitelink, void * mom)
Definition at line 1138 of file hisq_force_reference.cpp.
References do_halfwilson_hisq_force_reference().
halfwilson_hisq_force_reference() [2/2]
void halfwilson_hisq_force_reference (double eps, double weight1, void * act_path_coeff, void * temp_x, void * sitelink, void * mom)
Definition at line 1150 of file hisq_force_reference.cpp.
References do_halfwilson_hisq_force_reference().
hisqCompleteForceCPU()
void hisqCompleteForceCPU (const QudaGaugeParam & param, quda::cpuGaugeField & oprod, quda::cpuGaugeField & link, quda::cpuGaugeField * mom)
Definition at line 1602 of file hisq_force_reference2.cpp.
References QudaGaugeParam_s::cpu_prec, errorQuda, quda::cpuGaugeField::Gauge_p(), param, QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, and QudaGaugeParam_s::X.
Referenced by hisq_force_test().
hisqLongLinkForceCPU()
void hisqLongLinkForceCPU (double coeff, const QudaGaugeParam & param, quda::cpuGaugeField & oprod, quda::cpuGaugeField & link, quda::cpuGaugeField * newOprod)
Definition at line 1514 of file hisq_force_reference2.cpp.
References dw_dslash_4D_cuda_gen::coeff(), QudaGaugeParam_s::cpu_prec, errorQuda, quda::cpuGaugeField::Gauge_p(), param, QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, and QudaGaugeParam_s::X.
Referenced by hisq_force_test().
hisqStaplesForceCPU()
void hisqStaplesForceCPU (const double * path_coeff, const QudaGaugeParam & param, quda::cpuGaugeField & oprod, quda::cpuGaugeField & link, quda::cpuGaugeField * newOprod)
Definition at line 1365 of file hisq_force_reference2.cpp.
References QudaGaugeParam_s::cpu_prec, errorQuda, PathCoefficients< Real >::five, free(), quda::cpuGaugeField::Gauge_p(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, len, PathCoefficients< Real >::lepage, malloc(), PathCoefficients< Real >::naik, PathCoefficients< Real >::one, param, QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, PathCoefficients< Real >::seven, PathCoefficients< Real >::three, Vh_ex, and QudaGaugeParam_s::X.
Referenced by hisq_force_test().