QUDA: tests/invert_test.cpp File Reference
invert_test.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <util_quda.h>
#include <test_util.h>
#include <dslash_util.h>
#include <blas_reference.h>
#include <wilson_dslash_reference.h>
#include <domain_wall_dslash_reference.h>
#include "misc.h"
#include <qio_field.h>
#include <quda.h>
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
Functions
void usage (char **)
void display_test_info ()
int main (int argc, char **argv)
Variables
QudaDslashType dslash_type
QudaTwistFlavorType twist_flavor
int device
int xdim
int ydim
int zdim
int tdim
int Lsdim
int gridsize_from_cmdline []
QudaPrecision prec
QudaPrecision prec_sloppy
QudaPrecision prec_precondition
QudaReconstructType link_recon
QudaReconstructType link_recon_sloppy
QudaReconstructType link_recon_precondition
QudaInverterType inv_type
QudaInverterType precon_type
int multishift
double mass
double mu
double anisotropy
double tol
double tol_hq
QudaMassNormalization normalization
QudaMatPCType matpc_type
double clover_coeff
bool compute_clover
int niter
int gcrNkrylov
int pipeline
int solution_accumulator_pipeline
char latfile []
Macro Definition Documentation
MAX
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 23 of file invert_test.cpp.
Referenced by main().
Function Documentation
display_test_info()
void display_test_info ()
Definition at line 72 of file invert_test.cpp.
References dimPartitioned(), dslash_type, get_dslash_str(), get_mass_normalization_str(), get_matpc_str(), get_prec_str(), get_recon_str(), link_recon, link_recon_sloppy, Lsdim, matpc_type, multishift, normalization, prec, prec_sloppy, printfQuda, return(), tdim, xdim, ydim, and zdim.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 96 of file invert_test.cpp.
References QudaGaugeParam_s::anisotropy, anisotropy, quda::blas::ax(), quda::blas::axpy(), QudaInvertParam_s::b_5, QudaInvertParam_s::c_5, QudaInvertParam_s::cl_pad, clock(), dslash_cuda_gen::clover, clover_coeff, QudaInvertParam_s::clover_coeff, QudaInvertParam_s::clover_cpu_prec, QudaInvertParam_s::clover_cuda_prec, QudaInvertParam_s::clover_cuda_prec_precondition, QudaInvertParam_s::clover_cuda_prec_sloppy, clover_mat(), clover_matpc(), QudaInvertParam_s::clover_order, QudaInvertParam_s::cloverGiB, cloverSiteSize, compute_clover, QudaInvertParam_s::compute_clover, QudaInvertParam_s::compute_clover_inverse, construct_clover_field(), construct_gauge_field(), cpu_prec, QudaGaugeParam_s::cpu_prec, QudaInvertParam_s::cpu_prec, cuda_prec, QudaGaugeParam_s::cuda_prec, QudaInvertParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_precondition, cuda_prec_precondition, QudaInvertParam_s::cuda_prec_precondition, QudaGaugeParam_s::cuda_prec_sloppy, cuda_prec_sloppy, QudaInvertParam_s::cuda_prec_sloppy, QudaInvertParam_s::dagger, device, QudaInvertParam_s::dirac_order, display_test_info(), double, dslash_type, QudaInvertParam_s::dslash_type, dw_4d_mat(), dw_4d_matpc(), dw_mat(), dw_matpc(), dw_setDims(), e, endQuda(), QudaInvertParam_s::epsilon, errorQuda, exit(), finalizeComms(), float, free(), freeCloverQuda(), freeGaugeQuda(), QudaGaugeParam_s::ga_pad, QudaInvertParam_s::gamma_basis, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, gauge_param, QudaGaugeParam_s::gaugeGiB, gaugeSiteSize, gcrNkrylov, QudaInvertParam_s::gcrNkrylov, QudaInvertParam_s::gflops, gridsize_from_cmdline, gSize, fused_exterior_ndeg_tm_dslash_cuda_gen::i, if(), initComms(), initQuda(), QudaInvertParam_s::input_location, inv_param, inv_type, QudaInvertParam_s::inv_type, QudaInvertParam_s::inv_type_precondition, invertMultiShiftQuda(), invertQuda(), QudaInvertParam_s::iter, QudaInvertParam_s::kappa, kappa5, latfile, link_recon, link_recon_precondition, link_recon_sloppy, loadCloverQuda(), loadGaugeQuda(), QudaInvertParam_s::Ls, Lsdim, QudaInvertParam_s::m5, malloc(), mass, QudaInvertParam_s::mass, QudaInvertParam_s::mass_normalization, matpc_type, QudaInvertParam_s::matpc_type, MAX, QudaInvertParam_s::max_res_increase, QudaInvertParam_s::maxiter, QudaInvertParam_s::maxiter_precondition, mdw_mat(), mdw_matpc(), memset(), mu, QudaInvertParam_s::mu, multishift, quda::blas::mxpy(), newQudaGaugeParam(), newQudaInvertParam(), niter, quda::norm(), norm_2(), normalization, QudaInvertParam_s::Nsteps, QudaInvertParam_s::num_offset, QudaInvertParam_s::offset, offset, QudaInvertParam_s::omega, QudaInvertParam_s::output_location, pipeline, QudaInvertParam_s::pipeline, prec, prec_precondition, prec_sloppy, precon_type, QudaInvertParam_s::precondition_cycle, QudaInvertParam_s::preserve_source, printfQuda, process_command_line_option(), QUDA_ADDITIVE_SCHWARZ, QUDA_CG_INVERTER, QUDA_CLOVER_WILSON_DSLASH, QUDA_CPU_FIELD_LOCATION, QUDA_DAG_NO, QUDA_DEFAULT_NORMALIZATION, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DIRAC_ORDER, QUDA_DIRECT_PC_SOLVE, QUDA_DOMAIN_WALL_4D_DSLASH, QUDA_DOMAIN_WALL_DSLASH, QUDA_DOUBLE_PRECISION, QUDA_GAUGE_FIXED_NO, QUDA_HEAVY_QUARK_RESIDUAL, QUDA_INVALID_PRECISION, QUDA_L2_RELATIVE_RESIDUAL, QUDA_MASS_NORMALIZATION, QUDA_MAT_SOLUTION, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_MOBIUS_DWF_DSLASH, QUDA_NORMOP_PC_SOLVE, QUDA_PACKED_CLOVER_ORDER, QUDA_PERIODIC_T, QUDA_PRESERVE_SOURCE_YES, QUDA_QDP_GAUGE_ORDER, QUDA_RECONSTRUCT_INVALID, QUDA_SILENT, QUDA_SINGLE_PRECISION, QUDA_TWIST_NONDEG_DOUBLET, QUDA_TWIST_SINGLET, QUDA_TWISTED_CLOVER_DSLASH, QUDA_TWISTED_MASS_DSLASH, QUDA_VERBOSE, QUDA_WILSON_DSLASH, QUDA_WILSON_LINKS, rand(), read_gauge_field(), QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_precondition, QudaGaugeParam_s::reconstruct_sloppy, QudaInvertParam_s::reliable_delta, QudaInvertParam_s::residual_type, QudaInvertParam_s::return_clover, QudaInvertParam_s::return_clover_inverse, QudaInvertParam_s::schwarz_type, QudaInvertParam_s::secs, setDims(), setSpinorSiteSize(), solution_accumulator_pipeline, QudaInvertParam_s::solution_accumulator_pipeline, QudaInvertParam_s::solution_type, QudaInvertParam_s::solve_type, QudaInvertParam_s::solver_normalization, QudaInvertParam_s::sp_pad, QudaInvertParam_s::spinorGiB, spinorOut, spinorSiteSize, spinorTmp, sqrt(), strcmp(), QudaGaugeParam_s::t_boundary, tdim, tm_mat(), tm_matpc(), tm_ndeg_mat(), tm_ndeg_matpc(), tmc_mat(), tmc_matpc(), tmp0, tmp1, tol, QudaInvertParam_s::tol, tol_hq, QudaInvertParam_s::tol_hq, QudaInvertParam_s::tol_hq_offset, QudaInvertParam_s::tol_offset, QudaInvertParam_s::tol_precondition, QudaInvertParam_s::tol_restart, QudaInvertParam_s::true_res, QudaInvertParam_s::true_res_hq, QudaInvertParam_s::true_res_hq_offset, QudaInvertParam_s::true_res_offset, twist_flavor, QudaInvertParam_s::twist_flavor, QudaGaugeParam_s::type, usage(), QudaInvertParam_s::use_sloppy_partial_accumulator, V, QudaInvertParam_s::verbosity, QudaInvertParam_s::verbosity_precondition, Vh, wil_mat(), wil_matpc(), QudaGaugeParam_s::X, xdim, ydim, and zdim.
usage()
void usage (char **)
Definition at line 1693 of file test_util.cpp.
Referenced by main().
Variable Documentation
anisotropy
double anisotropy
Definition at line 1644 of file test_util.cpp.
Referenced by main().
clover_coeff
double clover_coeff
Definition at line 1645 of file test_util.cpp.
Referenced by main().
compute_clover
bool compute_clover
Definition at line 1646 of file test_util.cpp.
Referenced by main().
device
int device
Definition at line 2238 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by main().
dslash_type
QudaDslashType dslash_type
Definition at line 1626 of file test_util.cpp.
Referenced by display_test_info(), and main().
gcrNkrylov
int gcrNkrylov
Definition at line 1631 of file test_util.cpp.
Referenced by main(), and printQudaInvertParam().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 50 of file test_util.cpp.
Referenced by main().
inv_type
QudaInverterType inv_type
Definition at line 1638 of file test_util.cpp.
Referenced by main().
latfile
char latfile[]
Definition at line 1627 of file test_util.cpp.
Referenced by main().
link_recon
QudaReconstructType link_recon
Definition at line 1612 of file test_util.cpp.
Referenced by display_test_info(), and main().
link_recon_precondition
QudaReconstructType link_recon_precondition
Definition at line 1614 of file test_util.cpp.
Referenced by main().
link_recon_sloppy
QudaReconstructType link_recon_sloppy
Definition at line 1613 of file test_util.cpp.
Referenced by display_test_info(), and main().
Lsdim
int Lsdim
Definition at line 1624 of file test_util.cpp.
Referenced by display_test_info(), and main().
mass
double mass
Definition at line 1642 of file test_util.cpp.
Referenced by main().
matpc_type
QudaMatPCType matpc_type
Definition at line 1652 of file test_util.cpp.
Referenced by display_test_info(), and main().
mu
double mu
Definition at line 1643 of file test_util.cpp.
Referenced by main().
multishift
int multishift
Definition at line 1640 of file test_util.cpp.
Referenced by display_test_info(), and main().
niter
int niter
Definition at line 1630 of file test_util.cpp.
Referenced by main().
normalization
QudaMassNormalization normalization
Definition at line 1651 of file test_util.cpp.
Referenced by display_test_info(), and main().
pipeline
int pipeline
Definition at line 1632 of file test_util.cpp.
Referenced by main(), quda::BiCGstabL::operator()(), quda::GCR::operator()(), quda::orthoDir(), quda::BiCGstabL::orthoDir(), and printQudaInvertParam().
prec
QudaPrecision prec
Definition at line 1615 of file test_util.cpp.
Referenced by display_test_info(), and main().
prec_precondition
QudaPrecision prec_precondition
Definition at line 1617 of file test_util.cpp.
Referenced by main().
prec_sloppy
QudaPrecision prec_sloppy
Definition at line 1616 of file test_util.cpp.
Referenced by display_test_info(), and main().
precon_type
QudaInverterType precon_type
Definition at line 1639 of file test_util.cpp.
Referenced by main().
solution_accumulator_pipeline
int solution_accumulator_pipeline
Definition at line 1633 of file test_util.cpp.
Referenced by main(), and printQudaInvertParam().
tdim
int tdim
Definition at line 1623 of file test_util.cpp.
Referenced by display_test_info(), and main().
tol
double tol
Definition at line 1647 of file test_util.cpp.
Referenced by main().
tol_hq
double tol_hq
Definition at line 1648 of file test_util.cpp.
Referenced by main().
twist_flavor
QudaTwistFlavorType twist_flavor
Definition at line 1649 of file test_util.cpp.
Referenced by main().
xdim
int xdim
Definition at line 1620 of file test_util.cpp.
Referenced by display_test_info(), and main().
ydim
int ydim
Definition at line 1621 of file test_util.cpp.
Referenced by display_test_info(), and main().
zdim
int zdim
Definition at line 1622 of file test_util.cpp.
Referenced by display_test_info(), and main().