QUDA: include/layout_hyper.h File Reference
layout_hyper.h File Reference
Functions
int setup_layout (int len[], int nd, int numnodes)
int node_number (const int x[])
int node_index (const int x[])
void get_coords (int x[], int node, int index)
int num_sites (int node)
Variables
int this_node
Function Documentation
get_coords()
void get_coords (int x[], int node, int index)
Definition at line 232 of file layout_hyper.c.
References exit(), fprintf(), free(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, index(), ndim, node_index(), s, size1, size2, squaresize, this_node, and x.
Referenced by set_layout().
node_index()
int node_index (const int x[])
Definition at line 215 of file layout_hyper.c.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, ndim, p, sites_on_node, squaresize, and x.
Referenced by get_coords(), set_layout(), and vset_M().
node_number()
int node_number (const int x[])
Definition at line 205 of file layout_hyper.c.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, mcoord, ndim, squaresize, and x.
Referenced by set_layout(), and vset_M().
num_sites()
int num_sites (int node)
Definition at line 283 of file layout_hyper.c.
References sites_on_node.
Referenced by set_layout(), vcompare_M(), and vcreate_M().
setup_layout()
int setup_layout (int len[], int nd, int numnodes)
Definition at line 150 of file layout_hyper.c.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, int, len, malloc(), mcoord, ndim, nsquares, printf(), setup_hyper_prime(), setup_qmp_fixed(), setup_qmp_grid(), sites_on_node, size1, size2, and squaresize.
Referenced by set_layout().
Variable Documentation
this_node
int this_node
Definition at line 9 of file qio_field.cpp.
Referenced by get_coords(), open_test_input(), open_test_output(), read_gauge_field(), read_spinor_field(), set_layout(), setup_hyper_prime(), vcompare_M(), vcreate_M(), vset_M(), and write_spinor_field().