QUDA: tests/llfat_test.cpp File Reference
llfat_test.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include "quda.h"
#include "test_util.h"
#include "llfat_reference.h"
#include "misc.h"
#include "util_quda.h"
#include "malloc_quda.h"
Macros
#define TDIFF(a, b) (b.tv_sec - a.tv_sec + 0.000001*(b.tv_usec - a.tv_usec))
Functions
void usage (char **argv)
static void llfat_test ()
static void display_test_info ()
void usage_extra (char **argv)
int main (int argc, char **argv)
Variables
bool verify_results
int device
int xdim
int ydim
int zdim
int tdim
int gridsize_from_cmdline []
QudaReconstructType link_recon
QudaPrecision prec
int niter
static QudaPrecision cpu_prec = QUDA_DOUBLE_PRECISION
static QudaGaugeFieldOrder gauge_order = QUDA_MILC_GAUGE_ORDER
static size_t gSize
Macro Definition Documentation
TDIFF
#define TDIFF (a, b) (b.tv_sec - a.tv_sec + 0.000001*(b.tv_usec - a.tv_usec))
Definition at line 19 of file llfat_test.cpp.
Referenced by llfat_test().
Function Documentation
display_test_info()
static void display_test_info () static
Definition at line 334 of file llfat_test.cpp.
References dimPartitioned(), gauge_order, get_gauge_order_str(), get_prec_str(), get_recon_str(), link_recon, prec, printfQuda, return(), tdim, xdim, ydim, and zdim.
Referenced by main().
llfat_test()
static void llfat_test () static
Definition at line 38 of file llfat_test.cpp.
References QudaGaugeParam_s::anisotropy, dw_dslash_4D_cuda_gen::coeff(), compare_floats(), computeKSLinkQuda(), computeLongLinkCPU(), cpu_prec, QudaGaugeParam_s::cpu_prec, createSiteLinkCPU(), QudaGaugeParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, device, e, E1h, E2, E3, endQuda(), exchange_cpu_sitelink(), exchange_cpu_sitelink_ex(), exchange_llfat_cleanup(), fatlink, quda::blas::flops, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, gauge_order, QudaGaugeParam_s::gauge_order, gaugeSiteSize, gSize, host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, initQuda(), link_recon, llfat_reference(), llfat_reference_mg(), longlink, memcpy(), memset(), mu, newQudaGaugeParam(), niter, pinned_malloc, prec, printfQuda, QUDA_ANTI_PERIODIC_T, QUDA_DOUBLE_PRECISION, QUDA_GAUGE_FIXED_NO, QUDA_MILC_GAUGE_ORDER, QUDA_QDP_GAUGE_ORDER, QUDA_STAGGERED_PHASE_MILC, QUDA_WILSON_LINKS, qudaGaugeParam, R, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, safe_malloc, setDims(), sid, src, QudaGaugeParam_s::staggered_phase_type, strong_check_link(), QudaGaugeParam_s::t_boundary, TDIFF, tdim, QudaGaugeParam_s::type, V, V_ex, verify_results, Vh, Vh_ex, Vs, Vs_t, Vs_x, Vs_y, Vs_z, QudaGaugeParam_s::X, xdim, ydim, Z, za, zb, and zdim.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 363 of file llfat_test.cpp.
References cpu_prec, display_test_info(), exit(), finalizeComms(), fprintf(), gauge_order, gridsize_from_cmdline, fused_exterior_ndeg_tm_dslash_cuda_gen::i, initComms(), link_recon, llfat_test(), prec, process_command_line_option(), QUDA_DOUBLE_PRECISION, QUDA_MILC_GAUGE_ORDER, QUDA_QDP_GAUGE_ORDER, QUDA_RECONSTRUCT_NO, strcmp(), tdim, usage(), xdim, ydim, and zdim.
usage()
void usage (char ** argv)
Definition at line 1693 of file test_util.cpp.
Referenced by main().
usage_extra()
void usage_extra (char ** argv)
Definition at line 356 of file llfat_test.cpp.
References printfQuda, and return().
Variable Documentation
cpu_prec
QudaPrecision cpu_prec = QUDA_DOUBLE_PRECISION static
Definition at line 32 of file llfat_test.cpp.
Referenced by llfat_test(), and main().
device
int device
Definition at line 2238 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by llfat_test().
gauge_order
QudaGaugeFieldOrder gauge_order = QUDA_MILC_GAUGE_ORDER static
Definition at line 34 of file llfat_test.cpp.
Referenced by display_test_info(), llfat_test(), and main().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 50 of file test_util.cpp.
Referenced by main().
gSize
size_t gSize static
Definition at line 36 of file llfat_test.cpp.
Referenced by createMomCPU(), gauge_force_reference_dir(), gauge_force_test(), init(), invert_test(), llfat_test(), main(), and SU3test().
link_recon
QudaReconstructType link_recon
Definition at line 1612 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().
niter
int niter
Definition at line 1630 of file test_util.cpp.
Referenced by llfat_test().
prec
QudaPrecision prec
Definition at line 1615 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().
tdim
int tdim
Definition at line 1623 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().
verify_results
bool verify_results
Definition at line 1641 of file test_util.cpp.
Referenced by llfat_test().
xdim
int xdim
Definition at line 1620 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().
ydim
int ydim
Definition at line 1621 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().
zdim
int zdim
Definition at line 1622 of file test_util.cpp.
Referenced by display_test_info(), llfat_test(), and main().