QUDA: ndeg_tm_dslash_cuda_gen Namespace Reference
ndeg_tm_dslash_cuda_gen Namespace Reference
Functions
def complexify (a)
complex numbers ########################################################################
def complexToStr (c)
def gplus (g1, g2)
def gminus (g1, g2)
def projectorToStr (p)
def indent (code)
code generation ########################################################################
def block (code)
def sign (x)
def nthFloat4 (n)
def nthFloat2 (n)
def in_re (s, c)
def in_im (s, c)
def g_re (d, m, n)
def g_im (d, m, n)
def out1_re (s, c)
def out1_im (s, c)
def out2_re (s, c)
def out2_im (s, c)
def h1_re (h, c)
def h1_im (h, c)
def h2_re (h, c)
def h2_im (h, c)
def a_re (b, s, c)
def a_im (b, s, c)
def tmp_re (s, c)
def tmp_im (s, c)
def acc_re (s, c)
def acc_im (s, c)
def acc1_re (s, c)
def acc1_im (s, c)
def acc2_re (s, c)
def acc2_im (s, c)
def def_input_spinor ()
def def_gauge ()
def def_output_spinor ()
def prolog ()
def gen (dir, pack_only=False)
def twisted ()
def xpay ()
def epilog ()
def generate_dslash ()
temporal
def generate_dslash_kernels (arch)
Variables
def id
projector matrices ########################################################################
def gamma1
def gamma2
def gamma3
def gamma4
def igamma5
list projectors
int i = 3*s+c
start here
string a1 = ""
string a2 = ""
bool dslash = False
bool dagger = False
bool twist = False
int sharedFloatsPerFlavor = 0
bool sharedDslash = False
int arch = 200
Function Documentation
a_im()
def ndeg_tm_dslash_cuda_gen.a_im (b, s, c)
Definition at line 131 of file ndeg_tm_dslash_cuda_gen.py.
a_re()
def ndeg_tm_dslash_cuda_gen.a_re (b, s, c)
Definition at line 130 of file ndeg_tm_dslash_cuda_gen.py.
acc1_im()
def ndeg_tm_dslash_cuda_gen.acc1_im (s, c)
Definition at line 139 of file ndeg_tm_dslash_cuda_gen.py.
acc1_re()
def ndeg_tm_dslash_cuda_gen.acc1_re (s, c)
Definition at line 138 of file ndeg_tm_dslash_cuda_gen.py.
acc2_im()
def ndeg_tm_dslash_cuda_gen.acc2_im (s, c)
Definition at line 141 of file ndeg_tm_dslash_cuda_gen.py.
acc2_re()
def ndeg_tm_dslash_cuda_gen.acc2_re (s, c)
Definition at line 140 of file ndeg_tm_dslash_cuda_gen.py.
acc_im()
def ndeg_tm_dslash_cuda_gen.acc_im (s, c)
Definition at line 137 of file ndeg_tm_dslash_cuda_gen.py.
acc_re()
def ndeg_tm_dslash_cuda_gen.acc_re (s, c)
Definition at line 136 of file ndeg_tm_dslash_cuda_gen.py.
block()
def ndeg_tm_dslash_cuda_gen.block (code)
Definition at line 102 of file ndeg_tm_dslash_cuda_gen.py.
References indent().
Referenced by epilog(), gen(), and twisted().
complexify()
def ndeg_tm_dslash_cuda_gen.complexify (a)
complex numbers ########################################################################
Definition at line 6 of file ndeg_tm_dslash_cuda_gen.py.
complexToStr()
def ndeg_tm_dslash_cuda_gen.complexToStr (c)
Definition at line 9 of file ndeg_tm_dslash_cuda_gen.py.
References int.
Referenced by projectorToStr().
def_gauge()
def ndeg_tm_dslash_cuda_gen.def_gauge ()
Definition at line 173 of file ndeg_tm_dslash_cuda_gen.py.
References g_im(), g_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_input_spinor()
def ndeg_tm_dslash_cuda_gen.def_input_spinor ()
Definition at line 144 of file ndeg_tm_dslash_cuda_gen.py.
References in_im(), in_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_output_spinor()
def ndeg_tm_dslash_cuda_gen.def_output_spinor ()
Definition at line 206 of file ndeg_tm_dslash_cuda_gen.py.
References out1_im(), out1_re(), out2_im(), and out2_re().
Referenced by prolog().
epilog()
def ndeg_tm_dslash_cuda_gen.epilog ()
Definition at line 1042 of file ndeg_tm_dslash_cuda_gen.py.
References block(), g_im(), g_re(), in_im(), in_re(), out1_im(), out1_re(), twisted(), and xpay().
Referenced by generate_dslash().
g_im()
def ndeg_tm_dslash_cuda_gen.g_im (d, m, n)
Definition at line 121 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
g_re()
def ndeg_tm_dslash_cuda_gen.g_re (d, m, n)
Definition at line 120 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
gen()
def ndeg_tm_dslash_cuda_gen.gen (dir, pack_only = False)
Definition at line 426 of file ndeg_tm_dslash_cuda_gen.py.
References block(), g_im(), g_re(), h1_im(), h1_re(), h2_im(), h2_re(), in_im(), in_re(), indent(), out1_im(), out1_re(), out2_im(), out2_re(), projectorToStr(), and sign().
generate_dslash()
def ndeg_tm_dslash_cuda_gen.generate_dslash ()
temporal
Definition at line 1110 of file ndeg_tm_dslash_cuda_gen.py.
References epilog(), and prolog().
Referenced by generate_dslash_kernels().
generate_dslash_kernels()
def ndeg_tm_dslash_cuda_gen.generate_dslash_kernels (arch)
Definition at line 1116 of file ndeg_tm_dslash_cuda_gen.py.
References generate_dslash().
gminus()
def ndeg_tm_dslash_cuda_gen.gminus (g1, g2)
Definition at line 78 of file ndeg_tm_dslash_cuda_gen.py.
gplus()
def ndeg_tm_dslash_cuda_gen.gplus (g1, g2)
Definition at line 75 of file ndeg_tm_dslash_cuda_gen.py.
h1_im()
def ndeg_tm_dslash_cuda_gen.h1_im (h, c)
Definition at line 127 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by gen().
h1_re()
def ndeg_tm_dslash_cuda_gen.h1_re (h, c)
Definition at line 126 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by gen().
h2_im()
def ndeg_tm_dslash_cuda_gen.h2_im (h, c)
Definition at line 129 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by gen().
h2_re()
def ndeg_tm_dslash_cuda_gen.h2_re (h, c)
Definition at line 128 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by gen().
in_im()
def ndeg_tm_dslash_cuda_gen.in_im (s, c)
Definition at line 119 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), and prolog().
in_re()
def ndeg_tm_dslash_cuda_gen.in_re (s, c)
Definition at line 118 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), and prolog().
indent()
def ndeg_tm_dslash_cuda_gen.indent (code)
code generation ########################################################################
Definition at line 98 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by block(), gen(), and prolog().
nthFloat2()
def ndeg_tm_dslash_cuda_gen.nthFloat2 (n)
Definition at line 114 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_gauge(), and def_input_spinor().
nthFloat4()
def ndeg_tm_dslash_cuda_gen.nthFloat4 (n)
Definition at line 111 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_gauge(), and def_input_spinor().
out1_im()
def ndeg_tm_dslash_cuda_gen.out1_im (s, c)
Definition at line 123 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_output_spinor(), epilog(), gen(), prolog(), twisted(), and xpay().
out1_re()
def ndeg_tm_dslash_cuda_gen.out1_re (s, c)
Definition at line 122 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_output_spinor(), epilog(), gen(), prolog(), twisted(), and xpay().
out2_im()
def ndeg_tm_dslash_cuda_gen.out2_im (s, c)
Definition at line 125 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_output_spinor(), gen(), prolog(), twisted(), and xpay().
out2_re()
def ndeg_tm_dslash_cuda_gen.out2_re (s, c)
Definition at line 124 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by def_output_spinor(), gen(), prolog(), twisted(), and xpay().
projectorToStr()
def ndeg_tm_dslash_cuda_gen.projectorToStr (p)
Definition at line 81 of file ndeg_tm_dslash_cuda_gen.py.
References complexToStr().
Referenced by gen().
prolog()
def ndeg_tm_dslash_cuda_gen.prolog ()
Definition at line 238 of file ndeg_tm_dslash_cuda_gen.py.
References def_gauge(), def_input_spinor(), def_output_spinor(), in_im(), in_re(), indent(), out1_im(), out1_re(), out2_im(), and out2_re().
Referenced by generate_dslash().
sign()
def ndeg_tm_dslash_cuda_gen.sign (x)
Definition at line 105 of file ndeg_tm_dslash_cuda_gen.py.
Referenced by gen().
tmp_im()
def ndeg_tm_dslash_cuda_gen.tmp_im (s, c)
Definition at line 134 of file ndeg_tm_dslash_cuda_gen.py.
tmp_re()
def ndeg_tm_dslash_cuda_gen.tmp_re (s, c)
Definition at line 133 of file ndeg_tm_dslash_cuda_gen.py.
twisted()
def ndeg_tm_dslash_cuda_gen.twisted ()
Definition at line 765 of file ndeg_tm_dslash_cuda_gen.py.
References block(), out1_im(), out1_re(), out2_im(), and out2_re().
Referenced by epilog().
xpay()
def ndeg_tm_dslash_cuda_gen.xpay ()
Definition at line 833 of file ndeg_tm_dslash_cuda_gen.py.
References out1_im(), out1_re(), out2_im(), and out2_re().
Referenced by epilog().
Variable Documentation
a1
string ndeg_tm_dslash_cuda_gen.a1 = ""
Definition at line 961 of file ndeg_tm_dslash_cuda_gen.py.
a2
string ndeg_tm_dslash_cuda_gen.a2 = ""
Definition at line 962 of file ndeg_tm_dslash_cuda_gen.py.
arch
int ndeg_tm_dslash_cuda_gen.arch = 200
Definition at line 1175 of file ndeg_tm_dslash_cuda_gen.py.
dagger
bool ndeg_tm_dslash_cuda_gen.dagger = False
Definition at line 1166 of file ndeg_tm_dslash_cuda_gen.py.
dslash
bool ndeg_tm_dslash_cuda_gen.dslash = False
Definition at line 1165 of file ndeg_tm_dslash_cuda_gen.py.
gamma1
def ndeg_tm_dslash_cuda_gen.gamma1
Initial value:
 =  complexify([
     0,  0, 0, 1j,
     0,  0, 1j, 0,
     0, -1j, 0, 0,
     -1j,  0, 0, 0
 ])
Definition at line 39 of file ndeg_tm_dslash_cuda_gen.py.
gamma2
def ndeg_tm_dslash_cuda_gen.gamma2
Initial value:
 =  complexify([
     0, 0, 0, 1,
     0, 0, -1,  0,
     0, -1, 0,  0,
     1, 0, 0,  0
 ])
Definition at line 46 of file ndeg_tm_dslash_cuda_gen.py.
gamma3
def ndeg_tm_dslash_cuda_gen.gamma3
Initial value:
 =  complexify([
     0, 0, 1j,  0,
     0, 0, 0, -1j,
     -1j, 0, 0,  0,
     0, 1j, 0,  0
 ])
Definition at line 53 of file ndeg_tm_dslash_cuda_gen.py.
gamma4
def ndeg_tm_dslash_cuda_gen.gamma4
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, -1, 0,
     0, 0, 0, -1
 ])
Definition at line 60 of file ndeg_tm_dslash_cuda_gen.py.
i
int ndeg_tm_dslash_cuda_gen.i = 3*s+c
start here
Definition at line 868 of file ndeg_tm_dslash_cuda_gen.py.
id
def ndeg_tm_dslash_cuda_gen.id
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, 1, 0,
     0, 0, 0, 1
 ])
projector matrices ########################################################################
Definition at line 32 of file ndeg_tm_dslash_cuda_gen.py.
igamma5
def ndeg_tm_dslash_cuda_gen.igamma5
Initial value:
 =  complexify([
     0, 0, 1j, 0,
     0, 0, 0, 1j,
     1j, 0, 0, 0,
     0, 1j, 0, 0
 ])
Definition at line 67 of file ndeg_tm_dslash_cuda_gen.py.
projectors
list ndeg_tm_dslash_cuda_gen.projectors
Initial value:
 =  [
     gminus(id,gamma1), gplus(id,gamma1),
     gminus(id,gamma2), gplus(id,gamma2),
     gminus(id,gamma3), gplus(id,gamma3),
     gminus(id,gamma4), gplus(id,gamma4),
 ]
Definition at line 89 of file ndeg_tm_dslash_cuda_gen.py.
sharedDslash
bool ndeg_tm_dslash_cuda_gen.sharedDslash = False
Definition at line 1169 of file ndeg_tm_dslash_cuda_gen.py.
sharedFloatsPerFlavor
int ndeg_tm_dslash_cuda_gen.sharedFloatsPerFlavor = 0
Definition at line 1168 of file ndeg_tm_dslash_cuda_gen.py.
twist
bool ndeg_tm_dslash_cuda_gen.twist = False
Definition at line 1167 of file ndeg_tm_dslash_cuda_gen.py.