QUDA: quda::fermion_force Namespace Reference
quda::fermion_force Namespace Reference
Functions
void hisqStaplesForce (GaugeField &newOprod, const GaugeField &oprod, const GaugeField &link, const double path_coeff[6], long long *flops=nullptr)
Compute the fat-link contribution to the fermion force.
void hisqLongLinkForce (GaugeField &newOprod, const GaugeField &oprod, const GaugeField &link, double coeff, long long *flops=nullptr)
Compute the long-link contribution to the fermion force.
void hisqCompleteForce (GaugeField &momentum, const GaugeField &oprod, const GaugeField &link, long long *flops=nullptr)
Multiply the computed the force matrix by the gauge field and perform traceless anti-hermitian projection.
void setUnitarizeForceConstants (double unitarize_eps, double hisq_force_filter, double max_det_error, bool allow_svd, bool svd_only, double svd_rel_error, double svd_abs_error)
Set the constant parameters for the force unitarization.
void unitarizeForce (cudaGaugeField &newForce, const cudaGaugeField &oldForce, const cudaGaugeField &gauge, int *unitarization_failed, long long *flops=NULL)
Unitarize the fermion force.
void unitarizeForceCPU (cpuGaugeField &newForce, const cpuGaugeField &oldForce, const cpuGaugeField &gauge)
Unitarize the fermion force on CPU.
Function Documentation
hisqCompleteForce()
void quda::fermion_force::hisqCompleteForce (GaugeField & momentum, const GaugeField & oprod, const GaugeField & link, long long * flops = nullptr)
Multiply the computed the force matrix by the gauge field and perform traceless anti-hermitian projection.
Parameters
[out] momentum The computed momentum
[in] oprod The previously computed force
[in] link Thin-link gauge field
[out] flops number of flops performed
Referenced by computeHISQForceQuda(), and hisq_force_test().
hisqLongLinkForce()
void quda::fermion_force::hisqLongLinkForce (GaugeField & newOprod, const GaugeField & oprod, const GaugeField & link, double coeff, long long * flops = nullptr)
Compute the long-link contribution to the fermion force.
Parameters
[out] newOprod The computed force output
[in] oprod The previously computed input force
[in] link Thin-link gauge field
[in] coeff Long-link Coefficient
[out] flops number of flops performed
Referenced by computeHISQForceQuda(), and hisq_force_test().
hisqStaplesForce()
void quda::fermion_force::hisqStaplesForce (GaugeField & newOprod, const GaugeField & oprod, const GaugeField & link, const double path_coeff[6], long long * flops = nullptr)
Compute the fat-link contribution to the fermion force.
Parameters
[out] newOprod The computed force output
[in] oprod The previously computed input force
[in] link Thin-link gauge field
[in] path_coeff Coefficients of the contributions to the operator
[out] flops number of flops performed
Referenced by computeHISQForceQuda(), and hisq_force_test().
setUnitarizeForceConstants()
void quda::fermion_force::setUnitarizeForceConstants (double unitarize_eps, double hisq_force_filter, double max_det_error, bool allow_svd, bool svd_only, double svd_rel_error, double svd_abs_error)
Set the constant parameters for the force unitarization.
Referenced by computeHISQForceQuda(), and hisq_force_test().
unitarizeForce()
void quda::fermion_force::unitarizeForce (cudaGaugeField & newForce, const cudaGaugeField & oldForce, const cudaGaugeField & gauge, int * unitarization_failed, long long * flops = NULL)
Unitarize the fermion force.
Parameters
[in] newForce Unitarized output
[in] oldForce Input force
[in] gauge Gauge field
[out] unitarization_failed Whether the unitarization failed (number of failures)
[out] flops number of flops performed
Referenced by computeHISQForceQuda(), and hisq_force_test().
unitarizeForceCPU()
void quda::fermion_force::unitarizeForceCPU (cpuGaugeField & newForce, const cpuGaugeField & oldForce, const cpuGaugeField & gauge)
Unitarize the fermion force on CPU.
Parameters
[in] newForce Unitarized output
[in] oldForce Input force
[in] gauge Gauge field
Referenced by hisq_force_test().