QUDA: fused_exterior_deg_tmc_dslash_cuda_gen Namespace Reference
fused_exterior_deg_tmc_dslash_cuda_gen Namespace Reference
Functions
def complexify (a)
complex numbers ########################################################################
def complexToStr (c)
def gplus (g1, g2)
def gminus (g1, g2)
def projectorToStr (p)
def indent (code)
code generation ########################################################################
def block (code)
def sign (x)
def nthFloat4 (n)
def nthFloat2 (n)
def in_re (s, c)
def in_im (s, c)
def g_re (d, m, n)
def g_im (d, m, n)
def out_re (s, c)
def out_im (s, c)
def h1_re (h, c)
def h1_im (h, c)
def h2_re (h, c)
def h2_im (h, c)
def c_re (b, sm, cm, sn, cn)
def c_im (b, sm, cm, sn, cn)
def cinv_re (b, sm, cm, sn, cn)
def cinv_im (b, sm, cm, sn, cn)
def a_re (b, s, c)
def a_im (b, s, c)
def acc_re (s, c)
def acc_im (s, c)
def tmp_re (s, c)
def tmp_im (s, c)
def spinor (name, s, c, z)
def def_input_spinor ()
def def_gauge ()
def def_clover (pack_only=False)
def def_output_spinor ()
def prolog ()
def gen (dir, pack_only=False)
def input_spinor (s, c, z)
def clover_twisted_xpay ()
def epilog ()
def pack_face (facenum)
def generate_pack ()
def generate_dslash ()
def generate_dslash_kernels (arch)
Variables
def id
projector matrices ########################################################################
def gamma1
def gamma2
def gamma3
def gamma4
def igamma5
list projectors
bool dslash = False
bool dagger = False
bool twist = False
int sharedFloats = 0
bool sharedDslash = False
bool pack = False
int arch = 200
Function Documentation
a_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.a_im (b, s, c)
Definition at line 132 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
a_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.a_re (b, s, c)
Definition at line 131 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
acc_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.acc_im (s, c)
Definition at line 135 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by clover_twisted_xpay(), def_input_spinor(), and epilog().
acc_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.acc_re (s, c)
Definition at line 134 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by clover_twisted_xpay(), def_input_spinor(), and epilog().
block()
def fused_exterior_deg_tmc_dslash_cuda_gen.block (code)
Definition at line 101 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References indent().
Referenced by epilog(), gen(), generate_pack(), and pack_face().
c_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.c_im (b, sm, cm, sn, cn)
Definition at line 128 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), epilog(), and generate_pack().
c_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.c_re (b, sm, cm, sn, cn)
Definition at line 127 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), epilog(), and generate_pack().
cinv_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.cinv_im (b, sm, cm, sn, cn)
Definition at line 130 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), epilog(), and generate_pack().
cinv_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.cinv_re (b, sm, cm, sn, cn)
Definition at line 129 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), epilog(), and generate_pack().
clover_twisted_xpay()
def fused_exterior_deg_tmc_dslash_cuda_gen.clover_twisted_xpay ()
Definition at line 861 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References acc_im(), acc_re(), out_im(), and out_re().
Referenced by epilog().
complexify()
def fused_exterior_deg_tmc_dslash_cuda_gen.complexify (a)
complex numbers ########################################################################
Definition at line 5 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
complexToStr()
def fused_exterior_deg_tmc_dslash_cuda_gen.complexToStr (c)
Definition at line 8 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References int.
Referenced by projectorToStr().
def_clover()
def fused_exterior_deg_tmc_dslash_cuda_gen.def_clover (pack_only = False)
Definition at line 216 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References c_im(), c_re(), cinv_im(), cinv_re(), nthFloat2(), and nthFloat4().
Referenced by generate_pack(), and prolog().
def_gauge()
def fused_exterior_deg_tmc_dslash_cuda_gen.def_gauge ()
Definition at line 185 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References g_im(), g_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_input_spinor()
def fused_exterior_deg_tmc_dslash_cuda_gen.def_input_spinor ()
Definition at line 144 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References acc_im(), acc_re(), in_im(), in_re(), nthFloat2(), and nthFloat4().
Referenced by generate_pack(), and prolog().
def_output_spinor()
def fused_exterior_deg_tmc_dslash_cuda_gen.def_output_spinor ()
Definition at line 378 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References out_im(), and out_re().
Referenced by prolog().
epilog()
def fused_exterior_deg_tmc_dslash_cuda_gen.epilog ()
Definition at line 940 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References acc_im(), acc_re(), block(), c_im(), c_re(), cinv_im(), cinv_re(), clover_twisted_xpay(), g_im(), g_re(), in_im(), in_re(), out_im(), and out_re().
Referenced by generate_dslash().
g_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.g_im (d, m, n)
Definition at line 120 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
g_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.g_re (d, m, n)
Definition at line 119 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
gen()
def fused_exterior_deg_tmc_dslash_cuda_gen.gen (dir, pack_only = False)
Definition at line 528 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References block(), g_im(), g_re(), h1_im(), h1_re(), h2_im(), h2_re(), in_im(), in_re(), out_im(), out_re(), projectorToStr(), and sign().
generate_dslash()
def fused_exterior_deg_tmc_dslash_cuda_gen.generate_dslash ()
Definition at line 1098 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References epilog(), and prolog().
Referenced by generate_dslash_kernels().
generate_dslash_kernels()
def fused_exterior_deg_tmc_dslash_cuda_gen.generate_dslash_kernels (arch)
Definition at line 1102 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References generate_dslash().
generate_pack()
def fused_exterior_deg_tmc_dslash_cuda_gen.generate_pack ()
Definition at line 1040 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References block(), c_im(), c_re(), cinv_im(), cinv_re(), def_clover(), def_input_spinor(), in_im(), in_re(), and pack_face().
gminus()
def fused_exterior_deg_tmc_dslash_cuda_gen.gminus (g1, g2)
Definition at line 77 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
gplus()
def fused_exterior_deg_tmc_dslash_cuda_gen.gplus (g1, g2)
Definition at line 74 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
h1_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.h1_im (h, c)
Definition at line 124 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by gen().
h1_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.h1_re (h, c)
Definition at line 123 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by gen().
h2_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.h2_im (h, c)
Definition at line 126 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by gen().
h2_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.h2_re (h, c)
Definition at line 125 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by gen().
in_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.in_im (s, c)
Definition at line 118 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
in_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.in_re (s, c)
Definition at line 117 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
indent()
def fused_exterior_deg_tmc_dslash_cuda_gen.indent (code)
code generation ########################################################################
Definition at line 97 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by block(), pack_face(), and prolog().
input_spinor()
def fused_exterior_deg_tmc_dslash_cuda_gen.input_spinor (s, c, z)
Definition at line 852 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References in_im(), in_re(), out_im(), and out_re().
nthFloat2()
def fused_exterior_deg_tmc_dslash_cuda_gen.nthFloat2 (n)
Definition at line 113 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), def_gauge(), and def_input_spinor().
nthFloat4()
def fused_exterior_deg_tmc_dslash_cuda_gen.nthFloat4 (n)
Definition at line 110 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by def_clover(), def_gauge(), and def_input_spinor().
out_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.out_im (s, c)
Definition at line 122 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by clover_twisted_xpay(), def_output_spinor(), epilog(), gen(), input_spinor(), and prolog().
out_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.out_re (s, c)
Definition at line 121 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by clover_twisted_xpay(), def_output_spinor(), epilog(), gen(), input_spinor(), and prolog().
pack_face()
def fused_exterior_deg_tmc_dslash_cuda_gen.pack_face (facenum)
Definition at line 1026 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References block(), and indent().
Referenced by generate_pack().
projectorToStr()
def fused_exterior_deg_tmc_dslash_cuda_gen.projectorToStr (p)
Definition at line 80 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References complexToStr().
Referenced by gen().
prolog()
def fused_exterior_deg_tmc_dslash_cuda_gen.prolog ()
Definition at line 397 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
References def_clover(), def_gauge(), def_input_spinor(), def_output_spinor(), in_im(), in_re(), indent(), out_im(), and out_re().
Referenced by generate_dslash().
sign()
def fused_exterior_deg_tmc_dslash_cuda_gen.sign (x)
Definition at line 104 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Referenced by gen().
spinor()
def fused_exterior_deg_tmc_dslash_cuda_gen.spinor (name, s, c, z)
Definition at line 140 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
tmp_im()
def fused_exterior_deg_tmc_dslash_cuda_gen.tmp_im (s, c)
Definition at line 138 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
tmp_re()
def fused_exterior_deg_tmc_dslash_cuda_gen.tmp_re (s, c)
Definition at line 137 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
Variable Documentation
arch
int fused_exterior_deg_tmc_dslash_cuda_gen.arch = 200
Definition at line 1157 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
dagger
bool fused_exterior_deg_tmc_dslash_cuda_gen.dagger = False
Definition at line 1150 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
dslash
bool fused_exterior_deg_tmc_dslash_cuda_gen.dslash = False
Definition at line 1149 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
gamma1
def fused_exterior_deg_tmc_dslash_cuda_gen.gamma1
Initial value:
 =  complexify([
     0,  0, 0, 1j,
     0,  0, 1j, 0,
     0, -1j, 0, 0,
     -1j,  0, 0, 0
 ])
Definition at line 38 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
gamma2
def fused_exterior_deg_tmc_dslash_cuda_gen.gamma2
Initial value:
 =  complexify([
     0, 0, 0, 1,
     0, 0, -1,  0,
     0, -1, 0,  0,
     1, 0, 0,  0
 ])
Definition at line 45 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
gamma3
def fused_exterior_deg_tmc_dslash_cuda_gen.gamma3
Initial value:
 =  complexify([
     0, 0, 1j,  0,
     0, 0, 0, -1j,
     -1j, 0, 0,  0,
     0, 1j, 0,  0
 ])
Definition at line 52 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
gamma4
def fused_exterior_deg_tmc_dslash_cuda_gen.gamma4
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, -1, 0,
     0, 0, 0, -1
 ])
Definition at line 59 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
id
def fused_exterior_deg_tmc_dslash_cuda_gen.id
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, 1, 0,
     0, 0, 0, 1
 ])
projector matrices ########################################################################
Definition at line 31 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
igamma5
def fused_exterior_deg_tmc_dslash_cuda_gen.igamma5
Initial value:
 =  complexify([
     0, 0, 1j, 0,
     0, 0, 0, 1j,
     1j, 0, 0, 0,
     0, 1j, 0, 0
 ])
Definition at line 66 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
pack
bool fused_exterior_deg_tmc_dslash_cuda_gen.pack = False
Definition at line 1154 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
projectors
list fused_exterior_deg_tmc_dslash_cuda_gen.projectors
Initial value:
 =  [
     gminus(id,gamma1), gplus(id,gamma1),
     gminus(id,gamma2), gplus(id,gamma2),
     gminus(id,gamma3), gplus(id,gamma3),
     gminus(id,gamma4), gplus(id,gamma4),
 ]
Definition at line 88 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
sharedDslash
bool fused_exterior_deg_tmc_dslash_cuda_gen.sharedDslash = False
Definition at line 1153 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
sharedFloats
int fused_exterior_deg_tmc_dslash_cuda_gen.sharedFloats = 0
Definition at line 1152 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.
twist
bool fused_exterior_deg_tmc_dslash_cuda_gen.twist = False
Definition at line 1151 of file fused_exterior_deg_tmc_dslash_cuda_gen.py.