QUDA: fused_exterior_dw_dslash_4D_cuda_gen Namespace Reference
fused_exterior_dw_dslash_4D_cuda_gen Namespace Reference
Functions
def complexify (a)
complex numbers ########################################################################
def complexToStr (c)
def gplus (g1, g2)
def gminus (g1, g2)
def projectorToStr (p)
def indent (code, n=1)
code generation ########################################################################
def block (code)
def sign (x)
def nthFloat4 (n)
def nthFloat2 (n)
def in_re (s, c)
def in_im (s, c)
def g_re (d, m, n)
def g_im (d, m, n)
def out_re (s, c)
def out_im (s, c)
def h1_re (h, c)
def h1_im (h, c)
def h2_re (h, c)
def h2_im (h, c)
def c_re (b, sm, cm, sn, cn)
def c_im (b, sm, cm, sn, cn)
def a_re (b, s, c)
def a_im (b, s, c)
def tmp_re (s, c)
def tmp_im (s, c)
def def_input_spinor ()
def def_gauge ()
def def_clover ()
def def_output_spinor ()
def prolog ()
def gen (dir, pack_only=False)
def gen_dw_inv ()
def input_spinor (s, c, z)
def to_chiral_basis (c)
def from_chiral_basis (c)
def clover_mult (chi)
def apply_clover ()
def coeff ()
def ypax ()
def xpay ()
def epilog ()
def pack_face (facenum)
def generate_pack ()
def generate_dslash ()
def generate_dslash4D ()
def generate_dslash5D ()
Variables
def id
projector matrices ########################################################################
def gamma1
def gamma2
def gamma3
def gamma4
def igamma5
list two_P_L = [ id[x] - igamma5[x]/1j for x in range(0,4*4) ]
list two_P_R = [ id[x] + igamma5[x]/1j for x in range(0,4*4) ]
list projectors
int sharedFloats = 0
int cloverSharedFloats = 0
bool domain_wall = True
bool clover = False
bool dslash4 = True
bool dslash5 = False
bool normalDWF = False
bool dslash = True
bool dagger = False
f = open('dslash_core/dw_fused_exterior_dslash4_core.h', 'w')
Function Documentation
a_im()
def fused_exterior_dw_dslash_4D_cuda_gen.a_im (b, s, c)
Definition at line 140 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), from_chiral_basis(), and to_chiral_basis().
a_re()
def fused_exterior_dw_dslash_4D_cuda_gen.a_re (b, s, c)
Definition at line 139 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), from_chiral_basis(), and to_chiral_basis().
apply_clover()
def fused_exterior_dw_dslash_4D_cuda_gen.apply_clover ()
Definition at line 896 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References clover_mult(), from_chiral_basis(), and to_chiral_basis().
Referenced by epilog().
block()
def fused_exterior_dw_dslash_4D_cuda_gen.block (code)
Definition at line 111 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References indent().
Referenced by clover_mult(), epilog(), from_chiral_basis(), gen(), generate_pack(), pack_face(), and to_chiral_basis().
c_im()
def fused_exterior_dw_dslash_4D_cuda_gen.c_im (b, sm, cm, sn, cn)
Definition at line 138 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), def_clover(), and epilog().
c_re()
def fused_exterior_dw_dslash_4D_cuda_gen.c_re (b, sm, cm, sn, cn)
Definition at line 137 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), def_clover(), and epilog().
clover_mult()
def fused_exterior_dw_dslash_4D_cuda_gen.clover_mult (chi)
Definition at line 864 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References a_im(), a_re(), block(), c_im(), c_re(), out_im(), and out_re().
Referenced by apply_clover().
coeff()
def fused_exterior_dw_dslash_4D_cuda_gen.coeff ()
Definition at line 915 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by xpay().
complexify()
def fused_exterior_dw_dslash_4D_cuda_gen.complexify (a)
complex numbers ########################################################################
Definition at line 6 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
complexToStr()
def fused_exterior_dw_dslash_4D_cuda_gen.complexToStr (c)
Definition at line 9 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References int.
Referenced by projectorToStr().
def_clover()
def fused_exterior_dw_dslash_4D_cuda_gen.def_clover ()
Definition at line 212 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References c_im(), c_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_gauge()
def fused_exterior_dw_dslash_4D_cuda_gen.def_gauge ()
Definition at line 180 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References g_im(), g_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_input_spinor()
def fused_exterior_dw_dslash_4D_cuda_gen.def_input_spinor ()
Definition at line 146 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References in_im(), in_re(), nthFloat2(), and nthFloat4().
Referenced by generate_pack(), and prolog().
def_output_spinor()
def fused_exterior_dw_dslash_4D_cuda_gen.def_output_spinor ()
Definition at line 272 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References out_im(), and out_re().
Referenced by prolog().
epilog()
def fused_exterior_dw_dslash_4D_cuda_gen.epilog ()
Definition at line 996 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References apply_clover(), block(), c_im(), c_re(), g_im(), g_re(), in_im(), in_re(), out_im(), out_re(), and xpay().
Referenced by generate_dslash(), generate_dslash4D(), and generate_dslash5D().
from_chiral_basis()
def fused_exterior_dw_dslash_4D_cuda_gen.from_chiral_basis (c)
Definition at line 844 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References a_im(), a_re(), block(), out_im(), and out_re().
Referenced by apply_clover().
g_im()
def fused_exterior_dw_dslash_4D_cuda_gen.g_im (d, m, n)
Definition at line 130 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
g_re()
def fused_exterior_dw_dslash_4D_cuda_gen.g_re (d, m, n)
Definition at line 129 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_gauge(), epilog(), and gen().
gen()
def fused_exterior_dw_dslash_4D_cuda_gen.gen (dir, pack_only = False)
Definition at line 506 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References block(), g_im(), g_re(), h1_im(), h1_re(), h2_im(), h2_re(), in_im(), in_re(), indent(), out_im(), out_re(), projectorToStr(), and sign().
gen_dw_inv()
def fused_exterior_dw_dslash_4D_cuda_gen.gen_dw_inv ()
Definition at line 721 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
generate_dslash()
def fused_exterior_dw_dslash_4D_cuda_gen.generate_dslash ()
Definition at line 1101 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References epilog(), and prolog().
generate_dslash4D()
def fused_exterior_dw_dslash_4D_cuda_gen.generate_dslash4D ()
Definition at line 1108 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References epilog(), and prolog().
generate_dslash5D()
def fused_exterior_dw_dslash_4D_cuda_gen.generate_dslash5D ()
Definition at line 1115 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References epilog(), and prolog().
generate_pack()
def fused_exterior_dw_dslash_4D_cuda_gen.generate_pack ()
Definition at line 1075 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References block(), def_input_spinor(), in_im(), in_re(), and pack_face().
gminus()
def fused_exterior_dw_dslash_4D_cuda_gen.gminus (g1, g2)
Definition at line 87 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
gplus()
def fused_exterior_dw_dslash_4D_cuda_gen.gplus (g1, g2)
Definition at line 84 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
h1_im()
def fused_exterior_dw_dslash_4D_cuda_gen.h1_im (h, c)
Definition at line 134 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by gen().
h1_re()
def fused_exterior_dw_dslash_4D_cuda_gen.h1_re (h, c)
Definition at line 133 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by gen().
h2_im()
def fused_exterior_dw_dslash_4D_cuda_gen.h2_im (h, c)
Definition at line 136 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by gen().
h2_re()
def fused_exterior_dw_dslash_4D_cuda_gen.h2_re (h, c)
Definition at line 135 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by gen().
in_im()
def fused_exterior_dw_dslash_4D_cuda_gen.in_im (s, c)
Definition at line 128 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
in_re()
def fused_exterior_dw_dslash_4D_cuda_gen.in_re (s, c)
Definition at line 127 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
indent()
def fused_exterior_dw_dslash_4D_cuda_gen.indent (code, n = 1)
code generation ########################################################################
Definition at line 107 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by block(), gen(), pack_face(), and prolog().
input_spinor()
def fused_exterior_dw_dslash_4D_cuda_gen.input_spinor (s, c, z)
Definition at line 816 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References in_im(), in_re(), out_im(), and out_re().
Referenced by to_chiral_basis().
nthFloat2()
def fused_exterior_dw_dslash_4D_cuda_gen.nthFloat2 (n)
Definition at line 123 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_clover(), def_gauge(), def_input_spinor(), xpay(), and ypax().
nthFloat4()
def fused_exterior_dw_dslash_4D_cuda_gen.nthFloat4 (n)
Definition at line 120 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by def_clover(), def_gauge(), def_input_spinor(), xpay(), and ypax().
out_im()
def fused_exterior_dw_dslash_4D_cuda_gen.out_im (s, c)
Definition at line 132 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), def_output_spinor(), epilog(), from_chiral_basis(), gen(), input_spinor(), prolog(), to_chiral_basis(), xpay(), and ypax().
out_re()
def fused_exterior_dw_dslash_4D_cuda_gen.out_re (s, c)
Definition at line 131 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by clover_mult(), def_output_spinor(), epilog(), from_chiral_basis(), gen(), input_spinor(), prolog(), to_chiral_basis(), xpay(), and ypax().
pack_face()
def fused_exterior_dw_dslash_4D_cuda_gen.pack_face (facenum)
Definition at line 1061 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References block(), and indent().
Referenced by generate_pack().
projectorToStr()
def fused_exterior_dw_dslash_4D_cuda_gen.projectorToStr (p)
Definition at line 90 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References complexToStr().
Referenced by gen().
prolog()
def fused_exterior_dw_dslash_4D_cuda_gen.prolog ()
Definition at line 289 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References def_clover(), def_gauge(), def_input_spinor(), def_output_spinor(), in_im(), in_re(), indent(), out_im(), and out_re().
Referenced by generate_dslash(), generate_dslash4D(), and generate_dslash5D().
sign()
def fused_exterior_dw_dslash_4D_cuda_gen.sign (x)
Definition at line 114 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
Referenced by gen().
tmp_im()
def fused_exterior_dw_dslash_4D_cuda_gen.tmp_im (s, c)
Definition at line 143 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
tmp_re()
def fused_exterior_dw_dslash_4D_cuda_gen.tmp_re (s, c)
Definition at line 142 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
to_chiral_basis()
def fused_exterior_dw_dslash_4D_cuda_gen.to_chiral_basis (c)
Definition at line 824 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References a_im(), a_re(), block(), input_spinor(), out_im(), and out_re().
Referenced by apply_clover().
xpay()
def fused_exterior_dw_dslash_4D_cuda_gen.xpay ()
Definition at line 947 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References coeff(), nthFloat2(), nthFloat4(), out_im(), out_re(), and ypax().
Referenced by epilog().
ypax()
def fused_exterior_dw_dslash_4D_cuda_gen.ypax ()
Definition at line 925 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
References nthFloat2(), nthFloat4(), out_im(), and out_re().
Referenced by xpay().
Variable Documentation
clover
bool fused_exterior_dw_dslash_4D_cuda_gen.clover = False
Definition at line 1141 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
cloverSharedFloats
int fused_exterior_dw_dslash_4D_cuda_gen.cloverSharedFloats = 0
Definition at line 1133 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
dagger
bool fused_exterior_dw_dslash_4D_cuda_gen.dagger = False
Definition at line 1148 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
domain_wall
bool fused_exterior_dw_dslash_4D_cuda_gen.domain_wall = True
Definition at line 1140 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
dslash
bool fused_exterior_dw_dslash_4D_cuda_gen.dslash = True
Definition at line 1147 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
dslash4
bool fused_exterior_dw_dslash_4D_cuda_gen.dslash4 = True
Definition at line 1142 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
dslash5
bool fused_exterior_dw_dslash_4D_cuda_gen.dslash5 = False
Definition at line 1143 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
f
fused_exterior_dw_dslash_4D_cuda_gen.f = open('dslash_core/dw_fused_exterior_dslash4_core.h', 'w')
Definition at line 1149 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
gamma1
def fused_exterior_dw_dslash_4D_cuda_gen.gamma1
Initial value:
 =  complexify([
     0, 0, 0, 1j,
     0, 0, 1j, 0,
     0, -1j, 0, 0,
     -1j, 0, 0, 0
 ])
Definition at line 39 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
gamma2
def fused_exterior_dw_dslash_4D_cuda_gen.gamma2
Initial value:
 =  complexify([
     0, 0, 0, 1,
     0, 0, -1, 0,
     0, -1, 0, 0,
     1, 0, 0, 0
 ])
Definition at line 46 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
gamma3
def fused_exterior_dw_dslash_4D_cuda_gen.gamma3
Initial value:
 =  complexify([
     0, 0, 1j, 0,
     0, 0, 0, -1j,
     -1j, 0, 0, 0,
     0, 1j, 0, 0
 ])
Definition at line 53 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
gamma4
def fused_exterior_dw_dslash_4D_cuda_gen.gamma4
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, -1, 0,
     0, 0, 0, -1
 ])
Definition at line 60 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
id
def fused_exterior_dw_dslash_4D_cuda_gen.id
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, 1, 0,
     0, 0, 0, 1
 ])
projector matrices ########################################################################
Definition at line 32 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
igamma5
def fused_exterior_dw_dslash_4D_cuda_gen.igamma5
Initial value:
 =  complexify([
     0, 0, 1j, 0,
     0, 0, 0, 1j,
     1j, 0, 0, 0,
     0, 1j, 0, 0
 ])
Definition at line 67 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
normalDWF
bool fused_exterior_dw_dslash_4D_cuda_gen.normalDWF = False
Definition at line 1144 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
projectors
list fused_exterior_dw_dslash_4D_cuda_gen.projectors
Initial value:
 =  [
     gminus(id,gamma1), gplus(id,gamma1),
     gminus(id,gamma2), gplus(id,gamma2),
     gminus(id,gamma3), gplus(id,gamma3),
     gminus(id,gamma4), gplus(id,gamma4),
 ]
Definition at line 98 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
sharedFloats
fused_exterior_dw_dslash_4D_cuda_gen.sharedFloats = 0
Definition at line 1132 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
two_P_L
list fused_exterior_dw_dslash_4D_cuda_gen.two_P_L = [ id[x] - igamma5[x]/1j for x in range(0,4*4) ]
Definition at line 74 of file fused_exterior_dw_dslash_4D_cuda_gen.py.
two_P_R
list fused_exterior_dw_dslash_4D_cuda_gen.two_P_R = [ id[x] + igamma5[x]/1j for x in range(0,4*4) ]
Definition at line 75 of file fused_exterior_dw_dslash_4D_cuda_gen.py.