QUDA: fused_exterior_dslash_gen Namespace Reference
fused_exterior_dslash_gen Namespace Reference
Functions
def complexify (a)
complex numbers ########################################################################
def complexToStr (c)
def gplus (g1, g2)
def gminus (g1, g2)
def projectorToStr (p)
def indent (code)
code generation ########################################################################
def block (code)
def sign (x)
def nthFloat4 (n)
def nthFloat2 (n)
def in_re (s, c)
def in_im (s, c)
def g_re (d, m, n)
def g_im (d, m, n)
def out_re (s, c)
def out_im (s, c)
def h1_re (h, c)
def h1_im (h, c)
def h2_re (h, c)
def h2_im (h, c)
def c_re (b, sm, cm, sn, cn)
def c_im (b, sm, cm, sn, cn)
def a_re (b, s, c)
def a_im (b, s, c)
def acc_re (s, c)
def acc_im (s, c)
def tmp_re (s, c)
def tmp_im (s, c)
def spinor (name, s, c, z)
def def_input_spinor ()
def def_gauge ()
def def_clover ()
def def_output_spinor ()
def prolog ()
def gen (dir, pack_only=False)
def input_spinor (s, c, z)
def to_chiral_basis (v_out, v_in, c)
def from_chiral_basis (v_out, v_in, c)
def clover_mult (v_out, v_in, chi)
def apply_clover (v_out, v_in)
def twisted_rotate (x)
def twisted ()
def clover_xpay ()
def xpay ()
def epilog ()
def pack_face (facenum)
def generate_pack ()
def generate_dslash ()
def generate_clover ()
def generate_dslash_kernels (arch)
Variables
def id
projector matrices ########################################################################
def gamma1
def gamma2
def gamma3
def gamma4
def igamma5
list projectors
bool dslash = False
bool dagger = False
bool twist = False
bool clover = False
bool asymClover = False
int sharedFloats = 0
bool sharedDslash = False
bool pack = False
int arch = 200
Function Documentation
a_im()
def fused_exterior_dslash_gen.a_im (b, s, c)
Definition at line 130 of file fused_exterior_dslash_gen.py.
Referenced by clover_mult(), from_chiral_basis(), and to_chiral_basis().
a_re()
def fused_exterior_dslash_gen.a_re (b, s, c)
Definition at line 129 of file fused_exterior_dslash_gen.py.
Referenced by clover_mult(), from_chiral_basis(), and to_chiral_basis().
acc_im()
def fused_exterior_dslash_gen.acc_im (s, c)
Definition at line 133 of file fused_exterior_dslash_gen.py.
Referenced by clover_xpay(), def_input_spinor(), epilog(), and xpay().
acc_re()
def fused_exterior_dslash_gen.acc_re (s, c)
Definition at line 132 of file fused_exterior_dslash_gen.py.
Referenced by clover_xpay(), def_input_spinor(), epilog(), and xpay().
apply_clover()
def fused_exterior_dslash_gen.apply_clover (v_out, v_in)
Definition at line 788 of file fused_exterior_dslash_gen.py.
References clover_mult(), from_chiral_basis(), and to_chiral_basis().
Referenced by clover_xpay(), and epilog().
block()
def fused_exterior_dslash_gen.block (code)
Definition at line 101 of file fused_exterior_dslash_gen.py.
References indent().
Referenced by clover_mult(), epilog(), from_chiral_basis(), gen(), generate_pack(), pack_face(), to_chiral_basis(), and twisted().
c_im()
def fused_exterior_dslash_gen.c_im (b, sm, cm, sn, cn)
Definition at line 128 of file fused_exterior_dslash_gen.py.
Referenced by clover_mult(), def_clover(), and epilog().
c_re()
def fused_exterior_dslash_gen.c_re (b, sm, cm, sn, cn)
Definition at line 127 of file fused_exterior_dslash_gen.py.
Referenced by clover_mult(), def_clover(), and epilog().
clover_mult()
def fused_exterior_dslash_gen.clover_mult (v_out, v_in, chi)
Definition at line 756 of file fused_exterior_dslash_gen.py.
References a_im(), a_re(), block(), c_im(), c_re(), and spinor().
Referenced by apply_clover().
clover_xpay()
def fused_exterior_dslash_gen.clover_xpay ()
Definition at line 865 of file fused_exterior_dslash_gen.py.
References acc_im(), acc_re(), apply_clover(), out_im(), and out_re().
complexify()
def fused_exterior_dslash_gen.complexify (a)
complex numbers ########################################################################
Definition at line 5 of file fused_exterior_dslash_gen.py.
complexToStr()
def fused_exterior_dslash_gen.complexToStr (c)
Definition at line 8 of file fused_exterior_dslash_gen.py.
References int.
Referenced by projectorToStr().
def_clover()
def fused_exterior_dslash_gen.def_clover ()
Definition at line 215 of file fused_exterior_dslash_gen.py.
References c_im(), c_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_gauge()
def fused_exterior_dslash_gen.def_gauge ()
Definition at line 183 of file fused_exterior_dslash_gen.py.
References g_im(), g_re(), nthFloat2(), and nthFloat4().
Referenced by prolog().
def_input_spinor()
def fused_exterior_dslash_gen.def_input_spinor ()
Definition at line 142 of file fused_exterior_dslash_gen.py.
References acc_im(), acc_re(), in_im(), in_re(), nthFloat2(), and nthFloat4().
Referenced by generate_pack(), and prolog().
def_output_spinor()
def fused_exterior_dslash_gen.def_output_spinor ()
Definition at line 276 of file fused_exterior_dslash_gen.py.
References out_im(), and out_re().
Referenced by prolog().
epilog()
def fused_exterior_dslash_gen.epilog ()
Definition at line 910 of file fused_exterior_dslash_gen.py.
References acc_im(), acc_re(), apply_clover(), block(), c_im(), c_re(), g_im(), g_re(), in_im(), in_re(), out_im(), out_re(), twisted(), and xpay().
Referenced by generate_clover(), and generate_dslash().
from_chiral_basis()
def fused_exterior_dslash_gen.from_chiral_basis (v_out, v_in, c)
Definition at line 736 of file fused_exterior_dslash_gen.py.
References a_im(), a_re(), block(), and spinor().
Referenced by apply_clover().
g_im()
def fused_exterior_dslash_gen.g_im (d, m, n)
Definition at line 120 of file fused_exterior_dslash_gen.py.
Referenced by def_gauge(), epilog(), and gen().
g_re()
def fused_exterior_dslash_gen.g_re (d, m, n)
Definition at line 119 of file fused_exterior_dslash_gen.py.
Referenced by def_gauge(), epilog(), and gen().
gen()
def fused_exterior_dslash_gen.gen (dir, pack_only = False)
Definition at line 448 of file fused_exterior_dslash_gen.py.
References block(), g_im(), g_re(), h1_im(), h1_re(), h2_im(), h2_re(), in_im(), in_re(), out_im(), out_re(), projectorToStr(), and sign().
generate_clover()
def fused_exterior_dslash_gen.generate_clover ()
Definition at line 1039 of file fused_exterior_dslash_gen.py.
References epilog(), and prolog().
generate_dslash()
def fused_exterior_dslash_gen.generate_dslash ()
Definition at line 1036 of file fused_exterior_dslash_gen.py.
References epilog(), and prolog().
Referenced by generate_dslash_kernels().
generate_dslash_kernels()
def fused_exterior_dslash_gen.generate_dslash_kernels (arch)
Definition at line 1043 of file fused_exterior_dslash_gen.py.
References generate_dslash().
generate_pack()
def fused_exterior_dslash_gen.generate_pack ()
Definition at line 1009 of file fused_exterior_dslash_gen.py.
References block(), def_input_spinor(), in_im(), in_re(), and pack_face().
gminus()
def fused_exterior_dslash_gen.gminus (g1, g2)
Definition at line 77 of file fused_exterior_dslash_gen.py.
gplus()
def fused_exterior_dslash_gen.gplus (g1, g2)
Definition at line 74 of file fused_exterior_dslash_gen.py.
h1_im()
def fused_exterior_dslash_gen.h1_im (h, c)
Definition at line 124 of file fused_exterior_dslash_gen.py.
Referenced by gen().
h1_re()
def fused_exterior_dslash_gen.h1_re (h, c)
Definition at line 123 of file fused_exterior_dslash_gen.py.
Referenced by gen().
h2_im()
def fused_exterior_dslash_gen.h2_im (h, c)
Definition at line 126 of file fused_exterior_dslash_gen.py.
Referenced by gen().
h2_re()
def fused_exterior_dslash_gen.h2_re (h, c)
Definition at line 125 of file fused_exterior_dslash_gen.py.
Referenced by gen().
in_im()
def fused_exterior_dslash_gen.in_im (s, c)
Definition at line 118 of file fused_exterior_dslash_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
in_re()
def fused_exterior_dslash_gen.in_re (s, c)
Definition at line 117 of file fused_exterior_dslash_gen.py.
Referenced by def_input_spinor(), epilog(), gen(), generate_pack(), input_spinor(), and prolog().
indent()
def fused_exterior_dslash_gen.indent (code)
code generation ########################################################################
Definition at line 97 of file fused_exterior_dslash_gen.py.
Referenced by block(), pack_face(), and prolog().
input_spinor()
def fused_exterior_dslash_gen.input_spinor (s, c, z)
Definition at line 709 of file fused_exterior_dslash_gen.py.
References in_im(), in_re(), out_im(), and out_re().
nthFloat2()
def fused_exterior_dslash_gen.nthFloat2 (n)
Definition at line 113 of file fused_exterior_dslash_gen.py.
Referenced by def_clover(), def_gauge(), and def_input_spinor().
nthFloat4()
def fused_exterior_dslash_gen.nthFloat4 (n)
Definition at line 110 of file fused_exterior_dslash_gen.py.
Referenced by def_clover(), def_gauge(), and def_input_spinor().
out_im()
def fused_exterior_dslash_gen.out_im (s, c)
Definition at line 122 of file fused_exterior_dslash_gen.py.
Referenced by clover_xpay(), def_output_spinor(), epilog(), gen(), input_spinor(), prolog(), twisted(), twisted_rotate(), and xpay().
out_re()
def fused_exterior_dslash_gen.out_re (s, c)
Definition at line 121 of file fused_exterior_dslash_gen.py.
Referenced by clover_xpay(), def_output_spinor(), epilog(), gen(), input_spinor(), prolog(), twisted(), twisted_rotate(), and xpay().
pack_face()
def fused_exterior_dslash_gen.pack_face (facenum)
Definition at line 995 of file fused_exterior_dslash_gen.py.
References block(), and indent().
Referenced by generate_pack().
projectorToStr()
def fused_exterior_dslash_gen.projectorToStr (p)
Definition at line 80 of file fused_exterior_dslash_gen.py.
References complexToStr().
Referenced by gen().
prolog()
def fused_exterior_dslash_gen.prolog ()
Definition at line 295 of file fused_exterior_dslash_gen.py.
References def_clover(), def_gauge(), def_input_spinor(), def_output_spinor(), in_im(), in_re(), indent(), out_im(), and out_re().
Referenced by generate_clover(), and generate_dslash().
sign()
def fused_exterior_dslash_gen.sign (x)
Definition at line 104 of file fused_exterior_dslash_gen.py.
Referenced by gen(), and twisted_rotate().
spinor()
def fused_exterior_dslash_gen.spinor (name, s, c, z)
Definition at line 138 of file fused_exterior_dslash_gen.py.
Referenced by clover_mult(), from_chiral_basis(), and to_chiral_basis().
tmp_im()
def fused_exterior_dslash_gen.tmp_im (s, c)
Definition at line 136 of file fused_exterior_dslash_gen.py.
Referenced by twisted(), and twisted_rotate().
tmp_re()
def fused_exterior_dslash_gen.tmp_re (s, c)
Definition at line 135 of file fused_exterior_dslash_gen.py.
Referenced by twisted(), and twisted_rotate().
to_chiral_basis()
def fused_exterior_dslash_gen.to_chiral_basis (v_out, v_in, c)
Definition at line 717 of file fused_exterior_dslash_gen.py.
References a_im(), a_re(), block(), and spinor().
Referenced by apply_clover().
twisted()
def fused_exterior_dslash_gen.twisted ()
Definition at line 843 of file fused_exterior_dslash_gen.py.
References block(), out_im(), out_re(), tmp_im(), tmp_re(), and twisted_rotate().
Referenced by epilog().
twisted_rotate()
def fused_exterior_dslash_gen.twisted_rotate (x)
Definition at line 806 of file fused_exterior_dslash_gen.py.
References out_im(), out_re(), sign(), tmp_im(), and tmp_re().
Referenced by twisted().
xpay()
def fused_exterior_dslash_gen.xpay ()
Definition at line 883 of file fused_exterior_dslash_gen.py.
References acc_im(), acc_re(), out_im(), and out_re().
Referenced by epilog().
Variable Documentation
arch
int fused_exterior_dslash_gen.arch = 200
Definition at line 1137 of file fused_exterior_dslash_gen.py.
asymClover
bool fused_exterior_dslash_gen.asymClover = False
Definition at line 1131 of file fused_exterior_dslash_gen.py.
clover
bool fused_exterior_dslash_gen.clover = False
Definition at line 1130 of file fused_exterior_dslash_gen.py.
dagger
bool fused_exterior_dslash_gen.dagger = False
Definition at line 1128 of file fused_exterior_dslash_gen.py.
dslash
bool fused_exterior_dslash_gen.dslash = False
Definition at line 1127 of file fused_exterior_dslash_gen.py.
gamma1
def fused_exterior_dslash_gen.gamma1
Initial value:
 =  complexify([
     0,  0, 0, 1j,
     0,  0, 1j, 0,
     0, -1j, 0, 0,
     -1j,  0, 0, 0
 ])
Definition at line 38 of file fused_exterior_dslash_gen.py.
gamma2
def fused_exterior_dslash_gen.gamma2
Initial value:
 =  complexify([
     0, 0, 0, 1,
     0, 0, -1,  0,
     0, -1, 0,  0,
     1, 0, 0,  0
 ])
Definition at line 45 of file fused_exterior_dslash_gen.py.
gamma3
def fused_exterior_dslash_gen.gamma3
Initial value:
 =  complexify([
     0, 0, 1j,  0,
     0, 0, 0, -1j,
     -1j, 0, 0,  0,
     0, 1j, 0,  0
 ])
Definition at line 52 of file fused_exterior_dslash_gen.py.
gamma4
def fused_exterior_dslash_gen.gamma4
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, -1, 0,
     0, 0, 0, -1
 ])
Definition at line 59 of file fused_exterior_dslash_gen.py.
id
def fused_exterior_dslash_gen.id
Initial value:
 =  complexify([
     1, 0, 0, 0,
     0, 1, 0, 0,
     0, 0, 1, 0,
     0, 0, 0, 1
 ])
projector matrices ########################################################################
Definition at line 31 of file fused_exterior_dslash_gen.py.
igamma5
def fused_exterior_dslash_gen.igamma5
Initial value:
 =  complexify([
     0, 0, 1j, 0,
     0, 0, 0, 1j,
     1j, 0, 0, 0,
     0, 1j, 0, 0
 ])
Definition at line 66 of file fused_exterior_dslash_gen.py.
pack
bool fused_exterior_dslash_gen.pack = False
Definition at line 1134 of file fused_exterior_dslash_gen.py.
projectors
list fused_exterior_dslash_gen.projectors
Initial value:
 =  [
     gminus(id,gamma1), gplus(id,gamma1),
     gminus(id,gamma2), gplus(id,gamma2),
     gminus(id,gamma3), gplus(id,gamma3),
     gminus(id,gamma4), gplus(id,gamma4),
 ]
Definition at line 88 of file fused_exterior_dslash_gen.py.
sharedDslash
bool fused_exterior_dslash_gen.sharedDslash = False
Definition at line 1133 of file fused_exterior_dslash_gen.py.
sharedFloats
int fused_exterior_dslash_gen.sharedFloats = 0
Definition at line 1132 of file fused_exterior_dslash_gen.py.
twist
bool fused_exterior_dslash_gen.twist = False
Definition at line 1129 of file fused_exterior_dslash_gen.py.