QUDA: std::__1 Namespace Reference
std::__1 Namespace Reference
Namespaces
__detail
__is_construct
__libcpp_is_function_imp
Classes
struct __add_const
struct __add_const< _Tp, false >
struct __add_lvalue_reference_impl
struct __add_lvalue_reference_impl< _Tp, true >
struct __add_pointer_impl
struct __add_pointer_impl< _Tp, false >
struct __add_volatile
struct __add_volatile< _Tp, false >
struct __align_type
struct __any
struct __decay
struct __decay< _Up, true >
struct __find_max_align
struct __find_max_align< __type_list< _Hp, __nat >, _Len >
struct __find_max_align< __type_list< _Hp, _Tp >, _Len >
struct __find_pod
struct __find_pod< __type_list< _Hp, __nat >, _Align >
struct __find_pod< __type_list< _Hp, _Tp >, _Align >
struct __identity
struct __is_nothrow_swappable
struct __is_nullptr_t_impl
struct __is_nullptr_t_impl< nullptr_t >
struct __is_reference_wrapper
struct __is_reference_wrapper_impl
struct __is_reference_wrapper_impl< reference_wrapper< _Tp > >
struct __is_referenceable
struct __is_referenceable_impl
struct __is_same_uncvref
struct __is_swappable
struct __libcpp_compute_min
struct __libcpp_compute_min< _Tp, __digits, false >
struct __libcpp_is_floating_point
struct __libcpp_is_floating_point< double >
struct __libcpp_is_floating_point< float >
struct __libcpp_is_floating_point< long double >
struct __libcpp_is_function
struct __libcpp_is_function< _Tp, true >
struct __libcpp_is_integral
struct __libcpp_is_integral< __int128_t >
struct __libcpp_is_integral< __uint128_t >
struct __libcpp_is_integral< bool >
struct __libcpp_is_integral< char >
struct __libcpp_is_integral< char16_t >
struct __libcpp_is_integral< char32_t >
struct __libcpp_is_integral< int >
struct __libcpp_is_integral< long >
struct __libcpp_is_integral< long long >
struct __libcpp_is_integral< short >
struct __libcpp_is_integral< signed char >
struct __libcpp_is_integral< unsigned char >
struct __libcpp_is_integral< unsigned int >
struct __libcpp_is_integral< unsigned long >
struct __libcpp_is_integral< unsigned long long >
struct __libcpp_is_integral< unsigned short >
struct __libcpp_is_integral< wchar_t >
struct __libcpp_is_member_function_pointer
struct __libcpp_is_member_function_pointer< _Ret _Class::* >
struct __libcpp_is_member_pointer
struct __libcpp_is_member_pointer< _Tp _Up::* >
struct __libcpp_is_pointer
struct __libcpp_is_pointer< _Tp * >
struct __libcpp_is_signed
struct __libcpp_is_signed< _Tp, false >
struct __libcpp_is_signed_impl
struct __libcpp_is_signed_impl< _Tp, false >
struct __libcpp_is_unsigned
struct __libcpp_is_unsigned< _Tp, false >
struct __libcpp_is_unsigned_impl
struct __libcpp_is_unsigned_impl< _Tp, false >
struct __libcpp_is_void
struct __libcpp_is_void< void >
struct __libcpp_nothrow_destructor
class __libcpp_numeric_limits
class __libcpp_numeric_limits< _Tp, true >
class __libcpp_numeric_limits< bool, true >
class __libcpp_numeric_limits< double, true >
class __libcpp_numeric_limits< float, true >
class __libcpp_numeric_limits< long double, true >
struct __member_pointer_class_type
struct __member_pointer_class_type< _Ret _ClassType::* >
struct __member_pointer_traits
struct __member_pointer_traits_imp
struct __member_pointer_traits_imp< _Rp _Class::*, false, true >
struct __member_pointer_traits_imp< _Rp(_Class::*)() const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)() const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)() volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(...) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(...) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(...) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(...), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2,...) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2,...) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2,...) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1, _P2,...), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1,...) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1,...) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1,...) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0, _P1,...), true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0,...) const volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0,...) const, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0,...) volatile, true, false >
struct __member_pointer_traits_imp< _Rp(_Class::*)(_P0,...), true, false >
struct __nat
struct __numeric_type
struct __numeric_type< void >
class __promote
class __promote_imp
class __promote_imp< _A1, _A2, _A3, true >
class __promote_imp< _A1, _A2, void, true >
class __promote_imp< _A1, void, void, true >
class __result_of
class __result_of< _Fn(_A0), true, false >
class __result_of< _Fn(_A0, _A1), true, false >
class __result_of< _Fn(_A0, _A1, _A2), true, false >
class __result_of< _Fn(_Tp), false, true >
class __result_of< _Fn(_Tp, _A0), false, true >
class __result_of< _Fn(_Tp, _A0, _A1), false, true >
class __result_of< _Fn(_Tp, _A0, _A1, _A2), false, true >
struct __result_of_mdp
struct __result_of_mdp< _Rp _Class::*, _Tp, false >
struct __result_of_mdp< _Rp _Class::*, _Tp, true >
struct __result_of_mp
struct __result_of_mp< _MP, _Tp, true >
struct __result_of_mp< _Rp _Class::*, _Tp, false >
struct __select_align
struct __sfinae_underlying_type
struct __sfinae_underlying_type< _Tp, false >
struct __struct_double
struct __struct_double4
struct __two
struct __type_list
struct __unconstref
struct __uncvref
struct __void_t
struct is_trivially_assignable
class result_of
struct underlying_type
Typedefs
typedef long double max_align_t
typedef integral_constant< bool,(true)> true_type
typedef integral_constant< bool,(false)> false_type
typedef __type_list< __align_type< unsigned char >, __type_list< __align_type< unsigned short >, __type_list< __align_type< unsigned int >, __type_list< __align_type< unsigned long >, __type_list< __align_type< unsigned long long >, __type_list< __align_type< double >, __type_list< __align_type< long double >, __type_list< __align_type< __struct_double >, __type_list< __align_type< __struct_double4 >, __type_list< __align_type< int * >, __nat > > > > > > > > > > __all_types
typedef __type_list< signed char, __type_list< signed short, __type_list< signed int, __type_list< signed long, __type_list< signed long long, __type_list< __int128_t, __nat > > > > > > __signed_types
typedef __type_list< unsigned char, __type_list< unsigned short, __type_list< unsigned int, __type_list< unsigned long, __type_list< unsigned long long, __type_list< __uint128_t, __nat > > > > > > __unsigned_types
Enumerations
enum float_round_style {
round_indeterminate = -1, round_toward_zero = 0, round_to_nearest = 1, round_toward_infinity = 2,
round_toward_neg_infinity = 3, round_indeterminate = -1, round_toward_zero = 0, round_to_nearest = 1,
round_toward_infinity = 2, round_toward_neg_infinity = 3
}
enum float_denorm_style {
denorm_indeterminate = -1, denorm_absent = 0, denorm_present = 1, denorm_indeterminate = -1,
denorm_absent = 0, denorm_present = 1
}
enum float_round_style {
round_indeterminate = -1, round_toward_zero = 0, round_to_nearest = 1, round_toward_infinity = 2,
round_toward_neg_infinity = 3, round_indeterminate = -1, round_toward_zero = 0, round_to_nearest = 1,
round_toward_infinity = 2, round_toward_neg_infinity = 3
}
enum float_denorm_style {
denorm_indeterminate = -1, denorm_absent = 0, denorm_present = 1, denorm_indeterminate = -1,
denorm_absent = 0, denorm_present = 1
}
Functions
struct __attribute__ ((__type_visibility__("default"))) nullptr_t {}
__attribute__ ((__visibility__("hidden"), __always_inline__)) nullptr_t __get_nullptr_t()
template<class _Tp >
__attribute__ ((__no_sanitize__("cfi"))) __attribute__((__visibility__("hidden")
__always_inline__ _Tp * addressof (_Tp &__x) throw ()
template<class _Tp >
struct __attribute__((__type_visibility__("default"))) is_pointer struct __attribute__((__type_visibility__("default"))) is_lvalue_reference struct __attribute__((__type_visibility__("default"))) is_lvalue_reference< _Tp & > struct __attribute__((__type_visibility__("default"))) is_rvalue_reference struct __attribute__((__type_visibility__("default"))) is_reference struct __attribute__((__type_visibility__("default"))) is_reference< _Tp & > struct __attribute__((__type_visibility__("default"))) is_union struct __attribute__((__type_visibility__("default"))) is_class struct __attribute__((__type_visibility__("default"))) is_same struct __attribute__ ((__type_visibility__("default"))) is_same< _Tp
template<class _Tp >
struct __attribute__ ((__type_visibility__("default"))) remove_reference< _Tp &>
template<class _Tp >
add_lvalue_reference< _Tp >::type declval ()
template<class _TypeList , size_t _Size, bool = _Size <= sizeof(typename _TypeList::_Head)>
__attribute__ ((__visibility__("hidden"), __always_inline__)) explicit __rv(_Trr &__t) {return &t_
struct __attribute__((__type_visibility__("default"))) is_constructible struct __attribute__((__type_visibility__("default"))) is_default_constructible struct __attribute__((__type_visibility__("default"))) is_copy_constructible struct __attribute__((__type_visibility__("default"))) is_move_constructible struct __attribute__((__type_visibility__("default"))) is_trivially_constructible struct __is_trivially_constructible (_Tp)>
struct __is_trivially_constructible (_Tp, _Tp)>
struct const _Tp __is_trivially_constructible (_Tp, const _Tp &)>
struct _Tp __is_trivially_constructible (_Tp, _Tp &)>
struct __attribute__((__type_visibility__("default"))) is_trivially_copy_assignable struct __attribute__((__type_visibility__("default"))) is_trivially_move_assignable struct __attribute__((__type_visibility__("default"))) is_trivially_destructible struct __attribute__((__type_visibility__("default"))) is_nothrow_constructible struct __has_nothrow_constructor (_Tp)>
struct __has_nothrow_copy (_Tp)>
template<class _Tp >
struct __attribute__((__type_visibility__("default"))) is_nothrow_default_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_copy_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_move_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_assignable struct __attribute__ ((__type_visibility__("default"))) is_nothrow_assignable< _Tp &
struct __attribute__((__type_visibility__("default"))) is_nothrow_default_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_copy_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_move_constructible struct __attribute__((__type_visibility__("default"))) is_nothrow_assignable struct __has_nothrow_assign (_Tp)>
template<class _Tp >
__attribute__ ((__visibility__("hidden"), __always_inline__)) void swap(_Tp &__x
struct __attribute ((__type_visibility__("default"))) nullptr_t
__attribute ((__visibility__("hidden"), __always_inline__)) inline nullptr_t __get_nullptr_t()
Variables
struct __attribute__((__type_visibility__("default"))) is_pointer struct __attribute__((__type_visibility__("default"))) is_lvalue_reference struct __attribute__((__type_visibility__("default"))) is_lvalue_reference< _Tp & > struct __attribute__((__type_visibility__("default"))) is_rvalue_reference struct __attribute__((__type_visibility__("default"))) is_reference struct __attribute__((__type_visibility__("default"))) is_reference< _Tp & > struct __attribute__((__type_visibility__("default"))) is_union struct __attribute__((__type_visibility__("default"))) is_class struct __attribute__((__type_visibility__("default"))) is_same struct _Tp
struct __attribute__((__type_visibility__("default"))) is_unsigned struct __attribute__((__type_visibility__("default"))) rank struct __attribute__((__type_visibility__("default"))) rank< _Tp[]> struct __attribute__((__type_visibility__("default"))) rank< _Tp[_Np]> struct __attribute__((__type_visibility__("default"))) extent struct struct _Ip
class __attribute__((__type_visibility__("default"))) result_of< _Fn()> class __attribute__((__type_visibility__("default"))) result_of< _Fn(_A0)> class _A1
_Tp & __y
__x = std::__1::move(__y)
__attribute__((__visibility__("hidden"), __always_inline__)) typename enable_if< __is_swappable< _Tp > _ForwardIterator2 __b
Typedef Documentation
__all_types
typedef __type_list< __align_type< unsigned char >, __type_list< __align_type< unsigned short >, __type_list< __align_type< unsigned int >, __type_list< __align_type< unsigned long >, __type_list< __align_type< unsigned long long >, __type_list< __align_type< double >, __type_list< __align_type< long double >, __type_list< __align_type< __struct_double >, __type_list< __align_type< __struct_double4 >, __type_list< __align_type< int * >, __nat > > > > > > > > > > std::__1::__all_types
Definition at line 6033 of file CMakeCUDACompilerId.cpp1.ii.
__signed_types
typedef __type_list< signed char, __type_list< signed short, __type_list< signed int, __type_list< signed long, __type_list< signed long long, __type_list< __int128_t, __nat > > > > > > std::__1::__signed_types
Definition at line 6192 of file CMakeCUDACompilerId.cpp1.ii.
__unsigned_types
typedef __type_list< unsigned char, __type_list< unsigned short, __type_list< unsigned int, __type_list< unsigned long, __type_list< unsigned long long, __type_list< __uint128_t, __nat > > > > > > std::__1::__unsigned_types
Definition at line 6207 of file CMakeCUDACompilerId.cpp1.ii.
false_type
typedef integral_constant< bool,(false)> std::__1::false_type
Definition at line 5548 of file CMakeCUDACompilerId.cpp1.ii.
max_align_t
typedef long double std::__1::max_align_t
Definition at line 3990 of file CMakeCUDACompilerId.cpp1.ii.
true_type
typedef integral_constant< bool,(true)> std::__1::true_type
Definition at line 5547 of file CMakeCUDACompilerId.cpp1.ii.
Enumeration Type Documentation
float_denorm_style [1/2]
enum std::__1::float_denorm_style
Enumerator
denorm_indeterminate
denorm_absent
denorm_present
denorm_indeterminate
denorm_absent
denorm_present
Definition at line 6657 of file CMakeCUDACompilerId.cpp4.ii.
float_denorm_style [2/2]
enum std::__1::float_denorm_style
Enumerator
denorm_indeterminate
denorm_absent
denorm_present
denorm_indeterminate
denorm_absent
denorm_present
Definition at line 8808 of file CMakeCUDACompilerId.cpp1.ii.
float_round_style [1/2]
enum std::__1::float_round_style
Enumerator
round_indeterminate
round_toward_zero
round_to_nearest
round_toward_infinity
round_toward_neg_infinity
round_indeterminate
round_toward_zero
round_to_nearest
round_toward_infinity
round_toward_neg_infinity
Definition at line 6648 of file CMakeCUDACompilerId.cpp4.ii.
float_round_style [2/2]
enum std::__1::float_round_style
Enumerator
round_indeterminate
round_toward_zero
round_to_nearest
round_toward_infinity
round_toward_neg_infinity
round_indeterminate
round_toward_zero
round_to_nearest
round_toward_infinity
round_toward_neg_infinity
Definition at line 8799 of file CMakeCUDACompilerId.cpp1.ii.
Function Documentation
__attribute() [1/2]
std::__1::__attribute ((__visibility__("hidden"), __always_inline__))
Definition at line 818 of file CMakeCUDACompilerId.cudafe1.cpp.
__attribute() [2/2]
struct std::__1::__attribute ((__type_visibility__("default")))
Definition at line 788 of file CMakeCUDACompilerId.cudafe1.cpp.
References _Tp, quda::operator!=(), and quda::operator==().
__attribute__() [1/8]
std::__1::__attribute__ ((__visibility__("hidden"), __always_inline__)) inline
Definition at line 449 of file CMakeCUDACompilerId.cpp1.ii.
__attribute__() [2/8]
template<class _Tp > std::__1::__attribute__ ((__no_sanitize__("cfi"))) inline
__attribute__() [3/8]
template<class _Tp > struct __attribute__ ((__type_visibility__("default"))) is_pointer struct __attribute__ ((__type_visibility__("default"))) is_lvalue_reference struct __attribute__ ((__type_visibility__("default"))) is_lvalue_reference<_Tp &> struct __attribute__ ((__type_visibility__("default"))) is_rvalue_reference struct __attribute__ ((__type_visibility__("default"))) is_reference struct __attribute__ ((__type_visibility__("default"))) is_reference<_Tp &> struct __attribute__ ((__type_visibility__("default"))) is_union struct __attribute__ ((__type_visibility__("default"))) is_class struct __attribute__ ((__type_visibility__("default"))) is_same struct std::__1::__attribute__ ((__type_visibility__("default"))) &
__attribute__() [4/8]
template<class _Tp > struct std::__1::__attribute__ ((__type_visibility__("default"))) &
Definition at line 5794 of file CMakeCUDACompilerId.cpp1.ii.
References _Tp.
__attribute__() [5/8]
template<class _TypeList , size_t _Size, bool = _Size <= sizeof(typename _TypeList::_Head)> std::__1::__attribute__ ((__visibility__("hidden"), __always_inline__)) & {return &t_
Definition at line 6486 of file CMakeCUDACompilerId.cpp1.ii.
__attribute__() [6/8]
template<class _Tp > struct __attribute__ ((__type_visibility__("default"))) is_nothrow_default_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_copy_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_move_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_assignable struct std::__1::__attribute__ ((__type_visibility__("default"))) &
__attribute__() [7/8]
template<class _Tp > std::__1::__attribute__ ((__visibility__("hidden"), __always_inline__)) & inline
__attribute__() [8/8]
struct std::__1::__attribute__ ((__type_visibility__("default"))) {}
Definition at line 426 of file CMakeCUDACompilerId.cpp1.ii.
References _Tp, quda::operator!=(), and quda::operator==().
__has_nothrow_assign()
struct const _Tp std::__1::__has_nothrow_assign (_Tp)
Definition at line 7115 of file CMakeCUDACompilerId.cpp1.ii.
__has_nothrow_constructor()
struct __attribute__ ((__type_visibility__("default"))) is_trivially_copy_assignable struct __attribute__ ((__type_visibility__("default"))) is_trivially_move_assignable struct __attribute__ ((__type_visibility__("default"))) is_trivially_destructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_constructible struct std::__1::__has_nothrow_constructor (_Tp)
Definition at line 7052 of file CMakeCUDACompilerId.cpp1.ii.
__has_nothrow_copy()
struct _Tp std::__1::__has_nothrow_copy (_Tp)
Definition at line 7063 of file CMakeCUDACompilerId.cpp1.ii.
__is_trivially_constructible() [1/4]
struct __attribute__ ((__type_visibility__("default"))) is_constructible struct __attribute__ ((__type_visibility__("default"))) is_default_constructible struct __attribute__ ((__type_visibility__("default"))) is_copy_constructible struct __attribute__ ((__type_visibility__("default"))) is_move_constructible struct __attribute__ ((__type_visibility__("default"))) is_trivially_constructible struct std::__1::__is_trivially_constructible (_Tp)
Definition at line 6978 of file CMakeCUDACompilerId.cpp1.ii.
__is_trivially_constructible() [2/4]
struct std::__1::__is_trivially_constructible (_Tp , _Tp)
Definition at line 6985 of file CMakeCUDACompilerId.cpp1.ii.
__is_trivially_constructible() [3/4]
struct const _Tp std::__1::__is_trivially_constructible (_Tp , const _Tp &)
Definition at line 6992 of file CMakeCUDACompilerId.cpp1.ii.
__is_trivially_constructible() [4/4]
struct _Tp std::__1::__is_trivially_constructible (_Tp , _Tp &)
Definition at line 6999 of file CMakeCUDACompilerId.cpp1.ii.
addressof()
__always_inline__ _Tp * std::__1::addressof (_Tp & __x) throw ()
Definition at line 5521 of file CMakeCUDACompilerId.cpp1.ii.
References __x.
declval()
template<class _Tp > add_lvalue_reference< _Tp >::type std::__1::declval ()
Variable Documentation
__b
__attribute__ ((__visibility__("hidden"), __always_inline__)) typename enable_if< __is_swappable<_Tp> _ForwardIterator2 std::__1::__b
Initial value:
{
    swap(*__a, *__b)
Definition at line 7242 of file CMakeCUDACompilerId.cpp1.ii.
__x
std::__1::__x = std::__1::move(__y)
Definition at line 7224 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by __attribute__(), addressof(), and throw().
__y
_Tp & std::__1::__y
Initial value:
{
    _Tp __t(std::__1::move(__x))
Definition at line 7222 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by throw().
_A1
class __attribute__ ((__type_visibility__("default"))) result_of<_Fn()> class __attribute__ ((__type_visibility__("default"))) result_of<_Fn(_A0)> class std::__1::_A1
Definition at line 6915 of file CMakeCUDACompilerId.cpp1.ii.
_Ip
struct __attribute__ ((__type_visibility__("default"))) is_unsigned struct __attribute__ ((__type_visibility__("default"))) rank struct __attribute__ ((__type_visibility__("default"))) rank<_Tp[]> struct __attribute__ ((__type_visibility__("default"))) rank<_Tp[_Np]> struct __attribute__ ((__type_visibility__("default"))) extent struct struct std::__1::_Ip
Definition at line 5898 of file CMakeCUDACompilerId.cpp1.ii.
_Tp
struct __attribute__ ((__type_visibility__("default"))) is_nothrow_default_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_copy_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_move_constructible struct __attribute__ ((__type_visibility__("default"))) is_nothrow_assignable struct std::__1::_Tp
Definition at line 5657 of file CMakeCUDACompilerId.cpp1.ii.
Referenced by __attribute(), and __attribute__().