QUDA: tests/new_half.cu File Reference
new_half.cu File Reference
#include <quda_internal.h>
#include <register_traits.h>
Macros
#define MAX_USHORT 65535.0f
Functions
void ucopy (float &a, const ushort &b)
void ucopy (ushort &a, const float &b)
void old_load_half (float spinor[24], short *in, float *norm, int idx)
void old_save_half (float spinor[24], short *out, float *norm, int idx)
void new_load_half (float spinor[24], short *in, float *norm, int idx)
void new_save_half (float spinor[24], short *out, float *norm, int idx)
void oldCopyToHalf (short *out, float *norm, float *in, int N)
void oldCopyToFloat (float *out, short *in, float *norm, int N)
void newCopyToHalf (short *out, float *norm, float *in, int N)
void newCopyToFloat (float *out, short *in, float *norm, int N)
void insertNoise (float *field, int N, float power)
double l2 (float *a, float *b, int N)
int main ()
Macro Definition Documentation
MAX_USHORT
#define MAX_USHORT 65535.0f
Definition at line 16 of file new_half.cu.
Referenced by ucopy().
Function Documentation
insertNoise()
void insertNoise (float * field, int N, float power)
Definition at line 112 of file new_half.cu.
References comm_drand(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, and quda::pow().
Referenced by main().
l2()
double l2 (float * a, float * b, int N)
Definition at line 120 of file new_half.cu.
References a, b, fabs(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, and quda::sqrt().
Referenced by main().
main()
int main ()
Definition at line 135 of file new_half.cu.
References host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, insertNoise(), l2(), newCopyToFloat(), newCopyToHalf(), oldCopyToFloat(), oldCopyToHalf(), printf(), ref, and safe_malloc.
new_load_half()
void new_load_half (float spinor[24], short * in, float * norm, int idx)
Definition at line 43 of file new_half.cu.
References quda::copy(), quda::cos(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, in, quda::norm(), quda::sin(), spinor, and ucopy().
Referenced by newCopyToFloat().
new_save_half()
void new_save_half (float spinor[24], short * out, float * norm, int idx)
Definition at line 57 of file new_half.cu.
References quda::atan2(), quda::copy(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, quda::norm(), out, spinor, quda::sqrt(), tmp, and ucopy().
Referenced by newCopyToHalf().
newCopyToFloat()
void newCopyToFloat (float * out, short * in, float * norm, int N)
Definition at line 103 of file new_half.cu.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, new_load_half(), quda::norm(), out, and spinor.
Referenced by main().
newCopyToHalf()
void newCopyToHalf (short * out, float * norm, float * in, int N)
Definition at line 94 of file new_half.cu.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, new_save_half(), quda::norm(), out, and spinor.
Referenced by main().
old_load_half()
void old_load_half (float spinor[24], short * in, float * norm, int idx)
Definition at line 21 of file new_half.cu.
References quda::copy(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, in, quda::norm(), and spinor.
Referenced by oldCopyToFloat().
old_save_half()
void old_save_half (float spinor[24], short * out, float * norm, int idx)
Definition at line 30 of file new_half.cu.
References quda::copy(), fabs(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, quda::norm(), out, spinor, and tmp.
Referenced by oldCopyToHalf().
oldCopyToFloat()
void oldCopyToFloat (float * out, short * in, float * norm, int N)
Definition at line 85 of file new_half.cu.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, quda::norm(), old_load_half(), out, and spinor.
Referenced by main().
oldCopyToHalf()
void oldCopyToHalf (short * out, float * norm, float * in, int N)
Definition at line 76 of file new_half.cu.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, quda::norm(), old_save_half(), out, and spinor.
Referenced by main().
ucopy() [1/2]
void ucopy (float & a, const ushort & b) inline
Definition at line 17 of file new_half.cu.
References a, b, float, and MAX_USHORT.
Referenced by new_load_half(), and new_save_half().
ucopy() [2/2]
void ucopy (ushort & a, const float & b) inline
Definition at line 18 of file new_half.cu.
References a, b, and MAX_USHORT.