QUDA: lib/qio_util.cpp File Reference
qio_util.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <qio_util.h>
Functions
void print_m (suN_matrix *a)
void vfill_m (suN_matrix *a, int coords[], int rank)
void vset_M (suN_matrix *field[], int count)
int vcreate_M (suN_matrix *field[], int count)
void vdestroy_M (suN_matrix *field[], int count)
float vcompare_M (suN_matrix *fielda[], suN_matrix *fieldb[], int count)
void vput_M (char *s1, size_t index, int count, void *s2)
void vget_M (char *s1, size_t index, int count, void *s2)
int inside_subset (int x[], int lower[], int upper[])
Function Documentation
inside_subset()
int inside_subset (int x[], int lower[], int upper[])
Definition at line 134 of file qio_util.cpp.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, and x.
print_m()
void print_m (suN_matrix * a)
Definition at line 7 of file qio_util.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::i, and printf().
vcompare_M()
float vcompare_M (suN_matrix * fielda[], suN_matrix * fieldb[], int count)
Definition at line 77 of file qio_util.cpp.
References count, fused_exterior_ndeg_tm_dslash_cuda_gen::i, num_sites(), and this_node.
vcreate_M()
int vcreate_M (suN_matrix * field[], int count)
Definition at line 54 of file qio_util.cpp.
References count, fused_exterior_ndeg_tm_dslash_cuda_gen::i, malloc(), num_sites(), printf(), and this_node.
vdestroy_M()
void vdestroy_M (suN_matrix * field[], int count)
Definition at line 70 of file qio_util.cpp.
References count, free(), and fused_exterior_ndeg_tm_dslash_cuda_gen::i.
vfill_m()
void vfill_m (suN_matrix * a, int coords[], int rank)
Definition at line 17 of file qio_util.cpp.
References a, fused_exterior_ndeg_tm_dslash_cuda_gen::i, lattice_size, and rank.
Referenced by vset_M().
vget_M()
void vget_M (char * s1, size_t index, int count, void * s2)
Definition at line 117 of file qio_util.cpp.
References count, fused_exterior_ndeg_tm_dslash_cuda_gen::i, index(), and src.
vput_M()
void vput_M (char * s1, size_t index, int count, void * s2)
Definition at line 100 of file qio_util.cpp.
References count, fused_exterior_ndeg_tm_dslash_cuda_gen::i, index(), and src.
vset_M()
void vset_M (suN_matrix * field[], int count)
Definition at line 36 of file qio_util.cpp.
References count, fused_exterior_ndeg_tm_dslash_cuda_gen::i, index(), lattice_size, node_index(), node_number(), this_node, vfill_m(), and x.