QUDA: include/quda_fortran.h File Reference
quda_fortran.h File Reference
Fortran interface functions.
#include <quda_constants.h>
Functions
void init_quda_device_ (int *device)
void init_quda_memory_ ()
void init_quda_ (int *device)
void end_quda_ (void)
void comm_set_gridsize_ (int *grid)
void new_quda_gauge_param_ (QudaGaugeParam *param)
void new_quda_invert_param_ (QudaInvertParam *param)
void load_gauge_quda_ (void *h_gauge, QudaGaugeParam *param)
void free_gauge_quda_ (void)
void free_sloppy_gauge_quda_ (void)
void load_clover_quda_ (void *h_clover, void *h_clovinv, QudaInvertParam *inv_param)
void free_clover_quda_ (void)
void dslash_quda_ (void *h_out, void *h_in, QudaInvertParam *inv_param, QudaParity *parity)
void clover_quda_ (void *h_out, void *h_in, QudaInvertParam *inv_param, QudaParity *parity, int *inverse)
void mat_quda_ (void *h_out, void *h_in, QudaInvertParam *inv_param)
void mat_dag_mat_quda_ (void *h_out, void *h_in, QudaInvertParam *inv_param)
void invert_quda_ (void *h_x, void *h_b, QudaInvertParam *param)
void invert_multishift_quda_ (void *_hp_x, void *_hp_b, QudaInvertParam *param)
void update_gauge_field_quda_ (void *gauge, void *momentum, double *dt, bool *conj_mom, bool *exact, QudaGaugeParam *param)
void compute_staggered_force_quda_ (void *mom, double *dt, double *delta, void *gauge, void *x, QudaGaugeParam *gauge_param, QudaInvertParam *invert_param)
void compute_gauge_force_quda_ (void *mom, void *gauge, int *num_loop_types, double *coeff, double *dt, QudaGaugeParam *param)
Compute the gauge force and update the mometum field.
void apply_staggered_phase_quda_ ()
Apply the staggered phase factors to the resident gauge field.
void remove_staggered_phase_quda_ ()
Remove the staggered phase factors to the resident gauge field.
void kinetic_quda_ (double *kin, void *momentum, QudaGaugeParam *param)
Evaluate the kinetic (momentum) contribution to classical Hamiltonian for Hybrid Monte Carlo.
void plaq_quda_ (double plaq[3])
void set_kernel_pack_t_ (int *pack)
fTemporary function exposed for TIFR benchmarking
void flush_chrono_quda_ (int *index)
Flush the chronological history for the given index.
void register_pinned_quda_ (void *ptr, size_t *bytes)
Pinned a pre-existing memory allocation.
void unregister_pinned_quda_ (void *ptr)
Pinned a pre-existing memory allocation.
Detailed Description
Fortran interface functions.
The following are Fortran interface functions to QUDA that mirror the C-equivalents. This essentially just means making all calls by reference, using all the lower-case characters and adding a trailing underscore.
Definition in file quda_fortran.h.
Function Documentation
apply_staggered_phase_quda_()
void apply_staggered_phase_quda_ ()
Apply the staggered phase factors to the resident gauge field.
Definition at line 4901 of file interface_quda.cpp.
References quda::GaugeField::applyStaggeredPhase(), errorQuda, gaugePrecise, getVerbosity(), printfQuda, and QUDA_VERBOSE.
clover_quda_()
void clover_quda_ (void * h_out, void * h_in, QudaInvertParam * inv_param, QudaParity * parity, int * inverse)
Apply the clover operator or its inverse.
Parameters
h_out Result spinor field
h_in Input spinor field
param Contains all metadata regarding host and device storage
parity The source and destination parity of the field
inverse Whether to apply the inverse of the clover term
Definition at line 4730 of file interface_quda.cpp.
References cloverQuda(), inv_param, and parity.
comm_set_gridsize_()
void comm_set_gridsize_ (int * grid)
Setter method for the comm grid size to all us to reuse BQCD's MPI topology. This is considered a temporary hack that will be fixed when an interface for setting the logical topology is created (issue 31 on github).
BQCD wants a node mapping with x varying fastest.
Definition at line 4943 of file interface_quda.cpp.
References initCommsGridQuda().
compute_gauge_force_quda_()
void compute_gauge_force_quda_ (void * mom, void * gauge, int * num_loop_types, double * coeff, double * dt, QudaGaugeParam * param)
Compute the gauge force and update the mometum field.
Parameters
[in,out] mom The momentum field to be updated
[in] gauge The gauge field from which we compute the force
[in] num_loop_types Number of loop types in the gauge action
[in] loop_coeff Coefficients of the different loops in the Symanzik action
[in] dt The integration step size
[in] param The parameters of the external fields and the computation settings
Definition at line 4840 of file interface_quda.cpp.
References dw_dslash_4D_cuda_gen::coeff(), computeGaugeForceQuda(), createGaugeForcePaths(), errorQuda, host_free, fused_exterior_ndeg_tm_dslash_cuda_gen::i, param, and safe_malloc.
compute_staggered_force_quda_()
void compute_staggered_force_quda_ (void * mom, double * dt, double * delta, void * gauge, void * x, QudaGaugeParam * gauge_param, QudaInvertParam * invert_param)
Compute the naive staggered force. All fields must be in the same precision.
Parameters
mom Momentum field
dt Integrating step size
delta Additional scale factor when updating momentum (mom += delta * [force]_TA
gauge Gauge field (at present only supports resident gauge field)
x Array of single-parity solution vectors (at present only supports resident solutions)
gauge_param Gauge field meta data
invert_param Dirac and solver meta data
Definition at line 4896 of file interface_quda.cpp.
References computeStaggeredForceQuda(), delta, gauge_param, inv_param, and x.
dslash_quda_()
void dslash_quda_ (void * h_out, void * h_in, QudaInvertParam * inv_param, QudaParity * parity)
Apply the Dslash operator (D_{eo} or D_{oe}).
Parameters
h_out Result spinor field
h_in Input spinor field
param Contains all metadata regarding host and device storage
parity The destination parity of the field
Definition at line 4728 of file interface_quda.cpp.
References dslashQuda(), inv_param, and parity.
end_quda_()
void end_quda_ (void)
Finalize the library.
Definition at line 4721 of file interface_quda.cpp.
References endQuda().
flush_chrono_quda_()
void flush_chrono_quda_ (int * index)
Flush the chronological history for the given index.
Parameters
[in] index Index for which we are flushing
Definition at line 4765 of file interface_quda.cpp.
References flushChronoQuda(), and index().
free_clover_quda_()
void free_clover_quda_ (void)
Free QUDA's internal copy of the clover term and/or clover inverse.
Definition at line 4727 of file interface_quda.cpp.
References freeCloverQuda().
free_gauge_quda_()
void free_gauge_quda_ (void)
Free QUDA's internal copy of the gauge field.
Definition at line 4723 of file interface_quda.cpp.
References freeGaugeQuda().
free_sloppy_gauge_quda_()
void free_sloppy_gauge_quda_ (void)
Free QUDA's internal copy of the gauge field.
Definition at line 4724 of file interface_quda.cpp.
References freeSloppyGaugeQuda().
init_quda_()
void init_quda_ (int * device)
Initialize the library. Under the interface this just calls initQudaMemory and initQudaDevice.
Parameters
device CUDA device number to use. In a multi-GPU build, this parameter may be either set explicitly on a per-process basis or set to -1 to enable a default allocation of devices to processes.
Definition at line 4718 of file interface_quda.cpp.
References initQuda().
init_quda_device_()
void init_quda_device_ (int * device)
Initialize the library. This is a low-level interface that is called by initQuda. Calling initQudaDevice requires that the user also call initQudaMemory before using QUDA.
Parameters
device CUDA device number to use. In a multi-GPU build, this parameter may either be set explicitly on a per-process basis or set to -1 to enable a default allocation of devices to processes.
Definition at line 4719 of file interface_quda.cpp.
References initQudaDevice().
init_quda_memory_()
void init_quda_memory_ ()
Initialize the library persistant memory allocations (both host and device). This is a low-level interface that is called by initQuda. Calling initQudaMemory requires that the user has previously called initQudaDevice.
Definition at line 4720 of file interface_quda.cpp.
References initQudaMemory().
invert_multishift_quda_()
void invert_multishift_quda_ (void * _hp_x, void * _hp_b, QudaInvertParam * param)
Solve for multiple shifts (e.g., masses).
Parameters
_hp_x Array of solution spinor fields (large contiguous allocation)
_hp_b Array of source spinor fields
param Contains all metadata regarding host and device storage and solver parameters
Definition at line 4744 of file interface_quda.cpp.
References QudaGaugeParam_s::cpu_prec, errorQuda, gaugePrecise, fused_exterior_ndeg_tm_dslash_cuda_gen::i, invertMultiShiftQuda(), quda::GaugeField::Ncolor(), param, QUDA_ASQTAD_DSLASH, QUDA_MAX_MULTI_SHIFT, QUDA_STAGGERED_DSLASH, QUDA_TIFR_PADDED_DIRAC_ORDER, X, and quda::LatticeField::X().
invert_quda_()
void invert_quda_ (void * h_x, void * h_b, QudaInvertParam * param)
Perform the solve, according to the parameters set in param. It is assumed that the gauge field has already been loaded via loadGaugeQuda().
Parameters
h_x Solution spinor field
h_b Source spinor field
param Contains all metadata regarding host and device storage and solver parameters
Definition at line 4736 of file interface_quda.cpp.
References fflush(), invertQuda(), param, QUDA_ASQTAD_DSLASH, and QUDA_STAGGERED_DSLASH.
kinetic_quda_()
void kinetic_quda_ (double * kin, void * momentum, QudaGaugeParam * param)
Evaluate the kinetic (momentum) contribution to classical Hamiltonian for Hybrid Monte Carlo.
Parameters
kin Kinetic energy
momentum The momentum field
param The parameters of the external fields and the computation settings
Returns
momentum action
Definition at line 4922 of file interface_quda.cpp.
References momActionQuda(), and param.
load_clover_quda_()
void load_clover_quda_ (void * h_clover, void * h_clovinv, QudaInvertParam * inv_param)
Load the clover term and/or the clover inverse from the host. Either h_clover or h_clovinv may be set to NULL.
Parameters
h_clover Base pointer to host clover field
h_cloverinv Base pointer to host clover inverse field
inv_param Contains all metadata regarding host and device storage
Definition at line 4725 of file interface_quda.cpp.
References inv_param, and loadCloverQuda().
load_gauge_quda_()
void load_gauge_quda_ (void * h_gauge, QudaGaugeParam * param)
Load the gauge field from the host.
Parameters
h_gauge Base pointer to host gauge field (regardless of dimensionality)
param Contains all metadata regarding host and device storage
Definition at line 4722 of file interface_quda.cpp.
References loadGaugeQuda(), and param.
mat_dag_mat_quda_()
void mat_dag_mat_quda_ (void * h_out, void * h_in, QudaInvertParam * inv_param)
Apply M^{}M, possibly even/odd preconditioned.
Parameters
h_out Result spinor field
h_in Input spinor field
param Contains all metadata regarding host and device storage
Definition at line 4734 of file interface_quda.cpp.
References inv_param, and MatDagMatQuda().
mat_quda_()
void mat_quda_ (void * h_out, void * h_in, QudaInvertParam * inv_param)
Apply the full Dslash matrix, possibly even/odd preconditioned.
Parameters
h_out Result spinor field
h_in Input spinor field
param Contains all metadata regarding host and device storage
Definition at line 4732 of file interface_quda.cpp.
References inv_param, and MatQuda().
new_quda_gauge_param_()
void new_quda_gauge_param_ (QudaGaugeParam * param)
Initializes the QudaGaugeParam with default entries.
Parameters
The QudaGaugeParam to be initialized
Definition at line 4777 of file interface_quda.cpp.
References newQudaGaugeParam(), and param.
new_quda_invert_param_()
void new_quda_invert_param_ (QudaInvertParam * param)
Initializes the QudaInvertParam with default entries.
Parameters
The QudaInvertParam to be initialized
Definition at line 4780 of file interface_quda.cpp.
References newQudaInvertParam(), and param.
plaq_quda_()
void plaq_quda_ (double plaq[3])
Parameters
Computes the total, spatial and temporal plaquette averages of the loaded gauge configuration.
Array for storing the averages (total, spatial, temporal)
Definition at line 4998 of file interface_quda.cpp.
References plaqQuda().
register_pinned_quda_()
void register_pinned_quda_ (void * ptr, size_t * bytes)
Pinned a pre-existing memory allocation.
Parameters
[in] ptr Pointer to buffer to be pinned
[in] size Size of allocation
Definition at line 4767 of file interface_quda.cpp.
References quda::blas::bytes, checkCudaError, and ptr.
remove_staggered_phase_quda_()
void remove_staggered_phase_quda_ ()
Remove the staggered phase factors to the resident gauge field.
Definition at line 4911 of file interface_quda.cpp.
References errorQuda, gaugePrecise, getVerbosity(), printfQuda, QUDA_VERBOSE, quda::qudaDeviceSynchronize(), and quda::GaugeField::removeStaggeredPhase().
set_kernel_pack_t_()
void set_kernel_pack_t_ (int * pack)
fTemporary function exposed for TIFR benchmarking
Exposed due to poor derived MPI datatype performance with GPUDirect RDMA
Definition at line 4953 of file interface_quda.cpp.
References deg_tm_dslash_cuda_gen::pack, and quda::setKernelPackT().
unregister_pinned_quda_()
void unregister_pinned_quda_ (void * ptr)
Pinned a pre-existing memory allocation.
Parameters
[in] ptr Pointer to buffer to be unpinned
Definition at line 4772 of file interface_quda.cpp.
References checkCudaError, and ptr.
update_gauge_field_quda_()
void update_gauge_field_quda_ (void * gauge, void * momentum, double * dt, bool * conj_mom, bool * exact, QudaGaugeParam * param)
Evolve the gauge field by step size dt, using the momentum field I.e., Evalulate U(t+dt) = e(dt pi) U(t)
Parameters
gauge The gauge field to be updated
momentum The momentum field
dt The integration step size step
conj_mom Whether to conjugate the momentum matrix
exact Whether to use an exact exponential or Taylor expand
param The parameters of the external fields and the computation settings
Definition at line 4784 of file interface_quda.cpp.
References param, and updateGaugeFieldQuda().