QUDA: tests/staggered_dslash_reference.h File Reference
staggered_dslash_reference.h File Reference
#include <blas_reference.h>
#include <quda_internal.h>
#include "color_spinor_field.h"
Functions
void setDims (int *)
void staggered_dslash (void *res, void **fatlink, void **longlink, void *spinorField, int oddBit, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
void staggered_dslash_mg4dir (cpuColorSpinorField *out, void **fatlink, void **longlink, void **ghost_fatlink, void **ghost_longlink, cpuColorSpinorField *in, int oddBit, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
void mat (void *out, void **fatlink, void **longlink, void *in, double kappa, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
void staggered_matpc (void *out, void **fatlink, void **longlink, void *in, double kappa, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
void matdagmat (void *out, void **fatlink, void **longlink, void *in, double mass, int dagger_bit, QudaPrecision sPrecision, QudaPrecision gPrecision, void *tmp, QudaParity parity)
void matdagmat_mg4dir (cpuColorSpinorField *out, void **fatlink, void **longlink, void **ghost_fatlink, void **ghost_longlink, cpuColorSpinorField *in, double mass, int dagger_bit, QudaPrecision sPrecision, QudaPrecision gPrecision, cpuColorSpinorField *tmp, QudaParity parity)
Variables
int Z [4]
int Vh
int V
Function Documentation
mat()
void mat (void * out, void ** fatlink, void ** longlink, void * in, double kappa, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 137 of file staggered_dslash_reference.cpp.
References fatlink, in, kappa, longlink, Mat(), mySpinorSiteSize, out, QUDA_DOUBLE_PRECISION, V, and quda::blas::xpay().
matdagmat()
void matdagmat (void * out, void ** fatlink, void ** longlink, void * in, double mass, int dagger_bit, QudaPrecision sPrecision, QudaPrecision gPrecision, void * tmp, QudaParity parity)
Definition at line 202 of file staggered_dslash_reference.cpp.
References fatlink, in, longlink, mass, Matdagmat(), out, parity, QUDA_DOUBLE_PRECISION, and tmp.
matdagmat_mg4dir()
void matdagmat_mg4dir (cpuColorSpinorField * out, void ** fatlink, void ** longlink, void ** ghost_fatlink, void ** ghost_longlink, cpuColorSpinorField * in, double mass, int dagger_bit, QudaPrecision sPrecision, QudaPrecision gPrecision, cpuColorSpinorField * tmp, QudaParity parity)
setDims()
void setDims (int *)
Definition at line 130 of file test_util.cpp.
staggered_dslash()
void staggered_dslash (void * res, void ** fatlink, void ** longlink, void * spinorField, int oddBit, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 100 of file staggered_dslash_reference.cpp.
References dslashReference(), fatlink, longlink, and QUDA_DOUBLE_PRECISION.
Referenced by staggeredDslashRef().
staggered_dslash_mg4dir()
void staggered_dslash_mg4dir (cpuColorSpinorField * out, void ** fatlink, void ** longlink, void ** ghost_fatlink, void ** ghost_longlink, cpuColorSpinorField * in, int oddBit, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
Referenced by staggeredDslashRef().
staggered_matpc()
void staggered_matpc (void * out, void ** fatlink, void ** longlink, void * in, double kappa, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 245 of file staggered_dslash_reference.cpp.
References fatlink, kappa, longlink, Ls, MatPC(), matpc_type, mySpinorSiteSize, QUDA_DOUBLE_PRECISION, Vh, and quda::blas::xpay().
Variable Documentation
V
int V
Definition at line 28 of file test_util.cpp.
Vh
int Vh
Definition at line 29 of file test_util.cpp.
Z
int Z[4]
Definition at line 27 of file test_util.cpp.