QUDA: lib/dslash_core/staggered_fused_exterior_dslash_core.h File Reference
staggered_fused_exterior_dslash_core.h File Reference
#include "read_gauge.h"
#include "io_spinor.h"
Macros
#define SHARED_FLOATS_PER_THREAD 6
#define spinorFloat double
#define spinorFloat2 double2
#define i00_re I0.x
#define i00_im I0.y
#define i01_re I1.x
#define i01_im I1.y
#define i02_re I2.x
#define i02_im I2.y
#define t00_re T0.x
#define t00_im T0.y
#define t01_re T1.x
#define t01_im T1.y
#define t02_re T2.x
#define t02_im T2.y
#define time_boundary param.t_boundary
#define fat00_re FAT0.x
#define fat00_im FAT0.y
#define fat01_re FAT1.x
#define fat01_im FAT1.y
#define fat02_re FAT2.x
#define fat02_im FAT2.y
#define fat10_re FAT3.x
#define fat10_im FAT3.y
#define fat11_re FAT4.x
#define fat11_im FAT4.y
#define fat12_re FAT5.x
#define fat12_im FAT5.y
#define fat20_re FAT6.x
#define fat20_im FAT6.y
#define fat21_re FAT7.x
#define fat21_im FAT7.y
#define fat22_re FAT8.x
#define fat22_im FAT8.y
#define long00_re LONG0.x
#define long00_im LONG0.y
#define long01_re LONG1.x
#define long01_im LONG1.y
#define long02_re LONG2.x
#define long02_im LONG2.y
#define long10_re LONG3.x
#define long10_im LONG3.y
#define long11_re LONG4.x
#define long11_im LONG4.y
#define long12_re LONG5.x
#define long12_im LONG5.y
#define long20_re LONG6.x
#define long20_im LONG6.y
#define long21_re LONG7.x
#define long21_im LONG7.y
#define long22_re LONG8.x
#define long22_im LONG8.y
#define fatT00_re (+fat00_re)
#define fatT00_im (-fat00_im)
#define fatT01_re (+fat10_re)
#define fatT01_im (-fat10_im)
#define fatT02_re (+fat20_re)
#define fatT02_im (-fat20_im)
#define fatT10_re (+fat01_re)
#define fatT10_im (-fat01_im)
#define fatT11_re (+fat11_re)
#define fatT11_im (-fat11_im)
#define fatT12_re (+fat21_re)
#define fatT12_im (-fat21_im)
#define fatT20_re (+fat02_re)
#define fatT20_im (-fat02_im)
#define fatT21_re (+fat12_re)
#define fatT21_im (-fat12_im)
#define fatT22_re (+fat22_re)
#define fatT22_im (-fat22_im)
#define longT00_re (+long00_re)
#define longT00_im (-long00_im)
#define longT01_re (+long10_re)
#define longT01_im (-long10_im)
#define longT02_re (+long20_re)
#define longT02_im (-long20_im)
#define longT10_re (+long01_re)
#define longT10_im (-long01_im)
#define longT11_re (+long11_re)
#define longT11_im (-long11_im)
#define longT12_re (+long21_re)
#define longT12_im (-long21_im)
#define longT20_re (+long02_re)
#define longT20_im (-long02_im)
#define longT21_re (+long12_re)
#define longT21_im (-long12_im)
#define longT22_re (+long22_re)
#define longT22_im (-long22_im)
#define VOLATILE volatile
#define MAT_MUL_V(VOUT, M, V)
#define ADJ_MAT_MUL_V(VOUT, M, V)
#define NFACE 1
Functions
if (idx >=param.threads) return
if (src_idx >=param.dc.Ls) return
READ_FAT_MATRIX (FATLINK0TEX, 0, ga_idx, fat_stride)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 1)
RECONSTRUCT_FAT_GAUGE_MATRIX (0, fat, ga_idx, fat_sign)
MAT_MUL_V (A, fat, i)
READ_FAT_MATRIX (FATLINK1TEX, dir, fat_idx, fat_stride)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 0)
RECONSTRUCT_FAT_GAUGE_MATRIX (1, fat, ga_idx, fat_sign)
ADJ_MAT_MUL_V (A, fat, i)
READ_FAT_MATRIX (FATLINK0TEX, 2, ga_idx, fat_stride)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 3)
RECONSTRUCT_FAT_GAUGE_MATRIX (2, fat, ga_idx, fat_sign)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 2)
RECONSTRUCT_FAT_GAUGE_MATRIX (3, fat, ga_idx, fat_sign)
READ_FAT_MATRIX (FATLINK0TEX, 4, ga_idx, fat_stride)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 5)
RECONSTRUCT_FAT_GAUGE_MATRIX (4, fat, ga_idx, fat_sign)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 4)
RECONSTRUCT_FAT_GAUGE_MATRIX (5, fat, ga_idx, fat_sign)
READ_FAT_MATRIX (FATLINK0TEX, 6, ga_idx, fat_stride)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 7)
RECONSTRUCT_FAT_GAUGE_MATRIX (6, fat, ga_idx, fat_sign)
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX, nbr_idx1, stride1, 6)
RECONSTRUCT_FAT_GAUGE_MATRIX (7, fat, ga_idx, fat_sign)
Variables
spinorFloat o00_re = o00_im = 0.0
spinorFloat o00_im = A0_im
spinorFloat o01_re = o01_im = 0.0
spinorFloat o01_im = A1_im
spinorFloat o02_re = o02_im = 0.0
spinorFloat o02_im = A2_im
const auto * X = param.dc.X
const int & fat_stride = param.gauge_stride
int idx = block_idx(param.swizzle)*blockDim.x + threadIdx.x
int src_idx = blockIdx.y*blockDim.y + threadIdx.y
const int X1X0 = X[1]*X[0]
const int X2X1X0 = X[2]*X1X0
int y [4] = {}
int full_idx =0
int half_idx = full_idx>>1
int nbr_idx1 = sp_idx_1st_nbr + src_idx*param.dc.Vh
int stride1 = param.sp_stride
int fat_idx = sp_idx_1st_nbr
Macro Definition Documentation
ADJ_MAT_MUL_V
#define ADJ_MAT_MUL_V (VOUT, M, V)
Definition at line 293 of file staggered_fused_exterior_dslash_core.h.
fat00_im
#define fat00_im FAT0.y
Definition at line 60 of file staggered_fused_exterior_dslash_core.h.
fat00_re
#define fat00_re FAT0.x
Definition at line 59 of file staggered_fused_exterior_dslash_core.h.
fat01_im
#define fat01_im FAT1.y
Definition at line 62 of file staggered_fused_exterior_dslash_core.h.
fat01_re
#define fat01_re FAT1.x
Definition at line 61 of file staggered_fused_exterior_dslash_core.h.
fat02_im
#define fat02_im FAT2.y
Definition at line 64 of file staggered_fused_exterior_dslash_core.h.
fat02_re
#define fat02_re FAT2.x
Definition at line 63 of file staggered_fused_exterior_dslash_core.h.
fat10_im
#define fat10_im FAT3.y
Definition at line 66 of file staggered_fused_exterior_dslash_core.h.
fat10_re
#define fat10_re FAT3.x
Definition at line 65 of file staggered_fused_exterior_dslash_core.h.
fat11_im
#define fat11_im FAT4.y
Definition at line 68 of file staggered_fused_exterior_dslash_core.h.
fat11_re
#define fat11_re FAT4.x
Definition at line 67 of file staggered_fused_exterior_dslash_core.h.
fat12_im
#define fat12_im FAT5.y
Definition at line 70 of file staggered_fused_exterior_dslash_core.h.
fat12_re
#define fat12_re FAT5.x
Definition at line 69 of file staggered_fused_exterior_dslash_core.h.
fat20_im
#define fat20_im FAT6.y
Definition at line 72 of file staggered_fused_exterior_dslash_core.h.
fat20_re
#define fat20_re FAT6.x
Definition at line 71 of file staggered_fused_exterior_dslash_core.h.
fat21_im
#define fat21_im FAT7.y
Definition at line 74 of file staggered_fused_exterior_dslash_core.h.
fat21_re
#define fat21_re FAT7.x
Definition at line 73 of file staggered_fused_exterior_dslash_core.h.
fat22_im
#define fat22_im FAT8.y
Definition at line 76 of file staggered_fused_exterior_dslash_core.h.
fat22_re
#define fat22_re FAT8.x
Definition at line 75 of file staggered_fused_exterior_dslash_core.h.
fatT00_im
#define fatT00_im (-fat00_im)
Definition at line 183 of file staggered_fused_exterior_dslash_core.h.
fatT00_re
#define fatT00_re (+fat00_re)
Definition at line 182 of file staggered_fused_exterior_dslash_core.h.
fatT01_im
#define fatT01_im (-fat10_im)
Definition at line 185 of file staggered_fused_exterior_dslash_core.h.
fatT01_re
#define fatT01_re (+fat10_re)
Definition at line 184 of file staggered_fused_exterior_dslash_core.h.
fatT02_im
#define fatT02_im (-fat20_im)
Definition at line 187 of file staggered_fused_exterior_dslash_core.h.
fatT02_re
#define fatT02_re (+fat20_re)
Definition at line 186 of file staggered_fused_exterior_dslash_core.h.
fatT10_im
#define fatT10_im (-fat01_im)
Definition at line 189 of file staggered_fused_exterior_dslash_core.h.
fatT10_re
#define fatT10_re (+fat01_re)
Definition at line 188 of file staggered_fused_exterior_dslash_core.h.
fatT11_im
#define fatT11_im (-fat11_im)
Definition at line 191 of file staggered_fused_exterior_dslash_core.h.
fatT11_re
#define fatT11_re (+fat11_re)
Definition at line 190 of file staggered_fused_exterior_dslash_core.h.
fatT12_im
#define fatT12_im (-fat21_im)
Definition at line 193 of file staggered_fused_exterior_dslash_core.h.
fatT12_re
#define fatT12_re (+fat21_re)
Definition at line 192 of file staggered_fused_exterior_dslash_core.h.
fatT20_im
#define fatT20_im (-fat02_im)
Definition at line 195 of file staggered_fused_exterior_dslash_core.h.
fatT20_re
#define fatT20_re (+fat02_re)
Definition at line 194 of file staggered_fused_exterior_dslash_core.h.
fatT21_im
#define fatT21_im (-fat12_im)
Definition at line 197 of file staggered_fused_exterior_dslash_core.h.
fatT21_re
#define fatT21_re (+fat12_re)
Definition at line 196 of file staggered_fused_exterior_dslash_core.h.
fatT22_im
#define fatT22_im (-fat22_im)
Definition at line 199 of file staggered_fused_exterior_dslash_core.h.
fatT22_re
#define fatT22_re (+fat22_re)
Definition at line 198 of file staggered_fused_exterior_dslash_core.h.
i00_im
#define i00_im I0.y
Definition at line 15 of file staggered_fused_exterior_dslash_core.h.
i00_re
#define i00_re I0.x
Definition at line 14 of file staggered_fused_exterior_dslash_core.h.
i01_im
#define i01_im I1.y
Definition at line 17 of file staggered_fused_exterior_dslash_core.h.
i01_re
#define i01_re I1.x
Definition at line 16 of file staggered_fused_exterior_dslash_core.h.
i02_im
#define i02_im I2.y
Definition at line 19 of file staggered_fused_exterior_dslash_core.h.
i02_re
#define i02_re I2.x
Definition at line 18 of file staggered_fused_exterior_dslash_core.h.
long00_im
#define long00_im LONG0.y
Definition at line 79 of file staggered_fused_exterior_dslash_core.h.
long00_re
#define long00_re LONG0.x
Definition at line 78 of file staggered_fused_exterior_dslash_core.h.
long01_im
#define long01_im LONG1.y
Definition at line 81 of file staggered_fused_exterior_dslash_core.h.
long01_re
#define long01_re LONG1.x
Definition at line 80 of file staggered_fused_exterior_dslash_core.h.
long02_im
#define long02_im LONG2.y
Definition at line 83 of file staggered_fused_exterior_dslash_core.h.
long02_re
#define long02_re LONG2.x
Definition at line 82 of file staggered_fused_exterior_dslash_core.h.
long10_im
#define long10_im LONG3.y
Definition at line 85 of file staggered_fused_exterior_dslash_core.h.
long10_re
#define long10_re LONG3.x
Definition at line 84 of file staggered_fused_exterior_dslash_core.h.
long11_im
#define long11_im LONG4.y
Definition at line 87 of file staggered_fused_exterior_dslash_core.h.
long11_re
#define long11_re LONG4.x
Definition at line 86 of file staggered_fused_exterior_dslash_core.h.
long12_im
#define long12_im LONG5.y
Definition at line 89 of file staggered_fused_exterior_dslash_core.h.
long12_re
#define long12_re LONG5.x
Definition at line 88 of file staggered_fused_exterior_dslash_core.h.
long20_im
#define long20_im LONG6.y
Definition at line 91 of file staggered_fused_exterior_dslash_core.h.
long20_re
#define long20_re LONG6.x
Definition at line 90 of file staggered_fused_exterior_dslash_core.h.
long21_im
#define long21_im LONG7.y
Definition at line 93 of file staggered_fused_exterior_dslash_core.h.
long21_re
#define long21_re LONG7.x
Definition at line 92 of file staggered_fused_exterior_dslash_core.h.
long22_im
#define long22_im LONG8.y
Definition at line 95 of file staggered_fused_exterior_dslash_core.h.
long22_re
#define long22_re LONG8.x
Definition at line 94 of file staggered_fused_exterior_dslash_core.h.
longT00_im
#define longT00_im (-long00_im)
Definition at line 202 of file staggered_fused_exterior_dslash_core.h.
longT00_re
#define longT00_re (+long00_re)
Definition at line 201 of file staggered_fused_exterior_dslash_core.h.
longT01_im
#define longT01_im (-long10_im)
Definition at line 204 of file staggered_fused_exterior_dslash_core.h.
longT01_re
#define longT01_re (+long10_re)
Definition at line 203 of file staggered_fused_exterior_dslash_core.h.
longT02_im
#define longT02_im (-long20_im)
Definition at line 206 of file staggered_fused_exterior_dslash_core.h.
longT02_re
#define longT02_re (+long20_re)
Definition at line 205 of file staggered_fused_exterior_dslash_core.h.
longT10_im
#define longT10_im (-long01_im)
Definition at line 208 of file staggered_fused_exterior_dslash_core.h.
longT10_re
#define longT10_re (+long01_re)
Definition at line 207 of file staggered_fused_exterior_dslash_core.h.
longT11_im
#define longT11_im (-long11_im)
Definition at line 210 of file staggered_fused_exterior_dslash_core.h.
longT11_re
#define longT11_re (+long11_re)
Definition at line 209 of file staggered_fused_exterior_dslash_core.h.
longT12_im
#define longT12_im (-long21_im)
Definition at line 212 of file staggered_fused_exterior_dslash_core.h.
longT12_re
#define longT12_re (+long21_re)
Definition at line 211 of file staggered_fused_exterior_dslash_core.h.
longT20_im
#define longT20_im (-long02_im)
Definition at line 214 of file staggered_fused_exterior_dslash_core.h.
longT20_re
#define longT20_re (+long02_re)
Definition at line 213 of file staggered_fused_exterior_dslash_core.h.
longT21_im
#define longT21_im (-long12_im)
Definition at line 216 of file staggered_fused_exterior_dslash_core.h.
longT21_re
#define longT21_re (+long12_re)
Definition at line 215 of file staggered_fused_exterior_dslash_core.h.
longT22_im
#define longT22_im (-long22_im)
Definition at line 218 of file staggered_fused_exterior_dslash_core.h.
longT22_re
#define longT22_re (+long22_re)
Definition at line 217 of file staggered_fused_exterior_dslash_core.h.
MAT_MUL_V
#define MAT_MUL_V (VOUT, M, V)
Definition at line 255 of file staggered_fused_exterior_dslash_core.h.
NFACE
#define NFACE 1
Definition at line 335 of file staggered_fused_exterior_dslash_core.h.
SHARED_FLOATS_PER_THREAD
#define SHARED_FLOATS_PER_THREAD 6
Definition at line 3 of file staggered_fused_exterior_dslash_core.h.
spinorFloat
#define spinorFloat double
Definition at line 8 of file staggered_fused_exterior_dslash_core.h.
spinorFloat2
#define spinorFloat2 double2
Definition at line 9 of file staggered_fused_exterior_dslash_core.h.
t00_im
#define t00_im T0.y
Definition at line 22 of file staggered_fused_exterior_dslash_core.h.
t00_re
#define t00_re T0.x
Definition at line 21 of file staggered_fused_exterior_dslash_core.h.
t01_im
#define t01_im T1.y
Definition at line 24 of file staggered_fused_exterior_dslash_core.h.
t01_re
#define t01_re T1.x
Definition at line 23 of file staggered_fused_exterior_dslash_core.h.
t02_im
#define t02_im T2.y
Definition at line 26 of file staggered_fused_exterior_dslash_core.h.
t02_re
#define t02_re T2.x
Definition at line 25 of file staggered_fused_exterior_dslash_core.h.
time_boundary
#define time_boundary param.t_boundary
Definition at line 28 of file staggered_fused_exterior_dslash_core.h.
VOLATILE
#define VOLATILE volatile
Definition at line 223 of file staggered_fused_exterior_dslash_core.h.
Function Documentation
ADJ_MAT_MUL_V()
ADJ_MAT_MUL_V (A , fat , i)
if() [1/2]
if (idx >=param. threads)
if() [2/2]
if (src_idx >=param.dc. Ls)
MAT_MUL_V()
MAT_MUL_V (A , fat , i)
READ_1ST_NBR_SPINOR_GHOST() [1/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 1)
READ_1ST_NBR_SPINOR_GHOST() [2/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 0)
READ_1ST_NBR_SPINOR_GHOST() [3/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 3)
READ_1ST_NBR_SPINOR_GHOST() [4/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 2)
READ_1ST_NBR_SPINOR_GHOST() [5/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 5)
READ_1ST_NBR_SPINOR_GHOST() [6/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 4)
READ_1ST_NBR_SPINOR_GHOST() [7/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 7)
READ_1ST_NBR_SPINOR_GHOST() [8/8]
READ_1ST_NBR_SPINOR_GHOST (GHOSTSPINORTEX , nbr_idx1 , stride1 , 6)
READ_FAT_MATRIX() [1/5]
READ_FAT_MATRIX (FATLINK0TEX , 0 , ga_idx , fat_stride)
READ_FAT_MATRIX() [2/5]
READ_FAT_MATRIX (FATLINK1TEX , dir , fat_idx , fat_stride)
READ_FAT_MATRIX() [3/5]
READ_FAT_MATRIX (FATLINK0TEX , 2 , ga_idx , fat_stride)
READ_FAT_MATRIX() [4/5]
READ_FAT_MATRIX (FATLINK0TEX , 4 , ga_idx , fat_stride)
READ_FAT_MATRIX() [5/5]
READ_FAT_MATRIX (FATLINK0TEX , 6 , ga_idx , fat_stride)
RECONSTRUCT_FAT_GAUGE_MATRIX() [1/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (0 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [2/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (1 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [3/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (2 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [4/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (3 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [5/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (4 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [6/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (5 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [7/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (6 , fat , ga_idx , fat_sign)
RECONSTRUCT_FAT_GAUGE_MATRIX() [8/8]
RECONSTRUCT_FAT_GAUGE_MATRIX (7 , fat , ga_idx , fat_sign)
Variable Documentation
fat_idx
int fat_idx = sp_idx_1st_nbr
Definition at line 513 of file staggered_fused_exterior_dslash_core.h.
fat_stride
const int& fat_stride = param.gauge_stride
Definition at line 339 of file staggered_fused_exterior_dslash_core.h.
full_idx
int full_idx =0
Definition at line 369 of file staggered_fused_exterior_dslash_core.h.
half_idx
int half_idx = full_idx>>1
Definition at line 387 of file staggered_fused_exterior_dslash_core.h.
Referenced by gf_neighborIndexFullLattice(), neighborIndexFullLattice(), neighborIndexFullLattice_mg(), and x4_from_full_index().
idx
int idx = block_idx(param.swizzle)*blockDim.x + threadIdx.x
Definition at line 355 of file staggered_fused_exterior_dslash_core.h.
Referenced by LoadStore< Real >::addData(), quda::appendMatrixToArray(), completeForceSite(), quda::completeKSForceCore(), quda::completeKSForceCPU(), quda::completeKSForceKernel(), quda::ColorSpinorField::Component(), quda::cudaColorSpinorField::Component(), compute(), quda::computeKSLongLinkForceCPU(), quda::computeKSLongLinkForceKernel(), computeLongLinkSite(), computeOneLinkSite(), quda::computeOvrImpSTOUTStep(), quda::computeStapleRectangle(), coordsFromFaceIndex(), coordsFromFaceIndexStaggered(), coordsFromIndex(), coordsFromIndex3D(), createSiteLinkCPU(), gauge_force_test(), get_su3_matrix(), LoadStore< Real >::getData(), LoadStore< Real >::half_idx_conversion_ex2normal(), LoadStore< Real >::half_idx_conversion_normal2ex(), if(), index(), indexFromFaceIndex(), indexFromFaceIndexExtended(), indexFromFaceIndexExtendedStaggered(), indexFromFaceIndexStaggered(), quda::TimeProfile::Last(), quda::linkIndex(), quda::linkIndexM1(), quda::linkIndexP1(), quda::linkIndexShift(), quda::linkNormalIndexP1(), llfat_test(), quda::loadLinkVariableFromArray(), quda::loadMatrixFromArray(), quda::loadMomentumFromArray(), quda::neighborIndex(), new_load_half(), new_save_half(), old_load_half(), old_save_half(), quda::ColorSpinor< Float, Nc, Ns >::operator()(), quda::clover::Accessor< Float, nColor, nSpin, QUDA_FLOAT4_CLOVER_ORDER >::operator()(), quda::HMatrix< T, N >::operator()(), quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::operator()(), quda::ColorSpinor< Float, Nc, 4 >::operator()(), quda::ColorSpinor< Float, Nc, 2 >::operator()(), Texture< InterType, StoreType, -1 >::operator[](), quda::gauge::Reconstruct< 13, Float >::Pack(), quda::gauge::Reconstruct< 9, Float >::Pack(), process_command_line_option(), quda::ProjectSU3kernel(), quda::Deflation::reduce(), quda::reduce(), quda::reduce2d(), quda::TimeProfile::Reset_(), quda::shiftColorSpinorFieldExternalKernel(), quda::shiftColorSpinorFieldKernel(), quda::TimeProfile::Start_(), quda::TimeProfile::StartGlobal(), quda::TimeProfile::Stop_(), quda::TimeProfile::StopGlobal(), quda::gauge::timeBoundary(), quda::gauge::Reconstruct< 12, Float >::Unpack(), quda::gauge::Reconstruct< 8, Float >::Unpack(), quda::gauge::Reconstruct< 9, Float >::Unpack(), quda::vector_load(), quda::vector_store(), quda::writeLinkVariableToArray(), quda::writeMatrixToArray(), and quda::writeMomentumToArray().
nbr_idx1
int nbr_idx1 = sp_idx_1st_nbr + src_idx*param.dc.Vh
Definition at line 429 of file staggered_fused_exterior_dslash_core.h.
o00_im
o00_im = A0_im
Definition at line 246 of file staggered_fused_exterior_dslash_core.h.
o00_re
o00_re = o00_im = 0.0
Definition at line 245 of file staggered_fused_exterior_dslash_core.h.
o01_im
o01_im = A1_im
Definition at line 248 of file staggered_fused_exterior_dslash_core.h.
o01_re
o01_re = o01_im = 0.0
Definition at line 247 of file staggered_fused_exterior_dslash_core.h.
o02_im
o02_im = A2_im
Definition at line 250 of file staggered_fused_exterior_dslash_core.h.
o02_re
o02_re = o02_im = 0.0
Definition at line 249 of file staggered_fused_exterior_dslash_core.h.
src_idx
int src_idx = blockIdx.y*blockDim.y + threadIdx.y
Definition at line 358 of file staggered_fused_exterior_dslash_core.h.
stride1
int stride1 = param.sp_stride
Definition at line 430 of file staggered_fused_exterior_dslash_core.h.
X
const auto* X = param.dc.X
Definition at line 338 of file staggered_fused_exterior_dslash_core.h.
X1X0
const int X1X0 = X[1]*X[0]
Definition at line 361 of file staggered_fused_exterior_dslash_core.h.
X2X1X0
const int X2X1X0 = X[2]*X1X0
Definition at line 362 of file staggered_fused_exterior_dslash_core.h.
y
int y[4] = {}
Definition at line 367 of file staggered_fused_exterior_dslash_core.h.