QUDA: doubledouble3 Struct Reference
doubledouble3 Struct Reference
#include <dbldbl.h>
Public Member Functions
__device__ __host__ doubledouble3 ()
__device__ __host__ doubledouble3 (const doubledouble3 &a)
__device__ __host__ doubledouble3 (const double3 &a)
__device__ __host__ doubledouble3 (const doubledouble &x, const doubledouble &y, const doubledouble &z)
__device__ doubledouble3 & operator+= (const doubledouble3 &a)
__device__ __host__ void print () const
Public Attributes
doubledouble x
doubledouble y
doubledouble z
Detailed Description
Definition at line 356 of file dbldbl.h.
Constructor & Destructor Documentation
doubledouble3() [1/4]
__device__ __host__ doubledouble3::doubledouble3 () inline
Definition at line 361 of file dbldbl.h.
doubledouble3() [2/4]
__device__ __host__ doubledouble3::doubledouble3 (const doubledouble3 & a) inline
Definition at line 362 of file dbldbl.h.
doubledouble3() [3/4]
__device__ __host__ doubledouble3::doubledouble3 (const double3 & a) inline
Definition at line 363 of file dbldbl.h.
doubledouble3() [4/4]
__device__ __host__ doubledouble3::doubledouble3 (const doubledouble & x, const doubledouble & y, const doubledouble & z) inline
Definition at line 364 of file dbldbl.h.
Member Function Documentation
operator+=()
__device__ doubledouble3& doubledouble3::operator+= (const doubledouble3 & a) inline
Definition at line 366 of file dbldbl.h.
References a, x, y, and z.
print()
__device__ __host__ void doubledouble3::print () const inline
Definition at line 373 of file dbldbl.h.
References doubledouble::head(), printf(), doubledouble::tail(), x, y, and z.
Member Data Documentation
x
doubledouble doubledouble3::x
Definition at line 357 of file dbldbl.h.
Referenced by operator+=(), and print().
y
doubledouble doubledouble3::y
Definition at line 358 of file dbldbl.h.
Referenced by operator+=(), and print().
z
doubledouble doubledouble3::z
Definition at line 359 of file dbldbl.h.
Referenced by operator+=(), and print().
The documentation for this struct was generated from the following file:
include/dbldbl.h