QUDA: anonymous_namespace{dslash_policy.cuh}::DslashFusedGDRRecv Struct Reference
anonymous_namespace{dslash_policy.cuh}::DslashFusedGDRRecv Struct Reference
Public Member Functions
void operator() (DslashCuda &dslash, cudaColorSpinorField *in, const int volume, const int *faceVolumeCB, TimeProfile &profile)
Public Member Functions inherited from anonymous_namespace{dslash_policy.cuh}::DslashPolicyImp
virtual ~DslashPolicyImp ()
Detailed Description
Dslash parallelization with host staging for send and GDR for receive, with fused halo update kernel
Definition at line 949 of file dslash_policy.cuh.
Member Function Documentation
operator()()
void anonymous_namespace{dslash_policy.cuh}::DslashFusedGDRRecv::operator() (DslashCuda & dslash, cudaColorSpinorField * in, const int volume, const int * faceVolumeCB, TimeProfile & profile) inline virtual
Implements anonymous_namespace{dslash_policy.cuh}::DslashPolicyImp.
Definition at line 951 of file dslash_policy.cuh.
References dslash::aux_worker, comm_peer2peer_enabled(), DslashCommsPattern::commDimTotal, anonymous_namespace{dslash_policy.cuh}::commsComplete(), DslashCommsPattern::commsCompleted, anonymous_namespace{dslash_policy.cuh}::completeDslash(), DslashCommsPattern::completeSum, quda::Device, dslash_comms, dslash_exterior_compute, dslash_interior_compute, dslash::dslashStart, DslashCommsPattern::gatherCompleted, dslash::gatherEnd, quda::getKernelPackT(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, INTERIOR_KERNEL, anonymous_namespace{dslash_policy.cuh}::issueGather(), anonymous_namespace{dslash_policy.cuh}::issuePack(), anonymous_namespace{dslash_policy.cuh}::issueRecv(), quda::Nstream, DslashCommsPattern::previousDir, PROFILE, quda::QUDA_PROFILE_COMMS_START, quda::QUDA_PROFILE_DSLASH_KERNEL, quda::QUDA_PROFILE_EVENT_QUERY, quda::QUDA_PROFILE_EVENT_RECORD, quda::QUDA_PROFILE_TOTAL, quda::qudaEventQuery(), quda::qudaEventRecord(), quda::Remote, setFusedParam(), and streams.
The documentation for this struct was generated from the following file:
lib/dslash_policy.cuh