QUDA: quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > Struct Template Reference
quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > Struct Template Reference
#include <gauge_field_order.h>
Public Types
typedef mapper< Float >::type RegType
typedef VectorType< Float, N >::type Vector
typedef AllocType< huge_alloc >::type AllocInt
Public Member Functions
FloatNOrder (const GaugeField &u, Float *gauge_=0, Float **ghost_=0, bool override=false)
FloatNOrder (const FloatNOrder &order)
virtual ~FloatNOrder ()
__device__ __host__ void load (RegType v[length], int x, int dir, int parity) const
__device__ __host__ void save (const RegType v[length], int x, int dir, int parity)
__device__ __host__ gauge_wrapper< Float, FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > > operator() (int dim, int x_cb, int parity)
This accessor routine returns a gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const gauge_wrapper< Float, FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > > operator() (int dim, int x_cb, int parity) const
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ void loadGhost (RegType v[length], int x, int dir, int parity) const
__device__ __host__ void saveGhost (const RegType v[length], int x, int dir, int parity)
__device__ __host__ gauge_ghost_wrapper< Float, FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > > Ghost (int dim, int ghost_idx, int parity)
This accessor routine returns a gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const gauge_ghost_wrapper< Float, FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > > Ghost (int dim, int ghost_idx, int parity) const
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ void loadGhostEx (RegType v[length], int buff_idx, int extended_idx, int dir, int dim, int g, int parity, const int R[]) const
__device__ __host__ void saveGhostEx (const RegType v[length], int buff_idx, int extended_idx, int dir, int dim, int g, int parity, const int R[])
void save ()
Backup the field to the host when tuning.
void load ()
Restore the field from the host after tuning.
size_t Bytes () const
Public Attributes
Reconstruct< reconLenParam, Float > reconstruct
Float * gauge
const AllocInt offset
Float * ghost [4]
QudaGhostExchange ghostExchange
int coords [QUDA_MAX_DIM]
int_fastdiv X [QUDA_MAX_DIM]
int R [QUDA_MAX_DIM]
const int volumeCB
int faceVolumeCB [4]
const int stride
const int geometry
const AllocInt phaseOffset
void * backup_h
size_t bytes
host memory for backing up the field when tuning
Static Public Attributes
static const int reconLen = (reconLenParam == 11) ? 10 : reconLenParam
static const int hasPhase = (reconLen == 9 || reconLen == 13) ? 1 : 0
Detailed Description
template<typename Float, int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc>
struct quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >
Definition at line 949 of file gauge_field_order.h.
Member Typedef Documentation
AllocInt
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> typedef AllocType<huge_alloc>::type quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::AllocInt
Definition at line 952 of file gauge_field_order.h.
RegType
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> typedef mapper<Float>::type quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::RegType
Definition at line 950 of file gauge_field_order.h.
Vector
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> typedef VectorType<Float,N>::type quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::Vector
Definition at line 951 of file gauge_field_order.h.
Constructor & Destructor Documentation
FloatNOrder() [1/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder (const GaugeField & u, Float * gauge_ = 0, Float ** ghost_ = 0, bool override = false) inline
Definition at line 976 of file gauge_field_order.h.
References errorQuda, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::GaugeField::Gauge_p(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::geometry, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::LatticeField::Location(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, QUDA_CUDA_FIELD_LOCATION, QUDA_STAGGERED_PHASE_NO, quda::LatticeField::R(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, quda::LatticeField::SurfaceCB(), tex, quda::LatticeField::X(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X.
FloatNOrder() [2/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder (const FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc > & order) inline
Definition at line 1005 of file gauge_field_order.h.
References quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X.
~FloatNOrder()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> virtual quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::~FloatNOrder () inline virtual
Definition at line 1021 of file gauge_field_order.h.
Member Function Documentation
Bytes()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> size_t quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::Bytes () const inline
Definition at line 1259 of file gauge_field_order.h.
References quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen.
Ghost() [1/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ gauge_ghost_wrapper<Float,FloatNOrder<Float,length,N,reconLenParam,stag_phase,huge_alloc> > quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::Ghost (int dim, int ghost_idx, int parity) inline
This accessor routine returns a gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] ghost_idx Ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 1173 of file gauge_field_order.h.
References dim, and parity.
Ghost() [2/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ const gauge_ghost_wrapper<Float,FloatNOrder<Float,length,N,reconLenParam,stag_phase,huge_alloc> > quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::Ghost (int dim, int ghost_idx, int parity) const inline
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] ghost_idx Ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 1188 of file gauge_field_order.h.
References dim, and parity.
load() [1/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load (RegType v[length], int x, int dir, int parity) const inline
Definition at line 1023 of file gauge_field_order.h.
References quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::coords, quda::copy(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::gauge, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::offset, parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::phaseOffset, QUDA_STAGGERED_PHASE_MILC, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, deg_tm_dslash_cuda_gen::sign(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::stride, tex, tmp, quda::gauge::Reconstruct< N, Float >::Unpack(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X, and x.
load() [2/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load () inline
Restore the field from the host after tuning.
Definition at line 1252 of file gauge_field_order.h.
References quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::backup_h, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::bytes, checkCudaError, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::gauge, and host_free.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost().
loadGhost()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost (RegType v[length], int x, int dir, int parity) const inline
Definition at line 1114 of file gauge_field_order.h.
References quda::copy(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, tmp, quda::gauge::Reconstruct< N, Float >::Unpack(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::volumeCB, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X, and x.
loadGhostEx()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx (RegType v[length], int buff_idx, int extended_idx, int dir, int dim, int g, int parity, const int R[]) const inline
Definition at line 1193 of file gauge_field_order.h.
References quda::copy(), dim, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::geometry, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, tmp, quda::gauge::Reconstruct< N, Float >::Unpack(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X.
operator()() [1/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ gauge_wrapper<Float,FloatNOrder<Float,length,N,reconLenParam,stag_phase,huge_alloc> > quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::operator() (int dim, int x_cb, int parity) inline
This accessor routine returns a gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 1094 of file gauge_field_order.h.
References dim, and parity.
operator()() [2/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ const gauge_wrapper<Float,FloatNOrder<Float,length,N,reconLenParam,stag_phase,huge_alloc> > quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::operator() (int dim, int x_cb, int parity) const inline
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 1109 of file gauge_field_order.h.
References dim, and parity.
save() [1/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save (const RegType v[length], int x, int dir, int parity) inline
Definition at line 1062 of file gauge_field_order.h.
References quda::copy(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::gauge, quda::gauge::Reconstruct< N, Float >::getPhase(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::offset, quda::gauge::Reconstruct< N, Float >::Pack(), parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::phaseOffset, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::stride, tmp, quda::vector_store(), and x.
save() [2/2]
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save () inline
Backup the field to the host when tuning.
Definition at line 1242 of file gauge_field_order.h.
References quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::backup_h, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::bytes, checkCudaError, errorQuda, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::gauge, and safe_malloc.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost().
saveGhost()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost (const RegType v[length], int x, int dir, int parity) inline
Definition at line 1137 of file gauge_field_order.h.
References quda::copy(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::gauge::Reconstruct< N, Float >::getPhase(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::Reconstruct< N, Float >::Pack(), parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save(), tmp, quda::vector_store(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::volumeCB, and x.
saveGhostEx()
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> __device__ __host__ void quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx (const RegType v[length], int buff_idx, int extended_idx, int dir, int dim, int g, int parity, const int R[]) inline
Definition at line 1215 of file gauge_field_order.h.
References quda::copy(), dim, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::geometry, quda::gauge::Reconstruct< N, Float >::getPhase(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase, fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::Reconstruct< N, Float >::Pack(), parity, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen, quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct, tmp, and quda::vector_store().
Member Data Documentation
backup_h
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> void* quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::backup_h
Definition at line 973 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
bytes
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> size_t quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::bytes
host memory for backing up the field when tuning
Definition at line 974 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
coords
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::coords[QUDA_MAX_DIM]
Definition at line 965 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load().
faceVolumeCB
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::faceVolumeCB[4]
Definition at line 969 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
gauge
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> Float* quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::gauge
Definition at line 956 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
geometry
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::geometry
Definition at line 971 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
ghost
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> Float* quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghost[4]
Definition at line 963 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
ghostExchange
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> QudaGhostExchange quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::ghostExchange
Definition at line 964 of file gauge_field_order.h.
hasPhase
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::hasPhase = (reconLen == 9 || reconLen == 13) ? 1 : 0 static
Definition at line 955 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
offset
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const AllocInt quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::offset
Definition at line 957 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
phaseOffset
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const AllocInt quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::phaseOffset
Definition at line 972 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
R
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::R[QUDA_MAX_DIM]
Definition at line 967 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
reconLen
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconLen = (reconLenParam == 11) ? 10 : reconLenParam static
Definition at line 954 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::Bytes(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
reconstruct
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> Reconstruct<reconLenParam,Float> quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::reconstruct
Definition at line 953 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhostEx().
stride
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::stride
Definition at line 970 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::save().
volumeCB
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> const int quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::volumeCB
Definition at line 968 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::saveGhost().
X
template<typename Float , int length, int N, int reconLenParam, QudaStaggeredPhase stag_phase = QUDA_STAGGERED_PHASE_NO, bool huge_alloc = default_huge_alloc> int_fastdiv quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::X[QUDA_MAX_DIM]
Definition at line 966 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::FloatNOrder(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc >::loadGhostEx().
The documentation for this struct was generated from the following file:
include/gauge_field_order.h