QUDA: quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost > Struct Template Reference
quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
GhostAccessor (const GaugeField &U, void *gauge_, void **ghost_=0)
GhostAccessor (const GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost > &a)
__device__ __host__ complex< Float > & operator() (int d, int parity, int x_cb, int row, int col) const
Public Attributes
complex< Float > * ghost [8]
const int volumeCB
int ghostVolumeCB [8]
Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER > accessor
Detailed Description
template<typename Float, int nColor, bool native_ghost>
struct quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >
Definition at line 340 of file gauge_field_order.h.
Constructor & Destructor Documentation
GhostAccessor() [1/2]
template<typename Float , int nColor, bool native_ghost> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::GhostAccessor (const GaugeField & U, void * gauge_, void ** ghost_ = 0) inline
Definition at line 345 of file gauge_field_order.h.
References d, quda::GaugeField::Geometry(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, and quda::LatticeField::SurfaceCB().
GhostAccessor() [2/2]
template<typename Float , int nColor, bool native_ghost> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::GhostAccessor (const GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost > & a) inline
Definition at line 356 of file gauge_field_order.h.
References a, and d.
Member Function Documentation
operator()()
template<typename Float , int nColor, bool native_ghost> __device__ __host__ complex<Float>& quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::operator() (int d, int parity, int x_cb, int row, int col) const inline
Definition at line 364 of file gauge_field_order.h.
References d, nColor, and parity.
Member Data Documentation
accessor
template<typename Float , int nColor, bool native_ghost> Accessor<Float,nColor,QUDA_FLOAT2_GAUGE_ORDER> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::accessor
Definition at line 344 of file gauge_field_order.h.
ghost
template<typename Float , int nColor, bool native_ghost> complex<Float>* quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::ghost[8]
Definition at line 341 of file gauge_field_order.h.
ghostVolumeCB
template<typename Float , int nColor, bool native_ghost> int quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::ghostVolumeCB[8]
Definition at line 343 of file gauge_field_order.h.
volumeCB
template<typename Float , int nColor, bool native_ghost> const int quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost >::volumeCB
Definition at line 342 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h