QUDA: quda::gauge::Reconstruct< 9, Float > Struct Template Reference
quda::gauge::Reconstruct< 9, Float > Struct Template Reference
#include <gauge_field_order.h>
Public Types
typedef mapper< Float >::type RegType
typedef complex< RegType > Complex
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< 9, Float > &recon)
__device__ __host__ RegType getPhase (const RegType in[18]) const
__device__ __host__ void Pack (RegType out[8], const RegType in[18], int idx) const
template<typename I >
__device__ __host__ void Unpack (RegType out[18], const RegType in[8], int idx, int dir, const RegType phase, const I *X, const int *R) const
Public Attributes
const Reconstruct< 8, Float > reconstruct_8
const RegType scale
Detailed Description
template<typename Float>
struct quda::gauge::Reconstruct< 9, Float >
Definition at line 881 of file gauge_field_order.h.
Member Typedef Documentation
Complex
template<typename Float > typedef complex<RegType> quda::gauge::Reconstruct< 9, Float >::Complex
Definition at line 883 of file gauge_field_order.h.
RegType
template<typename Float > typedef mapper<Float>::type quda::gauge::Reconstruct< 9, Float >::RegType
Definition at line 882 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<typename Float > quda::gauge::Reconstruct< 9, Float >::Reconstruct (const GaugeField & u) inline
Definition at line 887 of file gauge_field_order.h.
Reconstruct() [2/2]
template<typename Float > quda::gauge::Reconstruct< 9, Float >::Reconstruct (const Reconstruct< 9, Float > & recon) inline
Definition at line 889 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<typename Float > __device__ __host__ RegType quda::gauge::Reconstruct< 9, Float >::getPhase (const RegType in[18]) const inline
Definition at line 892 of file gauge_field_order.h.
References a, quda::arg(), quda::conj(), quda::getDeterminant(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, and in.
Pack()
template<typename Float > __device__ __host__ void quda::gauge::Reconstruct< 9, Float >::Pack (RegType out[8], const RegType in[18], int idx) const inline
Definition at line 910 of file gauge_field_order.h.
References quda::gauge::Reconstruct< N, Float >::getPhase(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, in, out, quda::gauge::Reconstruct< 8, Float >::Pack(), and z.
Unpack()
template<typename Float > template<typename I > __device__ __host__ void quda::gauge::Reconstruct< 9, Float >::Unpack (RegType out[18], const RegType in[8], int idx, int dir, const RegType phase, const I * X, const int * R) const inline
Definition at line 922 of file gauge_field_order.h.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, idx, in, out, R, quda::gauge::Reconstruct< 8, Float >::Unpack(), X, and z.
Member Data Documentation
reconstruct_8
template<typename Float > const Reconstruct<8,Float> quda::gauge::Reconstruct< 9, Float >::reconstruct_8
Definition at line 884 of file gauge_field_order.h.
scale
template<typename Float > const RegType quda::gauge::Reconstruct< 9, Float >::scale
Definition at line 885 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h