QUDA: quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost > Struct Template Reference
quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
GhostAccessor (const GaugeField &U, void *gauge_=0, void **ghost_=0)
GhostAccessor (const GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost > &a)
__device__ __host__ complex< Float > & operator() (int d, int parity, int x, int row, int col) const
Public Attributes
complex< Float > * ghost [8]
int ghostOffset [8]
Detailed Description
template<typename Float, int nColor, bool native_ghost>
struct quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >
Definition at line 260 of file gauge_field_order.h.
Constructor & Destructor Documentation
GhostAccessor() [1/2]
template<typename Float , int nColor, bool native_ghost> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >::GhostAccessor (const GaugeField & U, void * gauge_ = 0, void ** ghost_ = 0) inline
Definition at line 263 of file gauge_field_order.h.
References d, quda::GaugeField::Geometry(), quda::GaugeField::Ghost(), quda::GaugeField::Ncolor(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, and quda::LatticeField::SurfaceCB().
GhostAccessor() [2/2]
template<typename Float , int nColor, bool native_ghost> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >::GhostAccessor (const GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost > & a) inline
Definition at line 275 of file gauge_field_order.h.
References a, and d.
Member Function Documentation
operator()()
template<typename Float , int nColor, bool native_ghost> __device__ __host__ complex<Float>& quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >::operator() (int d, int parity, int x, int row, int col) const inline
Definition at line 281 of file gauge_field_order.h.
References d, nColor, parity, and x.
Member Data Documentation
ghost
template<typename Float , int nColor, bool native_ghost> complex<Float>* quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >::ghost[8]
Definition at line 261 of file gauge_field_order.h.
ghostOffset
template<typename Float , int nColor, bool native_ghost> int quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost >::ghostOffset[8]
Definition at line 262 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h