QUDA: quda::gauge::Reconstruct< 8, Float > Struct Template Reference
quda::gauge::Reconstruct< 8, Float > Struct Template Reference
#include <gauge_field_order.h>
Public Types
typedef mapper< Float >::type RegType
typedef complex< RegType > Complex
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< 8, Float > &recon)
__device__ __host__ void Pack (RegType out[8], const RegType in[18], int idx) const
template<typename I >
__device__ __host__ void Unpack (RegType out[18], const RegType in[8], int idx, int dir, const RegType phase, const I *X, const int *R, const RegType scale=1.0) const
__device__ __host__ RegType getPhase (const RegType in[18])
Public Attributes
const RegType anisotropy
const QudaTboundary tBoundary
bool isFirstTimeSlice
bool isLastTimeSlice
QudaGhostExchange ghostExchange
Detailed Description
template<typename Float>
struct quda::gauge::Reconstruct< 8, Float >
Definition at line 809 of file gauge_field_order.h.
Member Typedef Documentation
Complex
template<typename Float > typedef complex<RegType> quda::gauge::Reconstruct< 8, Float >::Complex
Definition at line 811 of file gauge_field_order.h.
RegType
template<typename Float > typedef mapper<Float>::type quda::gauge::Reconstruct< 8, Float >::RegType
Definition at line 810 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<typename Float > quda::gauge::Reconstruct< 8, Float >::Reconstruct (const GaugeField & u) inline
Definition at line 818 of file gauge_field_order.h.
Reconstruct() [2/2]
template<typename Float > quda::gauge::Reconstruct< 8, Float >::Reconstruct (const Reconstruct< 8, Float > & recon) inline
Definition at line 823 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<typename Float > __device__ __host__ RegType quda::gauge::Reconstruct< 8, Float >::getPhase (const RegType in[18]) inline
Definition at line 876 of file gauge_field_order.h.
Pack()
template<typename Float > __device__ __host__ void quda::gauge::Reconstruct< 8, Float >::Pack (RegType out[8], const RegType in[18], int idx) const inline
Definition at line 827 of file gauge_field_order.h.
References fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, and out.
Referenced by quda::gauge::Reconstruct< 9, Float >::Pack().
Unpack()
template<typename Float > template<typename I > __device__ __host__ void quda::gauge::Reconstruct< 8, Float >::Unpack (RegType out[18], const RegType in[8], int idx, int dir, const RegType phase, const I * X, const int * R, const RegType scale = 1.0) const inline
Definition at line 835 of file gauge_field_order.h.
References anisotropy, quda::conj(), idx, in, quda::norm(), out, R, quda::sqrt(), and X.
Referenced by quda::gauge::Reconstruct< 9, Float >::Unpack().
Member Data Documentation
anisotropy
template<typename Float > const RegType quda::gauge::Reconstruct< 8, Float >::anisotropy
Definition at line 812 of file gauge_field_order.h.
ghostExchange
template<typename Float > QudaGhostExchange quda::gauge::Reconstruct< 8, Float >::ghostExchange
Definition at line 816 of file gauge_field_order.h.
isFirstTimeSlice
template<typename Float > bool quda::gauge::Reconstruct< 8, Float >::isFirstTimeSlice
Definition at line 814 of file gauge_field_order.h.
isLastTimeSlice
template<typename Float > bool quda::gauge::Reconstruct< 8, Float >::isLastTimeSlice
Definition at line 815 of file gauge_field_order.h.
tBoundary
template<typename Float > const QudaTboundary quda::gauge::Reconstruct< 8, Float >::tBoundary
Definition at line 813 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h