QUDA: quda::gauge::TIFRPaddedOrder< Float, length > Struct Template Reference
quda::gauge::TIFRPaddedOrder< Float, length > Struct Template Reference
#include <gauge_field_order.h>
Public Types
typedef mapper< Float >::type RegType
Public Types inherited from quda::gauge::LegacyOrder< Float, length >
typedef mapper< Float >::type RegType
Public Member Functions
TIFRPaddedOrder (const GaugeField &u, Float *gauge_=0, Float **ghost_=0)
TIFRPaddedOrder (const TIFRPaddedOrder &order)
virtual ~TIFRPaddedOrder ()
__device__ __host__ int getPaddedIndex (int x_cb, int parity) const
Compute the index into the padded field. Assumes that parity doesn't change from unpadded to padded.
__device__ __host__ void load (RegType v[18], int x, int dir, int parity) const
__device__ __host__ void save (const RegType v[18], int x, int dir, int parity)
__device__ __host__ gauge_wrapper< Float, TIFRPaddedOrder< Float, length > > operator() (int dim, int x_cb, int parity)
This accessor routine returns a gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const gauge_wrapper< Float, TIFRPaddedOrder< Float, length > > operator() (int dim, int x_cb, int parity) const
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
size_t Bytes () const
Public Member Functions inherited from quda::gauge::LegacyOrder< Float, length >
LegacyOrder (const GaugeField &u, Float **ghost_)
LegacyOrder (const LegacyOrder &order)
virtual ~LegacyOrder ()
__device__ __host__ void loadGhost (RegType v[length], int x, int dir, int parity) const
__device__ __host__ void saveGhost (const RegType v[length], int x, int dir, int parity)
__device__ __host__ void loadGhostEx (RegType v[length], int x, int dummy, int dir, int dim, int g, int parity, const int R[]) const
__device__ __host__ void saveGhostEx (const RegType v[length], int x, int dummy, int dir, int dim, int g, int parity, const int R[])
Public Attributes
Float * gauge
const int volumeCB
int exVolumeCB
const Float scale
const int dim [4]
const int exDim [4]
Public Attributes inherited from quda::gauge::LegacyOrder< Float, length >
Float * ghost [QUDA_MAX_DIM]
int faceVolumeCB [QUDA_MAX_DIM]
const int volumeCB
const int stride
const int geometry
const int hasPhase
Static Public Attributes
static constexpr int Nc = 3
Detailed Description
template<typename Float, int length>
struct quda::gauge::TIFRPaddedOrder< Float, length >
struct to define TIFR ordered gauge fields (with inlined z halo of depth two): [mu][parity][t][z+4][y][x/2][col][row]
Definition at line 1954 of file gauge_field_order.h.
Member Typedef Documentation
RegType
template<typename Float , int length> typedef mapper<Float>::type quda::gauge::TIFRPaddedOrder< Float, length >::RegType
Definition at line 1955 of file gauge_field_order.h.
Constructor & Destructor Documentation
TIFRPaddedOrder() [1/2]
template<typename Float , int length> quda::gauge::TIFRPaddedOrder< Float, length >::TIFRPaddedOrder (const GaugeField & u, Float * gauge_ = 0, Float ** ghost_ = 0) inline
Definition at line 1963 of file gauge_field_order.h.
References quda::LatticeField::X().
TIFRPaddedOrder() [2/2]
template<typename Float , int length> quda::gauge::TIFRPaddedOrder< Float, length >::TIFRPaddedOrder (const TIFRPaddedOrder< Float, length > & order) inline
Definition at line 1975 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::dim.
~TIFRPaddedOrder()
template<typename Float , int length> virtual quda::gauge::TIFRPaddedOrder< Float, length >::~TIFRPaddedOrder () inline virtual
Definition at line 1982 of file gauge_field_order.h.
Member Function Documentation
Bytes()
template<typename Float , int length> size_t quda::gauge::TIFRPaddedOrder< Float, length >::Bytes () const inline
Definition at line 2077 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::Nc.
getPaddedIndex()
template<typename Float , int length> __device__ __host__ int quda::gauge::TIFRPaddedOrder< Float, length >::getPaddedIndex (int x_cb, int parity) const inline
Compute the index into the padded field. Assumes that parity doesn't change from unpadded to padded.
Definition at line 1988 of file gauge_field_order.h.
References coord, quda::gauge::TIFRPaddedOrder< Float, length >::dim, quda::gauge::TIFRPaddedOrder< Float, length >::exDim, quda::getCoords(), quda::linkIndex(), and parity.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::load(), and quda::gauge::TIFRPaddedOrder< Float, length >::save().
load()
template<typename Float , int length> __device__ __host__ void quda::gauge::TIFRPaddedOrder< Float, length >::load (RegType v[18], int x, int dir, int parity) const inline
Definition at line 1999 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::exVolumeCB, quda::gauge::TIFRPaddedOrder< Float, length >::gauge, quda::gauge::TIFRPaddedOrder< Float, length >::getPaddedIndex(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::TIFRPaddedOrder< Float, length >::Nc, parity, quda::gauge::TIFRPaddedOrder< Float, length >::scale, x, y, and z.
operator()() [1/2]
template<typename Float , int length> __device__ __host__ gauge_wrapper<Float,TIFRPaddedOrder<Float,length> > quda::gauge::TIFRPaddedOrder< Float, length >::operator() (int dim, int x_cb, int parity) inline
This accessor routine returns a gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 2057 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::dim, and parity.
operator()() [2/2]
template<typename Float , int length> __device__ __host__ const gauge_wrapper<Float,TIFRPaddedOrder<Float,length> > quda::gauge::TIFRPaddedOrder< Float, length >::operator() (int dim, int x_cb, int parity) const inline
This accessor routine returns a const gauge_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_wrapper that curries in access to this field at the above coordinates.
Definition at line 2072 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::dim, and parity.
save()
template<typename Float , int length> __device__ __host__ void quda::gauge::TIFRPaddedOrder< Float, length >::save (const RegType v[18], int x, int dir, int parity) inline
Definition at line 2022 of file gauge_field_order.h.
References quda::gauge::TIFRPaddedOrder< Float, length >::exVolumeCB, quda::gauge::TIFRPaddedOrder< Float, length >::gauge, quda::gauge::TIFRPaddedOrder< Float, length >::getPaddedIndex(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, quda::gauge::TIFRPaddedOrder< Float, length >::Nc, parity, quda::gauge::TIFRPaddedOrder< Float, length >::scale, x, y, and z.
Member Data Documentation
dim
template<typename Float , int length> const int quda::gauge::TIFRPaddedOrder< Float, length >::dim[4]
Definition at line 1961 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::getPaddedIndex(), quda::gauge::TIFRPaddedOrder< Float, length >::operator()(), and quda::gauge::TIFRPaddedOrder< Float, length >::TIFRPaddedOrder().
exDim
template<typename Float , int length> const int quda::gauge::TIFRPaddedOrder< Float, length >::exDim[4]
Definition at line 1962 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::getPaddedIndex().
exVolumeCB
template<typename Float , int length> int quda::gauge::TIFRPaddedOrder< Float, length >::exVolumeCB
Definition at line 1958 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::load(), and quda::gauge::TIFRPaddedOrder< Float, length >::save().
gauge
template<typename Float , int length> Float* quda::gauge::TIFRPaddedOrder< Float, length >::gauge
Definition at line 1956 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::load(), and quda::gauge::TIFRPaddedOrder< Float, length >::save().
Nc
template<typename Float , int length> constexpr int quda::gauge::TIFRPaddedOrder< Float, length >::Nc = 3 static
Definition at line 1959 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::Bytes(), quda::gauge::TIFRPaddedOrder< Float, length >::load(), and quda::gauge::TIFRPaddedOrder< Float, length >::save().
scale
template<typename Float , int length> const Float quda::gauge::TIFRPaddedOrder< Float, length >::scale
Definition at line 1960 of file gauge_field_order.h.
Referenced by quda::gauge::TIFRPaddedOrder< Float, length >::load(), and quda::gauge::TIFRPaddedOrder< Float, length >::save().
volumeCB
template<typename Float , int length> const int quda::gauge::TIFRPaddedOrder< Float, length >::volumeCB
Definition at line 1957 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h