QUDA: quda::Trig< true, float > Struct Template Reference
quda::Trig< true, float > Struct Template Reference
#include <register_traits.h>
Static Public Member Functions
__device__ static __host__ float Atan2 (const float &a, const float &b)
__device__ static __host__ float Sin (const float &a)
__device__ static __host__ float Cos (const float &a)
Detailed Description
template<>
struct quda::Trig< true, float >
Specialization of Trig functions using shorts
Definition at line 221 of file register_traits.h.
Member Function Documentation
Atan2()
__device__ static __host__ float quda::Trig< true, float >::Atan2 (const float & a, const float & b) inline static
Definition at line 222 of file register_traits.h.
References a, atan2f(), and b.
Cos()
__device__ static __host__ float quda::Trig< true, float >::Cos (const float & a) inline static
Definition at line 230 of file register_traits.h.
References a, and cosf().
Sin()
__device__ static __host__ float quda::Trig< true, float >::Sin (const float & a) inline static
Definition at line 223 of file register_traits.h.
References a, and sinf().
The documentation for this struct was generated from the following file:
include/register_traits.h