QUDA: quda::Trig< false, float > Struct Template Reference
quda::Trig< false, float > Struct Template Reference
#include <register_traits.h>
Static Public Member Functions
__device__ static __host__ float Atan2 (const float &a, const float &b)
__device__ static __host__ float Sin (const float &a)
__device__ static __host__ float Cos (const float &a)
__device__ static __host__ void SinCos (const float &a, float *s, float *c)
Detailed Description
template<>
struct quda::Trig< false, float >
Specialization of Trig functions using floats
Definition at line 190 of file register_traits.h.
Member Function Documentation
Atan2()
__device__ static __host__ float quda::Trig< false, float >::Atan2 (const float & a, const float & b) inline static
Definition at line 191 of file register_traits.h.
References a, atan2f(), and b.
Cos()
__device__ static __host__ float quda::Trig< false, float >::Cos (const float & a) inline static
Definition at line 199 of file register_traits.h.
References a, and cosf().
Sin()
__device__ static __host__ float quda::Trig< false, float >::Sin (const float & a) inline static
Definition at line 192 of file register_traits.h.
References a, and sinf().
SinCos()
__device__ static __host__ void quda::Trig< false, float >::SinCos (const float & a, float * s, float * c) inline static
Definition at line 207 of file register_traits.h.
References a, c, and s.
The documentation for this struct was generated from the following file:
include/register_traits.h