QUDA: doubledouble Struct Reference
doubledouble Struct Reference
#include <dbldbl.h>
Public Member Functions
__device__ __host__ doubledouble ()
__device__ __host__ doubledouble (const doubledouble &a)
__device__ __host__ doubledouble (const dbldbl &a)
__device__ __host__ doubledouble (const double &head, const double &tail)
__device__ __host__ doubledouble (const double &head)
__device__ __host__ doubledouble & operator= (const double &head)
__device__ doubledouble & operator+= (const doubledouble &a)
__device__ __host__ double head () const
__device__ __host__ double tail () const
__device__ __host__ void print () const
Public Attributes
dbldbl a
Detailed Description
This C++ wrapper over the above dbldbl functions for easy inclusion in C++ generic template code, e.g., CUB.
Definition at line 283 of file dbldbl.h.
Constructor & Destructor Documentation
doubledouble() [1/5]
__device__ __host__ doubledouble::doubledouble () inline
Definition at line 287 of file dbldbl.h.
References a.
doubledouble() [2/5]
__device__ __host__ doubledouble::doubledouble (const doubledouble & a) inline
Definition at line 288 of file dbldbl.h.
doubledouble() [3/5]
__device__ __host__ doubledouble::doubledouble (const dbldbl & a) inline
Definition at line 289 of file dbldbl.h.
doubledouble() [4/5]
__device__ __host__ doubledouble::doubledouble (const double & head, const double & tail) inline
Definition at line 290 of file dbldbl.h.
References a, head(), and tail().
doubledouble() [5/5]
__device__ __host__ doubledouble::doubledouble (const double & head) inline
Definition at line 291 of file dbldbl.h.
References a, and head().
Member Function Documentation
head()
__device__ __host__ double doubledouble::head () const inline
Definition at line 303 of file dbldbl.h.
References a.
Referenced by doubledouble(), operator=(), print(), doubledouble2::print(), and doubledouble3::print().
operator+=()
__device__ doubledouble& doubledouble::operator+= (const doubledouble & a) inline
Definition at line 298 of file dbldbl.h.
References a, and add_dbldbl().
operator=()
__device__ __host__ doubledouble& doubledouble::operator= (const double & head) inline
Definition at line 293 of file dbldbl.h.
References head().
print()
__device__ __host__ void doubledouble::print () const inline
Definition at line 306 of file dbldbl.h.
References head(), printf(), and tail().
tail()
__device__ __host__ double doubledouble::tail () const inline
Definition at line 304 of file dbldbl.h.
References a.
Referenced by doubledouble(), print(), doubledouble2::print(), and doubledouble3::print().
Member Data Documentation
a
dbldbl doubledouble::a
Definition at line 285 of file dbldbl.h.
Referenced by doubledouble(), head(), operator+=(), and tail().
The documentation for this struct was generated from the following file:
include/dbldbl.h