QUDA: quda::Trig< isHalf, T > Struct Template Reference
quda::Trig< isHalf, T > Struct Template Reference
#include <register_traits.h>
Static Public Member Functions
__device__ static __host__ T Atan2 (const T &a, const T &b)
__device__ static __host__ T Sin (const T &a)
__device__ static __host__ T Cos (const T &a)
__device__ static __host__ void SinCos (const T &a, T *s, T *c)
Detailed Description
template<bool isHalf, typename T>
struct quda::Trig< isHalf, T >
Generic wrapper for Trig functions
Definition at line 179 of file register_traits.h.
Member Function Documentation
Atan2()
template<bool isHalf, typename T> __device__ static __host__ T quda::Trig< isHalf, T >::Atan2 (const T & a, const T & b) inline static
Definition at line 180 of file register_traits.h.
References a, quda::atan2(), and b.
Cos()
template<bool isHalf, typename T> __device__ static __host__ T quda::Trig< isHalf, T >::Cos (const T & a) inline static
Definition at line 182 of file register_traits.h.
References a, and quda::cos().
Sin()
template<bool isHalf, typename T> __device__ static __host__ T quda::Trig< isHalf, T >::Sin (const T & a) inline static
Definition at line 181 of file register_traits.h.
References a, and quda::sin().
SinCos()
template<bool isHalf, typename T> __device__ static __host__ void quda::Trig< isHalf, T >::SinCos (const T & a, T * s, T * c) inline static
Definition at line 183 of file register_traits.h.
References a, c, quda::cos(), s, and quda::sin().
The documentation for this struct was generated from the following file:
include/register_traits.h