QUDA: quda::colorspinor::square< ReduceType, Float > Struct Template Reference
quda::colorspinor::square< ReduceType, Float > Struct Template Reference
#include <color_spinor_field_order.h>
Public Member Functions
__host__ __device__ ReduceType operator() (quda::complex< Float > x)
Detailed Description
template<typename ReduceType, typename Float>
struct quda::colorspinor::square< ReduceType, Float >
Definition at line 170 of file color_spinor_field_order.h.
Member Function Documentation
operator()()
template<typename ReduceType , typename Float > __host__ __device__ ReduceType quda::colorspinor::square< ReduceType, Float >::operator() (quda::complex< Float > x) inline
Definition at line 170 of file color_spinor_field_order.h.
References quda::norm(), quda::colorspinor::square< ReduceType, Float >::operator()(), and x.
Referenced by quda::colorspinor::square< ReduceType, Float >::operator()().
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h