QUDA: quda::DslashCoarseLaunch Struct Reference
quda::DslashCoarseLaunch Struct Reference
Public Member Functions
DslashCoarseLaunch (ColorSpinorField &out, const ColorSpinorField &inA, const ColorSpinorField &inB, const GaugeField &Y, const GaugeField &X, double kappa, int parity, bool dslash, bool clover, bool dagger)
void operator() (DslashCoarsePolicy policy)
Execute the coarse dslash using the given policy.
Public Attributes
ColorSpinorField & out
const ColorSpinorField & inA
const ColorSpinorField & inB
const GaugeField & Y
const GaugeField & X
double kappa
int parity
bool dslash
bool clover
bool dagger
Detailed Description
Definition at line 875 of file dslash_coarse.cu.
Constructor & Destructor Documentation
DslashCoarseLaunch()
quda::DslashCoarseLaunch::DslashCoarseLaunch (ColorSpinorField & out, const ColorSpinorField & inA, const ColorSpinorField & inB, const GaugeField & Y, const GaugeField & X, double kappa, int parity, bool dslash, bool clover, bool dagger) inline
Definition at line 888 of file dslash_coarse.cu.
Member Function Documentation
operator()()
void quda::DslashCoarseLaunch::operator() (DslashCoarsePolicy policy) inline
Execute the coarse dslash using the given policy.
Definition at line 895 of file dslash_coarse.cu.
References quda::Worker::apply(), quda::dslash::aux_worker, quda::LatticeField::bufferIndex, checkLocation, checkPrecision, clover, comm_partitioned(), dagger, quda::Device, dslash, quda::DSLASH_COARSE_GDR, quda::DSLASH_COARSE_GDR_RECV, quda::DSLASH_COARSE_GDR_SEND, quda::DSLASH_COARSE_GDR_SEND_ZERO_COPY_READ, quda::DSLASH_COARSE_ZERO_COPY, quda::DSLASH_COARSE_ZERO_COPY_PACK, quda::DSLASH_COARSE_ZERO_COPY_PACK_GDR_RECV, quda::DSLASH_COARSE_ZERO_COPY_READ, errorQuda, quda::ColorSpinorField::exchangeGhost(), quda::Host, fused_exterior_ndeg_tm_dslash_cuda_gen::i, inA, inB, kappa, out, parity, quda::policy, quda::LatticeField::Precision(), QUDA_DOUBLE_PRECISION, QUDA_MAX_DIM, QUDA_SINGLE_PRECISION, quda::ColorSpinorField::V(), X, and Y.
Member Data Documentation
clover
bool quda::DslashCoarseLaunch::clover
Definition at line 885 of file dslash_coarse.cu.
Referenced by operator()().
dagger
bool quda::DslashCoarseLaunch::dagger
Definition at line 886 of file dslash_coarse.cu.
Referenced by operator()().
dslash
bool quda::DslashCoarseLaunch::dslash
Definition at line 884 of file dslash_coarse.cu.
Referenced by operator()().
inA
const ColorSpinorField& quda::DslashCoarseLaunch::inA
Definition at line 878 of file dslash_coarse.cu.
Referenced by operator()().
inB
const ColorSpinorField& quda::DslashCoarseLaunch::inB
Definition at line 879 of file dslash_coarse.cu.
Referenced by operator()().
kappa
double quda::DslashCoarseLaunch::kappa
Definition at line 882 of file dslash_coarse.cu.
Referenced by operator()().
out
ColorSpinorField& quda::DslashCoarseLaunch::out
Definition at line 877 of file dslash_coarse.cu.
Referenced by operator()().
parity
int quda::DslashCoarseLaunch::parity
Definition at line 883 of file dslash_coarse.cu.
Referenced by operator()().
X
const GaugeField& quda::DslashCoarseLaunch::X
Definition at line 881 of file dslash_coarse.cu.
Referenced by operator()().
Y
const GaugeField& quda::DslashCoarseLaunch::Y
Definition at line 880 of file dslash_coarse.cu.
Referenced by operator()().
The documentation for this struct was generated from the following file:
lib/dslash_coarse.cu