QUDA: quda::complex< ValueType > Struct Template Reference
quda::complex< ValueType > Struct Template Reference
#include <complex_quda.h>
Public Types
typedef ValueType value_type
Public Member Functions
__host__ __device__ complex (const ValueType &re=ValueType(), const ValueType &im=ValueType())
template<class X >
__host__ __device__ complex (const complex< X > &z)
template<class X >
__host__ __device__ complex (const std::complex< X > &z)
template<typename T >
__host__ __device__ complex< ValueType > & operator= (const complex< T > z)
__host__ __device__ complex< ValueType > & operator+= (const complex< ValueType > z)
__host__ __device__ complex< ValueType > & operator-= (const complex< ValueType > z)
__host__ __device__ complex< ValueType > & operator*= (const complex< ValueType > z)
__host__ __device__ complex< ValueType > & operator/= (const complex< ValueType > z)
__host__ __device__ complex< ValueType > & operator*= (const ValueType z)
__host__ __device__ ValueType real () const volatile
__host__ __device__ ValueType imag () const volatile
__host__ __device__ ValueType real () const
__host__ __device__ ValueType imag () const
__host__ __device__ void real (ValueType) volatile
__host__ __device__ void imag (ValueType) volatile
__host__ __device__ void real (ValueType)
__host__ __device__ void imag (ValueType)
Detailed Description
template<typename ValueType>
struct quda::complex< ValueType >
Definition at line 119 of file complex_quda.h.
Member Typedef Documentation
value_type
template<typename ValueType > typedef ValueType quda::complex< ValueType >::value_type
Definition at line 356 of file complex_quda.h.
Constructor & Destructor Documentation
complex() [1/3]
template<typename ValueType > __host__ __device__ quda::complex< ValueType >::complex (const ValueType & re = ValueType(), const ValueType & im = ValueType()) inline
Definition at line 360 of file complex_quda.h.
References quda::complex< ValueType >::imag(), and quda::complex< ValueType >::real().
complex() [2/3]
template<typename ValueType > template<class X > __host__ __device__ quda::complex< ValueType >::complex (const complex< X > & z) inline
Definition at line 368 of file complex_quda.h.
References quda::complex< ValueType >::imag(), quda::complex< ValueType >::real(), and z.
complex() [3/3]
template<typename ValueType > template<class X > __host__ __device__ quda::complex< ValueType >::complex (const std::complex< X > & z) inline
Definition at line 376 of file complex_quda.h.
References quda::complex< ValueType >::imag(), quda::complex< ValueType >::real(), and z.
Member Function Documentation
imag() [1/4]
template<typename ValueType > __host__ __device__ ValueType quda::complex< ValueType >::imag () const volatile inline
Referenced by quda::complex< ValueType >::complex(), quda::complex< ValueType >::operator+=(), quda::complex< ValueType >::operator-=(), and quda::complex< ValueType >::operator=().
imag() [2/4]
template<typename ValueType > __host__ __device__ ValueType quda::complex< ValueType >::imag () const inline
imag() [3/4]
template<typename ValueType > __host__ __device__ void quda::complex< ValueType >::imag (ValueType) volatile inline
imag() [4/4]
template<typename ValueType > __host__ __device__ void quda::complex< ValueType >::imag (ValueType) inline
operator*=() [1/2]
template<typename ValueType > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator*= (const complex< ValueType > z) inline
Definition at line 408 of file complex_quda.h.
References z.
operator*=() [2/2]
template<typename ValueType > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator*= (const ValueType z) inline
Definition at line 422 of file complex_quda.h.
References x, y, and z.
operator+=()
template<typename ValueType > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator+= (const complex< ValueType > z) inline
Definition at line 392 of file complex_quda.h.
References quda::complex< ValueType >::imag(), quda::complex< ValueType >::real(), and z.
operator-=()
template<typename ValueType > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator-= (const complex< ValueType > z) inline
Definition at line 400 of file complex_quda.h.
References quda::complex< ValueType >::imag(), quda::complex< ValueType >::real(), and z.
operator/=()
template<typename ValueType > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator/= (const complex< ValueType > z) inline
Definition at line 415 of file complex_quda.h.
References z.
operator=()
template<typename ValueType > template<typename T > __host__ __device__ complex<ValueType>& quda::complex< ValueType >::operator= (const complex< T > z) inline
Definition at line 384 of file complex_quda.h.
References quda::complex< ValueType >::imag(), quda::complex< ValueType >::real(), and z.
real() [1/4]
template<typename ValueType > __host__ __device__ ValueType quda::complex< ValueType >::real () const volatile inline
Referenced by quda::complex< ValueType >::complex(), quda::complex< ValueType >::operator+=(), quda::complex< ValueType >::operator-=(), and quda::complex< ValueType >::operator=().
real() [2/4]
template<typename ValueType > __host__ __device__ ValueType quda::complex< ValueType >::real () const inline
real() [3/4]
template<typename ValueType > __host__ __device__ void quda::complex< ValueType >::real (ValueType) volatile inline
real() [4/4]
template<typename ValueType > __host__ __device__ void quda::complex< ValueType >::real (ValueType) inline
The documentation for this struct was generated from the following file:
include/complex_quda.h