QUDA: quda::gauge::Reconstruct< 13, Float > Struct Template Reference
quda::gauge::Reconstruct< 13, Float > Struct Template Reference
#include <gauge_field_order.h>
Public Types
typedef mapper< Float >::type RegType
typedef complex< RegType > Complex
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< 13, Float > &recon)
__device__ __host__ void Pack (RegType out[12], const RegType in[18], int idx) const
template<typename I >
__device__ __host__ void Unpack (RegType out[18], const RegType in[12], int idx, int dir, const RegType phase, const I *X, const int *R) const
__device__ __host__ RegType getPhase (const RegType in[18]) const
Public Attributes
const Reconstruct< 12, Float > reconstruct_12
const RegType scale
Detailed Description
template<typename Float>
struct quda::gauge::Reconstruct< 13, Float >
Definition at line 750 of file gauge_field_order.h.
Member Typedef Documentation
Complex
template<typename Float > typedef complex<RegType> quda::gauge::Reconstruct< 13, Float >::Complex
Definition at line 752 of file gauge_field_order.h.
RegType
template<typename Float > typedef mapper<Float>::type quda::gauge::Reconstruct< 13, Float >::RegType
Definition at line 751 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<typename Float > quda::gauge::Reconstruct< 13, Float >::Reconstruct (const GaugeField & u) inline
Definition at line 756 of file gauge_field_order.h.
Reconstruct() [2/2]
template<typename Float > quda::gauge::Reconstruct< 13, Float >::Reconstruct (const Reconstruct< 13, Float > & recon) inline
Definition at line 757 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<typename Float > __device__ __host__ RegType quda::gauge::Reconstruct< 13, Float >::getPhase (const RegType in[18]) const inline
Definition at line 788 of file gauge_field_order.h.
References a, quda::arg(), quda::conj(), quda::getDeterminant(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, and in.
Pack()
template<typename Float > __device__ __host__ void quda::gauge::Reconstruct< 13, Float >::Pack (RegType out[12], const RegType in[18], int idx) const inline
Definition at line 760 of file gauge_field_order.h.
References idx, in, out, and quda::gauge::Reconstruct< 12, Float >::Pack().
Unpack()
template<typename Float > template<typename I > __device__ __host__ void quda::gauge::Reconstruct< 13, Float >::Unpack (RegType out[18], const RegType in[12], int idx, int dir, const RegType phase, const I * X, const int * R) const inline
Definition at line 765 of file gauge_field_order.h.
References dw_dslash_4D_cuda_gen::coeff(), quda::conj(), fused_exterior_ndeg_tm_dslash_cuda_gen::i, in, and out.
Member Data Documentation
reconstruct_12
template<typename Float > const Reconstruct<12,Float> quda::gauge::Reconstruct< 13, Float >::reconstruct_12
Definition at line 753 of file gauge_field_order.h.
scale
template<typename Float > const RegType quda::gauge::Reconstruct< 13, Float >::scale
Definition at line 754 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h