QUDA: doublesingle Struct Reference
doublesingle Struct Reference
#include <double_single.h>
Public Member Functions
__host__ __device__ doublesingle ()
__host__ __device__ doublesingle (const volatile doublesingle &b)
__host__ __device__ doublesingle (const float a)
__host__ __device__ void operator+= (const doublesingle &b)
__host__ __device__ void operator+= (const volatile doublesingle &b)
__host__ __device__ void operator+= (const float &b)
__host__ __device__ doublesingle & operator= (const doublesingle &b)
__host__ __device__ doublesingle & operator= (const float &b)
Public Attributes
float2 a
Detailed Description
Definition at line 12 of file double_single.h.
Constructor & Destructor Documentation
doublesingle() [1/3]
__host__ __device__ doublesingle::doublesingle () inline
Definition at line 14 of file double_single.h.
doublesingle() [2/3]
__host__ __device__ doublesingle::doublesingle (const volatile doublesingle & b) inline
Definition at line 15 of file double_single.h.
doublesingle() [3/3]
__host__ __device__ doublesingle::doublesingle (const float a) inline
Definition at line 16 of file double_single.h.
Member Function Documentation
operator+=() [1/3]
__host__ __device__ void doublesingle::operator+= (const doublesingle & b) inline
Definition at line 18 of file double_single.h.
References b, and dsadd().
operator+=() [2/3]
__host__ __device__ void doublesingle::operator+= (const volatile doublesingle & b) inline
Definition at line 19 of file double_single.h.
References b, and dsadd().
operator+=() [3/3]
__host__ __device__ void doublesingle::operator+= (const float & b) inline
Definition at line 20 of file double_single.h.
References b, and dsadd().
operator=() [1/2]
__host__ __device__ doublesingle& doublesingle::operator= (const doublesingle & b) inline
Definition at line 24 of file double_single.h.
References a, and b.
operator=() [2/2]
__host__ __device__ doublesingle& doublesingle::operator= (const float & b) inline
Definition at line 27 of file double_single.h.
References a, and b.
Member Data Documentation
a
float2 doublesingle::a
Definition at line 13 of file double_single.h.
Referenced by operator=().
The documentation for this struct was generated from the following file:
include/double_single.h