QUDA: tests/wilson_dslash_reference.h File Reference
wilson_dslash_reference.h File Reference
#include <enum_quda.h>
#include <quda.h>
Functions
void wil_dslash (void *res, void **gauge, void *spinorField, int oddBit, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void wil_mat (void *out, void **gauge, void *in, double kappa, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void wil_matpc (void *out, void **gauge, void *in, double kappa, QudaMatPCType matpc_type, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void tm_dslash (void *res, void **gauge, void *spinorField, double kappa, double mu, QudaTwistFlavorType flavor, int oddBit, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sprecision, QudaGaugeParam &param)
void tm_mat (void *out, void **gauge, void *in, double kappa, double mu, QudaTwistFlavorType flavor, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void tm_matpc (void *out, void **gauge, void *in, double kappa, double mu, QudaTwistFlavorType flavor, QudaMatPCType matpc_type, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void tmc_dslash (void *out, void **gauge, void *in, void *clover, void *cInv, double kappa, double mu, QudaTwistFlavorType flavor, int oddBit, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sprecision, QudaGaugeParam &param)
void tmc_mat (void *out, void **gauge, void *clover, void *in, double kappa, double mu, QudaTwistFlavorType flavor, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param)
void tmc_matpc (void *out, void **gauge, void *in, void *clover, void *cInv, double kappa, double mu, QudaTwistFlavorType flavor, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param)
void tm_ndeg_dslash (void *res1, void *res2, void **gaugeFull, void *spinorField1, void *spinorField2, double kappa, double mu, double epsilon, int oddBit, int daggerBit, QudaMatPCType matpc_type, QudaPrecision precision, QudaGaugeParam &gauge_param)
void tm_ndeg_matpc (void *outEven1, void *outEven2, void **gauge, void *inEven1, void *inEven2, double kappa, double mu, double epsilon, QudaMatPCType matpc_type, int dagger_bit, QudaPrecision precision, QudaGaugeParam &gauge_param)
void tm_ndeg_mat (void *evenOut, void *oddOut, void **gauge, void *evenIn, void *oddIn, double kappa, double mu, double epsilon, int dagger_bit, QudaPrecision precision, QudaGaugeParam &gauge_param)
void apply_clover (void *out, void *clover, void *in, int parity, QudaPrecision precision)
void clover_dslash (void *res, void **gauge, void *clover, void *spinorField, int oddBit, int daggerBit, QudaPrecision precision, QudaGaugeParam &param)
void clover_mat (void *out, void **gauge, void *clover, void *in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param)
void clover_matpc (void *out, void **gauge, void *clover, void *clover_inv, void *in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param)
Function Documentation
apply_clover()
void apply_clover (void * out, void * clover, void * in, int parity, QudaPrecision precision)
Definition at line 66 of file clover_reference.cpp.
References dslash_cuda_gen::clover, cloverReference(), errorQuda, in, out, parity, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by clover_dslash(), clover_mat(), clover_matpc(), and twistCloverGamma5().
clover_dslash()
void clover_dslash (void * res, void ** gauge, void * clover, void * spinorField, int oddBit, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 81 of file clover_reference.cpp.
References apply_clover(), dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, free(), in, malloc(), out, param, parity, spinorSiteSize, tmp, Vh, and wil_dslash().
Referenced by dslashRef().
clover_mat()
void clover_mat (void * out, void ** gauge, void * clover, void * in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 149 of file clover_reference.cpp.
References apply_clover(), dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, free(), gauge_param, in, kappa, malloc(), out, spinorSiteSize, tmp, V, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
clover_matpc()
void clover_matpc (void * out, void ** gauge, void * clover, void * clover_inv, void * in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 92 of file clover_reference.cpp.
References apply_clover(), dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, errorQuda, free(), gauge_param, in, kappa, malloc(), matpc_type, out, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, spinorSiteSize, tmp, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tm_dslash()
void tm_dslash (void * res, void ** gauge, void * spinorField, double kappa, double mu, QudaTwistFlavorType flavor, int oddBit, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sprecision, QudaGaugeParam & param)
Definition at line 277 of file wilson_dslash_reference.cpp.
References gauge_param, kappa, matpc_type, mu, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_GAMMA5_INVERSE, twist_gamma5(), Vh, and wil_dslash().
Referenced by dslashRef().
tm_mat()
void tm_mat (void * out, void ** gauge, void * in, double kappa, double mu, QudaTwistFlavorType flavor, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 311 of file wilson_dslash_reference.cpp.
References free(), gauge_param, in, kappa, malloc(), mu, out, QUDA_TWIST_GAMMA5_DIRECT, spinorSiteSize, tmp, twist_gamma5(), V, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tm_matpc()
void tm_matpc (void * out, void ** gauge, void * in, double kappa, double mu, QudaTwistFlavorType flavor, QudaMatPCType matpc_type, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 358 of file wilson_dslash_reference.cpp.
References free(), gauge_param, kappa, malloc(), matpc_type, mu, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_GAMMA5_INVERSE, spinorSiteSize, tmp, twist_gamma5(), Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tm_ndeg_dslash()
void tm_ndeg_dslash (void * res1, void * res2, void ** gaugeFull, void * spinorField1, void * spinorField2, double kappa, double mu, double epsilon, int oddBit, int daggerBit, QudaMatPCType matpc_type, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 462 of file wilson_dslash_reference.cpp.
References gauge_param, kappa, matpc_type, mu, ndeg_twist_gamma5(), QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_INVERSE, Vh, and wil_dslash().
Referenced by dslashRef().
tm_ndeg_mat()
void tm_ndeg_mat (void * evenOut, void * oddOut, void ** gauge, void * evenIn, void * oddIn, double kappa, double mu, double epsilon, int dagger_bit, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 545 of file wilson_dslash_reference.cpp.
References free(), gauge_param, kappa, malloc(), mu, ndeg_twist_gamma5(), QUDA_TWIST_GAMMA5_DIRECT, spinorSiteSize, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tm_ndeg_matpc()
void tm_ndeg_matpc (void * outEven1, void * outEven2, void ** gauge, void * inEven1, void * inEven2, double kappa, double mu, double epsilon, QudaMatPCType matpc_type, int dagger_bit, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 477 of file wilson_dslash_reference.cpp.
References free(), gauge_param, kappa, malloc(), matpc_type, mu, ndeg_twist_gamma5(), QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_GAMMA5_INVERSE, spinorSiteSize, tmp1, tmp2, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tmc_dslash()
void tmc_dslash (void * out, void ** gauge, void * in, void * clover, void * cInv, double kappa, double mu, QudaTwistFlavorType flavor, int oddBit, QudaMatPCType matpc_type, int daggerBit, QudaPrecision sprecision, QudaGaugeParam & param)
Definition at line 234 of file clover_reference.cpp.
References dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, free(), in, kappa, malloc(), matpc_type, mu, out, param, parity, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_INVERSE, spinorSiteSize, tmp1, tmp2, twistCloverGamma5(), Vh, and wil_dslash().
Referenced by dslashRef().
tmc_mat()
void tmc_mat (void * out, void ** gauge, void * clover, void * in, double kappa, double mu, QudaTwistFlavorType flavor, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 257 of file clover_reference.cpp.
References dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, free(), gauge_param, in, kappa, malloc(), mu, out, QUDA_TWIST_GAMMA5_DIRECT, spinorSiteSize, tmp, twistCloverGamma5(), V, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
tmc_matpc()
void tmc_matpc (void * out, void ** gauge, void * in, void * clover, void * cInv, double kappa, double mu, QudaTwistFlavorType flavor, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param)
Definition at line 284 of file clover_reference.cpp.
References dslash_cuda_gen::clover, deg_tm_dslash_cuda_gen::dagger, errorQuda, free(), gauge_param, in, kappa, malloc(), matpc_type, mu, out, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_TWIST_GAMMA5_DIRECT, QUDA_TWIST_GAMMA5_INVERSE, spinorSiteSize, tmp1, tmp2, twistCloverGamma5(), Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
wil_dslash()
void wil_dslash (void * res, void ** gauge, void * spinorField, int oddBit, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 175 of file wilson_dslash_reference.cpp.
References quda::ColorSpinorParam::create, csParam, d, dslashReference(), errorQuda, quda::ColorSpinorParam::fieldOrder, quda::ColorSpinorParam::gammaBasis, gauge_param, quda::GaugeField::Ghost(), quda::LatticeFieldParam::ghostExchange, in, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::ColorSpinorParam::nSpin, out, quda::LatticeFieldParam::pad, quda::LatticeFieldParam::precision, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DOUBLE_PRECISION, QUDA_EVEN_ODD_SITE_ORDER, QUDA_EVEN_PARITY, QUDA_GHOST_EXCHANGE_PAD, QUDA_INVALID_PARITY, QUDA_ODD_PARITY, QUDA_PARITY_SITE_SUBSET, QUDA_REFERENCE_FIELD_CREATE, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::ColorSpinorParam::v, quda::LatticeFieldParam::x, and Z.
Referenced by clover_dslash(), clover_mat(), clover_matpc(), dslashRef(), tm_dslash(), tm_mat(), tm_matpc(), tm_ndeg_dslash(), tm_ndeg_mat(), tm_ndeg_matpc(), tmc_dslash(), tmc_mat(), tmc_matpc(), wil_mat(), and wil_matpc().
wil_mat()
void wil_mat (void * out, void ** gauge, void * in, double kappa, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 296 of file wilson_dslash_reference.cpp.
References gauge_param, in, kappa, out, spinorSiteSize, V, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().
wil_matpc()
void wil_matpc (void * out, void ** gauge, void * in, double kappa, QudaMatPCType matpc_type, int daggerBit, QudaPrecision precision, QudaGaugeParam & param)
Definition at line 334 of file wilson_dslash_reference.cpp.
References free(), gauge_param, kappa, malloc(), matpc_type, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, spinorSiteSize, tmp, Vh, wil_dslash(), and quda::blas::xpay().
Referenced by dslashRef(), and main().