QUDA: lib/check_params.h File Reference
check_params.h File Reference
#include <float.h>
Macros
#define INVALID_INT QUDA_INVALID_ENUM
#define INVALID_DOUBLE DBL_MIN
Functions
void printQudaGaugeParam (QudaGaugeParam *param)
void printQudaEigParam (QudaEigParam *param)
void printQudaCloverParam (QudaInvertParam *param)
void printQudaInvertParam (QudaInvertParam *param)
void printQudaMultigridParam (QudaMultigridParam *param)
Macro Definition Documentation
INVALID_DOUBLE
#define INVALID_DOUBLE DBL_MIN
Definition at line 15 of file check_params.h.
Referenced by printQudaCloverParam(), printQudaEigParam(), printQudaGaugeParam(), printQudaInvertParam(), and printQudaMultigridParam().
INVALID_INT
#define INVALID_INT QUDA_INVALID_ENUM
Definition at line 14 of file check_params.h.
Referenced by printQudaCloverParam(), printQudaEigParam(), printQudaGaugeParam(), printQudaInvertParam(), and printQudaMultigridParam().
Function Documentation
printQudaCloverParam()
void printQudaCloverParam (QudaInvertParam * param)
Definition at line 214 of file check_params.h.
References clover_coeff, QudaInvertParam_s::clover_cuda_prec, QudaInvertParam_s::clover_cuda_prec_precondition, QudaInvertParam_s::clover_cuda_prec_refinement_sloppy, QudaInvertParam_s::clover_cuda_prec_sloppy, compute_clover, QudaInvertParam_s::dslash_type, INVALID_DOUBLE, INVALID_INT, newQudaInvertParam(), QUDA_CLOVER_WILSON_DSLASH, QUDA_CPU_FIELD_LOCATION, QUDA_INVALID_CLOVER_ORDER, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_PRECISION, and QUDA_TWISTED_CLOVER_DSLASH.
Referenced by printQudaInvertParam().
printQudaEigParam()
void printQudaEigParam (QudaEigParam * param)
Print the members of QudaEigParam.
Parameters
param The QudaEigParam whose elements we are to print.
Definition at line 143 of file check_params.h.
References eig_type, INVALID_DOUBLE, INVALID_INT, mem_type_ritz, param, printfQuda, QUDA_BOOLEAN_FALSE, QUDA_BOOLEAN_INVALID, QUDA_BOOLEAN_TRUE, QUDA_CUDA_FIELD_LOCATION, QUDA_EIG_INVALID, QUDA_EIG_TR_LANCZOS, QUDA_EIGEN_EXTLIB, QUDA_EXTLIB_INVALID, QUDA_INVALID_FIELD_LOCATION, QUDA_MEMORY_DEVICE, QUDA_MEMORY_INVALID, QUDA_SPECTRUM_LR_EIG, and tol.
Referenced by eigensolveQuda().
printQudaGaugeParam()
void printQudaGaugeParam (QudaGaugeParam * param)
Print the members of QudaGaugeParam.
Parameters
param The QudaGaugeParam whose elements we are to print.
Definition at line 40 of file check_params.h.
References anisotropy, cpu_prec, QudaGaugeParam_s::cuda_prec, cuda_prec, QudaGaugeParam_s::cuda_prec_precondition, cuda_prec_precondition, QudaGaugeParam_s::cuda_prec_refinement_sloppy, cuda_prec_refinement_sloppy, QudaGaugeParam_s::cuda_prec_sloppy, cuda_prec_sloppy, gauge_order, INVALID_DOUBLE, INVALID_INT, newQudaEigParam(), printfQuda, QUDA_ASQTAD_LONG_LINKS, QUDA_CPU_FIELD_LOCATION, QUDA_GAUGE_FIXED_INVALID, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_GAUGE_ORDER, QUDA_INVALID_LINKS, QUDA_INVALID_PRECISION, QUDA_INVALID_T_BOUNDARY, QUDA_RECONSTRUCT_INVALID, QUDA_STAGGERED_PHASE_INVALID, QUDA_STAGGERED_PHASE_NO, QUDA_WILSON_LINKS, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_precondition, QudaGaugeParam_s::reconstruct_refinement_sloppy, QudaGaugeParam_s::reconstruct_sloppy, QudaGaugeParam_s::type, and X.
Referenced by loadGaugeQuda().
printQudaInvertParam()
void printQudaInvertParam (QudaInvertParam * param)
Print the members of QudaInvertParam.
Parameters
param The QudaInvertParam whose elements we are to print.
Whether to use a pipelined solver
< Number of offsets in the multi-shift solver
< Number of offsets in the multi-shift solver
< width of domain overlaps
Definition at line 277 of file check_params.h.
References ca_basis, QudaInvertParam_s::ca_basis, ca_lambda_max, ca_lambda_min, QudaInvertParam_s::chrono_precision, QudaInvertParam_s::compute_action, cpu_prec, cuda_prec, QudaInvertParam_s::cuda_prec, cuda_prec_precondition, QudaInvertParam_s::cuda_prec_precondition, cuda_prec_refinement_sloppy, QudaInvertParam_s::cuda_prec_refinement_sloppy, cuda_prec_ritz, cuda_prec_sloppy, QudaInvertParam_s::cuda_prec_sloppy, dagger, deflation_grid, dslash_type, QudaInvertParam_s::dslash_type, eigcg_max_restarts, eigenval_tol, gcrNkrylov, quda::get_pointer_location(), inc_tol, QudaInvertParam_s::input_location, inv_type, QudaInvertParam_s::inv_type, QudaInvertParam_s::inv_type_precondition, INVALID_DOUBLE, INVALID_INT, kappa, laplace3D, Ls, mass, matpc_type, max_restart_num, max_search_dim, mu, nev, newQudaMultigridParam(), QudaInvertParam_s::num_offset, omega, QudaInvertParam_s::output_location, pipeline, printfQuda, printQudaCloverParam(), QUDA_ADDITIVE_SCHWARZ, QUDA_ASQTAD_DSLASH, QUDA_BICGSTAB_INVERTER, QUDA_CA_CG_INVERTER, QUDA_CA_CGNE_INVERTER, QUDA_CA_CGNR_INVERTER, QUDA_CA_GCR_INVERTER, QUDA_CG_INVERTER, QUDA_CHEBYSHEV_BASIS, QUDA_CPU_FIELD_LOCATION, QUDA_DAG_INVALID, QUDA_DEFAULT_NORMALIZATION, QUDA_DOMAIN_WALL_4D_DSLASH, QUDA_DOMAIN_WALL_DSLASH, QUDA_EIGEN_EXTLIB, QUDA_EXTLIB_INVALID, QUDA_GCR_INVERTER, QUDA_HEAVY_QUARK_RESIDUAL, QUDA_INVALID_BASIS, QUDA_INVALID_DIRAC_ORDER, QUDA_INVALID_DSLASH, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_GAMMA_BASIS, QUDA_INVALID_INVERTER, QUDA_INVALID_NORMALIZATION, QUDA_INVALID_PRECISION, QUDA_INVALID_RESIDUAL, QUDA_INVALID_SCHWARZ, QUDA_INVALID_SOLUTION, QUDA_INVALID_SOLVE, QUDA_INVALID_VERBOSITY, QUDA_L2_RELATIVE_RESIDUAL, QUDA_MATPC_INVALID, QUDA_MOBIUS_DWF_DSLASH, QUDA_MPBICGSTAB_INVERTER, QUDA_MPCG_INVERTER, QUDA_MR_INVERTER, QUDA_POWER_BASIS, QUDA_PRESERVE_SOURCE_INVALID, QUDA_SINGLE_PRECISION, QUDA_STAGGERED_DSLASH, QUDA_TWIST_INVALID, QUDA_TWISTED_MASS_DSLASH, QUDA_USE_INIT_GUESS_INVALID, QUDA_USE_INIT_GUESS_NO, reliable_delta, QudaInvertParam_s::reliable_delta, QudaInvertParam_s::reliable_delta_refinement, QudaInvertParam_s::residual_type, schwarz_type, solution_accumulator_pipeline, solution_type, solve_type, tol, tol_hq, tol_restart, twist_flavor, verbosity, and warningQuda.
Referenced by cloverQuda(), dslashQuda(), dslashQuda_4dpc(), dslashQuda_mdwf(), eigensolveQuda(), invertMultiSrcQuda(), invertQuda(), loadCloverQuda(), MatDagMatQuda(), MatQuda(), performWuppertalnStep(), and printQudaMultigridParam().
printQudaMultigridParam()
void printQudaMultigridParam (QudaMultigridParam * param)
Print the members of QudaMultigridParam.
Parameters
param The QudaMultigridParam whose elements we are to print.
Definition at line 598 of file check_params.h.
References coarse_solver, coarse_solver_ca_basis, coarse_solver_ca_basis_size, coarse_solver_ca_lambda_max, coarse_solver_ca_lambda_min, coarse_solver_maxiter, coarse_solver_tol, QudaMultigridParam_s::compute_null_vector, errorQuda, generate_all_levels, QudaMultigridParam_s::generate_all_levels, geo_block_size, INVALID_DOUBLE, INVALID_INT, QudaMultigridParam_s::invert_param, mu_factor, n_block_ortho, QudaMultigridParam_s::n_level, QudaMultigridParam_s::n_vec, nu_post, nu_pre, num_setup_iter, omega, post_orthonormalize, pre_orthonormalize, printfQuda, printQudaInvertParam(), QUDA_BICGSTAB_INVERTER, QUDA_BOOLEAN_FALSE, QUDA_BOOLEAN_INVALID, QUDA_BOOLEAN_TRUE, QUDA_COMPUTE_NULL_VECTOR_INVALID, QUDA_COMPUTE_NULL_VECTOR_YES, QUDA_CUDA_FIELD_LOCATION, QUDA_INVALID_BASIS, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_INVERTER, QUDA_INVALID_PRECISION, QUDA_INVALID_SCHWARZ, QUDA_INVALID_SETUP_TYPE, QUDA_INVALID_SOLUTION, QUDA_INVALID_SOLVE, QUDA_INVALID_VERBOSITY, QUDA_MAX_MG_LEVEL, QUDA_MG_CYCLE_INVALID, QUDA_NULL_VECTOR_SETUP, QUDA_POWER_BASIS, QUDA_SILENT, QUDA_SINGLE_PRECISION, setup_ca_basis, setup_ca_basis_size, setup_ca_lambda_max, setup_ca_lambda_min, setup_location, setup_maxiter, setup_maxiter_refresh, setup_tol, setup_type, smoother_solve_type, smoother_tol, and verbosity.
Referenced by quda::multigrid_solver::multigrid_solver().