QUDA: quda::GaugeOvrImpSTOUT< Float, Arg > Class Template Reference
quda::GaugeOvrImpSTOUT< Float, Arg > Class Template Reference
Public Member Functions
GaugeOvrImpSTOUT (Arg &arg, const GaugeField &meta)
virtual ~GaugeOvrImpSTOUT ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
void preTune ()
void postTune ()
long long flops () const
long long bytes () const
Private Member Functions
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
Arg & arg
const GaugeField & meta
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, typename Arg>
class quda::GaugeOvrImpSTOUT< Float, Arg >
Definition at line 160 of file gauge_stout.cu.
Constructor & Destructor Documentation
GaugeOvrImpSTOUT()
template<typename Float , typename Arg > quda::GaugeOvrImpSTOUT< Float, Arg >::GaugeOvrImpSTOUT (Arg & arg, const GaugeField & meta) inline
Definition at line 171 of file gauge_stout.cu.
~GaugeOvrImpSTOUT()
template<typename Float , typename Arg > virtual quda::GaugeOvrImpSTOUT< Float, Arg >::~GaugeOvrImpSTOUT () inline virtual
Definition at line 172 of file gauge_stout.cu.
Member Function Documentation
apply()
template<typename Float , typename Arg > void quda::GaugeOvrImpSTOUT< Float, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 174 of file gauge_stout.cu.
References quda::arg(), quda::TuneParam::block, errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::LatticeField::Location(), QUDA_CUDA_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
bytes()
template<typename Float , typename Arg > long long quda::GaugeOvrImpSTOUT< Float, Arg >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 204 of file gauge_stout.cu.
flops()
template<typename Float , typename Arg > long long quda::GaugeOvrImpSTOUT< Float, Arg >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 203 of file gauge_stout.cu.
minThreads()
template<typename Float , typename Arg > unsigned int quda::GaugeOvrImpSTOUT< Float, Arg >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 167 of file gauge_stout.cu.
postTune()
template<typename Float , typename Arg > void quda::GaugeOvrImpSTOUT< Float, Arg >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 201 of file gauge_stout.cu.
preTune()
template<typename Float , typename Arg > void quda::GaugeOvrImpSTOUT< Float, Arg >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 200 of file gauge_stout.cu.
tuneGridDim()
template<typename Float , typename Arg > bool quda::GaugeOvrImpSTOUT< Float, Arg >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 166 of file gauge_stout.cu.
tuneKey()
template<typename Float , typename Arg > TuneKey quda::GaugeOvrImpSTOUT< Float, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 193 of file gauge_stout.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float , typename Arg > Arg& quda::GaugeOvrImpSTOUT< Float, Arg >::arg private
Definition at line 162 of file gauge_stout.cu.
meta
template<typename Float , typename Arg > const GaugeField& quda::GaugeOvrImpSTOUT< Float, Arg >::meta private
Definition at line 163 of file gauge_stout.cu.
The documentation for this class was generated from the following file:
lib/gauge_stout.cu