QUDA: quda::GaugeCovDev Class Reference
quda::GaugeCovDev Class Reference
Full Covariant Derivative operator. Although not a Dirac operator per se, it's a linear operator so it's conventient to put in the Dirac operator abstraction.
#include <dirac_quda.h>
Public Member Functions
GaugeCovDev (const DiracParam &param)
GaugeCovDev (const GaugeCovDev &covDev)
virtual ~GaugeCovDev ()
GaugeCovDev & operator= (const GaugeCovDev &covDev)
virtual void DslashCD (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const int mu) const
virtual void MCD (ColorSpinorField &out, const ColorSpinorField &in, const int mu) const
virtual void MdagMCD (ColorSpinorField &out, const ColorSpinorField &in, const int mu) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Full Covariant Derivative operator. Although not a Dirac operator per se, it's a linear operator so it's conventient to put in the Dirac operator abstraction.
Definition at line 1069 of file dirac_quda.h.
Constructor & Destructor Documentation
GaugeCovDev() [1/2]
quda::GaugeCovDev::GaugeCovDev (const DiracParam & param)
Definition at line 9 of file gauge_covdev.cpp.
GaugeCovDev() [2/2]
quda::GaugeCovDev::GaugeCovDev (const GaugeCovDev & covDev)
Definition at line 11 of file gauge_covdev.cpp.
~GaugeCovDev()
quda::GaugeCovDev::~GaugeCovDev () virtual
Definition at line 13 of file gauge_covdev.cpp.
Member Function Documentation
Dslash()
void quda::GaugeCovDev::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Implements quda::Dirac.
Definition at line 49 of file gauge_covdev.cpp.
DslashCD()
void quda::GaugeCovDev::DslashCD (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const int mu) const virtual
Definition at line 21 of file gauge_covdev.cpp.
References quda::ApplyCovDev(), quda::Dirac::checkSpinorAlias(), comm_dim(), comm_dim_partitioned(), quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by MCD().
DslashXpay()
void quda::GaugeCovDev::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Implements quda::Dirac.
Definition at line 54 of file gauge_covdev.cpp.
M()
void quda::GaugeCovDev::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Definition at line 63 of file gauge_covdev.cpp.
MCD()
void quda::GaugeCovDev::MCD (ColorSpinorField & out, const ColorSpinorField & in, const int mu) const virtual
Definition at line 32 of file gauge_covdev.cpp.
References quda::Dirac::checkFullSpinor(), DslashCD(), and QUDA_INVALID_PARITY.
Referenced by dslashCUDA(), and MdagMCD().
MdagM()
void quda::GaugeCovDev::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Definition at line 68 of file gauge_covdev.cpp.
MdagMCD()
void quda::GaugeCovDev::MdagMCD (ColorSpinorField & out, const ColorSpinorField & in, const int mu) const virtual
Definition at line 38 of file gauge_covdev.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), MCD(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
operator=()
GaugeCovDev & quda::GaugeCovDev::operator= (const GaugeCovDev & covDev)
Definition at line 15 of file gauge_covdev.cpp.
References quda::Dirac::operator=().
prepare()
void quda::GaugeCovDev::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Definition at line 73 of file gauge_covdev.cpp.
reconstruct()
void quda::GaugeCovDev::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Definition at line 80 of file gauge_covdev.cpp.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/gauge_covdev.cpp