QUDA: quda::coeff_type< real, is_variable, Arg > Class Template Reference
quda::coeff_type< real, is_variable, Arg > Class Template Reference
Helper class for grabbing the constant struct, whether we are on the GPU or CPU.
Public Member Functions
__device__ __host__ coeff_type (const Arg &arg)
__device__ __host__ real a (int s)
__device__ __host__ real b (int s)
__device__ __host__ real c (int s)
Public Attributes
const Arg & arg
Detailed Description
template<typename real, bool is_variable, typename Arg>
class quda::coeff_type< real, is_variable, Arg >
Helper class for grabbing the constant struct, whether we are on the GPU or CPU.
Definition at line 39 of file dslash_domain_wall_m5.cuh.
Constructor & Destructor Documentation
coeff_type()
template<typename real, bool is_variable, typename Arg> __device__ __host__ quda::coeff_type< real, is_variable, Arg >::coeff_type (const Arg & arg) inline
Definition at line 43 of file dslash_domain_wall_m5.cuh.
Member Function Documentation
a()
template<typename real, bool is_variable, typename Arg> __device__ __host__ real quda::coeff_type< real, is_variable, Arg >::a (int s) inline
Definition at line 44 of file dslash_domain_wall_m5.cuh.
Referenced by quda::dslash5(), and quda::dslash5inv().
b()
template<typename real, bool is_variable, typename Arg> __device__ __host__ real quda::coeff_type< real, is_variable, Arg >::b (int s) inline
Definition at line 45 of file dslash_domain_wall_m5.cuh.
Referenced by quda::dslash5(), and quda::variableInv().
c()
template<typename real, bool is_variable, typename Arg> __device__ __host__ real quda::coeff_type< real, is_variable, Arg >::c (int s) inline
Definition at line 46 of file dslash_domain_wall_m5.cuh.
Referenced by quda::dslash5(), and quda::variableInv().
Member Data Documentation
arg
template<typename real, bool is_variable, typename Arg> const Arg& quda::coeff_type< real, is_variable, Arg >::arg
Definition at line 42 of file dslash_domain_wall_m5.cuh.
The documentation for this class was generated from the following file:
include/kernels/dslash_domain_wall_m5.cuh