QUDA: quda::TunableVectorY Class Reference
quda::TunableVectorY Class Reference
#include <tune_quda.h>
Public Member Functions
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual TuneKey tuneKey () const =0
virtual void apply (const cudaStream_t &stream)=0
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Protected Member Functions
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual long long flops () const =0
virtual long long bytes () const
virtual unsigned int minThreads () const
virtual bool tuneGridDim () const
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
This derived class is for algorithms that deploy a vector of computations across the y dimension of both the threads block and grid. For example this could be parity in the y dimension and checkerboarded volume in x.
Definition at line 426 of file tune_quda.h.
Constructor & Destructor Documentation
TunableVectorY()
quda::TunableVectorY::TunableVectorY (unsigned int vector_length_y) inline
Definition at line 437 of file tune_quda.h.
Member Function Documentation
advanceBlockDim()
bool quda::TunableVectorY::advanceBlockDim (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Reimplemented in quda::TunableVectorYZ, and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >.
Definition at line 440 of file tune_quda.h.
References quda::Tunable::advanceBlockDim(), quda::TuneParam::block, deviceProp, and quda::TuneParam::grid.
Referenced by quda::TunableVectorYZ::advanceBlockDim().
defaultTuneParam()
void quda::TunableVectorY::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::Tunable.
Reimplemented in quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >, quda::TunableVectorYZ, quda::Pack< Float, nColor, spin_project >, quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >, quda::Dslash5< Float, nColor, Arg >, quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >, and quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >.
Definition at line 474 of file tune_quda.h.
References quda::TuneParam::block, quda::Tunable::defaultTuneParam(), and quda::TuneParam::grid.
Referenced by quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::defaultTuneParam(), and quda::TunableVectorYZ::defaultTuneParam().
initTuneParam()
void quda::TunableVectorY::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Reimplemented in quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >, quda::TunableVectorYZ, quda::Pack< Float, nColor, spin_project >, quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >, quda::Dslash5< Float, nColor, Arg >, quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >, and quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >.
Definition at line 466 of file tune_quda.h.
References quda::TuneParam::block, quda::TuneParam::grid, and quda::Tunable::initTuneParam().
Referenced by quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::initTuneParam(), and quda::TunableVectorYZ::initTuneParam().
resizeStep()
void quda::TunableVectorY::resizeStep (int y) const inline
Definition at line 482 of file tune_quda.h.
Referenced by quda::TunableVectorYZ::resizeStep().
resizeVector()
void quda::TunableVectorY::resizeVector (int y) const inline
Definition at line 481 of file tune_quda.h.
Referenced by quda::TunableVectorYZ::resizeVector().
sharedBytesPerBlock()
virtual unsigned int quda::TunableVectorY::sharedBytesPerBlock (const TuneParam & param) const inline protected virtual
Implements quda::Tunable.
Reimplemented in quda::ProjectSU3< Float, G >, quda::CopyColorSpinor< 4, Arg >, quda::ExtractGhost< nDim, Arg >, quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >, quda::CopyColorSpinor< Ns, Arg >, quda::SpinorNoise< real, Ns, Nc, type, Arg >, and quda::CopyGauge< FloatOut, FloatIn, length, Arg >.
Definition at line 430 of file tune_quda.h.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::sharedBytesPerBlock().
sharedBytesPerThread()
virtual unsigned int quda::TunableVectorY::sharedBytesPerThread () const inline protected virtual
Implements quda::Tunable.
Reimplemented in quda::ProjectSU3< Float, G >, quda::CopyColorSpinor< 4, Arg >, quda::ExtractGhost< nDim, Arg >, quda::CopyColorSpinor< Ns, Arg >, quda::SpinorNoise< real, Ns, Nc, type, Arg >, quda::Dslash5< Float, nColor, Arg >, quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >, and quda::CopyGauge< FloatOut, FloatIn, length, Arg >.
Definition at line 429 of file tune_quda.h.
Member Data Documentation
step_y
unsigned int quda::TunableVectorY::step_y mutable protected
Definition at line 433 of file tune_quda.h.
tune_block_x
bool quda::TunableVectorY::tune_block_x protected
Definition at line 434 of file tune_quda.h.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setComputeType().
vector_length_y
unsigned int quda::TunableVectorY::vector_length_y mutable protected
Definition at line 432 of file tune_quda.h.
The documentation for this class was generated from the following file:
include/tune_quda.h