QUDA: quda::Dirac Class Reference
quda::Dirac Class Reference abstract
#include <dirac_quda.h>
Public Member Functions
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const =0
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const =0
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const =0
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const =0
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const =0
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const =0
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Static Public Member Functions
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Friends
class DiracMatrix
class DiracM
class DiracMdagM
class DiracMMdag
class DiracMdag
Detailed Description
Definition at line 106 of file dirac_quda.h.
Constructor & Destructor Documentation
Dirac() [1/2]
quda::Dirac::Dirac (const DiracParam & param)
Definition at line 12 of file dirac.cpp.
References quda::DiracParam::commDim, and commDim.
Dirac() [2/2]
quda::Dirac::Dirac (const Dirac & dirac)
Definition at line 29 of file dirac.cpp.
References commDim.
~Dirac()
quda::Dirac::~Dirac () virtual
Definition at line 45 of file dirac.cpp.
References getVerbosity(), quda::TimeProfile::Print(), profile, and QUDA_VERBOSE.
Member Function Documentation
checkFullSpinor()
void quda::Dirac::checkFullSpinor (const ColorSpinorField & out, const ColorSpinorField & in) const virtual
Definition at line 146 of file dirac.cpp.
References errorQuda, QUDA_FULL_SITE_SUBSET, and quda::ColorSpinorField::SiteSubset().
Referenced by quda::DiracWilson::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), quda::GaugeLaplace::M(), quda::GaugeCovDev::MCD(), quda::DiracWilson::MdagM(), quda::DiracClover::MdagM(), quda::DiracDomainWall::MdagM(), quda::DiracDomainWall4D::MdagM(), quda::DiracMobius::MdagM(), quda::DiracTwistedMass::MdagM(), quda::DiracTwistedClover::MdagM(), quda::GaugeLaplace::MdagM(), quda::GaugeCovDev::MdagMCD(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWallPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), quda::DiracStaggeredPC::reconstruct(), quda::DiracImprovedStaggeredPC::reconstruct(), quda::DiracCoarsePC::reconstruct(), and quda::GaugeLaplacePC::reconstruct().
checkParitySpinor()
void quda::Dirac::checkParitySpinor (const ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented in quda::DiracImprovedStaggered, quda::DiracStaggered, quda::DiracTwistedClover, and quda::DiracClover.
Definition at line 106 of file dirac.cpp.
References errorQuda, quda::ColorSpinorField::GammaBasis(), gauge, quda::ColorSpinorField::Ndim(), quda::ColorSpinorField::Nspin(), quda::LatticeField::Precision(), QUDA_FULL_SITE_SUBSET, QUDA_PARITY_SITE_SUBSET, QUDA_UKQCD_GAMMA_BASIS, quda::ColorSpinorField::SiteSubset(), quda::ColorSpinorField::Stride(), quda::ColorSpinorField::Volume(), quda::LatticeField::Volume(), quda::LatticeField::VolumeCB(), and quda::ColorSpinorField::X().
Referenced by quda::DiracClover::checkParitySpinor(), quda::DiracTwistedClover::checkParitySpinor(), quda::DiracWilson::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::DiracWilson::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), and quda::DiracTwistedMass::twistedApply().
checkSpinorAlias()
void quda::Dirac::checkSpinorAlias (const ColorSpinorField & a, const ColorSpinorField & b) const
Definition at line 154 of file dirac.cpp.
References errorQuda, and quda::ColorSpinorField::V().
Referenced by quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::GaugeCovDev::DslashCD(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), and quda::GaugeLaplace::DslashXpay().
create()
Dirac * quda::Dirac::create (const DiracParam & param) static
Definition at line 159 of file dirac.cpp.
References errorQuda, getVerbosity(), quda::DiracParam::Ls, printfQuda, QUDA_ASQTAD_DIRAC, QUDA_ASQTADPC_DIRAC, QUDA_CLOVER_DIRAC, QUDA_CLOVERPC_DIRAC, QUDA_COARSE_DIRAC, QUDA_COARSEPC_DIRAC, QUDA_DEBUG_VERBOSE, QUDA_DOMAIN_WALL_4D_DIRAC, QUDA_DOMAIN_WALL_4DPC_DIRAC, QUDA_DOMAIN_WALL_DIRAC, QUDA_DOMAIN_WALLPC_DIRAC, QUDA_GAUGE_COVDEV_DIRAC, QUDA_GAUGE_LAPLACE_DIRAC, QUDA_GAUGE_LAPLACEPC_DIRAC, QUDA_MOBIUS_DOMAIN_WALL_DIRAC, QUDA_MOBIUS_DOMAIN_WALLPC_DIRAC, QUDA_STAGGERED_DIRAC, QUDA_STAGGEREDPC_DIRAC, QUDA_TWISTED_CLOVER_DIRAC, QUDA_TWISTED_CLOVERPC_DIRAC, QUDA_TWISTED_MASS_DIRAC, QUDA_TWISTED_MASSPC_DIRAC, QUDA_WILSON_DIRAC, QUDA_WILSONPC_DIRAC, and quda::DiracParam::type.
Referenced by computeCloverForceQuda(), computeStaggeredForceQuda(), quda::createDirac(), quda::deflated_solver::deflated_solver(), dslashQuda(), init(), MatDagMatQuda(), MatQuda(), quda::multigrid_solver::multigrid_solver(), and updateMultigridQuda().
createCoarseOp()
virtual void quda::Dirac::createCoarseOp (GaugeField & Y, GaugeField & X, const Transfer & T, double kappa, double mass = 0., double mu = 0., double mu_factor = 0.) const inline virtual
Create the coarse operator (virtual parent)
Parameters
Y[out] Coarse link field
X[out] Coarse clover field
T[in] Transfer operator defining the coarse grid
kappa Kappa parameter for the coarse operator
mass Mass parameter for the coarse operator (gets explicitly built into clover, hard coded to zero for non-staggered ops)
mu TM mu parameter for the coarse operator
mu_factor multiplicative factor for the mu parameter
Reimplemented in quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilson.
Definition at line 196 of file dirac_quda.h.
References errorQuda.
Referenced by quda::DiracCoarse::initializeCoarse().
Dagger()
void quda::Dirac::Dagger (QudaDagType dag) const inline
Definition at line 182 of file dirac_quda.h.
Referenced by computeCloverForceQuda().
deleteTmp()
void quda::Dirac::deleteTmp (ColorSpinorField ** a, const bool & reset) const protected
Definition at line 81 of file dirac.cpp.
Referenced by quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracWilsonPC::M(), quda::DiracCloverPC::M(), quda::DiracDomainWallPC::M(), quda::DiracDomainWall4DPC::M(), quda::DiracMobius::M(), quda::DiracMobiusPC::M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedCloverPC::M(), quda::DiracStaggeredPC::M(), quda::DiracImprovedStaggeredPC::M(), quda::DiracCoarsePC::M(), quda::GaugeLaplacePC::M(), quda::DiracWilson::MdagM(), quda::DiracWilsonPC::MdagM(), quda::DiracClover::MdagM(), quda::DiracCloverPC::MdagM(), quda::DiracDomainWall::MdagM(), quda::DiracDomainWallPC::MdagM(), quda::DiracDomainWall4D::MdagM(), quda::DiracDomainWall4DPC::MdagM(), quda::DiracMobius::MdagM(), quda::DiracMobiusPC::MdagM(), quda::DiracTwistedMass::MdagM(), quda::DiracTwistedMassPC::MdagM(), quda::DiracTwistedClover::MdagM(), quda::DiracTwistedCloverPC::MdagM(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::DiracCoarse::MdagM(), quda::DiracCoarsePC::MdagM(), quda::GaugeLaplace::MdagM(), quda::GaugeLaplacePC::MdagM(), quda::GaugeCovDev::MdagMCD(), quda::DiracCloverPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracCoarsePC::prepare(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), and quda::DiracCoarsePC::reconstruct().
Dslash()
virtual void quda::Dirac::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggered, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracDomainWall, quda::DiracCloverPC, and quda::DiracWilson.
Referenced by computeCloverForceQuda(), computeStaggeredForceQuda(), and dslashCUDA().
DslashXpay()
virtual void quda::Dirac::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggered, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilson.
Referenced by quda::MG::verify().
flipDagger()
void quda::Dirac::flipDagger () const inline
Definition at line 183 of file dirac_quda.h.
References QUDA_DAG_NO, and QUDA_DAG_YES.
Referenced by quda::DiracDagger::operator()().
Flops()
unsigned long long quda::Dirac::Flops () const inline
Definition at line 177 of file dirac_quda.h.
References quda::blas::flops.
Referenced by dslashTest(), quda::DiracMatrix::flops(), main(), and TEST_P().
getMatPCType()
QudaMatPCType quda::Dirac::getMatPCType () const inline
Definition at line 180 of file dirac_quda.h.
References quda::DiracParam::matpcType.
Referenced by quda::DiracMatrix::getMatPCType().
getStencilSteps()
int quda::Dirac::getStencilSteps () const
Definition at line 251 of file dirac.cpp.
References errorQuda, QUDA_ASQTAD_DIRAC, QUDA_ASQTADPC_DIRAC, QUDA_CLOVER_DIRAC, QUDA_CLOVERPC_DIRAC, QUDA_COARSE_DIRAC, QUDA_COARSEPC_DIRAC, QUDA_DOMAIN_WALL_4DPC_DIRAC, QUDA_DOMAIN_WALL_DIRAC, QUDA_DOMAIN_WALLPC_DIRAC, QUDA_GAUGE_COVDEV_DIRAC, QUDA_GAUGE_LAPLACE_DIRAC, QUDA_GAUGE_LAPLACEPC_DIRAC, QUDA_MOBIUS_DOMAIN_WALL_DIRAC, QUDA_MOBIUS_DOMAIN_WALLPC_DIRAC, QUDA_STAGGERED_DIRAC, QUDA_STAGGEREDPC_DIRAC, QUDA_TWISTED_CLOVER_DIRAC, QUDA_TWISTED_CLOVERPC_DIRAC, QUDA_TWISTED_MASS_DIRAC, QUDA_TWISTED_MASSPC_DIRAC, QUDA_WILSON_DIRAC, QUDA_WILSONPC_DIRAC, and type.
Referenced by quda::DiracM::getStencilSteps(), quda::DiracMdagM::getStencilSteps(), quda::DiracMMdag::getStencilSteps(), and quda::DiracMdag::getStencilSteps().
HaloPrecision()
QudaPrecision quda::Dirac::HaloPrecision () const inline
Definition at line 200 of file dirac_quda.h.
References quda::DiracParam::halo_precision.
Referenced by quda::MG::generateNullVectors().
Kappa()
double quda::Dirac::Kappa () const inline
Definition at line 173 of file dirac_quda.h.
References quda::DiracParam::kappa.
Referenced by quda::MG::createCoarseDirac(), and quda::MG::verify().
M()
virtual void quda::Dirac::M (ColorSpinorField & out, const ColorSpinorField & in) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplacePC, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggeredPC, quda::DiracImprovedStaggered, quda::DiracStaggeredPC, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, quda::DiracWilsonPC, and quda::DiracWilson.
Referenced by computeCloverForceQuda(), quda::EigenSolver::computeSVD(), dslashCUDA(), MatQuda(), Mdag(), quda::CGNE::operator()(), quda::CGNR::operator()(), quda::CACGNE::operator()(), quda::CACGNR::operator()(), and quda::DiracM::operator()().
Mdag()
void quda::Dirac::Mdag (ColorSpinorField & out, const ColorSpinorField & in) const
Definition at line 90 of file dirac.cpp.
References dagger, flip, and M().
Referenced by invertMultiSrcQuda(), invertQuda(), quda::DiracWilson::MdagM(), quda::DiracWilsonPC::MdagM(), quda::DiracClover::MdagM(), quda::DiracCloverPC::MdagM(), quda::DiracDomainWall::MdagM(), quda::DiracDomainWallPC::MdagM(), quda::DiracDomainWall4D::MdagM(), quda::DiracDomainWall4DPC::MdagM(), quda::DiracMobius::MdagM(), quda::DiracMobiusPC::MdagM(), quda::DiracTwistedMass::MdagM(), quda::DiracTwistedMassPC::MdagM(), quda::DiracTwistedClover::MdagM(), quda::DiracTwistedCloverPC::MdagM(), quda::DiracCoarse::MdagM(), quda::DiracCoarsePC::MdagM(), quda::GaugeLaplace::MdagM(), quda::GaugeLaplacePC::MdagM(), quda::CGNE::operator()(), quda::CGNR::operator()(), quda::CACGNE::operator()(), quda::CACGNR::operator()(), and quda::DiracMdag::operator()().
MdagM()
virtual void quda::Dirac::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplacePC, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggeredPC, quda::DiracImprovedStaggered, quda::DiracStaggeredPC, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, quda::DiracWilsonPC, and quda::DiracWilson.
Referenced by dslashCUDA(), MatDagMatQuda(), MMdag(), quda::DiracMdagM::operator()(), and quda::MG::verify().
MMdag()
void quda::Dirac::MMdag (ColorSpinorField & out, const ColorSpinorField & in) const
Definition at line 97 of file dirac.cpp.
References dagger, flip, and MdagM().
Referenced by quda::DiracMMdag::operator()().
Mu()
virtual double quda::Dirac::Mu () const inline virtual
Reimplemented in quda::DiracCoarse, quda::DiracTwistedClover, and quda::DiracTwistedMass.
Definition at line 174 of file dirac_quda.h.
Referenced by quda::MG::createCoarseDirac(), and quda::MG::verify().
MuFactor()
virtual double quda::Dirac::MuFactor () const inline virtual
Reimplemented in quda::DiracCoarse.
Definition at line 175 of file dirac_quda.h.
newTmp()
bool quda::Dirac::newTmp (ColorSpinorField ** tmp, const ColorSpinorField & a) const protected
Definition at line 70 of file dirac.cpp.
References quda::ColorSpinorParam::create, param, and QUDA_ZERO_FIELD_CREATE.
Referenced by quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracWilsonPC::M(), quda::DiracCloverPC::M(), quda::DiracDomainWallPC::M(), quda::DiracDomainWall4DPC::M(), quda::DiracMobius::M(), quda::DiracMobiusPC::M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedCloverPC::M(), quda::DiracStaggeredPC::M(), quda::DiracImprovedStaggeredPC::M(), quda::DiracCoarsePC::M(), quda::GaugeLaplacePC::M(), quda::DiracWilson::MdagM(), quda::DiracWilsonPC::MdagM(), quda::DiracClover::MdagM(), quda::DiracCloverPC::MdagM(), quda::DiracDomainWall::MdagM(), quda::DiracDomainWallPC::MdagM(), quda::DiracDomainWall4D::MdagM(), quda::DiracDomainWall4DPC::MdagM(), quda::DiracMobius::MdagM(), quda::DiracMobiusPC::MdagM(), quda::DiracTwistedMass::MdagM(), quda::DiracTwistedMassPC::MdagM(), quda::DiracTwistedClover::MdagM(), quda::DiracTwistedCloverPC::MdagM(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::DiracCoarse::MdagM(), quda::DiracCoarsePC::MdagM(), quda::GaugeLaplace::MdagM(), quda::GaugeLaplacePC::MdagM(), quda::GaugeCovDev::MdagMCD(), quda::DiracCloverPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracCoarsePC::prepare(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), and quda::DiracCoarsePC::reconstruct().
operator=()
Dirac & quda::Dirac::operator= (const Dirac & dirac)
Definition at line 49 of file dirac.cpp.
References commDim, dagger, errorQuda, flops, gauge, kappa, laplace3D, matpcType, profile, tmp1, tmp2, and type.
Referenced by quda::DiracWilson::operator=(), quda::DiracStaggered::operator=(), quda::DiracImprovedStaggered::operator=(), quda::GaugeLaplace::operator=(), and quda::GaugeCovDev::operator=().
prepare()
virtual void quda::Dirac::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplacePC, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggeredPC, quda::DiracImprovedStaggered, quda::DiracStaggeredPC, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, quda::DiracWilsonPC, and quda::DiracWilson.
Referenced by quda::MG::generateNullVectors(), invertMultiSrcQuda(), invertQuda(), quda::MG::operator()(), and quda::PreconditionedSolver::operator()().
reconstruct()
virtual void quda::Dirac::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType) const pure virtual
Implemented in quda::GaugeCovDev, quda::GaugeLaplacePC, quda::GaugeLaplace, quda::DiracCoarsePC, quda::DiracCoarse, quda::DiracImprovedStaggeredPC, quda::DiracImprovedStaggered, quda::DiracStaggeredPC, quda::DiracStaggered, quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, quda::DiracWilsonPC, and quda::DiracWilson.
Referenced by quda::MG::generateNullVectors(), invertMultiSrcQuda(), invertQuda(), quda::MG::operator()(), and quda::PreconditionedSolver::operator()().
setCommDim()
void quda::Dirac::setCommDim (const int commDim_[QUDA_MAX_DIM]) const inline
Enable / disable communications for the Dirac operator.
Parameters
[in] commDim_ Array of booleans which determines whether communications are enabled
Definition at line 145 of file dirac_quda.h.
References in, out, parity, and QUDA_MAX_DIM.
Referenced by quda::MG::generateNullVectors().
setHaloPrecision()
void quda::Dirac::setHaloPrecision (QudaPrecision halo_precision_) const inline
Definition at line 201 of file dirac_quda.h.
Referenced by quda::MG::generateNullVectors().
setMass()
void quda::Dirac::setMass (double mass) inline
Definition at line 169 of file dirac_quda.h.
References quda::DiracParam::mass, and param.
Referenced by invertMultiShiftQuda().
Friends And Related Function Documentation
DiracM
friend class DiracM friend
Definition at line 109 of file dirac_quda.h.
DiracMatrix
friend class DiracMatrix friend
Definition at line 108 of file dirac_quda.h.
DiracMdag
friend class DiracMdag friend
Definition at line 112 of file dirac_quda.h.
DiracMdagM
friend class DiracMdagM friend
Definition at line 110 of file dirac_quda.h.
DiracMMdag
friend class DiracMMdag friend
Definition at line 111 of file dirac_quda.h.
Member Data Documentation
commDim
int quda::Dirac::commDim[QUDA_MAX_DIM] mutable protected
Definition at line 130 of file dirac_quda.h.
Referenced by quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), Dirac(), quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::DiracImprovedStaggered::Dslash(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::DiracImprovedStaggered::DslashXpay(), quda::DiracCoarse::DslashXpay(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), quda::DiracCoarse::M(), and operator=().
dagger
QudaDagType quda::Dirac::dagger mutable protected
Definition at line 120 of file dirac_quda.h.
Referenced by quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::DiracImprovedStaggered::Dslash(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::GaugeCovDev::DslashCD(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::DiracImprovedStaggered::DslashXpay(), quda::DiracCoarse::DslashXpay(), quda::GaugeLaplace::DslashXpay(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracCloverPC::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracDomainWall4DPC::M(), quda::DiracMobius::M(), quda::DiracMobiusPC::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracTwistedCloverPC::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), quda::DiracCoarse::M(), Mdag(), MMdag(), operator=(), quda::DiracTwistedMass::twistedApply(), and quda::DiracTwistedClover::twistedCloverApply().
flops
unsigned long long quda::Dirac::flops mutable protected
Definition at line 121 of file dirac_quda.h.
Referenced by quda::DiracClover::Clover(), quda::DiracCoarse::Clover(), quda::DiracCloverPC::CloverInv(), quda::DiracCoarse::CloverInv(), quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::DiracImprovedStaggered::Dslash(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::GaugeCovDev::DslashCD(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::DiracImprovedStaggered::DslashXpay(), quda::DiracCoarse::DslashXpay(), quda::DiracCoarsePC::DslashXpay(), quda::GaugeLaplace::DslashXpay(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), quda::DiracCoarse::M(), operator=(), quda::DiracTwistedMass::twistedApply(), and quda::DiracTwistedClover::twistedCloverApply().
gauge
cudaGaugeField* quda::Dirac::gauge protected
Definition at line 115 of file dirac_quda.h.
Referenced by checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracWilson::createCoarseOp(), quda::DiracClover::createCoarseOp(), quda::DiracCloverPC::createCoarseOp(), quda::DiracTwistedMass::createCoarseOp(), quda::DiracTwistedMassPC::createCoarseOp(), quda::DiracTwistedClover::createCoarseOp(), quda::DiracTwistedCloverPC::createCoarseOp(), quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::GaugeCovDev::DslashCD(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::GaugeLaplace::DslashXpay(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), and operator=().
halo_precision
QudaPrecision quda::Dirac::halo_precision mutable protected
Definition at line 125 of file dirac_quda.h.
Referenced by quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracCoarse::DslashXpay(), and quda::DiracCoarse::M().
kappa
double quda::Dirac::kappa protected
Definition at line 116 of file dirac_quda.h.
Referenced by quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracCoarse::DslashXpay(), quda::DiracCoarse::initializeCoarse(), quda::DiracWilson::M(), quda::DiracWilsonPC::M(), quda::DiracClover::M(), quda::DiracCloverPC::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedClover::M(), quda::DiracTwistedCloverPC::M(), quda::DiracCoarse::M(), quda::GaugeLaplace::M(), quda::GaugeLaplacePC::M(), operator=(), quda::DiracWilsonPC::prepare(), quda::DiracCloverPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::GaugeLaplacePC::prepare(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), quda::GaugeLaplacePC::reconstruct(), quda::DiracTwistedMass::twistedApply(), and quda::DiracTwistedClover::twistedCloverApply().
laplace3D
int quda::Dirac::laplace3D protected
Definition at line 118 of file dirac_quda.h.
Referenced by quda::GaugeLaplace::Dslash(), quda::GaugeLaplace::DslashXpay(), and operator=().
mass
double quda::Dirac::mass protected
Definition at line 117 of file dirac_quda.h.
Referenced by quda::DiracDomainWall::Dslash(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracCoarse::initializeCoarse(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracStaggered::M(), quda::DiracStaggeredPC::M(), quda::DiracImprovedStaggered::M(), quda::DiracImprovedStaggeredPC::M(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::DiracStaggeredPC::prepare(), quda::DiracImprovedStaggeredPC::prepare(), quda::DiracStaggeredPC::reconstruct(), and quda::DiracImprovedStaggeredPC::reconstruct().
matpcType
QudaMatPCType quda::Dirac::matpcType protected
Definition at line 119 of file dirac_quda.h.
Referenced by quda::DiracCloverPC::createCoarseOp(), quda::DiracTwistedMassPC::createCoarseOp(), quda::DiracTwistedCloverPC::createCoarseOp(), quda::DiracCoarsePC::createCoarseOp(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracWilsonPC::M(), quda::DiracCloverPC::M(), quda::DiracDomainWallPC::M(), quda::DiracDomainWall4DPC::M(), quda::DiracMobiusPC::M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedCloverPC::M(), quda::DiracStaggeredPC::M(), quda::DiracImprovedStaggeredPC::M(), quda::DiracCoarsePC::M(), quda::GaugeLaplacePC::M(), operator=(), quda::DiracWilsonPC::prepare(), quda::DiracCloverPC::prepare(), quda::DiracDomainWallPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracStaggeredPC::prepare(), quda::DiracImprovedStaggeredPC::prepare(), quda::DiracCoarsePC::prepare(), quda::GaugeLaplacePC::prepare(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWallPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), quda::DiracStaggeredPC::reconstruct(), quda::DiracImprovedStaggeredPC::reconstruct(), quda::DiracCoarsePC::reconstruct(), and quda::GaugeLaplacePC::reconstruct().
profile
TimeProfile quda::Dirac::profile mutable protected
Definition at line 132 of file dirac_quda.h.
Referenced by quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::DiracImprovedStaggered::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::GaugeCovDev::DslashCD(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::DiracImprovedStaggered::DslashXpay(), quda::GaugeLaplace::DslashXpay(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), operator=(), and ~Dirac().
tmp1
ColorSpinorField* quda::Dirac::tmp1 mutable protected
Definition at line 122 of file dirac_quda.h.
Referenced by quda::DiracWilsonPC::M(), quda::DiracCloverPC::M(), quda::DiracDomainWallPC::M(), quda::DiracDomainWall4DPC::M(), quda::DiracMobiusPC::M(), quda::DiracTwistedMassPC::M(), quda::DiracTwistedCloverPC::M(), quda::DiracStaggeredPC::M(), quda::DiracImprovedStaggeredPC::M(), quda::DiracCoarsePC::M(), quda::GaugeLaplacePC::M(), quda::DiracWilson::MdagM(), quda::DiracClover::MdagM(), quda::DiracDomainWall::MdagM(), quda::DiracDomainWall4D::MdagM(), quda::DiracMobius::MdagM(), quda::DiracTwistedMass::MdagM(), quda::DiracTwistedClover::MdagM(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::DiracCoarse::MdagM(), quda::GaugeLaplace::MdagM(), quda::GaugeCovDev::MdagMCD(), quda::DiracM::operator()(), quda::DiracMdagM::operator()(), quda::DiracMMdag::operator()(), quda::DiracMdag::operator()(), operator=(), quda::DiracCloverPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracCoarsePC::prepare(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), and quda::DiracCoarsePC::reconstruct().
tmp2
ColorSpinorField* quda::Dirac::tmp2 mutable protected
Definition at line 123 of file dirac_quda.h.
Referenced by quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracMobius::M(), quda::DiracWilsonPC::MdagM(), quda::DiracCloverPC::MdagM(), quda::DiracDomainWallPC::MdagM(), quda::DiracDomainWall4DPC::MdagM(), quda::DiracMobiusPC::MdagM(), quda::DiracTwistedMassPC::MdagM(), quda::DiracTwistedCloverPC::MdagM(), quda::DiracCoarsePC::MdagM(), quda::GaugeLaplacePC::MdagM(), quda::DiracM::operator()(), quda::DiracMdagM::operator()(), quda::DiracMMdag::operator()(), quda::DiracMdag::operator()(), and operator=().
type
QudaDiracType quda::Dirac::type protected
Definition at line 124 of file dirac_quda.h.
Referenced by getStencilSteps(), and operator=().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac.cpp