QUDA: quda::CopyGauge< FloatOut, FloatIn, length, Arg > Class Template Reference
quda::CopyGauge< FloatOut, FloatIn, length, Arg > Class Template Reference
Public Member Functions
CopyGauge (Arg &arg, const GaugeField &out, const GaugeField &in, QudaFieldLocation location)
void set_ghost (int is_ghost_)
virtual ~CopyGauge ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
bool advanceTuneParam (TuneParam &param) const
Private Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
Arg arg
int size
const GaugeField & meta
QudaFieldLocation location
bool is_ghost
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename FloatOut, typename FloatIn, int length, typename Arg>
class quda::CopyGauge< FloatOut, FloatIn, length, Arg >
Definition at line 11 of file copy_gauge_helper.cuh.
Constructor & Destructor Documentation
CopyGauge()
template<typename FloatOut, typename FloatIn, int length, typename Arg> quda::CopyGauge< FloatOut, FloatIn, length, Arg >::CopyGauge (Arg & arg, const GaugeField & out, const GaugeField & in, QudaFieldLocation location) inline
Definition at line 31 of file copy_gauge_helper.cuh.
References quda::LatticeField::AuxString(), and quda::compile_type_str().
~CopyGauge()
template<typename FloatOut, typename FloatIn, int length, typename Arg> virtual quda::CopyGauge< FloatOut, FloatIn, length, Arg >::~CopyGauge () inline virtual
Definition at line 80 of file copy_gauge_helper.cuh.
Member Function Documentation
advanceTuneParam()
template<typename FloatOut, typename FloatIn, int length, typename Arg> bool quda::CopyGauge< FloatOut, FloatIn, length, Arg >::advanceTuneParam (TuneParam & param) const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 25 of file copy_gauge_helper.cuh.
References quda::Tunable::advanceTuneParam(), and QUDA_CUDA_FIELD_LOCATION.
apply()
template<typename FloatOut, typename FloatIn, int length, typename Arg> void quda::CopyGauge< FloatOut, FloatIn, length, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 82 of file copy_gauge_helper.cuh.
References quda::arg(), quda::TuneParam::block, errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, length, QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::copyGauge(), and quda::copyMom().
bytes()
template<typename FloatOut, typename FloatIn, int length, typename Arg> long long quda::CopyGauge< FloatOut, FloatIn, length, Arg >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 118 of file copy_gauge_helper.cuh.
flops()
template<typename FloatOut, typename FloatIn, int length, typename Arg> long long quda::CopyGauge< FloatOut, FloatIn, length, Arg >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 117 of file copy_gauge_helper.cuh.
minThreads()
template<typename FloatOut, typename FloatIn, int length, typename Arg> unsigned int quda::CopyGauge< FloatOut, FloatIn, length, Arg >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 23 of file copy_gauge_helper.cuh.
References quda::size.
set_ghost()
template<typename FloatOut, typename FloatIn, int length, typename Arg> void quda::CopyGauge< FloatOut, FloatIn, length, Arg >::set_ghost (int is_ghost_) inline
Definition at line 61 of file copy_gauge_helper.cuh.
References errorQuda, quda::GaugeField::Geometry(), length, quda::gauge::Ncolor(), and quda::LatticeField::Ndim().
Referenced by quda::copyGauge().
sharedBytesPerBlock()
template<typename FloatOut, typename FloatIn, int length, typename Arg> unsigned int quda::CopyGauge< FloatOut, FloatIn, length, Arg >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 20 of file copy_gauge_helper.cuh.
sharedBytesPerThread()
template<typename FloatOut, typename FloatIn, int length, typename Arg> unsigned int quda::CopyGauge< FloatOut, FloatIn, length, Arg >::sharedBytesPerThread () const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 19 of file copy_gauge_helper.cuh.
tuneGridDim()
template<typename FloatOut, typename FloatIn, int length, typename Arg> bool quda::CopyGauge< FloatOut, FloatIn, length, Arg >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 22 of file copy_gauge_helper.cuh.
tuneKey()
template<typename FloatOut, typename FloatIn, int length, typename Arg> TuneKey quda::CopyGauge< FloatOut, FloatIn, length, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 110 of file copy_gauge_helper.cuh.
References quda::TuneKey::aux_n, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename FloatOut, typename FloatIn, int length, typename Arg> Arg quda::CopyGauge< FloatOut, FloatIn, length, Arg >::arg private
Definition at line 12 of file copy_gauge_helper.cuh.
is_ghost
template<typename FloatOut, typename FloatIn, int length, typename Arg> bool quda::CopyGauge< FloatOut, FloatIn, length, Arg >::is_ghost private
Definition at line 16 of file copy_gauge_helper.cuh.
location
template<typename FloatOut, typename FloatIn, int length, typename Arg> QudaFieldLocation quda::CopyGauge< FloatOut, FloatIn, length, Arg >::location private
Definition at line 15 of file copy_gauge_helper.cuh.
meta
template<typename FloatOut, typename FloatIn, int length, typename Arg> const GaugeField& quda::CopyGauge< FloatOut, FloatIn, length, Arg >::meta private
Definition at line 14 of file copy_gauge_helper.cuh.
size
template<typename FloatOut, typename FloatIn, int length, typename Arg> int quda::CopyGauge< FloatOut, FloatIn, length, Arg >::size private
Definition at line 13 of file copy_gauge_helper.cuh.
The documentation for this class was generated from the following file:
lib/copy_gauge_helper.cuh