QUDA: quda::GaugePlaq< Float, Gauge > Class Template Reference
quda::GaugePlaq< Float, Gauge > Class Template Reference
Public Member Functions
GaugePlaq (GaugePlaqArg< Gauge > &arg, const GaugeField &meta)
~GaugePlaq ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
bool tuneGridDim () const
Private Member Functions inherited from quda::TunableLocalParity
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
unsigned int maxBlockSize (const TuneParam &param) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual unsigned int minThreads () const
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
GaugePlaqArg< Gauge > arg
const GaugeField & meta
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, typename Gauge>
class quda::GaugePlaq< Float, Gauge >
Definition at line 9 of file gauge_plaq.cu.
Constructor & Destructor Documentation
GaugePlaq()
template<typename Float, typename Gauge> quda::GaugePlaq< Float, Gauge >::GaugePlaq (GaugePlaqArg< Gauge > & arg, const GaugeField & meta) inline
Definition at line 18 of file gauge_plaq.cu.
References quda::Tunable::aux, and quda::compile_type_str().
~GaugePlaq()
template<typename Float, typename Gauge> quda::GaugePlaq< Float, Gauge >::~GaugePlaq () inline
Definition at line 26 of file gauge_plaq.cu.
Member Function Documentation
apply()
template<typename Float, typename Gauge> void quda::GaugePlaq< Float, Gauge >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 28 of file gauge_plaq.cu.
References quda::TuneParam::block, quda::computePlaq(), errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::Tunable::jitify_error, LAUNCH_KERNEL_LOCAL_PARITY, quda::LatticeField::Location(), QUDA_CUDA_FIELD_LOCATION, quda::ReduceArg< double2 >::result_h, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::plaquette().
bytes()
template<typename Float, typename Gauge> long long quda::GaugePlaq< Float, Gauge >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 47 of file gauge_plaq.cu.
References quda::GaugePlaqArg< Gauge >::dataOr, and quda::GaugePlaqArg< Gauge >::threads.
flops()
template<typename Float, typename Gauge> long long quda::GaugePlaq< Float, Gauge >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 46 of file gauge_plaq.cu.
References quda::GaugePlaqArg< Gauge >::threads.
tuneGridDim()
template<typename Float, typename Gauge> bool quda::GaugePlaq< Float, Gauge >::tuneGridDim () const inline private virtual
Reimplemented from quda::TunableLocalParity.
Definition at line 15 of file gauge_plaq.cu.
tuneKey()
template<typename Float, typename Gauge> TuneKey quda::GaugePlaq< Float, Gauge >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 45 of file gauge_plaq.cu.
References quda::Tunable::aux, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, typename Gauge> GaugePlaqArg<Gauge> quda::GaugePlaq< Float, Gauge >::arg private
Definition at line 11 of file gauge_plaq.cu.
Referenced by quda::plaquette().
meta
template<typename Float, typename Gauge> const GaugeField& quda::GaugePlaq< Float, Gauge >::meta private
Definition at line 12 of file gauge_plaq.cu.
The documentation for this class was generated from the following file:
lib/gauge_plaq.cu