QUDA: quda::QudaMemCopy Class Reference
quda::QudaMemCopy Class Reference
Public Member Functions
QudaMemCopy (void *dst, const void *src, size_t count, cudaMemcpyKind kind, bool async, const char *func, const char *file, const char *line)
virtual ~QudaMemCopy ()
void apply (const cudaStream_t &stream)
bool advanceTuneParam (TuneParam &param) const
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Attributes
void * dst
const void * src
const size_t count
const cudaMemcpyKind kind
const bool async
const char * name
Additional Inherited Members
Protected Member Functions inherited from quda::Tunable
virtual unsigned int minThreads () const
virtual bool tuneGridDim () const
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
Definition at line 29 of file quda_cuda_api.cpp.
Constructor & Destructor Documentation
QudaMemCopy()
quda::QudaMemCopy::QudaMemCopy (void * dst, const void * src, size_t count, cudaMemcpyKind kind, bool async, const char * func, const char * file, const char * line) inline
Definition at line 42 of file quda_cuda_api.cpp.
References quda::Tunable::aux, and errorQuda.
~QudaMemCopy()
virtual quda::QudaMemCopy::~QudaMemCopy () inline virtual
Definition at line 72 of file quda_cuda_api.cpp.
Member Function Documentation
advanceTuneParam()
bool quda::QudaMemCopy::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 112 of file quda_cuda_api.cpp.
apply()
void quda::QudaMemCopy::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 74 of file quda_cuda_api.cpp.
References errorQuda, getTuning(), getVerbosity(), PROFILE, quda::QUDA_PROFILE_MEMCPY_D2D_ASYNC, quda::QUDA_PROFILE_MEMCPY_D2H_ASYNC, quda::QUDA_PROFILE_MEMCPY_H2D_ASYNC, and quda::tuneLaunch().
Referenced by quda::qudaMemcpy_(), and quda::qudaMemcpyAsync_().
bytes()
long long quda::QudaMemCopy::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 122 of file quda_cuda_api.cpp.
References count.
flops()
long long quda::QudaMemCopy::flops () const inline virtual
Implements quda::Tunable.
Definition at line 121 of file quda_cuda_api.cpp.
sharedBytesPerBlock()
unsigned int quda::QudaMemCopy::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 39 of file quda_cuda_api.cpp.
sharedBytesPerThread()
unsigned int quda::QudaMemCopy::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 38 of file quda_cuda_api.cpp.
tuneKey()
TuneKey quda::QudaMemCopy::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 114 of file quda_cuda_api.cpp.
References quda::Tunable::aux, and quda::u64toa().
Member Data Documentation
async
const bool quda::QudaMemCopy::async private
Definition at line 35 of file quda_cuda_api.cpp.
count
const size_t quda::QudaMemCopy::count private
Definition at line 33 of file quda_cuda_api.cpp.
Referenced by bytes().
dst
void* quda::QudaMemCopy::dst private
Definition at line 31 of file quda_cuda_api.cpp.
Referenced by quda::qudaMemcpy2DAsync_().
kind
const cudaMemcpyKind quda::QudaMemCopy::kind private
Definition at line 34 of file quda_cuda_api.cpp.
name
const char* quda::QudaMemCopy::name private
Definition at line 36 of file quda_cuda_api.cpp.
src
const void* quda::QudaMemCopy::src private
Definition at line 32 of file quda_cuda_api.cpp.
The documentation for this class was generated from the following file:
lib/quda_cuda_api.cpp