QUDA: quda::DslashCoarsePolicyTune Class Reference
quda::DslashCoarsePolicyTune Class Reference
Public Member Functions
DslashCoarsePolicyTune (DslashCoarseLaunch &dslash)
virtual ~DslashCoarsePolicyTune ()
void apply (const cudaStream_t &stream)
int tuningIter () const
bool advanceAux (TuneParam &param) const
bool advanceTuneParam (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
bool tuneGridDim () const
bool tuneAuxDim () const
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Attributes
DslashCoarseLaunch & dslash
Additional Inherited Members
Protected Member Functions inherited from quda::Tunable
virtual unsigned int minThreads () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
Definition at line 610 of file dslash_coarse.cu.
Constructor & Destructor Documentation
DslashCoarsePolicyTune()
quda::DslashCoarsePolicyTune::DslashCoarsePolicyTune (DslashCoarseLaunch & dslash) inline
Definition at line 620 of file dslash_coarse.cu.
References quda::LatticeField::AuxString(), quda::DslashCoarseLaunch::clover, comm_config_string(), comm_dim_partitioned_string(), comm_dim_topology_string(), comm_gdr_enabled(), quda::DslashCoarseLaunch::commDim, quda::disableProfileCount(), quda::DslashCoarseLaunch::dslash, quda::DSLASH_COARSE_BASIC, quda::DSLASH_COARSE_GDR, quda::DSLASH_COARSE_GDR_RECV, quda::DSLASH_COARSE_GDR_SEND, quda::DSLASH_COARSE_GDR_SEND_ZERO_COPY_READ, quda::DSLASH_COARSE_POLICY_DISABLED, quda::DSLASH_COARSE_ZERO_COPY, quda::DSLASH_COARSE_ZERO_COPY_PACK, quda::DSLASH_COARSE_ZERO_COPY_PACK_GDR_RECV, quda::DSLASH_COARSE_ZERO_COPY_READ, quda::enable_policy(), quda::enableProfileCount(), quda::blas::end(), errorQuda, quda::first_active_policy, quda::getTuneCache(), getTuning(), quda::DslashCoarseLaunch::halo_precision, quda::i32toa(), quda::DslashCoarseLaunch::inA, quda::policies(), prec_str, quda::LatticeField::Precision(), quda::setPolicyTuning(), and quda::DslashCoarseLaunch::Y.
~DslashCoarsePolicyTune()
virtual quda::DslashCoarsePolicyTune::~DslashCoarsePolicyTune () inline virtual
Definition at line 703 of file dslash_coarse.cu.
References quda::setPolicyTuning().
Member Function Documentation
advanceAux()
bool quda::DslashCoarsePolicyTune::advanceAux (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 715 of file dslash_coarse.cu.
References quda::TuneParam::aux, quda::DSLASH_COARSE_POLICY_DISABLED, and quda::policies().
advanceTuneParam()
bool quda::DslashCoarsePolicyTune::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 725 of file dslash_coarse.cu.
apply()
void quda::DslashCoarsePolicyTune::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 705 of file dslash_coarse.cu.
References quda::TuneParam::aux, quda::DSLASH_COARSE_POLICY_DISABLED, errorQuda, getTuning(), getVerbosity(), quda::policies(), and quda::tuneLaunch().
Referenced by quda::ApplyCoarse().
bytes()
long long quda::DslashCoarsePolicyTune::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 756 of file dslash_coarse.cu.
References quda::GaugeField::Bytes(), quda::ColorSpinorField::Bytes(), quda::DslashCoarseLaunch::clover, quda::DslashCoarseLaunch::dslash, quda::DslashCoarseLaunch::inA, quda::DslashCoarseLaunch::inB, quda::DslashCoarseLaunch::out, quda::ColorSpinorField::SiteSubset(), quda::LatticeField::Stride(), quda::LatticeField::VolumeCB(), quda::DslashCoarseLaunch::X, and quda::DslashCoarseLaunch::Y.
defaultTuneParam()
void quda::DslashCoarsePolicyTune::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::Tunable.
Definition at line 735 of file dslash_coarse.cu.
References quda::TuneParam::aux, quda::Tunable::defaultTuneParam(), and quda::first_active_policy.
flops()
long long quda::DslashCoarsePolicyTune::flops () const inline virtual
Implements quda::Tunable.
Definition at line 747 of file dslash_coarse.cu.
References quda::DslashCoarseLaunch::clover, quda::DslashCoarseLaunch::dslash, quda::DslashCoarseLaunch::inA, quda::ColorSpinorField::Ncolor(), quda::ColorSpinorField::Nspin(), quda::ColorSpinorField::SiteSubset(), volumeCB, and quda::ColorSpinorField::VolumeCB().
initTuneParam()
void quda::DslashCoarsePolicyTune::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 727 of file dslash_coarse.cu.
References quda::TuneParam::aux, quda::first_active_policy, and quda::Tunable::initTuneParam().
sharedBytesPerBlock()
unsigned int quda::DslashCoarsePolicyTune::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 617 of file dslash_coarse.cu.
sharedBytesPerThread()
unsigned int quda::DslashCoarsePolicyTune::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 616 of file dslash_coarse.cu.
tuneAuxDim()
bool quda::DslashCoarsePolicyTune::tuneAuxDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 615 of file dslash_coarse.cu.
tuneGridDim()
bool quda::DslashCoarsePolicyTune::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 614 of file dslash_coarse.cu.
tuneKey()
TuneKey quda::DslashCoarsePolicyTune::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 743 of file dslash_coarse.cu.
References quda::DslashCoarseLaunch::inA, and quda::LatticeField::VolString().
tuningIter()
int quda::DslashCoarsePolicyTune::tuningIter () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 713 of file dslash_coarse.cu.
Member Data Documentation
dslash
DslashCoarseLaunch& quda::DslashCoarsePolicyTune::dslash private
Definition at line 612 of file dslash_coarse.cu.
The documentation for this class was generated from the following file:
lib/dslash_coarse.cu