QUDA: quda::DiracMobius Class Reference
quda::DiracMobius Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracMobius (const DiracParam &param)
DiracMobius (const DiracMobius &dirac)
virtual ~DiracMobius ()
DiracMobius & operator= (const DiracMobius &dirac)
void Dslash4 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash4pre (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash4Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash4preXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash5Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracDomainWall
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Attributes
Complex b_5 [QUDA_MAX_DWF_LS]
Complex c_5 [QUDA_MAX_DWF_LS]
bool zMobius
Protected Attributes inherited from quda::DiracDomainWall
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracDomainWall
void checkDWF (const ColorSpinorField &out, const ColorSpinorField &in) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Detailed Description
Definition at line 449 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMobius() [1/2]
quda::DiracMobius::DiracMobius (const DiracParam & param)
Definition at line 7 of file dirac_mobius.cpp.
References quda::DiracParam::b_5, b_5, quda::DiracParam::c_5, c_5, getVerbosity(), quda::DiracParam::Ls, quda::DiracDomainWall::Ls, printfQuda, QUDA_VERBOSE, and zMobius.
DiracMobius() [2/2]
quda::DiracMobius::DiracMobius (const DiracMobius & dirac)
Definition at line 27 of file dirac_mobius.cpp.
References b_5, c_5, and quda::DiracDomainWall::Ls.
~DiracMobius()
quda::DiracMobius::~DiracMobius () virtual
Definition at line 33 of file dirac_mobius.cpp.
Member Function Documentation
Dslash4()
void quda::DiracMobius::Dslash4 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 48 of file dirac_mobius.cpp.
References quda::ApplyDomainWall4D(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by dslashCUDA(), dslashQuda_mdwf(), and quda::DiracMobiusPC::M().
Dslash4pre()
void quda::DiracMobius::Dslash4pre (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 60 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), b_5, c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_MOBIUS_PRE, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by dslashCUDA(), dslashQuda_mdwf(), quda::DiracMobiusPC::M(), quda::DiracMobiusPC::prepare(), and quda::DiracMobiusPC::reconstruct().
Dslash4preXpay()
void quda::DiracMobius::Dslash4preXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 102 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), b_5, c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_MOBIUS_PRE, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracMobiusPC::M().
Dslash4Xpay()
void quda::DiracMobius::Dslash4Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 90 of file dirac_mobius.cpp.
References quda::ApplyDomainWall4D(), b_5, c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::DiracDomainWall::m5, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracMobiusPC::prepare(), and quda::DiracMobiusPC::reconstruct().
Dslash5()
void quda::DiracMobius::Dslash5 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 75 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), b_5, c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_MOBIUS, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracMobiusPC::Dslash5inv(), dslashCUDA(), and dslashQuda_mdwf().
Dslash5Xpay()
void quda::DiracMobius::Dslash5Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 118 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), b_5, c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_MOBIUS, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracMobiusPC::M().
M()
void quda::DiracMobius::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracMobiusPC.
Definition at line 133 of file dirac_mobius.cpp.
References quda::ApplyDomainWall4D(), quda::ApplyDslash5(), quda::blas::axpy(), b_5, c_5, quda::Dirac::checkFullSpinor(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::deleteTmp(), quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, quda::Dirac::flops, quda::Dirac::gauge, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::Dirac::mass, quda::Dirac::newTmp(), quda::Dirac::profile, QUDA_FULL_SITE_SUBSET, QUDA_INVALID_PARITY, quda::ColorSpinorField::SiteSubset(), tmp, quda::Dirac::tmp2, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by MdagM().
MdagM()
void quda::DiracMobius::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracMobiusPC.
Definition at line 161 of file dirac_mobius.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
operator=()
DiracMobius & quda::DiracMobius::operator= (const DiracMobius & dirac)
Definition at line 35 of file dirac_mobius.cpp.
References b_5, c_5, quda::DiracDomainWall::Ls, quda::DiracDomainWall::operator=(), and zMobius.
Referenced by quda::DiracMobiusPC::operator=().
prepare()
void quda::DiracMobius::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracMobiusPC.
Definition at line 173 of file dirac_mobius.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracMobius::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracMobiusPC.
Definition at line 184 of file dirac_mobius.cpp.
Member Data Documentation
b_5
Complex quda::DiracMobius::b_5[QUDA_MAX_DWF_LS] protected
Definition at line 453 of file dirac_quda.h.
Referenced by DiracMobius(), Dslash4pre(), Dslash4preXpay(), Dslash4Xpay(), Dslash5(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5invXpay(), Dslash5Xpay(), M(), and operator=().
c_5
Complex quda::DiracMobius::c_5[QUDA_MAX_DWF_LS] protected
Definition at line 454 of file dirac_quda.h.
Referenced by DiracMobius(), Dslash4pre(), Dslash4preXpay(), Dslash4Xpay(), Dslash5(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5invXpay(), Dslash5Xpay(), M(), and operator=().
zMobius
bool quda::DiracMobius::zMobius protected
Whether we are using classical Mobius with constant real-valued b and c coefficients, or zMobius with complex-valued variable coefficients
Definition at line 461 of file dirac_quda.h.
Referenced by DiracMobius(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5invXpay(), and operator=().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_mobius.cpp