QUDA: quda::DiracWilsonPC Class Reference
quda::DiracWilsonPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracWilsonPC (const DiracParam &param)
DiracWilsonPC (const DiracWilsonPC &dirac)
virtual ~DiracWilsonPC ()
DiracWilsonPC & operator= (const DiracWilsonPC &dirac)
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 245 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracWilsonPC() [1/2]
quda::DiracWilsonPC::DiracWilsonPC (const DiracParam & param)
Definition at line 104 of file dirac_wilson.cpp.
DiracWilsonPC() [2/2]
quda::DiracWilsonPC::DiracWilsonPC (const DiracWilsonPC & dirac)
Definition at line 110 of file dirac_wilson.cpp.
~DiracWilsonPC()
quda::DiracWilsonPC::~DiracWilsonPC () virtual
Definition at line 116 of file dirac_wilson.cpp.
Member Function Documentation
M()
void quda::DiracWilsonPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 129 of file dirac_wilson.cpp.
References quda::Dirac::deleteTmp(), quda::DiracWilson::Dslash(), quda::DiracWilson::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
Referenced by MdagM().
MdagM()
void quda::DiracWilsonPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 148 of file dirac_wilson.cpp.
References quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp2.
operator=()
DiracWilsonPC & quda::DiracWilsonPC::operator= (const DiracWilsonPC & dirac)
Definition at line 121 of file dirac_wilson.cpp.
References quda::DiracWilson::operator=().
prepare()
void quda::DiracWilsonPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 156 of file dirac_wilson.cpp.
References quda::DiracWilson::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
reconstruct()
void quda::DiracWilsonPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 185 of file dirac_wilson.cpp.
References quda::Dirac::checkFullSpinor(), quda::DiracWilson::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_wilson.cpp