QUDA: quda::SimpleBiCGstab Class Reference
quda::SimpleBiCGstab Class Reference
#include <invert_quda.h>
Public Member Functions
SimpleBiCGstab (DiracMatrix &mat, SolverParam &param, TimeProfile &profile)
virtual ~SimpleBiCGstab ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
DiracMatrix & mat
cudaColorSpinorField * yp
cudaColorSpinorField * rp
cudaColorSpinorField * pp
cudaColorSpinorField * vp
cudaColorSpinorField * tmpp
cudaColorSpinorField * tp
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 726 of file invert_quda.h.
Constructor & Destructor Documentation
SimpleBiCGstab()
quda::SimpleBiCGstab::SimpleBiCGstab (DiracMatrix & mat, SolverParam & param, TimeProfile & profile)
Definition at line 15 of file inv_sbicgstab_quda.cpp.
~SimpleBiCGstab()
quda::SimpleBiCGstab::~SimpleBiCGstab () virtual
Definition at line 20 of file inv_sbicgstab_quda.cpp.
Member Function Documentation
operator()()
void quda::SimpleBiCGstab::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 23 of file inv_sbicgstab_quda.cpp.
References quda::conj(), quda::Solver::convergence(), quda::ColorSpinorParam::create, csParam, mat, quda::SolverParam::maxiter, quda::norm2(), omega, quda::Solver::param, printfQuda, quda::Solver::PrintStats(), quda::Solver::PrintSummary(), quda::Solver::profile, quda::QUDA_PROFILE_INIT, QUDA_ZERO_FIELD_CREATE, quda::SolverParam::residual_type, quda::sqrt(), quda::Solver::stopping(), quda::SolverParam::tol, quda::SolverParam::tol_hq, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, and warningQuda.
Member Data Documentation
init
bool quda::SimpleBiCGstab::init private
Definition at line 733 of file invert_quda.h.
mat
DiracMatrix& quda::SimpleBiCGstab::mat private
Definition at line 729 of file invert_quda.h.
Referenced by operator()().
pp
cudaColorSpinorField * quda::SimpleBiCGstab::pp private
Definition at line 732 of file invert_quda.h.
rp
cudaColorSpinorField * quda::SimpleBiCGstab::rp private
Definition at line 732 of file invert_quda.h.
tmpp
cudaColorSpinorField * quda::SimpleBiCGstab::tmpp private
Definition at line 732 of file invert_quda.h.
tp
cudaColorSpinorField * quda::SimpleBiCGstab::tp private
Definition at line 732 of file invert_quda.h.
vp
cudaColorSpinorField * quda::SimpleBiCGstab::vp private
Definition at line 732 of file invert_quda.h.
yp
cudaColorSpinorField* quda::SimpleBiCGstab::yp private
Definition at line 732 of file invert_quda.h.
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_sbicgstab_quda.cpp