QUDA: quda::TunableVectorYZ Class Reference
quda::TunableVectorYZ Class Reference
#include <tune_quda.h>
Public Member Functions
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual TuneKey tuneKey () const =0
virtual void apply (const cudaStream_t &stream)=0
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Attributes
unsigned vector_length_z
unsigned step_z
bool tune_block_y
Additional Inherited Members
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual long long flops () const =0
virtual long long bytes () const
virtual unsigned int minThreads () const
virtual bool tuneGridDim () const
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
Definition at line 485 of file tune_quda.h.
Constructor & Destructor Documentation
TunableVectorYZ()
quda::TunableVectorYZ::TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z) inline
Definition at line 492 of file tune_quda.h.
Member Function Documentation
advanceBlockDim()
bool quda::TunableVectorYZ::advanceBlockDim (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorY.
Reimplemented in quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >.
Definition at line 496 of file tune_quda.h.
References quda::Tunable::advanceBlockDim(), quda::TunableVectorY::advanceBlockDim(), quda::TuneParam::block, deviceProp, and quda::TuneParam::grid.
Referenced by quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceBlockDim().
defaultTuneParam()
void quda::TunableVectorYZ::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorY.
Reimplemented in quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >, quda::Pack< Float, nColor, spin_project >, quda::Dslash5< Float, nColor, Arg >, quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >, and quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >.
Definition at line 531 of file tune_quda.h.
References quda::TuneParam::block, quda::TunableVectorY::defaultTuneParam(), and quda::TuneParam::grid.
Referenced by quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >::defaultTuneParam(), quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::defaultTuneParam(), quda::Dslash5< Float, nColor, Arg >::defaultTuneParam(), quda::Pack< Float, nColor, spin_project >::defaultTuneParam(), and quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::defaultTuneParam().
initTuneParam()
void quda::TunableVectorYZ::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorY.
Reimplemented in quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >, quda::Pack< Float, nColor, spin_project >, quda::Dslash5< Float, nColor, Arg >, quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >, and quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >.
Definition at line 523 of file tune_quda.h.
References quda::TuneParam::block, quda::TuneParam::grid, and quda::TunableVectorY::initTuneParam().
Referenced by quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceAux(), quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >::initTuneParam(), quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::initTuneParam(), quda::Dslash5< Float, nColor, Arg >::initTuneParam(), quda::Pack< Float, nColor, spin_project >::initTuneParam(), and quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::initTuneParam().
resizeStep()
void quda::TunableVectorYZ::resizeStep (int y, int z) const inline
Definition at line 539 of file tune_quda.h.
References quda::activeTuning(), quda::disableProfileCount(), quda::enableProfileCount(), quda::flushProfile(), quda::getTuneCache(), quda::loadTuneCache(), quda::postTrace_(), quda::TunableVectorY::resizeStep(), quda::saveProfile(), quda::saveTuneCache(), quda::setPolicyTuning(), quda::tuneLaunch(), and verbosity.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceAux(), and quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setComputeType().
resizeVector()
void quda::TunableVectorYZ::resizeVector (int y, int z) const inline
Definition at line 538 of file tune_quda.h.
References quda::TunableVectorY::resizeVector().
Referenced by quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceAux(), quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceAux(), quda::DomainWall4D< Float, nDim, nColor, Arg >::DomainWall4D(), quda::DomainWall5D< Float, nDim, nColor, Arg >::DomainWall5D(), quda::NdegTwistedMass< Float, nDim, nColor, Arg >::NdegTwistedMass(), quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >::NdegTwistedMassPreconditioned(), and quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setComputeType().
Member Data Documentation
step_z
unsigned quda::TunableVectorYZ::step_z mutable private
Definition at line 488 of file tune_quda.h.
tune_block_y
bool quda::TunableVectorYZ::tune_block_y private
Definition at line 489 of file tune_quda.h.
vector_length_z
unsigned quda::TunableVectorYZ::vector_length_z mutable private
Definition at line 487 of file tune_quda.h.
The documentation for this class was generated from the following file:
include/tune_quda.h