QUDA: DslashTest Class Reference
DslashTest Class Reference
Public Member Functions
virtual ~DslashTest ()
virtual void SetUp ()
virtual void TearDown ()
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
Protected Member Functions
bool skip ()
Protected Attributes
::testing::tuple< int, int, int > param
Detailed Description
Definition at line 989 of file dslash_ctest.cpp.
Constructor & Destructor Documentation
~DslashTest()
virtual DslashTest::~DslashTest () inline virtual
Definition at line 1004 of file dslash_ctest.cpp.
Member Function Documentation
SetUp()
virtual void DslashTest::SetUp () inline virtual
Definition at line 1005 of file dslash_ctest.cpp.
References commDimPartitionedSet(), display_test_info(), init(), prec, and updateR().
SetUpTestCase()
static void DslashTest::SetUpTestCase () inline static
Definition at line 1030 of file dslash_ctest.cpp.
References device, and initQuda().
skip()
bool DslashTest::skip () inline protected
Definition at line 993 of file dslash_ctest.cpp.
References getPrecision(), and getReconstructNibble().
TearDown()
virtual void DslashTest::TearDown () inline virtual
Definition at line 1024 of file dslash_ctest.cpp.
References end().
TearDownTestCase()
static void DslashTest::TearDownTestCase () inline static
Definition at line 1037 of file dslash_ctest.cpp.
References endQuda().
Member Data Documentation
param
::testing::tuple<int, int, int> DslashTest::param protected
Definition at line 991 of file dslash_ctest.cpp.
The documentation for this class was generated from the following file:
tests/dslash_ctest.cpp