QUDA: quda::CloverField Class Reference
quda::CloverField Class Reference
#include <clover_field.h>
Public Member Functions
CloverField (const CloverFieldParam &param)
virtual ~CloverField ()
void * V (bool inverse=false)
void * Norm (bool inverse=false)
const void * V (bool inverse=false) const
const void * Norm (bool inverse=false) const
bool isNative () const
double * TrLog () const
QudaCloverFieldOrder Order () const
size_t Bytes () const
size_t NormBytes () const
int Ncolor () const
int Nspin () const
double Csw () const
bool Twisted () const
double Mu2 () const
double Rho () const
void setRho (double rho)
Bakes in the rho factor into the clover field, (for real diagonal additive Hasenbusch), e.g., A + rho.
double norm1 () const
Compute the L1 norm of the field.
double norm2 () const
Compute the L2 norm squared of the field.
double abs_max () const
Compute the absolute maximum of the field (Linfinity norm)
double abs_min () const
Compute the absolute minimum of the field.
Public Member Functions inherited from quda::LatticeField
LatticeField (const LatticeFieldParam &param)
LatticeField (const LatticeField &field)
virtual ~LatticeField ()
void allocateGhostBuffer (size_t ghost_bytes) const
Allocate the static ghost buffers.
void createComms (bool no_comms_fill=false, bool bidir=true)
void destroyComms ()
void createIPCComms ()
bool ipcCopyComplete (int dir, int dim)
bool ipcRemoteCopyComplete (int dir, int dim)
const cudaEvent_t & getIPCCopyEvent (int dir, int dim) const
const cudaEvent_t & getIPCRemoteCopyEvent (int dir, int dim) const
int Ndim () const
const int * X () const
int Volume () const
int VolumeCB () const
const int * SurfaceCB () const
int SurfaceCB (const int i) const
int Stride () const
int Pad () const
const int * R () const
QudaGhostExchange GhostExchange () const
QudaPrecision Precision () const
QudaPrecision GhostPrecision () const
double Scale () const
void Scale (double scale_)
Set the scale factor for a fixed-point field.
virtual QudaSiteSubset SiteSubset () const
virtual QudaMemoryType MemType () const
int Nvec () const
QudaFieldLocation Location () const
size_t GBytes () const
void checkField (const LatticeField &a) const
virtual void read (char *filename)
virtual void write (char *filename)
virtual void gather (int nFace, int dagger, int dir, cudaStream_t *stream_p=NULL)
virtual void commsStart (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual int commsQuery (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual void commsWait (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual void scatter (int nFace, int dagger, int dir)
const char * VolString () const
const char * AuxString () const
virtual void backup () const
Backs up the LatticeField.
virtual void restore () const
Restores the LatticeField.
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Attributes
size_t bytes
size_t norm_bytes
size_t length
size_t real_length
int nColor
int nSpin
void * clover
void * norm
void * cloverInv
void * invNorm
double csw
bool twisted
double mu2
double rho
QudaCloverFieldOrder order
QudaFieldCreate create
double trlog [2]
Protected Attributes inherited from quda::LatticeField
int volume
int volumeCB
int stride
int pad
size_t total_bytes
int nDim
int x [QUDA_MAX_DIM]
int surface [QUDA_MAX_DIM]
int surfaceCB [QUDA_MAX_DIM]
int r [QUDA_MAX_DIM]
QudaPrecision precision
QudaPrecision ghost_precision
bool ghost_precision_reset
double scale
QudaSiteSubset siteSubset
QudaGhostExchange ghostExchange
int nDimComms
size_t ghost_bytes
size_t ghost_bytes_old
size_t ghost_face_bytes [QUDA_MAX_DIM]
int ghostOffset [QUDA_MAX_DIM][2]
int ghostNormOffset [QUDA_MAX_DIM][2]
void * my_face_h [2]
void * my_face_hd [2]
void * my_face_d [2]
void * my_face_dim_dir_h [2][QUDA_MAX_DIM][2]
void * my_face_dim_dir_hd [2][QUDA_MAX_DIM][2]
void * my_face_dim_dir_d [2][QUDA_MAX_DIM][2]
void * from_face_h [2]
void * from_face_hd [2]
void * from_face_d [2]
void * from_face_dim_dir_h [2][QUDA_MAX_DIM][2]
void * from_face_dim_dir_hd [2][QUDA_MAX_DIM][2]
void * from_face_dim_dir_d [2][QUDA_MAX_DIM][2]
MsgHandle * mh_recv_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_back [2][QUDA_MAX_DIM]
MsgHandle * mh_send_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_send_back [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_rdma_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_rdma_back [2][QUDA_MAX_DIM]
MsgHandle * mh_send_rdma_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_send_rdma_back [2][QUDA_MAX_DIM]
bool initComms
char vol_string [TuneKey::volume_n]
char aux_string [TuneKey::aux_n]
QudaMemoryType mem_type
char * backup_h
char * backup_norm_h
bool backed_up
Additional Inherited Members
Static Public Member Functions inherited from quda::LatticeField
static void freeGhostBuffer (void)
Free statically allocated ghost buffers.
static void destroyIPCComms ()
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Static Public Attributes inherited from quda::LatticeField
static int bufferIndex = 0
static bool ghost_field_reset = false
Protected Member Functions inherited from quda::LatticeField
virtual void setTuningString ()
void precisionCheck ()
Static Protected Attributes inherited from quda::LatticeField
static void * ghost_send_buffer_d [2] = {nullptr, nullptr}
static void * ghost_recv_buffer_d [2] = {nullptr, nullptr}
static void * ghost_pinned_send_buffer_h [2] = {nullptr, nullptr}
static void * ghost_pinned_recv_buffer_h [2] = {nullptr, nullptr}
static void * ghost_pinned_send_buffer_hd [2] = {nullptr, nullptr}
static void * ghost_pinned_recv_buffer_hd [2] = {nullptr, nullptr}
static void * ghost_remote_send_buffer_d [2][QUDA_MAX_DIM][2]
static size_t ghostFaceBytes = 0
static bool initGhostFaceBuffer = false
static MsgHandle * mh_send_p2p_fwd [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_send_p2p_back [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_recv_p2p_fwd [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_recv_p2p_back [2][QUDA_MAX_DIM] { }
static int buffer_send_p2p_fwd [2][QUDA_MAX_DIM] { }
static int buffer_recv_p2p_fwd [2][QUDA_MAX_DIM] { }
static int buffer_send_p2p_back [2][QUDA_MAX_DIM] { }
static int buffer_recv_p2p_back [2][QUDA_MAX_DIM] { }
static cudaEvent_t ipcCopyEvent [2][2][QUDA_MAX_DIM]
static cudaEvent_t ipcRemoteCopyEvent [2][2][QUDA_MAX_DIM]
static bool initIPCComms = false
Detailed Description
Definition at line 45 of file clover_field.h.
Constructor & Destructor Documentation
CloverField()
quda::CloverField::CloverField (const CloverFieldParam & param)
Definition at line 37 of file clover_field.cpp.
References ALIGNMENT_ADJUST, bytes, create, errorQuda, isNative(), length, mu2, nColor, quda::LatticeField::nDim, norm_bytes, nSpin, order, quda::LatticeField::precision, QUDA_HALF_PRECISION, QUDA_QDPJIT_CLOVER_ORDER, QUDA_QUARTER_PRECISION, QUDA_REFERENCE_FIELD_CREATE, real_length, quda::LatticeField::stride, twisted, and quda::LatticeField::volumeCB.
~CloverField()
quda::CloverField::~CloverField () virtual
Definition at line 61 of file clover_field.cpp.
Member Function Documentation
abs_max()
double quda::CloverField::abs_max () const
Compute the absolute maximum of the field (Linfinity norm)
Returns
Absolute maximum value
Definition at line 69 of file max_clover.cu.
References quda::ABS_MAX, errorQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
abs_min()
double quda::CloverField::abs_min () const
Compute the absolute minimum of the field.
Returns
Absolute minimum value
Definition at line 79 of file max_clover.cu.
References quda::ABS_MIN, errorQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
Bytes()
size_t quda::CloverField::Bytes () const inline
Returns
The size of the fieldallocation
Definition at line 98 of file clover_field.h.
References quda::blas::bytes.
Referenced by quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::Accessor(), quda::clover::BQCDOrder< Float, length >::BQCDOrder(), quda::cudaCloverField::copy(), and loadCloverQuda().
Csw()
double quda::CloverField::Csw () const inline
Returns
Clover coefficient (usually includes kappa)
Definition at line 118 of file clover_field.h.
References quda::CloverFieldParam::csw.
Referenced by loadCloverQuda().
isNative()
bool quda::CloverField::isNative () const
Returns
True if the field is stored in an internal field order for the given precision.
Definition at line 63 of file clover_field.cpp.
References order, quda::LatticeField::precision, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_CLOVER_ORDER, QUDA_FLOAT4_CLOVER_ORDER, QUDA_HALF_PRECISION, QUDA_QUARTER_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by CloverField(), quda::CloverInvertArg< Float >::CloverInvertArg(), and quda::cudaCloverField::cudaCloverField().
Mu2()
double quda::CloverField::Mu2 () const inline
Returns
mu^2 factor baked into inverse clover field (for twisted-clover inverse)
Definition at line 128 of file clover_field.h.
References quda::CloverFieldParam::mu2.
Ncolor()
int quda::CloverField::Ncolor () const inline
Returns
Number of colors
Definition at line 108 of file clover_field.h.
References nColor.
Referenced by quda::_norm().
Norm() [1/2]
void* quda::CloverField::Norm (bool inverse = false) inline
Definition at line 75 of file clover_field.h.
References quda::CloverFieldParam::inverse, quda::CloverFieldParam::invNorm, and quda::CloverFieldParam::norm.
Referenced by quda::cudaCloverField::copy(), and quda::clover::FloatNOrder< Float, length, N, add_rho, huge_alloc >::FloatNOrder().
Norm() [2/2]
const void* quda::CloverField::Norm (bool inverse = false) const inline
Definition at line 77 of file clover_field.h.
References quda::CloverFieldParam::inverse, quda::CloverFieldParam::invNorm, and quda::CloverFieldParam::norm.
norm1()
double quda::CloverField::norm1 () const
Compute the L1 norm of the field.
Returns
L1 norm
Definition at line 49 of file max_clover.cu.
References errorQuda, quda::NORM1, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
norm2()
double quda::CloverField::norm2 () const
Compute the L2 norm squared of the field.
Returns
L2 norm squared
Definition at line 59 of file max_clover.cu.
References errorQuda, quda::NORM2, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
NormBytes()
size_t quda::CloverField::NormBytes () const inline
Returns
The size of the norm allocation
Definition at line 103 of file clover_field.h.
Referenced by quda::cudaCloverField::copy().
Nspin()
int quda::CloverField::Nspin () const inline
Returns
Number of spins
Definition at line 113 of file clover_field.h.
Order()
QudaCloverFieldOrder quda::CloverField::Order () const inline
Returns
The order of the field
Definition at line 93 of file clover_field.h.
References quda::CloverFieldParam::order.
Referenced by quda::cloverInvert(), quda::CloverInvertArg< Float >::CloverInvertArg(), quda::copyGenericClover(), quda::norm(), and quda::LatticeField::Nvec().
Rho()
double quda::CloverField::Rho () const inline
Returns
rho factor backed into the clover field, (for real diagonal additive Hasenbusch), e.g., A + rho
Definition at line 134 of file clover_field.h.
References quda::norm1(), quda::norm2(), and quda::CloverFieldParam::rho.
setRho()
void quda::CloverField::setRho (double rho)
Bakes in the rho factor into the clover field, (for real diagonal additive Hasenbusch), e.g., A + rho.
Definition at line 73 of file clover_field.cpp.
References rho.
Referenced by loadCloverQuda().
TrLog()
double* quda::CloverField::TrLog () const inline
Returns
Pointer to array storing trlog on each parity
Definition at line 88 of file clover_field.h.
Referenced by loadCloverQuda().
Twisted()
bool quda::CloverField::Twisted () const inline
Returns
If the clover field is associated with twisted-clover fermions
Definition at line 123 of file clover_field.h.
References quda::CloverFieldParam::twisted.
V() [1/2]
void* quda::CloverField::V (bool inverse = false) inline
Definition at line 74 of file clover_field.h.
References quda::CloverFieldParam::clover, quda::CloverFieldParam::cloverInv, and quda::CloverFieldParam::inverse.
Referenced by quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::Accessor(), quda::clover::BQCDOrder< Float, length >::BQCDOrder(), quda::colorSpinorParam(), quda::cudaCloverField::copy(), quda::clover::FloatNOrder< Float, length, N, add_rho, huge_alloc >::FloatNOrder(), loadCloverQuda(), loadSloppyCloverQuda(), quda::clover::QDPJITOrder< Float, length >::QDPJITOrder(), quda::clover::QDPOrder< Float, length >::QDPOrder(), and quda::cudaCloverField::saveCPUField().
V() [2/2]
const void* quda::CloverField::V (bool inverse = false) const inline
Definition at line 76 of file clover_field.h.
References quda::CloverFieldParam::clover, quda::CloverFieldParam::cloverInv, and quda::CloverFieldParam::inverse.
Member Data Documentation
bytes
size_t quda::CloverField::bytes protected
Definition at line 48 of file clover_field.h.
Referenced by CloverField(), quda::cudaCloverField::copy(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), and quda::cudaCloverField::saveCPUField().
clover
void* quda::CloverField::clover protected
Definition at line 55 of file clover_field.h.
Referenced by quda::cudaCloverField::copy(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), quda::cudaCloverField::saveCPUField(), quda::cpuCloverField::~cpuCloverField(), and quda::cudaCloverField::~cudaCloverField().
cloverInv
void* quda::CloverField::cloverInv protected
Definition at line 57 of file clover_field.h.
Referenced by quda::cudaCloverField::copy(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), quda::DiracCloverPC::DiracCloverPC(), quda::cudaCloverField::saveCPUField(), quda::cpuCloverField::~cpuCloverField(), and quda::cudaCloverField::~cudaCloverField().
create
QudaFieldCreate quda::CloverField::create protected
Definition at line 66 of file clover_field.h.
Referenced by CloverField(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), quda::cpuCloverField::~cpuCloverField(), and quda::cudaCloverField::~cudaCloverField().
csw
double quda::CloverField::csw protected
Definition at line 60 of file clover_field.h.
invNorm
void* quda::CloverField::invNorm protected
Definition at line 58 of file clover_field.h.
Referenced by quda::cudaCloverField::copy(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), quda::cudaCloverField::saveCPUField(), quda::cpuCloverField::~cpuCloverField(), and quda::cudaCloverField::~cudaCloverField().
length
size_t quda::CloverField::length protected
Definition at line 50 of file clover_field.h.
Referenced by CloverField().
mu2
double quda::CloverField::mu2 protected
Definition at line 62 of file clover_field.h.
Referenced by CloverField(), and quda::cudaCloverField::cudaCloverField().
nColor
int quda::CloverField::nColor protected
Definition at line 52 of file clover_field.h.
Referenced by CloverField().
norm
void* quda::CloverField::norm protected
Definition at line 56 of file clover_field.h.
Referenced by quda::cudaCloverField::cudaCloverField().
norm_bytes
size_t quda::CloverField::norm_bytes protected
Definition at line 49 of file clover_field.h.
Referenced by CloverField(), quda::cudaCloverField::copy(), quda::cpuCloverField::cpuCloverField(), quda::cudaCloverField::cudaCloverField(), and quda::cudaCloverField::saveCPUField().
nSpin
int quda::CloverField::nSpin protected
Definition at line 53 of file clover_field.h.
Referenced by CloverField().
order
QudaCloverFieldOrder quda::CloverField::order protected
Definition at line 65 of file clover_field.h.
Referenced by CloverField(), quda::cpuCloverField::cpuCloverField(), and isNative().
real_length
size_t quda::CloverField::real_length protected
Definition at line 51 of file clover_field.h.
Referenced by CloverField().
rho
double quda::CloverField::rho protected
Definition at line 63 of file clover_field.h.
Referenced by setRho().
trlog
double quda::CloverField::trlog[2] mutable protected
Definition at line 68 of file clover_field.h.
twisted
bool quda::CloverField::twisted protected
Definition at line 61 of file clover_field.h.
Referenced by CloverField(), and quda::cudaCloverField::cudaCloverField().
The documentation for this class was generated from the following files:
include/clover_field.h
lib/clover_field.cpp
lib/max_clover.cu