QUDA: quda::DiracCloverPC Class Reference
quda::DiracCloverPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracCloverPC (const DiracParam &param)
DiracCloverPC (const DiracCloverPC &dirac)
virtual ~DiracCloverPC ()
DiracCloverPC & operator= (const DiracCloverPC &dirac)
void CloverInv (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse even-odd preconditioned clover operator. Unlike the Wilson operator, the coarsening of the preconditioned clover operator differs from that of the unpreconditioned clover operator, so we need to specialize it.
Public Member Functions inherited from quda::DiracClover
DiracClover (const DiracParam &param)
DiracClover (const DiracClover &dirac)
virtual ~DiracClover ()
DiracClover & operator= (const DiracClover &dirac)
void Clover (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracClover
void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
void initConstants ()
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracClover
cudaCloverField & clover
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 305 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracCloverPC() [1/2]
quda::DiracCloverPC::DiracCloverPC (const DiracParam & param)
Definition at line 99 of file dirac_clover.cpp.
References quda::DiracClover::clover, quda::CloverField::cloverInv, and errorQuda.
DiracCloverPC() [2/2]
quda::DiracCloverPC::DiracCloverPC (const DiracCloverPC & dirac)
Definition at line 106 of file dirac_clover.cpp.
~DiracCloverPC()
quda::DiracCloverPC::~DiracCloverPC () virtual
Definition at line 108 of file dirac_clover.cpp.
Member Function Documentation
CloverInv()
void quda::DiracCloverPC::CloverInv (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 119 of file dirac_clover.cpp.
References quda::ApplyClover(), quda::DiracClover::checkParitySpinor(), quda::DiracClover::clover, quda::Dirac::flops, and quda::ColorSpinorField::Volume().
Referenced by cloverQuda(), M(), prepare(), and reconstruct().
createCoarseOp()
void quda::DiracCloverPC::createCoarseOp (GaugeField & Y, GaugeField & X, const Transfer & T, double kappa, double mass = 0., double mu = 0., double mu_factor = 0.) const virtual
Create the coarse even-odd preconditioned clover operator. Unlike the Wilson operator, the coarsening of the preconditioned clover operator differs from that of the unpreconditioned clover operator, so we need to specialize it.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
kappa Kappa parameter for the coarse operator
mass Mass parameter for the coarse operator (set to zero)
Reimplemented from quda::DiracClover.
Definition at line 272 of file dirac_clover.cpp.
References quda::DiracClover::clover, quda::CoarseOp(), quda::Dirac::gauge, quda::Dirac::matpcType, QUDA_CLOVERPC_DIRAC, quda::ColorSpinorField::TwistFlavor(), and quda::Transfer::Vectors().
Dslash()
void quda::DiracCloverPC::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 131 of file dirac_clover.cpp.
References quda::ApplyWilsonCloverPreconditioned(), quda::DiracClover::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::DiracClover::clover, quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by M().
DslashXpay()
void quda::DiracCloverPC::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Applies the operator (A + k D)
Reimplemented from quda::DiracClover.
Definition at line 142 of file dirac_clover.cpp.
References quda::ApplyWilsonCloverPreconditioned(), quda::DiracClover::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::DiracClover::clover, quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by M().
M()
void quda::DiracCloverPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracClover.
Definition at line 154 of file dirac_clover.cpp.
References CloverInv(), quda::Dirac::dagger, quda::Dirac::deleteTmp(), Dslash(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), DslashXpay(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), parity, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, and quda::Dirac::tmp1.
Referenced by MdagM().
MdagM()
void quda::DiracCloverPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracClover.
Definition at line 180 of file dirac_clover.cpp.
References quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp2.
operator=()
DiracCloverPC & quda::DiracCloverPC::operator= (const DiracCloverPC & dirac)
Definition at line 110 of file dirac_clover.cpp.
References quda::DiracClover::operator=().
prepare()
void quda::DiracCloverPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracClover.
Definition at line 190 of file dirac_clover.cpp.
References CloverInv(), quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
reconstruct()
void quda::DiracCloverPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracClover.
Definition at line 241 of file dirac_clover.cpp.
References quda::Dirac::checkFullSpinor(), CloverInv(), quda::Dirac::deleteTmp(), quda::DiracWilson::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_clover.cpp