QUDA: quda::ProjectSU3< Float, G > Class Template Reference
quda::ProjectSU3< Float, G > Class Template Reference
Public Member Functions
ProjectSU3 (ProjectSU3Arg< Float, G > &arg, const GaugeField &meta)
void apply (const cudaStream_t &stream)
void preTune ()
void postTune ()
long long flops () const
long long bytes () const
TuneKey tuneKey () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
ProjectSU3Arg< Float, G > arg
const GaugeField & meta
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, typename G>
class quda::ProjectSU3< Float, G >
Definition at line 553 of file unitarize_links_quda.cu.
Constructor & Destructor Documentation
ProjectSU3()
template<typename Float, typename G> quda::ProjectSU3< Float, G >::ProjectSU3 (ProjectSU3Arg< Float, G > & arg, const GaugeField & meta) inline
Definition at line 565 of file unitarize_links_quda.cu.
Member Function Documentation
apply()
template<typename Float, typename G> void quda::ProjectSU3< Float, G >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 568 of file unitarize_links_quda.cu.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::projectSU3().
bytes()
template<typename Float, typename G> long long quda::ProjectSU3< Float, G >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 579 of file unitarize_links_quda.cu.
References quda::ProjectSU3Arg< Float, G >::threads, and quda::ProjectSU3Arg< Float, G >::u.
flops()
template<typename Float, typename G> long long quda::ProjectSU3< Float, G >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 578 of file unitarize_links_quda.cu.
minThreads()
template<typename Float, typename G> unsigned int quda::ProjectSU3< Float, G >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 562 of file unitarize_links_quda.cu.
References quda::ProjectSU3Arg< Float, G >::threads.
postTune()
template<typename Float, typename G> void quda::ProjectSU3< Float, G >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 573 of file unitarize_links_quda.cu.
References quda::ProjectSU3Arg< Float, G >::fails, and quda::ProjectSU3Arg< Float, G >::u.
preTune()
template<typename Float, typename G> void quda::ProjectSU3< Float, G >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 572 of file unitarize_links_quda.cu.
References quda::ProjectSU3Arg< Float, G >::u.
sharedBytesPerBlock()
template<typename Float, typename G> unsigned int quda::ProjectSU3< Float, G >::sharedBytesPerBlock (const TuneParam &) const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 558 of file unitarize_links_quda.cu.
sharedBytesPerThread()
template<typename Float, typename G> unsigned int quda::ProjectSU3< Float, G >::sharedBytesPerThread () const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 557 of file unitarize_links_quda.cu.
tuneGridDim()
template<typename Float, typename G> bool quda::ProjectSU3< Float, G >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 561 of file unitarize_links_quda.cu.
tuneKey()
template<typename Float, typename G> TuneKey quda::ProjectSU3< Float, G >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 581 of file unitarize_links_quda.cu.
References quda::ProjectSU3Arg< Float, G >::threads, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, typename G> ProjectSU3Arg<Float,G> quda::ProjectSU3< Float, G >::arg private
Definition at line 554 of file unitarize_links_quda.cu.
meta
template<typename Float, typename G> const GaugeField& quda::ProjectSU3< Float, G >::meta private
Definition at line 555 of file unitarize_links_quda.cu.
The documentation for this class was generated from the following file:
lib/unitarize_links_quda.cu