QUDA: quda::TwistedClover< Float, nDim, nColor, Arg > Class Template Reference
quda::TwistedClover< Float, nDim, nColor, Arg > Class Template Reference
Public Member Functions
TwistedClover (Arg &arg, const ColorSpinorField &out, const ColorSpinorField &in)
virtual ~TwistedClover ()
void apply (const cudaStream_t &stream)
long long flops () const
long long bytes () const
TuneKey tuneKey () const
Public Member Functions inherited from quda::Dslash< Float >
template<typename T , typename Arg >
void launch (T *f, const TuneParam &tp, Arg &arg, const cudaStream_t &stream)
template<template< typename, int, int, int, bool, bool, KernelType, typename > class Launch, int nDim, int nColor, int nParity, bool dagger, bool xpay, typename Arg >
void instantiate (TuneParam &tp, Arg &arg, const cudaStream_t &stream)
This instantiate function is used to instantiate the the KernelType template required for the multi-GPU dslash kernels.
template<template< typename, int, int, int, bool, bool, KernelType, typename > class Launch, int nDim, int nColor, int nParity, bool xpay, typename Arg >
void instantiate (TuneParam &tp, Arg &arg, const cudaStream_t &stream)
This instantiate function is used to instantiate the the dagger template.
template<template< typename, int, int, int, bool, bool, KernelType, typename > class Launch, int nDim, int nColor, bool xpay, typename Arg >
void instantiate (TuneParam &tp, Arg &arg, const cudaStream_t &stream)
This instantiate function is used to instantiate the the nParity template.
template<template< typename, int, int, int, bool, bool, KernelType, typename > class Launch, int nDim, int nColor, typename Arg >
void instantiate (TuneParam &tp, Arg &arg, const cudaStream_t &stream)
This instantiate function is used to instantiate the the xpay template.
Dslash (DslashArg< Float > &arg, const ColorSpinorField &out, const ColorSpinorField &in, const char *src)
int Nface () const
int Dagger () const
const char * getAux (KernelType type) const
void setAux (KernelType type, const char *aux_)
void augmentAux (KernelType type, const char *extra)
virtual void preTune ()
Save the output field since the output field is both read from and written to in the exterior kernels.
virtual void postTune ()
Restore the output field if doing exterior kernel.
Public Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Protected Attributes
Arg & arg
const ColorSpinorField & in
Protected Attributes inherited from quda::Dslash< Float >
DslashArg< Float > & arg
const ColorSpinorField & out
const ColorSpinorField & in
const int nDimComms
char aux_base [TuneKey::aux_n - 32]
char aux [8][TuneKey::aux_n]
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Additional Inherited Members
Public Attributes inherited from quda::Dslash< Float >
DslashArg< Float > & dslashParam
Protected Member Functions inherited from quda::Dslash< Float >
void fillAuxBase ()
Set the base strings used by the different dslash kernel types for autotuning.
void fillAux (KernelType kernel_type, const char *kernel_str)
Specialize the auxiliary strings for each kernel type.
bool tuneGridDim () const
unsigned int minThreads () const
template<typename Arg >
void setParam (Arg &arg)
virtual int tuningIter () const
int blockStep () const
int blockMin () const
unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Detailed Description
template<typename Float, int nDim, int nColor, typename Arg>
class quda::TwistedClover< Float, nDim, nColor, Arg >
Definition at line 32 of file dslash_twisted_clover.cu.
Constructor & Destructor Documentation
TwistedClover()
template<typename Float, int nDim, int nColor, typename Arg> quda::TwistedClover< Float, nDim, nColor, Arg >::TwistedClover (Arg & arg, const ColorSpinorField & out, const ColorSpinorField & in) inline
Definition at line 40 of file dslash_twisted_clover.cu.
~TwistedClover()
template<typename Float, int nDim, int nColor, typename Arg> virtual quda::TwistedClover< Float, nDim, nColor, Arg >::~TwistedClover () inline virtual
Definition at line 47 of file dslash_twisted_clover.cu.
Member Function Documentation
apply()
template<typename Float, int nDim, int nColor, typename Arg> void quda::TwistedClover< Float, nDim, nColor, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 49 of file dslash_twisted_clover.cu.
References quda::arg(), errorQuda, getTuning(), getVerbosity(), quda::Dslash< Float >::setParam(), quda::stream, and quda::tuneLaunch().
bytes()
template<typename Float, int nDim, int nColor, typename Arg> long long quda::TwistedClover< Float, nDim, nColor, Arg >::bytes () const inline virtual
Reimplemented from quda::Dslash< Float >.
Definition at line 75 of file dslash_twisted_clover.cu.
References quda::blas::bytes, quda::Dslash< Float >::bytes(), quda::EXTERIOR_KERNEL_ALL, quda::EXTERIOR_KERNEL_T, quda::EXTERIOR_KERNEL_X, quda::EXTERIOR_KERNEL_Y, quda::EXTERIOR_KERNEL_Z, quda::INTERIOR_KERNEL, quda::KERNEL_POLICY, quda::LatticeField::Precision(), and quda::ColorSpinorField::Volume().
flops()
template<typename Float, int nDim, int nColor, typename Arg> long long quda::TwistedClover< Float, nDim, nColor, Arg >::flops () const inline virtual
Reimplemented from quda::Dslash< Float >.
Definition at line 59 of file dslash_twisted_clover.cu.
References quda::EXTERIOR_KERNEL_ALL, quda::EXTERIOR_KERNEL_T, quda::EXTERIOR_KERNEL_X, quda::EXTERIOR_KERNEL_Y, quda::EXTERIOR_KERNEL_Z, quda::blas::flops, quda::Dslash< Float >::flops(), quda::INTERIOR_KERNEL, quda::KERNEL_POLICY, and quda::ColorSpinorField::Volume().
tuneKey()
template<typename Float, int nDim, int nColor, typename Arg> TuneKey quda::TwistedClover< Float, nDim, nColor, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 94 of file dslash_twisted_clover.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int nDim, int nColor, typename Arg> Arg& quda::TwistedClover< Float, nDim, nColor, Arg >::arg protected
Definition at line 36 of file dslash_twisted_clover.cu.
in
template<typename Float, int nDim, int nColor, typename Arg> const ColorSpinorField& quda::TwistedClover< Float, nDim, nColor, Arg >::in protected
Definition at line 37 of file dslash_twisted_clover.cu.
The documentation for this class was generated from the following file:
lib/dslash_twisted_clover.cu