QUDA: quda::CG3 Class Reference
quda::CG3 Class Reference
#include <invert_quda.h>
Public Member Functions
CG3 (DiracMatrix &mat, DiracMatrix &matSloppy, SolverParam &param, TimeProfile &profile)
virtual ~CG3 ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
const DiracMatrix & mat
const DiracMatrix & matSloppy
ColorSpinorField * yp
ColorSpinorField * rp
ColorSpinorField * tmpp
ColorSpinorField * ArSp
ColorSpinorField * rSp
ColorSpinorField * xSp
ColorSpinorField * xS_oldp
ColorSpinorField * tmpSp
ColorSpinorField * rS_oldp
ColorSpinorField * tmp2Sp
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 607 of file invert_quda.h.
Constructor & Destructor Documentation
CG3()
quda::CG3::CG3 (DiracMatrix & mat, DiracMatrix & matSloppy, SolverParam & param, TimeProfile & profile)
Definition at line 16 of file inv_cg3_quda.cpp.
~CG3()
quda::CG3::~CG3 () virtual
Definition at line 21 of file inv_cg3_quda.cpp.
References ArSp, init, quda::DiracMatrix::isStaggered(), mat, quda::Solver::param, quda::SolverParam::precision, quda::SolverParam::precision_sloppy, rp, rS_oldp, rSp, tmp2Sp, tmpp, tmpSp, xS_oldp, xSp, and yp.
Member Function Documentation
operator()()
void quda::CG3::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 40 of file inv_cg3_quda.cpp.
References ArSp, quda::blas::axpby(), quda::blas::axpy(), quda::blas::axpyNorm(), quda::blas::caxpyNorm(), quda::blas::cDotProduct(), checkLocation, quda::SolverParam::compute_null_vector, quda::SolverParam::compute_true_res, quda::Solver::convergence(), quda::Solver::convergenceHQ(), quda::blas::copy(), quda::ColorSpinorParam::create, quda::ColorSpinorField::Create(), csParam, quda::SolverParam::delta, errorQuda, quda::blas::flops, quda::DiracMatrix::flops(), quda::SolverParam::gflops, quda::SolverParam::heavy_quark_check, quda::blas::HeavyQuarkResidualNorm(), init, quda::DiracMatrix::isStaggered(), quda::SolverParam::iter, quda::TimeProfile::Last(), mat, matSloppy, quda::SolverParam::max_res_increase, quda::SolverParam::max_res_increase_total, quda::SolverParam::maxiter, quda::blas::norm2(), quda::Solver::param, pipeline, quda::SolverParam::pipeline, quda::SolverParam::precision, quda::LatticeField::Precision(), quda::SolverParam::precision_sloppy, quda::SolverParam::preserve_source, printfQuda, quda::Solver::PrintStats(), quda::Solver::PrintSummary(), quda::Solver::profile, quda::blas::quadrupleCG3InitNorm(), quda::blas::quadrupleCG3UpdateNorm(), QUDA_COMPUTE_NULL_VECTOR_NO, QUDA_CUDA_FIELD_LOCATION, QUDA_HEAVY_QUARK_RESIDUAL, QUDA_PRESERVE_SOURCE_NO, quda::QUDA_PROFILE_COMPUTE, quda::QUDA_PROFILE_EPILOGUE, quda::QUDA_PROFILE_INIT, quda::QUDA_PROFILE_PREAMBLE, QUDA_USE_INIT_GUESS_NO, QUDA_USE_INIT_GUESS_YES, QUDA_ZERO_FIELD_CREATE, quda::blas::reDotProduct(), quda::SolverParam::residual_type, rp, rS_oldp, rSp, quda::SolverParam::secs, quda::ColorSpinorParam::setPrecision(), quda::sqrt(), quda::Solver::stopping(), tmp, tmp2Sp, tmpp, tmpSp, quda::SolverParam::tol, quda::SolverParam::tol_hq, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, quda::SolverParam::use_init_guess, warningQuda, quda::blas::xmyNorm(), quda::blas::xpy(), quda::blas::xpyHeavyQuarkResidualNorm(), xS_oldp, xSp, yp, and quda::blas::zero().
Member Data Documentation
ArSp
ColorSpinorField * quda::CG3::ArSp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
init
bool quda::CG3::init private
Definition at line 614 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
mat
const DiracMatrix& quda::CG3::mat private
Definition at line 610 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
matSloppy
const DiracMatrix& quda::CG3::matSloppy private
Definition at line 611 of file invert_quda.h.
Referenced by operator()().
rp
ColorSpinorField * quda::CG3::rp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
rS_oldp
ColorSpinorField * quda::CG3::rS_oldp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
rSp
ColorSpinorField * quda::CG3::rSp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
tmp2Sp
ColorSpinorField * quda::CG3::tmp2Sp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
tmpp
ColorSpinorField * quda::CG3::tmpp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
tmpSp
ColorSpinorField * quda::CG3::tmpSp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
xS_oldp
ColorSpinorField * quda::CG3::xS_oldp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
xSp
ColorSpinorField * quda::CG3::xSp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
yp
ColorSpinorField* quda::CG3::yp private
Definition at line 613 of file invert_quda.h.
Referenced by operator()(), and ~CG3().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_cg3_quda.cpp