QUDA: quda::DiracImprovedStaggered Class Reference
quda::DiracImprovedStaggered Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracImprovedStaggered (const DiracParam &param)
DiracImprovedStaggered (const DiracImprovedStaggered &dirac)
virtual ~DiracImprovedStaggered ()
DiracImprovedStaggered & operator= (const DiracImprovedStaggered &dirac)
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Attributes
cudaGaugeField & fatGauge
cudaGaugeField & longGauge
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Detailed Description
Definition at line 756 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracImprovedStaggered() [1/2]
quda::DiracImprovedStaggered::DiracImprovedStaggered (const DiracParam & param)
Definition at line 6 of file dirac_improved_staggered.cpp.
DiracImprovedStaggered() [2/2]
quda::DiracImprovedStaggered::DiracImprovedStaggered (const DiracImprovedStaggered & dirac)
Definition at line 9 of file dirac_improved_staggered.cpp.
~DiracImprovedStaggered()
quda::DiracImprovedStaggered::~DiracImprovedStaggered () virtual
Definition at line 12 of file dirac_improved_staggered.cpp.
Member Function Documentation
checkParitySpinor()
void quda::DiracImprovedStaggered::checkParitySpinor (const ColorSpinorField & in, const ColorSpinorField & out) const virtual
Reimplemented from quda::Dirac.
Definition at line 24 of file dirac_improved_staggered.cpp.
References errorQuda, fatGauge, quda::ColorSpinorField::Ndim(), quda::LatticeField::Precision(), QUDA_FULL_SITE_SUBSET, QUDA_PARITY_SITE_SUBSET, quda::ColorSpinorField::SiteSubset(), quda::ColorSpinorField::Stride(), quda::ColorSpinorField::Volume(), quda::LatticeField::VolumeCB(), and quda::ColorSpinorField::X().
Referenced by Dslash(), and DslashXpay().
Dslash()
void quda::DiracImprovedStaggered::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Implements quda::Dirac.
Definition at line 49 of file dirac_improved_staggered.cpp.
References quda::ApplyImprovedStaggered(), checkParitySpinor(), quda::Dirac::commDim, quda::Dirac::dagger, fatGauge, quda::Dirac::flops, longGauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracImprovedStaggeredPC::M(), and MdagM().
DslashXpay()
void quda::DiracImprovedStaggered::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Implements quda::Dirac.
Definition at line 57 of file dirac_improved_staggered.cpp.
References quda::ApplyImprovedStaggered(), checkParitySpinor(), quda::Dirac::commDim, quda::Dirac::dagger, fatGauge, quda::Dirac::flops, longGauge, quda::Dirac::profile, QUDA_DAG_NO, QUDA_DAG_YES, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracImprovedStaggeredPC::M(), MdagM(), quda::DiracImprovedStaggeredPC::prepare(), and quda::DiracImprovedStaggeredPC::reconstruct().
M()
void quda::DiracImprovedStaggered::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracImprovedStaggeredPC.
Definition at line 79 of file dirac_improved_staggered.cpp.
References quda::ApplyImprovedStaggered(), quda::Dirac::checkFullSpinor(), quda::Dirac::commDim, quda::Dirac::dagger, fatGauge, quda::Dirac::flops, longGauge, quda::Dirac::mass, quda::Dirac::profile, QUDA_DAG_NO, QUDA_DAG_YES, QUDA_INVALID_PARITY, and quda::ColorSpinorField::Volume().
MdagM()
void quda::DiracImprovedStaggered::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracImprovedStaggeredPC.
Definition at line 96 of file dirac_improved_staggered.cpp.
References quda::Dirac::deleteTmp(), Dslash(), DslashXpay(), quda::ColorSpinorField::Even(), quda::Dirac::mass, quda::Dirac::newTmp(), quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
operator=()
DiracImprovedStaggered & quda::DiracImprovedStaggered::operator= (const DiracImprovedStaggered & dirac)
Definition at line 14 of file dirac_improved_staggered.cpp.
References fatGauge, longGauge, and quda::Dirac::operator=().
Referenced by quda::DiracImprovedStaggeredPC::operator=().
prepare()
void quda::DiracImprovedStaggered::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracImprovedStaggeredPC.
Definition at line 111 of file dirac_improved_staggered.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracImprovedStaggered::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracImprovedStaggeredPC.
Definition at line 123 of file dirac_improved_staggered.cpp.
Member Data Documentation
fatGauge
cudaGaugeField& quda::DiracImprovedStaggered::fatGauge protected
Definition at line 759 of file dirac_quda.h.
Referenced by checkParitySpinor(), Dslash(), DslashXpay(), M(), and operator=().
longGauge
cudaGaugeField& quda::DiracImprovedStaggered::longGauge protected
Definition at line 760 of file dirac_quda.h.
Referenced by Dslash(), DslashXpay(), M(), and operator=().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_improved_staggered.cpp