QUDA: quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg > Class Template Reference
quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg > Class Template Reference
Public Member Functions
CalculateY (Arg &arg, const ColorSpinorField &meta, GaugeField &Y, GaugeField &X, GaugeField &Y_atomic, GaugeField &X_atomic)
virtual ~CalculateY ()
void apply (const cudaStream_t &stream)
void setDimension (int dim_)
void setDirection (QudaDirection dir_)
void setComputeType (ComputeType type_)
bool advanceAux (TuneParam &param) const
bool advanceSharedBytes (TuneParam &param) const
bool advanceTuneParam (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
void preTune ()
void postTune ()
Public Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Protected Member Functions
long long flops () const
long long bytes () const
unsigned int minThreads () const
bool tuneGridDim () const
bool tuneAuxDim () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const ColorSpinorField & meta
GaugeField & Y
GaugeField & X
GaugeField & Y_atomic
GaugeField & X_atomic
int dim
QudaDirection dir
ComputeType type
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg>
class quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >
Definition at line 32 of file coarse_op.cuh.
Constructor & Destructor Documentation
CalculateY()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::CalculateY (Arg & arg, const ColorSpinorField & meta, GaugeField & Y, GaugeField & X, GaugeField & Y_atomic, GaugeField & X_atomic) inline
Definition at line 180 of file coarse_op.cuh.
References quda::Tunable::aux, quda::LatticeField::AuxString(), comm_dim_partitioned_string(), quda::compile_type_str(), getOmpThreadStr(), quda::LatticeField::Location(), QUDA_CPU_FIELD_LOCATION, and QUDA_CUDA_FIELD_LOCATION.
~CalculateY()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> virtual quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::~CalculateY () inline virtual
Definition at line 194 of file coarse_op.cuh.
Member Function Documentation
advanceAux()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> bool quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceAux (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 643 of file coarse_op.cuh.
References quda::TuneParam::aux, quda::COMPUTE_VUV, deviceProp, quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::initTuneParam(), max_color_per_block, quda::TunableVectorYZ::resizeStep(), and quda::TunableVectorYZ::resizeVector().
advanceSharedBytes()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> bool quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceSharedBytes (TuneParam & param) const inline virtual
The goal here is to throttle the number of thread blocks per SM by over-allocating shared memory (in order to improve L2 utilization, etc.). We thus request the smallest amount of dynamic shared memory that guarantees throttling to a given number of blocks, in order to allow some extra leeway.
Reimplemented from quda::Tunable.
Definition at line 691 of file coarse_op.cuh.
References quda::Tunable::advanceSharedBytes(), quda::COMPUTE_COARSE_CLOVER, and quda::COMPUTE_VUV.
advanceTuneParam()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> bool quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 695 of file coarse_op.cuh.
References quda::Tunable::advanceTuneParam(), quda::LatticeField::Location(), quda::LatticeField::MemType(), QUDA_CUDA_FIELD_LOCATION, and QUDA_MEMORY_DEVICE.
apply()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 196 of file coarse_op.cuh.
References quda::activeTuning(), quda::alloc, quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::arg, quda::TuneParam::aux, quda::TuneParam::block, quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::Tunable::jitify_error, quda::LatticeField::Location(), pool_device_free, pool_device_malloc, QUDA_BACKWARDS, QUDA_CPU_FIELD_LOCATION, QUDA_FORWARDS, quda::reduce(), quda::TuneParam::shared_bytes, quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::sharedBytesPerBlock(), swap(), and quda::tuneLaunch().
Referenced by quda::calculateY().
bytes()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> long long quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 91 of file coarse_op.cuh.
References quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Bytes(), quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, and errorQuda.
defaultTuneParam()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorYZ.
Definition at line 716 of file coarse_op.cuh.
References quda::TuneParam::aux, quda::TuneParam::block, quda::COMPUTE_VUV, quda::TunableVectorYZ::defaultTuneParam(), and quda::TuneParam::grid.
flops()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> long long quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 47 of file coarse_op.cuh.
References quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, and errorQuda.
initTuneParam()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorYZ.
Definition at line 701 of file coarse_op.cuh.
References quda::TuneParam::aux, quda::TuneParam::block, quda::COMPUTE_VUV, quda::TuneParam::grid, and quda::TunableVectorYZ::initTuneParam().
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::advanceAux().
minThreads()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> unsigned int quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 145 of file coarse_op.cuh.
References quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, and errorQuda.
postTune()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 813 of file coarse_op.cuh.
References quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, errorQuda, quda::GaugeField::Gauge_p(), and quda::LatticeField::restore().
preTune()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 785 of file coarse_op.cuh.
References quda::LatticeField::backup(), quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, errorQuda, and quda::GaugeField::Gauge_p().
setComputeType()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setComputeType (ComputeType type_) inline
Set which computation we are doing
Definition at line 610 of file coarse_op.cuh.
References quda::COMPUTE_AV, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_UV, quda::COMPUTE_VUV, max_color_per_block, quda::TunableVectorYZ::resizeStep(), quda::TunableVectorYZ::resizeVector(), and quda::TunableVectorY::tune_block_x.
Referenced by quda::calculateY().
setDimension()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setDimension (int dim_) inline
Set which dimension we are working on (where applicable)
Definition at line 600 of file coarse_op.cuh.
Referenced by quda::calculateY().
setDirection()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> void quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::setDirection (QudaDirection dir_) inline
Set which direction we are working on (where applicable)
Definition at line 605 of file coarse_op.cuh.
Referenced by quda::calculateY().
sharedBytesPerBlock()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> unsigned int quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::sharedBytesPerBlock (const TuneParam & param) const inline protected virtual
Reimplemented from quda::TunableVectorY.
Definition at line 174 of file coarse_op.cuh.
References quda::COMPUTE_VUV, max_color_per_block, and quda::TunableVectorY::sharedBytesPerBlock().
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::apply().
tuneAuxDim()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> bool quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::tuneAuxDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 172 of file coarse_op.cuh.
References quda::COMPUTE_VUV.
tuneGridDim()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> bool quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 171 of file coarse_op.cuh.
tuneKey()
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> TuneKey quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 730 of file coarse_op.cuh.
References quda::Tunable::aux, quda::TuneKey::aux_n, quda::COMPUTE_AV, quda::COMPUTE_CLOVER_INV_MAX, quda::COMPUTE_COARSE_CLOVER, quda::COMPUTE_CONVERT, quda::COMPUTE_DIAGONAL, quda::COMPUTE_RESCALE, quda::COMPUTE_REVERSE_Y, quda::COMPUTE_TMAV, quda::COMPUTE_TMCAV, quda::COMPUTE_TMDIAGONAL, quda::COMPUTE_TWISTED_CLOVER_INV_MAX, quda::COMPUTE_UV, quda::COMPUTE_VUV, errorQuda, quda::LatticeField::Location(), quda::LatticeField::MemType(), QUDA_BACKWARDS, QUDA_CUDA_FIELD_LOCATION, QUDA_FORWARDS, QUDA_MEMORY_MAPPED, quda::blas::copy_ns::vol_str, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> Arg& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::arg protected
Definition at line 36 of file coarse_op.cuh.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::apply(), and quda::calculateY().
dim
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> int quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::dim protected
Definition at line 43 of file coarse_op.cuh.
dir
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> QudaDirection quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::dir protected
Definition at line 44 of file coarse_op.cuh.
meta
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> const ColorSpinorField& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::meta protected
Definition at line 37 of file coarse_op.cuh.
type
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> ComputeType quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::type protected
Definition at line 45 of file coarse_op.cuh.
X
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> GaugeField& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::X protected
Definition at line 39 of file coarse_op.cuh.
X_atomic
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> GaugeField& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::X_atomic protected
Definition at line 41 of file coarse_op.cuh.
Y
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> GaugeField& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::Y protected
Definition at line 38 of file coarse_op.cuh.
Y_atomic
template<bool from_coarse, typename Float, int fineSpin, int fineColor, int coarseSpin, int coarseColor, typename Arg> GaugeField& quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::Y_atomic protected
Definition at line 40 of file coarse_op.cuh.
The documentation for this class was generated from the following file:
lib/coarse_op.cuh