QUDA: quda::DiracDomainWall Class Reference
quda::DiracDomainWall Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Member Functions
void checkDWF (const ColorSpinorField &out, const ColorSpinorField &in) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Detailed Description
Definition at line 346 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracDomainWall() [1/2]
quda::DiracDomainWall::DiracDomainWall (const DiracParam & param)
Definition at line 7 of file dirac_domain_wall.cpp.
DiracDomainWall() [2/2]
quda::DiracDomainWall::DiracDomainWall (const DiracDomainWall & dirac)
Definition at line 15 of file dirac_domain_wall.cpp.
~DiracDomainWall()
quda::DiracDomainWall::~DiracDomainWall () virtual
Definition at line 23 of file dirac_domain_wall.cpp.
Member Function Documentation
checkDWF()
void quda::DiracDomainWall::checkDWF (const ColorSpinorField & out, const ColorSpinorField & in) const protected
Definition at line 35 of file dirac_domain_wall.cpp.
References errorQuda, Ls, quda::ColorSpinorField::Ndim(), and quda::ColorSpinorField::X().
Referenced by Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), DslashXpay(), and quda::DiracDomainWallPC::M().
Dslash()
void quda::DiracDomainWall::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 42 of file dirac_domain_wall.cpp.
References quda::ApplyDomainWall5D(), checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, Ls, quda::Dirac::mass, quda::Dirac::profile, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracDomainWallPC::M().
DslashXpay()
void quda::DiracDomainWall::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Reimplemented from quda::DiracWilson.
Definition at line 57 of file dirac_domain_wall.cpp.
References quda::ApplyDomainWall5D(), checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, Ls, quda::Dirac::mass, quda::Dirac::profile, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracDomainWallPC::M(), quda::DiracDomainWallPC::prepare(), and quda::DiracDomainWallPC::reconstruct().
M()
void quda::DiracDomainWall::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, and quda::DiracDomainWallPC.
Definition at line 73 of file dirac_domain_wall.cpp.
References quda::ApplyDomainWall5D(), quda::Dirac::checkFullSpinor(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, kappa5, Ls, quda::Dirac::mass, quda::Dirac::profile, QUDA_INVALID_PARITY, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by MdagM().
MdagM()
void quda::DiracDomainWall::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, and quda::DiracDomainWallPC.
Definition at line 85 of file dirac_domain_wall.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
operator=()
DiracDomainWall & quda::DiracDomainWall::operator= (const DiracDomainWall & dirac)
Definition at line 25 of file dirac_domain_wall.cpp.
References kappa5, m5, and quda::DiracWilson::operator=().
Referenced by quda::DiracDomainWallPC::operator=(), quda::DiracDomainWall4D::operator=(), and quda::DiracMobius::operator=().
prepare()
void quda::DiracDomainWall::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, and quda::DiracDomainWallPC.
Definition at line 97 of file dirac_domain_wall.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracDomainWall::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, and quda::DiracDomainWallPC.
Definition at line 109 of file dirac_domain_wall.cpp.
Member Data Documentation
kappa5
double quda::DiracDomainWall::kappa5 protected
Definition at line 350 of file dirac_quda.h.
Referenced by M(), quda::DiracDomainWallPC::M(), quda::DiracDomainWall4D::M(), quda::DiracDomainWall4DPC::M(), operator=(), quda::DiracDomainWallPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracDomainWallPC::reconstruct(), and quda::DiracDomainWall4DPC::reconstruct().
Ls
int quda::DiracDomainWall::Ls protected
Definition at line 351 of file dirac_quda.h.
Referenced by checkDWF(), quda::DiracMobius::DiracMobius(), Dslash(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), DslashXpay(), M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), and quda::DiracMobius::operator=().
m5
double quda::DiracDomainWall::m5 protected
Definition at line 349 of file dirac_quda.h.
Referenced by quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracMobius::Dslash5Xpay(), quda::DiracMobius::M(), and operator=().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_domain_wall.cpp