QUDA: quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder > Class Template Reference
quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder > Class Template Reference
Public Member Functions
CopyGaugeEx (CopyGaugeExArg< OutOrder, InOrder > &arg, const GaugeField &meta, QudaFieldLocation location)
virtual ~CopyGaugeEx ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
CopyGaugeExArg< OutOrder, InOrder > arg
const GaugeField & meta
QudaFieldLocation location
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename FloatOut, typename FloatIn, int length, typename OutOrder, typename InOrder>
class quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >
Definition at line 111 of file copy_gauge_extended.cu.
Constructor & Destructor Documentation
CopyGaugeEx()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::CopyGaugeEx (CopyGaugeExArg< OutOrder, InOrder > & arg, const GaugeField & meta, QudaFieldLocation location) inline
Definition at line 124 of file copy_gauge_extended.cu.
References quda::CopyGaugeExArg< OutOrder, InOrder >::geometry, quda::CopyGaugeExArg< OutOrder, InOrder >::in, and quda::CopyGaugeExArg< OutOrder, InOrder >::out.
~CopyGaugeEx()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > virtual quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::~CopyGaugeEx () inline virtual
Definition at line 128 of file copy_gauge_extended.cu.
Member Function Documentation
apply()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > void quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 130 of file copy_gauge_extended.cu.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, quda::CopyGaugeExArg< OutOrder, InOrder >::regularToextended, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
bytes()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > long long quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 149 of file copy_gauge_extended.cu.
References quda::CopyGaugeExArg< OutOrder, InOrder >::in, quda::CopyGaugeExArg< OutOrder, InOrder >::out, and quda::CopyGaugeExArg< OutOrder, InOrder >::volume.
flops()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > long long quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 148 of file copy_gauge_extended.cu.
minThreads()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > unsigned int quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 121 of file copy_gauge_extended.cu.
References quda::CopyGaugeExArg< OutOrder, InOrder >::volume.
sharedBytesPerBlock()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > unsigned int quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 118 of file copy_gauge_extended.cu.
sharedBytesPerThread()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > unsigned int quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 117 of file copy_gauge_extended.cu.
tuneGridDim()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > bool quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 120 of file copy_gauge_extended.cu.
tuneKey()
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > TuneKey quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 144 of file copy_gauge_extended.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > CopyGaugeExArg<OutOrder,InOrder> quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::arg private
Definition at line 112 of file copy_gauge_extended.cu.
location
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > QudaFieldLocation quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::location private
Definition at line 114 of file copy_gauge_extended.cu.
meta
template<typename FloatOut , typename FloatIn , int length, typename OutOrder , typename InOrder > const GaugeField& quda::CopyGaugeEx< FloatOut, FloatIn, length, OutOrder, InOrder >::meta private
Definition at line 113 of file copy_gauge_extended.cu.
The documentation for this class was generated from the following file:
lib/copy_gauge_extended.cu