QUDA: quda::BiCGstab Class Reference
quda::BiCGstab Class Reference
#include <invert_quda.h>
Public Member Functions
BiCGstab (DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, SolverParam &param, TimeProfile &profile)
virtual ~BiCGstab ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
DiracMatrix & mat
const DiracMatrix & matSloppy
const DiracMatrix & matPrecon
ColorSpinorField * yp
ColorSpinorField * rp
ColorSpinorField * pp
ColorSpinorField * vp
ColorSpinorField * tmpp
ColorSpinorField * tp
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 707 of file invert_quda.h.
Constructor & Destructor Documentation
BiCGstab()
quda::BiCGstab::BiCGstab (DiracMatrix & mat, DiracMatrix & matSloppy, DiracMatrix & matPrecon, SolverParam & param, TimeProfile & profile)
Definition at line 17 of file inv_bicgstab_quda.cpp.
~BiCGstab()
quda::BiCGstab::~BiCGstab () virtual
Definition at line 22 of file inv_bicgstab_quda.cpp.
References init, pp, quda::Solver::profile, quda::QUDA_PROFILE_FREE, rp, tmpp, tp, vp, and yp.
Member Function Documentation
operator()()
void quda::BiCGstab::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 51 of file inv_bicgstab_quda.cpp.
References quda::abs(), quda::blas::caxpbypzYmbw(), quda::blas::caxpbypzYmbwcDotProductUYNormY(), quda::blas::caxpy(), quda::blas::cDotProduct(), quda::blas::cDotProductNormA(), quda::SolverParam::compute_null_vector, quda::conj(), quda::Solver::convergence(), quda::blas::copy(), quda::ColorSpinorParam::create, quda::ColorSpinorField::Create(), csParam, quda::blas::cxpaypbz(), quda::SolverParam::delta, errorQuda, quda::fillInnerSolveParam(), quda::blas::flops, quda::DiracMatrix::flops(), getVerbosity(), quda::SolverParam::gflops, quda::SolverParam::heavy_quark_check, quda::blas::HeavyQuarkResidualNorm(), init, quda::SolverParam::is_preconditioner, quda::SolverParam::iter, quda::TimeProfile::Last(), mat, matPrecon, matSloppy, quda::SolverParam::maxiter, quda::blas::norm2(), omega, quda::Solver::param, quda::SolverParam::pipeline, pp, quda::LatticeField::Precision(), quda::SolverParam::precision_sloppy, quda::SolverParam::preserve_source, printfQuda, quda::Solver::PrintStats(), quda::Solver::PrintSummary(), quda::Solver::profile, QUDA_COMPUTE_NULL_VECTOR_NO, QUDA_COMPUTE_NULL_VECTOR_YES, QUDA_DEBUG_VERBOSE, QUDA_HEAVY_QUARK_RESIDUAL, QUDA_NULL_FIELD_CREATE, QUDA_PRESERVE_SOURCE_NO, quda::QUDA_PROFILE_COMPUTE, quda::QUDA_PROFILE_EPILOGUE, quda::QUDA_PROFILE_FREE, quda::QUDA_PROFILE_PREAMBLE, QUDA_USE_INIT_GUESS_YES, QUDA_VERBOSE, QUDA_ZERO_FIELD_CREATE, quda::reliable(), quda::SolverParam::residual_type, rp, quda::SolverParam::secs, quda::ColorSpinorParam::setPrecision(), quda::sqrt(), quda::Solver::stopping(), tmp, tmpp, quda::SolverParam::tol, quda::SolverParam::tol_hq, tp, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, updateR(), quda::SolverParam::use_init_guess, quda::SolverParam::use_sloppy_partial_accumulator, vp, warningQuda, quda::blas::xmyNorm(), quda::blas::xpy(), quda::blas::xpyHeavyQuarkResidualNorm(), yp, and quda::blas::zero().
Member Data Documentation
init
bool quda::BiCGstab::init private
Definition at line 716 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
mat
DiracMatrix& quda::BiCGstab::mat private
Definition at line 710 of file invert_quda.h.
Referenced by operator()().
matPrecon
const DiracMatrix& quda::BiCGstab::matPrecon private
Definition at line 712 of file invert_quda.h.
Referenced by operator()().
matSloppy
const DiracMatrix& quda::BiCGstab::matSloppy private
Definition at line 711 of file invert_quda.h.
Referenced by operator()().
pp
ColorSpinorField * quda::BiCGstab::pp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
rp
ColorSpinorField * quda::BiCGstab::rp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
tmpp
ColorSpinorField * quda::BiCGstab::tmpp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
tp
ColorSpinorField * quda::BiCGstab::tp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
vp
ColorSpinorField * quda::BiCGstab::vp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
yp
ColorSpinorField* quda::BiCGstab::yp private
Definition at line 715 of file invert_quda.h.
Referenced by operator()(), and ~BiCGstab().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_bicgstab_quda.cpp