QUDA: quda::ShiftColorSpinorField< Output, Input > Class Template Reference
quda::ShiftColorSpinorField< Output, Input > Class Template Reference
Public Member Functions
ShiftColorSpinorField (const ShiftColorSpinorField< Output, Input > &arg, QudaFieldLocation location)
virtual ~ShiftColorSpinorField ()
void apply (const cudaStream_t &stream)
virtual void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
long long flops () const
long long bytes () const
TuneKey tuneKey () const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
int sharedBytesPerThread () const
int sharedBytesPerBlock (const TuneParam &) cont
bool advanceGridDim (TuneParam &param) const
bool advanceBlockDim (TuneParam &param) const
Private Attributes
ShiftColorSpinorFieldArg< Output, Input > arg
const int * X
Additional Inherited Members
Protected Member Functions inherited from quda::Tunable
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const =0
virtual unsigned int minThreads () const
virtual bool tuneGridDim () const
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Output, typename Input>
class quda::ShiftColorSpinorField< Output, Input >
Definition at line 118 of file shift_quark_field.cu.
Constructor & Destructor Documentation
ShiftColorSpinorField()
template<typename Output, typename Input> quda::ShiftColorSpinorField< Output, Input >::ShiftColorSpinorField (const ShiftColorSpinorField< Output, Input > & arg, QudaFieldLocation location) inline
Definition at line 154 of file shift_quark_field.cu.
~ShiftColorSpinorField()
template<typename Output, typename Input> virtual quda::ShiftColorSpinorField< Output, Input >::~ShiftColorSpinorField () inline virtual
Definition at line 157 of file shift_quark_field.cu.
Member Function Documentation
advanceBlockDim()
template<typename Output, typename Input> bool quda::ShiftColorSpinorField< Output, Input >::advanceBlockDim (TuneParam & param) const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 130 of file shift_quark_field.cu.
References quda::TuneParam::block, deviceProp, errorQuda, quda::TuneParam::grid, and quda::ShiftColorSpinorFieldArg< Output, Input >::length.
advanceGridDim()
template<typename Output, typename Input> bool quda::ShiftColorSpinorField< Output, Input >::advanceGridDim (TuneParam & param) const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 128 of file shift_quark_field.cu.
apply()
template<typename Output, typename Input> void quda::ShiftColorSpinorField< Output, Input >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 159 of file shift_quark_field.cu.
References quda::arg(), quda::TuneParam::block, errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, QUDA_CUDA_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
bytes()
template<typename Output, typename Input> long long quda::ShiftColorSpinorField< Output, Input >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 191 of file shift_quark_field.cu.
defaultTuneParam()
template<typename Output, typename Input> void quda::ShiftColorSpinorField< Output, Input >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::Tunable.
Definition at line 186 of file shift_quark_field.cu.
flops()
template<typename Output, typename Input> long long quda::ShiftColorSpinorField< Output, Input >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 190 of file shift_quark_field.cu.
initTuneParam()
template<typename Output, typename Input> virtual void quda::ShiftColorSpinorField< Output, Input >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 171 of file shift_quark_field.cu.
References quda::TuneParam::block, deviceProp, errorQuda, quda::TuneParam::grid, quda::ShiftColorSpinorFieldArg< Output, Input >::length, and quda::TuneParam::shared_bytes.
sharedBytesPerBlock()
template<typename Output, typename Input> int quda::ShiftColorSpinorField< Output, Input >::sharedBytesPerBlock (const TuneParam &) inline private
Definition at line 125 of file shift_quark_field.cu.
sharedBytesPerThread()
template<typename Output, typename Input> int quda::ShiftColorSpinorField< Output, Input >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 124 of file shift_quark_field.cu.
tuneKey()
template<typename Output, typename Input> TuneKey quda::ShiftColorSpinorField< Output, Input >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 193 of file shift_quark_field.cu.
References quda::ShiftColorSpinorFieldArg< Output, Input >::in.
Member Data Documentation
arg
template<typename Output, typename Input> ShiftColorSpinorFieldArg<Output,Input> quda::ShiftColorSpinorField< Output, Input >::arg private
Definition at line 121 of file shift_quark_field.cu.
X
template<typename Output, typename Input> const int* quda::ShiftColorSpinorField< Output, Input >::X private
Definition at line 122 of file shift_quark_field.cu.
The documentation for this class was generated from the following file:
lib/shift_quark_field.cu