QUDA: quda::DiracWilson Class Reference
quda::DiracWilson Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Member Functions
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 205 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracWilson() [1/3]
quda::DiracWilson::DiracWilson (const DiracParam & param)
Definition at line 8 of file dirac_wilson.cpp.
DiracWilson() [2/3]
quda::DiracWilson::DiracWilson (const DiracWilson & dirac)
Definition at line 10 of file dirac_wilson.cpp.
DiracWilson() [3/3]
quda::DiracWilson::DiracWilson (const DiracParam & param, const int nDims)
Definition at line 13 of file dirac_wilson.cpp.
~DiracWilson()
quda::DiracWilson::~DiracWilson () virtual
Definition at line 15 of file dirac_wilson.cpp.
Member Function Documentation
createCoarseOp()
void quda::DiracWilson::createCoarseOp (GaugeField & Y, GaugeField & X, const Transfer & T, double kappa, double mass = 0., double mu = 0., double mu_factor = 0.) const virtual
Create the coarse Wilson operator.
Parameters
Y[out] Coarse link field
X[out] Coarse clover field
T[in] Transfer operator defining the coarse grid
mass Mass parameter for the coarse operator (hard coded to 0 when CoarseOp is called)
kappa Kappa parameter for the coarse operator
Reimplemented from quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracCloverPC, and quda::DiracClover.
Definition at line 97 of file dirac_wilson.cpp.
References quda::CoarseOp(), quda::Dirac::gauge, QUDA_MATPC_INVALID, QUDA_WILSON_DIRAC, quda::ColorSpinorField::TwistFlavor(), and quda::Transfer::Vectors().
Dslash()
void quda::DiracWilson::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracDomainWall, and quda::DiracCloverPC.
Definition at line 25 of file dirac_wilson.cpp.
References quda::ApplyWilson(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracTwistedCloverPC::Dslash(), and quda::DiracWilsonPC::M().
DslashXpay()
void quda::DiracWilson::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracDomainWall, quda::DiracCloverPC, and quda::DiracClover.
Definition at line 35 of file dirac_wilson.cpp.
References quda::ApplyWilson(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracWilsonPC::M(), quda::DiracCloverPC::M(), quda::DiracTwistedCloverPC::M(), quda::DiracWilsonPC::prepare(), quda::DiracCloverPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), and quda::DiracTwistedCloverPC::reconstruct().
initConstants()
void quda::DiracWilson::initConstants () protected
M()
void quda::DiracWilson::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilsonPC.
Definition at line 46 of file dirac_wilson.cpp.
References quda::ApplyWilson(), quda::Dirac::checkFullSpinor(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::kappa, quda::Dirac::profile, QUDA_INVALID_PARITY, and quda::ColorSpinorField::Volume().
Referenced by MdagM().
MdagM()
void quda::DiracWilson::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilsonPC.
Definition at line 54 of file dirac_wilson.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
operator=()
DiracWilson & quda::DiracWilson::operator= (const DiracWilson & dirac)
Definition at line 17 of file dirac_wilson.cpp.
References quda::Dirac::operator=().
Referenced by quda::DiracWilsonPC::operator=(), quda::DiracClover::operator=(), quda::DiracDomainWall::operator=(), quda::DiracTwistedMass::operator=(), and quda::DiracTwistedClover::operator=().
prepare()
void quda::DiracWilson::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilsonPC.
Definition at line 67 of file dirac_wilson.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracWilson::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Implements quda::Dirac.
Reimplemented in quda::DiracTwistedCloverPC, quda::DiracTwistedClover, quda::DiracTwistedMassPC, quda::DiracTwistedMass, quda::DiracMobiusPC, quda::DiracMobius, quda::DiracDomainWall4DPC, quda::DiracDomainWall4D, quda::DiracDomainWallPC, quda::DiracDomainWall, quda::DiracCloverPC, quda::DiracClover, and quda::DiracWilsonPC.
Definition at line 79 of file dirac_wilson.cpp.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_wilson.cpp