QUDA: quda::DiracDomainWallPC Class Reference
quda::DiracDomainWallPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracDomainWallPC (const DiracParam &param)
DiracDomainWallPC (const DiracDomainWallPC &dirac)
virtual ~DiracDomainWallPC ()
DiracDomainWallPC & operator= (const DiracDomainWallPC &dirac)
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracDomainWall
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracDomainWall
void checkDWF (const ColorSpinorField &out, const ColorSpinorField &in) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracDomainWall
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 376 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracDomainWallPC() [1/2]
quda::DiracDomainWallPC::DiracDomainWallPC (const DiracParam & param)
Definition at line 115 of file dirac_domain_wall.cpp.
DiracDomainWallPC() [2/2]
quda::DiracDomainWallPC::DiracDomainWallPC (const DiracDomainWallPC & dirac)
Definition at line 121 of file dirac_domain_wall.cpp.
~DiracDomainWallPC()
quda::DiracDomainWallPC::~DiracDomainWallPC () virtual
Definition at line 127 of file dirac_domain_wall.cpp.
Member Function Documentation
M()
void quda::DiracDomainWallPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Definition at line 142 of file dirac_domain_wall.cpp.
References quda::DiracDomainWall::checkDWF(), quda::Dirac::deleteTmp(), quda::DiracDomainWall::Dslash(), quda::DiracDomainWall::DslashXpay(), errorQuda, quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
Referenced by MdagM().
MdagM()
void quda::DiracDomainWallPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Definition at line 162 of file dirac_domain_wall.cpp.
References quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp2.
operator=()
DiracDomainWallPC & quda::DiracDomainWallPC::operator= (const DiracDomainWallPC & dirac)
Definition at line 132 of file dirac_domain_wall.cpp.
References quda::DiracDomainWall::operator=().
prepare()
void quda::DiracDomainWallPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Definition at line 172 of file dirac_domain_wall.cpp.
References quda::DiracDomainWall::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
reconstruct()
void quda::DiracDomainWallPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Definition at line 201 of file dirac_domain_wall.cpp.
References quda::Dirac::checkFullSpinor(), quda::DiracDomainWall::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::DiracDomainWall::kappa5, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_domain_wall.cpp