QUDA: quda::GaugeLaplacePC Class Reference
quda::GaugeLaplacePC Class Reference
Even-odd preconditioned Gauge Laplace operator.
#include <dirac_quda.h>
Public Member Functions
GaugeLaplacePC (const DiracParam &param)
GaugeLaplacePC (const GaugeLaplacePC &laplace)
virtual ~GaugeLaplacePC ()
GaugeLaplacePC & operator= (const GaugeLaplacePC &laplace)
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::GaugeLaplace
GaugeLaplace (const DiracParam &param)
GaugeLaplace (const GaugeLaplace &laplace)
virtual ~GaugeLaplace ()
GaugeLaplace & operator= (const GaugeLaplace &laplace)
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse operator (virtual parent)
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Even-odd preconditioned Gauge Laplace operator.
Definition at line 1047 of file dirac_quda.h.
Constructor & Destructor Documentation
GaugeLaplacePC() [1/2]
quda::GaugeLaplacePC::GaugeLaplacePC (const DiracParam & param)
Definition at line 86 of file gauge_laplace.cpp.
GaugeLaplacePC() [2/2]
quda::GaugeLaplacePC::GaugeLaplacePC (const GaugeLaplacePC & laplace)
Definition at line 88 of file gauge_laplace.cpp.
~GaugeLaplacePC()
quda::GaugeLaplacePC::~GaugeLaplacePC () virtual
Definition at line 90 of file gauge_laplace.cpp.
Member Function Documentation
M()
void quda::GaugeLaplacePC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::GaugeLaplace.
Definition at line 98 of file gauge_laplace.cpp.
References quda::Dirac::deleteTmp(), quda::GaugeLaplace::Dslash(), quda::GaugeLaplace::DslashXpay(), errorQuda, quda::Dirac::kappa, quda::Dirac::matpcType, quda::Dirac::newTmp(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
Referenced by MdagM().
MdagM()
void quda::GaugeLaplacePC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::GaugeLaplace.
Definition at line 117 of file gauge_laplace.cpp.
References quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp2.
operator=()
GaugeLaplacePC & quda::GaugeLaplacePC::operator= (const GaugeLaplacePC & laplace)
Definition at line 92 of file gauge_laplace.cpp.
References quda::GaugeLaplace::operator=().
prepare()
void quda::GaugeLaplacePC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::GaugeLaplace.
Definition at line 125 of file gauge_laplace.cpp.
References quda::GaugeLaplace::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
reconstruct()
void quda::GaugeLaplacePC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::GaugeLaplace.
Definition at line 154 of file gauge_laplace.cpp.
References quda::Dirac::checkFullSpinor(), quda::GaugeLaplace::DslashXpay(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::kappa, quda::Dirac::matpcType, quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, and QUDA_ODD_PARITY.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/gauge_laplace.cpp