QUDA: quda::DiracTwistedClover Class Reference
quda::DiracTwistedClover Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracTwistedClover (const DiracTwistedClover &dirac)
DiracTwistedClover (const DiracParam &param, const int nDim)
virtual ~DiracTwistedClover ()
DiracTwistedClover & operator= (const DiracTwistedClover &dirac)
void TwistClover (ColorSpinorField &out, const ColorSpinorField &in, const int parity) const
virtual void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
virtual void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
virtual void M (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
virtual void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
virtual void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
double Mu () const
void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass, double mu, double mu_factor=0.) const
Create the coarse twisted-clover operator.
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Protected Member Functions
void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
void twistedCloverApply (ColorSpinorField &out, const ColorSpinorField &in, const QudaTwistGamma5Type twistType, const int parity) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes
double mu
double epsilon
cudaCloverField & clover
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Detailed Description
Definition at line 601 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracTwistedClover() [1/2]
quda::DiracTwistedClover::DiracTwistedClover (const DiracTwistedClover & dirac)
Definition at line 18 of file dirac_twisted_clover.cpp.
DiracTwistedClover() [2/2]
quda::DiracTwistedClover::DiracTwistedClover (const DiracParam & param, const int nDim)
Definition at line 10 of file dirac_twisted_clover.cpp.
~DiracTwistedClover()
quda::DiracTwistedClover::~DiracTwistedClover () virtual
Definition at line 26 of file dirac_twisted_clover.cpp.
Member Function Documentation
checkParitySpinor()
void quda::DiracTwistedClover::checkParitySpinor (const ColorSpinorField & out, const ColorSpinorField & in) const protected virtual
Reimplemented from quda::Dirac.
Definition at line 39 of file dirac_twisted_clover.cpp.
References quda::Dirac::checkParitySpinor(), clover, errorQuda, quda::ColorSpinorField::Volume(), and quda::LatticeField::VolumeCB().
Referenced by quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedCloverPC::DslashXpay(), and twistedCloverApply().
createCoarseOp()
void quda::DiracTwistedClover::createCoarseOp (GaugeField & Y, GaugeField & X, const Transfer & T, double kappa, double mass, double mu, double mu_factor = 0.) const virtual
Create the coarse twisted-clover operator.
Parameters
T[in] Transfer operator defining the coarse grid
Y[out] Coarse link field
X[out] Coarse clover field
kappa Kappa parameter for the coarse operator
mass Mass parameter for the coarse operator (gets explicitly built into clover, hard coded to zero for non-staggered ops)
mu TM mu parameter for the coarse operator
mu_factor multiplicative factor for the mu parameter
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 127 of file dirac_twisted_clover.cpp.
References clover, quda::CoarseOp(), quda::Dirac::gauge, QUDA_MATPC_INVALID, QUDA_TWISTED_CLOVER_DIRAC, quda::ColorSpinorField::TwistFlavor(), and quda::Transfer::Vectors().
Dslash()
void quda::DiracTwistedClover::Dslash (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 64 of file dirac_twisted_clover.cpp.
References errorQuda.
DslashXpay()
void quda::DiracTwistedClover::DslashXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 70 of file dirac_twisted_clover.cpp.
References quda::ApplyTwistedClover(), clover, quda::Dirac::commDim, quda::Dirac::dagger, errorQuda, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::kappa, mu, quda::Dirac::profile, QUDA_TWIST_SINGLET, quda::ColorSpinorField::TwistFlavor(), and quda::ColorSpinorField::Volume().
Referenced by quda::DiracTwistedCloverPC::M().
M()
void quda::DiracTwistedClover::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 84 of file dirac_twisted_clover.cpp.
References quda::ApplyTwistedClover(), quda::Dirac::checkFullSpinor(), clover, quda::Dirac::commDim, quda::Dirac::dagger, errorQuda, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::kappa, mu, quda::Dirac::profile, QUDA_INVALID_PARITY, QUDA_TWIST_INVALID, QUDA_TWIST_NO, quda::ColorSpinorField::TwistFlavor(), and quda::ColorSpinorField::Volume().
Referenced by MdagM().
MdagM()
void quda::DiracTwistedClover::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 99 of file dirac_twisted_clover.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
Mu()
double quda::DiracTwistedClover::Mu () const inline virtual
Reimplemented from quda::Dirac.
Definition at line 632 of file dirac_quda.h.
References quda::DiracParam::kappa, quda::DiracParam::mass, quda::DiracParam::mu, quda::DiracParam::mu_factor, and X.
operator=()
DiracTwistedClover & quda::DiracTwistedClover::operator= (const DiracTwistedClover & dirac)
Definition at line 28 of file dirac_twisted_clover.cpp.
References clover, and quda::DiracWilson::operator=().
Referenced by quda::DiracTwistedCloverPC::operator=().
prepare()
void quda::DiracTwistedClover::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 110 of file dirac_twisted_clover.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracTwistedClover::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracWilson.
Reimplemented in quda::DiracTwistedCloverPC.
Definition at line 121 of file dirac_twisted_clover.cpp.
TwistClover()
void quda::DiracTwistedClover::TwistClover (ColorSpinorField & out, const ColorSpinorField & in, const int parity) const
Definition at line 59 of file dirac_twisted_clover.cpp.
References QUDA_TWIST_GAMMA5_DIRECT, and twistedCloverApply().
twistedCloverApply()
void quda::DiracTwistedClover::twistedCloverApply (ColorSpinorField & out, const ColorSpinorField & in, const QudaTwistGamma5Type twistType, const int parity) const protected
Definition at line 48 of file dirac_twisted_clover.cpp.
References quda::ApplyTwistClover(), checkParitySpinor(), clover, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::kappa, mu, QUDA_TWIST_GAMMA5_INVERSE, and quda::ColorSpinorField::Volume().
Referenced by TwistClover(), and quda::DiracTwistedCloverPC::TwistCloverInv().
Member Data Documentation
clover
cudaCloverField& quda::DiracTwistedClover::clover protected
Definition at line 606 of file dirac_quda.h.
Referenced by checkParitySpinor(), createCoarseOp(), quda::DiracTwistedCloverPC::createCoarseOp(), quda::DiracTwistedCloverPC::Dslash(), DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), M(), operator=(), and twistedCloverApply().
epsilon
double quda::DiracTwistedClover::epsilon protected
Definition at line 605 of file dirac_quda.h.
mu
double quda::DiracTwistedClover::mu protected
Definition at line 604 of file dirac_quda.h.
Referenced by quda::DiracTwistedCloverPC::Dslash(), DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), M(), and twistedCloverApply().
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_twisted_clover.cpp