QUDA: quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex > Class Template Reference
quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex > Class Template Reference
#include <color_spinor_field_order.h>
Public Member Functions
FieldOrderCB (const ColorSpinorField &field, int nFace=1, void *v_=0, void **ghost_=0)
void resetGhost (const ColorSpinorField &a, void *const *ghost_) const
void resetScale (Float max)
__device__ __host__ const complex< Float > operator() (int parity, int x_cb, int s, int c, int n=0) const
__device__ __host__ fieldorder_wrapper< Float, storeFloat > operator() (int parity, int x_cb, int s, int c, int n=0)
__device__ __host__ const complex< Float > Ghost (int dim, int dir, int parity, int x_cb, int s, int c, int n=0) const
__device__ __host__ fieldorder_wrapper< Float, ghostFloat > Ghost (int dim, int dir, int parity, int x_cb, int s, int c, int n=0, Float max=0)
__device__ __host__ void LatticeIndex (int y[QUDA_MAX_DIM], int i) const
__device__ __host__ void OffsetIndex (int &i, int y[QUDA_MAX_DIM]) const
__device__ __host__ int X (int d) const
__device__ __host__ const int * X () const
__device__ __host__ int Ncolor () const
__device__ __host__ int Nspin () const
__device__ __host__ int Nvec () const
__device__ __host__ int Nparity () const
__device__ __host__ int VolumeCB () const
__device__ __host__ int Ndim () const
__device__ __host__ QudaGammaBasis GammaBasis () const
__host__ double norm2 (bool global=true) const
__host__ double abs_max (bool global=true) const
size_t Bytes () const
Protected Attributes
complex< storeFloat > * v
const AccessorCB< storeFloat, nSpin, nColor, nVec, order > accessor
union {
norm_type * norm
Float scale
};
union {
Float scale_inv
int norm_offset
};
complex< ghostFloat > * ghost [8]
norm_type * ghost_norm [8]
int x [QUDA_MAX_DIM]
const int volumeCB
const int nDim
const QudaGammaBasis gammaBasis
const int siteSubset
const int nParity
const QudaFieldLocation location
const GhostAccessorCB< ghostFloat, nSpin, nColor, nVec, order > ghostAccessor
Float ghost_scale
Float ghost_scale_inv
Static Protected Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
static constexpr bool ghost_fixed = fixed_point<Float,ghostFloat>()
static constexpr bool block_float_ghost = !fixed && ghost_fixed
Private Types
typedef float norm_type
Detailed Description
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false>
class quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >
Definition at line 468 of file color_spinor_field_order.h.
Member Typedef Documentation
norm_type
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> typedef float quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::norm_type private
Definition at line 470 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
FieldOrderCB()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::FieldOrderCB (const ColorSpinorField & field, int nFace = 1, void * v_ = 0, void ** ghost_ = 0) inline
Constructor for the FieldOrderCB class
Parameters
field The field that we are accessing
Definition at line 507 of file color_spinor_field_order.h.
Member Function Documentation
abs_max()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __host__ double quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::abs_max (bool global = true) const inline
Returns the Linfinity norm of the field
Parameters
[in] global Whether to do a global or process local Linfinity reduction
Returns
Linfinity norm
Definition at line 766 of file color_spinor_field_order.h.
Referenced by quda::genericCompare().
Bytes()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> size_t quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Bytes () const inline
Definition at line 782 of file color_spinor_field_order.h.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::bytes().
GammaBasis()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ QudaGammaBasis quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::GammaBasis () const inline
Returns the field geometric dimension
Definition at line 739 of file color_spinor_field_order.h.
Ghost() [1/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ const complex<Float> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Ghost (int dim, int dir, int parity, int x_cb, int s, int c, int n = 0) const inline
Read-only complex-member accessor function for the ghost zone. The last parameter n is only used for indexed into the packed null-space vectors.
Parameters
x 1-d checkerboard site index
s spin index
c color index
v vector number
Definition at line 616 of file color_spinor_field_order.h.
Ghost() [2/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ fieldorder_wrapper<Float,ghostFloat> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Ghost (int dim, int dir, int parity, int x_cb, int s, int c, int n = 0, Float max = 0) inline
Writable complex-member accessor function for the ghost zone. The last parameter n is only used for indexed into the packed null-space vectors.
Parameters
x 1-d checkerboard site index
s spin index
c color index
n vector number
max site-element max (only when using block-float format)
Definition at line 652 of file color_spinor_field_order.h.
LatticeIndex()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ void quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::LatticeIndex (int y[QUDA_MAX_DIM], int i) const inline
Convert from 1-dimensional index to the n-dimensional spatial index. With full fields, we assume that the field is even-odd ordered. The lattice coordinates that are computed here are full-field coordinates.
Definition at line 668 of file color_spinor_field_order.h.
Ncolor()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Ncolor () const inline
Returns the number of field colors
Definition at line 720 of file color_spinor_field_order.h.
Ndim()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Ndim () const inline
Returns the field geometric dimension
Definition at line 736 of file color_spinor_field_order.h.
norm2()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __host__ double quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::norm2 (bool global = true) const inline
Returns the L2 norm squared of the field in a given dimension
Parameters
[in] global Whether to do a global or process local norm2 reduction
Returns
L2 norm squared
Definition at line 746 of file color_spinor_field_order.h.
Referenced by quda::calculateY().
Nparity()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Nparity () const inline
Returns the number of field parities (1 or 2)
Definition at line 730 of file color_spinor_field_order.h.
Nspin()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Nspin () const inline
Returns the number of field spins
Definition at line 723 of file color_spinor_field_order.h.
Nvec()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::Nvec () const inline
Returns the number of packed vectors (for mg prolongator)
Definition at line 726 of file color_spinor_field_order.h.
OffsetIndex()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ void quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::OffsetIndex (int & i, int y[QUDA_MAX_DIM]) const inline
Convert from n-dimensional spatial index to the 1-dimensional index. With full fields, we assume that the field is even-odd ordered. The input lattice coordinates are always full-field coordinates.
Definition at line 691 of file color_spinor_field_order.h.
operator()() [1/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ const complex<Float> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::operator() (int parity, int x_cb, int s, int c, int n = 0) const inline
Read-only complex-member accessor function. The last parameter n is only used for indexed into the packed null-space vectors.
Parameters
x 1-d checkerboard site index
s spin index
c color index
v vector number
Definition at line 572 of file color_spinor_field_order.h.
operator()() [2/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ fieldorder_wrapper<Float,storeFloat> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::operator() (int parity, int x_cb, int s, int c, int n = 0) inline
Writable complex-member accessor function. The last parameter n is only used for indexed into the packed null-space vectors.
Parameters
x 1-d checkerboard site index
s spin index
c color index
v vector number
Definition at line 603 of file color_spinor_field_order.h.
resetGhost()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> void quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::resetGhost (const ColorSpinorField & a, void *const * ghost_) const inline
Definition at line 536 of file color_spinor_field_order.h.
Referenced by quda::calculateY().
resetScale()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> void quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::resetScale (Float max) inline
Definition at line 548 of file color_spinor_field_order.h.
VolumeCB()
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::VolumeCB () const inline
Returns the field volume
Definition at line 733 of file color_spinor_field_order.h.
Referenced by quda::DslashCoarseArg< Float, yFloat, ghostFloat, coarseSpin, coarseColor, csOrder, gOrder >::DslashCoarseArg().
X() [1/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::X (int d) const inline
Return the length of dimension d
Definition at line 713 of file color_spinor_field_order.h.
X() [2/2]
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> __device__ __host__ const int* quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::X () const inline
Return the length of dimension d
Definition at line 716 of file color_spinor_field_order.h.
Member Data Documentation
@1
union { ... }
@3
union { ... }
accessor
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const AccessorCB<storeFloat,nSpin,nColor,nVec,order> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::accessor protected
Definition at line 474 of file color_spinor_field_order.h.
block_float_ghost
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> constexpr bool quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::block_float_ghost = !fixed && ghost_fixed static protected
Definition at line 500 of file color_spinor_field_order.h.
fixed
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> constexpr bool quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::fixed = fixed_point<Float,storeFloat>() static protected
Definition at line 498 of file color_spinor_field_order.h.
gammaBasis
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const QudaGammaBasis quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::gammaBasis protected
Definition at line 490 of file color_spinor_field_order.h.
ghost
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> complex<ghostFloat>* quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghost[8] mutable protected
Definition at line 485 of file color_spinor_field_order.h.
ghost_fixed
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> constexpr bool quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghost_fixed = fixed_point<Float,ghostFloat>() static protected
Definition at line 499 of file color_spinor_field_order.h.
ghost_norm
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> norm_type* quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghost_norm[8] mutable protected
Definition at line 486 of file color_spinor_field_order.h.
ghost_scale
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> Float quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghost_scale protected
Definition at line 495 of file color_spinor_field_order.h.
ghost_scale_inv
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> Float quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghost_scale_inv protected
Definition at line 496 of file color_spinor_field_order.h.
ghostAccessor
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const GhostAccessorCB<ghostFloat,nSpin,nColor,nVec,order> quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::ghostAccessor protected
Definition at line 494 of file color_spinor_field_order.h.
location
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const QudaFieldLocation quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::location protected
Definition at line 493 of file color_spinor_field_order.h.
nDim
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::nDim protected
Definition at line 489 of file color_spinor_field_order.h.
norm
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> norm_type* quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::norm
Definition at line 477 of file color_spinor_field_order.h.
norm_offset
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::norm_offset
Definition at line 482 of file color_spinor_field_order.h.
nParity
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::nParity protected
Definition at line 492 of file color_spinor_field_order.h.
scale
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> Float quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::scale
Definition at line 478 of file color_spinor_field_order.h.
scale_inv
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> Float quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::scale_inv
Definition at line 481 of file color_spinor_field_order.h.
siteSubset
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::siteSubset protected
Definition at line 491 of file color_spinor_field_order.h.
v
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> complex<storeFloat>* quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::v protected
Definition at line 473 of file color_spinor_field_order.h.
volumeCB
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> const int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::volumeCB protected
Definition at line 488 of file color_spinor_field_order.h.
x
template<typename Float, int nSpin, int nColor, int nVec, QudaFieldOrder order, typename storeFloat = Float, typename ghostFloat = storeFloat, bool disable_ghost = false, bool block_float = false, bool use_tex = false> int quda::colorspinor::FieldOrderCB< Float, nSpin, nColor, nVec, order, storeFloat, ghostFloat, disable_ghost, block_float, use_tex >::x[QUDA_MAX_DIM] mutable protected
Definition at line 487 of file color_spinor_field_order.h.
The documentation for this class was generated from the following file:
include/color_spinor_field_order.h