QUDA: quda::Dslash5< Float, nColor, Arg > Class Template Reference
quda::Dslash5< Float, nColor, Arg > Class Template Reference
Public Member Functions
Dslash5 (Arg &arg, const ColorSpinorField &meta)
virtual ~Dslash5 ()
template<typename T >
void launch (T *f, const TuneParam &tp, Arg &arg, const cudaStream_t &stream)
void apply (const cudaStream_t &stream)
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
Public Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Protected Member Functions
long long flops () const
long long bytes () const
bool tuneGridDim () const
unsigned int minThreads () const
int blockStep () const
int blockMin () const
unsigned int sharedBytesPerThread () const
unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const ColorSpinorField & meta
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Static Protected Attributes
static constexpr bool shared = true
static constexpr bool var_inverse = true
Detailed Description
template<typename Float, int nColor, typename Arg>
class quda::Dslash5< Float, nColor, Arg >
Definition at line 20 of file dslash5_domain_wall.cu.
Constructor & Destructor Documentation
Dslash5()
template<typename Float, int nColor, typename Arg> quda::Dslash5< Float, nColor, Arg >::Dslash5 (Arg & arg, const ColorSpinorField & meta) inline
Definition at line 103 of file dslash5_domain_wall.cu.
References quda::Tunable::aux, quda::LatticeField::AuxString(), quda::DSLASH5_DWF, quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, errorQuda, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, and quda::M5_INV_ZMOBIUS.
~Dslash5()
template<typename Float, int nColor, typename Arg> virtual quda::Dslash5< Float, nColor, Arg >::~Dslash5 () inline virtual
Definition at line 118 of file dslash5_domain_wall.cu.
Member Function Documentation
apply()
template<typename Float, int nColor, typename Arg> void quda::Dslash5< Float, nColor, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 130 of file dslash5_domain_wall.cu.
References quda::DSLASH5_DWF, quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, errorQuda, getTuning(), getVerbosity(), quda::Dslash5< Float, nColor, Arg >::launch(), quda::LatticeField::Location(), quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, QUDA_CPU_FIELD_LOCATION, and quda::tuneLaunch().
Referenced by quda::ApplyDslash5().
blockMin()
template<typename Float, int nColor, typename Arg> int quda::Dslash5< Float, nColor, Arg >::blockMin () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 80 of file dslash5_domain_wall.cu.
blockStep()
template<typename Float, int nColor, typename Arg> int quda::Dslash5< Float, nColor, Arg >::blockStep () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 79 of file dslash5_domain_wall.cu.
bytes()
template<typename Float, int nColor, typename Arg> long long quda::Dslash5< Float, nColor, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 62 of file dslash5_domain_wall.cu.
References quda::DSLASH5_DWF, quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, errorQuda, Ls, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, and quda::ColorSpinorField::X().
defaultTuneParam()
template<typename Float, int nColor, typename Arg> void quda::Dslash5< Float, nColor, Arg >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorYZ.
Definition at line 202 of file dslash5_domain_wall.cu.
References quda::TuneParam::block, quda::TunableVectorYZ::defaultTuneParam(), quda::TuneParam::grid, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::TuneParam::shared_bytes, and quda::Dslash5< Float, nColor, Arg >::sharedBytesPerThread().
flops()
template<typename Float, int nColor, typename Arg> long long quda::Dslash5< Float, nColor, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 31 of file dslash5_domain_wall.cu.
References quda::DSLASH5_DWF, quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, errorQuda, Ls, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::ColorSpinorField::Ncolor(), quda::ColorSpinorField::Nspin(), quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
initTuneParam()
template<typename Float, int nColor, typename Arg> void quda::Dslash5< Float, nColor, Arg >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorYZ.
Definition at line 192 of file dslash5_domain_wall.cu.
References quda::TuneParam::block, quda::TuneParam::grid, quda::TunableVectorYZ::initTuneParam(), quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::TuneParam::shared_bytes, and quda::Dslash5< Float, nColor, Arg >::sharedBytesPerThread().
launch()
template<typename Float, int nColor, typename Arg> template<typename T > void quda::Dslash5< Float, nColor, Arg >::launch (T * f, const TuneParam & tp, Arg & arg, const cudaStream_t & stream) inline
Definition at line 120 of file dslash5_domain_wall.cu.
References quda::TuneParam::block, quda::TuneParam::grid, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::qudaLaunchKernel(), quda::Tunable::setMaxDynamicSharedBytesPerBlock(), and quda::TuneParam::shared_bytes.
Referenced by quda::Dslash5< Float, nColor, Arg >::apply().
maxSharedBytesPerBlock()
template<typename Float, int nColor, typename Arg> unsigned int quda::Dslash5< Float, nColor, Arg >::maxSharedBytesPerBlock () const inline protected virtual
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
Returns
The maximum shared bytes limit per block the autotung will utilize.
Reimplemented from quda::Tunable.
Definition at line 93 of file dslash5_domain_wall.cu.
References quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::Tunable::maxDynamicSharedBytesPerBlock(), and quda::Tunable::maxSharedBytesPerBlock().
minThreads()
template<typename Float, int nColor, typename Arg> unsigned int quda::Dslash5< Float, nColor, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 78 of file dslash5_domain_wall.cu.
sharedBytesPerThread()
template<typename Float, int nColor, typename Arg> unsigned int quda::Dslash5< Float, nColor, Arg >::sharedBytesPerThread () const inline protected virtual
Reimplemented from quda::TunableVectorY.
Definition at line 81 of file dslash5_domain_wall.cu.
References quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, nColor, and quda::ColorSpinorField::Nspin().
Referenced by quda::Dslash5< Float, nColor, Arg >::defaultTuneParam(), and quda::Dslash5< Float, nColor, Arg >::initTuneParam().
tuneGridDim()
template<typename Float, int nColor, typename Arg> bool quda::Dslash5< Float, nColor, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 77 of file dslash5_domain_wall.cu.
tuneKey()
template<typename Float, int nColor, typename Arg> TuneKey quda::Dslash5< Float, nColor, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 212 of file dslash5_domain_wall.cu.
References quda::Tunable::aux, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int nColor, typename Arg> Arg& quda::Dslash5< Float, nColor, Arg >::arg protected
Definition at line 24 of file dslash5_domain_wall.cu.
Referenced by quda::ApplyDslash5().
meta
template<typename Float, int nColor, typename Arg> const ColorSpinorField& quda::Dslash5< Float, nColor, Arg >::meta protected
Definition at line 25 of file dslash5_domain_wall.cu.
shared
template<typename Float, int nColor, typename Arg> constexpr bool quda::Dslash5< Float, nColor, Arg >::shared = true static protected
Definition at line 26 of file dslash5_domain_wall.cu.
var_inverse
template<typename Float, int nColor, typename Arg> constexpr bool quda::Dslash5< Float, nColor, Arg >::var_inverse = true static protected
Whether to use variable or fixed coefficient algorithm. Must be true if using ZMOBIUS
Definition at line 29 of file dslash5_domain_wall.cu.
The documentation for this class was generated from the following file:
lib/dslash5_domain_wall.cu