QUDA: quda::Clover< Float, nSpin, nColor, Arg > Class Template Reference
quda::Clover< Float, nSpin, nColor, Arg > Class Template Reference
Public Member Functions
Clover (Arg &arg, const ColorSpinorField &meta)
virtual ~Clover ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
void preTune ()
void postTune ()
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Protected Member Functions
long long flops () const
long long bytes () const
bool tuneGridDim () const
unsigned int minThreads () const
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes
Arg & arg
const ColorSpinorField & meta
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, int nSpin, int nColor, typename Arg>
class quda::Clover< Float, nSpin, nColor, Arg >
Definition at line 568 of file dslash_quda.cu.
Constructor & Destructor Documentation
Clover()
template<typename Float, int nSpin, int nColor, typename Arg> quda::Clover< Float, nSpin, nColor, Arg >::Clover (Arg & arg, const ColorSpinorField & meta) inline
Definition at line 581 of file dslash_quda.cu.
References quda::LatticeField::AuxString().
~Clover()
template<typename Float, int nSpin, int nColor, typename Arg> virtual quda::Clover< Float, nSpin, nColor, Arg >::~Clover () inline virtual
Definition at line 585 of file dslash_quda.cu.
Member Function Documentation
apply()
template<typename Float, int nSpin, int nColor, typename Arg> void quda::Clover< Float, nSpin, nColor, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 587 of file dslash_quda.cu.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::LatticeField::Location(), QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::ApplyClover().
bytes()
template<typename Float, int nSpin, int nColor, typename Arg> long long quda::Clover< Float, nSpin, nColor, Arg >::bytes () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 576 of file dslash_quda.cu.
References quda::Arg< real, Ns, Nc, order >::nParity, and quda::Arg< real, Ns, Nc, order >::volumeCB.
flops()
template<typename Float, int nSpin, int nColor, typename Arg> long long quda::Clover< Float, nSpin, nColor, Arg >::flops () const inline protected virtual
Implements quda::Tunable.
Definition at line 575 of file dslash_quda.cu.
References quda::Arg< real, Ns, Nc, order >::nParity, and quda::Arg< real, Ns, Nc, order >::volumeCB.
minThreads()
template<typename Float, int nSpin, int nColor, typename Arg> unsigned int quda::Clover< Float, nSpin, nColor, Arg >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 578 of file dslash_quda.cu.
References quda::Arg< real, Ns, Nc, order >::volumeCB.
postTune()
template<typename Float, int nSpin, int nColor, typename Arg> void quda::Clover< Float, nSpin, nColor, Arg >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 599 of file dslash_quda.cu.
preTune()
template<typename Float, int nSpin, int nColor, typename Arg> void quda::Clover< Float, nSpin, nColor, Arg >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 598 of file dslash_quda.cu.
tuneGridDim()
template<typename Float, int nSpin, int nColor, typename Arg> bool quda::Clover< Float, nSpin, nColor, Arg >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 577 of file dslash_quda.cu.
tuneKey()
template<typename Float, int nSpin, int nColor, typename Arg> TuneKey quda::Clover< Float, nSpin, nColor, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 597 of file dslash_quda.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int nSpin, int nColor, typename Arg> Arg& quda::Clover< Float, nSpin, nColor, Arg >::arg protected
Definition at line 571 of file dslash_quda.cu.
meta
template<typename Float, int nSpin, int nColor, typename Arg> const ColorSpinorField& quda::Clover< Float, nSpin, nColor, Arg >::meta protected
Definition at line 572 of file dslash_quda.cu.
The documentation for this class was generated from the following file:
lib/dslash_quda.cu