QUDA: quda::Pack< Float, nColor, spin_project > Class Template Reference
quda::Pack< Float, nColor, spin_project > Class Template Reference
Public Member Functions
Pack (void *ghost[], const ColorSpinorField &in, MemoryLocation location, int nFace, bool dagger, int parity, double a, double b, double c)
virtual ~Pack ()
template<typename T , typename Arg >
void launch (T *f, const TuneParam &tp, Arg &arg, const cudaStream_t &stream)
void apply (const cudaStream_t &stream)
bool tuneSharedBytes () const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
int tuningIter () const
long long flops () const
long long bytes () const
Protected Member Functions
bool tuneGridDim () const
unsigned int maxGridSize () const
unsigned int minGridSize () const
int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
bool tuneAuxDim () const
unsigned int minThreads () const
void fillAux ()
Protected Attributes
void ** ghost
const ColorSpinorField & in
MemoryLocation location
const int nFace
const bool dagger
const int parity
const int nParity
int threads
const double a
const double b
const double c
int twist
Additional Inherited Members
Private Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
bool advanceBlockDim (TuneParam &param) const
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, int nColor, bool spin_project>
class quda::Pack< Float, nColor, spin_project >
Definition at line 45 of file dslash_pack2.cu.
Constructor & Destructor Documentation
Pack()
template<typename Float, int nColor, bool spin_project> quda::Pack< Float, nColor, spin_project >::Pack (void * ghost[], const ColorSpinorField & in, MemoryLocation location, int nFace, bool dagger, int parity, double a, double b, double c) inline
Definition at line 164 of file dslash_pack2.cu.
References quda::commDim, quda::Pack< Float, nColor, spin_project >::fillAux(), quda::ColorSpinorField::getDslashConstant(), quda::getKernelPackT(), and quda::DslashConstant::ghostFaceCB.
~Pack()
template<typename Float, int nColor, bool spin_project> virtual quda::Pack< Float, nColor, spin_project >::~Pack () inline virtual
Definition at line 189 of file dslash_pack2.cu.
Member Function Documentation
apply()
template<typename Float, int nColor, bool spin_project> void quda::Pack< Float, nColor, spin_project >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 202 of file dslash_pack2.cu.
References quda::arg(), quda::TuneParam::aux, errorQuda, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::Host, quda::Pack< Float, nColor, spin_project >::launch(), quda::ColorSpinorField::Nspin(), quda::ColorSpinorField::PCType(), QUDA_4D_PC, QUDA_5D_PC, and quda::tuneLaunch().
Referenced by quda::PackGhost().
bytes()
template<typename Float, int nColor, bool spin_project> long long quda::Pack< Float, nColor, spin_project >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 331 of file dslash_pack2.cu.
References quda::ColorSpinorField::getDslashConstant(), quda::DslashConstant::Ls, nColor, quda::ColorSpinorField::Nspin(), QUDA_HALF_PRECISION, QUDA_QUARTER_PRECISION, and quda::Pack< Float, nColor, spin_project >::threads.
defaultTuneParam()
template<typename Float, int nColor, bool spin_project> void quda::Pack< Float, nColor, spin_project >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorYZ.
Definition at line 309 of file dslash_pack2.cu.
References quda::TunableVectorYZ::defaultTuneParam(), quda::TuneParam::grid, quda::Host, quda::Tunable::maxDynamicSharedBytesPerBlock(), quda::Pack< Float, nColor, spin_project >::minGridSize(), and quda::TuneParam::shared_bytes.
fillAux()
template<typename Float, int nColor, bool spin_project> void quda::Pack< Float, nColor, spin_project >::fillAux () inline protected
Definition at line 125 of file dslash_pack2.cu.
References quda::Tunable::aux, quda::LatticeField::AuxString(), comm_dim_topology_string(), comm_peer2peer_enabled_global(), quda::commDim, quda::Device, errorQuda, quda::getKernelPackT(), quda::Host, quda::ColorSpinorField::Nspin(), quda::ColorSpinorField::PCType(), QUDA_5D_PC, and quda::Remote.
Referenced by quda::Pack< Float, nColor, spin_project >::Pack().
flops()
template<typename Float, int nColor, bool spin_project> long long quda::Pack< Float, nColor, spin_project >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 325 of file dslash_pack2.cu.
References quda::ColorSpinorField::getDslashConstant(), quda::DslashConstant::Ls, nColor, quda::ColorSpinorField::Nspin(), and quda::Pack< Float, nColor, spin_project >::threads.
gridStep()
template<typename Float, int nColor, bool spin_project> int quda::Pack< Float, nColor, spin_project >::gridStep () const inline protected virtual
gridStep sets the step size when iterating the grid size in advanceGridDim.
Returns
Grid step size
Reimplemented from quda::Tunable.
Definition at line 104 of file dslash_pack2.cu.
References quda::commDim, quda::Tunable::gridStep(), quda::Host, and quda::ColorSpinorField::Ndim().
initTuneParam()
template<typename Float, int nColor, bool spin_project> void quda::Pack< Float, nColor, spin_project >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorYZ.
Definition at line 297 of file dslash_pack2.cu.
References quda::TuneParam::grid, quda::Host, quda::TunableVectorYZ::initTuneParam(), quda::Tunable::maxDynamicSharedBytesPerBlock(), quda::Pack< Float, nColor, spin_project >::minGridSize(), and quda::TuneParam::shared_bytes.
launch()
template<typename Float, int nColor, bool spin_project> template<typename T , typename Arg > void quda::Pack< Float, nColor, spin_project >::launch (T * f, const TuneParam & tp, Arg & arg, const cudaStream_t & stream) inline
Definition at line 192 of file dslash_pack2.cu.
References quda::TuneParam::block, deviceProp, quda::TuneParam::grid, quda::qudaLaunchKernel(), quda::Tunable::setMaxDynamicSharedBytesPerBlock(), and quda::TuneParam::shared_bytes.
Referenced by quda::Pack< Float, nColor, spin_project >::apply().
maxGridSize()
template<typename Float, int nColor, bool spin_project> unsigned int quda::Pack< Float, nColor, spin_project >::maxGridSize () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 64 of file dslash_pack2.cu.
References quda::commDim, quda::Host, quda::Tunable::maxGridSize(), and quda::ColorSpinorField::Ndim().
minGridSize()
template<typename Float, int nColor, bool spin_project> unsigned int quda::Pack< Float, nColor, spin_project >::minGridSize () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 84 of file dslash_pack2.cu.
References quda::commDim, quda::Host, quda::Tunable::minGridSize(), and quda::ColorSpinorField::Ndim().
Referenced by quda::Pack< Float, nColor, spin_project >::defaultTuneParam(), and quda::Pack< Float, nColor, spin_project >::initTuneParam().
minThreads()
template<typename Float, int nColor, bool spin_project> unsigned int quda::Pack< Float, nColor, spin_project >::minThreads () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 123 of file dslash_pack2.cu.
References quda::Pack< Float, nColor, spin_project >::threads.
tuneAuxDim()
template<typename Float, int nColor, bool spin_project> bool quda::Pack< Float, nColor, spin_project >::tuneAuxDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 122 of file dslash_pack2.cu.
tuneGridDim()
template<typename Float, int nColor, bool spin_project> bool quda::Pack< Float, nColor, spin_project >::tuneGridDim () const inline protected virtual
Reimplemented from quda::Tunable.
Definition at line 62 of file dslash_pack2.cu.
tuneKey()
template<typename Float, int nColor, bool spin_project> TuneKey quda::Pack< Float, nColor, spin_project >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 321 of file dslash_pack2.cu.
References quda::Tunable::aux, and quda::LatticeField::VolString().
tuneSharedBytes()
template<typename Float, int nColor, bool spin_project> bool quda::Pack< Float, nColor, spin_project >::tuneSharedBytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 289 of file dslash_pack2.cu.
References quda::Tunable::maxDynamicSharedBytesPerBlock(), and quda::Tunable::maxSharedBytesPerBlock().
tuningIter()
template<typename Float, int nColor, bool spin_project> int quda::Pack< Float, nColor, spin_project >::tuningIter () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 323 of file dslash_pack2.cu.
Member Data Documentation
a
template<typename Float, int nColor, bool spin_project> const double quda::Pack< Float, nColor, spin_project >::a protected
Definition at line 57 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
b
template<typename Float, int nColor, bool spin_project> const double quda::Pack< Float, nColor, spin_project >::b protected
Definition at line 58 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
c
template<typename Float, int nColor, bool spin_project> const double quda::Pack< Float, nColor, spin_project >::c protected
Definition at line 59 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
dagger
template<typename Float, int nColor, bool spin_project> const bool quda::Pack< Float, nColor, spin_project >::dagger protected
Definition at line 53 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
ghost
template<typename Float, int nColor, bool spin_project> void** quda::Pack< Float, nColor, spin_project >::ghost protected
Definition at line 49 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
in
template<typename Float, int nColor, bool spin_project> const ColorSpinorField& quda::Pack< Float, nColor, spin_project >::in protected
Definition at line 50 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
location
template<typename Float, int nColor, bool spin_project> MemoryLocation quda::Pack< Float, nColor, spin_project >::location protected
Definition at line 51 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
nFace
template<typename Float, int nColor, bool spin_project> const int quda::Pack< Float, nColor, spin_project >::nFace protected
Definition at line 52 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
nParity
template<typename Float, int nColor, bool spin_project> const int quda::Pack< Float, nColor, spin_project >::nParity protected
Definition at line 55 of file dslash_pack2.cu.
parity
template<typename Float, int nColor, bool spin_project> const int quda::Pack< Float, nColor, spin_project >::parity protected
Definition at line 54 of file dslash_pack2.cu.
Referenced by quda::PackGhost().
threads
template<typename Float, int nColor, bool spin_project> int quda::Pack< Float, nColor, spin_project >::threads protected
Definition at line 56 of file dslash_pack2.cu.
Referenced by quda::Pack< Float, nColor, spin_project >::bytes(), quda::Pack< Float, nColor, spin_project >::flops(), and quda::Pack< Float, nColor, spin_project >::minThreads().
twist
template<typename Float, int nColor, bool spin_project> int quda::Pack< Float, nColor, spin_project >::twist protected
Definition at line 60 of file dslash_pack2.cu.
The documentation for this class was generated from the following file:
lib/dslash_pack2.cu