QUDA: quda::MPCG Class Reference
quda::MPCG Class Reference
#include <invert_quda.h>
Public Member Functions
MPCG (DiracMatrix &mat, SolverParam &param, TimeProfile &profile)
virtual ~MPCG ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Member Functions
void computeMatrixPowers (cudaColorSpinorField out[], cudaColorSpinorField &in, int nvec)
void computeMatrixPowers (std::vector< cudaColorSpinorField > &out, std::vector< cudaColorSpinorField > &in, int nsteps)
Private Attributes
const DiracMatrix & mat
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 673 of file invert_quda.h.
Constructor & Destructor Documentation
MPCG()
quda::MPCG::MPCG (DiracMatrix & mat, SolverParam & param, TimeProfile & profile)
Definition at line 93 of file inv_mpcg_quda.cpp.
~MPCG()
quda::MPCG::~MPCG () virtual
Definition at line 99 of file inv_mpcg_quda.cpp.
Member Function Documentation
computeMatrixPowers() [1/2]
void quda::MPCG::computeMatrixPowers (cudaColorSpinorField out[], cudaColorSpinorField & in, int nvec) private
Definition at line 103 of file inv_mpcg_quda.cpp.
References in, mat, and nvec.
Referenced by operator()().
computeMatrixPowers() [2/2]
void quda::MPCG::computeMatrixPowers (std::vector< cudaColorSpinorField > & out, std::vector< cudaColorSpinorField > & in, int nsteps) private
Definition at line 113 of file inv_mpcg_quda.cpp.
References mat, mu, and quda::blas::reDotProduct().
operator()()
void quda::MPCG::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 203 of file inv_mpcg_quda.cpp.
References quda::blas::ax(), quda::blas::axpy(), quda::computeCoeffs(), computeMatrixPowers(), quda::Solver::convergence(), quda::ColorSpinorParam::create, csParam, errorQuda, quda::it, mat, quda::SolverParam::maxiter, quda::blas::norm2(), quda::Solver::param, printfQuda, quda::Solver::PrintStats(), quda::Solver::PrintSummary(), quda::Solver::profile, quda::QUDA_PROFILE_INIT, QUDA_ZERO_FIELD_CREATE, R, quda::SolverParam::residual_type, quda::s, quda::sqrt(), quda::Solver::stopping(), quda::SolverParam::tol, quda::SolverParam::tol_hq, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, V, quda::blas::xmyNorm(), quda::blas::zero(), and quda::zero().
Member Data Documentation
mat
const DiracMatrix& quda::MPCG::mat private
Definition at line 675 of file invert_quda.h.
Referenced by computeMatrixPowers(), and operator()().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_mpcg_quda.cpp