QUDA: quda::linalg::Cholesky< Mat, T, N, fast > Class Template Reference
quda::linalg::Cholesky< Mat, T, N, fast > Class Template Reference
Compute Cholesky decomposition of A. By default, we use a modified Cholesky which avoids the division and sqrt, and instead only needs rsqrt. In which case we must use a modified forward and backward difference substitution.
Public Member Functions
__device__ __host__ Cholesky (const Mat< T, N > &A)
Constructor that computes the Cholesky decomposition.
__device__ __host__ const T D (int i) const
Return the diagonal element of the Cholesky decomposition L(i,i)
template<class Vector >
__device__ __host__ Vector forward (const Vector &b)
Forward substition to solve Lx = b.
template<class Vector >
__device__ __host__ Vector backward (const Vector &b)
Backward substition to solve L^dagger x = b.
__device__ __host__ Mat< T, N > invert ()
Compute the inverse of A (the matrix used to construct the Cholesky decomposition).
Private Attributes
Mat< T, N > L_
The Cholesky factorization.
Detailed Description
template<template< typename, int > class Mat, typename T, int N, bool fast = true>
class quda::linalg::Cholesky< Mat, T, N, fast >
Compute Cholesky decomposition of A. By default, we use a modified Cholesky which avoids the division and sqrt, and instead only needs rsqrt. In which case we must use a modified forward and backward difference substitution.
Template Parameters
Mat The Matrix container class type. This can either be a general Matrix (quda::Matrix) or a Hermitian matrix (quda::HMatrix).
T The underlying type. For Hermitian matrices this should be real type and for general matrices this should be the complex type.
N The size of the linear system we are solving
fast Whether to use the optimized Cholesky algorithm that stores the reciprocal sqrt on the diagonal of L, instead of the sqrt. This flag must be consistent with the equivalent flag used with the forward and backward substitutions.
Definition at line 38 of file linalg.cuh.
Constructor & Destructor Documentation
Cholesky()
template<template< typename, int > class Mat, typename T, int N, bool fast = true> __device__ __host__ quda::linalg::Cholesky< Mat, T, N, fast >::Cholesky (const Mat< T, N > & A) inline
Constructor that computes the Cholesky decomposition.
Parameters
[in] A Input matrix we are decomposing
Definition at line 48 of file linalg.cuh.
References quda::linalg::Cholesky< Mat, T, N, fast >::L_, quda::s, and quda::sqrt().
Member Function Documentation
backward()
template<template< typename, int > class Mat, typename T, int N, bool fast = true> template<class Vector > __device__ __host__ Vector quda::linalg::Cholesky< Mat, T, N, fast >::backward (const Vector & b) inline
Backward substition to solve L^dagger x = b.
Template Parameters
Vector The Vector container class, e.g., quda::colorspinor
Parameters
[in] b Source vector
Returns
solution vector
Definition at line 123 of file linalg.cuh.
References quda::linalg::Cholesky< Mat, T, N, fast >::L_.
Referenced by quda::computeAV(), and quda::computeTMCAV().
D()
template<template< typename, int > class Mat, typename T, int N, bool fast = true> __device__ __host__ const T quda::linalg::Cholesky< Mat, T, N, fast >::D (int i) const inline
Return the diagonal element of the Cholesky decomposition L(i,i)
Parameters
[in] i Index
Returns
Element at L(i,i)
Definition at line 84 of file linalg.cuh.
References quda::linalg::Cholesky< Mat, T, N, fast >::L_.
Referenced by quda::cloverInvertCompute().
forward()
template<template< typename, int > class Mat, typename T, int N, bool fast = true> template<class Vector > __device__ __host__ Vector quda::linalg::Cholesky< Mat, T, N, fast >::forward (const Vector & b) inline
Forward substition to solve Lx = b.
Template Parameters
Vector The Vector container class, e.g., quda::colorspinor
Parameters
[in] b Source vector
Returns
solution vector
Definition at line 97 of file linalg.cuh.
References quda::linalg::Cholesky< Mat, T, N, fast >::L_.
Referenced by quda::computeAV(), and quda::computeTMCAV().
invert()
template<template< typename, int > class Mat, typename T, int N, bool fast = true> __device__ __host__ Mat<T,N> quda::linalg::Cholesky< Mat, T, N, fast >::invert () inline
Compute the inverse of A (the matrix used to construct the Cholesky decomposition).
Returns
Matrix inverse
Definition at line 146 of file linalg.cuh.
References quda::linalg::Cholesky< Mat, T, N, fast >::L_.
Referenced by quda::cloverInvertCompute(), and quda::ComputeTMAVGPU().
Member Data Documentation
L_
template<template< typename, int > class Mat, typename T, int N, bool fast = true> Mat<T,N> quda::linalg::Cholesky< Mat, T, N, fast >::L_ private
The Cholesky factorization.
Definition at line 41 of file linalg.cuh.
Referenced by quda::linalg::Cholesky< Mat, T, N, fast >::backward(), quda::linalg::Cholesky< Mat, T, N, fast >::Cholesky(), quda::linalg::Cholesky< Mat, T, N, fast >::D(), quda::linalg::Cholesky< Mat, T, N, fast >::forward(), and quda::linalg::Cholesky< Mat, T, N, fast >::invert().
The documentation for this class was generated from the following file:
include/linalg.cuh