QUDA: quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder > Class Template Reference
quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder > Class Template Reference
Public Member Functions
CopySpinor (OutOrder &out, const InOrder &in, const ColorSpinorField &meta, QudaFieldLocation location)
virtual ~CopySpinor ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool advanceSharedBytes (TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
const InOrder & in
OutOrder & out
const ColorSpinorField & meta
QudaFieldLocation location
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder>
class quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >
Definition at line 46 of file copy_color_spinor_mg.cuh.
Constructor & Destructor Documentation
CopySpinor()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::CopySpinor (OutOrder & out, const InOrder & in, const ColorSpinorField & meta, QudaFieldLocation location) inline
Definition at line 61 of file copy_color_spinor_mg.cuh.
~CopySpinor()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> virtual quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::~CopySpinor () inline virtual
Definition at line 63 of file copy_color_spinor_mg.cuh.
Member Function Documentation
advanceSharedBytes()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> bool quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::advanceSharedBytes (TuneParam & param) const inline private virtual
The goal here is to throttle the number of thread blocks per SM by over-allocating shared memory (in order to improve L2 utilization, etc.). We thus request the smallest amount of dynamic shared memory that guarantees throttling to a given number of blocks, in order to allow some extra leeway.
Reimplemented from quda::Tunable.
Definition at line 56 of file copy_color_spinor_mg.cuh.
apply()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> void quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 65 of file copy_color_spinor_mg.cuh.
References quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, in, out, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, quda::tuneLaunch(), and quda::ColorSpinorField::VolumeCB().
Referenced by quda::genericCopyColorSpinor().
bytes()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> long long quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 79 of file copy_color_spinor_mg.cuh.
flops()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> long long quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 78 of file copy_color_spinor_mg.cuh.
minThreads()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> unsigned int quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 58 of file copy_color_spinor_mg.cuh.
References quda::ColorSpinorField::VolumeCB().
sharedBytesPerBlock()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> unsigned int quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 55 of file copy_color_spinor_mg.cuh.
sharedBytesPerThread()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> unsigned int quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 53 of file copy_color_spinor_mg.cuh.
tuneGridDim()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> bool quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 57 of file copy_color_spinor_mg.cuh.
tuneKey()
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> TuneKey quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 76 of file copy_color_spinor_mg.cuh.
References quda::LatticeField::AuxString(), and quda::LatticeField::VolString().
Member Data Documentation
in
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> const InOrder& quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::in private
Definition at line 47 of file copy_color_spinor_mg.cuh.
location
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> QudaFieldLocation quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::location private
Definition at line 50 of file copy_color_spinor_mg.cuh.
meta
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> const ColorSpinorField& quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::meta private
Definition at line 49 of file copy_color_spinor_mg.cuh.
out
template<typename FloatOut, typename FloatIn, int Ns, int Nc, typename OutOrder, typename InOrder> OutOrder& quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::out private
Definition at line 48 of file copy_color_spinor_mg.cuh.
The documentation for this class was generated from the following file:
lib/copy_color_spinor_mg.cuh