QUDA: quda::DiracDomainWall4D Class Reference
quda::DiracDomainWall4D Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracDomainWall4D (const DiracParam &param)
DiracDomainWall4D (const DiracDomainWall4D &dirac)
virtual ~DiracDomainWall4D ()
DiracDomainWall4D & operator= (const DiracDomainWall4D &dirac)
void Dslash4 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash4Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash5Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracDomainWall
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracDomainWall
void checkDWF (const ColorSpinorField &out, const ColorSpinorField &in) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracDomainWall
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 397 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracDomainWall4D() [1/2]
quda::DiracDomainWall4D::DiracDomainWall4D (const DiracParam & param)
Definition at line 7 of file dirac_domain_wall_4d.cpp.
DiracDomainWall4D() [2/2]
quda::DiracDomainWall4D::DiracDomainWall4D (const DiracDomainWall4D & dirac)
Definition at line 9 of file dirac_domain_wall_4d.cpp.
~DiracDomainWall4D()
quda::DiracDomainWall4D::~DiracDomainWall4D () virtual
Definition at line 11 of file dirac_domain_wall_4d.cpp.
Member Function Documentation
Dslash4()
void quda::DiracDomainWall4D::Dslash4 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 21 of file dirac_domain_wall_4d.cpp.
References quda::ApplyDomainWall4D(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by dslashCUDA(), dslashQuda_4dpc(), and quda::DiracDomainWall4DPC::M().
Dslash4Xpay()
void quda::DiracDomainWall4D::Dslash4Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 46 of file dirac_domain_wall_4d.cpp.
References quda::ApplyDomainWall4D(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::commDim, quda::Dirac::dagger, quda::Dirac::flops, quda::Dirac::gauge, quda::Dirac::profile, and quda::ColorSpinorField::Volume().
Referenced by quda::DiracDomainWall4DPC::M(), quda::DiracDomainWall4DPC::prepare(), and quda::DiracDomainWall4DPC::reconstruct().
Dslash5()
void quda::DiracDomainWall4D::Dslash5 (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 31 of file dirac_domain_wall_4d.cpp.
References quda::ApplyDslash5(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_DWF, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by dslashCUDA(), and dslashQuda_4dpc().
Dslash5Xpay()
void quda::DiracDomainWall4D::Dslash5Xpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 58 of file dirac_domain_wall_4d.cpp.
References quda::ApplyDslash5(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DSLASH5_DWF, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::Dirac::mass, quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::X().
Referenced by quda::DiracDomainWall4DPC::M().
M()
void quda::DiracDomainWall4D::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracDomainWall4DPC.
Definition at line 73 of file dirac_domain_wall_4d.cpp.
References quda::ApplyDomainWall4D(), quda::ApplyDslash5(), quda::Dirac::checkFullSpinor(), quda::Dirac::commDim, quda::Dirac::dagger, quda::DSLASH5_DWF, quda::Dirac::flops, quda::Dirac::gauge, quda::DiracDomainWall::kappa5, quda::DiracDomainWall::Ls, quda::Dirac::mass, quda::Dirac::profile, QUDA_INVALID_PARITY, quda::ColorSpinorField::Volume(), quda::ColorSpinorField::X(), and quda::blas::xpay().
Referenced by MdagM().
MdagM()
void quda::DiracDomainWall4D::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracDomainWall4DPC.
Definition at line 88 of file dirac_domain_wall_4d.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp1.
operator=()
DiracDomainWall4D & quda::DiracDomainWall4D::operator= (const DiracDomainWall4D & dirac)
Definition at line 13 of file dirac_domain_wall_4d.cpp.
References quda::DiracDomainWall::operator=().
Referenced by quda::DiracDomainWall4DPC::operator=().
prepare()
void quda::DiracDomainWall4D::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracDomainWall4DPC.
Definition at line 100 of file dirac_domain_wall_4d.cpp.
References errorQuda, QUDA_MATPC_SOLUTION, and QUDA_MATPCDAG_MATPC_SOLUTION.
reconstruct()
void quda::DiracDomainWall4D::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracDomainWall.
Reimplemented in quda::DiracDomainWall4DPC.
Definition at line 111 of file dirac_domain_wall_4d.cpp.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_domain_wall_4d.cpp