QUDA: quda::dslash::DslashPolicyTune< Dslash > Class Template Reference
quda::dslash::DslashPolicyTune< Dslash > Class Template Reference
Public Member Functions
DslashPolicyTune (Dslash &dslash, cudaColorSpinorField *in, const int volume, const int *ghostFace, TimeProfile &profile)
virtual ~DslashPolicyTune ()
void apply (const cudaStream_t &stream)
int tuningIter () const
bool advanceAux (TuneParam &param) const
bool advanceTuneParam (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
TuneKey tuneKey () const
long long flops () const
long long bytes () const
void preTune ()
void postTune ()
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
bool tuneGridDim () const
bool tuneAuxDim () const
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
Private Attributes
Dslash & dslash
decltype(dslash.dslashParam) & dslashParam
cudaColorSpinorField * in
const int volume
const int * ghostFace
TimeProfile & profile
Additional Inherited Members
Protected Member Functions inherited from quda::Tunable
virtual unsigned int minThreads () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Dslash>
class quda::dslash::DslashPolicyTune< Dslash >
Definition at line 1770 of file dslash_policy.cuh.
Constructor & Destructor Documentation
DslashPolicyTune()
template<typename Dslash > quda::dslash::DslashPolicyTune< Dslash >::DslashPolicyTune (Dslash & dslash, cudaColorSpinorField * in, const int volume, const int * ghostFace, TimeProfile & profile) inline
Definition at line 1786 of file dslash_policy.cuh.
References comm_enable_peer2peer(), comm_gdr_enabled(), comm_gpuid(), comm_peer2peer_enabled_global(), quda::dslash::DslashFactory< Dslash >::create(), device, quda::disableProfileCount(), quda::dslash::enable_policy(), quda::enableProfileCount(), quda::blas::end(), errorQuda, quda::dslash::first_active_policy, quda::getKernelPackT(), quda::getTuneCache(), getTuning(), getVerbosity(), in, quda::popKernelPackT(), quda::pushKernelPackT(), quda::dslash::QUDA_DSLASH, quda::dslash::QUDA_DSLASH_ASYNC, quda::dslash::QUDA_DSLASH_POLICY_DISABLED, quda::dslash::QUDA_FUSED_DSLASH, quda::dslash::QUDA_FUSED_DSLASH_ASYNC, quda::dslash::QUDA_FUSED_GDR_DSLASH, quda::dslash::QUDA_FUSED_GDR_RECV_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_GDR_RECV_DSLASH, quda::dslash::QUDA_GDR_DSLASH, quda::dslash::QUDA_GDR_RECV_DSLASH, quda::dslash::QUDA_P2P_COPY_ENGINE, quda::dslash::QUDA_P2P_DEFAULT, quda::dslash::QUDA_P2P_POLICY_DISABLED, quda::dslash::QUDA_P2P_REMOTE_WRITE, QUDA_SILENT, quda::dslash::QUDA_ZERO_COPY_DSLASH, quda::dslash::QUDA_ZERO_COPY_PACK_DSLASH, quda::dslash::QUDA_ZERO_COPY_PACK_GDR_RECV_DSLASH, quda::setKernelPackT(), quda::setPolicyTuning(), quda::cudaColorSpinorField::streamInit(), streams, and warningQuda.
~DslashPolicyTune()
template<typename Dslash > virtual quda::dslash::DslashPolicyTune< Dslash >::~DslashPolicyTune () inline virtual
Definition at line 2009 of file dslash_policy.cuh.
References quda::setPolicyTuning().
Member Function Documentation
advanceAux()
template<typename Dslash > bool quda::dslash::DslashPolicyTune< Dslash >::advanceAux (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 2051 of file dslash_policy.cuh.
References quda::TuneParam::aux, quda::dslash::first_active_p2p_policy, quda::dslash::first_active_policy, quda::dslash::QUDA_DSLASH_POLICY_DISABLED, and quda::dslash::QUDA_P2P_POLICY_DISABLED.
advanceTuneParam()
template<typename Dslash > bool quda::dslash::DslashPolicyTune< Dslash >::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 2068 of file dslash_policy.cuh.
apply()
template<typename Dslash > void quda::dslash::DslashPolicyTune< Dslash >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 2011 of file dslash_policy.cuh.
References quda::TuneParam::aux, comm_enable_peer2peer(), comm_peer2peer_enabled_global(), quda::dslash::DslashFactory< Dslash >::create(), errorQuda, quda::getKernelPackT(), getTuning(), getVerbosity(), in, quda::popKernelPackT(), quda::pushKernelPackT(), quda::dslash::QUDA_DSLASH_POLICY_DISABLED, quda::dslash::QUDA_FUSED_GDR_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_GDR_RECV_DSLASH, quda::dslash::QUDA_GDR_DSLASH, quda::dslash::QUDA_P2P_DEFAULT, quda::dslash::QUDA_P2P_REMOTE_WRITE, quda::dslash::QUDA_ZERO_COPY_DSLASH, quda::dslash::QUDA_ZERO_COPY_PACK_DSLASH, quda::dslash::QUDA_ZERO_COPY_PACK_GDR_RECV_DSLASH, quda::setKernelPackT(), and quda::tuneLaunch().
Referenced by quda::DomainWall4DApply< Float, nColor, recon >::DomainWall4DApply(), quda::DomainWall5DApply< Float, nColor, recon >::DomainWall5DApply(), quda::ImprovedStaggeredApply< Float, nColor, recon_l >::ImprovedStaggeredApply(), quda::LaplaceApply< Float, nColor, recon >::LaplaceApply(), quda::NdegTwistedMassApply< Float, nColor, recon >::NdegTwistedMassApply(), quda::NdegTwistedMassPreconditionedApply< Float, nColor, recon >::NdegTwistedMassPreconditionedApply(), quda::StaggeredApply< Float, nColor, recon_u >::StaggeredApply(), quda::TwistedCloverApply< Float, nColor, recon >::TwistedCloverApply(), quda::TwistedCloverPreconditionedApply< Float, nColor, recon >::TwistedCloverPreconditionedApply(), quda::TwistedMassApply< Float, nColor, recon >::TwistedMassApply(), quda::TwistedMassPreconditionedApply< Float, nColor, recon >::TwistedMassPreconditionedApply(), quda::WilsonApply< Float, nColor, recon >::WilsonApply(), quda::WilsonCloverApply< Float, nColor, recon >::WilsonCloverApply(), and quda::WilsonCloverPreconditionedApply< Float, nColor, recon >::WilsonCloverPreconditionedApply().
bytes()
template<typename Dslash > long long quda::dslash::DslashPolicyTune< Dslash >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 2103 of file dslash_policy.cuh.
References quda::Dslash< Float >::bytes(), and quda::KERNEL_POLICY.
defaultTuneParam()
template<typename Dslash > void quda::dslash::DslashPolicyTune< Dslash >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::Tunable.
Definition at line 2077 of file dslash_policy.cuh.
References quda::TuneParam::aux, quda::Tunable::defaultTuneParam(), quda::dslash::first_active_p2p_policy, and quda::dslash::first_active_policy.
flops()
template<typename Dslash > long long quda::dslash::DslashPolicyTune< Dslash >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 2095 of file dslash_policy.cuh.
References quda::Dslash< Float >::flops(), and quda::KERNEL_POLICY.
initTuneParam()
template<typename Dslash > void quda::dslash::DslashPolicyTune< Dslash >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 2070 of file dslash_policy.cuh.
References quda::TuneParam::aux, quda::dslash::first_active_p2p_policy, quda::dslash::first_active_policy, and quda::Tunable::initTuneParam().
postTune()
template<typename Dslash > void quda::dslash::DslashPolicyTune< Dslash >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 2113 of file dslash_policy.cuh.
References quda::Dslash< Float >::postTune().
preTune()
template<typename Dslash > void quda::dslash::DslashPolicyTune< Dslash >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 2111 of file dslash_policy.cuh.
References quda::Dslash< Float >::preTune().
sharedBytesPerBlock()
template<typename Dslash > unsigned int quda::dslash::DslashPolicyTune< Dslash >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 1783 of file dslash_policy.cuh.
sharedBytesPerThread()
template<typename Dslash > unsigned int quda::dslash::DslashPolicyTune< Dslash >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 1782 of file dslash_policy.cuh.
tuneAuxDim()
template<typename Dslash > bool quda::dslash::DslashPolicyTune< Dslash >::tuneAuxDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 1781 of file dslash_policy.cuh.
tuneGridDim()
template<typename Dslash > bool quda::dslash::DslashPolicyTune< Dslash >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 1780 of file dslash_policy.cuh.
tuneKey()
template<typename Dslash > TuneKey quda::dslash::DslashPolicyTune< Dslash >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 2084 of file dslash_policy.cuh.
References quda::TuneKey::aux, comm_config_string(), comm_dim_topology_string(), quda::KERNEL_POLICY, and quda::Tunable::tuneKey().
tuningIter()
template<typename Dslash > int quda::dslash::DslashPolicyTune< Dslash >::tuningIter () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 2048 of file dslash_policy.cuh.
Member Data Documentation
dslash
template<typename Dslash > Dslash& quda::dslash::DslashPolicyTune< Dslash >::dslash private
Definition at line 1773 of file dslash_policy.cuh.
dslashParam
template<typename Dslash > decltype(dslash.dslashParam) & quda::dslash::DslashPolicyTune< Dslash >::dslashParam private
Definition at line 1774 of file dslash_policy.cuh.
ghostFace
template<typename Dslash > const int* quda::dslash::DslashPolicyTune< Dslash >::ghostFace private
Definition at line 1777 of file dslash_policy.cuh.
in
template<typename Dslash > cudaColorSpinorField* quda::dslash::DslashPolicyTune< Dslash >::in private
Definition at line 1775 of file dslash_policy.cuh.
profile
template<typename Dslash > TimeProfile& quda::dslash::DslashPolicyTune< Dslash >::profile private
Definition at line 1778 of file dslash_policy.cuh.
volume
template<typename Dslash > const int quda::dslash::DslashPolicyTune< Dslash >::volume private
Definition at line 1776 of file dslash_policy.cuh.
The documentation for this class was generated from the following file:
lib/dslash_policy.cuh