QUDA: quda::SD Class Reference
quda::SD Class Reference
#include <invert_quda.h>
Public Member Functions
SD (DiracMatrix &mat, SolverParam &param, TimeProfile &profile)
virtual ~SD ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
const DiracMatrix & mat
cudaColorSpinorField * Ar
cudaColorSpinorField * r
cudaColorSpinorField * y
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 1035 of file invert_quda.h.
Constructor & Destructor Documentation
SD()
quda::SD::SD (DiracMatrix & mat, SolverParam & param, TimeProfile & profile)
Definition at line 17 of file inv_sd_quda.cpp.
~SD()
quda::SD::~SD () virtual
Definition at line 23 of file inv_sd_quda.cpp.
References Ar, init, quda::SolverParam::is_preconditioner, quda::Solver::param, quda::Solver::profile, quda::QUDA_PROFILE_FREE, r, and y.
Member Function Documentation
operator()()
void quda::SD::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 34 of file inv_sd_quda.cpp.
References Ar, quda::axpy(), quda::blas::cDotProductNormA(), commGlobalReductionSet(), getVerbosity(), quda::SolverParam::global_reduction, init, mat, quda::SolverParam::maxiter, quda::norm2(), quda::Solver::param, printfQuda, QUDA_DEBUG_VERBOSE, QUDA_VERBOSE, r, quda::sqrt(), quda::blas::xmyNorm(), y, and quda::zero().
Member Data Documentation
Ar
cudaColorSpinorField* quda::SD::Ar private
Definition at line 1038 of file invert_quda.h.
Referenced by operator()(), and ~SD().
init
bool quda::SD::init private
Definition at line 1041 of file invert_quda.h.
Referenced by operator()(), and ~SD().
mat
const DiracMatrix& quda::SD::mat private
Definition at line 1037 of file invert_quda.h.
Referenced by operator()().
r
cudaColorSpinorField* quda::SD::r private
Definition at line 1039 of file invert_quda.h.
Referenced by operator()(), and ~SD().
y
cudaColorSpinorField* quda::SD::y private
Definition at line 1040 of file invert_quda.h.
Referenced by operator()(), and ~SD().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_sd_quda.cpp