QUDA: quda::DiracMobiusPC Class Reference
quda::DiracMobiusPC Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracMobiusPC (const DiracParam &param)
DiracMobiusPC (const DiracMobiusPC &dirac)
virtual ~DiracMobiusPC ()
DiracMobiusPC & operator= (const DiracMobiusPC &dirac)
void Dslash5inv (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5invXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void M (ColorSpinorField &out, const ColorSpinorField &in) const
void MdagM (ColorSpinorField &out, const ColorSpinorField &in) const
void prepare (ColorSpinorField *&src, ColorSpinorField *&sol, ColorSpinorField &x, ColorSpinorField &b, const QudaSolutionType) const
void reconstruct (ColorSpinorField &x, const ColorSpinorField &b, const QudaSolutionType) const
Public Member Functions inherited from quda::DiracMobius
DiracMobius (const DiracParam &param)
DiracMobius (const DiracMobius &dirac)
virtual ~DiracMobius ()
DiracMobius & operator= (const DiracMobius &dirac)
void Dslash4 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash4pre (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash5 (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void Dslash4Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash4preXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
void Dslash5Xpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracDomainWall
DiracDomainWall (const DiracParam &param)
DiracDomainWall (const DiracDomainWall &dirac)
virtual ~DiracDomainWall ()
DiracDomainWall & operator= (const DiracDomainWall &dirac)
void Dslash (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity) const
void DslashXpay (ColorSpinorField &out, const ColorSpinorField &in, const QudaParity parity, const ColorSpinorField &x, const double &k) const
Public Member Functions inherited from quda::DiracWilson
DiracWilson (const DiracParam &param)
DiracWilson (const DiracWilson &dirac)
DiracWilson (const DiracParam &param, const int nDims)
virtual ~DiracWilson ()
DiracWilson & operator= (const DiracWilson &dirac)
virtual void createCoarseOp (GaugeField &Y, GaugeField &X, const Transfer &T, double kappa, double mass=0., double mu=0., double mu_factor=0.) const
Create the coarse Wilson operator.
Public Member Functions inherited from quda::Dirac
Dirac (const DiracParam &param)
Dirac (const Dirac &dirac)
virtual ~Dirac ()
Dirac & operator= (const Dirac &dirac)
void setCommDim (const int commDim_[QUDA_MAX_DIM]) const
Enable / disable communications for the Dirac operator.
virtual void checkParitySpinor (const ColorSpinorField &, const ColorSpinorField &) const
virtual void checkFullSpinor (const ColorSpinorField &, const ColorSpinorField &) const
void checkSpinorAlias (const ColorSpinorField &, const ColorSpinorField &) const
void Mdag (ColorSpinorField &out, const ColorSpinorField &in) const
void MMdag (ColorSpinorField &out, const ColorSpinorField &in) const
void setMass (double mass)
double Kappa () const
virtual double Mu () const
virtual double MuFactor () const
unsigned long long Flops () const
QudaMatPCType getMatPCType () const
int getStencilSteps () const
void Dagger (QudaDagType dag) const
void flipDagger () const
QudaPrecision HaloPrecision () const
void setHaloPrecision (QudaPrecision halo_precision_) const
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Additional Inherited Members
Static Public Member Functions inherited from quda::Dirac
static Dirac * create (const DiracParam &param)
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions inherited from quda::DiracDomainWall
void checkDWF (const ColorSpinorField &out, const ColorSpinorField &in) const
Protected Member Functions inherited from quda::DiracWilson
void initConstants ()
Protected Member Functions inherited from quda::Dirac
bool newTmp (ColorSpinorField **, const ColorSpinorField &) const
void deleteTmp (ColorSpinorField **, const bool &reset) const
Protected Attributes inherited from quda::DiracMobius
Complex b_5 [QUDA_MAX_DWF_LS]
Complex c_5 [QUDA_MAX_DWF_LS]
bool zMobius
Protected Attributes inherited from quda::DiracDomainWall
double m5
double kappa5
int Ls
Protected Attributes inherited from quda::Dirac
cudaGaugeField * gauge
double kappa
double mass
int laplace3D
QudaMatPCType matpcType
QudaDagType dagger
unsigned long long flops
ColorSpinorField * tmp1
ColorSpinorField * tmp2
QudaDiracType type
QudaPrecision halo_precision
int commDim [QUDA_MAX_DIM]
TimeProfile profile
Detailed Description
Definition at line 491 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMobiusPC() [1/2]
quda::DiracMobiusPC::DiracMobiusPC (const DiracParam & param)
Definition at line 190 of file dirac_mobius.cpp.
DiracMobiusPC() [2/2]
quda::DiracMobiusPC::DiracMobiusPC (const DiracMobiusPC & dirac)
Definition at line 192 of file dirac_mobius.cpp.
~DiracMobiusPC()
quda::DiracMobiusPC::~DiracMobiusPC () virtual
Definition at line 194 of file dirac_mobius.cpp.
Member Function Documentation
Dslash5inv()
void quda::DiracMobiusPC::Dslash5inv (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity) const
Definition at line 205 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), quda::DiracMobius::b_5, quda::DiracMobius::c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::DiracMobius::Dslash5(), quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::Dirac::mass, quda::norm2(), printfQuda, quda::ColorSpinorField::Volume(), quda::ColorSpinorField::X(), and quda::DiracMobius::zMobius.
Referenced by dslashCUDA(), dslashQuda_mdwf(), M(), prepare(), and reconstruct().
Dslash5invXpay()
void quda::DiracMobiusPC::Dslash5invXpay (ColorSpinorField & out, const ColorSpinorField & in, const QudaParity parity, const ColorSpinorField & x, const double & k) const
Definition at line 227 of file dirac_mobius.cpp.
References quda::ApplyDslash5(), quda::DiracMobius::b_5, quda::DiracMobius::c_5, quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::Dirac::checkSpinorAlias(), quda::Dirac::dagger, quda::Dirac::flops, quda::DiracDomainWall::Ls, quda::DiracDomainWall::m5, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::Dirac::mass, quda::ColorSpinorField::Volume(), quda::ColorSpinorField::X(), and quda::DiracMobius::zMobius.
Referenced by M().
M()
void quda::DiracMobiusPC::M (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracMobius.
Definition at line 242 of file dirac_mobius.cpp.
References quda::Dirac::dagger, quda::Dirac::deleteTmp(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), Dslash5inv(), Dslash5invXpay(), quda::DiracMobius::Dslash5Xpay(), quda::Dirac::matpcType, quda::Dirac::newTmp(), parity, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, and quda::Dirac::tmp1.
Referenced by dslashCUDA(), and MdagM().
MdagM()
void quda::DiracMobiusPC::MdagM (ColorSpinorField & out, const ColorSpinorField & in) const virtual
Reimplemented from quda::DiracMobius.
Definition at line 285 of file dirac_mobius.cpp.
References quda::Dirac::deleteTmp(), M(), quda::Dirac::Mdag(), quda::Dirac::newTmp(), and quda::Dirac::tmp2.
Referenced by dslashCUDA().
operator=()
DiracMobiusPC & quda::DiracMobiusPC::operator= (const DiracMobiusPC & dirac)
Definition at line 196 of file dirac_mobius.cpp.
References quda::DiracMobius::operator=().
prepare()
void quda::DiracMobiusPC::prepare (ColorSpinorField *& src, ColorSpinorField *& sol, ColorSpinorField & x, ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracMobius.
Definition at line 293 of file dirac_mobius.cpp.
References quda::Dirac::deleteTmp(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4Xpay(), Dslash5inv(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::matpcType, quda::Dirac::newTmp(), quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
reconstruct()
void quda::DiracMobiusPC::reconstruct (ColorSpinorField & x, const ColorSpinorField & b, const QudaSolutionType solType) const virtual
Reimplemented from quda::DiracMobius.
Definition at line 345 of file dirac_mobius.cpp.
References quda::Dirac::checkFullSpinor(), quda::Dirac::deleteTmp(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4Xpay(), Dslash5inv(), errorQuda, quda::ColorSpinorField::Even(), quda::Dirac::matpcType, quda::Dirac::newTmp(), quda::ColorSpinorField::Odd(), QUDA_EVEN_PARITY, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, QUDA_MATPC_SOLUTION, QUDA_MATPCDAG_MATPC_SOLUTION, QUDA_ODD_PARITY, and quda::Dirac::tmp1.
The documentation for this class was generated from the following files:
include/dirac_quda.h
lib/dirac_mobius.cpp