QUDA: quda::PreconditionedSolver Class Reference
quda::PreconditionedSolver Class Reference
#include <invert_quda.h>
Public Member Functions
PreconditionedSolver (Solver &solver, const Dirac &dirac, SolverParam &param, TimeProfile &profile, const char *prefix)
virtual ~PreconditionedSolver ()
void operator() (ColorSpinorField &x, ColorSpinorField &b)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
Solver * solver
const Dirac & dirac
const char * prefix
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 1067 of file invert_quda.h.
Constructor & Destructor Documentation
PreconditionedSolver()
quda::PreconditionedSolver::PreconditionedSolver (Solver & solver, const Dirac & dirac, SolverParam & param, TimeProfile & profile, const char * prefix) inline
Definition at line 1076 of file invert_quda.h.
~PreconditionedSolver()
virtual quda::PreconditionedSolver::~PreconditionedSolver () inline virtual
Definition at line 1085 of file invert_quda.h.
Member Function Documentation
operator()()
void quda::PreconditionedSolver::operator() (ColorSpinorField & x, ColorSpinorField & b) inline virtual
Implements quda::Solver.
Definition at line 1087 of file invert_quda.h.
References in, out, popOutputPrefix(), quda::Dirac::prepare(), pushOutputPrefix(), QUDA_FULL_SITE_SUBSET, QUDA_MAT_SOLUTION, QUDA_MATPC_SOLUTION, quda::Dirac::reconstruct(), quda::ColorSpinorField::SiteSubset(), and solution_type.
Member Data Documentation
dirac
const Dirac& quda::PreconditionedSolver::dirac private
Definition at line 1072 of file invert_quda.h.
prefix
const char* quda::PreconditionedSolver::prefix private
Definition at line 1073 of file invert_quda.h.
solver
Solver* quda::PreconditionedSolver::solver private
Definition at line 1071 of file invert_quda.h.
The documentation for this class was generated from the following file:
include/invert_quda.h