QUDA: quda::DiracMatrix Class Reference
quda::DiracMatrix Class Reference abstract
#include <dirac_quda.h>
Public Member Functions
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
DiracMatrix (const DiracMatrix &mat)
DiracMatrix (const DiracMatrix *mat)
virtual ~DiracMatrix ()
virtual void operator() (ColorSpinorField &out, const ColorSpinorField &in) const =0
virtual void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const =0
virtual void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const =0
unsigned long long flops () const
QudaMatPCType getMatPCType () const
virtual int getStencilSteps () const =0
std::string Type () const
bool isStaggered () const
const Dirac * Expose () const
Public Attributes
double shift
Shift term added onto operator (M/M^dag M/M M^dag + shift)
Protected Attributes
const Dirac * dirac
Detailed Description
Definition at line 1100 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMatrix() [1/4]
quda::DiracMatrix::DiracMatrix (const Dirac & d) inline
Definition at line 1106 of file dirac_quda.h.
DiracMatrix() [2/4]
quda::DiracMatrix::DiracMatrix (const Dirac * d) inline
Definition at line 1107 of file dirac_quda.h.
DiracMatrix() [3/4]
quda::DiracMatrix::DiracMatrix (const DiracMatrix & mat) inline
Definition at line 1108 of file dirac_quda.h.
DiracMatrix() [4/4]
quda::DiracMatrix::DiracMatrix (const DiracMatrix * mat) inline
Definition at line 1109 of file dirac_quda.h.
~DiracMatrix()
virtual quda::DiracMatrix::~DiracMatrix () inline virtual
Definition at line 1110 of file dirac_quda.h.
References in, out, and tmp.
Member Function Documentation
Expose()
const Dirac* quda::DiracMatrix::Expose () const inline
Definition at line 1135 of file dirac_quda.h.
References quda::DiracParam::dirac.
Referenced by quda::EigenSolver::computeSVD(), quda::CAGCR::create(), quda::MG::createCoarseDirac(), quda::MG::createCoarseSolver(), quda::CGNE::operator()(), quda::CGNR::operator()(), quda::GCR::operator()(), quda::CACGNE::operator()(), quda::CACGNR::operator()(), and quda::MG::reset().
flops()
unsigned long long quda::DiracMatrix::flops () const inline
Definition at line 1119 of file dirac_quda.h.
References quda::Dirac::Flops().
Referenced by quda::CG::blocksolve(), quda::IncEigCG::eigCGsolve(), quda::CG::operator()(), quda::CG3::operator()(), quda::CG3NE::operator()(), quda::PreconCG::operator()(), quda::BiCGstab::operator()(), quda::BiCGstabL::operator()(), quda::GCR::operator()(), quda::MR::operator()(), quda::CACG::operator()(), quda::CAGCR::operator()(), quda::MultiShiftCG::operator()(), and quda::GMResDR::operator()().
getMatPCType()
QudaMatPCType quda::DiracMatrix::getMatPCType () const inline
Definition at line 1122 of file dirac_quda.h.
References quda::Dirac::getMatPCType().
Referenced by quda::XSD::operator()().
getStencilSteps()
virtual int quda::DiracMatrix::getStencilSteps () const pure virtual
Implemented in quda::DiracDagger, quda::DiracMdag, quda::DiracMMdag, quda::DiracMdagM, and quda::DiracM.
Referenced by quda::DiracDagger::getStencilSteps(), and quda::BiCGstabL::operator()().
isStaggered()
bool quda::DiracMatrix::isStaggered () const inline
Definition at line 1128 of file dirac_quda.h.
Referenced by quda::CG::blocksolve(), quda::CG::operator()(), quda::CG3::operator()(), quda::MultiShiftCG::operator()(), quda::CG::~CG(), and quda::CG3::~CG3().
operator()() [1/3]
virtual void quda::DiracMatrix::operator() (ColorSpinorField & out, const ColorSpinorField & in) const pure virtual
Implemented in quda::DiracDagger, quda::DiracMdag, quda::DiracMMdag, quda::DiracMdagM, and quda::DiracM.
operator()() [2/3]
virtual void quda::DiracMatrix::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const pure virtual
Implemented in quda::DiracDagger, quda::DiracMdag, quda::DiracMMdag, quda::DiracMdagM, and quda::DiracM.
operator()() [3/3]
virtual void quda::DiracMatrix::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const pure virtual
Implemented in quda::DiracDagger, quda::DiracMdag, quda::DiracMMdag, quda::DiracMdagM, and quda::DiracM.
Type()
std::string quda::DiracMatrix::Type () const inline
Definition at line 1126 of file dirac_quda.h.
Member Data Documentation
dirac
const Dirac* quda::DiracMatrix::dirac protected
Definition at line 1103 of file dirac_quda.h.
shift
double quda::DiracMatrix::shift
Shift term added onto operator (M/M^dag M/M M^dag + shift)
Definition at line 1138 of file dirac_quda.h.
Referenced by invertMultiShiftQuda().
The documentation for this class was generated from the following file:
include/dirac_quda.h