QUDA: quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T > Class Template Reference
quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T > Class Template Reference
Public Member Functions
MultiBlas (SpinorX X[], SpinorY Y[], SpinorZ Z[], SpinorW W[], Functor &f, const coeff_array< T > &a, const coeff_array< T > &b, const coeff_array< T > &c, std::vector< ColorSpinorField *> &x, std::vector< ColorSpinorField *> &y, std::vector< ColorSpinorField *> &z, std::vector< ColorSpinorField *> &w, int NYW, int length)
virtual ~MultiBlas ()
TuneKey tuneKey () const
void apply (const cudaStream_t &stream)
void preTune ()
void postTune ()
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
long long flops () const
long long bytes () const
int tuningIter () const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
bool tuneSharedBytes () const
Private Attributes
const int NYW
const int nParity
MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor > arg
const coeff_array< T > & a
const coeff_array< T > & b
const coeff_array< T > & c
std::vector< ColorSpinorField * > & x
std::vector< ColorSpinorField * > & y
std::vector< ColorSpinorField * > & z
std::vector< ColorSpinorField * > & w
char * Y_h [MAX_MULTI_BLAS_N]
char * W_h [MAX_MULTI_BLAS_N]
char * Ynorm_h [MAX_MULTI_BLAS_N]
char * Wnorm_h [MAX_MULTI_BLAS_N]
Additional Inherited Members
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual unsigned int minThreads () const
virtual bool tuneGridDim () const
virtual bool tuneAuxDim () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T>
class quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >
Definition at line 47 of file multi_blas_quda.cu.
Constructor & Destructor Documentation
MultiBlas()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::MultiBlas (SpinorX X[], SpinorY Y[], SpinorZ Z[], SpinorW W[], Functor & f, const coeff_array< T > & a, const coeff_array< T > & b, const coeff_array< T > & c, std::vector< ColorSpinorField *> & x, std::vector< ColorSpinorField *> & y, std::vector< ColorSpinorField *> & z, std::vector< ColorSpinorField *> & w, int NYW, int length) inline
Definition at line 65 of file multi_blas_quda.cu.
References quda::blas::Amatrix_h, quda::blas::Bmatrix_h, quda::blas::Cmatrix_h, and quda::blas::coeff_array< T >::data.
~MultiBlas()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> virtual quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::~MultiBlas () inline virtual
Definition at line 100 of file multi_blas_quda.cu.
Member Function Documentation
apply()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> void quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 111 of file multi_blas_quda.cu.
References quda::blas::Amatrix_d, quda::arg(), quda::blas::arg_buffer, quda::TuneParam::block, quda::blas::Bmatrix_d, quda::blas::Cmatrix_d, quda::blas::coeff_array< T >::data, quda::blas::getStream(), getTuning(), getVerbosity(), quda::TuneParam::grid, MAX_MATRIX_SIZE, MAX_MULTI_BLAS_N, quda::TuneParam::shared_bytes, quda::tuneLaunch(), and quda::blas::coeff_array< T >::use_const.
Referenced by quda::blas::multiBlas().
bytes()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> long long quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 234 of file multi_blas_quda.cu.
References quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::f.
Referenced by quda::blas::multiBlas().
defaultTuneParam()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> void quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorY.
Definition at line 226 of file multi_blas_quda.cu.
References quda::TunableVectorY::defaultTuneParam(), and quda::TuneParam::grid.
flops()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> long long quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 232 of file multi_blas_quda.cu.
References quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::f, and quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::length.
Referenced by quda::blas::multiBlas().
initTuneParam()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> void quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorY.
Definition at line 220 of file multi_blas_quda.cu.
References quda::TuneParam::grid, and quda::TunableVectorY::initTuneParam().
postTune()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> void quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 212 of file multi_blas_quda.cu.
References quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::W, and quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::Y.
preTune()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> void quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 204 of file multi_blas_quda.cu.
References quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::W, and quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::Y.
tuneKey()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> TuneKey quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 102 of file multi_blas_quda.cu.
References quda::blas::MultiBlasArg< NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor >::f, and quda::TuneKey::name_n.
tuneSharedBytes()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> bool quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::tuneSharedBytes () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 62 of file multi_blas_quda.cu.
tuningIter()
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> int quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::tuningIter () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 240 of file multi_blas_quda.cu.
Member Data Documentation
a
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> const coeff_array<T>& quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::a private
Definition at line 54 of file multi_blas_quda.cu.
arg
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> MultiBlasArg<NXZ, SpinorX, SpinorY, SpinorZ, SpinorW, Functor> quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::arg mutable private
Definition at line 53 of file multi_blas_quda.cu.
b
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> const coeff_array<T> & quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::b private
Definition at line 54 of file multi_blas_quda.cu.
c
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> const coeff_array<T> & quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::c private
Definition at line 54 of file multi_blas_quda.cu.
nParity
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> const int quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::nParity private
Definition at line 52 of file multi_blas_quda.cu.
NYW
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> const int quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::NYW private
Definition at line 51 of file multi_blas_quda.cu.
w
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> std::vector<ColorSpinorField *> & quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::w private
Definition at line 56 of file multi_blas_quda.cu.
W_h
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> char * quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::W_h[MAX_MULTI_BLAS_N] private
Definition at line 60 of file multi_blas_quda.cu.
Wnorm_h
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> char * quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::Wnorm_h[MAX_MULTI_BLAS_N] private
Definition at line 60 of file multi_blas_quda.cu.
x
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> std::vector<ColorSpinorField *>& quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::x private
Definition at line 56 of file multi_blas_quda.cu.
y
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> std::vector<ColorSpinorField *> & quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::y private
Definition at line 56 of file multi_blas_quda.cu.
Y_h
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> char* quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::Y_h[MAX_MULTI_BLAS_N] private
Definition at line 60 of file multi_blas_quda.cu.
Ynorm_h
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> char * quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::Ynorm_h[MAX_MULTI_BLAS_N] private
Definition at line 60 of file multi_blas_quda.cu.
z
template<int NXZ, typename FloatN, int M, typename SpinorX, typename SpinorY, typename SpinorZ, typename SpinorW, typename Functor, typename T> std::vector<ColorSpinorField *> & quda::blas::MultiBlas< NXZ, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, Functor, T >::z private
Definition at line 56 of file multi_blas_quda.cu.
The documentation for this class was generated from the following file:
lib/multi_blas_quda.cu