QUDA: quda::Worker Class Reference
quda::Worker Class Reference abstract
#include <worker.h>
Public Member Functions
Worker ()
virtual ~Worker ()
virtual void apply (const cudaStream_t &stream)=0
Detailed Description
Definition at line 5 of file worker.h.
Constructor & Destructor Documentation
Worker()
quda::Worker::Worker () inline
Definition at line 8 of file worker.h.
~Worker()
virtual quda::Worker::~Worker () inline virtual
Definition at line 9 of file worker.h.
References apply(), and quda::stream.
Member Function Documentation
apply()
virtual void quda::Worker::apply (const cudaStream_t & stream) pure virtual
Implemented in quda::BiCGstabLUpdate, and quda::ShiftUpdate.
Referenced by quda::dslash::DslashBasic< Dslash >::operator()(), quda::dslash::DslashFusedExterior< Dslash >::operator()(), quda::DslashCoarseLaunch::operator()(), quda::dslash::DslashGDR< Dslash >::operator()(), quda::dslash::DslashFusedGDR< Dslash >::operator()(), quda::dslash::DslashGDRRecv< Dslash >::operator()(), quda::dslash::DslashFusedGDRRecv< Dslash >::operator()(), quda::dslash::DslashZeroCopyPack< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopyPack< Dslash >::operator()(), quda::dslash::DslashZeroCopyPackGDRRecv< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopyPackGDRRecv< Dslash >::operator()(), quda::dslash::DslashZeroCopy< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopy< Dslash >::operator()(), and ~Worker().
The documentation for this class was generated from the following file:
include/worker.h