QUDA: quda::SpinorNoise< real, Ns, Nc, type, Arg > Class Template Reference
quda::SpinorNoise< real, Ns, Nc, type, Arg > Class Template Reference
Public Member Functions
SpinorNoise (Arg &arg, const ColorSpinorField &meta)
void apply (const cudaStream_t &stream)
bool advanceTuneParam (TuneParam &param) const
TuneKey tuneKey () const
long long flops () const
long long bytes () const
void preTune ()
void postTune ()
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
bool advanceBlockDim (TuneParam &param) const
void initTuneParam (TuneParam &param) const
void defaultTuneParam (TuneParam &param) const
void resizeVector (int y) const
void resizeStep (int y) const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
Arg & arg
const ColorSpinorField & meta
Private Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg>
class quda::SpinorNoise< real, Ns, Nc, type, Arg >
Definition at line 87 of file spinor_noise.cu.
Constructor & Destructor Documentation
SpinorNoise()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> quda::SpinorNoise< real, Ns, Nc, type, Arg >::SpinorNoise (Arg & arg, const ColorSpinorField & meta) inline
Definition at line 98 of file spinor_noise.cu.
References quda::LatticeField::AuxString(), quda::LatticeField::Location(), and QUDA_CUDA_FIELD_LOCATION.
Member Function Documentation
advanceTuneParam()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> bool quda::SpinorNoise< real, Ns, Nc, type, Arg >::advanceTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 109 of file spinor_noise.cu.
References quda::Tunable::advanceTuneParam(), quda::LatticeField::Location(), and QUDA_CUDA_FIELD_LOCATION.
apply()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> void quda::SpinorNoise< real, Ns, Nc, type, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 104 of file spinor_noise.cu.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::spinorNoise().
bytes()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> long long quda::SpinorNoise< real, Ns, Nc, type, Arg >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 116 of file spinor_noise.cu.
References quda::ColorSpinorField::Bytes().
flops()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> long long quda::SpinorNoise< real, Ns, Nc, type, Arg >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 115 of file spinor_noise.cu.
minThreads()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> unsigned int quda::SpinorNoise< real, Ns, Nc, type, Arg >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 95 of file spinor_noise.cu.
References quda::ColorSpinorField::VolumeCB().
postTune()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> void quda::SpinorNoise< real, Ns, Nc, type, Arg >::postTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 118 of file spinor_noise.cu.
References quda::RNG::restore(), and quda::Arg< real, Ns, Nc, order >::rng.
preTune()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> void quda::SpinorNoise< real, Ns, Nc, type, Arg >::preTune () inline virtual
Reimplemented from quda::Tunable.
Definition at line 117 of file spinor_noise.cu.
References quda::RNG::backup(), and quda::Arg< real, Ns, Nc, order >::rng.
sharedBytesPerBlock()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> unsigned int quda::SpinorNoise< real, Ns, Nc, type, Arg >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 93 of file spinor_noise.cu.
sharedBytesPerThread()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> unsigned int quda::SpinorNoise< real, Ns, Nc, type, Arg >::sharedBytesPerThread () const inline private virtual
Reimplemented from quda::TunableVectorY.
Definition at line 92 of file spinor_noise.cu.
tuneGridDim()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> bool quda::SpinorNoise< real, Ns, Nc, type, Arg >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 94 of file spinor_noise.cu.
tuneKey()
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> TuneKey quda::SpinorNoise< real, Ns, Nc, type, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 114 of file spinor_noise.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> Arg& quda::SpinorNoise< real, Ns, Nc, type, Arg >::arg private
Definition at line 88 of file spinor_noise.cu.
meta
template<typename real, int Ns, int Nc, QudaNoiseType type, typename Arg> const ColorSpinorField& quda::SpinorNoise< real, Ns, Nc, type, Arg >::meta private
Definition at line 89 of file spinor_noise.cu.
The documentation for this class was generated from the following file:
lib/spinor_noise.cu