QUDA: quda::DiracMdag Class Reference
quda::DiracMdag Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracMdag (const Dirac &d)
DiracMdag (const Dirac *d)
void operator() (ColorSpinorField &out, const ColorSpinorField &in) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const
int getStencilSteps () const
Public Member Functions inherited from quda::DiracMatrix
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
DiracMatrix (const DiracMatrix &mat)
DiracMatrix (const DiracMatrix *mat)
virtual ~DiracMatrix ()
unsigned long long flops () const
QudaMatPCType getMatPCType () const
std::string Type () const
bool isStaggered () const
const Dirac * Expose () const
Additional Inherited Members
Public Attributes inherited from quda::DiracMatrix
double shift
Shift term added onto operator (M/M^dag M/M M^dag + shift)
Protected Attributes inherited from quda::DiracMatrix
const Dirac * dirac
Detailed Description
Definition at line 1258 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMdag() [1/2]
quda::DiracMdag::DiracMdag (const Dirac & d) inline
Definition at line 1261 of file dirac_quda.h.
DiracMdag() [2/2]
quda::DiracMdag::DiracMdag (const Dirac * d) inline
Definition at line 1262 of file dirac_quda.h.
Member Function Documentation
getStencilSteps()
int quda::DiracMdag::getStencilSteps () const inline virtual
Implements quda::DiracMatrix.
Definition at line 1289 of file dirac_quda.h.
References quda::DiracParam::dirac, and quda::Dirac::getStencilSteps().
operator()() [1/3]
void quda::DiracMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1264 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, and quda::Dirac::Mdag().
operator()() [2/3]
void quda::DiracMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1270 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, quda::Dirac::Mdag(), tmp, and quda::Dirac::tmp1.
operator()() [3/3]
void quda::DiracMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1278 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, quda::Dirac::Mdag(), quda::Dirac::tmp1, and quda::Dirac::tmp2.
The documentation for this class was generated from the following file:
include/dirac_quda.h