QUDA: StaggeredDslashTest Class Reference
StaggeredDslashTest Class Reference
Public Member Functions
virtual ~StaggeredDslashTest ()
virtual void SetUp ()
virtual void TearDown ()
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
Protected Member Functions
bool skip ()
Protected Attributes
::testing::tuple< int, int, int > param
Detailed Description
Definition at line 566 of file staggered_dslash_ctest.cpp.
Constructor & Destructor Documentation
~StaggeredDslashTest()
virtual StaggeredDslashTest::~StaggeredDslashTest () inline virtual
Definition at line 598 of file staggered_dslash_ctest.cpp.
Member Function Documentation
SetUp()
virtual void StaggeredDslashTest::SetUp () inline virtual
Definition at line 599 of file staggered_dslash_ctest.cpp.
References commDimPartitionedSet(), display_test_info(), init(), prec, qdp_fatlink_cpu, qdp_longlink_cpu, and updateR().
SetUpTestCase()
static void StaggeredDslashTest::SetUpTestCase () inline static
Definition at line 639 of file staggered_dslash_ctest.cpp.
References device, and initQuda().
skip()
bool StaggeredDslashTest::skip () inline protected
Definition at line 570 of file staggered_dslash_ctest.cpp.
References compute_fatlong, dslash_type, getPrecision(), getReconstructNibble(), QUDA_ASQTAD_DSLASH, QUDA_LAPLACE_DSLASH, and warningQuda.
TearDown()
virtual void StaggeredDslashTest::TearDown () inline virtual
Definition at line 633 of file staggered_dslash_ctest.cpp.
References end().
TearDownTestCase()
static void StaggeredDslashTest::TearDownTestCase () inline static
Definition at line 644 of file staggered_dslash_ctest.cpp.
References endQuda().
Member Data Documentation
param
::testing::tuple<int, int, int> StaggeredDslashTest::param protected
Definition at line 568 of file staggered_dslash_ctest.cpp.
The documentation for this class was generated from the following file:
tests/staggered_dslash_ctest.cpp