QUDA: quda::DiracMMdag Class Reference
quda::DiracMMdag Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracMMdag (const Dirac &d)
DiracMMdag (const Dirac *d)
void operator() (ColorSpinorField &out, const ColorSpinorField &in) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const
int getStencilSteps () const
Public Member Functions inherited from quda::DiracMatrix
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
DiracMatrix (const DiracMatrix &mat)
DiracMatrix (const DiracMatrix *mat)
virtual ~DiracMatrix ()
unsigned long long flops () const
QudaMatPCType getMatPCType () const
std::string Type () const
bool isStaggered () const
const Dirac * Expose () const
Additional Inherited Members
Public Attributes inherited from quda::DiracMatrix
double shift
Shift term added onto operator (M/M^dag M/M M^dag + shift)
Protected Attributes inherited from quda::DiracMatrix
const Dirac * dirac
Detailed Description
Definition at line 1221 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracMMdag() [1/2]
quda::DiracMMdag::DiracMMdag (const Dirac & d) inline
Definition at line 1224 of file dirac_quda.h.
DiracMMdag() [2/2]
quda::DiracMMdag::DiracMMdag (const Dirac * d) inline
Definition at line 1225 of file dirac_quda.h.
Member Function Documentation
getStencilSteps()
int quda::DiracMMdag::getStencilSteps () const inline virtual
Implements quda::DiracMatrix.
Definition at line 1252 of file dirac_quda.h.
References quda::DiracParam::dirac, and quda::Dirac::getStencilSteps().
operator()() [1/3]
void quda::DiracMMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1227 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, and quda::Dirac::MMdag().
operator()() [2/3]
void quda::DiracMMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1233 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, quda::Dirac::MMdag(), tmp, and quda::Dirac::tmp1.
operator()() [3/3]
void quda::DiracMMdag::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1241 of file dirac_quda.h.
References quda::blas::axpy(), quda::DiracParam::dirac, quda::Dirac::MMdag(), quda::Dirac::tmp1, and quda::Dirac::tmp2.
The documentation for this class was generated from the following file:
include/dirac_quda.h