QUDA: quda::ExtractGhostEx< Float, length, nDim, dim, Order > Class Template Reference
quda::ExtractGhostEx< Float, length, nDim, dim, Order > Class Template Reference
Public Member Functions
ExtractGhostEx (ExtractGhostExArg< Order, nDim, dim > &arg, bool extract, const GaugeField &meta, QudaFieldLocation location)
virtual ~ExtractGhostEx ()
void apply (const cudaStream_t &stream)
TuneKey tuneKey () const
long long flops () const
long long bytes () const
Private Member Functions
unsigned int sharedBytesPerThread () const
unsigned int sharedBytesPerBlock (const TuneParam &param) const
bool tuneGridDim () const
unsigned int minThreads () const
Private Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
virtual bool tuneAuxDim () const
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual int blockStep () const
virtual int blockMin () const
virtual void resetBlockDim (TuneParam &param) const
virtual bool advanceBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
virtual bool advanceAux (TuneParam &param) const
int writeAuxString (const char *format,...)
Private Attributes
ExtractGhostExArg< Order, nDim, dim > arg
int size
bool extract
const GaugeField & meta
QudaFieldLocation location
Private Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, int length, int nDim, int dim, typename Order>
class quda::ExtractGhostEx< Float, length, nDim, dim, Order >
Definition at line 192 of file extract_gauge_ghost_extended.cu.
Constructor & Destructor Documentation
ExtractGhostEx()
template<typename Float, int length, int nDim, int dim, typename Order> quda::ExtractGhostEx< Float, length, nDim, dim, Order >::ExtractGhostEx (ExtractGhostExArg< Order, nDim, dim > & arg, bool extract, const GaugeField & meta, QudaFieldLocation location) inline
Definition at line 207 of file extract_gauge_ghost_extended.cu.
References quda::ExtractGhostExArg< Order, nDim, dim >::A0, quda::ExtractGhostExArg< Order, nDim, dim >::A1, quda::ExtractGhostExArg< Order, nDim, dim >::B0, quda::ExtractGhostExArg< Order, nDim, dim >::B1, quda::ExtractGhostExArg< Order, nDim, dim >::C0, quda::ExtractGhostExArg< Order, nDim, dim >::C1, quda::ExtractGhostExArg< Order, nDim, dim >::order, and quda::ExtractGhostExArg< Order, nDim, dim >::R.
~ExtractGhostEx()
template<typename Float, int length, int nDim, int dim, typename Order> virtual quda::ExtractGhostEx< Float, length, nDim, dim, Order >::~ExtractGhostEx () inline virtual
Definition at line 217 of file extract_gauge_ghost_extended.cu.
Member Function Documentation
apply()
template<typename Float, int length, int nDim, int dim, typename Order> void quda::ExtractGhostEx< Float, length, nDim, dim, Order >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 219 of file extract_gauge_ghost_extended.cu.
References quda::arg(), quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::extractGhostEx().
bytes()
template<typename Float, int length, int nDim, int dim, typename Order> long long quda::ExtractGhostEx< Float, length, nDim, dim, Order >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 246 of file extract_gauge_ghost_extended.cu.
References quda::ExtractGhostExArg< Order, nDim, dim >::order.
flops()
template<typename Float, int length, int nDim, int dim, typename Order> long long quda::ExtractGhostEx< Float, length, nDim, dim, Order >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 245 of file extract_gauge_ghost_extended.cu.
minThreads()
template<typename Float, int length, int nDim, int dim, typename Order> unsigned int quda::ExtractGhostEx< Float, length, nDim, dim, Order >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 204 of file extract_gauge_ghost_extended.cu.
References quda::size.
sharedBytesPerBlock()
template<typename Float, int length, int nDim, int dim, typename Order> unsigned int quda::ExtractGhostEx< Float, length, nDim, dim, Order >::sharedBytesPerBlock (const TuneParam & param) const inline private virtual
Implements quda::Tunable.
Definition at line 201 of file extract_gauge_ghost_extended.cu.
sharedBytesPerThread()
template<typename Float, int length, int nDim, int dim, typename Order> unsigned int quda::ExtractGhostEx< Float, length, nDim, dim, Order >::sharedBytesPerThread () const inline private virtual
Implements quda::Tunable.
Definition at line 200 of file extract_gauge_ghost_extended.cu.
tuneGridDim()
template<typename Float, int length, int nDim, int dim, typename Order> bool quda::ExtractGhostEx< Float, length, nDim, dim, Order >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 203 of file extract_gauge_ghost_extended.cu.
tuneKey()
template<typename Float, int length, int nDim, int dim, typename Order> TuneKey quda::ExtractGhostEx< Float, length, nDim, dim, Order >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 243 of file extract_gauge_ghost_extended.cu.
References quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, int length, int nDim, int dim, typename Order> ExtractGhostExArg<Order,nDim,dim> quda::ExtractGhostEx< Float, length, nDim, dim, Order >::arg private
Definition at line 193 of file extract_gauge_ghost_extended.cu.
extract
template<typename Float, int length, int nDim, int dim, typename Order> bool quda::ExtractGhostEx< Float, length, nDim, dim, Order >::extract private
Definition at line 195 of file extract_gauge_ghost_extended.cu.
location
template<typename Float, int length, int nDim, int dim, typename Order> QudaFieldLocation quda::ExtractGhostEx< Float, length, nDim, dim, Order >::location private
Definition at line 197 of file extract_gauge_ghost_extended.cu.
meta
template<typename Float, int length, int nDim, int dim, typename Order> const GaugeField& quda::ExtractGhostEx< Float, length, nDim, dim, Order >::meta private
Definition at line 196 of file extract_gauge_ghost_extended.cu.
size
template<typename Float, int length, int nDim, int dim, typename Order> int quda::ExtractGhostEx< Float, length, nDim, dim, Order >::size private
Definition at line 194 of file extract_gauge_ghost_extended.cu.
The documentation for this class was generated from the following file:
lib/extract_gauge_ghost_extended.cu