QUDA: quda::CGNE Class Reference
quda::CGNE Class Reference
#include <invert_quda.h>
Public Member Functions
CGNE (DiracMatrix &mat, DiracMatrix &matSloppy, SolverParam &param, TimeProfile &profile)
virtual ~CGNE ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Run CG.
Public Member Functions inherited from quda::CG
CG (DiracMatrix &mat, DiracMatrix &matSloppy, SolverParam &param, TimeProfile &profile)
virtual ~CG ()
void operator() (ColorSpinorField &out, ColorSpinorField &in, ColorSpinorField *p_init, double r2_old_init)
Solve re-using an initial Krylov space defined by an initial r2_old_init and search direction p_init.
void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
DiracMMdag mmdag
DiracMMdag mmdagSloppy
ColorSpinorField * xp
ColorSpinorField * yp
bool init
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 642 of file invert_quda.h.
Constructor & Destructor Documentation
CGNE()
quda::CGNE::CGNE (DiracMatrix & mat, DiracMatrix & matSloppy, SolverParam & param, TimeProfile & profile)
Definition at line 60 of file inv_cg_quda.cpp.
~CGNE()
quda::CGNE::~CGNE () virtual
Definition at line 65 of file inv_cg_quda.cpp.
References init, xp, and yp.
Member Function Documentation
operator()()
void quda::CGNE::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Run CG.
Parameters
out Solution vector.
in Right-hand side.
Reimplemented from quda::CG.
Definition at line 74 of file inv_cg_quda.cpp.
References quda::blas::axpby(), quda::SolverParam::compute_true_res, quda::ColorSpinorParam::create, quda::ColorSpinorField::Create(), csParam, quda::DiracMatrix::Expose(), quda::blas::HeavyQuarkResidualNorm(), init, quda::SolverParam::iter, quda::Dirac::M(), quda::SolverParam::maxiter, quda::Dirac::Mdag(), mmdag, quda::blas::norm2(), quda::SolverParam::Nsteps, quda::CG::operator()(), quda::Solver::param, quda::SolverParam::preserve_source, quda::Solver::PrintSummary(), QUDA_HEAVY_QUARK_RESIDUAL, QUDA_NULL_FIELD_CREATE, QUDA_PRESERVE_SOURCE_NO, QUDA_PRESERVE_SOURCE_YES, QUDA_USE_INIT_GUESS_NO, QUDA_USE_INIT_GUESS_YES, QUDA_ZERO_FIELD_CREATE, quda::SolverParam::residual_type, quda::sqrt(), quda::Solver::stopping(), quda::SolverParam::tol, quda::SolverParam::tol_hq, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, quda::SolverParam::use_init_guess, quda::blas::xmyNorm(), xp, quda::blas::xpy(), yp, and quda::blas::zero().
Member Data Documentation
init
bool quda::CGNE::init private
Definition at line 649 of file invert_quda.h.
Referenced by operator()(), and ~CGNE().
mmdag
DiracMMdag quda::CGNE::mmdag private
Definition at line 645 of file invert_quda.h.
Referenced by operator()().
mmdagSloppy
DiracMMdag quda::CGNE::mmdagSloppy private
Definition at line 646 of file invert_quda.h.
xp
ColorSpinorField* quda::CGNE::xp private
Definition at line 647 of file invert_quda.h.
Referenced by operator()(), and ~CGNE().
yp
ColorSpinorField* quda::CGNE::yp private
Definition at line 648 of file invert_quda.h.
Referenced by operator()(), and ~CGNE().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_cg_quda.cpp