QUDA: quda::ColorSpinorField Class Reference
quda::ColorSpinorField Class Reference abstract
#include <color_spinor_field.h>
Public Member Functions
ColorSpinorField (const ColorSpinorField &)
ColorSpinorField (const ColorSpinorParam &)
virtual ~ColorSpinorField ()
virtual ColorSpinorField & operator= (const ColorSpinorField &)
int Ncolor () const
int Nspin () const
int Nvec () const
QudaTwistFlavorType TwistFlavor () const
int Ndim () const
const int * X () const
int X (int d) const
size_t RealLength () const
size_t Length () const
int Stride () const
int Volume () const
int VolumeCB () const
int Pad () const
size_t Bytes () const
size_t NormBytes () const
size_t GhostBytes () const
size_t GhostNormBytes () const
void PrintDims () const
void * V ()
const void * V () const
void * Norm ()
const void * Norm () const
virtual const void * Ghost2 () const
void exchange (void **ghost, void **sendbuf, int nFace=1) const
virtual void exchangeGhost (QudaParity parity, int nFace, int dagger, const MemoryLocation *pack_destination=nullptr, const MemoryLocation *halo_location=nullptr, bool gdr_send=false, bool gdr_recv=false, QudaPrecision ghost_precision=QUDA_INVALID_PRECISION) const =0
bool isNative () const
bool IsComposite () const
bool IsComponent () const
int CompositeDim () const
int ComponentId () const
int ComponentVolume () const
int ComponentVolumeCB () const
int ComponentStride () const
size_t ComponentLength () const
size_t ComponentRealLength () const
size_t ComponentBytes () const
size_t ComponentNormBytes () const
QudaPCType PCType () const
QudaSiteSubset SiteSubset () const
QudaSiteOrder SiteOrder () const
QudaFieldOrder FieldOrder () const
QudaGammaBasis GammaBasis () const
const int * GhostFace () const
const int * GhostFaceCB () const
int GhostOffset (const int i) const
int GhostOffset (const int i, const int j) const
int GhostNormOffset (const int i) const
int GhostNormOffset (const int i, const int j) const
void * Ghost (const int i)
const void * Ghost (const int i) const
void * GhostNorm (const int i)
const void * GhostNorm (const int i) const
void *const * Ghost () const
const DslashConstant & getDslashConstant () const
Get the dslash_constant structure from this field.
const ColorSpinorField & Even () const
const ColorSpinorField & Odd () const
ColorSpinorField & Even ()
ColorSpinorField & Odd ()
ColorSpinorField & Component (const int idx) const
ColorSpinorField & Component (const int idx)
CompositeColorSpinorField & Components ()
virtual void Source (const QudaSourceType sourceType, const int st=0, const int s=0, const int c=0)=0
virtual void PrintVector (unsigned int x) const =0
void LatticeIndex (int *y, int i) const
void OffsetIndex (int &i, int *y) const
ColorSpinorField * CreateCoarse (const int *geoBlockSize, int spinBlockSize, int Nvec, QudaPrecision precision=QUDA_INVALID_PRECISION, QudaFieldLocation location=QUDA_INVALID_FIELD_LOCATION, QudaMemoryType mem_Type=QUDA_MEMORY_INVALID)
Create a coarse color-spinor field, using this field to set the meta data.
ColorSpinorField * CreateFine (const int *geoblockSize, int spinBlockSize, int Nvec, QudaPrecision precision=QUDA_INVALID_PRECISION, QudaFieldLocation location=QUDA_INVALID_FIELD_LOCATION, QudaMemoryType mem_type=QUDA_MEMORY_INVALID)
Create a fine color-spinor field, using this field to set the meta data.
Public Member Functions inherited from quda::LatticeField
LatticeField (const LatticeFieldParam &param)
LatticeField (const LatticeField &field)
virtual ~LatticeField ()
void allocateGhostBuffer (size_t ghost_bytes) const
Allocate the static ghost buffers.
void createComms (bool no_comms_fill=false, bool bidir=true)
void destroyComms ()
void createIPCComms ()
bool ipcCopyComplete (int dir, int dim)
bool ipcRemoteCopyComplete (int dir, int dim)
const cudaEvent_t & getIPCCopyEvent (int dir, int dim) const
const cudaEvent_t & getIPCRemoteCopyEvent (int dir, int dim) const
int Ndim () const
const int * X () const
int Volume () const
int VolumeCB () const
const int * SurfaceCB () const
int SurfaceCB (const int i) const
int Stride () const
int Pad () const
const int * R () const
QudaGhostExchange GhostExchange () const
QudaPrecision Precision () const
QudaPrecision GhostPrecision () const
double Scale () const
void Scale (double scale_)
Set the scale factor for a fixed-point field.
virtual QudaMemoryType MemType () const
int Nvec () const
QudaFieldLocation Location () const
size_t GBytes () const
void checkField (const LatticeField &a) const
virtual void read (char *filename)
virtual void write (char *filename)
virtual void gather (int nFace, int dagger, int dir, cudaStream_t *stream_p=NULL)
virtual void commsStart (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual int commsQuery (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual void commsWait (int nFace, int dir, int dagger=0, cudaStream_t *stream_p=NULL, bool gdr_send=false, bool gdr_recv=true)
virtual void scatter (int nFace, int dagger, int dir)
const char * VolString () const
const char * AuxString () const
virtual void backup () const
Backs up the LatticeField.
virtual void restore () const
Restores the LatticeField.
Public Member Functions inherited from quda::Object
Object ()
virtual ~Object ()
Static Public Member Functions
static ColorSpinorField * Create (const ColorSpinorParam &param)
static ColorSpinorField * Create (const ColorSpinorField &src, const ColorSpinorParam &param)
Static Public Member Functions inherited from quda::LatticeField
static void freeGhostBuffer (void)
Free statically allocated ghost buffers.
static void destroyIPCComms ()
Static Public Member Functions inherited from quda::Object
static void * operator new (std::size_t size)
static void operator delete (void *p)
static void * operator new[] (std::size_t size)
static void operator delete[] (void *p)
Protected Member Functions
void createGhostZone (int nFace, bool spin_project=true) const
void reset (const ColorSpinorParam &)
void fill (ColorSpinorParam &) const
void setTuningString ()
Set the vol_string and aux_string for use in tuning.
Protected Member Functions inherited from quda::LatticeField
void precisionCheck ()
Static Protected Member Functions
static void checkField (const ColorSpinorField &, const ColorSpinorField &)
Protected Attributes
bool init
QudaPrecision ghost_precision_allocated
int nColor
int nSpin
int nVec
int nDim
int x [QUDA_MAX_DIM]
int volume
int volumeCB
int pad
int stride
QudaTwistFlavorType twistFlavor
QudaPCType pc_type
size_t real_length
size_t length
void * v
void * norm
void * v_h
void * norm_h
void * ghost [2][QUDA_MAX_DIM]
void * ghostNorm [2][QUDA_MAX_DIM]
int ghostFace [QUDA_MAX_DIM]
int ghostFaceCB [QUDA_MAX_DIM]
void * ghost_buf [2 *QUDA_MAX_DIM]
DslashConstant dslash_constant
size_t bytes
size_t norm_bytes
QudaSiteSubset siteSubset
QudaSiteOrder siteOrder
QudaFieldOrder fieldOrder
QudaGammaBasis gammaBasis
ColorSpinorField * even
ColorSpinorField * odd
CompositeColorSpinorFieldDescriptor composite_descr
used for deflation eigenvector sets etc.:
CompositeColorSpinorField components
Protected Attributes inherited from quda::LatticeField
int volume
int volumeCB
int stride
int pad
size_t total_bytes
int nDim
int x [QUDA_MAX_DIM]
int surface [QUDA_MAX_DIM]
int surfaceCB [QUDA_MAX_DIM]
int r [QUDA_MAX_DIM]
QudaPrecision precision
QudaPrecision ghost_precision
bool ghost_precision_reset
double scale
QudaSiteSubset siteSubset
QudaGhostExchange ghostExchange
int nDimComms
size_t ghost_bytes
size_t ghost_bytes_old
size_t ghost_face_bytes [QUDA_MAX_DIM]
int ghostOffset [QUDA_MAX_DIM][2]
int ghostNormOffset [QUDA_MAX_DIM][2]
void * my_face_h [2]
void * my_face_hd [2]
void * my_face_d [2]
void * my_face_dim_dir_h [2][QUDA_MAX_DIM][2]
void * my_face_dim_dir_hd [2][QUDA_MAX_DIM][2]
void * my_face_dim_dir_d [2][QUDA_MAX_DIM][2]
void * from_face_h [2]
void * from_face_hd [2]
void * from_face_d [2]
void * from_face_dim_dir_h [2][QUDA_MAX_DIM][2]
void * from_face_dim_dir_hd [2][QUDA_MAX_DIM][2]
void * from_face_dim_dir_d [2][QUDA_MAX_DIM][2]
MsgHandle * mh_recv_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_back [2][QUDA_MAX_DIM]
MsgHandle * mh_send_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_send_back [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_rdma_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_recv_rdma_back [2][QUDA_MAX_DIM]
MsgHandle * mh_send_rdma_fwd [2][QUDA_MAX_DIM]
MsgHandle * mh_send_rdma_back [2][QUDA_MAX_DIM]
bool initComms
char vol_string [TuneKey::volume_n]
char aux_string [TuneKey::aux_n]
QudaMemoryType mem_type
char * backup_h
char * backup_norm_h
bool backed_up
Private Member Functions
void create (int nDim, const int *x, int Nc, int Ns, int Nvec, QudaTwistFlavorType Twistflavor, QudaPrecision precision, int pad, QudaSiteSubset subset, QudaSiteOrder siteOrder, QudaFieldOrder fieldOrder, QudaGammaBasis gammaBasis, QudaPCType pc_type)
void destroy ()
Friends
class ColorSpinorParam
std::ostream & operator<< (std::ostream &out, const ColorSpinorField &)
Additional Inherited Members
Static Public Attributes inherited from quda::LatticeField
static int bufferIndex = 0
static bool ghost_field_reset = false
Static Protected Attributes inherited from quda::LatticeField
static void * ghost_send_buffer_d [2] = {nullptr, nullptr}
static void * ghost_recv_buffer_d [2] = {nullptr, nullptr}
static void * ghost_pinned_send_buffer_h [2] = {nullptr, nullptr}
static void * ghost_pinned_recv_buffer_h [2] = {nullptr, nullptr}
static void * ghost_pinned_send_buffer_hd [2] = {nullptr, nullptr}
static void * ghost_pinned_recv_buffer_hd [2] = {nullptr, nullptr}
static void * ghost_remote_send_buffer_d [2][QUDA_MAX_DIM][2]
static size_t ghostFaceBytes = 0
static bool initGhostFaceBuffer = false
static MsgHandle * mh_send_p2p_fwd [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_send_p2p_back [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_recv_p2p_fwd [2][QUDA_MAX_DIM] { }
static MsgHandle * mh_recv_p2p_back [2][QUDA_MAX_DIM] { }
static int buffer_send_p2p_fwd [2][QUDA_MAX_DIM] { }
static int buffer_recv_p2p_fwd [2][QUDA_MAX_DIM] { }
static int buffer_send_p2p_back [2][QUDA_MAX_DIM] { }
static int buffer_recv_p2p_back [2][QUDA_MAX_DIM] { }
static cudaEvent_t ipcCopyEvent [2][2][QUDA_MAX_DIM]
static cudaEvent_t ipcRemoteCopyEvent [2][2][QUDA_MAX_DIM]
static bool initIPCComms = false
Detailed Description
Definition at line 311 of file color_spinor_field.h.
Constructor & Destructor Documentation
ColorSpinorField() [1/2]
quda::ColorSpinorField::ColorSpinorField (const ColorSpinorField & field)
Definition at line 28 of file color_spinor_field.cpp.
References create(), fieldOrder, gammaBasis, ghost_buf, nColor, nDim, nSpin, nVec, pad, pc_type, quda::LatticeField::Precision(), QUDA_MAX_DIM, siteOrder, siteSubset, twistFlavor, and x.
ColorSpinorField() [2/2]
quda::ColorSpinorField::ColorSpinorField (const ColorSpinorParam & param)
Definition at line 16 of file color_spinor_field.cpp.
References create(), quda::ColorSpinorParam::fieldOrder, quda::ColorSpinorParam::gammaBasis, ghost_buf, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::ColorSpinorParam::nSpin, quda::ColorSpinorParam::nVec, quda::LatticeFieldParam::pad, quda::ColorSpinorParam::pc_type, quda::LatticeFieldParam::Precision(), QUDA_MAX_DIM, quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::ColorSpinorParam::twistFlavor, and quda::LatticeFieldParam::x.
~ColorSpinorField()
quda::ColorSpinorField::~ColorSpinorField () virtual
Definition at line 39 of file color_spinor_field.cpp.
References destroy().
Member Function Documentation
Bytes()
size_t quda::ColorSpinorField::Bytes () const inline
Definition at line 418 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::bytes.
Referenced by quda::SpinorNoise< real, Ns, Nc, type, Arg >::bytes(), quda::blas::BlasCuda< FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Functor >::bytes(), quda::blas::ReduceCuda< doubleN, ReduceType, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Reducer >::bytes(), quda::DslashCoarsePolicyTune::bytes(), quda::blas::copy_ns::copy(), quda::cpuColorSpinorField::copy(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::loadSpinorField(), quda::blas::BlasCuda< FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Functor >::postTune(), quda::blas::ReduceCuda< doubleN, ReduceType, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Reducer >::postTune(), quda::blas::BlasCuda< FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Functor >::preTune(), quda::blas::ReduceCuda< doubleN, ReduceType, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Reducer >::preTune(), and quda::cudaColorSpinorField::saveSpinorField().
checkField()
void quda::ColorSpinorField::checkField (const ColorSpinorField & a, const ColorSpinorField & b) static protected
Definition at line 586 of file color_spinor_field.cpp.
References errorQuda, Length(), Ncolor(), Nspin(), Nvec(), and TwistFlavor().
Referenced by quda::cpuColorSpinorField::Compare(), quda::cudaColorSpinorField::copy(), quda::cpuColorSpinorField::copy(), and quda::cudaColorSpinorField::CopySubset().
Component() [1/2]
ColorSpinorField & quda::ColorSpinorField::Component (const int idx) const
Definition at line 653 of file color_spinor_field.cpp.
References components, CompositeDim(), errorQuda, and IsComposite().
Referenced by quda::Solver::blocksolve(), quda::CG::blocksolve(), quda::Deflation::Deflation(), quda::GMResDR::FlexArnoldiProcedure(), quda::Deflation::increment(), invertMultiSrcQuda(), quda::GMResDR::operator()(), quda::Deflation::reduce(), quda::IncEigCG::RestartVT(), quda::GMResDR::RestartVZH(), test(), and quda::IncEigCG::UpdateVm().
Component() [2/2]
ColorSpinorField & quda::ColorSpinorField::Component (const int idx)
Definition at line 640 of file color_spinor_field.cpp.
References components, CompositeDim(), errorQuda, and IsComposite().
ComponentBytes()
size_t quda::ColorSpinorField::ComponentBytes () const inline
Definition at line 476 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::bytes.
ComponentId()
int quda::ColorSpinorField::ComponentId () const inline
Definition at line 469 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::id.
ComponentLength()
size_t quda::ColorSpinorField::ComponentLength () const inline
Definition at line 473 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::length.
ComponentNormBytes()
size_t quda::ColorSpinorField::ComponentNormBytes () const inline
Definition at line 477 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::norm_bytes.
ComponentRealLength()
size_t quda::ColorSpinorField::ComponentRealLength () const inline
Definition at line 474 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::real_length.
Components()
CompositeColorSpinorField& quda::ColorSpinorField::Components () inline
Definition at line 517 of file color_spinor_field.h.
References quda::operator<<(), out, param, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_PRECISION, QUDA_MEMORY_INVALID, and quda::s.
Referenced by benchmark(), quda::blas::caxpy(), quda::blas::caxpy_L(), quda::blas::caxpy_U(), quda::blas::caxpyz(), quda::blas::caxpyz_L(), quda::blas::caxpyz_U(), quda::GMResDR::FlexArnoldiProcedure(), quda::Deflation::increment(), quda::Deflation::loadVectors(), quda::Deflation::operator()(), quda::GMResDR::operator()(), quda::Deflation::reduce(), quda::EigCGArgs::RestartLanczos(), quda::IncEigCG::RestartVT(), quda::GMResDR::RestartVZH(), quda::Deflation::saveVectors(), test(), quda::GMResDR::UpdateSolution(), and quda::Deflation::verify().
ComponentStride()
int quda::ColorSpinorField::ComponentStride () const inline
Definition at line 472 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::stride.
ComponentVolume()
int quda::ColorSpinorField::ComponentVolume () const inline
Definition at line 470 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::volume.
ComponentVolumeCB()
int quda::ColorSpinorField::ComponentVolumeCB () const inline
Definition at line 471 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::volumeCB.
CompositeDim()
int quda::ColorSpinorField::CompositeDim () const inline
Definition at line 468 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::dim.
Referenced by Component(), quda::cudaColorSpinorField::Component(), quda::blas::copy_ns::copy(), and quda::Deflation::increment().
create()
void quda::ColorSpinorField::create (int nDim, const int * x, int Nc, int Ns, int Nvec, QudaTwistFlavorType Twistflavor, QudaPrecision precision, int pad, QudaSiteSubset subset, QudaSiteOrder siteOrder, QudaFieldOrder fieldOrder, QudaGammaBasis gammaBasis, QudaPCType pc_type) private
stuff for deflated solvers (eigenvector sets):
Definition at line 171 of file color_spinor_field.cpp.
References ALIGNMENT_ADJUST, quda::CompositeColorSpinorFieldDescriptor::bytes, bytes, composite_descr, quda::CompositeColorSpinorFieldDescriptor::dim, errorQuda, fieldOrder, gammaBasis, init, quda::CompositeColorSpinorFieldDescriptor::is_component, quda::CompositeColorSpinorFieldDescriptor::is_composite, isNative(), quda::CompositeColorSpinorFieldDescriptor::length, length, nColor, nDim, Ndim(), quda::CompositeColorSpinorFieldDescriptor::norm_bytes, norm_bytes, nSpin, nVec, Nvec(), pad, Pad(), pc_type, quda::LatticeField::precision, QUDA_FLOAT2_FIELD_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_HALF_PRECISION, QUDA_MAX_DIM, QUDA_PARITY_SITE_SUBSET, QUDA_QUARTER_PRECISION, QUDA_TWIST_DEG_DOUBLET, QUDA_TWIST_NONDEG_DOUBLET, quda::CompositeColorSpinorFieldDescriptor::real_length, real_length, setTuningString(), siteOrder, siteSubset, quda::CompositeColorSpinorFieldDescriptor::stride, stride, twistFlavor, quda::CompositeColorSpinorFieldDescriptor::volume, volume, quda::CompositeColorSpinorFieldDescriptor::volumeCB, volumeCB, and x.
Referenced by ColorSpinorField(), and operator=().
Create() [1/2]
ColorSpinorField * quda::ColorSpinorField::Create (const ColorSpinorParam & param) static
Definition at line 752 of file color_spinor_field.cpp.
References errorQuda, quda::ColorSpinorParam::location, QUDA_CPU_FIELD_LOCATION, and QUDA_CUDA_FIELD_LOCATION.
Referenced by quda::ax(), quda::CG::blocksolve(), quda::MG::buildFreeVectors(), quda::EigenSolver::chebyOp(), cloverQuda(), quda::CoarseCoarseOp(), quda::CoarseOp(), computeCloverForceQuda(), quda::TRLM::computeKeptRitz(), computeStaggeredForceQuda(), quda::Solver::constructDeflationSpace(), contractQuda(), quda::CACG::create(), quda::CAGCR::create(), quda::Transfer::createTmp(), quda::Transfer::createV(), quda::deflated_solver::deflated_solver(), quda::Deflation::Deflation(), dslashQuda(), dslashQuda_4dpc(), dslashQuda_mdwf(), quda::IncEigCG::eigCGsolve(), eigensolveQuda(), quda::MG::generateEigenVectors(), quda::IncEigCG::initCGsolve(), invertMultiShiftQuda(), invertMultiSrcQuda(), invertQuda(), quda::EigenSolver::loadFromFile(), quda::EigenSolver::loadVectors(), MatDagMatQuda(), MatQuda(), quda::EigenSolver::matVec(), quda::MG::MG(), quda::multigrid_solver::multigrid_solver(), quda::norm1(), quda::norm2(), quda::TRLM::operator()(), quda::CG::operator()(), quda::CG3::operator()(), quda::CG3NE::operator()(), quda::CGNE::operator()(), quda::CGNR::operator()(), quda::BiCGstab::operator()(), quda::BiCGstabL::operator()(), quda::GCR::operator()(), quda::MR::operator()(), quda::CACGNE::operator()(), quda::CACGNR::operator()(), quda::MultiShiftCG::operator()(), quda::IncEigCG::operator()(), quda::GMResDR::operator()(), performWuppertalnStep(), quda::Deflation::reduce(), quda::EigenSolver::saveVectors(), quda::spinorNoise(), and quda::MG::verify().
Create() [2/2]
ColorSpinorField * quda::ColorSpinorField::Create (const ColorSpinorField & src, const ColorSpinorParam & param) static
Definition at line 766 of file color_spinor_field.cpp.
References errorQuda, quda::ColorSpinorParam::location, QUDA_CPU_FIELD_LOCATION, and QUDA_CUDA_FIELD_LOCATION.
CreateCoarse()
ColorSpinorField * quda::ColorSpinorField::CreateCoarse (const int * geoBlockSize, int spinBlockSize, int Nvec, QudaPrecision precision = QUDA_INVALID_PRECISION, QudaFieldLocation location = QUDA_INVALID_FIELD_LOCATION, QudaMemoryType mem_Type = QUDA_MEMORY_INVALID)
Create a coarse color-spinor field, using this field to set the meta data.
Parameters
[in] geoBlockSize Geometric block size that defines the coarse grid dimensions
[in] spinlockSize Geometric block size that defines the coarse spin dimension
[in] Nvec Number of coarse color degrees of freedom per grid point
[in] precision Optionally set the precision of the fine field
[in] location Optionally set the location of the coarse field
[in] mem_type Optionally set the memory type used (e.g., can override with mapped memory)
Definition at line 780 of file color_spinor_field.cpp.
References quda::ColorSpinorParam::create, errorQuda, quda::ColorSpinorParam::fieldOrder, quda::LatticeField::Location(), quda::LatticeFieldParam::mem_type, quda::ColorSpinorParam::nColor, nDim, quda::ColorSpinorParam::nSpin, nSpin, quda::LatticeField::Precision(), QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, QUDA_FLOAT2_FIELD_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_PRECISION, QUDA_MEMORY_DEVICE, QUDA_MEMORY_INVALID, QUDA_MEMORY_PINNED, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, QUDA_ZERO_FIELD_CREATE, quda::ColorSpinorParam::setPrecision(), quda::LatticeFieldParam::siteSubset, quda::LatticeFieldParam::x, and x.
Referenced by quda::Transfer::createTmp().
CreateFine()
ColorSpinorField * quda::ColorSpinorField::CreateFine (const int * geoblockSize, int spinBlockSize, int Nvec, QudaPrecision precision = QUDA_INVALID_PRECISION, QudaFieldLocation location = QUDA_INVALID_FIELD_LOCATION, QudaMemoryType mem_type = QUDA_MEMORY_INVALID)
Create a fine color-spinor field, using this field to set the meta data.
Parameters
[in] geoBlockSize Geometric block size that defines the fine grid dimensions
[in] spinlockSize Geometric block size that defines the fine spin dimension
[in] Nvec Number of fine color degrees of freedom per grid point
[in] precision Optionally set the precision of the fine field
[in] location Optionally set the location of the fine field
[in] mem_type Optionally set the memory type used (e.g., can override with mapped memory)
Definition at line 819 of file color_spinor_field.cpp.
References quda::ColorSpinorParam::create, errorQuda, quda::ColorSpinorParam::fieldOrder, quda::LatticeField::Location(), quda::LatticeFieldParam::mem_type, quda::ColorSpinorParam::nColor, nDim, quda::ColorSpinorParam::nSpin, nSpin, quda::LatticeFieldParam::Precision(), quda::LatticeField::Precision(), QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT4_FIELD_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_INVALID_FIELD_LOCATION, QUDA_INVALID_PRECISION, QUDA_MEMORY_DEVICE, QUDA_MEMORY_INVALID, QUDA_MEMORY_PINNED, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, QUDA_ZERO_FIELD_CREATE, quda::ColorSpinorParam::setPrecision(), quda::LatticeFieldParam::siteSubset, quda::LatticeFieldParam::x, and x.
createGhostZone()
void quda::ColorSpinorField::createGhostZone (int nFace, bool spin_project = true) const protected
Compute the required extended ghost zone sizes and offsets
Parameters
[in] nFace The depth of the halo
[in] spin_project Whether we are spin projecting
includes DW and non-degenerate TM ghosts
temporal hack : extra dimension for DW ghosts
Definition at line 43 of file color_spinor_field.cpp.
References ALIGNMENT_ADJUST, comm_dim_partitioned(), dims, quda::DslashConstant::dims, dslash_constant, errorQuda, quda::DslashConstant::face_T, quda::DslashConstant::face_X, quda::DslashConstant::face_XY, quda::DslashConstant::face_XYZ, quda::DslashConstant::face_XYZT, quda::DslashConstant::face_Y, quda::DslashConstant::face_Z, FieldOrder(), quda::LatticeField::ghost_bytes, quda::LatticeField::ghost_face_bytes, quda::LatticeField::ghost_precision, ghost_precision_allocated, quda::DslashConstant::ghostFace, ghostFace, quda::DslashConstant::ghostFaceCB, ghostFaceCB, quda::LatticeField::ghostNormOffset, quda::LatticeField::ghostOffset, GhostOffset(), isNative(), quda::DslashConstant::Ls, nColor, nDim, nSpin, QUDA_FULL_SITE_SUBSET, QUDA_HALF_PRECISION, QUDA_MAX_DIM, QUDA_PARITY_SITE_SUBSET, QUDA_QUARTER_PRECISION, siteSubset, quda::DslashConstant::Vh, quda::DslashConstant::volume_4d, quda::DslashConstant::volume_4d_cb, volumeCB, quda::DslashConstant::X, x, X(), quda::DslashConstant::X2X1, quda::DslashConstant::X2X1mX1, quda::DslashConstant::X3X2X1, quda::DslashConstant::X3X2X1mX2X1, quda::DslashConstant::X4X3X2X1, quda::DslashConstant::X4X3X2X1hmX3X2X1h, quda::DslashConstant::X4X3X2X1mX3X2X1, quda::DslashConstant::X5X4X3X2X1mX4X3X2X1, and quda::DslashConstant::Xh.
Referenced by quda::cudaColorSpinorField::allocateGhostBuffer().
destroy()
void quda::ColorSpinorField::destroy () private
Definition at line 288 of file color_spinor_field.cpp.
References init.
Referenced by ~ColorSpinorField().
Even() [1/2]
const ColorSpinorField & quda::ColorSpinorField::Even () const
Definition at line 608 of file color_spinor_field.cpp.
References errorQuda, even, fieldOrder, QUDA_FULL_SITE_SUBSET, QUDA_QDPJIT_FIELD_ORDER, and siteSubset.
Referenced by benchmark(), computeCloverForceQuda(), computeStaggeredForceQuda(), quda::computeStaggeredOprod(), quda::MG::createCoarseDirac(), invert_test(), matdagmat(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::MG::operator()(), quda::Transfer::P(), quda::DiracWilsonPC::prepare(), quda::DiracCloverPC::prepare(), quda::DiracDomainWallPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracStaggeredPC::prepare(), quda::DiracImprovedStaggeredPC::prepare(), quda::DiracCoarsePC::prepare(), quda::GaugeLaplacePC::prepare(), quda::Transfer::R(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWallPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), quda::DiracStaggeredPC::reconstruct(), quda::DiracImprovedStaggeredPC::reconstruct(), quda::DiracCoarsePC::reconstruct(), quda::GaugeLaplacePC::reconstruct(), quda::shiftColorSpinorField(), staggeredDslashRef(), and quda::MG::verify().
Even() [2/2]
ColorSpinorField & quda::ColorSpinorField::Even ()
Definition at line 624 of file color_spinor_field.cpp.
References errorQuda, even, fieldOrder, QUDA_FULL_SITE_SUBSET, QUDA_QDPJIT_FIELD_ORDER, and siteSubset.
exchange()
void quda::ColorSpinorField::exchange (void ** ghost, void ** sendbuf, int nFace = 1) const
Do the exchange between neighbouring nodes of the data in sendbuf storing the result in recvbuf. The arrays are ordered (2*dim + dir).
Parameters
recvbuf Packed buffer where we store the result
sendbuf Packed buffer from which we're sending
nFace Number of layers we are exchanging
Definition at line 427 of file color_spinor_field.cpp.
References bytes, comm_declare_receive_relative, comm_declare_send_relative, comm_dim_partitioned(), comm_free(), comm_start(), comm_wait(), quda::LatticeField::ghost_precision, quda::LatticeField::Location(), quda::LatticeField::mh_send_back, quda::LatticeField::mh_send_fwd, nColor, quda::LatticeField::nDimComms, nSpin, pool_pinned_free, pool_pinned_malloc, QUDA_CPU_FIELD_LOCATION, QUDA_CUDA_FIELD_LOCATION, qudaMemcpy, siteSubset, quda::LatticeField::surfaceCB, and quda::LatticeField::total_bytes.
Referenced by quda::cpuColorSpinorField::exchangeGhost(), and quda::reduceRow().
exchangeGhost()
virtual void quda::ColorSpinorField::exchangeGhost (QudaParity parity, int nFace, int dagger, const MemoryLocation * pack_destination = nullptr, const MemoryLocation * halo_location = nullptr, bool gdr_send = false, bool gdr_recv = false, QudaPrecision ghost_precision = QUDA_INVALID_PRECISION) const pure virtual
This is a unified ghost exchange function for doing a complete halo exchange regardless of the type of field. All dimensions are exchanged and no spin projection is done in the case of Wilson fermions.
Parameters
[in] parity Field parity
[in] nFace Depth of halo exchange
[in] dagger Is this for a dagger operator (only relevant for spin projected Wilson)
[in] pack_destination Destination of the packing buffer
[in] halo_location Destination of the halo reading buffer
[in] gdr_send Are we using GDR for sending
[in] gdr_recv Are we using GDR for receiving
[in] ghost_precision The precision used for the ghost exchange
Implemented in quda::cpuColorSpinorField, and quda::cudaColorSpinorField.
Referenced by quda::calculateY(), quda::DslashCoarseLaunch::operator()(), and quda::wuppertalStep().
FieldOrder()
QudaFieldOrder quda::ColorSpinorField::FieldOrder () const inline
Definition at line 483 of file color_spinor_field.h.
Referenced by quda::ApplyCovDev(), quda::ApplyDomainWall4D(), quda::ApplyDomainWall5D(), quda::ApplyImprovedStaggered(), quda::ApplyLaplace(), quda::ApplyNdegTwistedMass(), quda::ApplyNdegTwistedMassPreconditioned(), quda::ApplyStaggered(), quda::ApplyTwistedClover(), quda::ApplyTwistedCloverPreconditioned(), quda::ApplyTwistedMass(), quda::ApplyTwistedMassPreconditioned(), quda::ApplyWilson(), quda::ApplyWilsonClover(), quda::ApplyWilsonCloverPreconditioned(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), quda::CovDevArg< Float, nColor, reconstruct_ >::CovDevArg(), createGhostZone(), quda::Dslash5Arg< Float, nColor >::Dslash5Arg(), quda::GammaArg< Float, nColor >::GammaArg(), quda::genericCompare(), quda::genericCopyColorSpinor(), quda::genericCudaPrintVector(), quda::genericPrintVector(), quda::genericSource(), quda::LaplaceArg< Float, nColor, reconstruct_ >::LaplaceArg(), quda::cudaColorSpinorField::loadSpinorField(), quda::blas::mixed_reduce(), quda::LatticeField::Nvec(), quda::PackArg< Float_, nColor_, nSpin_, spin_project_ >::PackArg(), quda::Prolongate(), quda::Restrict(), quda::cudaColorSpinorField::saveSpinorField(), quda::spinorNoise(), quda::StaggeredArg< Float, nColor, reconstruct_u_, reconstruct_l_, improved_, phase_ >::StaggeredArg(), quda::blas::uni_blas(), quda::blas::uni_reduce(), and quda::WilsonArg< Float, nColor, reconstruct_ >::WilsonArg().
fill()
void quda::ColorSpinorField::fill (ColorSpinorParam & param) const protected
Definition at line 403 of file color_spinor_field.cpp.
References quda::ColorSpinorParam::component_id, composite_descr, quda::ColorSpinorParam::composite_dim, quda::ColorSpinorParam::create, quda::CompositeColorSpinorFieldDescriptor::dim, quda::ColorSpinorParam::fieldOrder, fieldOrder, quda::ColorSpinorParam::gammaBasis, gammaBasis, quda::LatticeField::ghost_precision, quda::ColorSpinorParam::is_component, quda::CompositeColorSpinorFieldDescriptor::is_composite, quda::ColorSpinorParam::is_composite, quda::ColorSpinorParam::location, quda::LatticeField::Location(), quda::ColorSpinorParam::nColor, nColor, quda::LatticeFieldParam::nDim, nDim, quda::ColorSpinorParam::nSpin, nSpin, quda::ColorSpinorParam::nVec, nVec, quda::LatticeFieldParam::pad, pad, quda::ColorSpinorParam::pc_type, pc_type, quda::LatticeField::precision, QUDA_INVALID_FIELD_CREATE, QUDA_MAX_DIM, quda::ColorSpinorParam::setPrecision(), quda::ColorSpinorParam::siteOrder, siteOrder, quda::LatticeFieldParam::siteSubset, siteSubset, quda::ColorSpinorParam::twistFlavor, twistFlavor, quda::LatticeFieldParam::x, and x.
Referenced by quda::ColorSpinorParam::ColorSpinorParam().
GammaBasis()
QudaGammaBasis quda::ColorSpinorField::GammaBasis () const inline
Definition at line 484 of file color_spinor_field.h.
Referenced by quda::CopyColorSpinor< 4, Arg >::apply(), quda::Dirac::checkParitySpinor(), quda::contractQuda(), quda::cudaColorSpinorField::copy(), quda::CopyColorSpinor< Ns, Arg >::CopyColorSpinor(), quda::CopyColorSpinor< 4, Arg >::CopyColorSpinor(), quda::cudaColorSpinorField::copySpinorField(), quda::extendedCopyColorSpinor(), quda::Transfer::P(), and quda::Transfer::R().
getDslashConstant()
const DslashConstant& quda::ColorSpinorField::getDslashConstant () const inline
Get the dslash_constant structure from this field.
Definition at line 506 of file color_spinor_field.h.
Referenced by quda::Pack< Float, nColor, spin_project >::bytes(), quda::DomainWall4DApply< Float, nColor, recon >::DomainWall4DApply(), quda::DomainWall5DApply< Float, nColor, recon >::DomainWall5DApply(), quda::Pack< Float, nColor, spin_project >::flops(), quda::NdegTwistedMassApply< Float, nColor, recon >::NdegTwistedMassApply(), quda::NdegTwistedMassPreconditionedApply< Float, nColor, recon >::NdegTwistedMassPreconditionedApply(), and quda::Pack< Float, nColor, spin_project >::Pack().
Ghost() [1/3]
void * quda::ColorSpinorField::Ghost (const int i)
Definition at line 667 of file color_spinor_field.cpp.
References errorQuda, ghost, QUDA_PARITY_SITE_SUBSET, and siteSubset.
Referenced by quda::calculateY(), quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::FieldOrderCB(), and quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::FloatNOrder().
Ghost() [2/3]
const void * quda::ColorSpinorField::Ghost (const int i) const
Definition at line 672 of file color_spinor_field.cpp.
References errorQuda, ghost, QUDA_PARITY_SITE_SUBSET, and siteSubset.
Ghost() [3/3]
void *const * quda::ColorSpinorField::Ghost () const
Return array of pointers to the ghost zones (ordering dim*2+dir)
Definition at line 688 of file color_spinor_field.cpp.
References ghost_buf.
Ghost2()
virtual const void* quda::ColorSpinorField::Ghost2 () const inline virtual
Reimplemented in quda::cudaColorSpinorField.
Definition at line 428 of file color_spinor_field.h.
References dagger, parity, and QUDA_INVALID_PRECISION.
Referenced by quda::Dslash< Float >::setParam().
GhostBytes()
size_t quda::ColorSpinorField::GhostBytes () const inline
Definition at line 420 of file color_spinor_field.h.
Referenced by dslashTest(), main(), and TEST_P().
GhostFace()
const int* quda::ColorSpinorField::GhostFace () const inline
Definition at line 486 of file color_spinor_field.h.
Referenced by quda::TwistedCloverPreconditioned< Float, nDim, nColor, Arg >::bytes(), quda::WilsonCloverPreconditioned< Float, nDim, nColor, Arg >::bytes(), quda::Staggered< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Dslash< Float >::bytes(), quda::computeCloverForce(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::WilsonCloverPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::TwistedCloverPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::Staggered< Float, nDim, nColor, Arg >::flops(), and quda::Dslash< Float >::flops().
GhostFaceCB()
const int* quda::ColorSpinorField::GhostFaceCB () const inline
Definition at line 487 of file color_spinor_field.h.
Referenced by quda::ImprovedStaggeredApply< Float, nColor, recon_l >::ImprovedStaggeredApply(), quda::LaplaceApply< Float, nColor, recon >::LaplaceApply(), quda::StaggeredApply< Float, nColor, recon_u >::StaggeredApply(), quda::TwistedCloverApply< Float, nColor, recon >::TwistedCloverApply(), quda::TwistedCloverPreconditionedApply< Float, nColor, recon >::TwistedCloverPreconditionedApply(), quda::TwistedMassApply< Float, nColor, recon >::TwistedMassApply(), quda::TwistedMassPreconditionedApply< Float, nColor, recon >::TwistedMassPreconditionedApply(), quda::WilsonApply< Float, nColor, recon >::WilsonApply(), quda::WilsonCloverApply< Float, nColor, recon >::WilsonCloverApply(), and quda::WilsonCloverPreconditionedApply< Float, nColor, recon >::WilsonCloverPreconditionedApply().
GhostNorm() [1/2]
void * quda::ColorSpinorField::GhostNorm (const int i)
Definition at line 678 of file color_spinor_field.cpp.
References errorQuda, ghostNorm, QUDA_PARITY_SITE_SUBSET, and siteSubset.
GhostNorm() [2/2]
const void * quda::ColorSpinorField::GhostNorm (const int i) const
Definition at line 683 of file color_spinor_field.cpp.
References errorQuda, ghostNorm, QUDA_PARITY_SITE_SUBSET, and siteSubset.
GhostNormBytes()
size_t quda::ColorSpinorField::GhostNormBytes () const inline
Definition at line 421 of file color_spinor_field.h.
GhostNormOffset() [1/2]
int quda::ColorSpinorField::GhostNormOffset (const int i) const inline
Definition at line 490 of file color_spinor_field.h.
Referenced by quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::resetGhost().
GhostNormOffset() [2/2]
int quda::ColorSpinorField::GhostNormOffset (const int i, const int j) const inline
Definition at line 491 of file color_spinor_field.h.
GhostOffset() [1/2]
int quda::ColorSpinorField::GhostOffset (const int i) const inline
Definition at line 488 of file color_spinor_field.h.
Referenced by createGhostZone(), quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::resetGhost(), and quda::Dslash< Float >::setParam().
GhostOffset() [2/2]
int quda::ColorSpinorField::GhostOffset (const int i, const int j) const inline
Definition at line 489 of file color_spinor_field.h.
IsComponent()
bool quda::ColorSpinorField::IsComponent () const inline
Definition at line 466 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::is_component.
IsComposite()
bool quda::ColorSpinorField::IsComposite () const inline
Definition at line 465 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::is_composite.
Referenced by Component(), quda::cudaColorSpinorField::Component(), quda::blas::copy_ns::copy(), quda::DeflationParam::DeflationParam(), quda::Deflation::loadVectors(), and quda::Deflation::saveVectors().
isNative()
bool quda::ColorSpinorField::isNative () const
This function returns true if the field is stored in an internal field order, given the precision and the length of the spin dimension.
Definition at line 568 of file color_spinor_field.cpp.
References fieldOrder, nColor, nSpin, quda::LatticeField::precision, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT4_FIELD_ORDER, QUDA_HALF_PRECISION, QUDA_QUARTER_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by quda::cudaColorSpinorField::copySpinorField(), quda::CovDevArg< Float, nColor, reconstruct_ >::CovDevArg(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), createGhostZone(), quda::Dslash5Arg< Float, nColor >::Dslash5Arg(), quda::extendedCopyColorSpinor(), quda::GammaArg< Float, nColor >::GammaArg(), quda::genericCopyColorSpinor(), quda::LaplaceArg< Float, nColor, reconstruct_ >::LaplaceArg(), quda::blas::mixed_blas(), quda::blas::mixed_reduce(), quda::PackArg< Float_, nColor_, nSpin_, spin_project_ >::PackArg(), reset(), quda::StaggeredArg< Float, nColor, reconstruct_u_, reconstruct_l_, improved_, phase_ >::StaggeredArg(), quda::blas::uni_blas(), quda::blas::uni_reduce(), and quda::WilsonArg< Float, nColor, reconstruct_ >::WilsonArg().
LatticeIndex()
void quda::ColorSpinorField::LatticeIndex (int * y, int i) const
Compute the n-dimensional site index given the 1-d offset index
Parameters
y n-dimensional site index
i 1-dimensional site index
Definition at line 698 of file color_spinor_field.cpp.
References nDim, parity, QUDA_FULL_SITE_SUBSET, QUDA_MAX_DIM, siteSubset, and x.
Referenced by quda::Transfer::createGeoMap().
Length()
size_t quda::ColorSpinorField::Length () const inline
Definition at line 413 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::length.
Referenced by checkField(), quda::checkLength(), quda::checkSpinor(), quda::blas::copy_ns::copy(), invert_test(), quda::blas::mixed_reduce(), staggeredDslashRef(), quda::blas::uni_blas(), and quda::blas::uni_reduce().
Ncolor()
int quda::ColorSpinorField::Ncolor () const inline
Definition at line 405 of file color_spinor_field.h.
References nColor.
Referenced by quda::ApplyClover(), quda::ApplyDslash5(), quda::ApplyGamma(), quda::ApplyTwistClover(), quda::ApplyTwistGamma(), quda::DomainWall5D< Float, nDim, nColor, Arg >::bytes(), quda::Staggered< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Dslash< Float >::bytes(), checkField(), quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), quda::contractQuda(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracCoarse::DslashXpay(), quda::DiracCoarsePC::DslashXpay(), quda::Dslash5< Float, nColor, Arg >::flops(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::Staggered< Float, nDim, nColor, Arg >::flops(), quda::Dslash< Float >::flops(), quda::DslashCoarsePolicyTune::flops(), quda::genericCompare(), quda::genericCudaPrintVector(), quda::genericPrintVector(), quda::genericSource(), quda::blas::HeavyQuarkResidualNorm(), quda::instantiate(), quda::DiracCoarse::M(), quda::blas::mixed_reduce(), quda::Transfer::P(), quda::PackGhost(), quda::Transfer::R(), quda::spinorNoise(), quda::blas::uni_blas(), quda::blas::uni_reduce(), quda::wuppertalStep(), and quda::blas::xpyHeavyQuarkResidualNorm().
Ndim()
int quda::ColorSpinorField::Ndim () const inline
Definition at line 409 of file color_spinor_field.h.
Referenced by quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::BlockOrthoArg(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracImprovedStaggered::checkParitySpinor(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), create(), quda::Transfer::createGeoMap(), quda::DiracCoarse::createY(), quda::DiracCoarse::createYhat(), quda::DslashArg< Float >::DslashArg(), quda::DslashCoarseArg< Float, yFloat, ghostFloat, coarseSpin, coarseColor, csOrder, gOrder >::DslashCoarseArg(), quda::Pack< Float, nColor, spin_project >::gridStep(), quda::DiracDomainWall4DPC::M(), quda::Pack< Float, nColor, spin_project >::maxGridSize(), and quda::Pack< Float, nColor, spin_project >::minGridSize().
Norm() [1/2]
void* quda::ColorSpinorField::Norm () inline
Definition at line 426 of file color_spinor_field.h.
References quda::norm().
Referenced by quda::blas::copy_ns::copy(), quda::copyExtendedColorSpinor(), quda::cpuColorSpinorField::cpuColorSpinorField(), quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::FieldOrderCB(), quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::FloatNOrder(), quda::genericCudaPrintVector(), quda::cudaColorSpinorField::loadSpinorField(), and quda::cudaColorSpinorField::saveSpinorField().
Norm() [2/2]
const void* quda::ColorSpinorField::Norm () const inline
Definition at line 427 of file color_spinor_field.h.
References quda::norm().
NormBytes()
size_t quda::ColorSpinorField::NormBytes () const inline
Definition at line 419 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::norm_bytes.
Referenced by quda::blas::copy_ns::copy(), quda::copyExtendedColorSpinor(), quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::FieldOrderCB(), quda::cudaColorSpinorField::loadSpinorField(), quda::blas::BlasCuda< FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Functor >::postTune(), quda::blas::ReduceCuda< doubleN, ReduceType, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Reducer >::postTune(), quda::blas::BlasCuda< FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Functor >::preTune(), quda::blas::ReduceCuda< doubleN, ReduceType, FloatN, M, SpinorX, SpinorY, SpinorZ, SpinorW, SpinorV, Reducer >::preTune(), and quda::cudaColorSpinorField::saveSpinorField().
Nspin()
int quda::ColorSpinorField::Nspin () const inline
Definition at line 406 of file color_spinor_field.h.
Referenced by quda::Pack< Float, nColor, spin_project >::apply(), quda::ApplyClover(), quda::ApplyTwistClover(), quda::DomainWall5D< Float, nDim, nColor, Arg >::bytes(), quda::Staggered< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Pack< Float, nColor, spin_project >::bytes(), quda::Dslash< Float >::bytes(), checkField(), quda::Dirac::checkParitySpinor(), quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), quda::contractQuda(), quda::blas::copy_ns::copy(), quda::CopyExtendedColorSpinor(), quda::CopyGenericColorSpinor(), quda::DiracCoarse::createY(), quda::DiracCoarse::createYhat(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::Dslash5Arg< Float, nColor >::Dslash5Arg(), quda::DiracCoarse::DslashXpay(), quda::DiracCoarsePC::DslashXpay(), quda::Pack< Float, nColor, spin_project >::fillAux(), quda::Dslash5< Float, nColor, Arg >::flops(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::Staggered< Float, nDim, nColor, Arg >::flops(), quda::Dslash< Float >::flops(), quda::Pack< Float, nColor, spin_project >::flops(), quda::DslashCoarsePolicyTune::flops(), quda::GammaArg< Float, nColor >::GammaArg(), quda::genericCompare(), quda::genericCudaPrintVector(), quda::genericPrintVector(), quda::genericSource(), quda::DiracCoarse::M(), main(), quda::blas::mixed_blas(), quda::blas::mixed_reduce(), quda::Transfer::P(), quda::Transfer::R(), quda::Dslash5< Float, nColor, Arg >::sharedBytesPerThread(), quda::shiftColorSpinorField(), quda::spinorNoise(), quda::blas::uni_blas(), quda::blas::uni_reduce(), and quda::wuppertalStep().
Nvec()
int quda::ColorSpinorField::Nvec () const inline
Definition at line 407 of file color_spinor_field.h.
Referenced by checkField(), create(), quda::cudaColorSpinorField::sendGhost(), and quda::cudaColorSpinorField::sendStart().
Odd() [1/2]
const ColorSpinorField & quda::ColorSpinorField::Odd () const
Definition at line 616 of file color_spinor_field.cpp.
References errorQuda, fieldOrder, odd, QUDA_FULL_SITE_SUBSET, QUDA_QDPJIT_FIELD_ORDER, and siteSubset.
Referenced by benchmark(), computeCloverForceQuda(), computeStaggeredForceQuda(), quda::computeStaggeredOprod(), invert_test(), matdagmat(), quda::DiracStaggered::MdagM(), quda::DiracImprovedStaggered::MdagM(), quda::DiracWilsonPC::prepare(), quda::DiracCloverPC::prepare(), quda::DiracDomainWallPC::prepare(), quda::DiracDomainWall4DPC::prepare(), quda::DiracMobiusPC::prepare(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracStaggeredPC::prepare(), quda::DiracImprovedStaggeredPC::prepare(), quda::DiracCoarsePC::prepare(), quda::GaugeLaplacePC::prepare(), quda::DiracWilsonPC::reconstruct(), quda::DiracCloverPC::reconstruct(), quda::DiracDomainWallPC::reconstruct(), quda::DiracDomainWall4DPC::reconstruct(), quda::DiracMobiusPC::reconstruct(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), quda::DiracStaggeredPC::reconstruct(), quda::DiracImprovedStaggeredPC::reconstruct(), quda::DiracCoarsePC::reconstruct(), quda::GaugeLaplacePC::reconstruct(), quda::shiftColorSpinorField(), staggeredDslashRef(), and quda::MG::verify().
Odd() [2/2]
ColorSpinorField & quda::ColorSpinorField::Odd ()
Definition at line 632 of file color_spinor_field.cpp.
References errorQuda, fieldOrder, odd, QUDA_FULL_SITE_SUBSET, QUDA_QDPJIT_FIELD_ORDER, and siteSubset.
OffsetIndex()
void quda::ColorSpinorField::OffsetIndex (int & i, int * y) const
Compute the 1-d offset index given the n-dimensional site index
Parameters
i 1-dimensional site index
y n-dimensional site index
Definition at line 727 of file color_spinor_field.cpp.
References nDim, parity, QUDA_FULL_SITE_SUBSET, QUDA_MAX_DIM, siteSubset, and x.
Referenced by quda::Transfer::createGeoMap().
operator=()
ColorSpinorField & quda::ColorSpinorField::operator= (const ColorSpinorField & src) virtual
Reimplemented in quda::cpuColorSpinorField, and quda::cudaColorSpinorField.
Definition at line 292 of file color_spinor_field.cpp.
References composite_descr, create(), quda::CompositeColorSpinorFieldDescriptor::dim, fieldOrder, gammaBasis, quda::CompositeColorSpinorFieldDescriptor::id, quda::CompositeColorSpinorFieldDescriptor::is_component, quda::CompositeColorSpinorFieldDescriptor::is_composite, nColor, nDim, nSpin, nVec, pad, pc_type, quda::LatticeField::precision, siteOrder, siteSubset, twistFlavor, and x.
Referenced by quda::cudaColorSpinorField::operator=(), and quda::cpuColorSpinorField::operator=().
Pad()
int quda::ColorSpinorField::Pad () const inline
Definition at line 417 of file color_spinor_field.h.
Referenced by create().
PCType()
QudaPCType quda::ColorSpinorField::PCType () const inline
Definition at line 479 of file color_spinor_field.h.
Referenced by quda::Pack< Float, nColor, spin_project >::apply(), quda::ApplyDslash5(), quda::Pack< Float, nColor, spin_project >::fillAux(), and quda::PCType_().
PrintDims()
void quda::ColorSpinorField::PrintDims () const inline
Definition at line 422 of file color_spinor_field.h.
References printfQuda.
PrintVector()
virtual void quda::ColorSpinorField::PrintVector (unsigned int x) const pure virtual
Implemented in quda::cpuColorSpinorField, and quda::cudaColorSpinorField.
Referenced by quda::MG::verify().
RealLength()
size_t quda::ColorSpinorField::RealLength () const inline
Definition at line 412 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::real_length.
Referenced by quda::blas::copy_ns::copy(), quda::blas::mixed_reduce(), quda::CG::operator()(), and quda::blas::uni_reduce().
reset()
void quda::ColorSpinorField::reset (const ColorSpinorParam & param) protected
for deflated solvers:
Definition at line 314 of file color_spinor_field.cpp.
References ALIGNMENT_ADJUST, quda::CompositeColorSpinorFieldDescriptor::bytes, bytes, quda::ColorSpinorParam::component_id, composite_descr, quda::ColorSpinorParam::composite_dim, quda::CompositeColorSpinorFieldDescriptor::dim, errorQuda, quda::ColorSpinorParam::fieldOrder, fieldOrder, quda::ColorSpinorParam::gammaBasis, gammaBasis, quda::LatticeField::ghost_precision, quda::LatticeFieldParam::GhostPrecision(), quda::CompositeColorSpinorFieldDescriptor::id, init, quda::CompositeColorSpinorFieldDescriptor::is_component, quda::ColorSpinorParam::is_component, quda::CompositeColorSpinorFieldDescriptor::is_composite, quda::ColorSpinorParam::is_composite, isNative(), quda::CompositeColorSpinorFieldDescriptor::length, length, quda::ColorSpinorParam::nColor, nColor, quda::LatticeFieldParam::nDim, nDim, quda::CompositeColorSpinorFieldDescriptor::norm_bytes, norm_bytes, quda::ColorSpinorParam::nSpin, nSpin, quda::ColorSpinorParam::nVec, nVec, quda::LatticeFieldParam::pad, pad, quda::ColorSpinorParam::pc_type, pc_type, quda::LatticeFieldParam::Precision(), quda::LatticeField::precision, QUDA_FLOAT2_FIELD_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_HALF_PRECISION, QUDA_INVALID_FIELD_ORDER, QUDA_INVALID_GAMMA_BASIS, QUDA_INVALID_PRECISION, QUDA_INVALID_SITE_ORDER, QUDA_INVALID_SITE_SUBSET, QUDA_PARITY_SITE_SUBSET, QUDA_PC_INVALID, QUDA_QUARTER_PRECISION, QUDA_TWIST_DEG_DOUBLET, QUDA_TWIST_INVALID, QUDA_TWIST_NONDEG_DOUBLET, quda::CompositeColorSpinorFieldDescriptor::real_length, real_length, setTuningString(), quda::ColorSpinorParam::siteOrder, siteOrder, quda::LatticeFieldParam::siteSubset, siteSubset, quda::CompositeColorSpinorFieldDescriptor::stride, stride, quda::ColorSpinorParam::twistFlavor, twistFlavor, quda::CompositeColorSpinorFieldDescriptor::volume, volume, volumeCB, quda::LatticeFieldParam::x, and x.
Referenced by quda::cpuColorSpinorField::cpuColorSpinorField(), and quda::cudaColorSpinorField::cudaColorSpinorField().
setTuningString()
void quda::ColorSpinorField::setTuningString () protected virtual
Set the vol_string and aux_string for use in tuning.
Reimplemented from quda::LatticeField.
Definition at line 261 of file color_spinor_field.cpp.
References quda::TuneKey::aux_n, quda::LatticeField::aux_string, errorQuda, nColor, nDim, nSpin, quda::LatticeField::precision, QUDA_TWIST_INVALID, QUDA_TWIST_NO, stride, twistFlavor, quda::LatticeField::vol_string, volume, quda::TuneKey::volume_n, and x.
Referenced by create(), and reset().
SiteOrder()
QudaSiteOrder quda::ColorSpinorField::SiteOrder () const inline
Definition at line 482 of file color_spinor_field.h.
Referenced by quda::copyExtendedColorSpinor(), and quda::copyGenericColorSpinor().
SiteSubset()
QudaSiteSubset quda::ColorSpinorField::SiteSubset () const inline virtual
Returns
Field subset type
Reimplemented from quda::LatticeField.
Definition at line 481 of file color_spinor_field.h.
Referenced by quda::DslashCoarsePolicyTune::bytes(), quda::Dirac::checkFullSpinor(), quda::Dirac::checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracImprovedStaggered::checkParitySpinor(), quda::blas::copy_ns::copy(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), quda::cpuColorSpinorField::cpuColorSpinorField(), quda::cudaColorSpinorField::cudaColorSpinorField(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracCoarse::DslashXpay(), quda::DslashCoarsePolicyTune::flops(), invertQuda(), quda::DiracMobius::M(), quda::DiracCoarse::M(), quda::DiracCoarsePC::M(), quda::DiracCoarse::MdagM(), quda::MG::operator()(), quda::dslash::DslashBasic< Dslash >::operator()(), quda::dslash::DslashFusedExterior< Dslash >::operator()(), quda::DslashCoarseLaunch::operator()(), quda::dslash::DslashGDR< Dslash >::operator()(), quda::dslash::DslashFusedGDR< Dslash >::operator()(), quda::dslash::DslashGDRRecv< Dslash >::operator()(), quda::dslash::DslashFusedGDRRecv< Dslash >::operator()(), quda::PreconditionedSolver::operator()(), quda::dslash::DslashZeroCopyPack< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopyPack< Dslash >::operator()(), quda::dslash::DslashZeroCopyPackGDRRecv< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopyPackGDRRecv< Dslash >::operator()(), quda::dslash::DslashZeroCopy< Dslash >::operator()(), quda::dslash::DslashFusedZeroCopy< Dslash >::operator()(), quda::Transfer::P(), quda::Transfer::R(), and quda::shiftColorSpinorField().
Source()
virtual void quda::ColorSpinorField::Source (const QudaSourceType sourceType, const int st = 0, const int s = 0, const int c = 0) pure virtual
Implemented in quda::cpuColorSpinorField, and quda::cudaColorSpinorField.
Referenced by quda::MG::buildFreeVectors().
Stride()
int quda::ColorSpinorField::Stride () const inline
Definition at line 414 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::stride.
Referenced by quda::checkLength(), quda::Dirac::checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracImprovedStaggered::checkParitySpinor(), quda::checkSpinor(), and quda::colorspinor::QDPJITDiracOrder< Float, Ns, Nc >::QDPJITDiracOrder().
TwistFlavor()
QudaTwistFlavorType quda::ColorSpinorField::TwistFlavor () const inline
Definition at line 408 of file color_spinor_field.h.
Referenced by checkField(), quda::CloverArg< Float, nSpin, nColor, dynamic_clover_ >::CloverArg(), quda::DiracWilson::createCoarseOp(), quda::DiracClover::createCoarseOp(), quda::DiracCloverPC::createCoarseOp(), quda::DiracTwistedClover::createCoarseOp(), quda::DiracTwistedCloverPC::createCoarseOp(), quda::DiracCoarse::createCoarseOp(), quda::DiracCoarsePC::createCoarseOp(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::GammaArg< Float, nColor >::GammaArg(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracTwistedCloverPC::M(), quda::DiracTwistedMassPC::prepare(), quda::DiracTwistedCloverPC::prepare(), quda::DiracTwistedMassPC::reconstruct(), quda::DiracTwistedCloverPC::reconstruct(), and quda::MG::verify().
V() [1/2]
void* quda::ColorSpinorField::V () inline
Definition at line 424 of file color_spinor_field.h.
Referenced by quda::ApplyCovDev(), quda::ApplyDomainWall4D(), quda::ApplyDomainWall5D(), quda::ApplyImprovedStaggered(), quda::ApplyLaplace(), quda::ApplyNdegTwistedMass(), quda::ApplyNdegTwistedMassPreconditioned(), quda::ApplyStaggered(), quda::ApplyTwistedClover(), quda::ApplyTwistedCloverPreconditioned(), quda::ApplyTwistedMass(), quda::ApplyTwistedMassPreconditioned(), quda::ApplyWilson(), quda::ApplyWilsonClover(), quda::ApplyWilsonCloverPreconditioned(), quda::Dirac::checkSpinorAlias(), quda::blas::copy_ns::copy(), quda::copyExtendedColorSpinor(), quda::copyGenericColorSpinor(), covdevRef(), quda::cpuColorSpinorField::cpuColorSpinorField(), dslashCUDA(), dslashRef(), quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::FloatNOrder(), quda::genericCudaPrintVector(), invert_test(), quda::cudaColorSpinorField::loadSpinorField(), matdagmat(), quda::DslashCoarseLaunch::operator()(), quda::GMResDR::RestartVZH(), quda::cudaColorSpinorField::saveSpinorField(), staggered_dslash(), staggeredDslashRef(), and quda::wuppertalStep().
V() [2/2]
const void* quda::ColorSpinorField::V () const inline
Definition at line 425 of file color_spinor_field.h.
Volume()
int quda::ColorSpinorField::Volume () const inline
Definition at line 415 of file color_spinor_field.h.
References quda::CompositeColorSpinorFieldDescriptor::volume.
Referenced by quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::BlockOrthoArg(), quda::TwistedClover< Float, nDim, nColor, Arg >::bytes(), quda::WilsonClover< Float, nDim, nColor, Arg >::bytes(), quda::TwistedCloverPreconditioned< Float, nDim, nColor, Arg >::bytes(), quda::WilsonCloverPreconditioned< Float, nDim, nColor, Arg >::bytes(), quda::Staggered< Float, nDim, nColor, Arg >::bytes(), quda::Laplace< Float, nDim, nColor, Arg >::bytes(), quda::Dslash< Float >::bytes(), quda::Dirac::checkParitySpinor(), quda::DiracClover::checkParitySpinor(), quda::DiracTwistedClover::checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracImprovedStaggered::checkParitySpinor(), quda::DiracClover::Clover(), quda::DiracCloverPC::CloverInv(), quda::blas::copy_ns::copy(), quda::copyGenericColorSpinor(), quda::Transfer::createGeoMap(), quda::DiracWilson::Dslash(), quda::DiracCloverPC::Dslash(), quda::DiracDomainWall::Dslash(), quda::DiracTwistedMass::Dslash(), quda::DiracTwistedMassPC::Dslash(), quda::DiracTwistedCloverPC::Dslash(), quda::DiracStaggered::Dslash(), quda::DiracImprovedStaggered::Dslash(), quda::GaugeLaplace::Dslash(), quda::DiracDomainWall4D::Dslash4(), quda::DiracMobius::Dslash4(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash4Xpay(), quda::DiracMobius::Dslash4Xpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::GaugeCovDev::DslashCD(), dslashRef(), quda::DiracWilson::DslashXpay(), quda::DiracClover::DslashXpay(), quda::DiracCloverPC::DslashXpay(), quda::DiracDomainWall::DslashXpay(), quda::DiracTwistedMass::DslashXpay(), quda::DiracTwistedMassPC::DslashXpay(), quda::DiracTwistedClover::DslashXpay(), quda::DiracTwistedCloverPC::DslashXpay(), quda::DiracStaggered::DslashXpay(), quda::DiracImprovedStaggered::DslashXpay(), quda::GaugeLaplace::DslashXpay(), quda::extendedCopyColorSpinor(), quda::Dslash5< Float, nColor, Arg >::flops(), quda::DomainWall5D< Float, nDim, nColor, Arg >::flops(), quda::TwistedMass< Float, nDim, nColor, Arg >::flops(), quda::TwistedClover< Float, nDim, nColor, Arg >::flops(), quda::WilsonClover< Float, nDim, nColor, Arg >::flops(), quda::NdegTwistedMass< Float, nDim, nColor, Arg >::flops(), quda::Laplace< Float, nDim, nColor, Arg >::flops(), quda::WilsonCloverPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::TwistedCloverPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::TwistedMassPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::Staggered< Float, nDim, nColor, Arg >::flops(), quda::NdegTwistedMassPreconditioned< Float, nDim, nColor, Arg >::flops(), quda::Dslash< Float >::flops(), quda::DiracWilson::M(), quda::DiracClover::M(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), quda::DiracTwistedMass::M(), quda::DiracTwistedClover::M(), quda::DiracStaggered::M(), quda::DiracImprovedStaggered::M(), main(), quda::blas::mixed_blas(), quda::blas::mixed_reduce(), quda::shiftColorSpinorField(), quda::DiracTwistedMass::twistedApply(), quda::DiracTwistedClover::twistedCloverApply(), quda::blas::uni_blas(), quda::blas::uni_reduce(), and quda::MG::verify().
VolumeCB()
int quda::ColorSpinorField::VolumeCB () const inline
Definition at line 416 of file color_spinor_field.h.
References QUDA_PARITY_SITE_SUBSET, and quda::CompositeColorSpinorFieldDescriptor::volume.
Referenced by quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::apply(), quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::BlockOrthoArg(), quda::DomainWall5D< Float, nDim, nColor, Arg >::bytes(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::bytes(), quda::DiracCoarse::Clover(), quda::DiracCoarse::CloverInv(), quda::DiracCoarse::Dslash(), quda::DiracCoarsePC::Dslash(), quda::DiracCoarse::DslashXpay(), quda::DiracCoarsePC::DslashXpay(), quda::WuppertalSmearing< Float, Ns, Nc, Arg >::flops(), quda::DslashCoarsePolicyTune::flops(), quda::ImprovedStaggeredApply< Float, nColor, recon_l >::ImprovedStaggeredApply(), quda::LaplaceApply< Float, nColor, recon >::LaplaceApply(), quda::DiracCoarse::M(), quda::CopySpinor< FloatOut, FloatIn, Ns, Nc, OutOrder, InOrder >::minThreads(), quda::SpinorNoise< real, Ns, Nc, type, Arg >::minThreads(), quda::CopyColorSpinor< Ns, Arg >::minThreads(), quda::CopyColorSpinor< 4, Arg >::minThreads(), quda::Transfer::P(), quda::Transfer::R(), quda::StaggeredApply< Float, nColor, recon_u >::StaggeredApply(), quda::TwistedCloverApply< Float, nColor, recon >::TwistedCloverApply(), quda::TwistedCloverPreconditionedApply< Float, nColor, recon >::TwistedCloverPreconditionedApply(), quda::TwistedMassApply< Float, nColor, recon >::TwistedMassApply(), quda::TwistedMassPreconditionedApply< Float, nColor, recon >::TwistedMassPreconditionedApply(), quda::WilsonApply< Float, nColor, recon >::WilsonApply(), quda::WilsonCloverApply< Float, nColor, recon >::WilsonCloverApply(), and quda::WilsonCloverPreconditionedApply< Float, nColor, recon >::WilsonCloverPreconditionedApply().
X() [1/2]
const int* quda::ColorSpinorField::X () const inline
Definition at line 410 of file color_spinor_field.h.
Referenced by quda::Dslash5< Float, nColor, Arg >::bytes(), quda::calculateY(), quda::DiracDomainWall::checkDWF(), quda::Dirac::checkParitySpinor(), quda::DiracStaggered::checkParitySpinor(), quda::DiracImprovedStaggered::checkParitySpinor(), quda::ContractionArg< real >::ContractionArg(), createGhostZone(), quda::DiracCoarse::createY(), quda::DiracCoarse::createYhat(), quda::DomainWall4D< Float, nDim, nColor, Arg >::DomainWall4D(), quda::DomainWall5D< Float, nDim, nColor, Arg >::DomainWall5D(), quda::DiracDomainWall::Dslash(), quda::DiracMobius::Dslash4pre(), quda::DiracMobius::Dslash4preXpay(), quda::DiracDomainWall4D::Dslash5(), quda::DiracMobius::Dslash5(), quda::DiracDomainWall4DPC::Dslash5inv(), quda::DiracMobiusPC::Dslash5inv(), quda::DiracDomainWall4DPC::Dslash5invXpay(), quda::DiracMobiusPC::Dslash5invXpay(), quda::DiracDomainWall4D::Dslash5Xpay(), quda::DiracMobius::Dslash5Xpay(), quda::DslashArg< Float >::DslashArg(), quda::DslashCoarseArg< Float, yFloat, ghostFloat, coarseSpin, coarseColor, csOrder, gOrder >::DslashCoarseArg(), quda::DiracDomainWall::DslashXpay(), quda::extendedCopyColorSpinor(), quda::colorspinor::FieldOrderCB< Float, coarseSpin, coarseColor, 1, csOrder, Float, ghostFloat >::FieldOrderCB(), quda::Dslash5< Float, nColor, Arg >::flops(), quda::DomainWall5D< Float, nDim, nColor, Arg >::flops(), quda::DiracDomainWall::M(), quda::DiracDomainWall4D::M(), quda::DiracMobius::M(), matdagmat(), quda::PackGhostArg< Field >::PackGhostArg(), quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::PaddedSpaceSpinorColorOrder(), staggered_dslash(), and quda::WuppertalSmearingArg< Float, Ns, Nc, gRecon >::WuppertalSmearingArg().
X() [2/2]
int quda::ColorSpinorField::X (int d) const inline
Definition at line 411 of file color_spinor_field.h.
Friends And Related Function Documentation
ColorSpinorParam
friend class ColorSpinorParam friend
Definition at line 571 of file color_spinor_field.h.
operator<<
std::ostream& operator<< (std::ostream & out, const ColorSpinorField & a) friend
Definition at line 860 of file color_spinor_field.cpp.
Member Data Documentation
bytes
size_t quda::ColorSpinorField::bytes protected
Definition at line 362 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::backup(), quda::cpuColorSpinorField::backup(), quda::cpuColorSpinorField::copy(), quda::cpuColorSpinorField::cpuColorSpinorField(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::cudaColorSpinorField(), exchange(), quda::cudaColorSpinorField::loadSpinorField(), quda::operator<<(), reset(), quda::cudaColorSpinorField::restore(), quda::cpuColorSpinorField::restore(), quda::cudaColorSpinorField::saveSpinorField(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), quda::cudaColorSpinorField::zero(), quda::cpuColorSpinorField::zero(), and quda::cudaColorSpinorField::zeroPad().
components
CompositeColorSpinorField quda::ColorSpinorField::components protected
Definition at line 377 of file color_spinor_field.h.
Referenced by Component(), quda::cudaColorSpinorField::Component(), quda::cudaColorSpinorField::create(), and quda::cudaColorSpinorField::destroy().
composite_descr
CompositeColorSpinorFieldDescriptor quda::ColorSpinorField::composite_descr protected
used for deflation eigenvector sets etc.:
Definition at line 375 of file color_spinor_field.h.
Referenced by create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::cudaColorSpinorField(), quda::cudaColorSpinorField::destroy(), fill(), quda::operator<<(), operator=(), reset(), and quda::cudaColorSpinorField::zeroPad().
dslash_constant
DslashConstant quda::ColorSpinorField::dslash_constant mutable protected
Definition at line 360 of file color_spinor_field.h.
Referenced by createGhostZone().
even
ColorSpinorField* quda::ColorSpinorField::even protected
Definition at line 371 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::destroy(), quda::cpuColorSpinorField::destroy(), and Even().
fieldOrder
QudaFieldOrder quda::ColorSpinorField::fieldOrder protected
Definition at line 367 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cpuColorSpinorField::copy(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cpuColorSpinorField::destroy(), Even(), fill(), isNative(), Odd(), quda::operator<<(), operator=(), reset(), quda::cpuColorSpinorField::zero(), and quda::cudaColorSpinorField::zeroPad().
gammaBasis
QudaGammaBasis quda::ColorSpinorField::gammaBasis protected
Definition at line 368 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), fill(), quda::operator<<(), operator=(), and reset().
ghost
void* quda::ColorSpinorField::ghost[2][QUDA_MAX_DIM] protected
Definition at line 352 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::createComms(), and Ghost().
ghost_buf
void* quda::ColorSpinorField::ghost_buf[2 *QUDA_MAX_DIM] mutable protected
Definition at line 358 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cudaColorSpinorField::exchangeGhost(), quda::cpuColorSpinorField::exchangeGhost(), and Ghost().
ghost_precision_allocated
QudaPrecision quda::ColorSpinorField::ghost_precision_allocated mutable protected
Used to keep local track of allocated ghost_precision in createGhostZone
Definition at line 323 of file color_spinor_field.h.
Referenced by createGhostZone().
ghostFace
int quda::ColorSpinorField::ghostFace[QUDA_MAX_DIM] mutable protected
Definition at line 355 of file color_spinor_field.h.
Referenced by createGhostZone().
ghostFaceCB
int quda::ColorSpinorField::ghostFaceCB[QUDA_MAX_DIM] mutable protected
Definition at line 356 of file color_spinor_field.h.
Referenced by createGhostZone(), quda::cudaColorSpinorField::sendGhost(), and quda::cudaColorSpinorField::sendStart().
ghostNorm
void* quda::ColorSpinorField::ghostNorm[2][QUDA_MAX_DIM] protected
Definition at line 353 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::createComms(), and GhostNorm().
init
bool quda::ColorSpinorField::init protected
Definition at line 320 of file color_spinor_field.h.
Referenced by create(), destroy(), quda::cudaColorSpinorField::operator=(), quda::cpuColorSpinorField::operator=(), and reset().
length
size_t quda::ColorSpinorField::length protected
Definition at line 342 of file color_spinor_field.h.
Referenced by create(), quda::cpuColorSpinorField::create(), quda::operator<<(), reset(), and quda::cudaColorSpinorField::zeroPad().
nColor
int quda::ColorSpinorField::nColor protected
Definition at line 325 of file color_spinor_field.h.
Referenced by quda::cpuColorSpinorField::allocateGhostBuffer(), ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), createGhostZone(), exchange(), fill(), isNative(), quda::operator<<(), operator=(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), setTuningString(), and quda::cudaColorSpinorField::zeroPad().
nDim
int quda::ColorSpinorField::nDim protected
Definition at line 329 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cpuColorSpinorField::copy(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), CreateCoarse(), CreateFine(), createGhostZone(), quda::cpuColorSpinorField::destroy(), fill(), LatticeIndex(), OffsetIndex(), quda::operator<<(), operator=(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), setTuningString(), and quda::cpuColorSpinorField::zero().
norm
void* quda::ColorSpinorField::norm protected
Definition at line 345 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::backup(), quda::cpuColorSpinorField::backup(), quda::cudaColorSpinorField::CopySubset(), quda::cpuColorSpinorField::cpuColorSpinorField(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::cudaColorSpinorField(), quda::cudaColorSpinorField::destroy(), quda::cudaColorSpinorField::loadSpinorField(), quda::operator<<(), quda::cpuColorSpinorField::restore(), quda::cudaColorSpinorField::saveSpinorField(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), quda::cudaColorSpinorField::zero(), and quda::cudaColorSpinorField::zeroPad().
norm_bytes
size_t quda::ColorSpinorField::norm_bytes protected
Definition at line 363 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::backup(), quda::cpuColorSpinorField::backup(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::cudaColorSpinorField(), quda::cudaColorSpinorField::loadSpinorField(), quda::operator<<(), reset(), quda::cudaColorSpinorField::restore(), quda::cpuColorSpinorField::restore(), quda::cudaColorSpinorField::saveSpinorField(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), quda::cudaColorSpinorField::zero(), and quda::cudaColorSpinorField::zeroPad().
norm_h
void* quda::ColorSpinorField::norm_h protected
Definition at line 348 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::create(), and quda::cudaColorSpinorField::destroy().
nSpin
int quda::ColorSpinorField::nSpin protected
Definition at line 326 of file color_spinor_field.h.
Referenced by quda::cpuColorSpinorField::allocateGhostBuffer(), ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), CreateCoarse(), CreateFine(), createGhostZone(), exchange(), fill(), isNative(), quda::operator<<(), operator=(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), setTuningString(), and quda::cudaColorSpinorField::zeroPad().
nVec
int quda::ColorSpinorField::nVec protected
Definition at line 327 of file color_spinor_field.h.
Referenced by ColorSpinorField(), create(), quda::cudaColorSpinorField::create(), fill(), operator=(), and reset().
odd
ColorSpinorField* quda::ColorSpinorField::odd protected
Definition at line 372 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::destroy(), quda::cpuColorSpinorField::destroy(), and Odd().
pad
int quda::ColorSpinorField::pad protected
Definition at line 334 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cpuColorSpinorField::create(), fill(), quda::operator<<(), operator=(), and reset().
pc_type
QudaPCType quda::ColorSpinorField::pc_type protected
Definition at line 339 of file color_spinor_field.h.
Referenced by ColorSpinorField(), create(), fill(), quda::operator<<(), operator=(), and reset().
real_length
size_t quda::ColorSpinorField::real_length protected
Definition at line 341 of file color_spinor_field.h.
Referenced by create(), quda::operator<<(), and reset().
siteOrder
QudaSiteOrder quda::ColorSpinorField::siteOrder protected
Definition at line 366 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cudaColorSpinorField::create(), fill(), quda::operator<<(), operator=(), and reset().
siteSubset
QudaSiteSubset quda::ColorSpinorField::siteSubset protected
Definition at line 365 of file color_spinor_field.h.
Referenced by quda::cpuColorSpinorField::allocateGhostBuffer(), ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), createGhostZone(), quda::cudaColorSpinorField::destroy(), quda::cpuColorSpinorField::destroy(), Even(), exchange(), fill(), Ghost(), GhostNorm(), LatticeIndex(), Odd(), OffsetIndex(), quda::operator<<(), operator=(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), quda::cpuColorSpinorField::unpackGhost(), and quda::cudaColorSpinorField::zeroPad().
stride
int quda::ColorSpinorField::stride protected
Definition at line 335 of file color_spinor_field.h.
Referenced by create(), quda::operator<<(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), setTuningString(), and quda::cudaColorSpinorField::zeroPad().
twistFlavor
QudaTwistFlavorType quda::ColorSpinorField::twistFlavor protected
Definition at line 337 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cudaColorSpinorField::CopySubset(), create(), fill(), quda::operator<<(), operator=(), reset(), and setTuningString().
v
void* quda::ColorSpinorField::v protected
Definition at line 344 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::backup(), quda::cpuColorSpinorField::backup(), quda::cpuColorSpinorField::copy(), quda::cudaColorSpinorField::CopySubset(), quda::cpuColorSpinorField::cpuColorSpinorField(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), quda::cudaColorSpinorField::cudaColorSpinorField(), quda::cudaColorSpinorField::destroy(), quda::cpuColorSpinorField::destroy(), quda::cudaColorSpinorField::loadSpinorField(), quda::operator<<(), quda::cudaColorSpinorField::restore(), quda::cpuColorSpinorField::restore(), quda::cudaColorSpinorField::saveSpinorField(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), quda::cudaColorSpinorField::zero(), quda::cpuColorSpinorField::zero(), and quda::cudaColorSpinorField::zeroPad().
v_h
void* quda::ColorSpinorField::v_h protected
Definition at line 347 of file color_spinor_field.h.
Referenced by quda::cudaColorSpinorField::create(), and quda::cudaColorSpinorField::destroy().
volume
int quda::ColorSpinorField::volume protected
Definition at line 332 of file color_spinor_field.h.
Referenced by create(), quda::operator<<(), reset(), and setTuningString().
volumeCB
int quda::ColorSpinorField::volumeCB protected
Definition at line 333 of file color_spinor_field.h.
Referenced by create(), createGhostZone(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), and quda::cudaColorSpinorField::zeroPad().
x
int quda::ColorSpinorField::x[QUDA_MAX_DIM] protected
Definition at line 330 of file color_spinor_field.h.
Referenced by ColorSpinorField(), quda::cpuColorSpinorField::copy(), quda::cudaColorSpinorField::CopySubset(), create(), quda::cudaColorSpinorField::create(), quda::cpuColorSpinorField::create(), CreateCoarse(), CreateFine(), createGhostZone(), quda::cpuColorSpinorField::destroy(), fill(), LatticeIndex(), OffsetIndex(), quda::blas::doubleCG3UpdateNorm_< ReduceType, Float2, FloatN >::operator()(), quda::operator<<(), operator=(), reset(), quda::cudaColorSpinorField::sendGhost(), quda::cudaColorSpinorField::sendStart(), setTuningString(), and quda::cpuColorSpinorField::zero().
The documentation for this class was generated from the following files:
include/color_spinor_field.h
lib/color_spinor_field.cpp