QUDA: quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg > Class Template Reference
quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg > Class Template Reference
Public Member Functions
GenericPackGhostLauncher (Arg &arg, const ColorSpinorField &meta, MemoryLocation *destination)
virtual ~GenericPackGhostLauncher ()
void apply (const cudaStream_t &stream)
void setColorSpinBlock (TuneParam &param) const
bool advanceBlockDim (TuneParam &param) const
int blockStep () const
int blockMin () const
bool advanceAux (TuneParam &param) const
TuneKey tuneKey () const
virtual void initTuneParam (TuneParam &param) const
virtual void defaultTuneParam (TuneParam &param) const
long long flops () const
long long bytes () const
Public Member Functions inherited from quda::TunableVectorYZ
TunableVectorYZ (unsigned int vector_length_y, unsigned int vector_length_z)
void resizeVector (int y, int z) const
void resizeStep (int y, int z) const
Public Member Functions inherited from quda::TunableVectorY
TunableVectorY (unsigned int vector_length_y)
void resizeVector (int y) const
void resizeStep (int y) const
Public Member Functions inherited from quda::Tunable
Tunable ()
virtual ~Tunable ()
virtual void preTune ()
virtual void postTune ()
virtual int tuningIter () const
virtual std::string paramString (const TuneParam &param) const
virtual std::string perfString (float time) const
virtual bool advanceTuneParam (TuneParam &param) const
void checkLaunchParam (TuneParam &param)
CUresult jitifyError () const
CUresult & jitifyError ()
Private Member Functions
unsigned int minThreads () const
bool tuneGridDim () const
bool tuneAuxDim () const
Private Attributes
Arg & arg
const ColorSpinorField & meta
Additional Inherited Members
Protected Member Functions inherited from quda::TunableVectorY
virtual unsigned int sharedBytesPerThread () const
virtual unsigned int sharedBytesPerBlock (const TuneParam &param) const
Protected Member Functions inherited from quda::Tunable
virtual bool tuneSharedBytes () const
virtual bool advanceGridDim (TuneParam &param) const
virtual unsigned int maxBlockSize (const TuneParam &param) const
virtual unsigned int maxGridSize () const
virtual unsigned int minGridSize () const
virtual int gridStep () const
gridStep sets the step size when iterating the grid size in advanceGridDim.
virtual void resetBlockDim (TuneParam &param) const
unsigned int maxBlocksPerSM () const
For some reason this can't be queried from the device properties, so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability)
template<typename F >
void setMaxDynamicSharedBytesPerBlock (F *func) const
Enable the maximum dynamic shared bytes for the kernel "func" (values given by maxDynamicSharedBytesPerBlock()).
unsigned int maxDynamicSharedBytesPerBlock () const
This can't be correctly queried in CUDA for all architectures so here we set set this. Based on Table 14 of the CUDA Programming Guide 10.0 (Technical Specifications per Compute Capability).
virtual unsigned int maxSharedBytesPerBlock () const
The maximum shared memory that a CUDA thread block can use in the autotuner. This isn't necessarily the same as maxDynamicSharedMemoryPerBlock since that may need explicit opt in to enable (by calling setMaxDynamicSharedBytes for the kernel in question). If the CUDA kernel in question does this opt in then this function can be overloaded to return maxDynamicSharedBytesPerBlock.
virtual bool advanceSharedBytes (TuneParam &param) const
int writeAuxString (const char *format,...)
Protected Attributes inherited from quda::TunableVectorY
unsigned int vector_length_y
unsigned int step_y
bool tune_block_x
Protected Attributes inherited from quda::Tunable
char aux [TuneKey::aux_n]
CUresult jitify_error
Detailed Description
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg>
class quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >
Definition at line 46 of file color_spinor_pack.cu.
Constructor & Destructor Documentation
GenericPackGhostLauncher()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::GenericPackGhostLauncher (Arg & arg, const ColorSpinorField & meta, MemoryLocation * destination) inline
Definition at line 54 of file color_spinor_pack.cu.
References quda::Tunable::aux, quda::LatticeField::AuxString(), comm_dim_partitioned(), comm_dim_partitioned_string(), comm_dim_topology_string(), quda::compile_type_str(), quda::Device, quda::Host, quda::LatticeField::Location(), and QUDA_CUDA_FIELD_LOCATION.
~GenericPackGhostLauncher()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> virtual quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::~GenericPackGhostLauncher () inline virtual
Definition at line 83 of file color_spinor_pack.cu.
Member Function Documentation
advanceAux()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> bool quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceAux (TuneParam & param) const inline virtual
Reimplemented from quda::Tunable.
Definition at line 137 of file color_spinor_pack.cu.
References quda::TuneParam::aux, quda::TunableVectorYZ::initTuneParam(), quda::Arg< real, Ns, Nc, order >::nParity, quda::TunableVectorYZ::resizeVector(), and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::setColorSpinBlock().
advanceBlockDim()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> bool quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceBlockDim (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorYZ.
Definition at line 124 of file color_spinor_pack.cu.
References quda::Tunable::advanceBlockDim(), quda::TunableVectorYZ::advanceBlockDim(), and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::setColorSpinBlock().
apply()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> void quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::apply (const cudaStream_t & stream) inline virtual
Implements quda::Tunable.
Definition at line 85 of file color_spinor_pack.cu.
References quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::arg, quda::TuneParam::aux, quda::TuneParam::block, getTuning(), getVerbosity(), quda::TuneParam::grid, quda::Tunable::jitify_error, quda::LatticeField::Location(), quda::Arg< real, Ns, Nc, order >::nParity, QUDA_CPU_FIELD_LOCATION, quda::TuneParam::shared_bytes, and quda::tuneLaunch().
Referenced by quda::genericPackGhost().
blockMin()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> int quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::blockMin () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 135 of file color_spinor_pack.cu.
References quda::Tunable::blockMin().
blockStep()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> int quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::blockStep () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 134 of file color_spinor_pack.cu.
References quda::Tunable::blockStep().
bytes()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> long long quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::bytes () const inline virtual
Reimplemented from quda::Tunable.
Definition at line 169 of file color_spinor_pack.cu.
References comm_dim_partitioned(), quda::LatticeField::GhostPrecision(), quda::LatticeField::Precision(), and quda::LatticeField::SurfaceCB().
defaultTuneParam()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> virtual void quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::defaultTuneParam (TuneParam & param) const inline virtual
sets default values for when tuning is disabled
Reimplemented from quda::TunableVectorYZ.
Definition at line 162 of file color_spinor_pack.cu.
References quda::TuneParam::aux, quda::TunableVectorYZ::defaultTuneParam(), and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::setColorSpinBlock().
flops()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> long long quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::flops () const inline virtual
Implements quda::Tunable.
Definition at line 168 of file color_spinor_pack.cu.
initTuneParam()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> virtual void quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::initTuneParam (TuneParam & param) const inline virtual
Reimplemented from quda::TunableVectorYZ.
Definition at line 156 of file color_spinor_pack.cu.
References quda::TuneParam::aux, quda::TunableVectorYZ::initTuneParam(), and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::setColorSpinBlock().
minThreads()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> unsigned int quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::minThreads () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 49 of file color_spinor_pack.cu.
References quda::Arg< real, Ns, Nc, order >::volumeCB.
setColorSpinBlock()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> void quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::setColorSpinBlock (TuneParam & param) const inline
Definition at line 117 of file color_spinor_pack.cu.
References quda::TuneParam::aux, quda::TuneParam::block, quda::TuneParam::grid, and quda::Arg< real, Ns, Nc, order >::nParity.
Referenced by quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceAux(), quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::advanceBlockDim(), quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::defaultTuneParam(), and quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::initTuneParam().
tuneAuxDim()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> bool quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::tuneAuxDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 51 of file color_spinor_pack.cu.
tuneGridDim()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> bool quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::tuneGridDim () const inline private virtual
Reimplemented from quda::Tunable.
Definition at line 50 of file color_spinor_pack.cu.
tuneKey()
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> TuneKey quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::tuneKey () const inline virtual
Implements quda::Tunable.
Definition at line 152 of file color_spinor_pack.cu.
References quda::Tunable::aux, and quda::LatticeField::VolString().
Member Data Documentation
arg
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> Arg& quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::arg private
Definition at line 47 of file color_spinor_pack.cu.
Referenced by quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::apply(), and quda::genericPackGhost().
meta
template<typename Float, bool block_float, int Ns, int Ms, int Nc, int Mc, typename Arg> const ColorSpinorField& quda::GenericPackGhostLauncher< Float, block_float, Ns, Ms, Nc, Mc, Arg >::meta private
Definition at line 48 of file color_spinor_pack.cu.
The documentation for this class was generated from the following file:
lib/color_spinor_pack.cu