QUDA: quda::PreconCG Class Reference
quda::PreconCG Class Reference
#include <invert_quda.h>
Public Member Functions
PreconCG (DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, SolverParam &param, TimeProfile &profile)
virtual ~PreconCG ()
void operator() (ColorSpinorField &out, ColorSpinorField &in)
Public Member Functions inherited from quda::Solver
Solver (SolverParam &param, TimeProfile &profile)
virtual ~Solver ()
virtual void blocksolve (ColorSpinorField &out, ColorSpinorField &in)
bool convergence (double r2, double hq2, double r2_tol, double hq_tol)
bool convergenceHQ (double r2, double hq2, double r2_tol, double hq_tol)
Test for HQ solver convergence – ignore L2 residual.
bool convergenceL2 (double r2, double hq2, double r2_tol, double hq_tol)
Test for L2 solver convergence – ignore HQ residual.
void PrintStats (const char *name, int k, double r2, double b2, double hq2)
Prints out the running statistics of the solver (requires a verbosity of QUDA_VERBOSE)
void PrintSummary (const char *name, int k, double r2, double b2, double r2_tol, double hq_tol)
Prints out the summary of the solver convergence (requires a verbosity of QUDA_SUMMARIZE). Assumes SolverParam.true_res and SolverParam.true_res_hq has been set.
void constructDeflationSpace (const ColorSpinorField &meta, const DiracMatrix &mat, bool svd)
Constructs the deflation space.
virtual double flops () const
Private Attributes
const DiracMatrix & mat
const DiracMatrix & matSloppy
const DiracMatrix & matPrecon
Solver * K
SolverParam Kparam
Additional Inherited Members
Static Public Member Functions inherited from quda::Solver
static Solver * create (SolverParam &param, DiracMatrix &mat, DiracMatrix &matSloppy, DiracMatrix &matPrecon, TimeProfile &profile)
static double stopping (double tol, double b2, QudaResidualType residual_type)
Set the solver L2 stopping condition.
Public Attributes inherited from quda::Solver
EigenSolver * eig_solve
bool deflate_init = false
std::vector< ColorSpinorField * > defl_tmp1
std::vector< ColorSpinorField * > defl_tmp2
Protected Attributes inherited from quda::Solver
SolverParam & param
TimeProfile & profile
int node_parity
Detailed Description
Definition at line 689 of file invert_quda.h.
Constructor & Destructor Documentation
PreconCG()
quda::PreconCG::PreconCG (DiracMatrix & mat, DiracMatrix & matSloppy, DiracMatrix & matPrecon, SolverParam & param, TimeProfile & profile)
Definition at line 39 of file inv_pcg_quda.cpp.
References errorQuda, quda::fillInnerSolverParam(), quda::SolverParam::inv_type_precondition, K, Kparam, QUDA_CG_INVERTER, QUDA_INVALID_INVERTER, QUDA_MR_INVERTER, and QUDA_SD_INVERTER.
~PreconCG()
quda::PreconCG::~PreconCG () virtual
Definition at line 56 of file inv_pcg_quda.cpp.
References K, quda::Solver::profile, and quda::QUDA_PROFILE_FREE.
Member Function Documentation
operator()()
void quda::PreconCG::operator() (ColorSpinorField & out, ColorSpinorField & in) virtual
Implements quda::Solver.
Definition at line 65 of file inv_pcg_quda.cpp.
References quda::axpy(), quda::blas::axpyCGNorm(), quda::blas::axpyZpbx(), commGlobalReductionSet(), quda::Solver::convergence(), quda::copy(), quda::ColorSpinorParam::create, csParam, quda::SolverParam::delta, quda::blas::flops, quda::DiracMatrix::flops(), getVerbosity(), quda::SolverParam::gflops, quda::blas::HeavyQuarkResidualNorm(), quda::SolverParam::iter, K, quda::TimeProfile::Last(), mat, matPrecon, matSloppy, quda::SolverParam::max_res_increase, quda::SolverParam::max_res_increase_total, quda::SolverParam::maxiter, quda::norm2(), quda::Solver::param, quda::LatticeField::Precision(), quda::SolverParam::precision_precondition, quda::SolverParam::precision_sloppy, printfQuda, quda::Solver::PrintStats(), quda::Solver::profile, QUDA_COPY_FIELD_CREATE, QUDA_HEAVY_QUARK_RESIDUAL, quda::QUDA_PROFILE_COMPUTE, quda::QUDA_PROFILE_EPILOGUE, quda::QUDA_PROFILE_FREE, quda::QUDA_PROFILE_INIT, quda::QUDA_PROFILE_PREAMBLE, QUDA_REFERENCE_FIELD_CREATE, QUDA_VERBOSE, QUDA_ZERO_FIELD_CREATE, quda::blas::reDotProduct(), quda::SolverParam::residual_type, quda::SolverParam::secs, quda::ColorSpinorParam::setPrecision(), quda::sqrt(), quda::Solver::stopping(), quda::SolverParam::tol, quda::SolverParam::tol_hq, quda::SolverParam::true_res, quda::SolverParam::true_res_hq, updateR(), quda::SolverParam::use_sloppy_partial_accumulator, warningQuda, quda::blas::xmyNorm(), quda::blas::xpay(), quda::blas::xpy(), and quda::zero().
Member Data Documentation
K
Solver* quda::PreconCG::K private
Definition at line 695 of file invert_quda.h.
Referenced by operator()(), PreconCG(), and ~PreconCG().
Kparam
SolverParam quda::PreconCG::Kparam private
Definition at line 696 of file invert_quda.h.
Referenced by PreconCG().
mat
const DiracMatrix& quda::PreconCG::mat private
Definition at line 691 of file invert_quda.h.
Referenced by operator()().
matPrecon
const DiracMatrix& quda::PreconCG::matPrecon private
Definition at line 693 of file invert_quda.h.
Referenced by operator()().
matSloppy
const DiracMatrix& quda::PreconCG::matSloppy private
Definition at line 692 of file invert_quda.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
include/invert_quda.h
lib/inv_pcg_quda.cpp