QUDA: quda::DiracDagger Class Reference
quda::DiracDagger Class Reference
#include <dirac_quda.h>
Public Member Functions
DiracDagger (const DiracMatrix &mat)
DiracDagger (const DiracMatrix *mat)
void operator() (ColorSpinorField &out, const ColorSpinorField &in) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &tmp) const
void operator() (ColorSpinorField &out, const ColorSpinorField &in, ColorSpinorField &Tmp1, ColorSpinorField &Tmp2) const
int getStencilSteps () const
Public Member Functions inherited from quda::DiracMatrix
DiracMatrix (const Dirac &d)
DiracMatrix (const Dirac *d)
DiracMatrix (const DiracMatrix &mat)
DiracMatrix (const DiracMatrix *mat)
virtual ~DiracMatrix ()
unsigned long long flops () const
QudaMatPCType getMatPCType () const
std::string Type () const
bool isStaggered () const
const Dirac * Expose () const
Protected Attributes
const DiracMatrix & mat
Protected Attributes inherited from quda::DiracMatrix
const Dirac * dirac
Additional Inherited Members
Public Attributes inherited from quda::DiracMatrix
double shift
Shift term added onto operator (M/M^dag M/M M^dag + shift)
Detailed Description
Definition at line 1295 of file dirac_quda.h.
Constructor & Destructor Documentation
DiracDagger() [1/2]
quda::DiracDagger::DiracDagger (const DiracMatrix & mat) inline
Definition at line 1301 of file dirac_quda.h.
DiracDagger() [2/2]
quda::DiracDagger::DiracDagger (const DiracMatrix * mat) inline
Definition at line 1302 of file dirac_quda.h.
Member Function Documentation
getStencilSteps()
int quda::DiracDagger::getStencilSteps () const inline virtual
Implements quda::DiracMatrix.
Definition at line 1326 of file dirac_quda.h.
References quda::DiracMatrix::getStencilSteps().
operator()() [1/3]
void quda::DiracDagger::operator() (ColorSpinorField & out, const ColorSpinorField & in) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1304 of file dirac_quda.h.
References quda::DiracParam::dirac, quda::Dirac::flipDagger(), and mat().
operator()() [2/3]
void quda::DiracDagger::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & tmp) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1311 of file dirac_quda.h.
References quda::DiracParam::dirac, quda::Dirac::flipDagger(), and mat().
operator()() [3/3]
void quda::DiracDagger::operator() (ColorSpinorField & out, const ColorSpinorField & in, ColorSpinorField & Tmp1, ColorSpinorField & Tmp2) const inline virtual
Implements quda::DiracMatrix.
Definition at line 1318 of file dirac_quda.h.
References quda::DiracParam::dirac, quda::Dirac::flipDagger(), and mat().
Member Data Documentation
mat
const DiracMatrix& quda::DiracDagger::mat protected
Definition at line 1298 of file dirac_quda.h.
The documentation for this class was generated from the following file:
include/dirac_quda.h