QUDA: tests/contract_test.cpp File Reference
contract_test.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <util_quda.h>
#include <test_util.h>
#include <dslash_util.h>
#include <contract_reference.h>
#include "misc.h"
#include <gtest/gtest.h>
#include <quda.h>
#include <color_spinor_field.h>
Classes
class ContractionTest
Namespaces
quda
Functions
void usage (char **)
void quda::setTransferGPU (bool)
void display_test_info ()
void setInvertParam (QudaInvertParam &inv_param)
int main (int argc, char **argv)
void test (int contractionType, int Prec)
TEST_P (ContractionTest, verify)
std::string getContractName (testing::TestParamInfo<::testing::tuple< int, int >> param)
INSTANTIATE_TEST_SUITE_P (QUDA, ContractionTest, Combine(Range(0, 2), Range(0, NcontractType)), getContractName)
Variables
int device
int xdim
int ydim
int zdim
int tdim
int Lsdim
int gridsize_from_cmdline []
QudaPrecision prec
QudaPrecision prec_sloppy
QudaPrecision prec_precondition
QudaPrecision prec_null
QudaContractType contract_type
const int NcontractType = 2
bool verify_results
QudaPrecision & cpu_prec = prec
QudaPrecision & cuda_prec = prec
QudaPrecision & cuda_prec_sloppy = prec_sloppy
QudaPrecision & cuda_prec_precondition = prec_precondition
const char * prec_str [] = {"single", "double"}
const char * names [] = {"OpenSpin", "DegrandRossi"}
Function Documentation
display_test_info()
void display_test_info ()
Definition at line 52 of file contract_test.cpp.
References dimPartitioned(), get_prec_str(), Lsdim, prec, prec_sloppy, printfQuda, tdim, xdim, ydim, and zdim.
Referenced by main().
getContractName()
std::string getContractName (testing::TestParamInfo<::testing::tuple< int, int >> param)
Definition at line 252 of file contract_test.cpp.
References INSTANTIATE_TEST_SUITE_P(), names, NcontractType, param, prec, and prec_str.
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (QUDA , ContractionTest , Combine(Range(0, 2), Range(0, NcontractType)) , getContractName)
Referenced by getContractName().
main()
int main (int argc, char ** argv)
Definition at line 99 of file contract_test.cpp.
References comm_rank(), device, display_test_info(), endQuda(), finalizeComms(), gridsize_from_cmdline, initComms(), initQuda(), initRand(), prec, process_command_line_option(), QUDA_INVALID_PRECISION, setDims(), setSpinorSiteSize(), tdim, usage(), verify_results, warningQuda, X, xdim, ydim, and zdim.
setInvertParam()
void setInvertParam (QudaInvertParam & inv_param)
Definition at line 71 of file contract_test.cpp.
References QudaInvertParam_s::cl_pad, cpu_prec, QudaInvertParam_s::cpu_prec, cuda_prec, QudaInvertParam_s::cuda_prec, cuda_prec_precondition, QudaInvertParam_s::cuda_prec_precondition, cuda_prec_sloppy, QudaInvertParam_s::cuda_prec_sloppy, QudaInvertParam_s::dirac_order, QudaInvertParam_s::gamma_basis, QudaInvertParam_s::input_location, QudaInvertParam_s::Ls, QudaInvertParam_s::output_location, QudaInvertParam_s::preserve_source, QUDA_CPU_FIELD_LOCATION, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DIRAC_ORDER, QUDA_PRESERVE_SOURCE_NO, and QudaInvertParam_s::sp_pad.
Referenced by test().
test()
void test (int contractionType, int Prec)
Definition at line 154 of file contract_test.cpp.
References contraction_reference(), quda::contractQuda(), QudaInvertParam_s::cpu_prec, QudaInvertParam_s::cuda_prec, QudaInvertParam_s::cuda_prec_precondition, QudaInvertParam_s::cuda_prec_sloppy, errorQuda, get_contract_str(), inv_param, newQudaInvertParam(), printfQuda, QUDA_CONTRACT_TYPE_DR, QUDA_CONTRACT_TYPE_INVALID, QUDA_CONTRACT_TYPE_OPEN, QUDA_DOUBLE_PRECISION, QUDA_INVALID_PRECISION, QUDA_SINGLE_PRECISION, setInvertParam(), spinorSiteSize, tdim, V, X, xdim, ydim, and zdim.
Referenced by TEST_P().
TEST_P()
TEST_P (ContractionTest , verify)
Definition at line 244 of file contract_test.cpp.
References prec, and test().
usage()
void usage (char **)
Definition at line 1783 of file test_util.cpp.
Referenced by main().
Variable Documentation
contract_type
QudaContractType contract_type
Definition at line 1772 of file test_util.cpp.
Referenced by process_command_line_option().
cpu_prec
QudaPrecision& cpu_prec = prec
Definition at line 66 of file contract_test.cpp.
Referenced by main(), printQudaGaugeParam(), printQudaInvertParam(), read_field(), read_su3_field(), setInvertParam(), write_field(), and write_su3_field().
cuda_prec
QudaPrecision& cuda_prec = prec
Definition at line 67 of file contract_test.cpp.
Referenced by main(), printQudaGaugeParam(), printQudaInvertParam(), and setInvertParam().
cuda_prec_precondition
QudaPrecision& cuda_prec_precondition = prec_precondition
Definition at line 69 of file contract_test.cpp.
Referenced by main(), printQudaGaugeParam(), printQudaInvertParam(), and setInvertParam().
cuda_prec_sloppy
QudaPrecision& cuda_prec_sloppy = prec_sloppy
Definition at line 68 of file contract_test.cpp.
Referenced by main(), printQudaGaugeParam(), printQudaInvertParam(), and setInvertParam().
device
int device
Definition at line 1602 of file test_util.cpp.
Referenced by main().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 49 of file test_util.cpp.
Referenced by main().
Lsdim
int Lsdim
Definition at line 1619 of file test_util.cpp.
Referenced by display_test_info().
names
const char* names[] = {"OpenSpin", "DegrandRossi"}
Definition at line 97 of file contract_test.cpp.
Referenced by getContractName().
NcontractType
const int NcontractType = 2
Definition at line 41 of file contract_test.cpp.
Referenced by getContractName().
prec
QudaPrecision prec
Definition at line 1608 of file test_util.cpp.
Referenced by display_test_info(), getContractName(), main(), and TEST_P().
prec_null
QudaPrecision prec_null
Definition at line 1612 of file test_util.cpp.
prec_precondition
QudaPrecision prec_precondition
Definition at line 1611 of file test_util.cpp.
prec_sloppy
QudaPrecision prec_sloppy
Definition at line 1609 of file test_util.cpp.
Referenced by display_test_info().
prec_str
const char* prec_str[] = {"single", "double"}
Definition at line 93 of file contract_test.cpp.
Referenced by getContractName().
tdim
int tdim
Definition at line 1618 of file test_util.cpp.
Referenced by display_test_info(), main(), and test().
verify_results
bool verify_results
Definition at line 1643 of file test_util.cpp.
Referenced by main().
xdim
int xdim
Definition at line 1615 of file test_util.cpp.
Referenced by display_test_info(), main(), and test().
ydim
int ydim
Definition at line 1616 of file test_util.cpp.
Referenced by display_test_info(), main(), and test().
zdim
int zdim
Definition at line 1617 of file test_util.cpp.
Referenced by display_test_info(), main(), and test().