QUDA: tests/covdev_reference.h File Reference
covdev_reference.h File Reference
#include <blas_reference.h>
#include <quda_internal.h>
#include "color_spinor_field.h"
Functions
void setDims (int *)
void covdev_dslash (void *res, void **link, void *spinorField, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
void covdev_dslash_mg4dir (cpuColorSpinorField *out, void **link, void **ghostLink, cpuColorSpinorField *in, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
void mat (void *out, void **link, void *in, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
void matdagmat (void *out, void **link, void *in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, void *tmp, QudaParity parity)
void mat_mg4dir (cpuColorSpinorField *out, void **link, void **ghostLink, cpuColorSpinorField *in, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
void matdagmat_mg4dir (cpuColorSpinorField *out, void **link, void **ghostLink, cpuColorSpinorField *in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, cpuColorSpinorField *tmp, QudaParity parity)
Variables
int Z [4]
int Vh
int V
Function Documentation
covdev_dslash()
void covdev_dslash (void * res, void ** link, void * spinorField, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 78 of file covdev_reference.cpp.
References covdevReference(), and QUDA_DOUBLE_PRECISION.
covdev_dslash_mg4dir()
void covdev_dslash_mg4dir (cpuColorSpinorField * out, void ** link, void ** ghostLink, cpuColorSpinorField * in, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Referenced by matdagmat().
mat()
void mat (void * out, void ** link, void * in, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 112 of file covdev_reference.cpp.
References Mat(), and QUDA_DOUBLE_PRECISION.
Referenced by LoadStore< Real >::addMatrixToField(), quda::appendMatrixToArray(), conj(), covdevRef(), quda::MG::generateEigenVectors(), getRealBidiagMatrix(), quda::EigenSolver::matVec(), quda::DiracDagger::operator()(), operator*(), LoadStore< Real >::storeMatrixToField(), LoadStore< Real >::storeMatrixToMomentumField(), transpose(), and u_shift_mat().
mat_mg4dir()
void mat_mg4dir (cpuColorSpinorField * out, void ** link, void ** ghostLink, cpuColorSpinorField * in, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Referenced by covdevRef(), and matdagmat().
matdagmat()
void matdagmat (void * out, void ** link, void * in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, void * tmp, QudaParity parity)
Definition at line 163 of file covdev_reference.cpp.
References quda::cpuColorSpinorField::backGhostFaceBuffer, covdev_dslash_mg4dir(), errorQuda, quda::ColorSpinorField::Even(), quda::cpuColorSpinorField::exchangeGhost(), faceVolume, quda::cpuColorSpinorField::fwdGhostFaceBuffer, gaugeSiteSize, in, mat_mg4dir(), Matdagmat(), matdagmat_mg4dir(), mu, mySpinorSiteSize, quda::ColorSpinorField::Odd(), out, parity, QUDA_DOUBLE_PRECISION, QUDA_EVEN_PARITY, QUDA_INVALID_PARITY, QUDA_ODD_PARITY, quda::s, spinor, su3Mul(), su3Tmul(), sum(), tmp, quda::ColorSpinorField::V(), and Vh.
Referenced by invert_test(), and staggeredDslashRef().
matdagmat_mg4dir()
void matdagmat_mg4dir (cpuColorSpinorField * out, void ** link, void ** ghostLink, cpuColorSpinorField * in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, cpuColorSpinorField * tmp, QudaParity parity)
Referenced by invert_test(), and matdagmat().
setDims()
void setDims (int *)
Definition at line 151 of file test_util.cpp.
Referenced by eigensolve_test(), gauge_force_test(), hisq_force_init(), hisq_test(), init(), invert_test(), llfat_test(), main(), plaq_test(), GaugeAlgTest::SetUp(), SU3test(), and unitarize_link_test().
Variable Documentation
V
int V
Definition at line 27 of file test_util.cpp.
Vh
int Vh
Definition at line 28 of file test_util.cpp.
Z
int Z[4]
Definition at line 26 of file test_util.cpp.