QUDA: tests/covdev_reference.cpp File Reference
covdev_reference.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <test_util.h>
#include <quda_internal.h>
#include <quda.h>
#include <util_quda.h>
#include <covdev_reference.h>
#include "misc.h"
#include <blas_quda.h>
#include <blas_reference.h>
#include <dslash_util.h>
Functions
void * memset (void *s, int c, size_t n)
template<typename Float >
void display_link_internal (Float *link)
template<typename sFloat , typename gFloat >
void covdevReference (sFloat *res, gFloat **link, sFloat *spinorField, int oddBit, int daggerBit, int mu)
void covdev_dslash (void *res, void **link, void *spinorField, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
template<typename sFloat , typename gFloat >
void Mat (sFloat *out, gFloat **link, sFloat *in, int daggerBit, int mu)
void mat (void *out, void **link, void *in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
template<typename sFloat , typename gFloat >
void Matdagmat (sFloat *out, gFloat **link, sFloat *in, int daggerBit, int mu, sFloat *tmp, QudaParity parity)
void matdagmat (void *out, void **link, void *in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, void *tmp, QudaParity parity)
Function Documentation
covdev_dslash()
void covdev_dslash (void * res, void ** link, void * spinorField, int oddBit, int daggerBit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 78 of file covdev_reference.cpp.
References covdevReference(), and QUDA_DOUBLE_PRECISION.
covdevReference()
template<typename sFloat , typename gFloat > void covdevReference (sFloat * res, gFloat ** link, sFloat * spinorField, int oddBit, int daggerBit, int mu)
Definition at line 46 of file covdev_reference.cpp.
References gaugeLink(), gaugeSiteSize, mySpinorSiteSize, quda::s, spinor, spinorNeighbor(), su3Mul(), su3Tmul(), sum(), and Vh.
Referenced by covdev_dslash(), Mat(), and Matdagmat().
display_link_internal()
template<typename Float > void display_link_internal (Float * link)
Definition at line 30 of file covdev_reference.cpp.
Mat()
template<typename sFloat , typename gFloat > void Mat (sFloat * out, gFloat ** link, sFloat * in, int daggerBit, int mu)
Definition at line 99 of file covdev_reference.cpp.
References covdevReference(), in, mySpinorSiteSize, out, and Vh.
Referenced by quda::cloverInvertCompute(), quda::ComputeTMAVGPU(), quda::getDeterminant(), quda::getTrace(), magma_Xgeev(), magma_Xgels(), magma_Xgesv(), magma_Xheev(), mat(), quda::operator*(), quda::operator*=(), quda::operator+=(), quda::twistCloverApply(), and quda::twistedClover().
mat()
void mat (void * out, void ** link, void * in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision)
Definition at line 112 of file covdev_reference.cpp.
References Mat(), and QUDA_DOUBLE_PRECISION.
Referenced by LoadStore< Real >::addMatrixToField(), quda::appendMatrixToArray(), conj(), covdevRef(), quda::MG::generateEigenVectors(), getRealBidiagMatrix(), quda::EigenSolver::matVec(), quda::DiracDagger::operator()(), operator*(), LoadStore< Real >::storeMatrixToField(), LoadStore< Real >::storeMatrixToMomentumField(), transpose(), and u_shift_mat().
Matdagmat()
template<typename sFloat , typename gFloat > void Matdagmat (sFloat * out, gFloat ** link, sFloat * in, int daggerBit, int mu, sFloat * tmp, QudaParity parity)
Definition at line 134 of file covdev_reference.cpp.
References covdevReference(), in, out, QUDA_EVEN_PARITY, and QUDA_ODD_PARITY.
Referenced by matdagmat().
matdagmat()
void matdagmat (void * out, void ** link, void * in, int dagger_bit, int mu, QudaPrecision sPrecision, QudaPrecision gPrecision, void * tmp, QudaParity parity)
Definition at line 163 of file covdev_reference.cpp.
References quda::cpuColorSpinorField::backGhostFaceBuffer, covdev_dslash_mg4dir(), errorQuda, quda::ColorSpinorField::Even(), quda::cpuColorSpinorField::exchangeGhost(), faceVolume, quda::cpuColorSpinorField::fwdGhostFaceBuffer, gaugeSiteSize, in, mat_mg4dir(), Matdagmat(), matdagmat_mg4dir(), mu, mySpinorSiteSize, quda::ColorSpinorField::Odd(), out, parity, QUDA_DOUBLE_PRECISION, QUDA_EVEN_PARITY, QUDA_INVALID_PARITY, QUDA_ODD_PARITY, quda::s, spinor, su3Mul(), su3Tmul(), sum(), tmp, quda::ColorSpinorField::V(), and Vh.
Referenced by invert_test(), and staggeredDslashRef().
memset()
void* memset (void * s, int c, size_t n)
Referenced by compute_path_product(), quda::ComputeEta< libtype::magma_lib >(), computeFatLongGPUandCPU(), computeHISQLinksCPU(), computeHISQLinksGPU(), quda::cpuCloverField::cpuCloverField(), quda::cpuGaugeField::cpuGaugeField(), quda::cudaColorSpinorField::create(), quda::cudaCloverField::cudaCloverField(), eigensolve_test(), exchange_cpu_sitelink(), quda::GMResDR::FlexArnoldiProcedure(), gauge_force_reference_dir(), gauge_force_test(), hisq_test(), init(), quda::blas::initReduce(), invert_test(), link_sanity_check_internal_12(), link_sanity_check_internal_8(), llfat_compute_gen_staple_field(), llfat_reference(), llfat_test(), quda::cudaColorSpinorField::loadSpinorField(), main(), quda::mapped_malloc_(), quda::blas::multiReduce(), quda::pinned_malloc_(), quda::safe_malloc_(), site_link_sanity_check_internal_12(), quda::cpuGaugeField::zero(), quda::cpuColorSpinorField::zero(), and quda::cudaGaugeField::zeroPad().