QUDA: tests/domain_wall_dslash_reference.h File Reference
domain_wall_dslash_reference.h File Reference
#include <enum_quda.h>
#include <quda.h>
Functions
void dw_dslash (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm)
void dslash_4_4d (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm)
void dw_dslash_5_4d (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, bool zero_initialize)
void dslash_5_inv (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, double *kappa)
void mdw_dslash_5_inv (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, double _Complex *kappa)
void mdw_dslash_5 (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, double _Complex *kappa, bool zero_initialize)
void mdw_dslash_4_pre (void *res, void **gaugeFull, void *spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, double _Complex *b5, double _Complex *c5, bool zero_initialize)
void dw_mat (void *out, void **gauge, void *in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm)
void dw_4d_mat (void *out, void **gauge, void *in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm)
void mdw_mat (void *out, void **gauge, void *in, double _Complex *kappa_b, double _Complex *kappa_c, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm, double _Complex *b5, double _Complex *c5)
void dw_matdagmat (void *out, void **gauge, void *in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam &param, double mferm)
void dw_matpc (void *out, void **gauge, void *in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param, double mferm)
void dw_4d_matpc (void *out, void **gauge, void *in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param, double mferm)
void mdw_matpc (void *out, void **gauge, void *in, double _Complex *kappa_b, double _Complex *kappa_c, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam &gauge_param, double mferm, double _Complex *b5, double _Complex *c5)
Function Documentation
dslash_4_4d()
void dslash_4_4d (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm)
Definition at line 637 of file domain_wall_dslash_reference.cpp.
References quda::cpuColorSpinorField::backGhostFaceBuffer, quda::ColorSpinorParam::create, csParam, errorQuda, quda::cpuColorSpinorField::exchangeGhost(), quda::ColorSpinorParam::fieldOrder, quda::cpuColorSpinorField::fwdGhostFaceBuffer, quda::ColorSpinorParam::gammaBasis, quda::GaugeField::Ghost(), quda::LatticeFieldParam::ghostExchange, in, Ls, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::ColorSpinorParam::nSpin, quda::LatticeFieldParam::pad, quda::ColorSpinorParam::pc_type, QUDA_4D_PC, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DOUBLE_PRECISION, QUDA_EVEN_ODD_SITE_ORDER, QUDA_EVEN_PARITY, QUDA_GHOST_EXCHANGE_PAD, QUDA_INVALID_PARITY, QUDA_ODD_PARITY, QUDA_PARITY_SITE_SUBSET, QUDA_REFERENCE_FIELD_CREATE, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, quda::ColorSpinorParam::setPrecision(), quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::ColorSpinorParam::v, quda::LatticeFieldParam::x, and Z.
Referenced by dslashRef(), dw_4d_mat(), dw_4d_matpc(), mdw_mat(), and mdw_matpc().
dslash_5_inv()
void dslash_5_inv (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, double * kappa)
Definition at line 706 of file domain_wall_dslash_reference.cpp.
References dslashReference_5th_inv(), and QUDA_DOUBLE_PRECISION.
Referenced by dslashRef(), and dw_4d_matpc().
dw_4d_mat()
void dw_4d_mat (void * out, void ** gauge, void * in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm)
Definition at line 780 of file domain_wall_dslash_reference.cpp.
References dslash_4_4d(), dw_dslash_5_4d(), in, out, spinorSiteSize, V5, V5h, and quda::blas::xpay().
Referenced by dslashRef(), and main().
dw_4d_matpc()
void dw_4d_matpc (void * out, void ** gauge, void * in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param, double mferm)
Definition at line 865 of file domain_wall_dslash_reference.cpp.
References dslash_4_4d(), dslash_5_inv(), dw_dslash_5_4d(), kappa, kappa5, Ls, parity, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, spinorSiteSize, tmp, V5h, and quda::blas::xpay().
Referenced by dslashRef(), and main().
dw_dslash()
void dw_dslash (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm)
Definition at line 572 of file domain_wall_dslash_reference.cpp.
References quda::cpuColorSpinorField::backGhostFaceBuffer, quda::ColorSpinorParam::create, csParam, errorQuda, quda::cpuColorSpinorField::exchangeGhost(), quda::ColorSpinorParam::fieldOrder, quda::cpuColorSpinorField::fwdGhostFaceBuffer, quda::ColorSpinorParam::gammaBasis, quda::GaugeField::Ghost(), quda::LatticeFieldParam::ghostExchange, in, Ls, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::ColorSpinorParam::nSpin, quda::LatticeFieldParam::pad, quda::ColorSpinorParam::pc_type, QUDA_5D_PC, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DOUBLE_PRECISION, QUDA_EVEN_ODD_SITE_ORDER, QUDA_EVEN_PARITY, QUDA_GHOST_EXCHANGE_PAD, QUDA_INVALID_PARITY, QUDA_ODD_PARITY, QUDA_PARITY_SITE_SUBSET, QUDA_REFERENCE_FIELD_CREATE, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, quda::ColorSpinorParam::setPrecision(), quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::ColorSpinorParam::v, quda::LatticeFieldParam::x, and Z.
Referenced by dslashRef(), dw_mat(), and dw_matpc().
dw_dslash_5_4d()
void dw_dslash_5_4d (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, bool zero_initialize)
Definition at line 695 of file domain_wall_dslash_reference.cpp.
References in, and QUDA_DOUBLE_PRECISION.
Referenced by dslashRef(), dw_4d_mat(), and dw_4d_matpc().
dw_mat()
void dw_mat (void * out, void ** gauge, void * in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm)
Definition at line 766 of file domain_wall_dslash_reference.cpp.
References dw_dslash(), in, out, spinorSiteSize, V5, V5h, and quda::blas::xpay().
Referenced by dslashRef(), dw_matdagmat(), and main().
dw_matdagmat()
void dw_matdagmat (void * out, void ** gauge, void * in, double kappa, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm)
Definition at line 834 of file domain_wall_dslash_reference.cpp.
References dw_mat(), spinorSiteSize, tmp, and V5.
Referenced by dslashRef().
dw_matpc()
void dw_matpc (void * out, void ** gauge, void * in, double kappa, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param, double mferm)
Definition at line 845 of file domain_wall_dslash_reference.cpp.
References dw_dslash(), kappa, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_EVEN_EVEN_ASYMMETRIC, spinorSiteSize, tmp, V5h, and quda::blas::xpay().
Referenced by dslashRef(), and main().
mdw_dslash_4_pre()
void mdw_dslash_4_pre (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, double _Complex * b5, double _Complex * c5, bool zero_initialize)
Definition at line 741 of file domain_wall_dslash_reference.cpp.
References axpby(), in, Ls, QUDA_DOUBLE_PRECISION, spinorSiteSize, and Vh.
Referenced by dslashRef(), mdw_mat(), and mdw_matpc().
mdw_dslash_5()
void mdw_dslash_5 (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, double _Complex * kappa, bool zero_initialize)
Definition at line 725 of file domain_wall_dslash_reference.cpp.
References cxpay(), in, Ls, QUDA_DOUBLE_PRECISION, spinorSiteSize, and Vh.
Referenced by dslashRef(), mdw_mat(), and mdw_matpc().
mdw_dslash_5_inv()
void mdw_dslash_5_inv (void * res, void ** gaugeFull, void * spinorField, int oddBit, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, double _Complex * kappa)
Definition at line 715 of file domain_wall_dslash_reference.cpp.
References mdslashReference_5th_inv(), and QUDA_DOUBLE_PRECISION.
Referenced by dslashRef(), and mdw_matpc().
mdw_mat()
void mdw_mat (void * out, void ** gauge, void * in, double _Complex * kappa_b, double _Complex * kappa_c, int dagger, QudaPrecision precision, QudaGaugeParam & param, double mferm, double _Complex * b5, double _Complex * c5)
Definition at line 797 of file domain_wall_dslash_reference.cpp.
References cxpay(), dslash_4_4d(), in, kappa5, Ls, mdw_dslash_4_pre(), mdw_dslash_5(), out, spinorSiteSize, tmp, V5h, and Vh.
Referenced by dslashRef(), and main().
mdw_matpc()
void mdw_matpc (void * out, void ** gauge, void * in, double _Complex * kappa_b, double _Complex * kappa_c, QudaMatPCType matpc_type, int dagger, QudaPrecision precision, QudaGaugeParam & gauge_param, double mferm, double _Complex * b5, double _Complex * c5)
Definition at line 906 of file domain_wall_dslash_reference.cpp.
References cxpay(), dslash_4_4d(), errorQuda, kappa5, Ls, mdw_dslash_4_pre(), mdw_dslash_5(), mdw_dslash_5_inv(), parity, QUDA_MATPC_EVEN_EVEN, QUDA_MATPC_ODD_ODD, QUDA_MATPC_ODD_ODD_ASYMMETRIC, spinorSiteSize, tmp, V5h, and Vh.
Referenced by dslashRef(), and main().