QUDA: tests/heatbath_test.cpp File Reference
heatbath_test.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <quda.h>
#include <quda_internal.h>
#include <gauge_field.h>
#include <comm_quda.h>
#include <test_util.h>
#include <gauge_tools.h>
#include "misc.h"
#include <pgauge_monte.h>
#include <random_quda.h>
#include <unitarization_links.h>
#include <qio_field.h>
Namespaces
quda
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
#define DABS(a) ((a)<(0.)?(-(a)):(a))
Functions
void usage (char **)
void quda::setTransferGPU (bool)
void display_test_info ()
void setGaugeParam (QudaGaugeParam &gauge_param)
void setReunitarizationConsts ()
void CallUnitarizeLinks (quda::cudaGaugeField *cudaInGauge)
int main (int argc, char **argv)
Variables
int device
int xdim
int ydim
int zdim
int tdim
int Lsdim
int gridsize_from_cmdline []
QudaReconstructType link_recon
QudaPrecision prec
QudaPrecision prec_sloppy
QudaReconstructType link_recon_sloppy
double anisotropy
char latfile []
char gauge_outfile []
double heatbath_beta_value
int heatbath_warmup_steps
int heatbath_num_steps
int heatbath_num_heatbath_per_step
int heatbath_num_overrelax_per_step
bool heatbath_coldstart
QudaPrecision & cpu_prec = prec
QudaPrecision & cuda_prec = prec
QudaPrecision & cuda_prec_sloppy = prec_sloppy
Macro Definition Documentation
DABS
#define DABS (a) ((a)<(0.)?(-(a)):(a))
Definition at line 29 of file heatbath_test.cpp.
MAX
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 28 of file heatbath_test.cpp.
Referenced by setGaugeParam().
Function Documentation
CallUnitarizeLinks()
void CallUnitarizeLinks (quda::cudaGaugeField * cudaInGauge)
Definition at line 137 of file heatbath_test.cpp.
References device_free, device_malloc, errorQuda, num_failures, num_failures_dev, and quda::unitarizeLinks().
Referenced by main(), and GaugeAlgTest::SetUp().
display_test_info()
void display_test_info ()
Definition at line 62 of file heatbath_test.cpp.
References dimPartitioned(), get_prec_str(), get_recon_str(), link_recon, link_recon_sloppy, Lsdim, prec, prec_sloppy, printfQuda, tdim, xdim, ydim, and zdim.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 149 of file heatbath_test.cpp.
References CallUnitarizeLinks(), comm_dim_partitioned(), construct_gauge_field(), quda::copyExtendedGauge(), copyExtendedResidentGaugeQuda(), QudaGaugeParam_s::cpu_prec, quda::GaugeFieldParam::create, QudaGaugeParam_s::cuda_prec, device, display_test_info(), endQuda(), extendedGaugeResident, finalizeComms(), freeGaugeQuda(), QudaGaugeParam_s::gauge_order, gauge_outfile, quda::cudaGaugeField::Gauge_p(), gauge_param, gaugeSiteSize, quda::LatticeFieldParam::ghostExchange, gParam, gridsize_from_cmdline, gSize, heatbath_beta_value, heatbath_coldstart, heatbath_num_heatbath_per_step, heatbath_num_overrelax_per_step, heatbath_num_steps, heatbath_warmup_steps, quda::RNG::Init(), initComms(), quda::InitGaugeField(), initQuda(), initRand(), latfile, link_recon, link_recon_sloppy, quda::GaugeFieldParam::link_type, loadGaugeQuda(), QudaGaugeParam_s::location, quda::Monte(), newQudaGaugeParam(), quda::GaugeFieldParam::order, quda::LatticeFieldParam::pad, quda::PGaugeExchangeFree(), quda::plaquette(), prec, prec_sloppy, printfQuda, process_command_line_option(), qChargeQuda(), QUDA_CUDA_FIELD_LOCATION, QUDA_DOUBLE_PRECISION, QUDA_FLOAT2_GAUGE_ORDER, QUDA_FLOAT4_GAUGE_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_GHOST_EXCHANGE_EXTENDED, QUDA_GHOST_EXCHANGE_NO, QUDA_INVALID_PRECISION, QUDA_NULL_FIELD_CREATE, QUDA_RECONSTRUCT_8, QUDA_RECONSTRUCT_INVALID, QUDA_RECONSTRUCT_NO, QUDA_VECTOR_GEOMETRY, QUDA_ZERO_FIELD_CREATE, R, read_gauge_field(), quda::GaugeFieldParam::reconstruct, QudaGaugeParam_s::reconstruct, quda::RNG::Release(), saveGaugeFieldQuda(), setDims(), setGaugeParam(), setReunitarizationConsts(), setSpinorSiteSize(), quda::GaugeFieldParam::t_boundary, QudaGaugeParam_s::type, usage(), V, write_gauge_field(), and QudaGaugeParam_s::X.
setGaugeParam()
void setGaugeParam (QudaGaugeParam & gauge_param)
Definition at line 87 of file heatbath_test.cpp.
References QudaGaugeParam_s::anisotropy, anisotropy, QudaGaugeParam_s::cpu_prec, cpu_prec, QudaGaugeParam_s::cuda_prec, cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, cuda_prec_sloppy, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, link_recon, link_recon_sloppy, MAX, QUDA_GAUGE_FIXED_NO, QUDA_PERIODIC_T, QUDA_QDP_GAUGE_ORDER, QUDA_WILSON_LINKS, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, QudaGaugeParam_s::t_boundary, QudaGaugeParam_s::tadpole_coeff, tdim, QudaGaugeParam_s::type, QudaGaugeParam_s::X, xdim, ydim, and zdim.
Referenced by main().
setReunitarizationConsts()
void setReunitarizationConsts ()
Definition at line 123 of file heatbath_test.cpp.
References reunit_allow_svd, reunit_svd_only, quda::setUnitarizeLinksConstants(), svd_abs_error, svd_rel_error, and unitarize_eps.
Referenced by main().
usage()
void usage (char **)
Definition at line 1783 of file test_util.cpp.
Referenced by main().
Variable Documentation
anisotropy
double anisotropy
Definition at line 1650 of file test_util.cpp.
Referenced by setGaugeParam().
cpu_prec
QudaPrecision& cpu_prec = prec
Definition at line 83 of file heatbath_test.cpp.
Referenced by setGaugeParam().
cuda_prec
QudaPrecision& cuda_prec = prec
Definition at line 84 of file heatbath_test.cpp.
Referenced by setGaugeParam().
cuda_prec_sloppy
QudaPrecision& cuda_prec_sloppy = prec_sloppy
Definition at line 85 of file heatbath_test.cpp.
Referenced by setGaugeParam().
device
int device
Definition at line 1602 of file test_util.cpp.
Referenced by main().
gauge_outfile
char gauge_outfile[]
Definition at line 1626 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 49 of file test_util.cpp.
Referenced by main().
heatbath_beta_value
double heatbath_beta_value
Definition at line 1765 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
heatbath_coldstart
bool heatbath_coldstart
Definition at line 1770 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
heatbath_num_heatbath_per_step
int heatbath_num_heatbath_per_step
Definition at line 1768 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
heatbath_num_overrelax_per_step
int heatbath_num_overrelax_per_step
Definition at line 1769 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
heatbath_num_steps
int heatbath_num_steps
Definition at line 1767 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
heatbath_warmup_steps
int heatbath_warmup_steps
Definition at line 1766 of file test_util.cpp.
Referenced by main(), and process_command_line_option().
latfile
char latfile[]
Definition at line 1623 of file test_util.cpp.
Referenced by main().
link_recon
QudaReconstructType link_recon
Definition at line 1605 of file test_util.cpp.
Referenced by display_test_info(), main(), and setGaugeParam().
link_recon_sloppy
QudaReconstructType link_recon_sloppy
Definition at line 1606 of file test_util.cpp.
Referenced by display_test_info(), main(), and setGaugeParam().
Lsdim
int Lsdim
Definition at line 1619 of file test_util.cpp.
Referenced by display_test_info().
prec
QudaPrecision prec
Definition at line 1608 of file test_util.cpp.
Referenced by display_test_info(), and main().
prec_sloppy
QudaPrecision prec_sloppy
Definition at line 1609 of file test_util.cpp.
Referenced by display_test_info(), and main().
tdim
int tdim
Definition at line 1618 of file test_util.cpp.
Referenced by display_test_info(), and setGaugeParam().
xdim
int xdim
Definition at line 1615 of file test_util.cpp.
Referenced by display_test_info(), and setGaugeParam().
ydim
int ydim
Definition at line 1616 of file test_util.cpp.
Referenced by display_test_info(), and setGaugeParam().
zdim
int zdim
Definition at line 1617 of file test_util.cpp.
Referenced by display_test_info(), and setGaugeParam().