QUDA: tests/llfat_reference.h File Reference
llfat_reference.h File Reference
Functions
void llfat_reference (void **fatlink, void **sitelink, QudaPrecision prec, void *act_path_coeff)
void llfat_reference_mg (void **fatlink, void **sitelink, void **ghost_sitelink, void **ghost_sitelink_diag, QudaPrecision prec, void *act_path_coeff)
void computeLongLinkCPU (void **longlink, void **sitelink, QudaPrecision prec, void *act_path_coeff)
void cpu_axy (QudaPrecision prec, double a, void *x, void *y, int size)
void cpu_xpy (QudaPrecision prec, void *x, void *y, int size)
void computeHISQLinksCPU (void **fatlink, void **longlink, void **fatlink_eps, void **longlink_eps, void **sitelink, void *qudaGaugeParamPtr, double **act_path_coeffs, double eps_naik)
void reorderQDPtoMILC (void *milc_out, void **qdp_in, int V, int siteSize, QudaPrecision out_precision, QudaPrecision in_precision)
void reorderMILCtoQDP (void **qdp_out, void *milc_in, int V, int siteSize, QudaPrecision out_precision, QudaPrecision in_precision)
Function Documentation
computeHISQLinksCPU()
void computeHISQLinksCPU (void ** fatlink, void ** longlink, void ** fatlink_eps, void ** longlink_eps, void ** sitelink, void * qudaGaugeParamPtr, double ** act_path_coeffs, double eps_naik)
Definition at line 912 of file llfat_reference.cpp.
References computeLongLinkCPU(), cpu_axy(), QudaGaugeParam_s::cpu_prec, cpu_xpy(), quda::GaugeFieldParam::create, E1h, E2, E3, exchange_cpu_sitelink(), exchange_cpu_sitelink_ex(), quda::GaugeFieldParam::gauge, quda::cpuGaugeField::Gauge_p(), gaugeSiteSize, quda::LatticeFieldParam::ghostExchange, gParam, gSize, host_free, quda::GaugeFieldParam::link_type, llfat_reference(), llfat_reference_mg(), memset(), mu, n_naiks, quda::GaugeFieldParam::order, quda::LatticeFieldParam::pad, pinned_malloc, prec, QUDA_DOUBLE_PRECISION, QUDA_GENERAL_LINKS, QUDA_GHOST_EXCHANGE_NO, QUDA_MILC_GAUGE_ORDER, QUDA_QDP_GAUGE_ORDER, QUDA_REFERENCE_FIELD_CREATE, QUDA_ZERO_FIELD_CREATE, qudaGaugeParam, R, reorderMILCtoQDP(), reorderQDPtoMILC(), safe_malloc, quda::unitarizeLinksCPU(), V, V_ex, Vh, Vh_ex, Vs, Vs_t, Vs_x, Vs_y, Vs_z, QudaGaugeParam_s::X, quda::LatticeFieldParam::x, X1, X2, X3, X4, and Z.
Referenced by computeFatLongGPUandCPU(), and hisq_test().
computeLongLinkCPU()
void computeLongLinkCPU (void ** longlink, void ** sitelink, QudaPrecision prec, void * act_path_coeff)
Definition at line 365 of file llfat_reference.cpp.
References computeLongLinkCPU(), QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
cpu_axy()
void cpu_axy (QudaPrecision prec, double a, void * x, void * y, int size)
Definition at line 816 of file llfat_reference.cpp.
References QUDA_DOUBLE_PRECISION, and quda::size.
Referenced by computeHISQLinksCPU(), computeHISQLinksGPU(), and hisq_test().
cpu_xpy()
void cpu_xpy (QudaPrecision prec, void * x, void * y, int size)
Definition at line 835 of file llfat_reference.cpp.
References QUDA_DOUBLE_PRECISION, and quda::size.
Referenced by computeHISQLinksCPU(), computeHISQLinksGPU(), and hisq_test().
llfat_reference()
void llfat_reference (void ** fatlink, void ** sitelink, QudaPrecision prec, void * act_path_coeff)
Definition at line 387 of file llfat_reference.cpp.
References exchange_cpu_staple(), fatlink, llfat_add_su3_matrix(), llfat_cpu(), llfat_mult_su3_an(), llfat_mult_su3_na(), llfat_mult_su3_nn(), llfat_reference_mg(), llfat_scalar_mult_add_su3_matrix(), llfat_scalar_mult_su3_matrix(), memset(), mu, neighborIndexFullLattice_mg(), prec, QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, TUP, V, Vh, Vs, Vs_t, Vs_x, Vs_y, Vs_z, Vsh, Vsh_t, Vsh_x, Vsh_y, Vsh_z, X1, X2, X3, XUP, and Z.
Referenced by computeHISQLinksCPU(), and llfat_test().
llfat_reference_mg()
void llfat_reference_mg (void ** fatlink, void ** sitelink, void ** ghost_sitelink, void ** ghost_sitelink_diag, QudaPrecision prec, void * act_path_coeff)
Referenced by computeHISQLinksCPU(), llfat_reference(), and llfat_test().
reorderMILCtoQDP()
void reorderMILCtoQDP (void ** qdp_out, void * milc_in, int V, int siteSize, QudaPrecision out_precision, QudaPrecision in_precision)
Definition at line 893 of file llfat_reference.cpp.
References QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, and V.
reorderQDPtoMILC()
void reorderQDPtoMILC (void * milc_out, void ** qdp_in, int V, int siteSize, QudaPrecision out_precision, QudaPrecision in_precision)
Definition at line 866 of file llfat_reference.cpp.
References QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, and V.