QUDA: tests/multigrid_benchmark_test.cu File Reference
multigrid_benchmark_test.cu File Reference
#include <stdio.h>
#include <stdlib.h>
#include <quda_internal.h>
#include <color_spinor_field.h>
#include <blas_quda.h>
#include <test_util.h>
#include <misc.h>
#include <dslash_util.h>
#include <dirac_quda.h>
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
#define MAX(a, b) ((a)>(b)?(a):(b))
Functions
void usage (char **)
void display_test_info ()
void initFields (QudaPrecision prec)
void freeFields ()
double benchmark (int test, const int niter)
int main (int argc, char **argv)
Variables
QudaDslashType dslash_type
QudaInverterType inv_type
int nvec
int device
int xdim
int ydim
int zdim
int tdim
int gridsize_from_cmdline []
int niter
int Nsrc
bool verify_results
int test_type
QudaPrecision prec
QudaPrecision prec_sloppy
QudaPrecision smoother_halo_prec
ColorSpinorField * xH
ColorSpinorField * yH
ColorSpinorField * xD
ColorSpinorField * yD
cpuGaugeField * Y_h
cpuGaugeField * X_h
cpuGaugeField * Xinv_h
cpuGaugeField * Yhat_h
cudaGaugeField * Y_d
cudaGaugeField * X_d
cudaGaugeField * Xinv_d
cudaGaugeField * Yhat_d
int Nspin
int Ncolor
DiracCoarse * dirac
const char * names []
Macro Definition Documentation
MAX [1/2]
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 51 of file multigrid_benchmark_test.cu.
Referenced by initFields().
MAX [2/2]
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 51 of file multigrid_benchmark_test.cu.
Function Documentation
benchmark()
double benchmark (int test, const int niter)
Definition at line 191 of file multigrid_benchmark_test.cu.
References quda::DiracCoarse::Clover(), quda::DiracCoarse::Dslash(), quda::blas::end(), errorQuda, quda::ColorSpinorField::Even(), quda::DiracCoarse::M(), niter, quda::ColorSpinorField::Odd(), and QUDA_EVEN_PARITY.
Referenced by main().
display_test_info()
void display_test_info ()
Definition at line 54 of file multigrid_benchmark_test.cu.
References dimPartitioned(), Ncolor, Nspin, printfQuda, tdim, xdim, ydim, and zdim.
Referenced by main().
freeFields()
void freeFields ()
Definition at line 170 of file multigrid_benchmark_test.cu.
References X_d, X_h, xD, xH, Xinv_d, Xinv_h, Y_d, Y_h, yD, yH, Yhat_d, and Yhat_h.
Referenced by main().
initFields()
void initFields (QudaPrecision prec)
Definition at line 68 of file multigrid_benchmark_test.cu.
References checkCudaError, quda::cudaGaugeField::copy(), quda::GaugeFieldParam::create, quda::ColorSpinorParam::create, quda::ColorSpinorParam::fieldOrder, quda::ColorSpinorParam::gammaBasis, quda::GaugeFieldParam::geometry, quda::LatticeFieldParam::ghostExchange, gParam, quda::GaugeFieldParam::link_type, MAX, quda::GaugeFieldParam::nColor, Ncolor, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::GaugeFieldParam::nFace, Nspin, quda::ColorSpinorParam::nSpin, Nsrc, quda::GaugeFieldParam::order, quda::LatticeFieldParam::pad, param, quda::ColorSpinorParam::pc_type, prec_sloppy, quda::LatticeFieldParam::Precision(), QUDA_4D_PC, QUDA_COARSE_GEOMETRY, QUDA_COARSE_LINKS, QUDA_DEGRAND_ROSSI_GAMMA_BASIS, QUDA_DOUBLE_PRECISION, QUDA_EVEN_ODD_SITE_ORDER, QUDA_FLOAT2_FIELD_ORDER, QUDA_FLOAT2_GAUGE_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_GHOST_EXCHANGE_NO, QUDA_GHOST_EXCHANGE_PAD, QUDA_PERIODIC_T, QUDA_QDP_GAUGE_ORDER, QUDA_RECONSTRUCT_NO, QUDA_SCALAR_GEOMETRY, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, QUDA_UKQCD_GAMMA_BASIS, QUDA_ZERO_FIELD_CREATE, quda::GaugeFieldParam::reconstruct, quda::GaugeFieldParam::setPrecision(), quda::ColorSpinorParam::setPrecision(), quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::GaugeFieldParam::t_boundary, tdim, quda::LatticeFieldParam::x, xdim, ydim, and zdim.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 230 of file multigrid_benchmark_test.cu.
References benchmark(), device, dirac, display_test_info(), endQuda(), finalizeComms(), quda::Dirac::Flops(), freeFields(), get_prec_str(), gridsize_from_cmdline, quda::DiracParam::halo_precision, initComms(), initFields(), initQuda(), names, Ncolor, niter, Nspin, param, prec, prec_sloppy, printfQuda, process_command_line_option(), QUDA_INVALID_PRECISION, QUDA_SUMMARIZE, setVerbosity(), smoother_halo_prec, tdim, test_type, usage(), xdim, ydim, and zdim.
usage()
void usage (char **)
Definition at line 1783 of file test_util.cpp.
Referenced by main().
Variable Documentation
device
int device
Definition at line 1602 of file test_util.cpp.
Referenced by main().
dirac
DiracCoarse* dirac
Definition at line 189 of file multigrid_benchmark_test.cu.
Referenced by main().
dslash_type
QudaDslashType dslash_type
Definition at line 1621 of file test_util.cpp.
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 49 of file test_util.cpp.
Referenced by main().
inv_type
QudaInverterType inv_type
Definition at line 1640 of file test_util.cpp.
names
const char* names[]
Initial value:
= {
  "Dslash",
  "Mat",
  "Clover"
}
Definition at line 224 of file multigrid_benchmark_test.cu.
Referenced by main().
Ncolor
int Ncolor
Definition at line 49 of file multigrid_benchmark_test.cu.
Referenced by display_test_info(), initFields(), and main().
niter
int niter
Definition at line 1629 of file test_util.cpp.
Referenced by benchmark(), and main().
Nspin
int Nspin
Definition at line 48 of file multigrid_benchmark_test.cu.
Referenced by display_test_info(), initFields(), and main().
Nsrc
int Nsrc
Definition at line 1627 of file test_util.cpp.
Referenced by initFields().
nvec
int nvec
Definition at line 1637 of file test_util.cpp.
prec
QudaPrecision prec
Definition at line 1608 of file test_util.cpp.
Referenced by main().
prec_sloppy
QudaPrecision prec_sloppy
Definition at line 1609 of file test_util.cpp.
Referenced by initFields(), and main().
smoother_halo_prec
QudaPrecision smoother_halo_prec
Definition at line 1694 of file test_util.cpp.
Referenced by main().
tdim
int tdim
Definition at line 1618 of file test_util.cpp.
Referenced by display_test_info(), initFields(), and main().
test_type
int test_type
Definition at line 1636 of file test_util.cpp.
Referenced by main().
verify_results
bool verify_results
Definition at line 1643 of file test_util.cpp.
X_d
cudaGaugeField * X_d
Definition at line 46 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
X_h
cpuGaugeField * X_h
Definition at line 45 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
xD
ColorSpinorField* xD
Definition at line 43 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
xdim
int xdim
Definition at line 1615 of file test_util.cpp.
Referenced by display_test_info(), initFields(), and main().
xH
ColorSpinorField* xH
Definition at line 42 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Xinv_d
cudaGaugeField * Xinv_d
Definition at line 46 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Xinv_h
cpuGaugeField * Xinv_h
Definition at line 45 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Y_d
cudaGaugeField* Y_d
Definition at line 46 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Y_h
cpuGaugeField* Y_h
Definition at line 45 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
yD
ColorSpinorField * yD
Definition at line 43 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
ydim
int ydim
Definition at line 1616 of file test_util.cpp.
Referenced by display_test_info(), initFields(), and main().
yH
ColorSpinorField * yH
Definition at line 42 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Yhat_d
cudaGaugeField * Yhat_d
Definition at line 46 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
Yhat_h
cpuGaugeField * Yhat_h
Definition at line 45 of file multigrid_benchmark_test.cu.
Referenced by freeFields().
zdim
int zdim
Definition at line 1617 of file test_util.cpp.
Referenced by display_test_info(), initFields(), and main().