QUDA: quda::blas::copy_ns Namespace Reference
quda::blas::copy_ns Namespace Reference
Classes
class CopyCuda
Functions
template<typename FloatN , int N, typename Output , typename Input >
__global__ void copyKernel (Output Y, Input X, int length)
void copy (cudaColorSpinorField &dst, const cudaColorSpinorField &src)
Variables
struct {
const char * quda::blas::copy_ns::vol_str
const char * quda::blas::copy_ns::aux_str
} blasStrings
Function Documentation
copy()
void quda::blas::copy_ns::copy (cudaColorSpinorField & dst, const cudaColorSpinorField & src)
Definition at line 105 of file copy_quda.cu.
References quda::LatticeField::AuxString(), blasStrings, quda::blas::bytes, quda::ColorSpinorField::Bytes(), checkCudaError, checkSpinorLength, quda::ColorSpinorField::CompositeDim(), errorQuda, quda::blas::getStream(), quda::ColorSpinorField::IsComposite(), quda::ColorSpinorField::Length(), quda::ColorSpinorField::Norm(), quda::ColorSpinorField::NormBytes(), quda::ColorSpinorField::Nspin(), quda::LatticeField::Precision(), QUDA_DOUBLE_PRECISION, QUDA_HALF_PRECISION, QUDA_QUARTER_PRECISION, QUDA_SINGLE_PRECISION, qudaMemcpyAsync, quda::ColorSpinorField::RealLength(), quda::ColorSpinorField::SiteSubset(), tmp, quda::ColorSpinorField::V(), quda::LatticeField::VolString(), and quda::ColorSpinorField::Volume().
Referenced by quda::blas::copy().
copyKernel()
template<typename FloatN , int N, typename Output , typename Input > __global__ void quda::blas::copy_ns::copyKernel (Output Y, Input X, int length)
Definition at line 32 of file copy_quda.cu.
References parity.
Variable Documentation
aux_str
const char* quda::blas::copy_ns::aux_str
Definition at line 28 of file copy_quda.cu.
blasStrings
struct { ... } quda::blas::copy_ns::blasStrings
Referenced by copy(), and quda::blas::copy_ns::CopyCuda< FloatN, N, Output, Input >::tuneKey().
vol_str
const char* quda::blas::copy_ns::vol_str
Definition at line 27 of file copy_quda.cu.
Referenced by quda::CalculateY< from_coarse, Float, fineSpin, fineColor, coarseSpin, coarseColor, Arg >::tuneKey().