QUDA: lib/nvtx_pmpi.c File Reference
nvtx_pmpi.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <nvToolsExt.h>
#include <nvToolsExtCudaRt.h>
#include <mpi_comm_handle.h>
Macros
#define _EXTERN_C_
Functions
_EXTERN_C_ void pmpi_init (MPI_Fint *ierr)
_EXTERN_C_ void PMPI_INIT (MPI_Fint *ierr)
_EXTERN_C_ void pmpi_init_ (MPI_Fint *ierr)
_EXTERN_C_ void pmpi_init__ (MPI_Fint *ierr)
_EXTERN_C_ int PMPI_Init (int *argc, char ***argv)
_EXTERN_C_ int MPI_Init (int *argc, char ***argv)
_EXTERN_C_ int PMPI_Send (const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
_EXTERN_C_ int MPI_Send (const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
_EXTERN_C_ int PMPI_Recv (void *buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status *status)
_EXTERN_C_ int MPI_Recv (void *buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status *status)
_EXTERN_C_ int PMPI_Allreduce (const void *sendbuf, void *recvbuf, int count, MPI_Datatype datatype, MPI_Op op, MPI_Comm comm)
_EXTERN_C_ int MPI_Allreduce (const void *sendbuf, void *recvbuf, int count, MPI_Datatype datatype, MPI_Op op, MPI_Comm comm)
_EXTERN_C_ int PMPI_Reduce (const void *sendbuf, void *recvbuf, int count, MPI_Datatype datatype, MPI_Op op, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Reduce (const void *sendbuf, void *recvbuf, int count, MPI_Datatype datatype, MPI_Op op, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Wait (MPI_Request *request, MPI_Status *status)
_EXTERN_C_ int MPI_Wait (MPI_Request *request, MPI_Status *status)
_EXTERN_C_ int PMPI_Waitany (int count, MPI_Request array_of_requests[], int *index, MPI_Status *status)
_EXTERN_C_ int MPI_Waitany (int count, MPI_Request array_of_requests[], int *index, MPI_Status *status)
_EXTERN_C_ int PMPI_Waitall (int count, MPI_Request array_of_requests[], MPI_Status *array_of_statuses)
_EXTERN_C_ int MPI_Waitall (int count, MPI_Request array_of_requests[], MPI_Status *array_of_statuses)
_EXTERN_C_ int PMPI_Waitsome (int incount, MPI_Request array_of_requests[], int *outcount, int array_of_indices[], MPI_Status array_of_statuses[])
_EXTERN_C_ int MPI_Waitsome (int incount, MPI_Request array_of_requests[], int *outcount, int array_of_indices[], MPI_Status array_of_statuses[])
_EXTERN_C_ int PMPI_Gather (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Gather (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Gatherv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Gatherv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Scatter (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Scatter (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Scatterv (const void *sendbuf, const int sendcounts[], const int displs[], MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Scatterv (const void *sendbuf, const int sendcounts[], const int displs[], MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Allgather (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int MPI_Allgather (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int PMPI_Allgatherv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int MPI_Allgatherv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int PMPI_Alltoall (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int MPI_Alltoall (const void *sendbuf, int sendcount, MPI_Datatype sendtype, void *recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int PMPI_Alltoallv (const void *sendbuf, const int sendcounts[], const int sdispls[], MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int rdispls[], MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int MPI_Alltoallv (const void *sendbuf, const int sendcounts[], const int sdispls[], MPI_Datatype sendtype, void *recvbuf, const int recvcounts[], const int rdispls[], MPI_Datatype recvtype, MPI_Comm comm)
_EXTERN_C_ int PMPI_Alltoallw (const void *sendbuf, const int sendcounts[], const int sdispls[], const MPI_Datatype sendtypes[], void *recvbuf, const int recvcounts[], const int rdispls[], const MPI_Datatype recvtypes[], MPI_Comm comm)
_EXTERN_C_ int MPI_Alltoallw (const void *sendbuf, const int sendcounts[], const int sdispls[], const MPI_Datatype sendtypes[], void *recvbuf, const int recvcounts[], const int rdispls[], const MPI_Datatype recvtypes[], MPI_Comm comm)
_EXTERN_C_ int PMPI_Bcast (void *buffer, int count, MPI_Datatype datatype, int root, MPI_Comm comm)
_EXTERN_C_ int MPI_Bcast (void *buffer, int count, MPI_Datatype datatype, int root, MPI_Comm comm)
_EXTERN_C_ int PMPI_Sendrecv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, int dest, int sendtag, void *recvbuf, int recvcount, MPI_Datatype recvtype, int source, int recvtag, MPI_Comm comm, MPI_Status *status)
_EXTERN_C_ int MPI_Sendrecv (const void *sendbuf, int sendcount, MPI_Datatype sendtype, int dest, int sendtag, void *recvbuf, int recvcount, MPI_Datatype recvtype, int source, int recvtag, MPI_Comm comm, MPI_Status *status)
_EXTERN_C_ int PMPI_Barrier (MPI_Comm comm)
_EXTERN_C_ int MPI_Barrier (MPI_Comm comm)
_EXTERN_C_ int PMPI_Start (MPI_Request *request)
_EXTERN_C_ int MPI_Start (MPI_Request *request)
_EXTERN_C_ int PMPI_Test (MPI_Request *request, int *flag, MPI_Status *status)
_EXTERN_C_ int MPI_Test (MPI_Request *request, int *flag, MPI_Status *status)
_EXTERN_C_ int PMPI_Send_init (const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request *request)
_EXTERN_C_ int MPI_Send_init (const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request *request)
_EXTERN_C_ int PMPI_Recv_init (void *buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Request *request)
_EXTERN_C_ int MPI_Recv_init (void *buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Request *request)
Variables
static int in_wrapper = 0
Macro Definition Documentation
_EXTERN_C_
#define _EXTERN_C_
Definition at line 9 of file nvtx_pmpi.c.
Referenced by MPI_Allgather(), MPI_Allgatherv(), MPI_Allreduce(), MPI_Alltoall(), MPI_Alltoallv(), MPI_Alltoallw(), MPI_Barrier(), MPI_Bcast(), MPI_Gather(), MPI_Gatherv(), MPI_Init(), MPI_Recv(), MPI_Reduce(), MPI_Scatter(), MPI_Scatterv(), MPI_Send(), MPI_Send_init(), MPI_Sendrecv(), MPI_Start(), MPI_Test(), MPI_Wait(), MPI_Waitall(), MPI_Waitany(), and MPI_Waitsome().
Function Documentation
MPI_Allgather()
_EXTERN_C_ int MPI_Allgather (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
Definition at line 340 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Allgather(), and PMPI_Allgatherv().
Referenced by comm_allreduce(), comm_allreduce_array(), comm_gather_gpuid(), and comm_gather_hostname().
MPI_Allgatherv()
_EXTERN_C_ int MPI_Allgatherv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, MPI_Comm comm)
Definition at line 363 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Allgatherv(), and PMPI_Alltoall().
MPI_Allreduce()
_EXTERN_C_ int MPI_Allreduce (const void * sendbuf, void * recvbuf, int count, MPI_Datatype datatype, MPI_Op op, MPI_Comm comm)
Definition at line 110 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Allreduce(), and PMPI_Reduce().
Referenced by comm_allreduce(), comm_allreduce_array(), comm_allreduce_int(), comm_allreduce_max(), comm_allreduce_max_array(), comm_allreduce_min(), and comm_allreduce_xor().
MPI_Alltoall()
_EXTERN_C_ int MPI_Alltoall (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
Definition at line 386 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Alltoall(), and PMPI_Alltoallv().
MPI_Alltoallv()
_EXTERN_C_ int MPI_Alltoallv (const void * sendbuf, const int sendcounts[], const int sdispls[], MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int rdispls[], MPI_Datatype recvtype, MPI_Comm comm)
Definition at line 409 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Alltoallv(), and PMPI_Alltoallw().
MPI_Alltoallw()
_EXTERN_C_ int MPI_Alltoallw (const void * sendbuf, const int sendcounts[], const int sdispls[], const MPI_Datatype sendtypes[], void * recvbuf, const int recvcounts[], const int rdispls[], const MPI_Datatype recvtypes[], MPI_Comm comm)
Definition at line 432 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Alltoallw(), and PMPI_Bcast().
MPI_Barrier()
_EXTERN_C_ int MPI_Barrier (MPI_Comm comm)
Definition at line 501 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Barrier(), and PMPI_Start().
Referenced by comm_barrier().
MPI_Bcast()
_EXTERN_C_ int MPI_Bcast (void * buffer, int count, MPI_Datatype datatype, int root, MPI_Comm comm)
Definition at line 455 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Bcast(), and PMPI_Sendrecv().
Referenced by comm_broadcast().
MPI_Gather()
_EXTERN_C_ int MPI_Gather (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Definition at line 248 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Gather(), and PMPI_Gatherv().
MPI_Gatherv()
_EXTERN_C_ int MPI_Gatherv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm comm)
Definition at line 271 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Gatherv(), and PMPI_Scatter().
MPI_Init()
_EXTERN_C_ int MPI_Init (int * argc, char *** argv)
Definition at line 42 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Init(), PMPI_Send(), and rank.
Referenced by initComms().
MPI_Recv()
_EXTERN_C_ int MPI_Recv (void * buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status * status)
Definition at line 87 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Allreduce(), and PMPI_Recv().
MPI_Recv_init()
_EXTERN_C_ int MPI_Recv_init (void * buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Request * request)
Definition at line 593 of file nvtx_pmpi.c.
References in_wrapper, and PMPI_Recv_init().
Referenced by comm_declare_receive_displaced(), and comm_declare_strided_receive_displaced().
MPI_Reduce()
_EXTERN_C_ int MPI_Reduce (const void * sendbuf, void * recvbuf, int count, MPI_Datatype datatype, MPI_Op op, int root, MPI_Comm comm)
Definition at line 133 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Reduce(), and PMPI_Wait().
MPI_Scatter()
_EXTERN_C_ int MPI_Scatter (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Definition at line 294 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Scatter(), and PMPI_Scatterv().
MPI_Scatterv()
_EXTERN_C_ int MPI_Scatterv (const void * sendbuf, const int sendcounts[], const int displs[], MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Definition at line 317 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Allgather(), and PMPI_Scatterv().
MPI_Send()
_EXTERN_C_ int MPI_Send (const void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
Definition at line 64 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Recv(), and PMPI_Send().
MPI_Send_init()
_EXTERN_C_ int MPI_Send_init (const void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Definition at line 570 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Recv_init(), and PMPI_Send_init().
Referenced by comm_declare_send_displaced(), and comm_declare_strided_send_displaced().
MPI_Sendrecv()
_EXTERN_C_ int MPI_Sendrecv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, int dest, int sendtag, void * recvbuf, int recvcount, MPI_Datatype recvtype, int source, int recvtag, MPI_Comm comm, MPI_Status * status)
Definition at line 478 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Barrier(), and PMPI_Sendrecv().
MPI_Start()
_EXTERN_C_ int MPI_Start (MPI_Request * request)
Definition at line 524 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Start(), and PMPI_Test().
Referenced by comm_start().
MPI_Test()
_EXTERN_C_ int MPI_Test (MPI_Request * request, int * flag, MPI_Status * status)
Definition at line 547 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Send_init(), and PMPI_Test().
Referenced by comm_query().
MPI_Wait()
_EXTERN_C_ int MPI_Wait (MPI_Request * request, MPI_Status * status)
Definition at line 156 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, index(), PMPI_Wait(), and PMPI_Waitany().
Referenced by comm_wait().
MPI_Waitall()
_EXTERN_C_ int MPI_Waitall (int count, MPI_Request array_of_requests[], MPI_Status * array_of_statuses)
Definition at line 202 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Waitall(), and PMPI_Waitsome().
MPI_Waitany()
_EXTERN_C_ int MPI_Waitany (int count, MPI_Request array_of_requests[], int * index, MPI_Status * status)
Definition at line 179 of file nvtx_pmpi.c.
References _EXTERN_C_, quda::count, in_wrapper, PMPI_Waitall(), and PMPI_Waitany().
MPI_Waitsome()
_EXTERN_C_ int MPI_Waitsome (int incount, MPI_Request array_of_requests[], int * outcount, int array_of_indices[], MPI_Status array_of_statuses[])
Definition at line 225 of file nvtx_pmpi.c.
References _EXTERN_C_, in_wrapper, PMPI_Gather(), and PMPI_Waitsome().
PMPI_Allgather()
_EXTERN_C_ int PMPI_Allgather (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
Referenced by MPI_Allgather(), and MPI_Scatterv().
PMPI_Allgatherv()
_EXTERN_C_ int PMPI_Allgatherv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, MPI_Comm comm)
Referenced by MPI_Allgather(), and MPI_Allgatherv().
PMPI_Allreduce()
_EXTERN_C_ int PMPI_Allreduce (const void * sendbuf, void * recvbuf, int count, MPI_Datatype datatype, MPI_Op op, MPI_Comm comm)
Referenced by MPI_Allreduce(), and MPI_Recv().
PMPI_Alltoall()
_EXTERN_C_ int PMPI_Alltoall (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, MPI_Comm comm)
Referenced by MPI_Allgatherv(), and MPI_Alltoall().
PMPI_Alltoallv()
_EXTERN_C_ int PMPI_Alltoallv (const void * sendbuf, const int sendcounts[], const int sdispls[], MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int rdispls[], MPI_Datatype recvtype, MPI_Comm comm)
Referenced by MPI_Alltoall(), and MPI_Alltoallv().
PMPI_Alltoallw()
_EXTERN_C_ int PMPI_Alltoallw (const void * sendbuf, const int sendcounts[], const int sdispls[], const MPI_Datatype sendtypes[], void * recvbuf, const int recvcounts[], const int rdispls[], const MPI_Datatype recvtypes[], MPI_Comm comm)
Referenced by MPI_Alltoallv(), and MPI_Alltoallw().
PMPI_Barrier()
_EXTERN_C_ int PMPI_Barrier (MPI_Comm comm)
Referenced by MPI_Barrier(), and MPI_Sendrecv().
PMPI_Bcast()
_EXTERN_C_ int PMPI_Bcast (void * buffer, int count, MPI_Datatype datatype, int root, MPI_Comm comm)
Referenced by MPI_Alltoallw(), and MPI_Bcast().
PMPI_Gather()
_EXTERN_C_ int PMPI_Gather (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Referenced by MPI_Gather(), and MPI_Waitsome().
PMPI_Gatherv()
_EXTERN_C_ int PMPI_Gatherv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, const int recvcounts[], const int displs[], MPI_Datatype recvtype, int root, MPI_Comm comm)
Referenced by MPI_Gather(), and MPI_Gatherv().
pmpi_init()
_EXTERN_C_ void pmpi_init (MPI_Fint * ierr)
PMPI_INIT()
_EXTERN_C_ void PMPI_INIT (MPI_Fint * ierr)
PMPI_Init()
_EXTERN_C_ int PMPI_Init (int * argc, char *** argv)
Referenced by MPI_Init().
pmpi_init_()
_EXTERN_C_ void pmpi_init_ (MPI_Fint * ierr)
pmpi_init__()
_EXTERN_C_ void pmpi_init__ (MPI_Fint * ierr)
PMPI_Recv()
_EXTERN_C_ int PMPI_Recv (void * buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status * status)
Referenced by MPI_Recv(), and MPI_Send().
PMPI_Recv_init()
_EXTERN_C_ int PMPI_Recv_init (void * buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Request * request)
Referenced by MPI_Recv_init(), and MPI_Send_init().
PMPI_Reduce()
_EXTERN_C_ int PMPI_Reduce (const void * sendbuf, void * recvbuf, int count, MPI_Datatype datatype, MPI_Op op, int root, MPI_Comm comm)
Referenced by MPI_Allreduce(), and MPI_Reduce().
PMPI_Scatter()
_EXTERN_C_ int PMPI_Scatter (const void * sendbuf, int sendcount, MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Referenced by MPI_Gatherv(), and MPI_Scatter().
PMPI_Scatterv()
_EXTERN_C_ int PMPI_Scatterv (const void * sendbuf, const int sendcounts[], const int displs[], MPI_Datatype sendtype, void * recvbuf, int recvcount, MPI_Datatype recvtype, int root, MPI_Comm comm)
Referenced by MPI_Scatter(), and MPI_Scatterv().
PMPI_Send()
_EXTERN_C_ int PMPI_Send (const void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
Referenced by MPI_Init(), and MPI_Send().
PMPI_Send_init()
_EXTERN_C_ int PMPI_Send_init (const void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Referenced by MPI_Send_init(), and MPI_Test().
PMPI_Sendrecv()
_EXTERN_C_ int PMPI_Sendrecv (const void * sendbuf, int sendcount, MPI_Datatype sendtype, int dest, int sendtag, void * recvbuf, int recvcount, MPI_Datatype recvtype, int source, int recvtag, MPI_Comm comm, MPI_Status * status)
Referenced by MPI_Bcast(), and MPI_Sendrecv().
PMPI_Start()
_EXTERN_C_ int PMPI_Start (MPI_Request * request)
Referenced by MPI_Barrier(), and MPI_Start().
PMPI_Test()
_EXTERN_C_ int PMPI_Test (MPI_Request * request, int * flag, MPI_Status * status)
Referenced by MPI_Start(), and MPI_Test().
PMPI_Wait()
_EXTERN_C_ int PMPI_Wait (MPI_Request * request, MPI_Status * status)
Referenced by MPI_Reduce(), and MPI_Wait().
PMPI_Waitall()
_EXTERN_C_ int PMPI_Waitall (int count, MPI_Request array_of_requests[], MPI_Status * array_of_statuses)
Referenced by MPI_Waitall(), and MPI_Waitany().
PMPI_Waitany()
_EXTERN_C_ int PMPI_Waitany (int count, MPI_Request array_of_requests[], int * index, MPI_Status * status)
Referenced by MPI_Wait(), and MPI_Waitany().
PMPI_Waitsome()
_EXTERN_C_ int PMPI_Waitsome (int incount, MPI_Request array_of_requests[], int * outcount, int array_of_indices[], MPI_Status array_of_statuses[])
Referenced by MPI_Waitall(), and MPI_Waitsome().
Variable Documentation
in_wrapper
int in_wrapper = 0 static
Definition at line 27 of file nvtx_pmpi.c.
Referenced by MPI_Allgather(), MPI_Allgatherv(), MPI_Allreduce(), MPI_Alltoall(), MPI_Alltoallv(), MPI_Alltoallw(), MPI_Barrier(), MPI_Bcast(), MPI_Gather(), MPI_Gatherv(), MPI_Init(), MPI_Recv(), MPI_Recv_init(), MPI_Reduce(), MPI_Scatter(), MPI_Scatterv(), MPI_Send(), MPI_Send_init(), MPI_Sendrecv(), MPI_Start(), MPI_Test(), MPI_Wait(), MPI_Waitall(), MPI_Waitany(), and MPI_Waitsome().