QUDA: lib/qio_field.cpp File Reference
qio_field.cpp File Reference
#include <qio.h>
#include <qio_util.h>
#include <quda.h>
#include <util_quda.h>
Functions
QIO_Reader * open_test_input (const char *filename, int volfmt, int serpar)
QIO_Writer * open_test_output (const char *filename, int volfmt, int serpar, int ildgstyle)
QudaPrecision get_prec (QIO_Reader *infile)
template<int len>
int read_field (QIO_Reader *infile, int count, void *field_in[], QudaPrecision cpu_prec)
int read_su3_field (QIO_Reader *infile, int count, void *field_in[], QudaPrecision cpu_prec)
void set_layout (const int *X)
void read_gauge_field (const char *filename, void *gauge[], QudaPrecision precision, const int *X, int argc, char *argv[])
int read_field (QIO_Reader *infile, int Ninternal, int count, void *field_in[], QudaPrecision cpu_prec)
void read_spinor_field (const char *filename, void *V[], QudaPrecision precision, const int *X, int nColor, int nSpin, int Nvec, int argc, char *argv[])
template<int len>
int write_field (QIO_Writer *outfile, int count, void *field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, int nSpin, int nColor, const char *type)
int write_su3_field (QIO_Writer *outfile, int count, void *field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, const char *type)
void write_gauge_field (const char *filename, void *gauge[], QudaPrecision precision, const int *X, int argc, char *argv[])
int write_field (QIO_Writer *outfile, int Ninternal, int count, void *field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, int nSpin, int nColor, const char *type)
void write_spinor_field (const char *filename, void *V[], QudaPrecision precision, const int *X, int nColor, int nSpin, int Nvec, int argc, char *argv[])
Variables
QIO_Layout layout
int lattice_dim
int lattice_size [4]
int this_node
Function Documentation
get_prec()
QudaPrecision get_prec (QIO_Reader * infile)
Definition at line 69 of file qio_field.cpp.
References errorQuda, prec, printfQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by main(), process_command_line_option(), and read_field().
open_test_input()
QIO_Reader* open_test_input (const char * filename, int volfmt, int serpar)
Definition at line 11 of file qio_field.cpp.
References layout, printfQuda, and this_node.
Referenced by read_gauge_field(), and read_spinor_field().
open_test_output()
QIO_Writer* open_test_output (const char * filename, int volfmt, int serpar, int ildgstyle)
Definition at line 35 of file qio_field.cpp.
References layout, printfQuda, and this_node.
Referenced by write_gauge_field(), and write_spinor_field().
read_field() [1/2]
template<int len> int read_field (QIO_Reader * infile, int count, void * field_in[], QudaPrecision cpu_prec)
Definition at line 86 of file qio_field.cpp.
References get_prec(), printfQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by read_spinor_field().
read_field() [2/2]
int read_field (QIO_Reader * infile, int Ninternal, int count, void * field_in[], QudaPrecision cpu_prec)
Definition at line 179 of file qio_field.cpp.
References quda::count, cpu_prec, and errorQuda.
read_gauge_field()
void read_gauge_field (const char * filename, void * gauge[], QudaPrecision precision, const int * X, int argc, char * argv[])
Definition at line 157 of file qio_field.cpp.
References errorQuda, open_test_input(), printfQuda, read_su3_field(), set_layout(), and this_node.
read_spinor_field()
void read_spinor_field (const char * filename, void * V[], QudaPrecision precision, const int * X, int nColor, int nSpin, int Nvec, int argc, char * argv[])
Definition at line 198 of file qio_field.cpp.
References errorQuda, open_test_input(), printfQuda, read_field(), set_layout(), and this_node.
read_su3_field()
int read_su3_field (QIO_Reader * infile, int count, void * field_in[], QudaPrecision cpu_prec)
Definition at line 124 of file qio_field.cpp.
References quda::count, and cpu_prec.
Referenced by read_gauge_field().
set_layout()
void set_layout (const int * X)
Definition at line 129 of file qio_field.cpp.
References comm_dim(), errorQuda, get_coords(), lattice_dim, lattice_size, layout, node_index(), node_number(), num_sites(), printfQuda, setup_layout(), sites_on_node, and this_node.
Referenced by read_gauge_field(), read_spinor_field(), write_gauge_field(), and write_spinor_field().
write_field() [1/2]
template<int len> int write_field (QIO_Writer * outfile, int count, void * field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, int nSpin, int nColor, const char * type)
Definition at line 220 of file qio_field.cpp.
References errorQuda, lattice_size, printfQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by write_spinor_field().
write_field() [2/2]
int write_field (QIO_Writer * outfile, int Ninternal, int count, void * field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, int nSpin, int nColor, const char * type)
Definition at line 305 of file qio_field.cpp.
References quda::count, cpu_prec, errorQuda, and nColor.
write_gauge_field()
void write_gauge_field (const char * filename, void * gauge[], QudaPrecision precision, const int * X, int argc, char * argv[])
Definition at line 278 of file qio_field.cpp.
References errorQuda, open_test_output(), printfQuda, QUDA_DOUBLE_PRECISION, set_layout(), this_node, and write_su3_field().
write_spinor_field()
void write_spinor_field (const char * filename, void * V[], QudaPrecision precision, const int * X, int nColor, int nSpin, int Nvec, int argc, char * argv[])
Definition at line 326 of file qio_field.cpp.
References errorQuda, open_test_output(), printfQuda, QUDA_DOUBLE_PRECISION, set_layout(), this_node, and write_field().
write_su3_field()
int write_su3_field (QIO_Writer * outfile, int count, void * field_out[], QudaPrecision file_prec, QudaPrecision cpu_prec, const char * type)
Definition at line 272 of file qio_field.cpp.
References quda::count, and cpu_prec.
Referenced by write_gauge_field().
Variable Documentation
lattice_dim
int lattice_dim
Definition at line 7 of file qio_field.cpp.
Referenced by set_layout().
lattice_size
int lattice_size[4]
Definition at line 8 of file qio_field.cpp.
Referenced by set_layout(), vfill_m(), vset_M(), and write_field().
layout
QIO_Layout layout
Definition at line 6 of file qio_field.cpp.
Referenced by open_test_input(), open_test_output(), and set_layout().
this_node
int this_node
Definition at line 9 of file qio_field.cpp.
Referenced by get_coords(), open_test_input(), open_test_output(), read_gauge_field(), read_spinor_field(), set_layout(), setup_hyper_prime(), vcompare_M(), vcreate_M(), vset_M(), write_gauge_field(), and write_spinor_field().