QUDA: include/qio_field.h File Reference
qio_field.h File Reference
Functions
void read_gauge_field (const char *filename, void *gauge[], QudaPrecision prec, const int *X, int argc, char *argv[])
void write_gauge_field (const char *filename, void *gauge[], QudaPrecision prec, const int *X, int argc, char *argv[])
void read_spinor_field (const char *filename, void *V[], QudaPrecision precision, const int *X, int nColor, int nSpin, int Nvec, int argc, char *argv[])
void write_spinor_field (const char *filename, void *V[], QudaPrecision precision, const int *X, int nColor, int nSpin, int Nvec, int argc, char *argv[])
Function Documentation
read_gauge_field()
void read_gauge_field (const char * filename, void * gauge[], QudaPrecision prec, const int * X, int argc, char * argv[]) inline
Definition at line 14 of file qio_field.h.
Referenced by eigensolve_test(), init(), invert_test(), main(), plaq_test(), and SU3test().
read_spinor_field()
void read_spinor_field (const char * filename, void * V[], QudaPrecision precision, const int * X, int nColor, int nSpin, int Nvec, int argc, char * argv[]) inline
Definition at line 24 of file qio_field.h.
Referenced by quda::Deflation::loadVectors(), and quda::EigenSolver::loadVectors().
write_gauge_field()
void write_gauge_field (const char * filename, void * gauge[], QudaPrecision prec, const int * X, int argc, char * argv[]) inline
Definition at line 19 of file qio_field.h.
Referenced by main().
write_spinor_field()
void write_spinor_field (const char * filename, void * V[], QudaPrecision precision, const int * X, int nColor, int nSpin, int Nvec, int argc, char * argv[]) inline
Definition at line 29 of file qio_field.h.
Referenced by quda::Deflation::saveVectors(), and quda::EigenSolver::saveVectors().