QUDA: tests/staggered_gauge_utils.cpp File Reference
staggered_gauge_utils.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <test_util.h>
#include <quda_internal.h>
#include <quda.h>
#include <util_quda.h>
#include <staggered_gauge_utils.h>
#include <llfat_reference.h>
#include <unitarization_links.h>
#include "misc.h"
Functions
void computeHISQLinksGPU (void **qdp_fatlink, void **qdp_longlink, void **qdp_fatlink_eps, void **qdp_longlink_eps, void **qdp_inlink, QudaGaugeParam &gauge_param_in, double **act_path_coeffs, double eps_naik, size_t gSize, int n_naiks)
void setActionPaths (double **act_paths)
void computeFatLongGPU (void **qdp_fatlink, void **qdp_longlink, void **qdp_inlink, QudaGaugeParam &gauge_param, size_t gSize, int n_naiks, double eps_naik)
void computeFatLongGPUandCPU (void **qdp_fatlink_gpu, void **qdp_longlink_gpu, void **qdp_fatlink_cpu, void **qdp_longlink_cpu, void **qdp_inlink, QudaGaugeParam &gauge_param, size_t gSize, int n_naiks, double eps_naik)
void computeStaggeredPlaquetteQDPOrder (void **qdp_link, double plaq[3], const QudaGaugeParam &gauge_param_in, const QudaDslashType dslash_type)
Variables
double tadpole_factor
static double unitarize_eps = 1e-6
static bool reunit_allow_svd = true
static bool reunit_svd_only = false
static double svd_rel_error = 1e-4
static double svd_abs_error = 1e-4
static double max_allowed_error = 1e-11
Function Documentation
computeFatLongGPU()
void computeFatLongGPU (void ** qdp_fatlink, void ** qdp_longlink, void ** qdp_inlink, QudaGaugeParam & gauge_param, size_t gSize, int n_naiks, double eps_naik)
Definition at line 162 of file staggered_gauge_utils.cpp.
References computeHISQLinksGPU(), gaugeSiteSize, setActionPaths(), and V.
Referenced by eigensolve_test(), and invert_test().
computeFatLongGPUandCPU()
void computeFatLongGPUandCPU (void ** qdp_fatlink_gpu, void ** qdp_longlink_gpu, void ** qdp_fatlink_cpu, void ** qdp_longlink_cpu, void ** qdp_inlink, QudaGaugeParam & gauge_param, size_t gSize, int n_naiks, double eps_naik)
Definition at line 210 of file staggered_gauge_utils.cpp.
References computeHISQLinksCPU(), computeHISQLinksGPU(), gaugeSiteSize, memset(), setActionPaths(), and V.
Referenced by init().
computeHISQLinksGPU()
void computeHISQLinksGPU (void ** qdp_fatlink, void ** qdp_longlink, void ** qdp_fatlink_eps, void ** qdp_longlink_eps, void ** qdp_inlink, QudaGaugeParam & gauge_param_in, double ** act_path_coeffs, double eps_naik, size_t gSize, int n_naiks)
Definition at line 25 of file staggered_gauge_utils.cpp.
References computeKSLinkQuda(), cpu_axy(), QudaGaugeParam_s::cpu_prec, cpu_xpy(), gauge_param, gaugeSiteSize, host_free, memset(), pinned_malloc, QUDA_RECONSTRUCT_NO, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, reorderMILCtoQDP(), reorderQDPtoMILC(), and V.
Referenced by computeFatLongGPU(), and computeFatLongGPUandCPU().
computeStaggeredPlaquetteQDPOrder()
void computeStaggeredPlaquetteQDPOrder (void ** qdp_link, double plaq[3], const QudaGaugeParam & gauge_param_in, const QudaDslashType dslash_type)
Definition at line 283 of file staggered_gauge_utils.cpp.
References QudaGaugeParam_s::anisotropy, QudaGaugeParam_s::cpu_prec, QudaGaugeParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, errorQuda, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, gauge_param, loadGaugeQuda(), newQudaGaugeParam(), plaqQuda(), QUDA_ANTI_PERIODIC_T, QUDA_ASQTAD_DSLASH, QUDA_GAUGE_FIXED_NO, QUDA_LAPLACE_DSLASH, QUDA_QDP_GAUGE_ORDER, QUDA_STAGGERED_DSLASH, QUDA_WILSON_LINKS, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, QudaGaugeParam_s::t_boundary, QudaGaugeParam_s::type, and QudaGaugeParam_s::X.
Referenced by eigensolve_test(), and invert_test().
setActionPaths()
void setActionPaths (double ** act_paths)
Definition at line 102 of file staggered_gauge_utils.cpp.
References max_allowed_error, reunit_allow_svd, reunit_svd_only, quda::setUnitarizeLinksConstants(), svd_abs_error, svd_rel_error, tadpole_factor, and unitarize_eps.
Referenced by computeFatLongGPU(), and computeFatLongGPUandCPU().
Variable Documentation
max_allowed_error
double max_allowed_error = 1e-11 static
Definition at line 22 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().
reunit_allow_svd
bool reunit_allow_svd = true static
Definition at line 18 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().
reunit_svd_only
bool reunit_svd_only = false static
Definition at line 19 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().
svd_abs_error
double svd_abs_error = 1e-4 static
Definition at line 21 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().
svd_rel_error
double svd_rel_error = 1e-4 static
Definition at line 20 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().
tadpole_factor
double tadpole_factor
Definition at line 1651 of file test_util.cpp.
Referenced by setActionPaths().
unitarize_eps
double unitarize_eps = 1e-6 static
Definition at line 17 of file staggered_gauge_utils.cpp.
Referenced by setActionPaths().