QUDA: tests/staggered_gauge_utils.h File Reference
staggered_gauge_utils.h File Reference
#include <blas_reference.h>
#include <quda_internal.h>
#include "color_spinor_field.h"
Functions
void setDims (int *)
void computeHISQLinksGPU (void **qdp_fatlink, void **qdp_longlink, void **qdp_fatlink_eps, void **qdp_longlink_eps, void **qdp_inlink, QudaGaugeParam &gauge_param, double **act_path_coeffs, double eps_naik, size_t gSize, int n_naiks)
void computeFatLongGPU (void **qdp_fatlink, void **qdp_longlink, void **qdp_inlink, QudaGaugeParam &gauge_param, size_t gSize, int n_naiks, double eps_naik)
void computeFatLongGPUandCPU (void **qdp_fatlink_gpu, void **qdp_longlink_gpu, void **qdp_fatlink_cpu, void **qdp_longlink_cpu, void **qdp_inlink, QudaGaugeParam &gauge_param, size_t gSize, int n_naiks, double eps_naik)
void computeStaggeredPlaquetteQDPOrder (void **qdp_link, double plaq[3], const QudaGaugeParam &gauge_param_in, const QudaDslashType dslash_type)
Variables
int Z [4]
int Vh
int V
Function Documentation
computeFatLongGPU()
void computeFatLongGPU (void ** qdp_fatlink, void ** qdp_longlink, void ** qdp_inlink, QudaGaugeParam & gauge_param, size_t gSize, int n_naiks, double eps_naik)
Definition at line 162 of file staggered_gauge_utils.cpp.
References computeHISQLinksGPU(), gaugeSiteSize, setActionPaths(), and V.
Referenced by eigensolve_test(), and invert_test().
computeFatLongGPUandCPU()
void computeFatLongGPUandCPU (void ** qdp_fatlink_gpu, void ** qdp_longlink_gpu, void ** qdp_fatlink_cpu, void ** qdp_longlink_cpu, void ** qdp_inlink, QudaGaugeParam & gauge_param, size_t gSize, int n_naiks, double eps_naik)
Definition at line 210 of file staggered_gauge_utils.cpp.
References computeHISQLinksCPU(), computeHISQLinksGPU(), gaugeSiteSize, memset(), setActionPaths(), and V.
Referenced by init().
computeHISQLinksGPU()
void computeHISQLinksGPU (void ** qdp_fatlink, void ** qdp_longlink, void ** qdp_fatlink_eps, void ** qdp_longlink_eps, void ** qdp_inlink, QudaGaugeParam & gauge_param, double ** act_path_coeffs, double eps_naik, size_t gSize, int n_naiks)
Definition at line 25 of file staggered_gauge_utils.cpp.
References computeKSLinkQuda(), cpu_axy(), QudaGaugeParam_s::cpu_prec, cpu_xpy(), gauge_param, gaugeSiteSize, host_free, memset(), pinned_malloc, QUDA_RECONSTRUCT_NO, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, reorderMILCtoQDP(), reorderQDPtoMILC(), and V.
Referenced by computeFatLongGPU(), and computeFatLongGPUandCPU().
computeStaggeredPlaquetteQDPOrder()
void computeStaggeredPlaquetteQDPOrder (void ** qdp_link, double plaq[3], const QudaGaugeParam & gauge_param_in, const QudaDslashType dslash_type)
Definition at line 283 of file staggered_gauge_utils.cpp.
References QudaGaugeParam_s::anisotropy, QudaGaugeParam_s::cpu_prec, QudaGaugeParam_s::cuda_prec, QudaGaugeParam_s::cuda_prec_sloppy, errorQuda, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, gauge_param, loadGaugeQuda(), newQudaGaugeParam(), plaqQuda(), QUDA_ANTI_PERIODIC_T, QUDA_ASQTAD_DSLASH, QUDA_GAUGE_FIXED_NO, QUDA_LAPLACE_DSLASH, QUDA_QDP_GAUGE_ORDER, QUDA_STAGGERED_DSLASH, QUDA_WILSON_LINKS, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, QudaGaugeParam_s::t_boundary, QudaGaugeParam_s::type, and QudaGaugeParam_s::X.
Referenced by eigensolve_test(), and invert_test().
setDims()
void setDims (int *)
Definition at line 151 of file test_util.cpp.
Variable Documentation
V
int V
Definition at line 27 of file test_util.cpp.
Vh
int Vh
Definition at line 28 of file test_util.cpp.
Z
int Z[4]
Definition at line 26 of file test_util.cpp.