QUDA: quda::dslash::DslashFactory< Dslash > Struct Template Reference
quda::dslash::DslashFactory< Dslash > Struct Template Reference
Static Public Member Functions
static DslashPolicyImp< Dslash > * create (const QudaDslashPolicy &dslashPolicy)
Detailed Description
template<typename Dslash>
struct quda::dslash::DslashFactory< Dslash >
Definition at line 1705 of file dslash_policy.cuh.
Member Function Documentation
create()
template<typename Dslash > static DslashPolicyImp<Dslash>* quda::dslash::DslashFactory< Dslash >::create (const QudaDslashPolicy & dslashPolicy) inline static
Definition at line 1707 of file dslash_policy.cuh.
References comm_gdr_blacklist(), errorQuda, quda::dslash::QUDA_DSLASH, quda::dslash::QUDA_DSLASH_ASYNC, quda::dslash::QUDA_DSLASH_NC, quda::dslash::QUDA_FUSED_DSLASH, quda::dslash::QUDA_FUSED_DSLASH_ASYNC, quda::dslash::QUDA_FUSED_GDR_DSLASH, quda::dslash::QUDA_FUSED_GDR_RECV_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_DSLASH, quda::dslash::QUDA_FUSED_ZERO_COPY_PACK_GDR_RECV_DSLASH, quda::dslash::QUDA_GDR_DSLASH, quda::dslash::QUDA_GDR_RECV_DSLASH, quda::dslash::QUDA_ZERO_COPY_DSLASH, quda::dslash::QUDA_ZERO_COPY_PACK_DSLASH, and quda::dslash::QUDA_ZERO_COPY_PACK_GDR_RECV_DSLASH.
Referenced by quda::dslash::DslashPolicyTune< Dslash >::apply(), and quda::dslash::DslashPolicyTune< Dslash >::DslashPolicyTune().
The documentation for this struct was generated from the following file:
lib/dslash_policy.cuh