QUDA: quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN > Struct Template Reference
quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN > Struct Template Reference
Public Member Functions
cabxpyzaxnorm (const Float2 &a, const Float2 &b)
__device__ __host__ void operator() (ReduceType &sum, FloatN &x, FloatN &y, FloatN &z, FloatN &w, FloatN &v)
where the reduction is usually computed and any auxiliary operations
Public Member Functions inherited from quda::blas::ReduceFunctor< ReduceType, Float2, FloatN >
virtual __device__ __host__ void pre ()
pre-computation routine called before the "M-loop"
virtual __device__ __host__ void post (ReduceType &sum)
post-computation routine called after the "M-loop"
Static Public Member Functions
static int streams ()
static int flops ()
total number of input and output streams
Public Attributes
Float2 a
Float2 b
Detailed Description
template<typename ReduceType, typename Float2, typename FloatN>
struct quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >
double cabxpyzAxNorm(float a, complex b, float *x, float *y, float *z){} First performs the operation z[i] = y[i] + a*b*x[i] Second performs x[i] *= a Third returns the norm of x
Definition at line 302 of file reduce_core.cuh.
Constructor & Destructor Documentation
cabxpyzaxnorm()
template<typename ReduceType , typename Float2 , typename FloatN > quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::cabxpyzaxnorm (const Float2 & a, const Float2 & b) inline
Definition at line 305 of file reduce_core.cuh.
Member Function Documentation
flops()
template<typename ReduceType , typename Float2 , typename FloatN > static int quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::flops () inline static
total number of input and output streams
Definition at line 314 of file reduce_core.cuh.
References quda::blas::cdot_().
operator()()
template<typename ReduceType , typename Float2 , typename FloatN > __device__ __host__ void quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::operator() (ReduceType & sum, FloatN & x, FloatN & y, FloatN & z, FloatN & w, FloatN & v) inline virtual
where the reduction is usually computed and any auxiliary operations
Implements quda::blas::ReduceFunctor< ReduceType, Float2, FloatN >.
Definition at line 306 of file reduce_core.cuh.
References quda::blas::Caxpy_(), and quda::sum().
streams()
template<typename ReduceType , typename Float2 , typename FloatN > static int quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::streams () inline static
Definition at line 313 of file reduce_core.cuh.
Member Data Documentation
a
template<typename ReduceType , typename Float2 , typename FloatN > Float2 quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::a
Definition at line 303 of file reduce_core.cuh.
b
template<typename ReduceType , typename Float2 , typename FloatN > Float2 quda::blas::cabxpyzaxnorm< ReduceType, Float2, FloatN >::b
Definition at line 304 of file reduce_core.cuh.
The documentation for this struct was generated from the following file:
include/kernels/reduce_core.cuh