QUDA: quda::colorspinor::fieldorder_wrapper< Float, storeFloat > Struct Template Reference
quda::colorspinor::fieldorder_wrapper< Float, storeFloat > Struct Template Reference
fieldorder_wrapper is an internal class that is used to wrap instances of FieldOrder accessors, currying in the specific location on the field. This is used as a helper class for fixed-point accessors providing the necessary conversion and scaling when writing to a fixed-point field.
#include <color_spinor_field_order.h>
Public Member Functions
__device__ __host__ fieldorder_wrapper (complex< storeFloat > *v, int idx, Float scale, Float scale_inv)
fieldorder_wrapper constructor
__device__ __host__ Float real () const
__device__ __host__ Float imag () const
__device__ __host__ void real (const Float &a)
__device__ __host__ void imag (const Float &a)
__device__ __host__ complex< Float > operator- () const
negation operator
__device__ __host__ void operator= (const fieldorder_wrapper< Float, storeFloat > &a)
Assignment operator with fieldorder_wrapper instance as input.
template<typename theirFloat >
__device__ __host__ void operator= (const complex< theirFloat > &a)
Assignment operator with complex number instance as input.
template<typename theirFloat >
__device__ __host__ void operator= (const theirFloat &a)
Assignment operator with real number instance as input.
template<typename theirFloat >
__device__ __host__ void operator+= (const complex< theirFloat > &a)
Operator+= with complex number instance as input.
template<typename theirFloat >
__device__ __host__ void operator-= (const complex< theirFloat > &a)
Operator-= with complex number instance as input.
Public Attributes
complex< storeFloat > * v
const int idx
const Float scale
const Float scale_inv
Static Public Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
Detailed Description
template<typename Float, typename storeFloat>
struct quda::colorspinor::fieldorder_wrapper< Float, storeFloat >
fieldorder_wrapper is an internal class that is used to wrap instances of FieldOrder accessors, currying in the specific location on the field. This is used as a helper class for fixed-point accessors providing the necessary conversion and scaling when writing to a fixed-point field.
Definition at line 356 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
fieldorder_wrapper()
template<typename Float, typename storeFloat> __device__ __host__ quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::fieldorder_wrapper (complex< storeFloat > * v, int idx, Float scale, Float scale_inv) inline
fieldorder_wrapper constructor
Parameters
idx Field index
Definition at line 367 of file color_spinor_field_order.h.
Member Function Documentation
imag() [1/2]
template<typename Float, typename storeFloat> __device__ __host__ Float quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::imag () const inline
Definition at line 378 of file color_spinor_field_order.h.
Referenced by quda::complex< double >::complex(), quda::complex< float >::complex(), quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator=(), quda::complex< double >::operator=(), and quda::complex< float >::operator=().
imag() [2/2]
template<typename Float, typename storeFloat> __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::imag (const Float & a) inline
Definition at line 393 of file color_spinor_field_order.h.
operator+=()
template<typename Float, typename storeFloat> template<typename theirFloat > __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator+= (const complex< theirFloat > & a) inline
Operator+= with complex number instance as input.
Parameters
a Complex number we want to add to this accessor
Definition at line 442 of file color_spinor_field_order.h.
operator-()
template<typename Float, typename storeFloat> __device__ __host__ complex<Float> quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator- () const inline
negation operator
Returns
negation of this complex number
Definition at line 405 of file color_spinor_field_order.h.
operator-=()
template<typename Float, typename storeFloat> template<typename theirFloat > __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator-= (const complex< theirFloat > & a) inline
Operator-= with complex number instance as input.
Parameters
a Complex number we want to subtract from this accessor
Definition at line 455 of file color_spinor_field_order.h.
References nColor.
operator=() [1/3]
template<typename Float, typename storeFloat> __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator= (const fieldorder_wrapper< Float, storeFloat > & a) inline
Assignment operator with fieldorder_wrapper instance as input.
Parameters
a fieldorder_wrapper we are copying from
Definition at line 413 of file color_spinor_field_order.h.
References quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::idx, quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::imag(), quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::real(), and quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::v.
operator=() [2/3]
template<typename Float, typename storeFloat> template<typename theirFloat > __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator= (const complex< theirFloat > & a) inline
Assignment operator with complex number instance as input.
Parameters
a Complex number we want to store in this accessor
Definition at line 422 of file color_spinor_field_order.h.
operator=() [3/3]
template<typename Float, typename storeFloat> template<typename theirFloat > __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator= (const theirFloat & a) inline
Assignment operator with real number instance as input.
Parameters
a real number we want to store in this accessor
Definition at line 435 of file color_spinor_field_order.h.
real() [1/2]
template<typename Float, typename storeFloat> __device__ __host__ Float quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::real () const inline
Definition at line 370 of file color_spinor_field_order.h.
Referenced by quda::complex< double >::complex(), quda::complex< float >::complex(), quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator=(), quda::complex< double >::operator=(), and quda::complex< float >::operator=().
real() [2/2]
template<typename Float, typename storeFloat> __device__ __host__ void quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::real (const Float & a) inline
Definition at line 386 of file color_spinor_field_order.h.
Member Data Documentation
fixed
template<typename Float, typename storeFloat> constexpr bool quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::fixed = fixed_point<Float,storeFloat>() static
Definition at line 361 of file color_spinor_field_order.h.
idx
template<typename Float, typename storeFloat> const int quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::idx
Definition at line 358 of file color_spinor_field_order.h.
Referenced by quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator=().
scale
template<typename Float, typename storeFloat> const Float quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::scale
Definition at line 359 of file color_spinor_field_order.h.
scale_inv
template<typename Float, typename storeFloat> const Float quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::scale_inv
Definition at line 360 of file color_spinor_field_order.h.
v
template<typename Float, typename storeFloat> complex<storeFloat>* quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::v
Definition at line 357 of file color_spinor_field_order.h.
Referenced by quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::operator=().
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h