QUDA: quda::gauge::Reconstruct< 12, Float, ghostExchange_ > Struct Template Reference
quda::gauge::Reconstruct< 12, Float, ghostExchange_ > Struct Template Reference
Gauge reconstruct 12 helper where we reconstruct the third row from the cross product of the first two rows.
#include <gauge_field_order.h>
Public Types
using real = typename mapper< Float >::type
using complex = complex< real >
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< 12, Float, ghostExchange_ > &recon)
__device__ __host__ void Pack (real out[12], const complex in[9], int idx) const
template<typename I >
__device__ __host__ void Unpack (complex out[9], const real in[12], int idx, int dir, real phase, const I *X, const int *R) const
__device__ __host__ real getPhase (const complex in[9])
Public Attributes
const real anisotropy
const real tBoundary
const int firstTimeSliceBound
const int lastTimeSliceBound
const bool isFirstTimeSlice
const bool isLastTimeSlice
QudaGhostExchange ghostExchange
Detailed Description
template<typename Float, QudaGhostExchange ghostExchange_>
struct quda::gauge::Reconstruct< 12, Float, ghostExchange_ >
Gauge reconstruct 12 helper where we reconstruct the third row from the cross product of the first two rows.
Template Parameters
Float Storage format (e.g., double, float, short)
ghostExchange_ optional template the ghostExchange type to avoid the run-time overhead
Definition at line 1230 of file gauge_field_order.h.
Member Typedef Documentation
complex
template<typename Float , QudaGhostExchange ghostExchange_> using quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::complex = complex<real>
Definition at line 1232 of file gauge_field_order.h.
real
template<typename Float , QudaGhostExchange ghostExchange_> using quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::real = typename mapper<Float>::type
Definition at line 1231 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<typename Float , QudaGhostExchange ghostExchange_> quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::Reconstruct (const GaugeField & u) inline
Definition at line 1241 of file gauge_field_order.h.
Reconstruct() [2/2]
template<typename Float , QudaGhostExchange ghostExchange_> quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::Reconstruct (const Reconstruct< 12, Float, ghostExchange_ > & recon) inline
Definition at line 1252 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<typename Float , QudaGhostExchange ghostExchange_> __device__ __host__ real quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::getPhase (const complex in[9]) inline
Definition at line 1300 of file gauge_field_order.h.
Pack()
template<typename Float , QudaGhostExchange ghostExchange_> __device__ __host__ void quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::Pack (real out[12], const complex in[9], int idx) const inline
Definition at line 1263 of file gauge_field_order.h.
Referenced by quda::gauge::Reconstruct< 13, Float, ghostExchange_, stag_phase >::Pack().
Unpack()
template<typename Float , QudaGhostExchange ghostExchange_> template<typename I > __device__ __host__ void quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::Unpack (complex out[9], const real in[12], int idx, int dir, real phase, const I * X, const int * R) const inline
Definition at line 1273 of file gauge_field_order.h.
References anisotropy, quda::cmac(), quda::cmul(), quda::conj(), R, and X.
Member Data Documentation
anisotropy
template<typename Float , QudaGhostExchange ghostExchange_> const real quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::anisotropy
Definition at line 1233 of file gauge_field_order.h.
firstTimeSliceBound
template<typename Float , QudaGhostExchange ghostExchange_> const int quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::firstTimeSliceBound
Definition at line 1235 of file gauge_field_order.h.
ghostExchange
template<typename Float , QudaGhostExchange ghostExchange_> QudaGhostExchange quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::ghostExchange
Definition at line 1239 of file gauge_field_order.h.
isFirstTimeSlice
template<typename Float , QudaGhostExchange ghostExchange_> const bool quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::isFirstTimeSlice
Definition at line 1237 of file gauge_field_order.h.
isLastTimeSlice
template<typename Float , QudaGhostExchange ghostExchange_> const bool quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::isLastTimeSlice
Definition at line 1238 of file gauge_field_order.h.
lastTimeSliceBound
template<typename Float , QudaGhostExchange ghostExchange_> const int quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::lastTimeSliceBound
Definition at line 1236 of file gauge_field_order.h.
tBoundary
template<typename Float , QudaGhostExchange ghostExchange_> const real quda::gauge::Reconstruct< 12, Float, ghostExchange_ >::tBoundary
Definition at line 1234 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h