QUDA: quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase > Struct Template Reference
quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase > Struct Template Reference
Gauge reconstruct 9 helper where we reconstruct the gauge matrix from 8 packed elements (maximal compression) and include a non-trivial phase factor.
#include <gauge_field_order.h>
Public Types
using real = typename mapper< Float >::type
using complex = complex< real >
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< 9, Float, ghostExchange_, stag_phase > &recon)
__device__ __host__ real getPhase (const complex in[9]) const
__device__ __host__ void Pack (real out[8], const complex in[9], int idx) const
template<typename I >
__device__ __host__ void Unpack (complex out[9], const real in[8], int idx, int dir, real phase, const I *X, const int *R) const
Public Attributes
const Reconstruct< 8, Float, ghostExchange_ > reconstruct_8
const real scale
const real scale_inv
Detailed Description
template<typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase>
struct quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >
Gauge reconstruct 9 helper where we reconstruct the gauge matrix from 8 packed elements (maximal compression) and include a non-trivial phase factor.
Template Parameters
Float Storage format (e.g., double, float, short)
ghostExchange_ optional template the ghostExchange type to avoid the run-time overhead
Definition at line 1586 of file gauge_field_order.h.
Member Typedef Documentation
complex
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> using quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::complex = complex<real>
Definition at line 1588 of file gauge_field_order.h.
real
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> using quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::real = typename mapper<Float>::type
Definition at line 1587 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::Reconstruct (const GaugeField & u) inline
Definition at line 1593 of file gauge_field_order.h.
Reconstruct() [2/2]
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::Reconstruct (const Reconstruct< 9, Float, ghostExchange_, stag_phase > & recon) inline
Definition at line 1595 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> __device__ __host__ real quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::getPhase (const complex in[9]) const inline
Definition at line 1602 of file gauge_field_order.h.
References quda::arg(), quda::conj(), quda::getDeterminant(), quda::gauge_wrapper< Float, T >::phase, and QUDA_STAGGERED_PHASE_NO.
Pack()
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> __device__ __host__ void quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::Pack (real out[8], const complex in[9], int idx) const inline
Definition at line 1624 of file gauge_field_order.h.
References quda::cmul(), quda::gauge::Reconstruct< 8, Float, ghostExchange_ >::Pack(), and QUDA_STAGGERED_PHASE_NO.
Unpack()
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> template<typename I > __device__ __host__ void quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::Unpack (complex out[9], const real in[8], int idx, int dir, real phase, const I * X, const int * R) const inline
Definition at line 1644 of file gauge_field_order.h.
References quda::cmul(), quda::gauge_wrapper< Float, T >::phase, QUDA_STAGGERED_PHASE_NO, and quda::gauge::Reconstruct< 8, Float, ghostExchange_ >::Unpack().
Member Data Documentation
reconstruct_8
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> const Reconstruct<8, Float, ghostExchange_> quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::reconstruct_8
Definition at line 1589 of file gauge_field_order.h.
scale
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> const real quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::scale
Definition at line 1590 of file gauge_field_order.h.
scale_inv
template<typename Float , QudaGhostExchange ghostExchange_, QudaStaggeredPhase stag_phase> const real quda::gauge::Reconstruct< 9, Float, ghostExchange_, stag_phase >::scale_inv
Definition at line 1591 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h