QUDA: quda::StaggeredApply< Float, nColor, recon_u > Struct Template Reference
quda::StaggeredApply< Float, nColor, recon_u > Struct Template Reference
Public Member Functions
StaggeredApply (ColorSpinorField &out, const ColorSpinorField &in, const GaugeField &U, double a, const ColorSpinorField &x, int parity, bool dagger, const int *comm_override, TimeProfile &profile)
Detailed Description
template<typename Float, int nColor, QudaReconstructType recon_u>
struct quda::StaggeredApply< Float, nColor, recon_u >
Definition at line 65 of file dslash_staggered.cu.
Constructor & Destructor Documentation
StaggeredApply()
template<typename Float , int nColor, QudaReconstructType recon_u> quda::StaggeredApply< Float, nColor, recon_u >::StaggeredApply (ColorSpinorField & out, const ColorSpinorField & in, const GaugeField & U, double a, const ColorSpinorField & x, int parity, bool dagger, const int * comm_override, TimeProfile & profile) inline
Definition at line 67 of file dslash_staggered.cu.
References quda::dslash::DslashPolicyTune< Dslash >::apply(), quda::arg(), checkCudaError, errorQuda, quda::ColorSpinorField::GhostFaceCB(), QUDA_STAGGERED_PHASE_MILC, QUDA_STAGGERED_PHASE_TIFR, quda::staggered(), quda::GaugeField::StaggeredPhase(), and quda::ColorSpinorField::VolumeCB().
The documentation for this struct was generated from the following file:
lib/dslash_staggered.cu