QUDA: quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex > Struct Template Reference
quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
GhostAccessor (const GaugeField &U, void *gauge_, void **ghost_=0)
GhostAccessor (const GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex > &a)
void resetScale (Float max)
__device__ __host__ const complex< Float > operator() (int d, int parity, int x_cb, int row, int col) const
__device__ __host__ fieldorder_wrapper< Float, storeFloat > operator() (int d, int parity, int x_cb, int row, int col)
Public Attributes
complex< storeFloat > * ghost [8]
const int volumeCB
int ghostVolumeCB [8]
Float scale
Float scale_inv
Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex > accessor
Static Public Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
Detailed Description
template<typename Float, int nColor, bool native_ghost, typename storeFloat, bool use_tex>
struct quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >
Definition at line 817 of file gauge_field_order.h.
Constructor & Destructor Documentation
GhostAccessor() [1/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::GhostAccessor (const GaugeField & U, void * gauge_, void ** ghost_ = 0) inline
Definition at line 826 of file gauge_field_order.h.
References quda::GaugeField::Geometry(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, quda::LatticeField::Scale(), and quda::LatticeField::SurfaceCB().
GhostAccessor() [2/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::GhostAccessor (const GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex > & a) inline
Definition at line 840 of file gauge_field_order.h.
References ghost, and ghostVolumeCB.
Member Function Documentation
operator()() [1/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> __device__ __host__ const complex<Float> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::operator() (int d, int parity, int x_cb, int row, int col) const inline
Definition at line 857 of file gauge_field_order.h.
References nColor, tmp, and quda::gauge_wrapper< Float, T >::x_cb.
operator()() [2/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> __device__ __host__ fieldorder_wrapper<Float,storeFloat> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::operator() (int d, int parity, int x_cb, int row, int col) inline
Definition at line 871 of file gauge_field_order.h.
References nColor, and quda::gauge_wrapper< Float, T >::x_cb.
resetScale()
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> void quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::resetScale (Float max) inline
Definition at line 849 of file gauge_field_order.h.
References quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::resetScale().
Member Data Documentation
accessor
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> Accessor<Float,nColor,QUDA_FLOAT2_GAUGE_ORDER,storeFloat,use_tex> quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::accessor
Definition at line 824 of file gauge_field_order.h.
fixed
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> constexpr bool quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::fixed = fixed_point<Float,storeFloat>() static
Definition at line 823 of file gauge_field_order.h.
ghost
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> complex<storeFloat>* quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::ghost[8]
Definition at line 818 of file gauge_field_order.h.
Referenced by GhostAccessor().
ghostVolumeCB
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> int quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::ghostVolumeCB[8]
Definition at line 820 of file gauge_field_order.h.
Referenced by GhostAccessor().
scale
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> Float quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::scale
Definition at line 821 of file gauge_field_order.h.
scale_inv
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> Float quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::scale_inv
Definition at line 822 of file gauge_field_order.h.
volumeCB
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> const int quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::volumeCB
Definition at line 819 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h