QUDA: quda::dslash::DslashBasic< Dslash > Struct Template Reference
quda::dslash::DslashBasic< Dslash > Struct Template Reference
Public Member Functions
void operator() (Dslash &dslash, cudaColorSpinorField *in, const int volume, const int *faceVolumeCB, TimeProfile &profile)
Public Member Functions inherited from quda::dslash::DslashPolicyImp< Dslash >
virtual ~DslashPolicyImp ()
Detailed Description
template<typename Dslash>
struct quda::dslash::DslashBasic< Dslash >
Standard dslash parallelization with host staging for send and receive
Definition at line 365 of file dslash_policy.cuh.
Member Function Documentation
operator()()
template<typename Dslash > void quda::dslash::DslashBasic< Dslash >::operator() (Dslash & dslash, cudaColorSpinorField * in, const int volume, const int * faceVolumeCB, TimeProfile & profile) inline virtual
Implements quda::dslash::DslashPolicyImp< Dslash >.
Definition at line 367 of file dslash_policy.cuh.
References quda::Worker::apply(), quda::Tunable::apply(), quda::LatticeField::bufferIndex, comm_peer2peer_enabled(), quda::dslash::DslashCommsPattern::commDimTotal, quda::dslash::commsComplete(), quda::dslash::DslashCommsPattern::commsCompleted, quda::dslash::completeDslash(), quda::dslash::DslashCommsPattern::completeSum, quda::Dslash< Float >::Dagger(), quda::Device, quda::dslash::DslashCommsPattern::dslashCompleted, quda::Dslash< Float >::dslashParam, quda::dslash::DslashCommsPattern::gatherCompleted, quda::getKernelPackT(), quda::INTERIOR_KERNEL, quda::dslash::issueGather(), quda::dslash::issuePack(), quda::dslash::issueRecv(), quda::Dslash< Float >::Nface(), quda::Nstream, quda::dslash::DslashCommsPattern::previousDir, PROFILE, QUDA_PARITY_SITE_SUBSET, quda::QUDA_PROFILE_COMMS_START, quda::QUDA_PROFILE_DSLASH_KERNEL, quda::QUDA_PROFILE_EVENT_QUERY, quda::QUDA_PROFILE_EVENT_RECORD, quda::QUDA_PROFILE_STREAM_WAIT_EVENT, quda::QUDA_PROFILE_TOTAL, quda::qudaEventQuery(), quda::qudaEventRecord(), quda::qudaStreamWaitEvent(), quda::Remote, quda::cudaColorSpinorField::sendStart(), quda::ColorSpinorField::SiteSubset(), and streams.
The documentation for this struct was generated from the following file:
lib/dslash_policy.cuh