QUDA: quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex > Struct Template Reference
quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
GhostAccessor (const GaugeField &U, void *gauge_=0, void **ghost_=0)
GhostAccessor (const GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex > &a)
void resetScale (Float max)
__device__ __host__ complex< Float > operator() (int d, int parity, int x, int row, int col) const
__device__ __host__ fieldorder_wrapper< Float, storeFloat > operator() (int d, int parity, int x, int row, int col)
Public Attributes
complex< storeFloat > * ghost [8]
int ghostOffset [8]
Float scale
Float scale_inv
Static Public Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
Detailed Description
template<typename Float, int nColor, bool native_ghost, typename storeFloat, bool use_tex>
struct quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >
Definition at line 619 of file gauge_field_order.h.
Constructor & Destructor Documentation
GhostAccessor() [1/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::GhostAccessor (const GaugeField & U, void * gauge_ = 0, void ** ghost_ = 0) inline
Definition at line 626 of file gauge_field_order.h.
References quda::GaugeField::Geometry(), quda::GaugeField::Ghost(), quda::GaugeField::Ncolor(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, quda::LatticeField::Scale(), and quda::LatticeField::SurfaceCB().
GhostAccessor() [2/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::GhostAccessor (const GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex > & a) inline
Definition at line 642 of file gauge_field_order.h.
References ghost, and ghostOffset.
Member Function Documentation
operator()() [1/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> __device__ __host__ complex<Float> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::operator() (int d, int parity, int x, int row, int col) const inline
Definition at line 657 of file gauge_field_order.h.
References nColor, and tmp.
operator()() [2/2]
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> __device__ __host__ fieldorder_wrapper<Float,storeFloat> quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::operator() (int d, int parity, int x, int row, int col) inline
Definition at line 667 of file gauge_field_order.h.
References nColor.
resetScale()
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> void quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::resetScale (Float max) inline
Definition at line 650 of file gauge_field_order.h.
Member Data Documentation
fixed
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> constexpr bool quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::fixed = fixed_point<Float,storeFloat>() static
Definition at line 624 of file gauge_field_order.h.
ghost
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> complex<storeFloat>* quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::ghost[8]
Definition at line 620 of file gauge_field_order.h.
Referenced by GhostAccessor().
ghostOffset
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> int quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::ghostOffset[8]
Definition at line 621 of file gauge_field_order.h.
Referenced by GhostAccessor().
scale
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> Float quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::scale
Definition at line 622 of file gauge_field_order.h.
scale_inv
template<typename Float , int nColor, bool native_ghost, typename storeFloat , bool use_tex> Float quda::gauge::GhostAccessor< Float, nColor, QUDA_MILC_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::scale_inv
Definition at line 623 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h