QUDA: quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex > Struct Template Reference
quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
Accessor (const GaugeField &U, void *gauge_=0, void **ghost_=0, bool override=false)
Accessor (const Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex > &a)
void resetScale (Float max_)
__device__ __host__ const complex< Float > operator() (int dim, int parity, int x_cb, int row, int col) const
__device__ __host__ fieldorder_wrapper< Float, storeFloat > operator() (int dim, int parity, int x_cb, int row, int col)
template<typename theirFloat >
__device__ __host__ void atomic_add (int dim, int parity, int x_cb, int row, int col, const complex< theirFloat > &val) const
template<typename helper , typename reducer >
__host__ double transform_reduce (QudaFieldLocation location, int dim, helper h, reducer r, double init) const
Public Attributes
complex< storeFloat > * u
const int offset_cb
const int volumeCB
const int stride
const int geometry
Float max
Float scale
Float scale_inv
Static Public Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
Detailed Description
template<typename Float, int nColor, typename storeFloat, bool use_tex>
struct quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >
Definition at line 683 of file gauge_field_order.h.
Constructor & Destructor Documentation
Accessor() [1/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::Accessor (const GaugeField & U, void * gauge_ = 0, void ** ghost_ = 0, bool override = false) inline
Definition at line 698 of file gauge_field_order.h.
References errorQuda, quda::GaugeField::Gauge_p(), quda::LatticeField::Location(), QUDA_CUDA_FIELD_LOCATION, and quda::LatticeField::Scale().
Accessor() [2/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::Accessor (const Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex > & a) inline
Definition at line 717 of file gauge_field_order.h.
Member Function Documentation
atomic_add()
template<typename Float , int nColor, typename storeFloat , bool use_tex> template<typename theirFloat > __device__ __host__ void quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::atomic_add (int dim, int parity, int x_cb, int row, int col, const complex< theirFloat > & val) const inline
Definition at line 762 of file gauge_field_order.h.
References atomicAdd(), nColor, and quda::gauge_wrapper< Float, T >::x_cb.
operator()() [1/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> __device__ __host__ const complex<Float> quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::operator() (int dim, int parity, int x_cb, int row, int col) const inline
Definition at line 733 of file gauge_field_order.h.
References nColor, and tmp.
operator()() [2/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> __device__ __host__ fieldorder_wrapper<Float,storeFloat> quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::operator() (int dim, int parity, int x_cb, int row, int col) inline
Definition at line 755 of file gauge_field_order.h.
References index(), and nColor.
resetScale()
template<typename Float , int nColor, typename storeFloat , bool use_tex> void quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::resetScale (Float max_) inline
Definition at line 725 of file gauge_field_order.h.
Referenced by quda::gauge::GhostAccessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, native_ghost, storeFloat, use_tex >::resetScale().
transform_reduce()
template<typename Float , int nColor, typename storeFloat , bool use_tex> template<typename helper , typename reducer > __host__ double quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::transform_reduce (QudaFieldLocation location, int dim, helper h, reducer r, double init) const inline
Definition at line 789 of file gauge_field_order.h.
References quda::alloc, errorQuda, quda::cublas::init(), nColor, and QUDA_CUDA_FIELD_LOCATION.
Member Data Documentation
fixed
template<typename Float , int nColor, typename storeFloat , bool use_tex> constexpr bool quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::fixed = fixed_point<Float,storeFloat>() static
Definition at line 696 of file gauge_field_order.h.
geometry
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::geometry
Definition at line 692 of file gauge_field_order.h.
max
template<typename Float , int nColor, typename storeFloat , bool use_tex> Float quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::max
Definition at line 693 of file gauge_field_order.h.
offset_cb
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::offset_cb
Definition at line 685 of file gauge_field_order.h.
scale
template<typename Float , int nColor, typename storeFloat , bool use_tex> Float quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::scale
Definition at line 694 of file gauge_field_order.h.
scale_inv
template<typename Float , int nColor, typename storeFloat , bool use_tex> Float quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::scale_inv
Definition at line 695 of file gauge_field_order.h.
stride
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::stride
Definition at line 691 of file gauge_field_order.h.
u
template<typename Float , int nColor, typename storeFloat , bool use_tex> complex<storeFloat>* quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::u
Definition at line 684 of file gauge_field_order.h.
volumeCB
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_FLOAT2_GAUGE_ORDER, storeFloat, use_tex >::volumeCB
Definition at line 690 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h