QUDA: quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase > Struct Template Reference
quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase > Struct Template Reference
Generic reconstruction helper with no reconstruction.
#include <gauge_field_order.h>
Public Types
using real = typename mapper< Float >::type
using complex = complex< real >
Public Member Functions
Reconstruct (const GaugeField &u)
Reconstruct (const Reconstruct< N, Float, ghostExchange_ > &recon)
__device__ __host__ void Pack (real out[N], const complex in[N/2], int idx) const
template<typename I >
__device__ __host__ void Unpack (complex out[N/2], const real in[N], int idx, int dir, real phase, const I *X, const int *R) const
__device__ __host__ real getPhase (const complex in[N/2]) const
Public Attributes
real scale
real scale_inv
Detailed Description
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO>
struct quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >
Generic reconstruction helper with no reconstruction.
Template Parameters
N number of real numbers in each packed gauge matrix
Float Storage format (e.g., double, float, short)
ghostExchange_ optional template the ghostExchange type to avoid the run-time overhead (dummy for trivial reconstruct type)
Definition at line 1125 of file gauge_field_order.h.
Member Typedef Documentation
complex
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> using quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::complex = complex<real>
Definition at line 1127 of file gauge_field_order.h.
real
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> using quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::real = typename mapper<Float>::type
Definition at line 1126 of file gauge_field_order.h.
Constructor & Destructor Documentation
Reconstruct() [1/2]
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::Reconstruct (const GaugeField & u) inline
Definition at line 1130 of file gauge_field_order.h.
Reconstruct() [2/2]
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::Reconstruct (const Reconstruct< N, Float, ghostExchange_ > & recon) inline
Definition at line 1131 of file gauge_field_order.h.
Member Function Documentation
getPhase()
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> __device__ __host__ real quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::getPhase (const complex in[N/2]) const inline
Definition at line 1164 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::save(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::saveGhostEx().
Pack()
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> __device__ __host__ void quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::Pack (real out[N], const complex in[N/2], int idx) const inline
Definition at line 1135 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::save(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::saveGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::saveGhostEx().
Unpack()
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> template<typename I > __device__ __host__ void quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::Unpack (complex out[N/2], const real in[N], int idx, int dir, real phase, const I * X, const int * R) const inline
Definition at line 1153 of file gauge_field_order.h.
Referenced by quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::load(), quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::loadGhost(), and quda::gauge::FloatNOrder< Float, length, N, reconLenParam, stag_phase, huge_alloc, ghostExchange_, use_inphase >::loadGhostEx().
Member Data Documentation
scale
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> real quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::scale
Definition at line 1128 of file gauge_field_order.h.
scale_inv
template<int N, typename Float, QudaGhostExchange ghostExchange_, QudaStaggeredPhase = QUDA_STAGGERED_PHASE_NO> real quda::gauge::Reconstruct< N, Float, ghostExchange_, QudaStaggeredPhase >::scale_inv
Definition at line 1129 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h