QUDA: quda::complex< char > Struct Template Reference
quda::complex< char > Struct Template Reference
#include <complex_quda.h>
Public Types
typedef char value_type
Public Member Functions
__host__ __device__ complex ()
__host__ __device__ complex (const char &re, const char &im=float())
__host__ __device__ complex (const complex< char > &z)
__host__ __device__ complex< char > & operator+= (const complex< char > z)
__host__ __device__ complex< char > & operator-= (const complex< char > z)
__host__ __device__ char real () const volatile
__host__ __device__ char imag () const volatile
__host__ __device__ char real () const
__host__ __device__ char imag () const
__host__ __device__ void real (char re) volatile
__host__ __device__ void imag (char im) volatile
__host__ __device__ void real (char re)
__host__ __device__ void imag (char im)
operator std::complex< char > () const
template<typename T >
__host__ __device__ operator complex< T > () const
Detailed Description
template<>
struct quda::complex< char >
Definition at line 710 of file complex_quda.h.
Member Typedef Documentation
value_type
typedef char quda::complex< char >::value_type
Definition at line 713 of file complex_quda.h.
Constructor & Destructor Documentation
complex() [1/3]
__host__ __device__ quda::complex< char >::complex () inline
Definition at line 715 of file complex_quda.h.
complex() [2/3]
__host__ __device__ quda::complex< char >::complex (const char & re, const char & im = float()) inline
Definition at line 717 of file complex_quda.h.
complex() [3/3]
__host__ __device__ quda::complex< char >::complex (const complex< char > & z) inline
Definition at line 723 of file complex_quda.h.
Member Function Documentation
imag() [1/4]
__host__ __device__ char quda::complex< char >::imag () const volatile inline
Definition at line 740 of file complex_quda.h.
Referenced by quda::gauge::square_< ReduceType, char >::operator()(), quda::gauge::abs_< Float, char >::operator()(), quda::colorspinor::square_< ReduceType, char >::operator()(), quda::colorspinor::abs_< Float, char >::operator()(), operator+=(), and operator-=().
imag() [2/4]
__host__ __device__ char quda::complex< char >::imag () const inline
Definition at line 742 of file complex_quda.h.
imag() [3/4]
__host__ __device__ void quda::complex< char >::imag (char im) volatile inline
Definition at line 744 of file complex_quda.h.
imag() [4/4]
__host__ __device__ void quda::complex< char >::imag (char im) inline
Definition at line 746 of file complex_quda.h.
operator complex< T >()
template<typename T > __host__ __device__ quda::complex< char >::operator complex< T > () const inline
Definition at line 751 of file complex_quda.h.
operator std::complex< char >()
quda::complex< char >::operator std::complex< char > () const inline
Definition at line 749 of file complex_quda.h.
operator+=()
__host__ __device__ complex<char>& quda::complex< char >::operator+= (const complex< char > z) inline
Definition at line 725 of file complex_quda.h.
References imag(), and real().
operator-=()
__host__ __device__ complex<char>& quda::complex< char >::operator-= (const complex< char > z) inline
Definition at line 732 of file complex_quda.h.
References imag(), and real().
real() [1/4]
__host__ __device__ char quda::complex< char >::real () const volatile inline
Definition at line 739 of file complex_quda.h.
Referenced by quda::gauge::square_< ReduceType, char >::operator()(), quda::gauge::abs_< Float, char >::operator()(), quda::colorspinor::square_< ReduceType, char >::operator()(), quda::colorspinor::abs_< Float, char >::operator()(), operator+=(), and operator-=().
real() [2/4]
__host__ __device__ char quda::complex< char >::real () const inline
Definition at line 741 of file complex_quda.h.
real() [3/4]
__host__ __device__ void quda::complex< char >::real (char re) volatile inline
Definition at line 743 of file complex_quda.h.
real() [4/4]
__host__ __device__ void quda::complex< char >::real (char re) inline
Definition at line 745 of file complex_quda.h.
The documentation for this struct was generated from the following file:
include/complex_quda.h