QUDA: quda::gauge::LegacyOrder< Float, length > Struct Template Reference
quda::gauge::LegacyOrder< Float, length > Struct Template Reference
The LegacyOrder defines the ghost zone storage and ordering for all cpuGaugeFields, which use the same ghost zone storage.
#include <gauge_field_order.h>
Public Types
using Accessor = LegacyOrder< Float, length >
using real = typename mapper< Float >::type
using complex = complex< real >
Public Member Functions
LegacyOrder (const GaugeField &u, Float **ghost_)
LegacyOrder (const LegacyOrder &order)
__device__ __host__ void loadGhost (complex v[length/2], int x, int dir, int parity, real phase=1.0) const
__device__ __host__ void saveGhost (const complex v[length/2], int x, int dir, int parity)
__device__ __host__ gauge_ghost_wrapper< real, Accessor > Ghost (int dim, int ghost_idx, int parity, real phase=1.0)
This accessor routine returns a gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const gauge_ghost_wrapper< real, Accessor > Ghost (int dim, int ghost_idx, int parity, real phase=1.0) const
This accessor routine returns a const gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ void loadGhostEx (complex v[length/2], int x, int dummy, int dir, int dim, int g, int parity, const int R[]) const
__device__ __host__ void saveGhostEx (const complex v[length/2], int x, int dummy, int dir, int dim, int g, int parity, const int R[])
Public Attributes
Float * ghost [QUDA_MAX_DIM]
int faceVolumeCB [QUDA_MAX_DIM]
const int volumeCB
const int stride
const int geometry
const int hasPhase
Detailed Description
template<typename Float, int length>
struct quda::gauge::LegacyOrder< Float, length >
The LegacyOrder defines the ghost zone storage and ordering for all cpuGaugeFields, which use the same ghost zone storage.
Definition at line 2043 of file gauge_field_order.h.
Member Typedef Documentation
Accessor
template<typename Float , int length> using quda::gauge::LegacyOrder< Float, length >::Accessor = LegacyOrder<Float, length>
Definition at line 2044 of file gauge_field_order.h.
complex
template<typename Float , int length> using quda::gauge::LegacyOrder< Float, length >::complex = complex<real>
Definition at line 2046 of file gauge_field_order.h.
real
template<typename Float , int length> using quda::gauge::LegacyOrder< Float, length >::real = typename mapper<Float>::type
Definition at line 2045 of file gauge_field_order.h.
Constructor & Destructor Documentation
LegacyOrder() [1/2]
template<typename Float , int length> quda::gauge::LegacyOrder< Float, length >::LegacyOrder (const GaugeField & u, Float ** ghost_) inline
Definition at line 2054 of file gauge_field_order.h.
References errorQuda, quda::GaugeField::Ghost(), quda::GaugeField::Nface(), QUDA_COARSE_GEOMETRY, and quda::LatticeField::SurfaceCB().
LegacyOrder() [2/2]
template<typename Float , int length> quda::gauge::LegacyOrder< Float, length >::LegacyOrder (const LegacyOrder< Float, length > & order) inline
Definition at line 2069 of file gauge_field_order.h.
References quda::gauge::LegacyOrder< Float, length >::faceVolumeCB, and quda::gauge::LegacyOrder< Float, length >::ghost.
Member Function Documentation
Ghost() [1/2]
template<typename Float , int length> __device__ __host__ gauge_ghost_wrapper<real, Accessor> quda::gauge::LegacyOrder< Float, length >::Ghost (int dim, int ghost_idx, int parity, real phase = 1.0) inline
This accessor routine returns a gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] ghost_idx Ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_ghost_wrapper that curries in access to this field at the above coordinates.
Definition at line 2123 of file gauge_field_order.h.
References quda::gauge_wrapper< Float, T >::dim, quda::gauge_wrapper< Float, T >::parity, and quda::gauge_wrapper< Float, T >::phase.
Ghost() [2/2]
template<typename Float , int length> __device__ __host__ const gauge_ghost_wrapper<real, Accessor> quda::gauge::LegacyOrder< Float, length >::Ghost (int dim, int ghost_idx, int parity, real phase = 1.0) const inline
This accessor routine returns a const gauge_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dir Which dimension are we requesting
[in] ghost_idx Ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a gauge_ghost_wrapper that curries in access to this field at the above coordinates.
Definition at line 2139 of file gauge_field_order.h.
References quda::gauge_wrapper< Float, T >::dim, quda::gauge_wrapper< Float, T >::parity, and quda::gauge_wrapper< Float, T >::phase.
loadGhost()
template<typename Float , int length> __device__ __host__ void quda::gauge::LegacyOrder< Float, length >::loadGhost (complex v[length/2], int x, int dir, int parity, real phase = 1.0) const inline
Definition at line 2081 of file gauge_field_order.h.
loadGhostEx()
template<typename Float , int length> __device__ __host__ void quda::gauge::LegacyOrder< Float, length >::loadGhostEx (complex v[length/2], int x, int dummy, int dir, int dim, int g, int parity, const int R[]) const inline
Definition at line 2145 of file gauge_field_order.h.
References quda::gauge_wrapper< Float, T >::dim, and quda::gauge_wrapper< Float, T >::parity.
saveGhost()
template<typename Float , int length> __device__ __host__ void quda::gauge::LegacyOrder< Float, length >::saveGhost (const complex v[length/2], int x, int dir, int parity) inline
Definition at line 2093 of file gauge_field_order.h.
saveGhostEx()
template<typename Float , int length> __device__ __host__ void quda::gauge::LegacyOrder< Float, length >::saveGhostEx (const complex v[length/2], int x, int dummy, int dir, int dim, int g, int parity, const int R[]) inline
Definition at line 2158 of file gauge_field_order.h.
References quda::gauge_wrapper< Float, T >::dim, and quda::gauge_wrapper< Float, T >::parity.
Member Data Documentation
faceVolumeCB
template<typename Float , int length> int quda::gauge::LegacyOrder< Float, length >::faceVolumeCB[QUDA_MAX_DIM]
Definition at line 2048 of file gauge_field_order.h.
Referenced by quda::gauge::LegacyOrder< Float, length >::LegacyOrder().
geometry
template<typename Float , int length> const int quda::gauge::LegacyOrder< Float, length >::geometry
Definition at line 2051 of file gauge_field_order.h.
ghost
template<typename Float , int length> Float* quda::gauge::LegacyOrder< Float, length >::ghost[QUDA_MAX_DIM]
Definition at line 2047 of file gauge_field_order.h.
Referenced by quda::gauge::LegacyOrder< Float, length >::LegacyOrder().
hasPhase
template<typename Float , int length> const int quda::gauge::LegacyOrder< Float, length >::hasPhase
Definition at line 2052 of file gauge_field_order.h.
stride
template<typename Float , int length> const int quda::gauge::LegacyOrder< Float, length >::stride
Definition at line 2050 of file gauge_field_order.h.
volumeCB
template<typename Float , int length> const int quda::gauge::LegacyOrder< Float, length >::volumeCB
Definition at line 2049 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h