QUDA: quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec > Struct Template Reference
quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec > Struct Template Reference
Public Member Functions
template<typename... T>
BlockOrthoArg (ColorSpinorField &V, const int *fine_to_coarse, const int *coarse_to_fine, int parity, const int *geo_bs, const int n_block_ortho, const ColorSpinorField &meta, T... B)
Public Attributes
Rotator V
const int * fine_to_coarse
const int * coarse_to_fine
const spin_mapper< fineSpin, coarseSpin > spin_map
const int parity
const int nParity
const int nBlockOrtho
int coarseVolume
int fineVolumeCB
int geoBlockSizeCB
int_fastdiv swizzle
const Vector * B
Detailed Description
template<typename Rotator, typename Vector, int fineSpin, int spinBlockSize, int coarseSpin, int nVec>
struct quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >
Kernel argument struct
Definition at line 25 of file block_orthogonalize.cuh.
Constructor & Destructor Documentation
BlockOrthoArg()
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> template<typename... T> quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::BlockOrthoArg (ColorSpinorField & V, const int * fine_to_coarse, const int * coarse_to_fine, int parity, const int * geo_bs, const int n_block_ortho, const ColorSpinorField & meta, T... B) inline
Definition at line 39 of file block_orthogonalize.cuh.
References errorQuda, MAX_MATRIX_SIZE, quda::ColorSpinorField::Ndim(), quda::ColorSpinorField::Volume(), and quda::ColorSpinorField::VolumeCB().
Member Data Documentation
B
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const Vector* quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::B
Definition at line 37 of file block_orthogonalize.cuh.
Referenced by quda::__launch_bounds__().
coarse_to_fine
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const int* quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::coarse_to_fine
Definition at line 28 of file block_orthogonalize.cuh.
coarseVolume
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::coarseVolume
Definition at line 33 of file block_orthogonalize.cuh.
fine_to_coarse
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const int* quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::fine_to_coarse
Definition at line 27 of file block_orthogonalize.cuh.
fineVolumeCB
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::fineVolumeCB
Definition at line 34 of file block_orthogonalize.cuh.
geoBlockSizeCB
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::geoBlockSizeCB
Definition at line 35 of file block_orthogonalize.cuh.
nBlockOrtho
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::nBlockOrtho
Definition at line 32 of file block_orthogonalize.cuh.
nParity
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::nParity
Definition at line 31 of file block_orthogonalize.cuh.
parity
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const int quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::parity
Definition at line 30 of file block_orthogonalize.cuh.
Referenced by quda::__launch_bounds__(), and quda::blockOrthoCPU().
spin_map
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> const spin_mapper<fineSpin,coarseSpin> quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::spin_map
Definition at line 29 of file block_orthogonalize.cuh.
swizzle
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> int_fastdiv quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::swizzle
Definition at line 36 of file block_orthogonalize.cuh.
V
template<typename Rotator , typename Vector , int fineSpin, int spinBlockSize, int coarseSpin, int nVec> Rotator quda::BlockOrthoArg< Rotator, Vector, fineSpin, spinBlockSize, coarseSpin, nVec >::V
Definition at line 26 of file block_orthogonalize.cuh.
The documentation for this struct was generated from the following file:
include/kernels/block_orthogonalize.cuh