QUDA: quda::TwistedCloverPreconditionedLaunch< Float, nDim, nColor, nParity, dagger, xpay, kernel_type, Arg > Struct Template Reference
quda::TwistedCloverPreconditionedLaunch< Float, nDim, nColor, nParity, dagger, xpay, kernel_type, Arg > Struct Template Reference
This is a helper class that is used to instantiate the correct templated kernel for the dslash.
Static Public Member Functions
template<typename Dslash >
static void launch (Dslash &dslash, TuneParam &tp, Arg &arg, const cudaStream_t &stream)
Static Public Attributes
static constexpr const char * kernel = "quda::twistedCloverPreconditionedGPU"
Detailed Description
template<typename Float, int nDim, int nColor, int nParity, bool dagger, bool xpay, KernelType kernel_type, typename Arg>
struct quda::TwistedCloverPreconditionedLaunch< Float, nDim, nColor, nParity, dagger, xpay, kernel_type, Arg >
This is a helper class that is used to instantiate the correct templated kernel for the dslash.
Definition at line 22 of file dslash_twisted_clover_preconditioned.cu.
Member Function Documentation
launch()
template<typename Float , int nDim, int nColor, int nParity, bool dagger, bool xpay, KernelType kernel_type, typename Arg > template<typename Dslash > static void quda::TwistedCloverPreconditionedLaunch< Float, nDim, nColor, nParity, dagger, xpay, kernel_type, Arg >::launch (Dslash & dslash, TuneParam & tp, Arg & arg, const cudaStream_t & stream) inline static
Definition at line 25 of file dslash_twisted_clover_preconditioned.cu.
References dagger, errorQuda, quda::Dslash< Float >::launch(), nColor, quda::twistedCloverPreconditionedGPU(), and quda::blas::xpay().
Member Data Documentation
kernel
template<typename Float , int nDim, int nColor, int nParity, bool dagger, bool xpay, KernelType kernel_type, typename Arg > constexpr const char* quda::TwistedCloverPreconditionedLaunch< Float, nDim, nColor, nParity, dagger, xpay, kernel_type, Arg >::kernel = "quda::twistedCloverPreconditionedGPU" static
Definition at line 23 of file dslash_twisted_clover_preconditioned.cu.
The documentation for this struct was generated from the following file:
lib/dslash_twisted_clover_preconditioned.cu