QUDA: quda::complex< int > Struct Template Reference
quda::complex< int > Struct Template Reference
#include <complex_quda.h>
Public Types
typedef int value_type
Public Member Functions
__host__ __device__ complex ()
__host__ __device__ complex (const int &re, const int &im=float())
__host__ __device__ complex (const complex< int > &z)
__host__ __device__ complex< int > & operator+= (const complex< int > z)
__host__ __device__ complex< int > & operator-= (const complex< int > z)
__host__ __device__ int real () const volatile
__host__ __device__ int imag () const volatile
__host__ __device__ int real () const
__host__ __device__ int imag () const
__host__ __device__ void real (int re) volatile
__host__ __device__ void imag (int im) volatile
__host__ __device__ void real (int re)
__host__ __device__ void imag (int im)
operator std::complex< int > () const
template<typename T >
__host__ __device__ operator complex< T > () const
Detailed Description
template<>
struct quda::complex< int >
Definition at line 803 of file complex_quda.h.
Member Typedef Documentation
value_type
typedef int quda::complex< int >::value_type
Definition at line 806 of file complex_quda.h.
Constructor & Destructor Documentation
complex() [1/3]
__host__ __device__ quda::complex< int >::complex () inline
Definition at line 808 of file complex_quda.h.
complex() [2/3]
__host__ __device__ quda::complex< int >::complex (const int & re, const int & im = float()) inline
Definition at line 810 of file complex_quda.h.
complex() [3/3]
__host__ __device__ quda::complex< int >::complex (const complex< int > & z) inline
Definition at line 816 of file complex_quda.h.
Member Function Documentation
imag() [1/4]
__host__ __device__ int quda::complex< int >::imag () const volatile inline
Definition at line 833 of file complex_quda.h.
Referenced by quda::gauge::square_< ReduceType, int >::operator()(), quda::gauge::abs_< Float, int >::operator()(), operator+=(), and operator-=().
imag() [2/4]
__host__ __device__ int quda::complex< int >::imag () const inline
Definition at line 835 of file complex_quda.h.
imag() [3/4]
__host__ __device__ void quda::complex< int >::imag (int im) volatile inline
Definition at line 837 of file complex_quda.h.
imag() [4/4]
__host__ __device__ void quda::complex< int >::imag (int im) inline
Definition at line 839 of file complex_quda.h.
operator complex< T >()
template<typename T > __host__ __device__ quda::complex< int >::operator complex< T > () const inline
Definition at line 844 of file complex_quda.h.
operator std::complex< int >()
quda::complex< int >::operator std::complex< int > () const inline
Definition at line 842 of file complex_quda.h.
operator+=()
__host__ __device__ complex<int>& quda::complex< int >::operator+= (const complex< int > z) inline
Definition at line 818 of file complex_quda.h.
References imag(), and real().
operator-=()
__host__ __device__ complex<int>& quda::complex< int >::operator-= (const complex< int > z) inline
Definition at line 825 of file complex_quda.h.
References imag(), and real().
real() [1/4]
__host__ __device__ int quda::complex< int >::real () const volatile inline
Definition at line 832 of file complex_quda.h.
Referenced by quda::gauge::square_< ReduceType, int >::operator()(), quda::gauge::abs_< Float, int >::operator()(), operator+=(), and operator-=().
real() [2/4]
__host__ __device__ int quda::complex< int >::real () const inline
Definition at line 834 of file complex_quda.h.
real() [3/4]
__host__ __device__ void quda::complex< int >::real (int re) volatile inline
Definition at line 836 of file complex_quda.h.
real() [4/4]
__host__ __device__ void quda::complex< int >::real (int re) inline
Definition at line 838 of file complex_quda.h.
The documentation for this struct was generated from the following file:
include/complex_quda.h