QUDA: quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex > Struct Template Reference
quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
Accessor (const GaugeField &U, void *gauge_=0, void **ghost_=0)
Accessor (const Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex > &a)
void resetScale (Float max)
__device__ __host__ complex< Float > operator() (int d, int parity, int x, int row, int col) const
__device__ __host__ fieldorder_wrapper< Float, storeFloat > operator() (int d, int parity, int x, int row, int col)
template<typename theirFloat >
__device__ __host__ void atomic_add (int dim, int parity, int x_cb, int row, int col, const complex< theirFloat > &val) const
template<typename helper , typename reducer >
__host__ double transform_reduce (QudaFieldLocation location, int dim, helper h, reducer r, double init) const
Public Attributes
complex< storeFloat > * u [QUDA_MAX_GEOMETRY]
const int volumeCB
const int geometry
const int cb_offset
Float scale
Float scale_inv
Static Public Attributes
static constexpr bool fixed = fixed_point<Float,storeFloat>()
Detailed Description
template<typename Float, int nColor, typename storeFloat, bool use_tex>
struct quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >
Definition at line 370 of file gauge_field_order.h.
Constructor & Destructor Documentation
Accessor() [1/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::Accessor (const GaugeField & U, void * gauge_ = 0, void ** ghost_ = 0) inline
Definition at line 379 of file gauge_field_order.h.
References quda::GaugeField::Gauge_p(), quda::GaugeField::Geometry(), and quda::LatticeField::Scale().
Accessor() [2/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::Accessor (const Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex > & a) inline
Definition at line 389 of file gauge_field_order.h.
References QUDA_MAX_GEOMETRY, and u.
Member Function Documentation
atomic_add()
template<typename Float , int nColor, typename storeFloat , bool use_tex> template<typename theirFloat > __device__ __host__ void quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::atomic_add (int dim, int parity, int x_cb, int row, int col, const complex< theirFloat > & val) const inline
Definition at line 418 of file gauge_field_order.h.
References atomicAdd(), quda::gauge_wrapper< Float, T >::dim, and nColor.
operator()() [1/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> __device__ __host__ complex<Float> quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::operator() (int d, int parity, int x, int row, int col) const inline
Definition at line 402 of file gauge_field_order.h.
References nColor, and tmp.
operator()() [2/2]
template<typename Float , int nColor, typename storeFloat , bool use_tex> __device__ __host__ fieldorder_wrapper<Float,storeFloat> quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::operator() (int d, int parity, int x, int row, int col) inline
Definition at line 413 of file gauge_field_order.h.
References nColor.
resetScale()
template<typename Float , int nColor, typename storeFloat , bool use_tex> void quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::resetScale (Float max) inline
Definition at line 395 of file gauge_field_order.h.
transform_reduce()
template<typename Float , int nColor, typename storeFloat , bool use_tex> template<typename helper , typename reducer > __host__ double quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::transform_reduce (QudaFieldLocation location, int dim, helper h, reducer r, double init) const inline
Definition at line 446 of file gauge_field_order.h.
References quda::alloc, errorQuda, quda::cublas::init(), nColor, and QUDA_CUDA_FIELD_LOCATION.
Member Data Documentation
cb_offset
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::cb_offset
Definition at line 374 of file gauge_field_order.h.
fixed
template<typename Float , int nColor, typename storeFloat , bool use_tex> constexpr bool quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::fixed = fixed_point<Float,storeFloat>() static
Definition at line 377 of file gauge_field_order.h.
geometry
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::geometry
Definition at line 373 of file gauge_field_order.h.
scale
template<typename Float , int nColor, typename storeFloat , bool use_tex> Float quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::scale
Definition at line 375 of file gauge_field_order.h.
scale_inv
template<typename Float , int nColor, typename storeFloat , bool use_tex> Float quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::scale_inv
Definition at line 376 of file gauge_field_order.h.
u
template<typename Float , int nColor, typename storeFloat , bool use_tex> complex<storeFloat>* quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::u[QUDA_MAX_GEOMETRY]
Definition at line 371 of file gauge_field_order.h.
Referenced by Accessor().
volumeCB
template<typename Float , int nColor, typename storeFloat , bool use_tex> const int quda::gauge::Accessor< Float, nColor, QUDA_QDP_GAUGE_ORDER, storeFloat, use_tex >::volumeCB
Definition at line 372 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h