QUDA: quda::WilsonCloverPreconditionedApply< Float, nColor, recon > Struct Template Reference
quda::WilsonCloverPreconditionedApply< Float, nColor, recon > Struct Template Reference
Public Member Functions
WilsonCloverPreconditionedApply (ColorSpinorField &out, const ColorSpinorField &in, const GaugeField &U, const CloverField &A, double a, const ColorSpinorField &x, int parity, bool dagger, const int *comm_override, TimeProfile &profile)
Detailed Description
template<typename Float, int nColor, QudaReconstructType recon>
struct quda::WilsonCloverPreconditionedApply< Float, nColor, recon >
Definition at line 130 of file dslash_wilson_clover_preconditioned.cu.
Constructor & Destructor Documentation
WilsonCloverPreconditionedApply()
template<typename Float , int nColor, QudaReconstructType recon> quda::WilsonCloverPreconditionedApply< Float, nColor, recon >::WilsonCloverPreconditionedApply (ColorSpinorField & out, const ColorSpinorField & in, const GaugeField & U, const CloverField & A, double a, const ColorSpinorField & x, int parity, bool dagger, const int * comm_override, TimeProfile & profile) inline
Definition at line 132 of file dslash_wilson_clover_preconditioned.cu.
References quda::dslash::DslashPolicyTune< Dslash >::apply(), quda::arg(), checkCudaError, quda::ColorSpinorField::GhostFaceCB(), quda::ColorSpinorField::VolumeCB(), and quda::wilson().
The documentation for this struct was generated from the following file:
lib/dslash_wilson_clover_preconditioned.cu