QUDA: quda::complex< float > Struct Template Reference
quda::complex< float > Struct Template Reference
#include <complex_quda.h>
Public Types
typedef float value_type
Public Member Functions
__host__ __device__ complex ()
__host__ __device__ complex (const float &re, const float &im=float())
__host__ __device__ complex (const complex< float > &z)
__host__ __device__ complex (float2 z)
template<class X >
complex (const std::complex< X > &z)
template<typename T >
__host__ __device__ volatile complex< float > & operator= (const complex< T > z) volatile
template<typename T >
__host__ __device__ complex< float > & operator= (const complex< T > z)
__host__ __device__ complex< float > & operator+= (const complex< float > z)
__host__ __device__ complex< float > & operator-= (const complex< float > z)
__host__ __device__ complex< float > & operator*= (const complex< float > z)
__host__ __device__ complex< float > & operator/= (const complex< float > z)
__host__ __device__ complex< float > & operator*= (const float z)
__host__ __device__ complex (const volatile complex< float > &z)
__host__ __device__ float real () const volatile
__host__ __device__ float imag () const volatile
__host__ __device__ float real () const
__host__ __device__ float imag () const
__host__ __device__ void real (float re) volatile
__host__ __device__ void imag (float im) volatile
__host__ __device__ void real (float re)
__host__ __device__ void imag (float im)
operator std::complex< float > () const
template<typename T >
__host__ __device__ operator complex< T > () const
template<typename otherFloat , typename storeFloat >
__host__ __device__ void operator= (const gauge::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__host__ __device__ complex (const gauge::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__host__ __device__ void operator= (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__host__ __device__ complex (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__device__ __host__ void operator= (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__device__ __host__ complex (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__device__ __host__ void operator= (const gauge::fieldorder_wrapper< otherFloat, storeFloat > &a)
template<typename otherFloat , typename storeFloat >
__device__ __host__ complex (const gauge::fieldorder_wrapper< otherFloat, storeFloat > &a)
Detailed Description
template<>
struct quda::complex< float >
Definition at line 458 of file complex_quda.h.
Member Typedef Documentation
value_type
typedef float quda::complex< float >::value_type
Definition at line 461 of file complex_quda.h.
Constructor & Destructor Documentation
complex() [1/10]
__host__ __device__ quda::complex< float >::complex () inline
Definition at line 463 of file complex_quda.h.
complex() [2/10]
__host__ __device__ quda::complex< float >::complex (const float & re, const float & im = float()) inline
Definition at line 465 of file complex_quda.h.
complex() [3/10]
__host__ __device__ quda::complex< float >::complex (const complex< float > & z) inline
Definition at line 474 of file complex_quda.h.
complex() [4/10]
__host__ __device__ quda::complex< float >::complex (float2 z) inline
Definition at line 478 of file complex_quda.h.
complex() [5/10]
template<class X > quda::complex< float >::complex (const std::complex< X > & z) inline
Definition at line 482 of file complex_quda.h.
complex() [6/10]
__host__ __device__ quda::complex< float >::complex (const volatile complex< float > & z) inline
Definition at line 546 of file complex_quda.h.
complex() [7/10]
template<typename otherFloat , typename storeFloat > __host__ __device__ quda::complex< float >::complex (const gauge::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
complex() [8/10]
template<typename otherFloat , typename storeFloat > __host__ __device__ quda::complex< float >::complex (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
complex() [9/10]
template<typename otherFloat , typename storeFloat > __device__ __host__ quda::complex< float >::complex (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
Definition at line 1596 of file color_spinor_field_order.h.
References quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::imag(), and quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::real().
complex() [10/10]
template<typename otherFloat , typename storeFloat > __device__ __host__ quda::complex< float >::complex (const gauge::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
Definition at line 3003 of file gauge_field_order.h.
References quda::gauge::default_huge_alloc, quda::gauge::fieldorder_wrapper< Float, storeFloat >::imag(), QUDA_GHOST_EXCHANGE_INVALID, QUDA_STAGGERED_PHASE_NO, and quda::gauge::fieldorder_wrapper< Float, storeFloat >::real().
Member Function Documentation
imag() [1/4]
__host__ __device__ float quda::complex< float >::imag () const volatile inline
Definition at line 553 of file complex_quda.h.
Referenced by quda::abs(), quda::arg(), quda::atanh(), quda::cos(), quda::cosh(), quda::exp(), quda::make_Float2(), operator+=(), quda::complex< double >::operator+=(), operator-=(), quda::operator/(), quda::sin(), and quda::sinh().
imag() [2/4]
__host__ __device__ float quda::complex< float >::imag () const inline
Definition at line 555 of file complex_quda.h.
imag() [3/4]
__host__ __device__ void quda::complex< float >::imag (float im) volatile inline
Definition at line 557 of file complex_quda.h.
imag() [4/4]
__host__ __device__ void quda::complex< float >::imag (float im) inline
Definition at line 559 of file complex_quda.h.
operator complex< T >()
template<typename T > __host__ __device__ quda::complex< float >::operator complex< T > () const inline
Definition at line 564 of file complex_quda.h.
operator std::complex< float >()
quda::complex< float >::operator std::complex< float > () const inline
Definition at line 562 of file complex_quda.h.
operator*=() [1/2]
__host__ __device__ complex<float>& quda::complex< float >::operator*= (const complex< float > z) inline
Definition at line 524 of file complex_quda.h.
operator*=() [2/2]
__host__ __device__ complex<float>& quda::complex< float >::operator*= (const float z) inline
Definition at line 538 of file complex_quda.h.
operator+=()
__host__ __device__ complex<float>& quda::complex< float >::operator+= (const complex< float > z) inline
Definition at line 508 of file complex_quda.h.
References imag(), and real().
operator-=()
__host__ __device__ complex<float>& quda::complex< float >::operator-= (const complex< float > z) inline
Definition at line 516 of file complex_quda.h.
References imag(), and real().
operator/=()
__host__ __device__ complex<float>& quda::complex< float >::operator/= (const complex< float > z) inline
Definition at line 531 of file complex_quda.h.
operator=() [1/6]
template<typename T > __host__ __device__ volatile complex<float>& quda::complex< float >::operator= (const complex< T > z) volatile inline
Definition at line 491 of file complex_quda.h.
operator=() [2/6]
template<typename T > __host__ __device__ complex<float>& quda::complex< float >::operator= (const complex< T > z) inline
Definition at line 500 of file complex_quda.h.
operator=() [3/6]
template<typename otherFloat , typename storeFloat > __host__ __device__ void quda::complex< float >::operator= (const gauge::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
operator=() [4/6]
template<typename otherFloat , typename storeFloat > __host__ __device__ void quda::complex< float >::operator= (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
operator=() [5/6]
template<typename otherFloat , typename storeFloat > __device__ __host__ void quda::complex< float >::operator= (const colorspinor::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
Definition at line 1584 of file color_spinor_field_order.h.
References quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::imag(), and quda::colorspinor::fieldorder_wrapper< Float, storeFloat >::real().
operator=() [6/6]
template<typename otherFloat , typename storeFloat > __device__ __host__ void quda::complex< float >::operator= (const gauge::fieldorder_wrapper< otherFloat, storeFloat > & a) inline
Definition at line 2991 of file gauge_field_order.h.
References quda::gauge::fieldorder_wrapper< Float, storeFloat >::imag(), and quda::gauge::fieldorder_wrapper< Float, storeFloat >::real().
real() [1/4]
__host__ __device__ float quda::complex< float >::real () const volatile inline
Definition at line 552 of file complex_quda.h.
Referenced by quda::abs(), quda::arg(), quda::atanh(), quda::cos(), quda::cosh(), quda::exp(), quda::make_Float2(), operator+=(), quda::complex< double >::operator+=(), operator-=(), quda::operator/(), quda::sin(), and quda::sinh().
real() [2/4]
__host__ __device__ float quda::complex< float >::real () const inline
Definition at line 554 of file complex_quda.h.
real() [3/4]
__host__ __device__ void quda::complex< float >::real (float re) volatile inline
Definition at line 556 of file complex_quda.h.
real() [4/4]
__host__ __device__ void quda::complex< float >::real (float re) inline
Definition at line 558 of file complex_quda.h.
The documentation for this struct was generated from the following files:
include/complex_quda.h
include/color_spinor_field_order.h
include/gauge_field_order.h