QUDA: quda::FullClover Struct Reference
quda::FullClover Struct Reference
#include <clover_field.h>
Public Member Functions
FullClover (const cudaCloverField &clover, bool inverse=false)
Public Attributes
void * even
void * odd
void * evenNorm
void * oddNorm
QudaPrecision precision
size_t bytes
size_t norm_bytes
int stride
double rho
Detailed Description
Definition at line 271 of file clover_field.h.
Constructor & Destructor Documentation
FullClover()
quda::FullClover::FullClover (const cudaCloverField & clover, bool inverse = false) inline
Definition at line 293 of file clover_field.h.
References quda::CloverFieldParam::clover, quda::cloverDerivative(), quda::cloverInvert(), quda::cloverRho(), quda::computeClover(), quda::computeCloverForce(), quda::computeCloverSigmaOprod(), quda::computeCloverSigmaTrace(), quda::copyGenericClover(), quda::cudaCloverField::even, quda::cudaCloverField::evenInv, quda::cudaCloverField::evenInvNorm, quda::cudaCloverField::evenNorm, in, quda::CloverFieldParam::inverse, quda::cudaCloverField::odd, quda::cudaCloverField::oddInv, quda::cudaCloverField::oddInvNorm, quda::cudaCloverField::oddNorm, out, parity, quda::CloverFieldParam::rho, and quda::LatticeFieldParam::x.
Member Data Documentation
bytes
size_t quda::FullClover::bytes
Definition at line 277 of file clover_field.h.
even
void* quda::FullClover::even
Definition at line 272 of file clover_field.h.
evenNorm
void* quda::FullClover::evenNorm
Definition at line 274 of file clover_field.h.
norm_bytes
size_t quda::FullClover::norm_bytes
Definition at line 278 of file clover_field.h.
odd
void* quda::FullClover::odd
Definition at line 273 of file clover_field.h.
oddNorm
void* quda::FullClover::oddNorm
Definition at line 275 of file clover_field.h.
precision
QudaPrecision quda::FullClover::precision
Definition at line 276 of file clover_field.h.
rho
double quda::FullClover::rho
Definition at line 280 of file clover_field.h.
stride
int quda::FullClover::stride
Definition at line 279 of file clover_field.h.
The documentation for this struct was generated from the following file:
include/clover_field.h