QUDA: quda::LaplaceArg< Float, nColor, reconstruct_ > Struct Template Reference
quda::LaplaceArg< Float, nColor, reconstruct_ > Struct Template Reference
Parameter structure for driving the covariatnt derivative operator.
Public Types
typedef colorspinor_mapper< Float, nSpin, nColor, spin_project, spinor_direct_load >::type F
typedef gauge_mapper< Float, reconstruct, 18, QUDA_STAGGERED_PHASE_NO, gauge_direct_load, ghost >::type G
typedef mapper< Float >::type real
Public Types inherited from quda::DslashArg< Float >
typedef mapper< Float >::type real
Public Member Functions
LaplaceArg (ColorSpinorField &out, const ColorSpinorField &in, const GaugeField &U, int dir, double a, const ColorSpinorField &x, int parity, bool dagger, const int *comm_override)
Public Member Functions inherited from quda::DslashArg< Float >
DslashArg (const ColorSpinorField &in, const GaugeField &U, int parity, bool dagger, bool xpay, int nFace, int spin_project, const int *comm_override)
Public Attributes
F out
const F in
const F x
const G U
const real a
int dir
Public Attributes inherited from quda::DslashArg< Float >
const int parity
const int nParity
const int nFace
const QudaReconstructType reconstruct
const int_fastdiv X0h
const int_fastdiv dim [5]
const int volumeCB
int commDim [4]
int ghostDim [4]
const bool dagger
const bool xpay
real t_proj_scale
DslashConstant dc
KernelType kernel_type
bool remote_write
int_fastdiv threads
int threadDimMapLower [4]
int threadDimMapUpper [4]
const bool spin_project
real twist_a
real twist_b
real twist_c
Static Public Attributes
static constexpr int nSpin = 1
static constexpr bool spin_project = false
static constexpr bool spinor_direct_load = false
static constexpr QudaReconstructType reconstruct = reconstruct_
static constexpr bool gauge_direct_load = false
static constexpr QudaGhostExchange ghost = QUDA_GHOST_EXCHANGE_PAD
Detailed Description
template<typename Float, int nColor, QudaReconstructType reconstruct_>
struct quda::LaplaceArg< Float, nColor, reconstruct_ >
Parameter structure for driving the covariatnt derivative operator.
Definition at line 16 of file laplace.cuh.
Member Typedef Documentation
F
template<typename Float, int nColor, QudaReconstructType reconstruct_> typedef colorspinor_mapper<Float, nSpin, nColor, spin_project, spinor_direct_load>::type quda::LaplaceArg< Float, nColor, reconstruct_ >::F
Definition at line 20 of file laplace.cuh.
G
template<typename Float, int nColor, QudaReconstructType reconstruct_> typedef gauge_mapper<Float, reconstruct, 18, QUDA_STAGGERED_PHASE_NO, gauge_direct_load, ghost>::type quda::LaplaceArg< Float, nColor, reconstruct_ >::G
Definition at line 25 of file laplace.cuh.
real
template<typename Float, int nColor, QudaReconstructType reconstruct_> typedef mapper<Float>::type quda::LaplaceArg< Float, nColor, reconstruct_ >::real
Definition at line 27 of file laplace.cuh.
Constructor & Destructor Documentation
LaplaceArg()
template<typename Float, int nColor, QudaReconstructType reconstruct_> quda::LaplaceArg< Float, nColor, reconstruct_ >::LaplaceArg (ColorSpinorField & out, const ColorSpinorField & in, const GaugeField & U, int dir, double a, const ColorSpinorField & x, int parity, bool dagger, const int * comm_override) inline
The direction from which to omit the derivative
Definition at line 36 of file laplace.cuh.
References quda::DslashArg< Float >::dagger, quda::LaplaceArg< Float, nColor, reconstruct_ >::dir, errorQuda, quda::GaugeField::FieldOrder(), quda::ColorSpinorField::FieldOrder(), quda::GaugeField::isNative(), quda::ColorSpinorField::isNative(), quda::DslashArg< Float >::kernel_type, nColor, and quda::DslashArg< Float >::nParity.
Member Data Documentation
a
template<typename Float, int nColor, QudaReconstructType reconstruct_> const real quda::LaplaceArg< Float, nColor, reconstruct_ >::a
the gauge field
Definition at line 33 of file laplace.cuh.
dir
template<typename Float, int nColor, QudaReconstructType reconstruct_> int quda::LaplaceArg< Float, nColor, reconstruct_ >::dir
xpay scale factor - can be -kappa or -kappa^2
Definition at line 34 of file laplace.cuh.
Referenced by quda::LaplaceArg< Float, nColor, reconstruct_ >::LaplaceArg().
gauge_direct_load
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr bool quda::LaplaceArg< Float, nColor, reconstruct_ >::gauge_direct_load = false static
Definition at line 23 of file laplace.cuh.
ghost
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr QudaGhostExchange quda::LaplaceArg< Float, nColor, reconstruct_ >::ghost = QUDA_GHOST_EXCHANGE_PAD static
Definition at line 24 of file laplace.cuh.
Referenced by quda::applyLaplace().
in
template<typename Float, int nColor, QudaReconstructType reconstruct_> const F quda::LaplaceArg< Float, nColor, reconstruct_ >::in
output vector field
Definition at line 30 of file laplace.cuh.
Referenced by quda::applyLaplace().
nSpin
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr int quda::LaplaceArg< Float, nColor, reconstruct_ >::nSpin = 1 static
Definition at line 17 of file laplace.cuh.
out
template<typename Float, int nColor, QudaReconstructType reconstruct_> F quda::LaplaceArg< Float, nColor, reconstruct_ >::out
Definition at line 29 of file laplace.cuh.
Referenced by quda::laplace().
reconstruct
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr QudaReconstructType quda::LaplaceArg< Float, nColor, reconstruct_ >::reconstruct = reconstruct_ static
Definition at line 22 of file laplace.cuh.
spin_project
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr bool quda::LaplaceArg< Float, nColor, reconstruct_ >::spin_project = false static
Definition at line 18 of file laplace.cuh.
spinor_direct_load
template<typename Float, int nColor, QudaReconstructType reconstruct_> constexpr bool quda::LaplaceArg< Float, nColor, reconstruct_ >::spinor_direct_load = false static
Definition at line 19 of file laplace.cuh.
U
template<typename Float, int nColor, QudaReconstructType reconstruct_> const G quda::LaplaceArg< Float, nColor, reconstruct_ >::U
input vector field for xpay
Definition at line 32 of file laplace.cuh.
Referenced by quda::applyLaplace().
x
template<typename Float, int nColor, QudaReconstructType reconstruct_> const F quda::LaplaceArg< Float, nColor, reconstruct_ >::x
input vector field
Definition at line 31 of file laplace.cuh.
Referenced by quda::laplace().
The documentation for this struct was generated from the following file:
include/kernels/laplace.cuh