QUDA: quda::colorspinor::abs_< Float, char > Struct Template Reference
quda::colorspinor::abs_< Float, char > Struct Template Reference
#include <color_spinor_field_order.h>
Public Member Functions
abs_ (const Float scale)
__host__ __device__ Float operator() (const quda::complex< char > &x)
Public Attributes
Float scale
Detailed Description
template<typename Float>
struct quda::colorspinor::abs_< Float, char >
Definition at line 221 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
abs_()
template<typename Float > quda::colorspinor::abs_< Float, char >::abs_ (const Float scale) inline
Definition at line 223 of file color_spinor_field_order.h.
Member Function Documentation
operator()()
template<typename Float > __host__ __device__ Float quda::colorspinor::abs_< Float, char >::operator() (const quda::complex< char > & x) inline
Definition at line 224 of file color_spinor_field_order.h.
References quda::abs(), quda::complex< char >::imag(), and quda::complex< char >::real().
Member Data Documentation
scale
template<typename Float > Float quda::colorspinor::abs_< Float, char >::scale
Definition at line 222 of file color_spinor_field_order.h.
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h