QUDA: quda::Dslash5Arg< Float, nColor > Struct Template Reference
quda::Dslash5Arg< Float, nColor > Struct Template Reference
Parameter structure for applying the Dslash.
Public Types
typedef colorspinor_mapper< Float, 4, nColor >::type F
typedef mapper< Float >::type real
Public Member Functions
Dslash5Arg (ColorSpinorField &out, const ColorSpinorField &in, const ColorSpinorField &x, double m_f, double m_5, const Complex *b_5_, const Complex *c_5_, double a_, bool dagger, Dslash5Type type)
virtual ~Dslash5Arg ()
Public Attributes
F out
const F in
const F x
const int nParity
const int volume_cb
const int volume_4d_cb
const int_fastdiv Ls
const real m_f
const real m_5
const bool dagger
const bool xpay
real b
real c
real a
Dslash5Type type
coeff_5< real > * mobius_h
Detailed Description
template<typename Float, int nColor>
struct quda::Dslash5Arg< Float, nColor >
Parameter structure for applying the Dslash.
Definition at line 78 of file dslash_domain_wall_m5.cuh.
Member Typedef Documentation
F
template<typename Float, int nColor> typedef colorspinor_mapper<Float, 4, nColor>::type quda::Dslash5Arg< Float, nColor >::F
Definition at line 79 of file dslash_domain_wall_m5.cuh.
real
template<typename Float, int nColor> typedef mapper<Float>::type quda::Dslash5Arg< Float, nColor >::real
Definition at line 80 of file dslash_domain_wall_m5.cuh.
Constructor & Destructor Documentation
Dslash5Arg()
template<typename Float, int nColor> quda::Dslash5Arg< Float, nColor >::Dslash5Arg (ColorSpinorField & out, const ColorSpinorField & in, const ColorSpinorField & x, double m_f, double m_5, const Complex * b_5_, const Complex * c_5_, double a_, bool dagger, Dslash5Type type) inline
Definition at line 104 of file dslash_domain_wall_m5.cuh.
References quda::coeff_5< real >::a, quda::coeff_5< real >::b, quda::coeff_5< real >::c, quda::DSLASH5_DWF, quda::DSLASH5_MOBIUS, quda::DSLASH5_MOBIUS_PRE, errorQuda, quda::ColorSpinorField::FieldOrder(), quda::ColorSpinorField::isNative(), Ls, quda::M5_INV_DWF, quda::M5_INV_MOBIUS, quda::M5_INV_ZMOBIUS, quda::ColorSpinorField::Nspin(), quda::Nstream, quda::pow(), quda::s, quda::size, and streams.
~Dslash5Arg()
template<typename Float, int nColor> virtual quda::Dslash5Arg< Float, nColor >::~Dslash5Arg () inline virtual
Definition at line 180 of file dslash_domain_wall_m5.cuh.
Member Data Documentation
a
template<typename Float, int nColor> real quda::Dslash5Arg< Float, nColor >::a
Definition at line 98 of file dslash_domain_wall_m5.cuh.
b
template<typename Float, int nColor> real quda::Dslash5Arg< Float, nColor >::b
Definition at line 96 of file dslash_domain_wall_m5.cuh.
c
template<typename Float, int nColor> real quda::Dslash5Arg< Float, nColor >::c
Definition at line 97 of file dslash_domain_wall_m5.cuh.
dagger
template<typename Float, int nColor> const bool quda::Dslash5Arg< Float, nColor >::dagger
Definition at line 93 of file dslash_domain_wall_m5.cuh.
in
template<typename Float, int nColor> const F quda::Dslash5Arg< Float, nColor >::in
Definition at line 83 of file dslash_domain_wall_m5.cuh.
Ls
template<typename Float, int nColor> const int_fastdiv quda::Dslash5Arg< Float, nColor >::Ls
Definition at line 88 of file dslash_domain_wall_m5.cuh.
m_5
template<typename Float, int nColor> const real quda::Dslash5Arg< Float, nColor >::m_5
Definition at line 91 of file dslash_domain_wall_m5.cuh.
m_f
template<typename Float, int nColor> const real quda::Dslash5Arg< Float, nColor >::m_f
Definition at line 90 of file dslash_domain_wall_m5.cuh.
mobius_h
template<typename Float, int nColor> coeff_5<real>* quda::Dslash5Arg< Float, nColor >::mobius_h
Definition at line 102 of file dslash_domain_wall_m5.cuh.
nParity
template<typename Float, int nColor> const int quda::Dslash5Arg< Float, nColor >::nParity
Definition at line 85 of file dslash_domain_wall_m5.cuh.
out
template<typename Float, int nColor> F quda::Dslash5Arg< Float, nColor >::out
Definition at line 82 of file dslash_domain_wall_m5.cuh.
type
template<typename Float, int nColor> Dslash5Type quda::Dslash5Arg< Float, nColor >::type
Definition at line 100 of file dslash_domain_wall_m5.cuh.
volume_4d_cb
template<typename Float, int nColor> const int quda::Dslash5Arg< Float, nColor >::volume_4d_cb
Definition at line 87 of file dslash_domain_wall_m5.cuh.
volume_cb
template<typename Float, int nColor> const int quda::Dslash5Arg< Float, nColor >::volume_cb
Definition at line 86 of file dslash_domain_wall_m5.cuh.
x
template<typename Float, int nColor> const F quda::Dslash5Arg< Float, nColor >::x
Definition at line 84 of file dslash_domain_wall_m5.cuh.
xpay
template<typename Float, int nColor> const bool quda::Dslash5Arg< Float, nColor >::xpay
Definition at line 94 of file dslash_domain_wall_m5.cuh.
The documentation for this struct was generated from the following file:
include/kernels/dslash_domain_wall_m5.cuh