QUDA: quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER > Struct Template Reference
quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER > Struct Template Reference
#include <clover_field_order.h>
Public Member Functions
Accessor (const CloverField &A, bool inverse=false)
__device__ __host__ complex< Float > operator() (int parity, int x, int s_row, int s_col, int c_row, int c_col) const
template<typename helper , typename reducer >
__host__ double transform_reduce (QudaFieldLocation location, helper h, reducer r, double init) const
Public Attributes
Float * a [2]
const int N = nSpin * nColor / 2
complex< Float > zero
Detailed Description
template<typename Float, int nColor, int nSpin>
struct quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >
Definition at line 307 of file clover_field_order.h.
Constructor & Destructor Documentation
Accessor()
template<typename Float , int nColor, int nSpin> quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::Accessor (const CloverField & A, bool inverse = false) inline
Definition at line 311 of file clover_field_order.h.
References quda::CloverField::Bytes(), quda::inverse(), and quda::CloverField::V().
Member Function Documentation
operator()()
template<typename Float , int nColor, int nSpin> __device__ __host__ complex<Float> quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::operator() (int parity, int x, int s_row, int s_col, int c_row, int c_col) const inline
Definition at line 319 of file clover_field_order.h.
References quda::clover_wrapper< Float, T >::chirality, nColor, quda::clover_wrapper< Float, T >::parity, tmp, and quda::zero().
transform_reduce()
template<typename Float , int nColor, int nSpin> template<typename helper , typename reducer > __host__ double quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::transform_reduce (QudaFieldLocation location, helper h, reducer r, double init) const inline
Definition at line 345 of file clover_field_order.h.
References errorQuda.
Member Data Documentation
a
template<typename Float , int nColor, int nSpin> Float* quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::a[2]
Definition at line 308 of file clover_field_order.h.
N
template<typename Float , int nColor, int nSpin> const int quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::N = nSpin * nColor / 2
Definition at line 309 of file clover_field_order.h.
zero
template<typename Float , int nColor, int nSpin> complex<Float> quda::clover::Accessor< Float, nColor, nSpin, QUDA_PACKED_CLOVER_ORDER >::zero
Definition at line 310 of file clover_field_order.h.
The documentation for this struct was generated from the following file:
include/clover_field_order.h