QUDA: quda::colorspinor::abs_< Float, short > Struct Template Reference
quda::colorspinor::abs_< Float, short > Struct Template Reference
#include <color_spinor_field_order.h>
Public Member Functions
abs_ (const Float scale)
__host__ __device__ Float operator() (const quda::complex< short > &x)
Public Attributes
Float scale
Detailed Description
template<typename Float>
struct quda::colorspinor::abs_< Float, short >
Definition at line 214 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
abs_()
template<typename Float > quda::colorspinor::abs_< Float, short >::abs_ (const Float scale) inline
Definition at line 216 of file color_spinor_field_order.h.
Member Function Documentation
operator()()
template<typename Float > __host__ __device__ Float quda::colorspinor::abs_< Float, short >::operator() (const quda::complex< short > & x) inline
Definition at line 217 of file color_spinor_field_order.h.
References quda::abs(), quda::complex< short >::imag(), and quda::complex< short >::real().
Member Data Documentation
scale
template<typename Float > Float quda::colorspinor::abs_< Float, short >::scale
Definition at line 215 of file color_spinor_field_order.h.
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h