QUDA: quda::deflated_solver Struct Reference
quda::deflated_solver Struct Reference
#include <deflation.h>
Public Member Functions
deflated_solver (QudaEigParam &eig_param, TimeProfile &profile)
virtual ~deflated_solver ()
Public Attributes
Dirac * d
DiracMatrix * m
ColorSpinorField * RV
DeflationParam * deflParam
Deflation * defl
TimeProfile & profile
Detailed Description
Following the multigrid design, this is an object that captures an entire deflation operations. A bit of a hack at the moment, this is used to allow us to store and reuse the deflation stuff between solves. This is use by the newDeflationQuda and destroyDeflationQuda interface functions.
Definition at line 180 of file deflation.h.
Constructor & Destructor Documentation
deflated_solver()
deflated_solver::deflated_solver (QudaEigParam & eig_param, TimeProfile & profile)
Definition at line 2743 of file interface_quda.cpp.
References checkGauge(), quda::ColorSpinorParam::create, quda::Dirac::create(), quda::ColorSpinorField::Create(), QudaInvertParam_s::cuda_prec, QudaInvertParam_s::cuda_prec_ritz, QudaEigParam_s::cuda_prec_ritz, cudaGauge, d, defl, QudaInvertParam_s::deflation_grid, deflParam, getVerbosity(), QudaEigParam_s::gflops, QudaInvertParam_s::inv_type, QudaEigParam_s::invert_param, QudaEigParam_s::location, m, QudaEigParam_s::mem_type_ritz, QudaInvertParam_s::nev, param, printfQuda, QUDA_CUDA_FIELD_LOCATION, QUDA_DEBUG_VERBOSE, QUDA_DIRECT_PC_SOLVE, QUDA_EIGCG_INVERTER, QUDA_INC_EIGCG_INVERTER, QUDA_MEMORY_DEVICE, QUDA_MEMORY_MAPPED, QUDA_MEMORY_PINNED, QUDA_NORMOP_PC_SOLVE, quda::QUDA_PROFILE_INIT, QUDA_UKQCD_GAMMA_BASIS, QUDA_ZERO_FIELD_CREATE, RV, QudaEigParam_s::secs, quda::setDiracParam(), quda::setDiracSloppyParam(), QudaInvertParam_s::solve_type, and quda::LatticeField::X().
Referenced by newDeflationQuda().
~deflated_solver()
virtual quda::deflated_solver::~deflated_solver () inline virtual
Definition at line 194 of file deflation.h.
References quda::QUDA_PROFILE_FREE, and quda::DeflationParam::RV.
Member Data Documentation
d
Dirac* quda::deflated_solver::d
Definition at line 182 of file deflation.h.
Referenced by deflated_solver(), invertMultiShiftQuda(), invertMultiSrcQuda(), and invertQuda().
defl
Deflation* quda::deflated_solver::defl
Definition at line 189 of file deflation.h.
Referenced by deflated_solver(), quda::IncEigCG::initCGsolve(), newDeflationQuda(), and quda::IncEigCG::operator()().
deflParam
DeflationParam* quda::deflated_solver::deflParam
Definition at line 187 of file deflation.h.
Referenced by deflated_solver().
m
DiracMatrix* quda::deflated_solver::m
Definition at line 183 of file deflation.h.
Referenced by deflated_solver(), invertMultiShiftQuda(), invertMultiSrcQuda(), and invertQuda().
profile
TimeProfile& quda::deflated_solver::profile
Definition at line 190 of file deflation.h.
RV
ColorSpinorField* quda::deflated_solver::RV
Definition at line 185 of file deflation.h.
Referenced by deflated_solver().
The documentation for this struct was generated from the following files:
include/deflation.h
lib/interface_quda.cpp