QUDA: quda::TwistedCloverPreconditionedApply< Float, nColor, recon > Struct Template Reference
quda::TwistedCloverPreconditionedApply< Float, nColor, recon > Struct Template Reference
Public Member Functions
TwistedCloverPreconditionedApply (ColorSpinorField &out, const ColorSpinorField &in, const GaugeField &U, const CloverField &C, double a, double b, bool xpay, const ColorSpinorField &x, int parity, bool dagger, const int *comm_override, TimeProfile &profile)
Detailed Description
template<typename Float, int nColor, QudaReconstructType recon>
struct quda::TwistedCloverPreconditionedApply< Float, nColor, recon >
Definition at line 131 of file dslash_twisted_clover_preconditioned.cu.
Constructor & Destructor Documentation
TwistedCloverPreconditionedApply()
template<typename Float , int nColor, QudaReconstructType recon> quda::TwistedCloverPreconditionedApply< Float, nColor, recon >::TwistedCloverPreconditionedApply (ColorSpinorField & out, const ColorSpinorField & in, const GaugeField & U, const CloverField & C, double a, double b, bool xpay, const ColorSpinorField & x, int parity, bool dagger, const int * comm_override, TimeProfile & profile) inline
Definition at line 133 of file dslash_twisted_clover_preconditioned.cu.
References quda::dslash::DslashPolicyTune< Dslash >::apply(), quda::arg(), checkCudaError, quda::ColorSpinorField::GhostFaceCB(), and quda::ColorSpinorField::VolumeCB().
The documentation for this struct was generated from the following file:
lib/dslash_twisted_clover_preconditioned.cu