QUDA: quda::ExtractGhostArg< Float, nColor_, Order, nDim > Struct Template Reference
quda::ExtractGhostArg< Float, nColor_, Order, nDim > Struct Template Reference
Public Types
using real = typename mapper< Float >::type
Public Member Functions
ExtractGhostArg (const Order &order, const GaugeField &u, const int *A_, const int *B_, const int *C_, const int f_[nDim][nDim], const int *localParity_, int offset)
Public Attributes
Order order
const unsigned char nFace
unsigned short X [nDim]
unsigned short A [nDim]
unsigned short B [nDim]
unsigned short C [nDim]
int f [nDim][nDim]
bool localParity [nDim]
int faceVolumeCB [nDim]
int commDim [QUDA_MAX_DIM]
const int offset
Static Public Attributes
static constexpr int nColor = nColor_
Detailed Description
template<typename Float, int nColor_, typename Order, int nDim>
struct quda::ExtractGhostArg< Float, nColor_, Order, nDim >
Definition at line 11 of file extract_gauge_ghost_helper.cuh.
Member Typedef Documentation
real
template<typename Float, int nColor_, typename Order, int nDim> using quda::ExtractGhostArg< Float, nColor_, Order, nDim >::real = typename mapper<Float>::type
Definition at line 12 of file extract_gauge_ghost_helper.cuh.
Constructor & Destructor Documentation
ExtractGhostArg()
template<typename Float, int nColor_, typename Order, int nDim> quda::ExtractGhostArg< Float, nColor_, Order, nDim >::ExtractGhostArg (const Order & order, const GaugeField & u, const int * A_, const int * B_, const int * C_, const int f_[nDim][nDim], const int * localParity_, int offset) inline
Definition at line 25 of file extract_gauge_ghost_helper.cuh.
References comm_dim_partitioned(), quda::GaugeField::Nface(), quda::LatticeField::SurfaceCB(), and quda::LatticeField::X().
Member Data Documentation
A
template<typename Float, int nColor_, typename Order, int nDim> unsigned short quda::ExtractGhostArg< Float, nColor_, Order, nDim >::A[nDim]
Definition at line 17 of file extract_gauge_ghost_helper.cuh.
B
template<typename Float, int nColor_, typename Order, int nDim> unsigned short quda::ExtractGhostArg< Float, nColor_, Order, nDim >::B[nDim]
Definition at line 18 of file extract_gauge_ghost_helper.cuh.
C
template<typename Float, int nColor_, typename Order, int nDim> unsigned short quda::ExtractGhostArg< Float, nColor_, Order, nDim >::C[nDim]
Definition at line 19 of file extract_gauge_ghost_helper.cuh.
commDim
template<typename Float, int nColor_, typename Order, int nDim> int quda::ExtractGhostArg< Float, nColor_, Order, nDim >::commDim[QUDA_MAX_DIM]
Definition at line 23 of file extract_gauge_ghost_helper.cuh.
f
template<typename Float, int nColor_, typename Order, int nDim> int quda::ExtractGhostArg< Float, nColor_, Order, nDim >::f[nDim][nDim]
Definition at line 20 of file extract_gauge_ghost_helper.cuh.
faceVolumeCB
template<typename Float, int nColor_, typename Order, int nDim> int quda::ExtractGhostArg< Float, nColor_, Order, nDim >::faceVolumeCB[nDim]
Definition at line 22 of file extract_gauge_ghost_helper.cuh.
localParity
template<typename Float, int nColor_, typename Order, int nDim> bool quda::ExtractGhostArg< Float, nColor_, Order, nDim >::localParity[nDim]
Definition at line 21 of file extract_gauge_ghost_helper.cuh.
nColor
template<typename Float, int nColor_, typename Order, int nDim> constexpr int quda::ExtractGhostArg< Float, nColor_, Order, nDim >::nColor = nColor_ static
Definition at line 13 of file extract_gauge_ghost_helper.cuh.
nFace
template<typename Float, int nColor_, typename Order, int nDim> const unsigned char quda::ExtractGhostArg< Float, nColor_, Order, nDim >::nFace
Definition at line 15 of file extract_gauge_ghost_helper.cuh.
offset
template<typename Float, int nColor_, typename Order, int nDim> const int quda::ExtractGhostArg< Float, nColor_, Order, nDim >::offset
Definition at line 24 of file extract_gauge_ghost_helper.cuh.
order
template<typename Float, int nColor_, typename Order, int nDim> Order quda::ExtractGhostArg< Float, nColor_, Order, nDim >::order
Definition at line 14 of file extract_gauge_ghost_helper.cuh.
X
template<typename Float, int nColor_, typename Order, int nDim> unsigned short quda::ExtractGhostArg< Float, nColor_, Order, nDim >::X[nDim]
Definition at line 16 of file extract_gauge_ghost_helper.cuh.
The documentation for this struct was generated from the following file:
lib/extract_gauge_ghost_helper.cuh