QUDA: quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc > Struct Template Reference
quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc > Struct Template Reference
Accessor routine for ColorSpinorFields in native field order.
#include <color_spinor_field_order.h>
Public Types
using Accessor = FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >
using real = typename mapper< Float >::type
using complex = complex< real >
typedef VectorType< Float, N >::type Vector
typedef VectorType< real, N >::type RegVector
typedef AllocType< huge_alloc >::type AllocInt
typedef float norm_type
Public Member Functions
FloatNOrder (const ColorSpinorField &a, int nFace=1, Float *field_=0, norm_type *norm_=0, Float **ghost_=0, bool override=false)
void resetGhost (const ColorSpinorField &a, void *const *ghost_) const
__device__ __host__ void load (complex out[length/2], int x, int parity=0) const
__device__ __host__ void save (const complex in[length/2], int x, int parity=0)
__device__ __host__ colorspinor_wrapper< real, Accessor > operator() (int x_cb, int parity)
This accessor routine returns a colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const colorspinor_wrapper< real, Accessor > operator() (int x_cb, int parity) const
This accessor routine returns a const colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ void loadGhost (complex out[length_ghost/2], int x, int dim, int dir, int parity=0) const
__device__ __host__ void saveGhost (const complex in[length_ghost/2], int x, int dim, int dir, int parity=0) const
__device__ __host__ colorspinor_ghost_wrapper< real, Accessor > Ghost (int dim, int dir, int ghost_idx, int parity)
This accessor routine returns a colorspinor_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const colorspinor_ghost_wrapper< real, Accessor > Ghost (int dim, int dir, int ghost_idx, int parity) const
This accessor routine returns a const colorspinor_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
void save ()
Backup the field to the host when tuning.
void load ()
Restore the field from the host after tuning.
size_t Bytes () const
Public Attributes
Float * field
norm_type * norm
const AllocInt offset
const AllocInt norm_offset
int volumeCB
int faceVolumeCB [4]
int stride
Float * ghost [8]
norm_type * ghost_norm [8]
int nParity
void * backup_h
size_t bytes
host memory for backing up the field when tuning
Static Public Attributes
static constexpr int length = 2 * Ns * Nc
static constexpr int length_ghost = spin_project ? length / 2 : length
static constexpr int M = length / N
static constexpr int M_ghost = spin_project ? M / 2 : M
Detailed Description
template<typename Float, int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false>
struct quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >
Accessor routine for ColorSpinorFields in native field order.
Template Parameters
Float Underlying storage data type of the field
Ns Number of spin components
Nc Number of colors
N Number of real numbers per short vector
spin_project Whether the ghosts are spin projected or not
huge_alloc Template parameter that enables 64-bit pointer arithmetic for huge allocations (e.g., packed set of vectors). Default is to use 32-bit pointer arithmetic.
Definition at line 798 of file color_spinor_field_order.h.
Member Typedef Documentation
Accessor
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> using quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::Accessor = FloatNOrder<Float, Ns, Nc, N, spin_project, huge_alloc>
Definition at line 799 of file color_spinor_field_order.h.
AllocInt
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> typedef AllocType<huge_alloc>::type quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::AllocInt
Definition at line 804 of file color_spinor_field_order.h.
complex
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> using quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::complex = complex<real>
Definition at line 801 of file color_spinor_field_order.h.
norm_type
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> typedef float quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::norm_type
Definition at line 805 of file color_spinor_field_order.h.
real
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> using quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::real = typename mapper<Float>::type
Definition at line 800 of file color_spinor_field_order.h.
RegVector
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> typedef VectorType<real, N>::type quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::RegVector
Definition at line 803 of file color_spinor_field_order.h.
Vector
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> typedef VectorType<Float, N>::type quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::Vector
Definition at line 802 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
FloatNOrder()
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::FloatNOrder (const ColorSpinorField & a, int nFace = 1, Float * field_ = 0, norm_type * norm_ = 0, Float ** ghost_ = 0, bool override = false) inline
Definition at line 833 of file color_spinor_field_order.h.
References errorQuda, quda::ColorSpinorField::Ghost(), quda::LatticeField::Location(), quda::ColorSpinorField::Norm(), quda::LatticeField::Precision(), QUDA_CUDA_FIELD_LOCATION, QUDA_HALF_PRECISION, QUDA_QUARTER_PRECISION, quda::LatticeField::SurfaceCB(), and quda::ColorSpinorField::V().
Member Function Documentation
Bytes()
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> size_t quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::Bytes () const inline
Definition at line 1113 of file color_spinor_field_order.h.
Ghost() [1/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ colorspinor_ghost_wrapper<real, Accessor> quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::Ghost (int dim, int dir, int ghost_idx, int parity) inline
This accessor routine returns a colorspinor_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dim Dimensions of the ghost we are requesting
[in] ghost_idx Checkerboarded space-time ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_ghost_wrapper that curries in access to this field at the above coordinates.
Definition at line 1071 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity.
Ghost() [2/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ const colorspinor_ghost_wrapper<real, Accessor> quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::Ghost (int dim, int dir, int ghost_idx, int parity) const inline
This accessor routine returns a const colorspinor_ghost_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] dim Dimensions of the ghost we are requesting
[in] ghost_idx Checkerboarded space-time ghost index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_ghost+wrapper that curries in access to this field at the above coordinates.
Definition at line 1087 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity.
load() [1/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::load (complex out[length/2], int x, int parity = 0) const inline
Definition at line 878 of file color_spinor_field_order.h.
References length, out, and quda::colorspinor_wrapper< Float, T >::parity.
load() [2/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::load () inline
Restore the field from the host after tuning.
Definition at line 1106 of file color_spinor_field_order.h.
References checkCudaError, and host_free.
loadGhost()
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::loadGhost (complex out[length_ghost/2], int x, int dim, int dir, int parity = 0) const inline
Definition at line 987 of file color_spinor_field_order.h.
References out, and quda::colorspinor_wrapper< Float, T >::parity.
operator()() [1/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ colorspinor_wrapper<real, Accessor> quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::operator() (int x_cb, int parity) inline
This accessor routine returns a colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_wrapper that curries in access to this field at the above coordinates.
Definition at line 968 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::colorspinor_wrapper< Float, T >::x_cb.
operator()() [2/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ const colorspinor_wrapper<real, Accessor> quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::operator() (int x_cb, int parity) const inline
This accessor routine returns a const colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_wrapper that curries in access to this field at the above coordinates.
Definition at line 982 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::colorspinor_wrapper< Float, T >::x_cb.
resetGhost()
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::resetGhost (const ColorSpinorField & a, void *const * ghost_) const inline
Definition at line 865 of file color_spinor_field_order.h.
References comm_dim_partitioned().
save() [1/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::save (const complex in[length/2], int x, int parity = 0) inline
Definition at line 919 of file color_spinor_field_order.h.
References in, length, quda::colorspinor_wrapper< Float, T >::parity, and quda::vector_store().
save() [2/2]
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::save () inline
Backup the field to the host when tuning.
Definition at line 1096 of file color_spinor_field_order.h.
References checkCudaError, errorQuda, and safe_malloc.
saveGhost()
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> __device__ __host__ void quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::saveGhost (const complex in[length_ghost/2], int x, int dim, int dir, int parity = 0) const inline
Definition at line 1019 of file color_spinor_field_order.h.
References in, quda::colorspinor_wrapper< Float, T >::parity, and quda::vector_store().
Member Data Documentation
backup_h
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> void* quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::backup_h
Definition at line 830 of file color_spinor_field_order.h.
bytes
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> size_t quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::bytes
host memory for backing up the field when tuning
Definition at line 831 of file color_spinor_field_order.h.
faceVolumeCB
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::faceVolumeCB[4]
Definition at line 825 of file color_spinor_field_order.h.
field
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> Float* quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::field
Definition at line 810 of file color_spinor_field_order.h.
ghost
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> Float* quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::ghost[8] mutable
Definition at line 827 of file color_spinor_field_order.h.
ghost_norm
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> norm_type* quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::ghost_norm[8] mutable
Definition at line 828 of file color_spinor_field_order.h.
length
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> constexpr int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::length = 2 * Ns * Nc static
Definition at line 806 of file color_spinor_field_order.h.
length_ghost
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> constexpr int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::length_ghost = spin_project ? length / 2 : length static
Definition at line 807 of file color_spinor_field_order.h.
M
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> constexpr int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::M = length / N static
Definition at line 808 of file color_spinor_field_order.h.
M_ghost
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> constexpr int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::M_ghost = spin_project ? M / 2 : M static
Definition at line 809 of file color_spinor_field_order.h.
norm
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> norm_type* quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::norm
Definition at line 811 of file color_spinor_field_order.h.
norm_offset
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> const AllocInt quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::norm_offset
Definition at line 813 of file color_spinor_field_order.h.
nParity
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::nParity
Definition at line 829 of file color_spinor_field_order.h.
offset
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> const AllocInt quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::offset
Definition at line 812 of file color_spinor_field_order.h.
stride
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::stride
Definition at line 826 of file color_spinor_field_order.h.
volumeCB
template<typename Float , int Ns, int Nc, int N, bool spin_project = false, bool huge_alloc = false> int quda::colorspinor::FloatNOrder< Float, Ns, Nc, N, spin_project, huge_alloc >::volumeCB
Definition at line 824 of file color_spinor_field_order.h.
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h