QUDA: quda::colorspinor::square_< ReduceType, short > Struct Template Reference
quda::colorspinor::square_< ReduceType, short > Struct Template Reference
#include <color_spinor_field_order.h>
Public Member Functions
square_ (ReduceType scale)
__host__ __device__ ReduceType operator() (const quda::complex< short > &x)
Public Attributes
const ReduceType scale
Detailed Description
template<typename ReduceType>
struct quda::colorspinor::square_< ReduceType, short >
Definition at line 195 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
square_()
template<typename ReduceType > quda::colorspinor::square_< ReduceType, short >::square_ (ReduceType scale) inline
Definition at line 197 of file color_spinor_field_order.h.
Member Function Documentation
operator()()
template<typename ReduceType > __host__ __device__ ReduceType quda::colorspinor::square_< ReduceType, short >::operator() (const quda::complex< short > & x) inline
Definition at line 198 of file color_spinor_field_order.h.
References quda::complex< short >::imag(), quda::norm(), and quda::complex< short >::real().
Member Data Documentation
scale
template<typename ReduceType > const ReduceType quda::colorspinor::square_< ReduceType, short >::scale
Definition at line 196 of file color_spinor_field_order.h.
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h