QUDA: quda::gauge::abs_< Float, char > Struct Template Reference
quda::gauge::abs_< Float, char > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
abs_ (const Float scale)
__host__ __device__ Float operator() (const quda::complex< char > &x)
Public Attributes
Float scale
Detailed Description
template<typename Float>
struct quda::gauge::abs_< Float, char >
Definition at line 197 of file gauge_field_order.h.
Constructor & Destructor Documentation
abs_()
template<typename Float > quda::gauge::abs_< Float, char >::abs_ (const Float scale) inline
Definition at line 199 of file gauge_field_order.h.
Member Function Documentation
operator()()
template<typename Float > __host__ __device__ Float quda::gauge::abs_< Float, char >::operator() (const quda::complex< char > & x) inline
Definition at line 200 of file gauge_field_order.h.
References quda::abs(), quda::complex< char >::imag(), and quda::complex< char >::real().
Member Data Documentation
scale
template<typename Float > Float quda::gauge::abs_< Float, char >::scale
Definition at line 198 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h