QUDA: quda::Timer Struct Reference
quda::Timer Struct Reference
#include <timer.h>
Public Member Functions
Timer ()
void Start (const char *func, const char *file, int line)
void Stop (const char *func, const char *file, int line)
double Last ()
void Reset (const char *func, const char *file, int line)
Public Attributes
double time
double last
timeval start
timeval stop
bool running
int count
Detailed Description
Use this for recording a fine-grained profile of a QUDA algorithm. This uses host-side measurement, so should be used for timing fully host-device synchronous algorithms.Enumeration type used for writing a simple but extensible profiling framework.
Definition at line 42 of file timer.h.
Constructor & Destructor Documentation
Timer()
quda::Timer::Timer () inline
Definition at line 61 of file timer.h.
Member Function Documentation
Last()
double quda::Timer::Last () inline
Definition at line 88 of file timer.h.
Referenced by quda::tuneLaunch().
Reset()
void quda::Timer::Reset (const char * func, const char * file, int line) inline
Definition at line 90 of file timer.h.
References errorQuda, and printfQuda.
Start()
void quda::Timer::Start (const char * func, const char * file, int line) inline
Definition at line 63 of file timer.h.
References errorQuda, and printfQuda.
Referenced by quda::TimeProfile::Start_(), quda::TimeProfile::StartGlobal(), and quda::tuneLaunch().
Stop()
void quda::Timer::Stop (const char * func, const char * file, int line) inline
Definition at line 72 of file timer.h.
References errorQuda, and printfQuda.
Referenced by quda::TimeProfile::Stop_(), quda::TimeProfile::StopGlobal(), and quda::tuneLaunch().
Member Data Documentation
count
int quda::Timer::count
Definition at line 59 of file timer.h.
last
double quda::Timer::last
Used to store when the timer was last started
Definition at line 47 of file timer.h.
Referenced by quda::TimeProfile::Last().
running
bool quda::Timer::running
Keep track of number of calls
Definition at line 56 of file timer.h.
Referenced by quda::TimeProfile::isRunning().
start
timeval quda::Timer::start
Used to store when the timer was last stopped
Definition at line 50 of file timer.h.
stop
timeval quda::Timer::stop
Are we currently timing?
Definition at line 53 of file timer.h.
time
double quda::Timer::time
< The cumulative sum of time The last recorded time interval
Definition at line 44 of file timer.h.
Referenced by quda::TimeProfile::Print(), and quda::TimeProfile::PrintGlobal().
The documentation for this struct was generated from the following file:
include/timer.h