QUDA: quda::gauge::abs_< Float, int > Struct Template Reference
quda::gauge::abs_< Float, int > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
abs_ (const Float scale)
__host__ __device__ Float operator() (const quda::complex< int > &x)
Public Attributes
Float scale
Detailed Description
template<typename Float>
struct quda::gauge::abs_< Float, int >
Definition at line 211 of file gauge_field_order.h.
Constructor & Destructor Documentation
abs_()
template<typename Float > quda::gauge::abs_< Float, int >::abs_ (const Float scale) inline
Definition at line 213 of file gauge_field_order.h.
Member Function Documentation
operator()()
template<typename Float > __host__ __device__ Float quda::gauge::abs_< Float, int >::operator() (const quda::complex< int > & x) inline
Definition at line 214 of file gauge_field_order.h.
References quda::abs(), quda::complex< int >::imag(), and quda::complex< int >::real().
Member Data Documentation
scale
template<typename Float > Float quda::gauge::abs_< Float, int >::scale
Definition at line 212 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h