QUDA: quda::LaplaceApply< Float, nColor, recon > Struct Template Reference
quda::LaplaceApply< Float, nColor, recon > Struct Template Reference
Public Member Functions
LaplaceApply (ColorSpinorField &out, const ColorSpinorField &in, const GaugeField &U, int dir, double a, const ColorSpinorField &x, int parity, bool dagger, const int *comm_override, TimeProfile &profile)
Detailed Description
template<typename Float, int nColor, QudaReconstructType recon>
struct quda::LaplaceApply< Float, nColor, recon >
Definition at line 164 of file laplace.cu.
Constructor & Destructor Documentation
LaplaceApply()
template<typename Float , int nColor, QudaReconstructType recon> quda::LaplaceApply< Float, nColor, recon >::LaplaceApply (ColorSpinorField & out, const ColorSpinorField & in, const GaugeField & U, int dir, double a, const ColorSpinorField & x, int parity, bool dagger, const int * comm_override, TimeProfile & profile) inline
Definition at line 166 of file laplace.cu.
References quda::dslash::DslashPolicyTune< Dslash >::apply(), quda::arg(), checkCudaError, quda::ColorSpinorField::GhostFaceCB(), quda::laplace(), and quda::ColorSpinorField::VolumeCB().
The documentation for this struct was generated from the following file:
lib/laplace.cu