QUDA: quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc > Struct Template Reference
quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc > Struct Template Reference
#include <color_spinor_field_order.h>
Public Types
using Accessor = PaddedSpaceSpinorColorOrder< Float, Ns, Nc >
using real = typename mapper< Float >::type
using complex = complex< real >
Public Member Functions
PaddedSpaceSpinorColorOrder (const ColorSpinorField &a, int nFace=1, Float *field_=0, float *dummy=0, Float **ghost_=0)
__device__ __host__ int getPaddedIndex (int x_cb, int parity) const
Compute the index into the padded field. Assumes that parity doesn't change from unpadded to padded.
__device__ __host__ void load (complex v[length/2], int x, int parity=0) const
__device__ __host__ void save (const complex v[length/2], int x, int parity=0)
__device__ __host__ colorspinor_wrapper< real, Accessor > operator() (int x_cb, int parity)
This accessor routine returns a colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ const colorspinor_wrapper< real, Accessor > operator() (int x_cb, int parity) const
This accessor routine returns a const colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
__device__ __host__ void loadGhost (complex v[length/2], int x, int dim, int dir, int parity=0) const
__device__ __host__ void saveGhost (const complex v[length/2], int x, int dim, int dir, int parity=0)
size_t Bytes () const
Public Attributes
Float * field
size_t offset
Float * ghost [8]
int volumeCB
int exVolumeCB
int faceVolumeCB [4]
int stride
int nParity
int dim [4]
int exDim [4]
Static Public Attributes
static const int length = 2 * Ns * Nc
Detailed Description
template<typename Float, int Ns, int Nc>
struct quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >
Definition at line 1365 of file color_spinor_field_order.h.
Member Typedef Documentation
Accessor
template<typename Float, int Ns, int Nc> using quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::Accessor = PaddedSpaceSpinorColorOrder<Float, Ns, Nc>
Definition at line 1366 of file color_spinor_field_order.h.
complex
template<typename Float, int Ns, int Nc> using quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::complex = complex<real>
Definition at line 1368 of file color_spinor_field_order.h.
real
template<typename Float, int Ns, int Nc> using quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::real = typename mapper<Float>::type
Definition at line 1367 of file color_spinor_field_order.h.
Constructor & Destructor Documentation
PaddedSpaceSpinorColorOrder()
template<typename Float, int Ns, int Nc> quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::PaddedSpaceSpinorColorOrder (const ColorSpinorField & a, int nFace = 1, Float * field_ = 0, float * dummy = 0, Float ** ghost_ = 0) inline
Definition at line 1380 of file color_spinor_field_order.h.
References errorQuda, and quda::ColorSpinorField::X().
Member Function Documentation
Bytes()
template<typename Float, int Ns, int Nc> size_t quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::Bytes () const inline
Definition at line 1507 of file color_spinor_field_order.h.
getPaddedIndex()
template<typename Float, int Ns, int Nc> __device__ __host__ int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::getPaddedIndex (int x_cb, int parity) const inline
Compute the index into the padded field. Assumes that parity doesn't change from unpadded to padded.
Definition at line 1403 of file color_spinor_field_order.h.
References quda::getCoords(), and quda::linkIndex().
load()
template<typename Float, int Ns, int Nc> __device__ __host__ void quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::load (complex v[length/2], int x, int parity = 0) const inline
Definition at line 1413 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::s.
loadGhost()
template<typename Float, int Ns, int Nc> __device__ __host__ void quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::loadGhost (complex v[length/2], int x, int dim, int dir, int parity = 0) const inline
Definition at line 1487 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::s.
operator()() [1/2]
template<typename Float, int Ns, int Nc> __device__ __host__ colorspinor_wrapper<real, Accessor> quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::operator() (int x_cb, int parity) inline
This accessor routine returns a colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_wrapper that curries in access to this field at the above coordinates.
Definition at line 1468 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::colorspinor_wrapper< Float, T >::x_cb.
operator()() [2/2]
template<typename Float, int Ns, int Nc> __device__ __host__ const colorspinor_wrapper<real, Accessor> quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::operator() (int x_cb, int parity) const inline
This accessor routine returns a const colorspinor_wrapper to this object, allowing us to overload various operators for manipulating at the site level interms of matrix operations.
Parameters
[in] x_cb Checkerboarded space-time index we are requesting
[in] parity Parity we are requesting
Returns
Instance of a colorspinor_wrapper that curries in access to this field at the above coordinates.
Definition at line 1482 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::colorspinor_wrapper< Float, T >::x_cb.
save()
template<typename Float, int Ns, int Nc> __device__ __host__ void quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::save (const complex v[length/2], int x, int parity = 0) inline
Definition at line 1434 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::s.
saveGhost()
template<typename Float, int Ns, int Nc> __device__ __host__ void quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::saveGhost (const complex v[length/2], int x, int dim, int dir, int parity = 0) inline
Definition at line 1497 of file color_spinor_field_order.h.
References quda::colorspinor_wrapper< Float, T >::parity, and quda::s.
Member Data Documentation
dim
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::dim[4]
Definition at line 1378 of file color_spinor_field_order.h.
exDim
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::exDim[4]
Definition at line 1379 of file color_spinor_field_order.h.
exVolumeCB
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::exVolumeCB
Definition at line 1374 of file color_spinor_field_order.h.
faceVolumeCB
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::faceVolumeCB[4]
Definition at line 1375 of file color_spinor_field_order.h.
field
template<typename Float, int Ns, int Nc> Float* quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::field
Definition at line 1370 of file color_spinor_field_order.h.
ghost
template<typename Float, int Ns, int Nc> Float* quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::ghost[8]
Definition at line 1372 of file color_spinor_field_order.h.
length
template<typename Float, int Ns, int Nc> const int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::length = 2 * Ns * Nc static
Definition at line 1369 of file color_spinor_field_order.h.
nParity
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::nParity
Definition at line 1377 of file color_spinor_field_order.h.
offset
template<typename Float, int Ns, int Nc> size_t quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::offset
Definition at line 1371 of file color_spinor_field_order.h.
stride
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::stride
Definition at line 1376 of file color_spinor_field_order.h.
volumeCB
template<typename Float, int Ns, int Nc> int quda::colorspinor::PaddedSpaceSpinorColorOrder< Float, Ns, Nc >::volumeCB
Definition at line 1373 of file color_spinor_field_order.h.
The documentation for this struct was generated from the following file:
include/color_spinor_field_order.h