QUDA: quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs > Struct Template Reference
quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs > Struct Template Reference
Public Member Functions
GaugeSTOUTArg (GaugeOr &origin, GaugeDs &dest, const GaugeField &data, const Float rho, const Float tolerance)
Public Attributes
int threads
int X [4]
int border [4]
GaugeOr origin
const Float rho
const Float tolerance
GaugeDs dest
Detailed Description
template<typename Float, typename GaugeOr, typename GaugeDs>
struct quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >
Definition at line 9 of file gauge_stout.cuh.
Constructor & Destructor Documentation
GaugeSTOUTArg()
template<typename Float , typename GaugeOr , typename GaugeDs > quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::GaugeSTOUTArg (GaugeOr & origin, GaugeDs & dest, const GaugeField & data, const Float rho, const Float tolerance) inline
Definition at line 19 of file gauge_stout.cuh.
References quda::arg(), quda::computeStaple(), quda::conj(), quda::getCoords(), quda::linkIndexShift(), mu, parity, quda::LatticeField::R(), quda::setZero(), quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::X, and quda::LatticeField::X().
Member Data Documentation
border
template<typename Float , typename GaugeOr , typename GaugeDs > int quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::border[4]
Definition at line 12 of file gauge_stout.cuh.
dest
template<typename Float , typename GaugeOr , typename GaugeDs > GaugeDs quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::dest
Definition at line 17 of file gauge_stout.cuh.
origin
template<typename Float , typename GaugeOr , typename GaugeDs > GaugeOr quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::origin
Definition at line 13 of file gauge_stout.cuh.
rho
template<typename Float , typename GaugeOr , typename GaugeDs > const Float quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::rho
Definition at line 14 of file gauge_stout.cuh.
threads
template<typename Float , typename GaugeOr , typename GaugeDs > int quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::threads
Definition at line 10 of file gauge_stout.cuh.
tolerance
template<typename Float , typename GaugeOr , typename GaugeDs > const Float quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::tolerance
Definition at line 15 of file gauge_stout.cuh.
X
template<typename Float , typename GaugeOr , typename GaugeDs > int quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::X[4]
Definition at line 11 of file gauge_stout.cuh.
Referenced by quda::computeOvrImpSTOUTStep(), quda::computeStapleRectangle(), quda::computeSTOUTStep(), and quda::GaugeSTOUTArg< Float, GaugeOr, GaugeDs >::GaugeSTOUTArg().
The documentation for this struct was generated from the following file:
include/kernels/gauge_stout.cuh