QUDA: Locator< oddBit > Struct Template Reference
Locator< oddBit > Struct Template Reference
Public Member Functions
Locator (const int dim[4])
int getFullFromHalfIndex (int half_lattice_index)
int getNeighborFromFullIndex (int full_lattice_index, int dir, int *err=NULL)
Private Member Functions
void getCoordsFromHalfIndex (int half_index, int coord[4])
void getCoordsFromFullIndex (int full_index, int coord[4])
void cache (int half_lattice_index)
Private Attributes
int local_dim [4]
int volume
int half_index
int full_index
int full_coord [4]
Detailed Description
template<int oddBit>
struct Locator< oddBit >
Definition at line 571 of file hisq_force_reference2.cpp.
Constructor & Destructor Documentation
Locator()
template<int oddBit> Locator< oddBit >::Locator (const int dim[4])
Definition at line 592 of file hisq_force_reference2.cpp.
References Locator< oddBit >::local_dim, and Locator< oddBit >::volume.
Member Function Documentation
cache()
template<int oddBit> void Locator< oddBit >::cache (int half_lattice_index) private
Definition at line 664 of file hisq_force_reference2.cpp.
References Locator< oddBit >::full_coord, Locator< oddBit >::full_index, Locator< oddBit >::getCoordsFromHalfIndex(), and Locator< oddBit >::half_index.
Referenced by Locator< oddBit >::getFullFromHalfIndex().
getCoordsFromFullIndex()
template<int oddBit> void Locator< oddBit >::getCoordsFromFullIndex (int full_index, int coord[4]) private
Definition at line 635 of file hisq_force_reference2.cpp.
References Locator< oddBit >::local_dim.
Referenced by Locator< oddBit >::getNeighborFromFullIndex().
getCoordsFromHalfIndex()
template<int oddBit> void Locator< oddBit >::getCoordsFromHalfIndex (int half_index, int coord[4]) private
Definition at line 603 of file hisq_force_reference2.cpp.
References E1, E1h, E2, E3, and Locator< oddBit >::local_dim.
Referenced by Locator< oddBit >::cache().
getFullFromHalfIndex()
template<int oddBit> int Locator< oddBit >::getFullFromHalfIndex (int half_lattice_index)
Definition at line 674 of file hisq_force_reference2.cpp.
References Locator< oddBit >::cache(), Locator< oddBit >::full_index, and Locator< oddBit >::half_index.
Referenced by computeAllLinkSite(), computeLongLinkSite(), computeMiddleLinkSite(), and computeSideLinkSite().
getNeighborFromFullIndex()
template<int oddBit> int Locator< oddBit >::getNeighborFromFullIndex (int full_lattice_index, int dir, int * err = NULL)
Definition at line 682 of file hisq_force_reference2.cpp.
References E1, E2, E3, E4, errorQuda, Locator< oddBit >::getCoordsFromFullIndex(), and Locator< oddBit >::local_dim.
Referenced by computeAllLinkSite(), computeLongLinkSite(), computeMiddleLinkSite(), and computeSideLinkSite().
Member Data Documentation
full_coord
template<int oddBit> int Locator< oddBit >::full_coord[4] private
Definition at line 578 of file hisq_force_reference2.cpp.
Referenced by Locator< oddBit >::cache().
full_index
template<int oddBit> int Locator< oddBit >::full_index private
Definition at line 577 of file hisq_force_reference2.cpp.
Referenced by Locator< oddBit >::cache(), and Locator< oddBit >::getFullFromHalfIndex().
half_index
template<int oddBit> int Locator< oddBit >::half_index private
Definition at line 576 of file hisq_force_reference2.cpp.
Referenced by Locator< oddBit >::cache(), and Locator< oddBit >::getFullFromHalfIndex().
local_dim
template<int oddBit> int Locator< oddBit >::local_dim[4] private
Definition at line 574 of file hisq_force_reference2.cpp.
Referenced by Locator< oddBit >::getCoordsFromFullIndex(), Locator< oddBit >::getCoordsFromHalfIndex(), Locator< oddBit >::getNeighborFromFullIndex(), and Locator< oddBit >::Locator().
volume
template<int oddBit> int Locator< oddBit >::volume private
Definition at line 575 of file hisq_force_reference2.cpp.
Referenced by completeForceField(), computeAllLinkField(), computeLongLinkField(), computeMiddleLinkField(), computeOneLinkField(), computeSideLinkField(), hisqStaplesForceCPU(), and Locator< oddBit >::Locator().
The documentation for this struct was generated from the following file:
tests/hisq_force_reference2.cpp