QUDA: quda::gauge::square_< ReduceType, int > Struct Template Reference
quda::gauge::square_< ReduceType, int > Struct Template Reference
#include <gauge_field_order.h>
Public Member Functions
square_ (const ReduceType scale)
__host__ __device__ ReduceType operator() (const quda::complex< int > &x)
Public Attributes
const ReduceType scale
Detailed Description
template<typename ReduceType>
struct quda::gauge::square_< ReduceType, int >
Definition at line 185 of file gauge_field_order.h.
Constructor & Destructor Documentation
square_()
template<typename ReduceType > quda::gauge::square_< ReduceType, int >::square_ (const ReduceType scale) inline
Definition at line 187 of file gauge_field_order.h.
Member Function Documentation
operator()()
template<typename ReduceType > __host__ __device__ ReduceType quda::gauge::square_< ReduceType, int >::operator() (const quda::complex< int > & x) inline
Definition at line 188 of file gauge_field_order.h.
References quda::complex< int >::imag(), quda::norm(), and quda::complex< int >::real().
Member Data Documentation
scale
template<typename ReduceType > const ReduceType quda::gauge::square_< ReduceType, int >::scale
Definition at line 186 of file gauge_field_order.h.
The documentation for this struct was generated from the following file:
include/gauge_field_order.h