QUDA: tests/su3_test.cpp File Reference
su3_test.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <util_quda.h>
#include <test_util.h>
#include <dslash_util.h>
#include "misc.h"
#include <qio_field.h>
#include <quda.h>
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
Functions
void setGaugeParam (QudaGaugeParam &gauge_param)
void usage (char **)
void SU3test (int argc, char **argv)
int main (int argc, char **argv)
Variables
bool tune
int device
int xdim
int ydim
int zdim
int tdim
int gridsize_from_cmdline []
QudaReconstructType link_recon
QudaReconstructType link_recon_sloppy
QudaPrecision prec
QudaPrecision prec_sloppy
double anisotropy
bool verify_results
char latfile []
bool unit_gauge
QudaVerbosity verbosity
QudaPrecision cpu_prec = QUDA_DOUBLE_PRECISION
QudaPrecision & cuda_prec = prec
QudaPrecision & cuda_prec_sloppy = prec_sloppy
Macro Definition Documentation
MAX
#define MAX (a, b) ((a)>(b)?(a):(b))
Definition at line 43 of file su3_test.cpp.
Referenced by setGaugeParam().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 236 of file su3_test.cpp.
References SU3test().
setGaugeParam()
void setGaugeParam (QudaGaugeParam & gauge_param)
Definition at line 49 of file su3_test.cpp.
References anisotropy, QudaGaugeParam_s::anisotropy, cpu_prec, QudaGaugeParam_s::cpu_prec, cuda_prec, QudaGaugeParam_s::cuda_prec, cuda_prec_sloppy, QudaGaugeParam_s::cuda_prec_sloppy, QudaGaugeParam_s::ga_pad, QudaGaugeParam_s::gauge_fix, QudaGaugeParam_s::gauge_order, link_recon, link_recon_sloppy, MAX, QUDA_GAUGE_FIXED_NO, QUDA_PERIODIC_T, QUDA_QDP_GAUGE_ORDER, QUDA_WILSON_LINKS, QudaGaugeParam_s::reconstruct, QudaGaugeParam_s::reconstruct_sloppy, QudaGaugeParam_s::t_boundary, tdim, QudaGaugeParam_s::type, usage(), QudaGaugeParam_s::X, xdim, ydim, and zdim.
Referenced by SU3test().
SU3test()
void SU3test (int argc, char ** argv)
Definition at line 88 of file su3_test.cpp.
References check_gauge(), construct_gauge_field(), QudaGaugeParam_s::cpu_prec, device, endQuda(), epsilon, finalizeComms(), freeGaugeQuda(), gauge_param, gaugeSiteSize, gridsize_from_cmdline, gSize, initComms(), initQuda(), initRand(), latfile, link_recon, link_recon_sloppy, loadGaugeQuda(), newQudaGaugeParam(), performAPEnStep(), performOvrImpSTOUTnStep(), performSTOUTnStep(), plaqQuda(), prec, prec_sloppy, printfQuda, process_command_line_option(), qChargeDensityQuda(), qChargeQuda(), QUDA_DOUBLE_PRECISION, QUDA_INVALID_PRECISION, QUDA_RECONSTRUCT_INVALID, read_gauge_field(), saveGaugeQuda(), setDims(), setGaugeParam(), setVerbosity(), unit_gauge, usage(), V, verbosity, verify_results, and QudaGaugeParam_s::X.
Referenced by main().
usage()
void usage (char **)
Definition at line 1783 of file test_util.cpp.
Referenced by setGaugeParam(), and SU3test().
Variable Documentation
anisotropy
double anisotropy
Definition at line 1650 of file test_util.cpp.
Referenced by process_command_line_option(), and setGaugeParam().
cpu_prec
QudaPrecision cpu_prec = QUDA_DOUBLE_PRECISION
Definition at line 45 of file su3_test.cpp.
Referenced by setGaugeParam().
cuda_prec
QudaPrecision& cuda_prec = prec
Definition at line 46 of file su3_test.cpp.
Referenced by setGaugeParam().
cuda_prec_sloppy
QudaPrecision& cuda_prec_sloppy = prec_sloppy
Definition at line 47 of file su3_test.cpp.
Referenced by setGaugeParam().
device
int device
Definition at line 1602 of file test_util.cpp.
Referenced by SU3test().
gridsize_from_cmdline
int gridsize_from_cmdline[]
For MPI, the default node mapping is lexicographical with t varying fastest.
Definition at line 49 of file test_util.cpp.
Referenced by SU3test().
latfile
char latfile[]
Definition at line 1623 of file test_util.cpp.
Referenced by process_command_line_option(), and SU3test().
link_recon
QudaReconstructType link_recon
Definition at line 1605 of file test_util.cpp.
Referenced by setGaugeParam(), and SU3test().
link_recon_sloppy
QudaReconstructType link_recon_sloppy
Definition at line 1606 of file test_util.cpp.
Referenced by process_command_line_option(), setGaugeParam(), and SU3test().
prec
QudaPrecision prec
Definition at line 1608 of file test_util.cpp.
Referenced by SU3test().
prec_sloppy
QudaPrecision prec_sloppy
Definition at line 1609 of file test_util.cpp.
Referenced by process_command_line_option(), and SU3test().
tdim
int tdim
Definition at line 1618 of file test_util.cpp.
Referenced by setGaugeParam().
tune
bool tune
unit_gauge
bool unit_gauge
Definition at line 1624 of file test_util.cpp.
Referenced by process_command_line_option(), and SU3test().
verbosity
QudaVerbosity verbosity
Definition at line 1614 of file test_util.cpp.
Referenced by process_command_line_option(), and SU3test().
verify_results
bool verify_results
Definition at line 1643 of file test_util.cpp.
Referenced by SU3test().
xdim
int xdim
Definition at line 1615 of file test_util.cpp.
Referenced by setGaugeParam().
ydim
int ydim
Definition at line 1616 of file test_util.cpp.
Referenced by setGaugeParam().
zdim
int zdim
Definition at line 1617 of file test_util.cpp.
Referenced by setGaugeParam().