QUDA: tests/test_util.h File Reference
test_util.h File Reference
#include <quda.h>
#include <random_quda.h>
Macros
#define gaugeSiteSize 18
#define spinorSiteSize 24
#define cloverSiteSize 72
#define momSiteSize 10
#define hwSiteSize 12
Functions
void initComms (int argc, char **argv, int *const commDims)
void finalizeComms ()
void initRand ()
void setDims (int *X)
void dw_setDims (int *X, const int L5)
void setSpinorSiteSize (int n)
int dimPartitioned (int dim)
bool last_node_in_t ()
int neighborIndex (int i, int oddBit, int dx4, int dx3, int dx2, int dx1)
int neighborIndexFullLattice (int i, int dx4, int dx3, int dx2, int dx1)
int neighborIndex (int dim[], int index, int oddBit, int dx[])
int neighborIndexFullLattice (int dim[], int index, int dx[])
int neighborIndex_mg (int i, int oddBit, int dx4, int dx3, int dx2, int dx1)
int neighborIndexFullLattice_mg (int i, int dx4, int dx3, int dx2, int dx1)
void printSpinorElement (void *spinor, int X, QudaPrecision precision)
void printGaugeElement (void *gauge, int X, QudaPrecision precision)
int fullLatticeIndex (int i, int oddBit)
int fullLatticeIndex (int dim[], int index, int oddBit)
int getOddBit (int X)
void applyGaugeFieldScaling_long (void **gauge, int Vh, QudaGaugeParam *param, QudaDslashType dslash_type, QudaPrecision local_prec)
void construct_gauge_field (void **gauge, int type, QudaPrecision precision, QudaGaugeParam *param)
void construct_fat_long_gauge_field (void **fatlink, void **longlink, int type, QudaPrecision precision, QudaGaugeParam *, QudaDslashType dslash_type)
void construct_spinor_source (void *v, int nSpin, int nColor, QudaPrecision precision, const int *const x, quda::RNG &rng)
void construct_clover_field (void *clover, double norm, double diag, QudaPrecision precision)
void createSiteLinkCPU (void **link, QudaPrecision precision, int phase)
void su3_construct (void *mat, QudaReconstructType reconstruct, QudaPrecision precision)
void su3_reconstruct (void *mat, int dir, int ga_idx, QudaReconstructType reconstruct, QudaPrecision precision, QudaGaugeParam *param)
void compare_spinor (void *spinor_cpu, void *spinor_gpu, int len, QudaPrecision precision)
void strong_check (void *spinor, void *spinorGPU, int len, QudaPrecision precision)
int compare_floats (void *a, void *b, int len, double epsilon, QudaPrecision precision)
void check_gauge (void **, void **, double epsilon, QudaPrecision precision)
int strong_check_link (void **linkA, const char *msgA, void **linkB, const char *msgB, int len, QudaPrecision prec)
int strong_check_mom (void *momA, void *momB, int len, QudaPrecision prec)
void createMomCPU (void *mom, QudaPrecision precision)
void createHwCPU (void *hw, QudaPrecision precision)
int x4_from_full_index (int i)
int fullLatticeIndex_4d (int i, int oddBit)
int fullLatticeIndex_5d (int i, int oddBit)
int fullLatticeIndex_5d_4dpc (int i, int oddBit)
int process_command_line_option (int argc, char **argv, int *idx)
void stopwatchStart ()
double stopwatchReadSeconds ()
void exchange_cpu_sitelink (int *X, void **sitelink, void **ghost_sitelink, void **ghost_sitelink_diag, QudaPrecision gPrecision, QudaGaugeParam *param, int optflag)
void exchange_cpu_sitelink_ex (int *X, int *R, void **sitelink, QudaGaugeFieldOrder cpu_order, QudaPrecision gPrecision, int optflag, int geometry)
void exchange_cpu_staple (int *X, void *staple, void **ghost_staple, QudaPrecision gPrecision)
void exchange_llfat_init (QudaPrecision prec)
void exchange_llfat_cleanup (void)
QudaPrecision getPrecision (int i)
int getReconstructNibble (QudaReconstructType recon)
Variables
int Z [4]
int V
int Vh
int Vs_x
int Vs_y
int Vs_z
int Vs_t
int Vsh_x
int Vsh_y
int Vsh_z
int Vsh_t
int faceVolume [4]
int E1
int E1h
int E2
int E3
int E4
int E [4]
int V_ex
int Vh_ex
int Ls
int V5
int V5h
int mySpinorSiteSize
Macro Definition Documentation
cloverSiteSize
#define cloverSiteSize 72
Definition at line 9 of file test_util.h.
Referenced by init(), and main().
gaugeSiteSize
#define gaugeSiteSize 18
Definition at line 7 of file test_util.h.
hwSiteSize
#define hwSiteSize 12
Definition at line 11 of file test_util.h.
Referenced by createHwCPU(), and hisq_force_init().
momSiteSize
#define momSiteSize 10
Definition at line 10 of file test_util.h.
Referenced by compare_mom(), createMomCPU(), gauge_force_test(), hisq_force_test(), and printMomElement().
spinorSiteSize
#define spinorSiteSize 24
Definition at line 8 of file test_util.h.
Function Documentation
applyGaugeFieldScaling_long()
void applyGaugeFieldScaling_long (void ** gauge, int Vh, QudaGaugeParam * param, QudaDslashType dslash_type, QudaPrecision local_prec)
Definition at line 854 of file test_util.cpp.
References applyGaugeFieldScaling_long(), errorQuda, QUDA_DOUBLE_PRECISION, and QUDA_SINGLE_PRECISION.
check_gauge()
void check_gauge (void ** , void ** , double epsilon, QudaPrecision precision)
Definition at line 1220 of file test_util.cpp.
References checkGauge(), and QUDA_DOUBLE_PRECISION.
Referenced by SU3test().
compare_floats()
int compare_floats (void * a, void * b, int len, double epsilon, QudaPrecision precision)
Definition at line 434 of file test_util.cpp.
References compareFloats(), and QUDA_DOUBLE_PRECISION.
Referenced by gauge_force_test(), hisq_force_test(), hisq_test(), llfat_test(), and TEST().
compare_spinor()
void compare_spinor (void * spinor_cpu, void * spinor_gpu, int len, QudaPrecision precision)
construct_clover_field()
void construct_clover_field (void * clover, double norm, double diag, QudaPrecision precision)
Definition at line 1167 of file test_util.cpp.
References constructCloverField(), and QUDA_DOUBLE_PRECISION.
Referenced by init(), and main().
construct_fat_long_gauge_field()
void construct_fat_long_gauge_field (void ** fatlink, void ** longlink, int type, QudaPrecision precision, QudaGaugeParam * , QudaDslashType dslash_type)
Definition at line 1062 of file test_util.cpp.
References applyStaggeredScaling(), constructGaugeField(), constructUnitGaugeField(), gaugeSiteSize, quda::polar(), QUDA_ASQTAD_DSLASH, QUDA_ASQTAD_FAT_LINKS, QUDA_ASQTAD_LONG_LINKS, QUDA_DOUBLE_PRECISION, QUDA_STAGGERED_DSLASH, QudaGaugeParam_s::type, and V.
Referenced by eigensolve_test(), init(), and invert_test().
construct_gauge_field()
void construct_gauge_field (void ** gauge, int type, QudaPrecision precision, QudaGaugeParam * param)
Definition at line 1047 of file test_util.cpp.
References applyGaugeFieldScaling(), constructGaugeField(), constructUnitGaugeField(), QUDA_DOUBLE_PRECISION, and Vh.
Referenced by eigensolve_test(), init(), invert_test(), main(), plaq_test(), and SU3test().
construct_spinor_source()
void construct_spinor_source (void * v, int nSpin, int nColor, QudaPrecision precision, const int *const x, quda::RNG & rng)
Create random spinor source field using QUDA's internal hypercubic GPU RNG
Definition at line 1342 of file test_util.cpp.
References quda::ColorSpinorParam::create, quda::ColorSpinorParam::fieldOrder, nColor, quda::ColorSpinorParam::nColor, quda::LatticeFieldParam::nDim, quda::ColorSpinorParam::nSpin, param, QUDA_EVEN_ODD_SITE_ORDER, QUDA_FULL_SITE_SUBSET, QUDA_NOISE_UNIFORM, QUDA_REFERENCE_FIELD_CREATE, QUDA_SPACE_SPIN_COLOR_FIELD_ORDER, quda::ColorSpinorParam::setPrecision(), quda::ColorSpinorParam::siteOrder, quda::LatticeFieldParam::siteSubset, quda::spinorNoise(), quda::ColorSpinorParam::v, and quda::LatticeFieldParam::x.
Referenced by invert_test(), and main().
createHwCPU()
void createHwCPU (void * hw, QudaPrecision precision)
Definition at line 1487 of file test_util.cpp.
References hwSiteSize, QUDA_DOUBLE_PRECISION, and V.
Referenced by hisq_force_init().
createMomCPU()
void createMomCPU (void * mom, QudaPrecision precision)
Definition at line 1451 of file test_util.cpp.
References gaugeSiteSize, gSize, momSiteSize, QUDA_DOUBLE_PRECISION, and V.
Referenced by gauge_force_test().
createSiteLinkCPU()
void createSiteLinkCPU (void ** link, QudaPrecision precision, int phase)
Definition at line 1227 of file test_util.cpp.
References constructUnitaryGaugeField(), fullLatticeIndex(), gaugeSiteSize, last_node_in_t(), QUDA_DOUBLE_PRECISION, QUDA_SINGLE_PRECISION, TUP, V, Vh, X1, X2, X3, X4, XUP, YUP, Z, and ZUP.
Referenced by createNoisyLinkCPU(), gauge_force_test(), hisq_force_init(), hisq_test(), llfat_test(), and unitarize_link_test().
dimPartitioned()
int dimPartitioned (int dim)
Definition at line 1776 of file test_util.cpp.
References dim_partitioned, and gridsize_from_cmdline.
Referenced by display_test_info().
dw_setDims()
void dw_setDims (int * X, const int L5)
Definition at line 187 of file test_util.cpp.
References faceVolume, Ls, V, V5, V5h, Vh, Vs_t, Vsh_t, and Z.
Referenced by eigensolve_test(), init(), invert_test(), and main().
exchange_cpu_sitelink()
void exchange_cpu_sitelink (int * X, void ** sitelink, void ** ghost_sitelink, void ** ghost_sitelink_diag, QudaPrecision gPrecision, QudaGaugeParam * param, int optflag)
Definition at line 512 of file face_gauge.cpp.
References exchange_sitelink(), gaugeSiteSize, host_free, memset(), QUDA_DOUBLE_PRECISION, safe_malloc, setup_dims(), and Vs.
Referenced by computeHISQLinksCPU(), and llfat_test().
exchange_cpu_sitelink_ex()
void exchange_cpu_sitelink_ex (int * X, int * R, void ** sitelink, QudaGaugeFieldOrder cpu_order, QudaPrecision gPrecision, int optflag, int geometry)
Definition at line 644 of file face_gauge.cpp.
References comm_declare_receive_relative, comm_declare_send_relative, comm_free(), comm_start(), comm_wait(), quda::commDim, commDimPartitioned(), E, gaugeSiteSize, host_free, MEMCOPY_GAUGE_FIELDS_BUF_TO_GRID, MEMCOPY_GAUGE_FIELDS_BUF_TO_GRID_T, MEMCOPY_GAUGE_FIELDS_GRID_TO_BUF, safe_malloc, and Vh_ex.
Referenced by computeHISQLinksCPU(), gauge_force_test(), and llfat_test().
exchange_cpu_staple()
void exchange_cpu_staple (int * X, void * staple, void ** ghost_staple, QudaPrecision gPrecision)
Definition at line 980 of file face_gauge.cpp.
References do_exchange_cpu_staple(), gaugeSiteSize, host_free, QUDA_DOUBLE_PRECISION, safe_malloc, setup_dims(), Vs, Vs_t, Vs_x, Vs_y, and Vs_z.
Referenced by llfat_reference().
exchange_llfat_cleanup()
void exchange_llfat_cleanup (void)
Definition at line 1007 of file face_gauge.cpp.
References back_nbr_staple, back_nbr_staple_sendbuf, checkCudaError, fwd_nbr_staple, fwd_nbr_staple_sendbuf, and host_free.
Referenced by hisq_test(), llfat_test(), and unitarize_link_test().
exchange_llfat_init()
void exchange_llfat_init (QudaPrecision prec)
Definition at line 373 of file face_gauge.cpp.
References back_nbr_staple, back_nbr_staple_sendbuf, fwd_nbr_staple, fwd_nbr_staple_sendbuf, gaugeSiteSize, initialized, pinned_malloc, prec, and Vs.
finalizeComms()
void finalizeComms ()
Definition at line 128 of file test_util.cpp.
Referenced by main(), plaq_test(), and SU3test().
fullLatticeIndex() [1/2]
int fullLatticeIndex (int i, int oddBit)
Definition at line 452 of file test_util.cpp.
References X, X1, X2, X3, and Z.
fullLatticeIndex() [2/2]
int fullLatticeIndex (int dim[], int index, int oddBit)
fullLatticeIndex_4d()
int fullLatticeIndex_4d (int i, int oddBit)
Definition at line 648 of file test_util.cpp.
References Vh, X, X1, X2, X3, and Z.
Referenced by neighborIndex_4d().
fullLatticeIndex_5d()
int fullLatticeIndex_5d (int i, int oddBit)
Definition at line 682 of file test_util.cpp.
References Z.
Referenced by dslashReference_5th(), neighborIndex_5d(), and spinorNeighbor_5d().
fullLatticeIndex_5d_4dpc()
int fullLatticeIndex_5d_4dpc (int i, int oddBit)
Definition at line 687 of file test_util.cpp.
References Z.
Referenced by dslashReference_5th(), neighborIndex_5d(), and spinorNeighbor_5d().
getOddBit()
int getOddBit (int X)
Definition at line 247 of file test_util.cpp.
References Z.
Referenced by printGaugeElement().
getPrecision()
QudaPrecision getPrecision (int i) inline
Definition at line 129 of file test_util.h.
References QUDA_DOUBLE_PRECISION, QUDA_HALF_PRECISION, QUDA_INVALID_PRECISION, QUDA_QUARTER_PRECISION, and QUDA_SINGLE_PRECISION.
Referenced by display_test_info(), init(), StaggeredDslashTest::skip(), DslashTest::skip(), and skip_kernel().
getReconstructNibble()
int getReconstructNibble (QudaReconstructType recon) inline
Definition at line 140 of file test_util.h.
References QUDA_RECONSTRUCT_12, QUDA_RECONSTRUCT_13, QUDA_RECONSTRUCT_8, QUDA_RECONSTRUCT_9, and QUDA_RECONSTRUCT_NO.
Referenced by StaggeredDslashTest::skip(), and DslashTest::skip().
initComms()
void initComms (int argc, char ** argv, int *const commDims)
Definition at line 88 of file test_util.cpp.
References get_gridsize_from_env(), initCommsGridQuda(), initRand(), lex_rank_from_coords_t(), lex_rank_from_coords_x(), MPI_Init(), printfQuda, and rank_order.
Referenced by main(), plaq_test(), and SU3test().
initRand()
void initRand ()
Definition at line 138 of file test_util.cpp.
References rank.
Referenced by initComms(), main(), plaq_test(), and SU3test().
last_node_in_t()
bool last_node_in_t ()
Definition at line 118 of file test_util.cpp.
References commCoords(), and quda::commDim.
Referenced by applyGaugeFieldScaling(), applyGaugeFieldScaling_long(), createSiteLinkCPU(), and site_link_sanity_check_internal_12().
neighborIndex() [1/2]
int neighborIndex (int i, int oddBit, int dx4, int dx3, int dx2, int dx1)
Definition at line 488 of file test_util.cpp.
References fullLatticeIndex(), and Z.
Referenced by neighborIndexFullLattice().
neighborIndex() [2/2]
int neighborIndex (int dim[], int index, int oddBit, int dx[])
neighborIndex_mg()
int neighborIndex_mg (int i, int oddBit, int dx4, int dx3, int dx2, int dx1)
Definition at line 523 of file test_util.cpp.
References comm_dim_partitioned(), fullLatticeIndex(), and Z.
Referenced by spinorNeighbor_5d().
neighborIndexFullLattice() [1/2]
int neighborIndexFullLattice (int i, int dx4, int dx3, int dx2, int dx1)
Definition at line 556 of file test_util.cpp.
References neighborIndex(), and Vh.
neighborIndexFullLattice() [2/2]
int neighborIndexFullLattice (int dim[], int index, int dx[])
neighborIndexFullLattice_mg()
int neighborIndexFullLattice_mg (int i, int dx4, int dx3, int dx2, int dx1)
Definition at line 601 of file test_util.cpp.
References fullLatticeIndex(), Vh, and Z.
Referenced by llfat_reference().
printGaugeElement()
void printGaugeElement (void * gauge, int X, QudaPrecision precision)
Definition at line 231 of file test_util.cpp.
References gaugeSiteSize, getOddBit(), printVector(), QUDA_DOUBLE_PRECISION, and Vh.
printSpinorElement()
void printSpinorElement (void * spinor, int X, QudaPrecision precision)
Definition at line 223 of file test_util.cpp.
References printVector(), QUDA_DOUBLE_PRECISION, and quda::s.
Referenced by dslashReference_4d_sgpu().
process_command_line_option()
int process_command_line_option (int argc, char ** argv, int * idx)
Definition at line 2019 of file test_util.cpp.
References alternative_reliable, anisotropy, ca_basis, ca_lambda_max, ca_lambda_min, clover_coeff, coarse_solve_type, coarse_solver, coarse_solver_ca_basis, coarse_solver_ca_basis_size, coarse_solver_ca_lambda_max, coarse_solver_ca_lambda_min, coarse_solver_maxiter, coarse_solver_tol, commDimPartitionedSet(), compute_clover, compute_fatlong, contract_type, dagger, deflation_ext_lib, deflation_grid, device, dim_partitioned, dslash_type, eig_amax, eig_amin, eig_arpack_check, eig_arpack_logfile, eig_check_interval, eig_compute_svd, eig_max_restarts, eig_nConv, eig_nEv, eig_nKr, eig_poly_deg, eig_QUDA_logfile, eig_require_convergence, eig_spectrum, eig_tol, eig_type, eig_use_dagger, eig_use_normop, eig_use_poly_acc, eig_vec_infile, eig_vec_outfile, eigcg_max_restarts, eigenval_tol, eps_naik, epsilon, gauge_outfile, gaussian_sigma, gcrNkrylov, generate_all_levels, generate_nullspace, geo_block_size, get_contract_type(), get_df_mem_type_ritz(), get_dslash_type(), get_eig_spectrum_type(), get_eig_type(), get_flavor_type(), get_location(), get_mass_normalization_type(), get_matpc_type(), get_prec(), get_quda_ver_str(), get_rank_order(), get_recon(), get_schwarz_type(), get_solution_type(), get_solve_ext_lib_type(), get_solve_type(), get_solver_type(), get_verbosity_type(), gridsize_from_cmdline, heatbath_beta_value, heatbath_coldstart, heatbath_num_heatbath_per_step, heatbath_num_overrelax_per_step, heatbath_num_steps, heatbath_warmup_steps, inc_tol, inv_type, kappa, laplace3D, latfile, link_recon, link_recon_precondition, link_recon_sloppy, location_ritz, low_mode_check, Ls, Lsdim, mass, matpc_type, max_restart_num, max_search_dim, mem_type_ritz, mg_eig, mg_eig_amax, mg_eig_amin, mg_eig_check_interval, mg_eig_max_restarts, mg_eig_nEv, mg_eig_nKr, mg_eig_poly_deg, mg_eig_require_convergence, mg_eig_spectrum, mg_eig_tol, mg_eig_type, mg_eig_use_dagger, mg_eig_use_normop, mg_eig_use_poly_acc, mg_levels, mg_vec_infile, mg_vec_outfile, mg_verbosity, Msrc, mu, mu_factor, multishift, n_block_ortho, nev, niter, normalization, Nsrc, nu_post, nu_pre, num_setup_iter, nvec, oblique_proj_check, omega, out, pipeline, post_orthonormalize, pre_orthonormalize, prec, prec_null, prec_precondition, prec_refinement_sloppy, prec_ritz, prec_sloppy, precon_type, printfQuda, QUDA_CHEBYSHEV_BASIS, QUDA_DAG_YES, QUDA_MAX_MG_LEVEL, QUDA_NULL_VECTOR_SETUP, QUDA_POWER_BASIS, QUDA_TEST_VECTOR_SETUP, rank_order, reliable_delta, schwarz_cycle, schwarz_type, setup_ca_basis, setup_ca_basis_size, setup_ca_lambda_max, setup_ca_lambda_min, setup_inv, setup_location, setup_maxiter, setup_maxiter_refresh, setup_tol, setup_type, smoother_halo_prec, smoother_solve_type, smoother_tol, smoother_type, solution_accumulator_pipeline, solution_type, solve_type, solver_ext_lib, solver_location, tadpole_factor, tdim, test_type, tol, tol_hq, tol_restart, twist_flavor, unit_gauge, usage(), verbosity, verify_results, xdim, ydim, and zdim.
Referenced by main(), plaq_test(), and SU3test().
setDims()
void setDims (int * X)
Definition at line 151 of file test_util.cpp.
References E, E1, E1h, E2, E3, E4, faceVolume, V, V_ex, Vh, Vh_ex, Vs_t, Vs_x, Vs_y, Vs_z, Vsh_t, Vsh_x, Vsh_y, Vsh_z, and Z.
setSpinorSiteSize()
void setSpinorSiteSize (int n)
Definition at line 211 of file test_util.cpp.
References mySpinorSiteSize.
Referenced by eigensolve_test(), init(), invert_test(), and main().
stopwatchReadSeconds()
double stopwatchReadSeconds ()
Definition at line 4423 of file test_util.cpp.
References startTime.
Referenced by packTest().
stopwatchStart()
void stopwatchStart ()
Definition at line 4419 of file test_util.cpp.
References startTime.
Referenced by packTest().
strong_check()
void strong_check (void * spinor, void * spinorGPU, int len, QudaPrecision precision)
strong_check_link()
int strong_check_link (void ** linkA, const char * msgA, void ** linkB, const char * msgB, int len, QudaPrecision prec)
Definition at line 1429 of file test_util.cpp.
References compare_link(), printfQuda, and printLinkElement().
Referenced by hisq_test(), and llfat_test().
strong_check_mom()
int strong_check_mom (void * momA, void * momB, int len, QudaPrecision prec)
Definition at line 1559 of file test_util.cpp.
References compare_mom(), device, printfQuda, printMomElement(), and QUDA_DOUBLE_PRECISION.
Referenced by gauge_force_test(), and hisq_force_test().
su3_construct()
void su3_construct (void * mat, QudaReconstructType reconstruct, QudaPrecision precision)
Definition at line 322 of file test_util.cpp.
References QUDA_DOUBLE_PRECISION, QUDA_RECONSTRUCT_12, su3Construct12(), and su3Construct8().
su3_reconstruct()
void su3_reconstruct (void * mat, int dir, int ga_idx, QudaReconstructType reconstruct, QudaPrecision precision, QudaGaugeParam * param)
Definition at line 412 of file test_util.cpp.
References QUDA_DOUBLE_PRECISION, QUDA_RECONSTRUCT_12, su3Reconstruct12(), and su3Reconstruct8().
x4_from_full_index()
int x4_from_full_index (int i)
Definition at line 692 of file test_util.cpp.
References fullLatticeIndex(), Vh, and Z.
Variable Documentation
E
int E[4]
Definition at line 35 of file test_util.cpp.
Referenced by setDims().
E1
int E1
Definition at line 34 of file test_util.cpp.
Referenced by Locator< oddBit >::getCoordsFromHalfIndex(), Locator< oddBit >::getNeighborFromFullIndex(), LoadStore< Real >::half_idx_conversion_ex2normal(), LoadStore< Real >::half_idx_conversion_normal2ex(), and setDims().
E1h
int E1h
Definition at line 34 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), gauge_force_test(), Locator< oddBit >::getCoordsFromHalfIndex(), LoadStore< Real >::half_idx_conversion_ex2normal(), llfat_test(), and setDims().
E2
int E2
Definition at line 34 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), gauge_force_test(), Locator< oddBit >::getCoordsFromHalfIndex(), Locator< oddBit >::getNeighborFromFullIndex(), LoadStore< Real >::half_idx_conversion_ex2normal(), LoadStore< Real >::half_idx_conversion_normal2ex(), llfat_test(), and setDims().
E3
int E3
Definition at line 34 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), gauge_force_test(), Locator< oddBit >::getCoordsFromHalfIndex(), Locator< oddBit >::getNeighborFromFullIndex(), LoadStore< Real >::half_idx_conversion_ex2normal(), LoadStore< Real >::half_idx_conversion_normal2ex(), llfat_test(), and setDims().
E4
int E4
Definition at line 34 of file test_util.cpp.
Referenced by Locator< oddBit >::getNeighborFromFullIndex(), and setDims().
faceVolume
int faceVolume[4]
Definition at line 31 of file test_util.cpp.
Referenced by dslashReference(), dslashReference_4d_sgpu(), dw_setDims(), matdagmat(), and setDims().
Ls
int Ls
Definition at line 38 of file test_util.cpp.
Referenced by quda::Dslash5< Float, nColor, Arg >::bytes(), quda::cpuColorSpinorField::create(), quda::Dslash5Arg< Float, nColor >::Dslash5Arg(), dslash_4_4d(), dslashRef(), dslashReference_4d_sgpu(), dslashReference_5th(), dslashReference_5th_inv(), dw_4d_matpc(), dw_dslash(), dw_setDims(), quda::Dslash5< Float, nColor, Arg >::flops(), quda::DomainWall5D< Float, nDim, nColor, Arg >::flops(), quda::getCoords(), init(), mdslashReference_5th_inv(), mdw_dslash_4_pre(), mdw_dslash_5(), mdw_mat(), mdw_matpc(), neighborIndex_5d(), printQudaInvertParam(), process_command_line_option(), and spinorNeighbor_5d().
mySpinorSiteSize
int mySpinorSiteSize
Definition at line 42 of file test_util.cpp.
Referenced by setSpinorSiteSize().
V
int V
Definition at line 27 of file test_util.cpp.
Referenced by applyGaugeFieldScaling_long(), checkGauge(), construct_fat_long_gauge_field(), constructCloverField(), createHwCPU(), createMomCPU(), createSiteLinkCPU(), dw_setDims(), and setDims().
V5
int V5
Definition at line 39 of file test_util.cpp.
Referenced by dw_4d_mat(), dw_mat(), dw_matdagmat(), and dw_setDims().
V5h
int V5h
Definition at line 40 of file test_util.cpp.
Referenced by dslashReference_4d_sgpu(), dslashReference_5th(), dw_4d_mat(), dw_4d_matpc(), dw_mat(), dw_matpc(), dw_setDims(), mdw_mat(), and mdw_matpc().
V_ex
int V_ex
Definition at line 36 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), gauge_force_test(), llfat_test(), and setDims().
Vh
int Vh
Definition at line 28 of file test_util.cpp.
Referenced by applyGaugeFieldScaling(), applyGaugeFieldScaling_long(), applyStaggeredScaling(), checkGauge(), construct_gauge_field(), constructGaugeField(), constructUnitaryGaugeField(), constructUnitGaugeField(), createSiteLinkCPU(), dw_setDims(), fullLatticeIndex_4d(), neighborIndexFullLattice(), neighborIndexFullLattice_mg(), printGaugeElement(), setDims(), and x4_from_full_index().
Vh_ex
int Vh_ex
Definition at line 36 of file test_util.cpp.
Referenced by setDims().
Vs_t
int Vs_t
Definition at line 29 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), dw_setDims(), exchange_cpu_staple(), llfat_reference(), llfat_test(), setDims(), and setup_dims().
Vs_x
int Vs_x
Definition at line 29 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), exchange_cpu_staple(), llfat_reference(), llfat_test(), setDims(), and setup_dims().
Vs_y
int Vs_y
Definition at line 29 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), exchange_cpu_staple(), llfat_reference(), llfat_test(), setDims(), and setup_dims().
Vs_z
int Vs_z
Definition at line 29 of file test_util.cpp.
Referenced by computeHISQLinksCPU(), exchange_cpu_staple(), llfat_reference(), llfat_test(), setDims(), and setup_dims().
Vsh_t
int Vsh_t
Definition at line 30 of file test_util.cpp.
Referenced by do_exchange_cpu_staple(), dw_setDims(), llfat_reference(), setDims(), setup_dims(), and spinorNeighbor_5d().
Vsh_x
int Vsh_x
Definition at line 30 of file test_util.cpp.
Referenced by do_exchange_cpu_staple(), llfat_reference(), setDims(), and setup_dims().
Vsh_y
int Vsh_y
Definition at line 30 of file test_util.cpp.
Referenced by do_exchange_cpu_staple(), llfat_reference(), setDims(), and setup_dims().
Vsh_z
int Vsh_z
Definition at line 30 of file test_util.cpp.
Referenced by do_exchange_cpu_staple(), llfat_reference(), setDims(), and setup_dims().
Z
int Z[4]
Definition at line 26 of file test_util.cpp.
Referenced by applyGaugeFieldScaling(), createSiteLinkCPU(), dw_setDims(), fullLatticeIndex(), fullLatticeIndex_4d(), fullLatticeIndex_5d(), fullLatticeIndex_5d_4dpc(), getOddBit(), neighborIndex(), neighborIndex_mg(), neighborIndexFullLattice_mg(), setDims(), su3Reconstruct12(), su3Reconstruct8(), and x4_from_full_index().